import {
  CHURCHILL_NIGHT_CHANGES_STORY_VERSION,
  assertChurchillNightStoryIntegrity,
} from "@/lib/creative/concepts/ChurchillNightChangesStoryContract";

const ASSET = Object.freeze({
  exact_logo: "f2e57100-1b78-43c9-b080-1c7945fc4d23",
  pool_real: "797c9d16-5465-4e60-be93-a6c65707f7db",
  pool_video_real: "d10ddc3a-386f-403b-9bb4-2cfe40c7c655",
  shuffleboard_real: "4357898f-23fd-418f-af8d-89e3719c0969",
  pool_electronic_darts_real: "7bc9e891-e3d0-4b03-8b53-95ff255f31c6",
  singer_real: "370a3030-8656-4b28-934f-6653d5eaf3c8",
  band_real: "cb027610-625c-4751-99a0-6a41b3597237",
  stage_video_real: "dcd86649-42f8-4f7a-be91-00c456eb940d",
  dinner_real: "8b4854e6-8c9c-4fc6-a3f5-7eaadc1d8d8b",
  dining_video_real: "fb7e06e3-77cb-49f3-9f11-9fa59887b6be",
  carpaccio_real: "e767ad1c-e9ba-4bc3-aebc-525e963a8c78",
});

const PLAN = Object.freeze({
  ice_time_freeze: Object.freeze({
    story_seconds: 8,
    method: "APPROVED_ICE_PHYSICS_TO_AUTHENTIC_POOL_EDITORIAL_COMPOSITE",
    preserve: ["approved ice/time-freeze opening", "suspended liquid/ice physics"],
    authentic_landings: [ASSET.pool_real, ASSET.pool_video_real],
    forbidden: ["green pool felt", "generic pool room", "generated Churchill replacement"],
    final_action: "ice refraction/cube highlight wipes into authentic orange Churchill pool/cue-ball action",
    approval_required: true,
  }),
  pool_to_shuffleboard: Object.freeze({
    story_seconds: 5,
    method: "APPROVED_R1_SHUFFLEBOARD_MOTION_WITH_AUTHENTIC_ENDPOINTS",
    authentic_sources: [ASSET.pool_real, ASSET.shuffleboard_real],
    rules: ["orange Churchill pool endpoint", "real 1-2-3 shuffleboard geometry", "no stylized black/gold table"],
    approval_required: false,
  }),
  shuffleboard_to_dart: Object.freeze({
    story_seconds: 4,
    method: "EDITORIAL_OCCLUSION_MATCH_CUT_NOT_AI_MORPH",
    authentic_sources: [ASSET.shuffleboard_real, ASSET.pool_electronic_darts_real],
    generated_plate_role: "motion-only if visually approved",
    cut: "real puck crosses/fills lens -> dark occlusion -> dart appears after cut",
    forbidden: ["puck morphing visibly into dart", "room redesign", "cartoon transformation"],
    approval_required: true,
  }),
  electric_dart_flight: Object.freeze({
    story_seconds: 7,
    method: "SHORT_AUTHENTIC_CHURCHILL_PLATES_PLUS_DART_ACTION",
    authentic_sources: [ASSET.pool_electronic_darts_real],
    structure: ["dart entry", "middle-depth crossing", "electronic target impact"],
    camera: "nearly fixed / restrained telephoto; dart supplies speed",
    forbidden: ["AI fly-through room", "traditional dartboard", "neon trail", "geometry drift"],
    approval_required: true,
  }),
  frozen_night_hero: Object.freeze({
    story_seconds: 7,
    method: "AUTHENTIC_MULTI_LAYER_TIME_FREEZE_COMPOSITE",
    authentic_sources: [
      ASSET.singer_real,
      ASSET.band_real,
      ASSET.stage_video_real,
      ASSET.dinner_real,
      ASSET.dining_video_real,
      ASSET.carpaccio_real,
      ASSET.pool_real,
      ASSET.pool_video_real,
      ASSET.shuffleboard_real,
      ASSET.pool_electronic_darts_real,
    ],
    composition: [
      "real singer/band frozen mid-performance",
      "real guests/dinner frozen mid-action",
      "wine/cocktail liquid suspended",
      "orange Churchill pool ball frozen",
      "real shuffleboard puck frozen",
      "real electronic dart action frozen",
      "one red-wine droplet remains moving and contains Churchill reality",
    ],
    camera: "single coherent premium move through composited authentic layers; readable geography before spectacle",
    forbidden: ["whole venue generated by AI", "generated people", "generic restaurant", "unclear abstract montage"],
    approval_required: true,
  }),
  wine_loop_return: Object.freeze({
    story_seconds: 4,
    method: "REFLECTION_LOOP_PAYOFF",
    authentic_sources: [ASSET.dinner_real, ASSET.dining_video_real],
    action: "exit moving wine droplet/reflection into authentic dinner; guest completes natural glass movement; reflection echoes opening",
    forbidden: ["static dinner still only", "new story beat", "software UI"],
    approval_required: true,
  }),
});

export function churchillV3CompositePlan() {
  assertChurchillNightStoryIntegrity();
  return {
    version: "CHURCHILL_V3_COMPOSITE_R1_AUTHENTIC",
    canonical_story_version: CHURCHILL_NIGHT_CHANGES_STORY_VERSION,
    asset_truth: ASSET,
    beats: PLAN,
    story_change_authorized: false,
    master_render_authorized: false,
    publication_authorized: false,
  };
}

export const CHURCHILL_V3_COMPOSITE_ASSETS = ASSET;
export const CHURCHILL_V3_COMPOSITE_BEATS = PLAN;
