export const PRODUCT_MODULE_REQUIREMENTS = Object.freeze({
  pos: ["pos"],
  "front-desk": ["frontdesk", "reservations"],
  bookings: ["reservations"],
  reservations: ["reservations", "tables"],
  payments: ["finance"],
  "cash-control": ["finance"],
  "customer-receipts": ["finance"],
  orders: ["pos"],
  housekeeping: ["housekeeping", "hotel"],
  concierge: ["concierge", "hotel"],
  "hotel-channel-manager": ["hotel", "reservations"],
  "revenue-management": ["hotel", "analytics"],
  "night-audit": ["hotel", "finance", "accounting"],
  workforce: ["hr", "schedule", "payroll"],
  payroll: ["hr", "payroll"],
  attendance: ["hr", "schedule"],
  scheduling: ["hr", "schedule"],
  "employee-requests": ["hr"],
  "field-service": ["operations", "projects", "hr", "schedule"],
  maintenance: ["maintenance", "operations"],
  projects: ["projects"],
  "staff-portal": ["hr"],
  performance: ["hr"],
  "employee-onboarding": ["hr"],
  finance: ["finance", "accounting"],
  invoicing: ["finance", "accounting"],
  payables: ["finance", "accounting"],
  "bank-reconciliation": ["finance", "accounting"],
  collections: ["finance", "accounting"],
  "tax-vat": ["finance", "accounting"],
  "fixed-assets": ["finance", "accounting"],
  close: ["finance", "accounting"],
  forecasting: ["finance", "analytics"],
  consolidation: ["finance", "accounting"],
  "e-invoicing": ["finance", "accounting"],
  "reporting-bi": ["finance", "analytics"],
  inventory: ["inventory", "procurement"],
  procurement: ["procurement"],
  receiving: ["inventory", "procurement"],
  warehouse: ["inventory"],
  "food-cost": ["inventory", "production"],
  "production-costing": ["inventory", "production"],
  replenishment: ["inventory", "procurement"],
  "kitchen-display": ["kitchen", "pos"],
  "menu-management": ["pos", "inventory"],
  "prep-production-control": ["production", "inventory"],
  "invoice-intelligence": ["finance", "accounting"],
  "expense-capture": ["finance", "accounting"],
  "bank-statement-intelligence": ["finance", "accounting"],
  "three-way-match": ["procurement", "inventory", "finance"],
  "recipe-import": ["inventory", "production"],
  "supplier-price-capture": ["inventory", "procurement"],
  automations: ["automation"],
  crm: ["crm"],
  inbox: ["crm"],
  loyalty: ["crm"],
  reviews: ["crm", "marketing_ai"],
  marketing: ["marketing_ai", "crm"],
  sales: ["crm"],
  "customer-portal": ["customer_portal", "crm"],
  "social-publishing": ["marketing_ai"],
  "campaign-attribution": ["marketing_ai", "analytics"],
  "business-partner": ["owner_ai"],
  agents: ["owner_ai", "automation"],
  insights: ["analytics", "owner_ai"],
  secretary: ["owner_ai"],
  knowledge: ["owner_ai"],
  "creative-studio": ["design_studio"],
  "image-studio": ["design_studio"],
  "video-studio": ["design_studio"],
  "music-studio": ["design_studio"],
  "voice-studio": ["design_studio"],
  "campaign-production": ["design_studio", "marketing_ai"],
  "restaurant-system": ["pos", "tables", "kitchen", "inventory", "procurement", "hr", "schedule", "payroll", "finance", "accounting", "crm"],
  "hotel-system": ["hotel", "frontdesk", "reservations", "housekeeping", "concierge", "maintenance", "hr", "schedule", "payroll", "finance", "accounting", "crm"],
  "retail-system": ["pos", "inventory", "procurement", "hr", "schedule", "payroll", "finance", "accounting", "crm"],
  "field-service-system": ["operations", "projects", "maintenance", "hr", "schedule", "finance", "accounting", "crm"],
  "pest-control-system": ["operations", "projects", "hr", "schedule", "finance", "accounting", "crm"],
  "agency-system": ["projects", "design_studio", "marketing_ai", "crm", "finance", "accounting"],
  "accounting-firm": ["finance", "accounting", "customer_portal", "analytics"],
});

export const LEGACY_MODULE_TO_PRODUCT = Object.freeze({
  pos: "pos", frontdesk: "front-desk", reservations: "bookings", housekeeping: "housekeeping",
  concierge: "concierge", hr: "workforce", schedule: "scheduling", payroll: "payroll",
  finance: "finance", accounting: "finance", inventory: "inventory", procurement: "procurement",
  projects: "projects", crm: "crm", marketing_ai: "marketing", customer_portal: "customer-portal",
  automation: "automations", analytics: "insights", owner_ai: "business-partner", design_studio: "creative-studio",
  maintenance: "maintenance", hotel: "hotel-system", production: "production-costing", kitchen: "kitchen-display",
  tables: "reservations", operations: "field-service",
});

export function requiredModulesForProducts(productIds = []) {
  return [...new Set(productIds.flatMap((id) => PRODUCT_MODULE_REQUIREMENTS[id] || []))];
}

export function productsFromLegacyModules(selectedModules = []) {
  const ids = selectedModules.map((item) => typeof item === "string" ? item : item?.id).filter(Boolean);
  return [...new Set(ids.map((id) => LEGACY_MODULE_TO_PRODUCT[id]).filter(Boolean))];
}
