export const dynamic = "force-dynamic";
export const runtime = "nodejs";

import crypto from "node:crypto";
import { NextResponse } from "next/server";
import { requireOrganizationAccess } from "@/lib/platform/security/requireOrganizationAccess";
import { AvantiqoAudioProvider } from "@/lib/platform/service-runtime/providers/avantiqo-audio/AvantiqoAudioProvider.js";
import { buildSingingVoiceIdentityExecutionInput, buildSingingVoiceIdentityPlan } from "@/lib/creative/music/runtime/CreativeMusicSingingVoiceIdentityRuntime.js";

const EXECUTION_PERMISSIONS = Object.freeze(["creative.execute", "creative.production.run", "creative.*"]);
const RESEARCH_ALLOWED_BLOCKERS = new Set(["MODEL_LICENSE_VERIFICATION_REQUIRED", "OWNED_RUNTIME_CERTIFICATION_REQUIRED"]);
function text(value){return String(value??"").trim();}
async function requireAccess(request,organizationId){const access=await requireOrganizationAccess({organizationId,request,requiredAnyPermission:EXECUTION_PERMISSIONS});if(!access.success){const error=new Error(access.error||"CREATIVE_MUSIC_SINGING_VOICE_ACCESS_FORBIDDEN");error.status=access.status||403;throw error;}}
function ensureResearchOnly(){if(process.env.NODE_ENV==="production"){const error=new Error("CREATIVE_MUSIC_SINGING_VOICE_RESEARCH_DISABLED_IN_PRODUCTION");error.status=403;throw error;}}
function sourceInput(body){return{organization_id:text(body.organization_id),entity_id:text(body.entity_id)||null,voice_library_profile_id:text(body.voice_library_profile_id),source_audio:text(body.source_audio),source_is_isolated_vocal:body.source_is_isolated_vocal===true,source_duration_seconds:Number(body.source_duration_seconds)||null,reference_is_isolated_vocal:body.reference_is_isolated_vocal===true,reference_duration_seconds:Number(body.reference_duration_seconds)||null,reference_snr_db:Number.isFinite(Number(body.reference_snr_db))?Number(body.reference_snr_db):null,reference_accompaniment_ratio:Number.isFinite(Number(body.reference_accompaniment_ratio))?Number(body.reference_accompaniment_ratio):null,reference_reverb_ratio:Number.isFinite(Number(body.reference_reverb_ratio))?Number(body.reference_reverb_ratio):null,reference_clipping_ratio:Number.isFinite(Number(body.reference_clipping_ratio))?Number(body.reference_clipping_ratio):null};}
export async function POST(request){try{const body=await request.json(),organizationId=text(body.organization_id);if(!organizationId)return NextResponse.json({success:false,error:"organization_id required"},{status:400});await requireAccess(request,organizationId);const action=text(body.action||"plan").toLowerCase();if(action==="plan"){const plan=await buildSingingVoiceIdentityPlan({...sourceInput(body),preserve_source_pitch:true,consent_verified:true,model_license_verified:false,runtime_certified:false});return NextResponse.json({success:true,plan,production_routing_allowed:false,research_candidate:true},{headers:{"Cache-Control":"no-store"}});}if(action==="research_execute"){ensureResearchOnly();const execution=await buildSingingVoiceIdentityExecutionInput(sourceInput(body));const blockers=(execution.metadata?.research_plan_blockers||[]).filter((item)=>!RESEARCH_ALLOWED_BLOCKERS.has(item));if(blockers.length)throw new Error(`CREATIVE_MUSIC_SINGING_VOICE_SOURCE_NOT_READY:${blockers.join("|")}`);if(execution.requirements?.source_isolated_vocal!==true)throw new Error("CREATIVE_MUSIC_SINGING_VOICE_ISOLATED_SOURCE_REQUIRED");if(execution.requirements?.reference_isolated_vocal!==true)throw new Error("CREATIVE_MUSIC_SINGING_VOICE_ISOLATED_REFERENCE_REQUIRED");if(!text(execution.voice_library_service_id))throw new Error("CREATIVE_MUSIC_SINGING_VOICE_SERVICE_CONTEXT_REQUIRED");const usageId=crypto.randomUUID();const submitted=await AvantiqoAudioProvider.execute({...execution,context:{organization_id:organizationId,organization_service_id:execution.voice_library_service_id,usage_id:usageId},metadata:{...(execution.metadata||{}),research_candidate:true,local_only:true}});return NextResponse.json({success:true,status:"QUEUED",usage_id:usageId,provider_job_id:submitted.output?.provider_job_id||null,research_candidate:true,production_certified:false,production_routing_allowed:false,external_provider_spend_authorized:false},{headers:{"Cache-Control":"no-store"}});}if(action==="status"){ensureResearchOnly();const jobId=text(body.provider_job_id);if(!jobId)throw new Error("CREATIVE_MUSIC_SINGING_VOICE_JOB_ID_REQUIRED");const result=await AvantiqoAudioProvider.getStatus({job_id:jobId,context:{organization_id:organizationId}});return NextResponse.json({success:true,...result,research_candidate:true,production_certified:false,production_routing_allowed:false},{headers:{"Cache-Control":"no-store"}});}return NextResponse.json({success:false,error:"CREATIVE_MUSIC_SINGING_VOICE_ACTION_INVALID"},{status:400});}catch(error){return NextResponse.json({success:false,error:error?.message||"Creative Music singing voice failed"},{status:error?.status||400});}}
