/**
 * EVENT SUBSCRIPTION REGISTRY
 * Defines which workers respond to which events
 */

export const EVENT_SUBSCRIPTIONS = {
  WORK_CENTER: [
    "ORDER_CREATED",
    "ORDER_ITEM_ADDED",
    "ORDER_COMPLETED",
  ],

  OPERATIONS: [
    "RESTAURANT_WORK_ITEM_READY",
    "RESTAURANT_HANDOFF_COMPLETED",
    "RESTAURANT_WORK_ITEM_COMPLETED",
  ],

  FINANCE: [
    "POS_SALE_RECOGNIZED",
    "POS_CASH_PAYMENT_RECEIVED",
    "POS_CARD_PAYMENT_RECEIVED",
    "POS_QR_PAYMENT_RECEIVED",
    "POS_TRANSFER_PAYMENT_RECEIVED",
  ],
};
