/**
 * EVENT SUBSCRIPTION REGISTRY
 * Defines which workers respond to which events
 */

export const EVENT_SUBSCRIPTIONS = {
  WORK_CENTER: [
    "ORDER_CREATED",
    "ORDER_ITEM_ADDED",
    "ORDER_COMPLETED"
  ],

  INVENTORY: [
    "ORDER_ITEM_ADDED",
    "ORDER_COMPLETED",
    "STOCK_ADJUSTED",
    "PURCHASE_RECEIVED"
  ],

  FINANCE: [
    "ORDER_COMPLETED",
    "PAYMENT_RECEIVED",
    "INVOICE_CREATED"
  ],

  OPERATIONS: [
    "RESTAURANT_WORK_ITEM_READY",
    "RESTAURANT_HANDOFF_COMPLETED",
    "RESTAURANT_WORK_ITEM_COMPLETED"
  ]
};
