import { spawn } from "node:child_process";
import { materializeMedia } from "@/lib/creative/media/runtime/CreativeMediaInspectionRuntime";

const CONTRACT = "AVANTIQO_MUSIC_MIX_EVIDENCE_V4";
const WINDOW_SECONDS = 120;
const ENVELOPE_RATE = 16000;
const ENVELOPE_WINDOW_SECONDS = 1.0;
const ENVELOPE_HOP_SECONDS = 0.5;
function text(v){return String(v??"").trim();}
function finite(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}
function run(command,args,timeoutMs=180000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{shell:false,stdio:["ignore","pipe","pipe"]});const stderr=[];const timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("CREATIVE_MUSIC_MIX_EVIDENCE_TIMEOUT"));},timeoutMs);child.stderr.on("data",c=>stderr.push(c));child.on("error",e=>{clearTimeout(timer);reject(e);});child.on("close",code=>{clearTimeout(timer);const err=Buffer.concat(stderr).toString("utf8");if(code===0)resolve(err);else reject(new Error(err||`CREATIVE_MUSIC_MIX_EVIDENCE_EXIT_${code}`));});});}
function stats(stderr){const s=String(stderr||"");const mean=s.match(/mean_volume:\s*(-?[0-9.]+)\s*dB/i);const peak=s.match(/max_volume:\s*(-?[0-9.]+)\s*dB/i);return {mean_db:finite(mean?.[1]),peak_dbfs:finite(peak?.[1])};}
async function measure(ffmpeg,file,filter=null){const chain=[filter,"volumedetect"].filter(Boolean).join(",");return stats(await run(ffmpeg,["-hide_banner","-nostats","-t",String(WINDOW_SECONDS),"-i",file,"-vn","-af",chain,"-f","null","-"]));}

async function pcmEnvelope(ffmpeg,file){
  const out=await new Promise((resolve,reject)=>{const child=spawn(ffmpeg,["-hide_banner","-loglevel","error","-t",String(WINDOW_SECONDS),"-i",file,"-vn","-ac","1","-ar",String(ENVELOPE_RATE),"-f","f32le","-acodec","pcm_f32le","-"],{shell:false,stdio:["ignore","pipe","pipe"]});const stdout=[],stderr=[];const timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("CREATIVE_MUSIC_MIX_ENVELOPE_TIMEOUT"));},180000);child.stdout.on("data",c=>stdout.push(c));child.stderr.on("data",c=>stderr.push(c));child.on("error",e=>{clearTimeout(timer);reject(e);});child.on("close",code=>{clearTimeout(timer);if(code===0)resolve(Buffer.concat(stdout));else reject(new Error(Buffer.concat(stderr).toString("utf8")||`CREATIVE_MUSIC_MIX_ENVELOPE_EXIT_${code}`));});});
  const frames=Math.floor(out.length/4),samples=new Float32Array(frames);for(let i=0;i<frames;i++)samples[i]=out.readFloatLE(i*4);
  const win=Math.max(1,Math.round(ENVELOPE_RATE*ENVELOPE_WINDOW_SECONDS)),hop=Math.max(1,Math.round(ENVELOPE_RATE*ENVELOPE_HOP_SECONDS)),rows=[];
  for(let start=0;start+Math.round(ENVELOPE_RATE*.25)<=samples.length;start+=hop){const end=Math.min(samples.length,start+win);let sum=0;for(let i=start;i<end;i++)sum+=samples[i]*samples[i];const rms=Math.sqrt(sum/Math.max(1,end-start));const db=rms>1e-9?20*Math.log10(rms):-120;rows.push({time_seconds:Number(((start+(end-start)/2)/ENVELOPE_RATE).toFixed(3)),rms_dbfs:Number(db.toFixed(2))});}
  return rows.slice(0,240);
}
async function trackEvidence({organization_id,track,source_url,ffmpeg}){const media=await materializeMedia({organization_id,source_url,source_file_name:`${track.id}.wav`,source_mime_type:"audio/wav"});try{const [full,sub,lowmid,presence,air,sibilance,envelope]=await Promise.all([measure(ffmpeg,media.file_path),measure(ffmpeg,media.file_path,"highpass=f=30,lowpass=f=120"),measure(ffmpeg,media.file_path,"highpass=f=120,lowpass=f=500"),measure(ffmpeg,media.file_path,"highpass=f=2200,lowpass=f=5200"),measure(ffmpeg,media.file_path,"highpass=f=7000,lowpass=f=14000"),measure(ffmpeg,media.file_path,"highpass=f=5600,lowpass=f=9500"),pcmEnvelope(ffmpeg,media.file_path)]);const delta=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)?Number((a-b).toFixed(2)):null;return {track_id:track.id,measured:true,mean_db:full.mean_db,peak_dbfs:full.peak_dbfs,crest_proxy_db:Number.isFinite(full.mean_db)&&Number.isFinite(full.peak_dbfs)?Number((full.peak_dbfs-full.mean_db).toFixed(2)):null,sub_vs_lowmid_db:delta(sub.mean_db,lowmid.mean_db),presence_vs_lowmid_db:delta(presence.mean_db,lowmid.mean_db),air_vs_presence_db:delta(air.mean_db,presence.mean_db),sibilance_vs_presence_db:delta(sibilance.mean_db,presence.mean_db),dynamics_envelope:envelope,envelope_window_seconds:ENVELOPE_WINDOW_SECONDS,envelope_hop_seconds:ENVELOPE_HOP_SECONDS};}finally{await media.cleanup().catch(()=>{});}}
export async function analyzeMusicMixEvidence({organization_id,session,asset_urls={},media_tools={}}={}){if(!organization_id)throw new Error("CREATIVE_MUSIC_MIX_EVIDENCE_ORGANIZATION_REQUIRED");const ffmpeg=text(media_tools.ffmpeg||process.env.CREATIVE_FFMPEG_PATH)||"ffmpeg";const rows=[];for(const track of session?.tracks||[]){if(track.mute===true)continue;const sourceId=(track.clips||[]).find(c=>c?.source_asset_id)?.source_asset_id;const sourceUrl=sourceId?asset_urls[sourceId]:null;if(!sourceUrl){rows.push({track_id:track.id,measured:false,reason:"SOURCE_URL_UNAVAILABLE"});continue;}try{rows.push(await trackEvidence({organization_id,track,source_url:sourceUrl,ffmpeg}));}catch(error){rows.push({track_id:track.id,measured:false,reason:text(error?.message||"ANALYSIS_FAILED")});}}
const measured=rows.filter(r=>r.measured);
const relationships=[];
for(let i=0;i<measured.length;i+=1){for(let j=i+1;j<measured.length;j+=1){const a=measured[i],b=measured[j];const presenceOverlap=Math.abs((a.presence_vs_lowmid_db??0)-(b.presence_vs_lowmid_db??0));const lowOverlap=Math.abs((a.sub_vs_lowmid_db??0)-(b.sub_vs_lowmid_db??0));const meanDelta=Math.abs((a.mean_db??-120)-(b.mean_db??-120));relationships.push({track_a_id:a.track_id,track_b_id:b.track_id,presence_overlap_score:Number(Math.max(0,1-presenceOverlap/8).toFixed(3)),low_overlap_score:Number(Math.max(0,1-lowOverlap/8).toFixed(3)),level_proximity_score:Number(Math.max(0,1-meanDelta/12).toFixed(3)),measured_from_independent_track_spectra:true,simultaneous_masking_measured:false});}}
return {contract:CONTRACT,measured_track_count:measured.length,tracks:rows,relationships,relationship_method:"INDEPENDENT_TRACK_SPECTRAL_OVERLAP_PROXY",simultaneous_masking_measured:false,artistic_intent_inferred:false,mutation_authorized:false};}
export const CreativeMusicMixEvidenceRuntime=Object.freeze({contract:CONTRACT,analyze:analyzeMusicMixEvidence});
