import { createMusicAutomationLane } from "./CreativeMusicAutomationRuntime.js";
import { musicSecondsToFrames, musicSecondsToSmpte } from "./CreativeMusicPictureLockRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_CINEMATIC_SOUND_OBJECT_V1";
const CATEGORIES=Object.freeze(["VEHICLE","MACHINERY","IMPACT","FOLEY","FOOTSTEP","PROP","AMBIENCE","WHOOSH","UI","VOICE","CREATURE","CUSTOM"]);
const LAYER_TYPES=Object.freeze(["PRODUCTION_SOURCE","CLOSE_DETAIL","MECHANICAL","TRANSIENT","BODY","SUB_LFE","ENVIRONMENT","DESIGNED_TEXTURE","CHARACTER_SWEETENER"]);
const DEFAULT_LAYERS=Object.freeze({
 VEHICLE:["PRODUCTION_SOURCE","MECHANICAL","BODY","TRANSIENT","SUB_LFE","ENVIRONMENT","CHARACTER_SWEETENER"],
 MACHINERY:["PRODUCTION_SOURCE","MECHANICAL","BODY","TRANSIENT","ENVIRONMENT"],
 IMPACT:["PRODUCTION_SOURCE","TRANSIENT","BODY","SUB_LFE","ENVIRONMENT"],
 FOLEY:["PRODUCTION_SOURCE","CLOSE_DETAIL","ENVIRONMENT"],FOOTSTEP:["PRODUCTION_SOURCE","CLOSE_DETAIL","BODY","ENVIRONMENT"],PROP:["PRODUCTION_SOURCE","CLOSE_DETAIL","BODY"],
 AMBIENCE:["PRODUCTION_SOURCE","ENVIRONMENT","DESIGNED_TEXTURE"],WHOOSH:["PRODUCTION_SOURCE","DESIGNED_TEXTURE","TRANSIENT"],UI:["PRODUCTION_SOURCE","TRANSIENT","DESIGNED_TEXTURE"],VOICE:["PRODUCTION_SOURCE","CLOSE_DETAIL","ENVIRONMENT"],CREATURE:["PRODUCTION_SOURCE","BODY","CHARACTER_SWEETENER","ENVIRONMENT"],CUSTOM:["PRODUCTION_SOURCE"]
});
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,min,max,f=0){return Math.max(min,Math.min(max,finite(v,f)));}
function category(value){const c=text(value||"CUSTOM").toUpperCase();if(!CATEGORIES.includes(c))throw new Error(`CREATIVE_MUSIC_SOUND_OBJECT_CATEGORY_INVALID:${c}`);return c;}
function layer(input,index){const type=text(input?.type||input||"PRODUCTION_SOURCE").toUpperCase();if(!LAYER_TYPES.includes(type))throw new Error(`CREATIVE_MUSIC_SOUND_LAYER_TYPE_INVALID:${type}`);return{id:text(input?.id)||`layer-${index+1}`,type,description:text(input?.description)||null,asset_id:text(input?.asset_id)||null,gain_db:clamp(input?.gain_db,-60,18,0),required:input?.required!==false,source_provenance_required:true,destructive_processing_allowed:false};}

export function createMusicCinematicSoundObject(input={}){
 const c=category(input.category),start=Math.max(0,finite(input.start_seconds,0)),duration=Math.max(.001,finite(input.duration_seconds,.25)),fps=Math.max(1,finite(input.frame_rate,24)),path=input.spatial_path||{};
 const supplied=Array.isArray(input.layers)&&input.layers.length?input.layers:DEFAULT_LAYERS[c].map(type=>({type,required:true}));
 const layers=supplied.map(layer);
 return{contract:CONTRACT,id:text(input.id)||`sound-object-${crypto.randomUUID()}`,name:text(input.name||input.description||c).slice(0,160),category:c,picture_object_id:text(input.picture_object_id)||null,cue_id:text(input.cue_id)||null,shot_id:text(input.shot_id)||null,picture_lock_digest:text(input.picture_lock_digest)||null,cue_sheet_hash:text(input.cue_sheet_hash)||null,start_seconds:start,end_seconds:Number((start+duration).toFixed(6)),duration_seconds:duration,start_frame:musicSecondsToFrames(start,fps),end_frame:musicSecondsToFrames(start+duration,fps),start_timecode:musicSecondsToSmpte(start,fps),end_timecode:musicSecondsToSmpte(start+duration,fps),sync_tolerance_frames:Math.max(1,Math.round(finite(input.sync_tolerance_frames,1))),layers,layer_count:layers.length,spatial_path:{mode:["STATIC","MOVE","FOLLOW_PICTURE_OBJECT"].includes(text(path.mode).toUpperCase())?text(path.mode).toUpperCase():input.picture_object_id?"FOLLOW_PICTURE_OBJECT":"STATIC",start_azimuth_degrees:clamp(path.start_azimuth_degrees,-180,180,0),end_azimuth_degrees:clamp(path.end_azimuth_degrees,-180,180,clamp(path.start_azimuth_degrees,-180,180,0)),width_percent:clamp(path.width_percent,0,200,0),divergence_percent:clamp(path.divergence_percent,0,100,20)},mix_intent:{foreground:input.foreground!==false,center_picture_motivated:input.center_picture_motivated===true,lfe_allowed:layers.some(x=>x.type==="SUB_LFE"),dialogue_priority:input.dialogue_priority===true},governance:{approved_cue_required:true,picture_lock_required:true,layer_source_provenance_required:true,independent_perceptual_review_required:true,automatic_layer_generation_authority:false,automatic_mix_acceptance:false,original_source_assets_preserved:true}};
}

export function buildMusicCinematicSoundObjectPlan({picture_lock,cue_sheet_hash=null,cues=[]}={}){if(!picture_lock?.picture_lock_digest)throw new Error("CREATIVE_MUSIC_SOUND_OBJECT_PICTURE_LOCK_REQUIRED");const objects=(cues||[]).map((cue,index)=>createMusicCinematicSoundObject({...cue,id:cue.id||`sound-object-${index+1}`,picture_lock_digest:picture_lock.picture_lock_digest,cue_sheet_hash:cue.cue_sheet_hash||cue_sheet_hash,frame_rate:picture_lock.frame_rate}));return{contract:"AVANTIQO_MUSIC_CINEMATIC_SOUND_OBJECT_PLAN_V1",picture_lock_digest:picture_lock.picture_lock_digest,cue_sheet_hash:text(cue_sheet_hash)||null,object_count:objects.length,objects,picture_locked:true,source_layering_required:true,spatial_mix_required:true,perceptual_review_required:true,provider_jobs_submitted:0,automatic_generation_started:false};}

export function soundObjectSpatialAutomationLanes(soundObject={},trackId){const id=text(trackId);if(!id)throw new Error("CREATIVE_MUSIC_SOUND_OBJECT_TRACK_REQUIRED");const path=soundObject.spatial_path||{};if(path.mode==="STATIC")return[];const points=[{time_seconds:soundObject.start_seconds,value:path.start_azimuth_degrees},{time_seconds:soundObject.end_seconds,value:path.end_azimuth_degrees}];const lanes=[createMusicAutomationLane({id:`spatial-${soundObject.id}-azimuth`,target_type:"track",target_id:id,parameter:"spatial:azimuth_degrees",interpolation:"linear",points})];if(finite(path.width_percent,0)>0)lanes.push(createMusicAutomationLane({id:`spatial-${soundObject.id}-width`,target_type:"track",target_id:id,parameter:"spatial:width_percent",interpolation:"linear",points:[{time_seconds:soundObject.start_seconds,value:path.width_percent},{time_seconds:soundObject.end_seconds,value:path.width_percent}]}));return lanes;}

export function soundObjectLayerReadiness(soundObject={}){const missing=[];for(const layer of soundObject.layers||[]){if(layer.required===true&&!text(layer.asset_id))missing.push(layer.type);}return{contract:"AVANTIQO_MUSIC_SOUND_OBJECT_LAYER_READINESS_V1",sound_object_id:soundObject.id||null,ready:missing.length===0,missing_required_layer_types:[...new Set(missing)],required_layer_count:(soundObject.layers||[]).filter(x=>x.required===true).length,resolved_required_layer_count:(soundObject.layers||[]).filter(x=>x.required===true&&text(x.asset_id)).length,automatic_waiver_allowed:false};}

export const CreativeMusicCinematicSoundObjectRuntime=Object.freeze({contract:CONTRACT,categories:CATEGORIES,layerTypes:LAYER_TYPES,create:createMusicCinematicSoundObject,plan:buildMusicCinematicSoundObjectPlan,spatialAutomation:soundObjectSpatialAutomationLanes,readiness:soundObjectLayerReadiness});
