import { createMusicClip, createMusicTrack } from "./CreativeMusicMultitrackRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_FOLEY_BINDING_V1";
function text(v){return String(v??"").trim();}
function finite(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}
function cueRole(category){return text(category).toUpperCase()==="AMBIENCE"?"AMBIENCE":"FOLEY";}
function cueTrackType(category){return cueRole(category)==="AMBIENCE"?"ambience":"foley";}
function pictureContext(session={}){const lock=session.picture_lock||{};const digest=text(lock.picture_lock_digest),duration=finite(lock.duration_seconds,null),frameRate=finite(lock.frame_rate,null);if(!digest)throw new Error("CREATIVE_MUSIC_FOLEY_BINDING_PICTURE_LOCK_REQUIRED");if(duration===null||duration<=0)throw new Error("CREATIVE_MUSIC_FOLEY_BINDING_PICTURE_DURATION_REQUIRED");return{digest,duration,frame_rate:frameRate};}
function normalizeCue(cue={},picture={}){const id=text(cue.id||cue.cue_id);if(!id)throw new Error("CREATIVE_MUSIC_FOLEY_BINDING_CUE_ID_REQUIRED");const start=Math.max(0,finite(cue.start_seconds,0)),duration=Math.max(.01,finite(cue.duration_seconds,.25));if(start>picture.duration+1e-6||start+duration>picture.duration+.05)throw new Error(`CREATIVE_MUSIC_FOLEY_BINDING_CUE_OUTSIDE_PICTURE:${id}`);const category=text(cue.category||"CUSTOM").toUpperCase();return{id,category,start_seconds:start,duration_seconds:duration,sync_tolerance_ms:Math.max(8,Math.min(120,finite(cue.sync_tolerance_ms,category==="IMPACT"?16:40))),description:text(cue.description),perspective:text(cue.perspective||"ON_SCREEN").toUpperCase()};}
function selectTrack(session,cue,targetTrackId,picture){const role=cueRole(cue.category),type=cueTrackType(cue.category);if(targetTrackId){const track=(session.tracks||[]).find(row=>row.id===targetTrackId);if(!track)throw new Error("CREATIVE_MUSIC_FOLEY_BINDING_TARGET_TRACK_NOT_FOUND");if(track.type!==type||text(track.audio_role).toUpperCase()!==role)throw new Error(`CREATIVE_MUSIC_FOLEY_BINDING_TARGET_TRACK_ROLE_INVALID:${track.id}`);return track;}const existing=(session.tracks||[]).find(row=>row.type===type&&text(row.audio_role).toUpperCase()===role&&text(row.picture_lock_digest)===picture.digest);if(existing)return existing;const track=createMusicTrack({type,name:role==="AMBIENCE"?"Picture Ambience":"Foley",audio_role:role,picture_lock_digest:picture.digest,foley_cue_id:role==="FOLEY"?cue.id:null});session.tracks.push(track);return track;}
export function bindMusicFoleyAsset(sessionInput={},input={}){const session=structuredClone(sessionInput),picture=pictureContext(session),cue=normalizeCue(input.cue||{},picture),assetId=text(input.source_asset_id);if(!assetId)throw new Error("CREATIVE_MUSIC_FOLEY_BINDING_SOURCE_ASSET_REQUIRED");const track=selectTrack(session,cue,text(input.target_track_id),picture),sourceOffset=Math.max(0,finite(input.source_offset_seconds,0)),sourceDuration=finite(input.source_duration_seconds,null),duration=sourceDuration===null?cue.duration_seconds:Math.min(cue.duration_seconds,Math.max(.01,sourceDuration));const clip=createMusicClip({source_asset_id:assetId,start_seconds:cue.start_seconds,duration_seconds:duration,source_offset_seconds:sourceOffset,foley_cue_id:cue.id,picture_lock_digest:picture.digest,fade_in_seconds:Math.min(.015,duration/4),fade_out_seconds:Math.min(.02,duration/4)});clip.foley_binding={contract:CONTRACT,cue_id:cue.id,category:cue.category,picture_lock_digest:picture.digest,sync_tolerance_ms:cue.sync_tolerance_ms,source_asset_id:assetId,source_offset_seconds:sourceOffset,recorded_or_imported_source:true,ai_generation_required:false,source_preserved:true,destructive_edit:false,human_sync_review_required:true};track.foley_cue_id=track.type==="foley"?cue.id:track.foley_cue_id||null;track.picture_lock_digest=picture.digest;track.clips=Array.isArray(track.clips)?track.clips:[];const existingIndex=track.clips.findIndex(row=>text(row.foley_cue_id)===cue.id&&text(row.source_asset_id)===assetId);if(existingIndex>=0)track.clips[existingIndex]=clip;else track.clips.push(clip);return{contract:CONTRACT,success:true,session,report:{cue_id:cue.id,category:cue.category,track_id:track.id,track_type:track.type,audio_role:track.audio_role,source_asset_id:assetId,picture_lock_digest:picture.digest,start_seconds:cue.start_seconds,duration_seconds:duration,sync_tolerance_ms:cue.sync_tolerance_ms,exact_picture_time_binding:true,provider_job_submitted:false,ai_generation_required:false,source_preserved:true,destructive_edit:false,human_sync_review_required:true}};}
export const CreativeMusicFoleyBindingRuntime=Object.freeze({contract:CONTRACT,bind:bindMusicFoleyAsset});
