import { spawn } from "node:child_process";
import { materializeMedia } from "@/lib/creative/media/runtime/CreativeMediaInspectionRuntime";

export const MUSIC_REFERENCE_MASTERING_CONTRACT="AVANTIQO_MUSIC_REFERENCE_MASTERING_V1";
const RATE=24000;
function text(v){return String(v??"").trim();}function finite(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}function db(v){return v>1e-12?20*Math.log10(v):-120;}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function run(cmd,args,timeout=180000){return new Promise((resolve,reject)=>{const child=spawn(cmd,args,{shell:false,stdio:["ignore","pipe","pipe"]}),out=[],err=[],timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("CREATIVE_MUSIC_REFERENCE_MASTERING_PROCESS_TIMEOUT"));},timeout);child.stdout.on("data",c=>out.push(c));child.stderr.on("data",c=>err.push(c));child.on("error",e=>{clearTimeout(timer);reject(e);});child.on("close",code=>{clearTimeout(timer);const result={stdout:Buffer.concat(out),stderr:Buffer.concat(err).toString("utf8")};code===0?resolve(result):reject(new Error(result.stderr||`CREATIVE_MUSIC_REFERENCE_MASTERING_PROCESS_EXIT_${code}`));});});}
function floats(buf){const n=Math.floor(buf.length/4),a=new Float32Array(n);for(let i=0;i<n;i++)a[i]=buf.readFloatLE(i*4);return a;}
function stereoMetrics(s){const frames=Math.floor(s.length/2);if(!frames)return null;let sumL=0,sumR=0,sumLL=0,sumRR=0,sumLR=0,stereoSq=0,monoSq=0,peak=0;for(let i=0;i<frames;i++){const l=s[i*2],r=s[i*2+1];sumL+=l;sumR+=r;sumLL+=l*l;sumRR+=r*r;sumLR+=l*r;stereoSq+=(l*l+r*r)*.5;const m=(l+r)*.5;monoSq+=m*m;peak=Math.max(peak,Math.abs(l),Math.abs(r));}const ml=sumL/frames,mr=sumR/frames,cov=sumLR/frames-ml*mr,vl=Math.max(0,sumLL/frames-ml*ml),vr=Math.max(0,sumRR/frames-mr*mr),corr=cov/Math.max(1e-12,Math.sqrt(vl*vr)),rms=Math.sqrt(stereoSq/frames),mono=Math.sqrt(monoSq/frames);return{rms_dbfs:Number(db(rms).toFixed(2)),crest_factor_db:Number((db(peak)-db(rms)).toFixed(2)),stereo_correlation:Number(clamp(corr,-1,1).toFixed(4)),mono_fold_down_loss_db:Number((db(mono)-db(rms)).toFixed(2))};}
async function pcm(ffmpeg,path,filter=null){const args=["-hide_banner","-loglevel","error","-i",path,"-vn"];if(filter)args.push("-af",filter);args.push("-ac","2","-ar",String(RATE),"-f","f32le","-acodec","pcm_f32le","-");return floats((await run(ffmpeg,args)).stdout);}
async function band(ffmpeg,path,low,high,gainDb=0){const center=Math.sqrt(low*high),width=Math.max(40,high-low),filter=`volume=${gainDb}dB,bandpass=f=${center}:width_type=h:width=${width}`,s=await pcm(ffmpeg,path,filter);let sum=0;for(const v of s)sum+=v*v;return Math.sqrt(sum/Math.max(1,s.length));}
async function analyzeOne(ffmpeg,path,gainDb=0){const samples=await pcm(ffmpeg,path,gainDb?`volume=${gainDb}dB`:null),m=stereoMetrics(samples);const defs=[['sub',30,80],['bass',80,160],['low_mid',160,500],['mid',500,2500],['presence',2500,5000],['air',5000,11500]],bands={};for(const [id,l,h] of defs)bands[id]=Number(db(await band(ffmpeg,path,l,h,gainDb)).toFixed(2));return{...m,bands};}
function deltas(master,ref){const band_deltas_db={};for(const key of Object.keys(master.bands||{}))band_deltas_db[key]=Number((master.bands[key]-ref.bands[key]).toFixed(2));return{band_deltas_db,crest_delta_db:Number((master.crest_factor_db-ref.crest_factor_db).toFixed(2)),stereo_correlation_delta:Number((master.stereo_correlation-ref.stereo_correlation).toFixed(4)),mono_fold_down_delta_db:Number((master.mono_fold_down_loss_db-ref.mono_fold_down_loss_db).toFixed(2))};}
export async function analyzeMusicReferenceMastering({organization_id,master_asset={},reference_assets=[],media_tools={}}={}){if(!organization_id)throw new Error("CREATIVE_MUSIC_REFERENCE_MASTERING_ORGANIZATION_REQUIRED");const masterUrl=text(master_asset.file_url||master_asset.audio_url||master_asset.url);if(!masterUrl)throw new Error("CREATIVE_MUSIC_REFERENCE_MASTERING_MASTER_REQUIRED");const refs=(Array.isArray(reference_assets)?reference_assets:[]).filter(Boolean).slice(0,8);if(!refs.length)throw new Error("CREATIVE_MUSIC_REFERENCE_MASTERING_REFERENCE_REQUIRED");const ffmpeg=text(media_tools.ffmpeg||process.env.CREATIVE_FFMPEG_PATH)||"ffmpeg",masterMat=await materializeMedia({url:masterUrl,file_name:master_asset.file_name||"master.wav",mime_type:master_asset.metadata?.mime_type||"audio/wav",organization_id,policy:{max_bytes:2147483648,timeout_ms:300000,max_redirects:0}});try{const masterRaw=await analyzeOne(ffmpeg,masterMat.file_path,0),rows=[];for(const ref of refs){const url=text(ref.file_url||ref.audio_url||ref.url);if(!url)continue;const mat=await materializeMedia({url,file_name:ref.file_name||ref.name||"reference.wav",mime_type:ref.metadata?.mime_type||"audio/wav",organization_id,policy:{max_bytes:2147483648,timeout_ms:300000,max_redirects:0}});try{const refRaw=await analyzeOne(ffmpeg,mat.file_path,0),gainDb=Number((masterRaw.rms_dbfs-refRaw.rms_dbfs).toFixed(2)),refMatched=await analyzeOne(ffmpeg,mat.file_path,gainDb),delta=deltas(masterRaw,refMatched),reviewFlags=[];for(const [bandId,value] of Object.entries(delta.band_deltas_db))if(Math.abs(value)>4.5)reviewFlags.push(`TONAL_DELTA_${bandId.toUpperCase()}`);if(Math.abs(delta.crest_delta_db)>4)reviewFlags.push("DYNAMIC_CONTRAST_DELTA");if(Math.abs(delta.stereo_correlation_delta)>.25)reviewFlags.push("STEREO_IMAGE_DELTA");if(Math.abs(delta.mono_fold_down_delta_db)>2.5)reviewFlags.push("MONO_TRANSLATION_DELTA");rows.push({reference_asset_id:ref.id||null,reference_name:ref.name||ref.title||ref.file_name||null,loudness_match_gain_db:gainDb,master_metrics:masterRaw,reference_metrics_level_matched:refMatched,deltas:delta,review_flags:reviewFlags,reference_is_target:false,automatic_eq_match_forbidden:true,automatic_dynamics_match_forbidden:true,automatic_stereo_match_forbidden:true});}finally{await mat.cleanup().catch(()=>{});}}return Object.freeze({contract:MUSIC_REFERENCE_MASTERING_CONTRACT,master_asset_id:master_asset.id||null,reference_count:rows.length,level_matching_method:"RMS_LEVEL_MATCH_BEFORE_COMPARISON",references:rows,human_mastering_review_required:true,reference_guidance_only:true,artistic_intent_inferred:false,automatic_processing_authorized:false,mutation_authorized:false,publication_authorized:false});}finally{await masterMat.cleanup().catch(()=>{});}}
export const CreativeMusicReferenceMasteringRuntime=Object.freeze({contract:MUSIC_REFERENCE_MASTERING_CONTRACT,analyze:analyzeMusicReferenceMastering});
