import { createHash } from "node:crypto";

export const AUDIO_POST_DIALOGUE_MATCH_CONTRACT="AVANTIQO_AUDIO_POST_DIALOGUE_MATCH_V1";
const BANDS=Object.freeze(["low","body","presence","air"]);
function text(v){return String(v??"").trim();}function finite(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,a,b){return Math.max(a,Math.min(b,finite(v,0)));}
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}function digest(v){return createHash("sha256").update(JSON.stringify(canonical(v))).digest("hex");}
function perspective(v){const x=text(v||"MEDIUM").toUpperCase();return["CLOSE","MEDIUM","FAR","OFFSCREEN"].includes(x)?x:"MEDIUM";}
export function buildAudioPostDialogueMatchPlan({production={},adr={},editorial={},room_tone_asset_id=null}={}){
  if(!text(production.asset_id)||!text(adr.asset_id))throw new Error("AUDIO_POST_DIALOGUE_MATCH_ASSETS_REQUIRED");
  if(production.asset_id===adr.asset_id)throw new Error("AUDIO_POST_DIALOGUE_MATCH_DISTINCT_ASSETS_REQUIRED");
  const prodRms=finite(production.rms_dbfs),adrRms=finite(adr.rms_dbfs);if(prodRms===null||adrRms===null)throw new Error("AUDIO_POST_DIALOGUE_MATCH_LEVEL_EVIDENCE_REQUIRED");
  const productionBands=production.bands||{},adrBands=adr.bands||{},bandDeltas={};for(const id of BANDS){const p=finite(productionBands[id]),a=finite(adrBands[id]);if(p===null||a===null)throw new Error(`AUDIO_POST_DIALOGUE_MATCH_BAND_EVIDENCE_REQUIRED:${id}`);bandDeltas[id]=Number((p-a).toFixed(2));}
  const gainDb=Number(clamp(prodRms-adrRms,-12,12).toFixed(2)),eqMoves=[];for(const id of BANDS){const d=bandDeltas[id];if(Math.abs(d)>=1.5)eqMoves.push({band:id,change_db:Number(clamp(d,-6,6).toFixed(2)),measured_delta_db:d,automatic_apply:false});}
  const prodPerspective=perspective(editorial.production_perspective),adrPerspective=perspective(editorial.adr_perspective),perspectiveMismatch=prodPerspective!==adrPerspective;
  const roomTone=text(room_tone_asset_id||editorial.room_tone_asset_id)||null,roomToneRequired=Boolean(roomTone)||editorial.production_sound!==false;
  const warnings=[];if(Math.abs(prodRms-adrRms)>12)warnings.push("DIALOGUE_LEVEL_DELTA_EXCEEDS_MATCH_RANGE");if(eqMoves.some(x=>Math.abs(x.measured_delta_db)>8))warnings.push("DIALOGUE_TONAL_DELTA_LARGE");if(perspectiveMismatch)warnings.push("DIALOGUE_PERSPECTIVE_MISMATCH");if(roomToneRequired&&!roomTone)warnings.push("DIALOGUE_ROOM_TONE_REQUIRED");
  const core={contract:AUDIO_POST_DIALOGUE_MATCH_CONTRACT,production_asset_id:production.asset_id,adr_asset_id:adr.asset_id,room_tone_asset_id:roomTone,production_profile_digest:text(production.profile_digest)||null,adr_profile_digest:text(adr.profile_digest)||null,gain_match_db:gainDb,band_deltas_db:bandDeltas,eq_moves:eqMoves,production_perspective:prodPerspective,adr_perspective:adrPerspective,perspective_mismatch:perspectiveMismatch,room_tone_required:roomToneRequired,warnings};
  return Object.freeze({...core,plan_fingerprint:digest(core),technical_match_ready:warnings.length===0,human_dialogue_editor_review_required:true,automatic_eq_apply_forbidden:true,automatic_reverb_match_forbidden:true,automatic_room_tone_print_forbidden:true,source_audio_rewritten:false,publication_authorized:false});
}
export function approveAudioPostDialogueMatch(plan={},input={}){if(text(plan.contract)!==AUDIO_POST_DIALOGUE_MATCH_CONTRACT)throw new Error("AUDIO_POST_DIALOGUE_MATCH_PLAN_REQUIRED");if(text(input.plan_fingerprint)!==text(plan.plan_fingerprint))throw new Error("AUDIO_POST_DIALOGUE_MATCH_FINGERPRINT_MISMATCH");if(input.level_match_approved!==true)throw new Error("AUDIO_POST_DIALOGUE_MATCH_LEVEL_APPROVAL_REQUIRED");if((plan.eq_moves||[]).length&&input.tonal_match_approved!==true)throw new Error("AUDIO_POST_DIALOGUE_MATCH_TONAL_APPROVAL_REQUIRED");if(plan.room_tone_required&&input.room_tone_continuity_approved!==true)throw new Error("AUDIO_POST_DIALOGUE_MATCH_ROOM_TONE_APPROVAL_REQUIRED");if(plan.perspective_mismatch&&input.perspective_match_approved!==true)throw new Error("AUDIO_POST_DIALOGUE_MATCH_PERSPECTIVE_APPROVAL_REQUIRED");if((plan.warnings||[]).length&&input.override_warnings!==true)throw new Error("AUDIO_POST_DIALOGUE_MATCH_WARNINGS_REQUIRE_OVERRIDE");return Object.freeze({contract:"AVANTIQO_AUDIO_POST_DIALOGUE_MATCH_APPROVAL_V1",status:"APPROVED",plan_fingerprint:plan.plan_fingerprint,production_asset_id:plan.production_asset_id,adr_asset_id:plan.adr_asset_id,room_tone_asset_id:plan.room_tone_asset_id||null,approved_gain_match_db:plan.gain_match_db,approved_eq_moves:plan.eq_moves,level_match_approved:true,tonal_match_approved:input.tonal_match_approved===true,room_tone_continuity_approved:input.room_tone_continuity_approved===true,perspective_match_approved:input.perspective_match_approved===true,warning_override:input.override_warnings===true,reviewer_user_id:text(input.reviewer_user_id)||null,note:text(input.note)||null,approved_at:new Date().toISOString(),automatic_processing_authorized:false,source_audio_rewritten:false});}
export const CreativeAudioPostDialogueMatchRuntime=Object.freeze({contract:AUDIO_POST_DIALOGUE_MATCH_CONTRACT,bands:BANDS,build:buildAudioPostDialogueMatchPlan,approve:approveAudioPostDialogueMatch});
