import crypto from "node:crypto";

const CONTRACT="AVANTIQO_PROFESSIONAL_AUDIO_LONG_FORM_RENDER_PLAN_V1";
const DEFAULT_CHUNK_SECONDS=300;
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,min,max,f=0){return Math.max(min,Math.min(max,finite(v,f)));}
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(!v||typeof v!=="object")return v;return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(canonical(v))).digest("hex");}
function delayTailSeconds(bus={}){if(text(bus.effect_type).toLowerCase()!=="delay")return 0;const p=bus.parameters||{},time=clamp(p.time_seconds,.01,2,.375),feedback=clamp(p.feedback,0,.92,.28);return feedback>0?Math.min(12,time*Math.max(1,Math.ceil(Math.log(.001)/Math.log(feedback)))):time;}
function reverbTailSeconds(bus={}){if(text(bus.effect_type).toLowerCase()!=="reverb")return 0;const p=bus.parameters||{};return Math.min(15,Math.max(.1,finite(p.decay_seconds,2.2)+finite(p.pre_delay_ms,18)/1000));}
function compressionMemorySeconds(processing={}){const c=processing?.compressor||{};return c.enabled===false?0:Math.min(5,Math.max(.05,finite(c.release_ms,250)/1000*4));}
function graphContextSeconds(session={}){let max=.5;for(const bus of session.buses||[]){max=Math.max(max,delayTailSeconds(bus),reverbTailSeconds(bus),compressionMemorySeconds(bus.processing));if(text(bus.effect_type).toLowerCase()==="compressor")max=Math.max(max,Math.min(8,Math.max(.05,finite(bus.parameters?.release_ms,120)/1000*4)));}for(const track of session.tracks||[]){for(const insert of track.inserts||[]){const type=text(insert.type||insert.kind).toLowerCase(),settings=insert.settings||insert.parameters||insert;if(type==="compressor"||type==="deesser"||type==="gate")max=Math.max(max,Math.min(5,Math.max(.05,finite(settings.release_ms,250)/1000*4)));} }for(const object of session.sound_objects||[]){const path=object.spatial_path||{},immersive=path.immersive||{};if(immersive.doppler_enabled===true){const distance=Math.max(finite(path.start_distance_meters,0),finite(path.end_distance_meters,0));max=Math.max(max,distance/Math.max(250,finite(immersive.speed_of_sound_mps,343)));}if(immersive.reflections_enabled!==false)max=Math.max(max,.12+.1*finite(immersive.room_size,.35));}return Number(Math.min(20,max).toFixed(3));}
export function buildProfessionalAudioLongFormRenderPlan({session={},release_plan={},graph_fingerprint=null,chunk_seconds=DEFAULT_CHUNK_SECONDS}={}){const duration=Math.max(0,finite(release_plan.duration_seconds,0)),rate=Math.max(8000,Math.round(finite(release_plan.sample_rate,session.sample_rate||48000))),channels=Math.max(1,Math.round(finite(release_plan.channels,2))),body=Math.max(30,Math.min(900,finite(chunk_seconds,DEFAULT_CHUNK_SECONDS))),context=graphContextSeconds(session),totalFrames=Math.max(0,Math.round(duration*rate)),bodyFrames=Math.max(1,Math.round(body*rate)),contextFrames=Math.max(0,Math.round(context*rate)),chunks=[];for(let bodyStart=0,index=0;bodyStart<totalFrames;bodyStart+=bodyFrames,index+=1){const bodyEnd=Math.min(totalFrames,bodyStart+bodyFrames),renderStart=Math.max(0,bodyStart-contextFrames),renderEnd=Math.min(totalFrames,bodyEnd+contextFrames);chunks.push({index,body_start_frame:bodyStart,body_end_frame:bodyEnd,body_frames:bodyEnd-bodyStart,render_start_frame:renderStart,render_end_frame:renderEnd,render_frames:renderEnd-renderStart,trim_head_frames:bodyStart-renderStart,trim_tail_frames:renderEnd-bodyEnd,body_start_seconds:Number((bodyStart/rate).toFixed(6)),body_end_seconds:Number((bodyEnd/rate).toFixed(6)),render_start_seconds:Number((renderStart/rate).toFixed(6)),render_end_seconds:Number((renderEnd/rate).toFixed(6))});}
 const basis={contract:CONTRACT,project_revision:release_plan.project_revision??session.revision??0,release_plan_contract:release_plan.contract||null,release_plan_graph_fingerprint:graph_fingerprint||null,delivery_profile_id:release_plan.delivery_profile?.id||null,delivery_language:session.delivery_language||null,picture_lock_digest:session.picture_lock?.picture_lock_digest||null,sample_rate:rate,bit_depth:24,channels,channel_layout:release_plan.channel_layout||session.spatial_audio?.layout_id||"stereo",speaker_order:release_plan.speaker_order||[],duration_seconds:duration,total_frames:totalFrames,chunk_body_seconds:body,context_seconds:context,chunks,absolute_timeline_required:true,automation_timebase:"ABSOLUTE_PROJECT_SECONDS",chunk_processor_state:"RENDER_WITH_CONTEXT_THEN_SAMPLE_EXACT_TRIM",concat_mode:"PCM_SAMPLE_EXACT",rf64_auto:true,bwf_required:Boolean(session.picture_lock?.picture_lock_digest),original_assets_immutable:true};return{...basis,plan_hash:hash(basis),chunk_count:chunks.length,parallel_chunk_render_allowed:true,whole_program_qc_required:true,whole_program_loudness_measurement_required:true,chunk_loudness_normalization_forbidden:true,per_chunk_limiter_forbidden:true,final_mastering_after_assembly_required:true};}
export const CreativeProfessionalAudioLongFormRenderPlanRuntime=Object.freeze({contract:CONTRACT,build:buildProfessionalAudioLongFormRenderPlan});
