const CONTRACT="AVANTIQO_MUSIC_TEMPO_MAP_V2";const TEMPO="AVANTIQO_MUSIC_TEMPO_EVENT_V1";const METER="AVANTIQO_MUSIC_METER_EVENT_V1";
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,min,max,f=min){return Math.max(min,Math.min(max,finite(v,f)));}function id(v,prefix){return text(v)||`${prefix}-${crypto.randomUUID()}`;}
function validSignature(value){const match=text(value).match(/^(\d{1,2})\/(1|2|4|8|16|32)$/);if(!match)return false;const numerator=Number(match[1]);return numerator>=1&&numerator<=32;}
function normalizeSignature(value,fallback="4/4"){const signature=text(value||fallback);if(!validSignature(signature))throw new Error(`CREATIVE_MUSIC_TEMPO_MAP_METER_INVALID:${signature}`);return signature;}
export function createMusicTempoMap(input={}){const bpm=clamp(input.initial_bpm,30,300,120);const signature=normalizeSignature(input.initial_time_signature,"4/4");return{contract:CONTRACT,tempo_events:[{contract:TEMPO,id:id(null,"tempo"),beat:0,bpm,curve:"step"}],meter_events:[{contract:METER,id:id(null,"meter"),beat:0,time_signature:signature}],non_destructive:true,exact_linear_ramp_integration:true,provider_job_submitted:false};}
export function ensureMusicTempoMap(value={},fallback={}){const compatible=value?.contract==="AVANTIQO_MUSIC_TEMPO_MAP_V1"||value?.contract===CONTRACT;const source=compatible?structuredClone(value):createMusicTempoMap({initial_bpm:fallback.bpm,initial_time_signature:fallback.time_signature});source.contract=CONTRACT;if(!Array.isArray(source.tempo_events)||!source.tempo_events.length)source.tempo_events=createMusicTempoMap({initial_bpm:fallback.bpm}).tempo_events;if(!Array.isArray(source.meter_events)||!source.meter_events.length)source.meter_events=createMusicTempoMap({initial_time_signature:fallback.time_signature}).meter_events;source.tempo_events=source.tempo_events.map((event)=>({contract:TEMPO,id:id(event.id,"tempo"),beat:Math.max(0,finite(event.beat,0)),bpm:clamp(event.bpm,30,300,120),curve:["step","linear"].includes(text(event.curve))?text(event.curve):"step"})).sort((a,b)=>a.beat-b.beat);source.meter_events=source.meter_events.map((event)=>({contract:METER,id:id(event.id,"meter"),beat:Math.max(0,finite(event.beat,0)),time_signature:normalizeSignature(event.time_signature,fallback.time_signature||"4/4")})).sort((a,b)=>a.beat-b.beat);if(source.tempo_events[0].beat!==0)source.tempo_events.unshift({contract:TEMPO,id:id(null,"tempo"),beat:0,bpm:clamp(fallback.bpm,30,300,120),curve:"step"});if(source.meter_events[0].beat!==0)source.meter_events.unshift({contract:METER,id:id(null,"meter"),beat:0,time_signature:normalizeSignature(fallback.time_signature,"4/4")});source.non_destructive=true;source.exact_linear_ramp_integration=true;source.provider_job_submitted=false;return source;}
function assertUniqueBeat(events,kind){for(let i=1;i<events.length;i+=1)if(Math.abs(events[i].beat-events[i-1].beat)<1e-9)throw new Error(`CREATIVE_MUSIC_TEMPO_MAP_DUPLICATE_${kind}_BEAT:${events[i].beat}`);}
export function addMusicTempoEvent(map={},event={}){const next=ensureMusicTempoMap(map);const beat=Math.max(0,finite(event.beat,0));if(next.tempo_events.some((entry)=>Math.abs(entry.beat-beat)<1e-9))throw new Error(`CREATIVE_MUSIC_TEMPO_MAP_DUPLICATE_TEMPO_BEAT:${beat}`);next.tempo_events.push({contract:TEMPO,id:id(event.id,"tempo"),beat,bpm:clamp(event.bpm,30,300,120),curve:["step","linear"].includes(text(event.curve))?text(event.curve):"step"});next.tempo_events.sort((a,b)=>a.beat-b.beat);return next;}
export function addMusicMeterEvent(map={},event={}){const next=ensureMusicTempoMap(map);const signature=normalizeSignature(event.time_signature,"4/4"),beat=Math.max(0,finite(event.beat,0));if(next.meter_events.some((entry)=>Math.abs(entry.beat-beat)<1e-9))throw new Error(`CREATIVE_MUSIC_TEMPO_MAP_DUPLICATE_METER_BEAT:${beat}`);next.meter_events.push({contract:METER,id:id(event.id,"meter"),beat,time_signature:signature});next.meter_events.sort((a,b)=>a.beat-b.beat);return next;}
export function removeMusicTempoMapEvent(map={},kind,eventId){const next=ensureMusicTempoMap(map);const key=kind==="meter"?"meter_events":"tempo_events";const found=next[key].find((entry)=>entry.id===text(eventId));if(!found)throw new Error("CREATIVE_MUSIC_TEMPO_MAP_EVENT_NOT_FOUND");if(found.beat===0)throw new Error("CREATIVE_MUSIC_TEMPO_MAP_INITIAL_EVENT_REQUIRED");next[key]=next[key].filter((entry)=>entry.id!==found.id);return next;}
function tempoAtBeat(map,beat){const events=map.tempo_events;let current=events[0];for(let i=1;i<events.length;i+=1){const next=events[i];if(next.beat>beat)break;current=next;}return current;}
function linearSegmentSeconds(startBpm,endBpm,totalBeats,partialBeats){const span=Math.max(1e-12,totalBeats),beats=clamp(partialBeats,0,span,0),slope=(endBpm-startBpm)/span;if(Math.abs(slope)<1e-12)return beats*60/startBpm;const ending=startBpm+slope*beats;if(ending<=0||startBpm<=0)throw new Error("CREATIVE_MUSIC_TEMPO_MAP_NONPOSITIVE_RAMP");return(60/slope)*Math.log(ending/startBpm);}
export function musicBeatToSeconds(mapInput,beat){const map=ensureMusicTempoMap(mapInput);const target=Math.max(0,finite(beat,0));let seconds=0;for(let index=0;index<map.tempo_events.length;index+=1){const event=map.tempo_events[index],next=map.tempo_events[index+1];if(target<=event.beat)break;const segmentEnd=Math.min(target,next?.beat??target);if(segmentEnd<=event.beat)continue;const beats=segmentEnd-event.beat;if(event.curve==="linear"&&next){seconds+=linearSegmentSeconds(event.bpm,next.bpm,next.beat-event.beat,beats);}else seconds+=beats*60/event.bpm;if(segmentEnd>=target)break;}return seconds;}
export function musicSecondsToBeat(mapInput,seconds){const map=ensureMusicTempoMap(mapInput);const target=Math.max(0,finite(seconds,0));let low=0,high=Math.max(4,target*5+32);while(musicBeatToSeconds(map,high)<target&&high<1e7)high*=2;for(let i=0;i<56;i+=1){const mid=(low+high)/2;if(musicBeatToSeconds(map,mid)<target)low=mid;else high=mid;}return(low+high)/2;}
export function musicTempoAtBeat(mapInput,beat){const map=ensureMusicTempoMap(mapInput);const value=Math.max(0,finite(beat,0));const current=tempoAtBeat(map,value);const index=map.tempo_events.findIndex((entry)=>entry.id===current.id),next=map.tempo_events[index+1];if(current.curve==="linear"&&next&&value<next.beat){const progress=(value-current.beat)/(next.beat-current.beat);return current.bpm+(next.bpm-current.bpm)*progress;}return current.bpm;}
export function musicMeterAtBeat(mapInput,beat){const map=ensureMusicTempoMap(mapInput);let current=map.meter_events[0];for(const event of map.meter_events){if(event.beat>beat)break;current=event;}return current.time_signature;}
export function validateMusicTempoMap(map={}){const normalized=ensureMusicTempoMap(map);if(normalized.contract!==CONTRACT||normalized.non_destructive!==true)throw new Error("CREATIVE_MUSIC_TEMPO_MAP_INVALID");if(normalized.tempo_events.length>512||normalized.meter_events.length>512)throw new Error("CREATIVE_MUSIC_TEMPO_MAP_LIMIT_EXCEEDED");assertUniqueBeat(normalized.tempo_events,"TEMPO");assertUniqueBeat(normalized.meter_events,"METER");for(const event of normalized.meter_events)normalizeSignature(event.time_signature);return{success:true,contract:"AVANTIQO_MUSIC_TEMPO_MAP_VALIDATION_V2",tempo_event_count:normalized.tempo_events.length,meter_event_count:normalized.meter_events.length,exact_linear_ramp_integration:true,provider_job_submitted:false};}
export const CreativeMusicTempoMapRuntime={contract:CONTRACT,ensure:ensureMusicTempoMap,create:createMusicTempoMap,addTempo:addMusicTempoEvent,addMeter:addMusicMeterEvent,remove:removeMusicTempoMapEvent,beatToSeconds:musicBeatToSeconds,secondsToBeat:musicSecondsToBeat,tempoAtBeat:musicTempoAtBeat,meterAtBeat:musicMeterAtBeat,validate:validateMusicTempoMap};
