import { bindMusicSessionToPicture, createMusicPictureLock, musicFramesToSeconds, musicSecondsToFrames } from "./CreativeMusicPictureLockRuntime.js";

const CONTRACT="AVANTIQO_AUDIO_POST_RECONFORM_V1";
function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function text(v){return String(v??"").trim();}
function normalizeMapEntry(input,index){const oldStart=Math.max(0,Math.round(finite(input.old_start_frame,0))),oldEnd=Math.max(oldStart,Math.round(finite(input.old_end_frame,oldStart))),newStart=Math.max(0,Math.round(finite(input.new_start_frame,oldStart)));return{id:text(input.id)||`segment-${index+1}`,old_start_frame:oldStart,old_end_frame:oldEnd,new_start_frame:newStart,frame_delta:newStart-oldStart};}
export function normalizeAudioPostConformMap(entries=[]){const map=(Array.isArray(entries)?entries:[]).map(normalizeMapEntry).sort((a,b)=>a.old_start_frame-b.old_start_frame);for(let i=1;i<map.length;i++){if(map[i].old_start_frame<=map[i-1].old_end_frame)throw new Error("CREATIVE_AUDIO_POST_CONFORM_MAP_OVERLAP");}return map;}
export function mapAudioPostFrame(frame,mapEntries=[]){const f=Math.max(0,Math.round(finite(frame,0))),map=(mapEntries||[]).map((item,index)=>Number.isFinite(Number(item?.frame_delta))?item:normalizeMapEntry(item,index)),entry=map.find(item=>f>=item.old_start_frame&&f<=item.old_end_frame);return entry?f+entry.frame_delta:f;}
function mapSeconds(seconds,oldFps,newFps,map){const oldFrame=musicSecondsToFrames(seconds,oldFps),newFrame=mapAudioPostFrame(oldFrame,map);return musicFramesToSeconds(newFrame,newFps);}
export function reconformAudioPostSession(sessionInput={},nextPictureInput={},conformMapInput=[]){
  const original=structuredClone(sessionInput),oldPicture=original.picture_lock;if(!oldPicture?.picture_lock_digest)throw new Error("CREATIVE_AUDIO_POST_RECONFORM_CURRENT_PICTURE_REQUIRED");const nextPicture=createMusicPictureLock(nextPictureInput),map=normalizeAudioPostConformMap(conformMapInput);if(!map.length)throw new Error("CREATIVE_AUDIO_POST_RECONFORM_MAP_REQUIRED");const oldFps=finite(oldPicture.frame_rate,24),newFps=finite(nextPicture.frame_rate,oldFps);let movedClips=0,movedAutomationPoints=0,editorialApprovalsInvalidated=0;
  const next=structuredClone(original);
  for(const track of next.tracks||[]){for(const clip of track.clips||[]){const before=finite(clip.start_seconds,0),after=mapSeconds(before,oldFps,newFps,map);if(Math.abs(after-before)>.000001){clip.start_seconds=after;clip.preserve_source_asset=true;clip.destructive_edit=false;movedClips++;}if(clip.audio_post){const oldSync=Math.max(0,Math.round(finite(clip.audio_post.sync_frame,musicSecondsToFrames(before,oldFps)))),newSync=mapAudioPostFrame(oldSync,map);if(newSync!==oldSync){clip.audio_post.sync_frame=newSync;clip.audio_post.sync_seconds=musicFramesToSeconds(newSync,newFps);clip.audio_post.sync_timecode=null;if(clip.audio_post.dialogue_edit_approved===true){clip.audio_post.dialogue_edit_approved=false;editorialApprovalsInvalidated++;}clip.audio_post.reconform_required_review=true;clip.audio_post.reconformed_from_sync_frame=oldSync;}}}
  }
  for(const lane of next.automation_lanes||[]){for(const point of lane.points||[]){const before=finite(point.time_seconds,0),after=mapSeconds(before,oldFps,newFps,map);if(Math.abs(after-before)>.000001){point.time_seconds=after;movedAutomationPoints++;}}(lane.points||[]).sort((a,b)=>a.time_seconds-b.time_seconds);}
  next.picture_lock=nextPicture;next.timeline={...(next.timeline||{}),timebase:"PICTURE_FRAMES",frame_rate:newFps,picture_duration_seconds:nextPicture.duration_seconds,picture_lock_digest:nextPicture.picture_lock_digest,start_timecode:nextPicture.start_timecode};
  next.audio_post_reconform={contract:CONTRACT,from_picture_lock_digest:oldPicture.picture_lock_digest,to_picture_lock_digest:nextPicture.picture_lock_digest,conform_map:map,moved_clip_count:movedClips,moved_automation_point_count:movedAutomationPoints,editorial_approvals_invalidated:editorialApprovalsInvalidated,source_audio_rewritten:false,original_sources_preserved:true,completed_at:new Date().toISOString()};
  return{session:next,report:next.audio_post_reconform};
}
export const CreativeAudioPostReconformRuntime=Object.freeze({contract:CONTRACT,normalizeMap:normalizeAudioPostConformMap,mapFrame:mapAudioPostFrame,reconform:reconformAudioPostSession});
