import crypto from "node:crypto";

const CONTRACT="AVANTIQO_AUDIO_POST_PRINTMASTER_V1";
const PROFILES=Object.freeze({
  THEATRICAL:Object.freeze({id:"THEATRICAL",label:"Theatrical",monitor_environment:"CALIBRATED_CINEMA",dynamic_range:"WIDE",dialogue_premix_reuse:true,near_field:false,streaming:false}),
  NEAR_FIELD:Object.freeze({id:"NEAR_FIELD",label:"Near-field / Home",monitor_environment:"CALIBRATED_NEAR_FIELD",dynamic_range:"CONTROLLED",dialogue_premix_reuse:true,near_field:true,streaming:false}),
  STREAMING:Object.freeze({id:"STREAMING",label:"Streaming",monitor_environment:"CALIBRATED_NEAR_FIELD",dynamic_range:"CONTROLLED",dialogue_premix_reuse:true,near_field:true,streaming:true}),
});
function text(v){return String(v??"").trim();}function finite(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}function digest(v){return crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");}
export function buildAudioPostPrintmasterPlan({session={},source_master_asset_id,variants=["THEATRICAL","NEAR_FIELD","STREAMING"]}={}){if(!text(session.picture_lock?.picture_lock_digest))throw new Error("AUDIO_POST_PRINTMASTER_PICTURE_LOCK_REQUIRED");if(!text(source_master_asset_id))throw new Error("AUDIO_POST_PRINTMASTER_SOURCE_MASTER_REQUIRED");const requested=[...new Set((variants||[]).map(v=>text(v).toUpperCase()).filter(Boolean))],unsupported=requested.filter(id=>!PROFILES[id]);if(unsupported.length)throw new Error("AUDIO_POST_PRINTMASTER_PROFILE_INVALID:"+unsupported.join(","));const revision=Math.max(0,Math.round(finite(session.revision,0))),layout=text(session.spatial_audio?.layout_id||"stereo");const rows=requested.map(id=>{const p=PROFILES[id];return{...p,source_master_asset_id:text(source_master_asset_id),picture_lock_digest:session.picture_lock.picture_lock_digest,project_revision:revision,source_layout:layout,target_layout:layout,independent_render_required:true,independent_qc_required:true,independent_listening_review_required:true,automatic_dialogue_trim:false,automatic_loudness_normalization:false,automatic_dynamics_reduction:false,source_premixes_reused:true,source_assets_preserved:true};});const core={contract:CONTRACT,picture_lock_digest:session.picture_lock.picture_lock_digest,project_revision:revision,source_master_asset_id:text(source_master_asset_id),variants:rows};return{...core,plan_fingerprint:digest(core),separate_printmasters_required:rows.length>1,one_master_fits_all_claimed:false,automatic_render_authorized:false,publication_authorized:false};}
export function evaluateAudioPostPrintmasterVariant(plan={},variantId,input={}){if(plan.contract!==CONTRACT)throw new Error("AUDIO_POST_PRINTMASTER_PLAN_REQUIRED");const id=text(variantId).toUpperCase(),variant=(plan.variants||[]).find(v=>v.id===id);if(!variant)throw new Error("AUDIO_POST_PRINTMASTER_VARIANT_NOT_FOUND:"+id);const failures=[];if(text(input.source_master_asset_id)!==text(plan.source_master_asset_id))failures.push("PRINTMASTER_SOURCE_MASTER_MISMATCH");if(text(input.picture_lock_digest)!==text(plan.picture_lock_digest))failures.push("PRINTMASTER_PICTURE_LOCK_MISMATCH");if(Math.round(finite(input.project_revision,-1))!==Math.round(finite(plan.project_revision,0)))failures.push("PRINTMASTER_PROJECT_REVISION_STALE");if(text(input.channel_layout)!==text(variant.target_layout))failures.push("PRINTMASTER_CHANNEL_LAYOUT_MISMATCH");if(input.technical_qc_passed!==true)failures.push("PRINTMASTER_TECHNICAL_QC_REQUIRED");if(input.listening_review_approved!==true)failures.push("PRINTMASTER_LISTENING_REVIEW_REQUIRED");if(id==="THEATRICAL"&&input.cinema_monitor_reviewed!==true)failures.push("PRINTMASTER_CINEMA_MONITOR_REVIEW_REQUIRED");if((id==="NEAR_FIELD"||id==="STREAMING")&&input.near_field_monitor_reviewed!==true)failures.push("PRINTMASTER_NEAR_FIELD_MONITOR_REVIEW_REQUIRED");return{contract:"AVANTIQO_AUDIO_POST_PRINTMASTER_VARIANT_QC_V1",variant_id:id,passed:failures.length===0,failures,source_master_asset_id:plan.source_master_asset_id,picture_lock_digest:plan.picture_lock_digest,project_revision:plan.project_revision,channel_layout:variant.target_layout,monitor_environment:variant.monitor_environment,automatic_acceptance:false,publication_authorized:false};}
export function sealAudioPostPrintmasterSet(plan={},evaluations=[]){if(plan.contract!==CONTRACT)throw new Error("AUDIO_POST_PRINTMASTER_PLAN_REQUIRED");const byId=new Map((evaluations||[]).map(e=>[text(e.variant_id).toUpperCase(),e])),missing=(plan.variants||[]).filter(v=>byId.get(v.id)?.passed!==true).map(v=>v.id);if(missing.length)throw new Error("AUDIO_POST_PRINTMASTER_VARIANTS_NOT_APPROVED:"+missing.join(","));const evidence={contract:"AVANTIQO_AUDIO_POST_PRINTMASTER_SET_SEAL_V1",plan_fingerprint:plan.plan_fingerprint,picture_lock_digest:plan.picture_lock_digest,project_revision:plan.project_revision,source_master_asset_id:plan.source_master_asset_id,variants:(plan.variants||[]).map(v=>({id:v.id,monitor_environment:v.monitor_environment,channel_layout:v.target_layout,qc_contract:byId.get(v.id)?.contract,passed:true}))};return{...evidence,seal_hash:digest(evidence),immutable_evidence:true,audio_mutation_performed:false,provider_job_submitted:false};}
export const CreativeAudioPostPrintmasterRuntime=Object.freeze({contract:CONTRACT,profiles:PROFILES,build:buildAudioPostPrintmasterPlan,evaluate:evaluateAudioPostPrintmasterVariant,seal:sealAudioPostPrintmasterSet});
