import { buildMusicCinematicSoundObjectPlan } from "./CreativeMusicCinematicSoundObjectRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_CINEMATIC_CUE_BRIDGE_V1";
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
const FOLEY_MAP=Object.freeze({FOOTSTEP:"FOOTSTEP",CLOTH:"FOLEY",PROP:"PROP",IMPACT:"IMPACT",MACHINERY:"MACHINERY",AMBIENCE:"AMBIENCE",VEHICLE:"VEHICLE",BODY:"FOLEY",CUSTOM:"CUSTOM"});
function pictureDuration(lock){const value=finite(lock?.duration_seconds,null);if(!Number.isFinite(value)||value<=0)throw new Error("CREATIVE_MUSIC_CUE_BRIDGE_PICTURE_DURATION_REQUIRED");return value;}
function ensureWithinPicture(start,duration,pictureDurationValue,id){if(start<0||start>pictureDurationValue+1e-6||start+duration>pictureDurationValue+.05)throw new Error(`CREATIVE_MUSIC_CUE_OUTSIDE_PICTURE:${id}`);}

export function buildMusicCinematicCuesFromDirector({picture_lock,director_cue_sheet=null,foley_plan=null}={}){
 if(!picture_lock?.picture_lock_digest)throw new Error("CREATIVE_MUSIC_CUE_BRIDGE_PICTURE_LOCK_REQUIRED");const duration=pictureDuration(picture_lock),cues=[];
 if(director_cue_sheet){if(Math.abs(finite(director_cue_sheet.duration_seconds)-duration)>.05)throw new Error("CREATIVE_MUSIC_DIRECTOR_CUE_SHEET_PICTURE_DURATION_MISMATCH");for(const shot of director_cue_sheet.cues||[]){const shotStart=Math.max(0,finite(shot.timeline_in_seconds,0)),shotDuration=Math.max(.001,finite(shot.duration_seconds,finite(shot.timeline_out_seconds,shotStart)-shotStart));for(let i=0;i<(shot.sync_events||[]).length;i++){const event=shot.sync_events[i],relative=Math.max(0,finite(event.at_seconds,0)),start=shotStart+relative,id=`${shot.cue_id}:sync:${i+1}`;ensureWithinPicture(start,.25,duration,id);cues.push({id,cue_id:shot.cue_id,shot_id:shot.shot_id,category:"CUSTOM",name:text(event.event)||"Picture sync event",description:text(event.event),start_seconds:start,duration_seconds:.25,sync_tolerance_frames:1,foreground:true,center_picture_motivated:true,source_time_basis:"SHOT_RELATIVE",spatial_path:{mode:"STATIC",start_azimuth_degrees:0,end_azimuth_degrees:0}});}if(text(shot.ambience)){const id=`${shot.cue_id}:ambience`;ensureWithinPicture(shotStart,shotDuration,duration,id);cues.push({id,cue_id:shot.cue_id,shot_id:shot.shot_id,category:"AMBIENCE",name:text(shot.ambience),description:text(shot.ambience),start_seconds:shotStart,duration_seconds:shotDuration,foreground:false,source_time_basis:"SHOT_TIMELINE",spatial_path:{mode:"WIDE",start_azimuth_degrees:0,end_azimuth_degrees:0,width_percent:160,divergence_percent:70}});}for(let i=0;i<(shot.sound_effects||[]).length;i++){const description=text(shot.sound_effects[i]);if(!description)continue;const id=`${shot.cue_id}:sfx:${i+1}`;ensureWithinPicture(shotStart,shotDuration,duration,id);cues.push({id,cue_id:shot.cue_id,shot_id:shot.shot_id,category:"CUSTOM",name:description,description,start_seconds:shotStart,duration_seconds:shotDuration,foreground:true,source_time_basis:"SHOT_TIMELINE",spatial_path:{mode:"STATIC",start_azimuth_degrees:0,end_azimuth_degrees:0}});}}}
 if(foley_plan){if(Number.isFinite(finite(foley_plan.picture_duration_seconds,null))&&Math.abs(finite(foley_plan.picture_duration_seconds)-duration)>.05)throw new Error("CREATIVE_MUSIC_FOLEY_PICTURE_DURATION_MISMATCH");for(const event of foley_plan.events||[]){const id=text(event.id)||`foley-${cues.length+1}`,start=Math.max(0,finite(event.start_seconds,0)),eventDuration=Math.max(.01,finite(event.duration_seconds,.25));ensureWithinPicture(start,eventDuration,duration,id);cues.push({id:`foley:${id}`,cue_id:id,category:FOLEY_MAP[text(event.category).toUpperCase()]||"CUSTOM",name:text(event.description)||text(event.category)||"Foley",description:text(event.description),start_seconds:start,duration_seconds:eventDuration,foreground:text(event.perspective).toUpperCase()!=="BACKGROUND",sync_tolerance_frames:Math.max(1,Math.round((finite(event.sync_tolerance_ms,40)/1000)*finite(picture_lock.frame_rate,24))),source_time_basis:"PICTURE_ABSOLUTE",spatial_path:{mode:"STATIC",start_azimuth_degrees:0,end_azimuth_degrees:0}});}}
 return{contract:CONTRACT,picture_lock_digest:picture_lock.picture_lock_digest,director_cue_sheet_hash:text(director_cue_sheet?.cue_sheet_hash)||null,director_sync_event_time_basis:"SHOT_RELATIVE",foley_time_basis:"PICTURE_ABSOLUTE",cue_count:cues.length,cues,ambiguous_text_category_policy:"CUSTOM_NO_SEMANTIC_GUESS",picture_locked:true};
}

export function buildMusicSoundObjectPlanFromDirector(input={}){const bridge=buildMusicCinematicCuesFromDirector(input);const plan=buildMusicCinematicSoundObjectPlan({picture_lock:input.picture_lock,cue_sheet_hash:bridge.director_cue_sheet_hash,cues:bridge.cues});return{...plan,bridge_contract:CONTRACT,director_sync_event_time_basis:bridge.director_sync_event_time_basis,foley_time_basis:bridge.foley_time_basis,ambiguous_text_category_policy:bridge.ambiguous_text_category_policy};}
export const CreativeMusicCinematicCueBridgeRuntime=Object.freeze({contract:CONTRACT,buildCues:buildMusicCinematicCuesFromDirector,buildPlan:buildMusicSoundObjectPlanFromDirector});
