import { normalizeMusicVocalProductionRole } from "./CreativeMusicVocalProductionBusRuntime.js";
const CONTRACT="AVANTIQO_MUSIC_VOCAL_STACK_ALIGNMENT_V1";
const TIMING_CONTRACT="AVANTIQO_MUSIC_VOCAL_TIMING_ANALYSIS_V1";
function finite(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}function text(v){return String(v??"").trim();}
function median(values=[]){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function percentile(values=[],p=.9){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;return a[Math.min(a.length-1,Math.max(0,Math.ceil(p*a.length)-1))];}
function currentTiming(clip={}){const a=clip.vocal_timing_analysis;if(!a||a.contract!==TIMING_CONTRACT)return null;if(text(a.source_asset_id)!==text(clip.source_asset_id))return null;if(Math.abs(finite(a.source_offset_seconds,-1)-finite(clip.source_offset_seconds,0))>.001)return null;if(Math.abs(finite(a.source_duration_seconds,-1)-finite(clip.duration_seconds,0))>.01)return null;return a;}
function phraseRows(track={}){const rows=[];for(const clip of track.clips||[]){if(clip.muted===true)continue;const analysis=currentTiming(clip);if(!analysis)continue;for(const phrase of analysis.phrases||[]){const localStart=finite(phrase.source_start_seconds,finite(phrase.start_seconds,null)),localEnd=finite(phrase.source_end_seconds,finite(phrase.end_seconds,null));if(localStart===null||localEnd===null||localEnd<=localStart)continue;const clipStart=finite(clip.start_seconds,0),sourceOffset=finite(clip.source_offset_seconds,0),start=clipStart+(localStart-sourceOffset),end=clipStart+(localEnd-sourceOffset);rows.push({track_id:track.id,clip_id:clip.id,phrase_id:phrase.id||null,start_seconds:start,end_seconds:end,duration_seconds:end-start});}}return rows.sort((a,b)=>a.start_seconds-b.start_seconds);}
function pairPhrase(target,leadRows){let best=null;for(const lead of leadRows){const overlap=Math.max(0,Math.min(target.end_seconds,lead.end_seconds)-Math.max(target.start_seconds,lead.start_seconds)),startDistance=Math.abs(target.start_seconds-lead.start_seconds),score=overlap>0?1000+overlap:-startDistance;if(!best||score>best.score)best={lead,score,overlap,startDistance};}if(!best)return null;return{lead:best.lead,overlap_seconds:best.overlap,start_distance_seconds:best.startDistance};}
export function analyzeMusicVocalStackAlignment(session={}){const vocals=(session.tracks||[]).filter(t=>String(t.type).toLowerCase()==="vocal"&&t.mute!==true),leads=vocals.filter(t=>normalizeMusicVocalProductionRole(t.vocal_role)==="LEAD"),referenceId=text(session.vocal_production?.reference_lead_track_id),reference=referenceId?leads.find(t=>t.id===referenceId):leads.length===1?leads[0]:null,blockers=[];if(vocals.length&&!reference)blockers.push(leads.length>1?"VOCAL_ALIGNMENT_REFERENCE_LEAD_REQUIRED":"VOCAL_ALIGNMENT_LEAD_REQUIRED");const leadRows=reference?phraseRows(reference):[],stackRoles=new Set(["DOUBLE","HARMONY","BACKING","CHOIR","ADLIB"]),tracks=[];for(const track of vocals){const role=normalizeMusicVocalProductionRole(track.vocal_role);if(!stackRoles.has(role))continue;const phrases=phraseRows(track);if(!phrases.length){blockers.push(`VOCAL_STACK_TIMING_EVIDENCE_REQUIRED:${track.id}`);tracks.push({track_id:track.id,role,phrase_pair_count:0,evidence_current:false,pairs:[]});continue;}const pairs=[];for(const phrase of phrases){const match=pairPhrase(phrase,leadRows);if(!match)continue;const startOffset=(phrase.start_seconds-match.lead.start_seconds)*1000,endOffset=(phrase.end_seconds-match.lead.end_seconds)*1000;pairs.push({target_clip_id:phrase.clip_id,target_phrase_id:phrase.phrase_id,lead_clip_id:match.lead.clip_id,lead_phrase_id:match.lead.phrase_id,target_start_seconds:Number(phrase.start_seconds.toFixed(6)),lead_start_seconds:Number(match.lead.start_seconds.toFixed(6)),start_offset_ms:Number(startOffset.toFixed(2)),end_offset_ms:Number(endOffset.toFixed(2)),absolute_start_offset_ms:Number(Math.abs(startOffset).toFixed(2)),overlap_seconds:Number(match.overlap_seconds.toFixed(4))});}const abs=pairs.map(p=>p.absolute_start_offset_ms);tracks.push({track_id:track.id,role,evidence_current:true,phrase_pair_count:pairs.length,median_absolute_start_offset_ms:median(abs),p90_absolute_start_offset_ms:percentile(abs,.9),maximum_absolute_start_offset_ms:abs.length?Math.max(...abs):null,mean_signed_start_offset_ms:pairs.length?Number((pairs.reduce((sum,p)=>sum+p.start_offset_ms,0)/pairs.length).toFixed(2)):null,pairs:pairs.slice(0,96)});}
return{contract:CONTRACT,reference_lead_track_id:reference?.id||null,reference_phrase_count:leadRows.length,stack_track_count:tracks.length,tracks,blockers:[...new Set(blockers)],measurement_ready:blockers.length===0,automatic_alignment_forbidden:true,time_stretch_applied:false,phase_alignment_applied:false,source_audio_rewritten:false,human_vocal_producer_review_required:true,alignment_correction_capability:"creative.music.vocal_timing",artistic_tightness_inferred:false};}
export const CreativeMusicVocalStackAlignmentRuntime=Object.freeze({contract:CONTRACT,analyze:analyzeMusicVocalStackAlignment});
