const CONTRACT="AVANTIQO_PROFESSIONAL_AUDIO_DELIVERY_PROFILE_V1";
const PROFILES=Object.freeze({
  music_release:Object.freeze({id:"music_release",label:"Music Release",picture_lock_required:false,bwf_required:false,required_sample_rate:null,required_bit_depth:24,allowed_layouts:["stereo","5.1","7.1","7.1.4"],me_required:false,fold_down_qc_required:false,dialogue_listening_required:false,loudness_policy:"MASTERING_PROFILE"}),
  picture_post:Object.freeze({id:"picture_post",label:"Picture Post",picture_lock_required:true,bwf_required:true,required_sample_rate:48000,required_bit_depth:24,allowed_layouts:["stereo","5.1","7.1","7.1.4"],me_required:true,fold_down_qc_required:true,dialogue_listening_required:true,loudness_policy:"PROJECT_TARGET"}),
  broadcast_handoff:Object.freeze({id:"broadcast_handoff",label:"Broadcast Handoff",picture_lock_required:true,bwf_required:true,required_sample_rate:48000,required_bit_depth:24,allowed_layouts:["stereo","5.1"],me_required:true,fold_down_qc_required:true,dialogue_listening_required:true,loudness_policy:"EXPLICIT_DELIVERY_TARGET_REQUIRED"}),
  cinema_handoff:Object.freeze({id:"cinema_handoff",label:"Cinema Handoff",picture_lock_required:true,bwf_required:true,required_sample_rate:48000,required_bit_depth:24,allowed_layouts:["5.1","7.1","7.1.4"],me_required:true,fold_down_qc_required:true,dialogue_listening_required:true,loudness_policy:"EXPLICIT_DELIVERY_TARGET_REQUIRED",dolby_branding:false}),
});
function text(v){return String(v??"").trim();}
export function listProfessionalAudioDeliveryProfiles(){return Object.values(PROFILES).map(p=>({...p,allowed_layouts:[...p.allowed_layouts]}));}
export function resolveProfessionalAudioDeliveryProfile(value="music_release"){const id=text(value||"music_release").toLowerCase();const profile=PROFILES[id];if(!profile)throw new Error(`CREATIVE_PRO_AUDIO_DELIVERY_PROFILE_INVALID:${id}`);return{contract:CONTRACT,...profile,allowed_layouts:[...profile.allowed_layouts]};}
export function validateProfessionalAudioDeliveryProfile({session={},profile:input,mastering={}}={}){const profile=typeof input==="string"?resolveProfessionalAudioDeliveryProfile(input):resolveProfessionalAudioDeliveryProfile(input?.id),failures=[],layout=session.spatial_audio?.layout_id||"stereo",rate=Math.round(Number(session.sample_rate)||48000);if(profile.picture_lock_required&&!session.picture_lock?.picture_lock_digest)failures.push("DELIVERY_PROFILE_PICTURE_LOCK_REQUIRED");if(profile.required_sample_rate&&rate!==profile.required_sample_rate)failures.push(`DELIVERY_PROFILE_SAMPLE_RATE_REQUIRED:${profile.required_sample_rate}`);if(!profile.allowed_layouts.includes(layout))failures.push(`DELIVERY_PROFILE_LAYOUT_NOT_ALLOWED:${layout}`);if(profile.loudness_policy==="EXPLICIT_DELIVERY_TARGET_REQUIRED"&&(!Number.isFinite(Number(mastering.target_lufs))||!Number.isFinite(Number(mastering.true_peak_dbtp))))failures.push("DELIVERY_PROFILE_EXPLICIT_LOUDNESS_TARGET_REQUIRED");return{contract:"AVANTIQO_PROFESSIONAL_AUDIO_DELIVERY_PROFILE_VALIDATION_V1",profile,success:failures.length===0,failures,session_layout:layout,session_sample_rate:rate,dolby_branding_authorized:false};}
export const CreativeProfessionalAudioDeliveryProfileRuntime=Object.freeze({contract:CONTRACT,list:listProfessionalAudioDeliveryProfiles,resolve:resolveProfessionalAudioDeliveryProfile,validate:validateProfessionalAudioDeliveryProfile});
