import crypto from "node:crypto";
const CONTRACT="AVANTIQO_PROFESSIONAL_AUDIO_LONG_FORM_WORKER_V2";
const REQUIRED_GRAPH_CONTRACT="AVANTIQO_MUSIC_WORKSTATION_GRAPH_PARITY_V1";
const RESPONSE_CONTRACT="AVANTIQO_PROFESSIONAL_AUDIO_LONG_FORM_WORKER_RESPONSE_V1";
function text(v){return String(v??"").trim();}function canonical(v){if(Array.isArray(v))return v.map(canonical);if(!v||typeof v!=="object")return v;return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));}function digest(v){return crypto.createHash("sha256").update(JSON.stringify(canonical(v))).digest("hex");}
export function inspectProfessionalAudioLongFormWorker(environment=process.env){const advertised=text(environment.AVANTIQO_AUDIO_LONG_FORM_WORKER_GRAPH_CONTRACT),endpoint=text(environment.AVANTIQO_AUDIO_LONG_FORM_WORKER_URL),token=text(environment.AVANTIQO_AUDIO_LONG_FORM_WORKER_TOKEN),ready=advertised===REQUIRED_GRAPH_CONTRACT&&Boolean(endpoint)&&Boolean(token);return{contract:CONTRACT,required_graph_contract:REQUIRED_GRAPH_CONTRACT,advertised_graph_contract:advertised||null,worker_url_configured:Boolean(endpoint),worker_token_configured:Boolean(token),ready,execution_authorized:ready,ffmpeg_only_fallback_allowed:false,browser_fallback_allowed:false,blocking_reason:ready?null:!endpoint?"LONG_FORM_PARITY_WORKER_URL_REQUIRED":!token?"LONG_FORM_PARITY_WORKER_TOKEN_REQUIRED":"LONG_FORM_WORKER_GRAPH_CONTRACT_MISMATCH"};}
export function buildProfessionalAudioLongFormWorkerEnvelope({organization_id,creative_project_id,plan,graph_fingerprint,session_snapshot,asset_urls={}}={}){if(!organization_id||!creative_project_id||!plan?.plan_hash||!graph_fingerprint)throw new Error("CREATIVE_AUDIO_LONG_FORM_WORKER_ENVELOPE_INVALID");const body={contract:"AVANTIQO_PROFESSIONAL_AUDIO_LONG_FORM_JOB_V1",organization_id,creative_project_id,plan_hash:plan.plan_hash,graph_fingerprint,project_revision:plan.project_revision,delivery_profile_id:plan.delivery_profile_id,delivery_language:plan.delivery_language,picture_lock_digest:plan.picture_lock_digest,sample_rate:plan.sample_rate,bit_depth:plan.bit_depth,channels:plan.channels,channel_layout:plan.channel_layout,speaker_order:plan.speaker_order,duration_seconds:plan.duration_seconds,total_frames:plan.total_frames,chunks:plan.chunks,absolute_timeline_required:true,chunk_processor_state:plan.chunk_processor_state,concat_mode:plan.concat_mode,final_mastering_after_assembly_required:true,chunk_loudness_normalization_forbidden:true,per_chunk_limiter_forbidden:true,rf64_auto:true,bwf_required:plan.bwf_required,session_snapshot,asset_urls};return{...body,job_hash:digest(body)};}
async function callWorker(path,payload,environment=process.env){const worker=inspectProfessionalAudioLongFormWorker(environment);if(!worker.ready)throw new Error(worker.blocking_reason);const base=text(environment.AVANTIQO_AUDIO_LONG_FORM_WORKER_URL).replace(/\/+$/,""),response=await fetch(`${base}${path}`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${text(environment.AVANTIQO_AUDIO_LONG_FORM_WORKER_TOKEN)}`},body:JSON.stringify(payload),cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`CREATIVE_AUDIO_LONG_FORM_WORKER_HTTP_${response.status}`);if(body.contract!==RESPONSE_CONTRACT)throw new Error("CREATIVE_AUDIO_LONG_FORM_WORKER_RESPONSE_CONTRACT_INVALID");return body;}
export async function submitProfessionalAudioLongFormWorkerJob(input,environment=process.env){const envelope=input?.envelope||buildProfessionalAudioLongFormWorkerEnvelope(input),response=await callWorker("/v1/audio/long-form/render",envelope,environment);if(!text(response.job_id))throw new Error("CREATIVE_AUDIO_LONG_FORM_WORKER_JOB_ID_REQUIRED");if(response.job_hash&&response.job_hash!==envelope.job_hash)throw new Error("CREATIVE_AUDIO_LONG_FORM_WORKER_JOB_HASH_MISMATCH");return{worker_contract:CONTRACT,envelope,response,job_id:response.job_id,job_hash:envelope.job_hash,pending:response.status!=="COMPLETED"};}
export async function pollProfessionalAudioLongFormWorkerJob({job_id,job_hash},environment=process.env){if(!text(job_id)||!text(job_hash))throw new Error("CREATIVE_AUDIO_LONG_FORM_WORKER_POLL_IDENTITY_REQUIRED");const response=await callWorker("/v1/audio/long-form/status",{contract:"AVANTIQO_PROFESSIONAL_AUDIO_LONG_FORM_STATUS_V1",job_id,job_hash},environment);if(response.job_hash&&response.job_hash!==job_hash)throw new Error("CREATIVE_AUDIO_LONG_FORM_WORKER_POLL_HASH_MISMATCH");return response;}
export const CreativeProfessionalAudioLongFormWorkerRuntime=Object.freeze({contract:CONTRACT,requiredGraphContract:REQUIRED_GRAPH_CONTRACT,responseContract:RESPONSE_CONTRACT,inspect:inspectProfessionalAudioLongFormWorker,envelope:buildProfessionalAudioLongFormWorkerEnvelope,submit:submitProfessionalAudioLongFormWorkerJob,poll:pollProfessionalAudioLongFormWorkerJob});
