import { CreativeAssetsRuntime } from "@/lib/creative/assets/runtime/CreativeAssetsRuntime";
import {
  dispatchAudioTask,
} from "@/lib/creative/audio/runtime/AudioQueueRuntime";
import {
  unwrapAudioOutput,
} from "@/lib/creative/audio/runtime/AudioFinishingContractRuntime";
import { ProductionTaskRuntime } from "@/lib/operations/tasks/runtime/ProductionTaskRuntime";

const AUDIO_BUCKET = "creative-assets";
const SOURCE_KIND = "SOURCE";
const MASTER_KIND = "MASTER";

function list(value) {
  return Array.isArray(value) ? value.filter(Boolean) : [];
}

function text(value) {
  return String(value ?? "").trim();
}

function object(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : {};
}

function finite(value, fallback = null) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function deepValue(value, keys, depth = 0, seen = new Set()) {
  if (value === null || value === undefined || depth > 9) return null;
  if (typeof value !== "object") return null;
  if (seen.has(value)) return null;
  seen.add(value);

  if (Array.isArray(value)) {
    for (const entry of value) {
      const nested = deepValue(entry, keys, depth + 1, seen);
      if (nested !== null && nested !== undefined && nested !== "") return nested;
    }
    return null;
  }

  for (const key of keys) {
    if (Object.prototype.hasOwnProperty.call(value, key)) {
      const candidate = value[key];
      if (candidate !== null && candidate !== undefined && candidate !== "") return candidate;
    }
  }

  for (const child of Object.values(value)) {
    const nested = deepValue(child, keys, depth + 1, seen);
    if (nested !== null && nested !== undefined && nested !== "") return nested;
  }
  return null;
}

export function musicStorageReference(value = {}) {
  const candidate = deepValue(value, ["storage_reference", "storageReference"]);
  return text(candidate);
}

export function musicGeneratedSeed(value = {}) {
  const candidate = deepValue(value, ["seed", "generation_seed", "generationSeed"]);
  const number = finite(candidate, null);
  return number === null ? null : Math.trunc(number);
}

function safeFileName(title, usageId, suffix = "") {
  const stem = text(title || "avantiqo-music")
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 72) || "avantiqo-music";
  const usage = text(usageId).replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 8);
  const extra = text(suffix).replace(/[^a-zA-Z0-9_-]/g, "");
  return [stem, usage, extra].filter(Boolean).join("-");
}

async function projectMusicAssets({ organizationId, projectId, missionId }) {
  const assets = await CreativeAssetsRuntime.list({
    organization_id: organizationId,
    creative_project_id: projectId || null,
    creative_mission_id: missionId || null,
    limit: 600,
  });
  return assets.filter((asset) => text(asset.metadata?.media_kind).toUpperCase() === "MUSIC");
}

function nextVersion(assets = []) {
  return Math.max(
    0,
    ...assets
      .filter((asset) => text(asset.metadata?.music_asset_kind).toUpperCase() !== MASTER_KIND)
      .map((asset) => finite(asset.metadata?.music_version, 0) || 0),
  ) + 1;
}

function publicAsset(asset) {
  if (!asset) return null;
  return {
    id: asset.id,
    title: asset.title || asset.name || asset.file_name || null,
    file_url: asset.file_url || null,
    asset_type: asset.asset_type || null,
    metadata: asset.metadata || {},
  };
}

export async function persistMusicGenerationAsset({
  organizationId,
  projectId = null,
  missionId = null,
  result,
  session = {},
  usage = null,
}) {
  if (!organizationId) throw new Error("organization_id required");
  if (!result || result.pending === true || result.failed === true) return null;

  const reference = musicStorageReference(result);
  if (!reference) return null;

  const usageId = text(usage?.id || result?.usage?.id);
  const assets = await projectMusicAssets({ organizationId, projectId, missionId });
  const existing = assets.find((asset) => (
    text(asset.file_url) === reference ||
    (usageId && text(asset.metadata?.music_usage_id) === usageId &&
      text(asset.metadata?.music_asset_kind || SOURCE_KIND).toUpperCase() === SOURCE_KIND)
  ));
  if (existing) return existing;

  const title = text(session.title || "Avantiqo composition").slice(0, 160);
  const version = nextVersion(assets);
  const seed = musicGeneratedSeed(result);
  const metadata = object(usage?.metadata);

  return CreativeAssetsRuntime.create({
    organization_id: organizationId,
    creative_project_id: projectId,
    creative_mission_id: missionId,
    asset_type: "AUDIO",
    file_url: reference,
    file_name: `${safeFileName(title, usageId, `v${version}`)}.wav`,
    name: title,
    title,
    description: "Original composition generated by Avantiqo Music Studio.",
    ai_generated: true,
    provider: result.provider || usage?.provider || "avantiqo-audio",
    engine: "AVANTIQO_MUSIC",
    prompt: null,
    metadata: {
      media_kind: "MUSIC",
      mime_type: "audio/wav",
      music_asset_kind: SOURCE_KIND,
      storage_reference: reference,
      music_usage_id: usageId || null,
      music_session_id: usageId ? `music:${usageId}` : null,
      music_version: version,
      music_operation: text(metadata.operation || "AVANTIQO_MUSIC_STUDIO_COMPOSE"),
      music_provider_job_id: text(result.provider_job_id || usage?.provider_request_id) || null,
      mastering_profile: text(session.mastering_profile || metadata.mastering_profile || "streaming"),
      generation_seed: seed,
      duration_seconds: finite(session.duration_seconds, null),
      bpm: finite(session.bpm, null),
      keyscale: text(session.keyscale) || null,
      timesignature: text(session.timesignature) || null,
      instrumental: session.instrumental !== false,
      style: text(session.style) || null,
      mood: text(session.mood) || null,
      owned_engine: true,
      engine_family: "ACE_STEP_1_5",
      certified_capability: "ai.music.generate",
      provider_selection_exposed: false,
      user_prompt_surface: false,
      music_pipeline_status: "GENERATED",
      generated_at: new Date().toISOString(),
    },
  });
}

async function ensureSourceTask({
  organizationId,
  projectId,
  sourceAsset,
  session,
  usage,
  result,
}) {
  const usageId = text(usage?.id || sourceAsset?.metadata?.music_usage_id);
  const tasks = await ProductionTaskRuntime.list({
    organization_id: organizationId,
    creative_project_id: projectId,
  });
  let sourceTask = tasks.find((task) => (
    text(task.metadata?.music_usage_id) === usageId &&
    text(task.metadata?.music_pipeline_role).toUpperCase() === SOURCE_KIND
  )) || null;

  if (!sourceTask) {
    sourceTask = await ProductionTaskRuntime.create({
      organization_id: organizationId,
      creative_project_id: projectId,
      type: "GENERATE_MUSIC",
      status: "WAITING",
      title: session.title || sourceAsset.title || "Avantiqo music source",
      description: "Durable source evidence for Avantiqo Music automatic finishing.",
      service_id: "ai.music.generate",
      service_code: "ai.music.generate",
      capability: "ai.music.generate",
      priority: 90,
      input: {
        output_spec: {
          duration_seconds: finite(session.duration_seconds, null),
          format: "wav",
          sample_rate: 48000,
          channels: 2,
        },
      },
      cost: {
        estimated: finite(usage?.customer_price, 0) || 0,
        actual: finite(usage?.customer_price, 0) || 0,
        currency: usage?.currency || null,
        approved: true,
      },
      timing: { estimated_seconds: finite(session.duration_seconds, 0) || 0 },
      review: { required: false, approved: true },
      metadata: {
        workflow_kind: "AUDIO",
        production_step_id: "music",
        production_step_index: 1,
        audio_role: "program",
        music_pipeline_role: SOURCE_KIND,
        music_usage_id: usageId || null,
        source_asset_id: sourceAsset.id,
        music_version: sourceAsset.metadata?.music_version || null,
        mastering_profile: session.mastering_profile || null,
      },
    });
  }

  if (sourceTask.status !== "COMPLETED") {
    sourceTask = await ProductionTaskRuntime.complete(sourceTask.id, {
      provider: result?.provider || usage?.provider || "avantiqo-audio",
      settlement: result?.settlement || "CHARGED",
      output: {
        type: "ASSET",
        file_url: sourceAsset.file_url,
        audio_url: sourceAsset.file_url,
        storage_reference: sourceAsset.file_url,
        mime_type: "audio/wav",
        duration_seconds: finite(session.duration_seconds, null),
        seed: sourceAsset.metadata?.generation_seed ?? null,
      },
    });
  }

  return sourceTask;
}

async function ensureFinishTask({ organizationId, projectId, sourceTask, sourceAsset, session, usage }) {
  const usageId = text(usage?.id || sourceAsset?.metadata?.music_usage_id);
  const tasks = await ProductionTaskRuntime.list({
    organization_id: organizationId,
    creative_project_id: projectId,
  });
  let finishTask = tasks.find((task) => (
    text(task.metadata?.music_usage_id) === usageId &&
    text(task.metadata?.music_pipeline_role).toUpperCase() === MASTER_KIND
  )) || null;

  if (!finishTask) {
    const mastering = object(session.mastering);
    finishTask = await ProductionTaskRuntime.create({
      organization_id: organizationId,
      creative_project_id: projectId,
      type: "EXECUTE_CAPABILITY",
      status: "WAITING",
      title: `Master ${session.title || sourceAsset.title || "Avantiqo composition"}`,
      description: "Automatically master the generated composition, validate loudness/true peak, export release files and produce waveform evidence.",
      service_id: "creative.audio.finish",
      service_code: "creative.audio.finish",
      capability: "creative.audio.finish",
      priority: 91,
      depends_on: [sourceTask.id],
      input: {
        source_task_ids: [sourceTask.id],
        output_spec: {
          title: session.title || sourceAsset.title || "Avantiqo composition",
          tracks: [{
            source_task_id: sourceTask.id,
            role: "program",
            label: session.title || sourceAsset.title || "Music",
          }],
          loudness: {
            target_lufs: finite(mastering.target_lufs, -14),
            true_peak_dbtp: finite(mastering.true_peak_dbtp, -1),
            tolerance_lu: 0.5,
            true_peak_tolerance_db: 0.1,
          },
          sample_rate: 48000,
          channels: 2,
          deliveries: [
            { id: "release-wav", format: "wav", file_name: "master.wav", codec: "pcm_s24le" },
            { id: "release-mp3", format: "mp3", file_name: "master.mp3", bitrate: "320k" },
          ],
          waveform: { width: 1600, height: 400 },
        },
        storage_policy: { bucket: AUDIO_BUCKET },
      },
      cost: { estimated: 0, actual: 0, currency: usage?.currency || null, approved: true },
      timing: { estimated_seconds: 0 },
      review: { required: false, approved: true },
      metadata: {
        workflow_kind: "AUDIO",
        production_step_id: "finish",
        production_step_index: 2,
        deliverable_type: "MUSIC",
        release_candidate: true,
        music_pipeline_role: MASTER_KIND,
        music_usage_id: usageId || null,
        source_asset_id: sourceAsset.id,
        source_task_id: sourceTask.id,
        music_version: sourceAsset.metadata?.music_version || null,
        mastering_profile: session.mastering_profile || "streaming",
        storage_policy: { bucket: AUDIO_BUCKET },
      },
    });
  }

  return finishTask;
}

async function persistMasterAsset({ organizationId, projectId, missionId, sourceAsset, finishTask, session, usage }) {
  const output = object(unwrapAudioOutput(finishTask.output));
  const reference = text(output.master_url || output.audio_url || output.file_url || output.url);
  if (!reference) return null;

  const usageId = text(usage?.id || sourceAsset.metadata?.music_usage_id);
  const assets = await projectMusicAssets({ organizationId, projectId, missionId });
  const existing = assets.find((asset) => (
    text(asset.metadata?.music_asset_kind).toUpperCase() === MASTER_KIND &&
    (
      text(asset.metadata?.music_finish_task_id) === text(finishTask.id) ||
      (usageId && text(asset.metadata?.music_usage_id) === usageId)
    )
  ));
  if (existing) return existing;

  const title = text(session.title || sourceAsset.title || "Avantiqo composition");
  const masterReport = object(output.master_report);
  const masterAsset = await CreativeAssetsRuntime.create({
    organization_id: organizationId,
    creative_project_id: projectId,
    creative_mission_id: missionId,
    asset_type: "AUDIO",
    file_url: reference,
    file_name: `${safeFileName(title, usageId, `v${sourceAsset.metadata?.music_version || 1}-master`)}.wav`,
    name: `${title} — Master`,
    title: `${title} — Master`,
    description: "Release-ready Avantiqo master with loudness and true-peak validation.",
    ai_generated: true,
    provider: "avantiqo-local-audio-worker",
    engine: "AVANTIQO_AUDIO_FINISHING",
    prompt: null,
    metadata: {
      media_kind: "MUSIC",
      mime_type: output.mime_type || "audio/wav",
      music_asset_kind: MASTER_KIND,
      music_usage_id: usageId || null,
      music_session_id: sourceAsset.metadata?.music_session_id || (usageId ? `music:${usageId}` : null),
      music_version: sourceAsset.metadata?.music_version || null,
      source_asset_id: sourceAsset.id,
      music_source_task_id: sourceAsset.metadata?.music_source_task_id || finishTask.metadata?.source_task_id || null,
      music_finish_task_id: finishTask.id,
      mastering_profile: session.mastering_profile || sourceAsset.metadata?.mastering_profile || "streaming",
      master_id: output.master_id || masterReport.master_id || null,
      waveform_url: output.waveform_url || masterReport.waveform?.url || null,
      integrated_lufs: finite(masterReport.master?.integrated_lufs, null),
      true_peak_dbtp: finite(masterReport.master?.true_peak_dbtp, null),
      release_candidate: output.release_candidate === true,
      deliveries: list(output.files).map((file) => ({
        name: file?.name || null,
        url: file?.url || null,
        mime_type: file?.mime_type || null,
      })),
      owned_engine: true,
      finishing_runtime: "AVANTIQO_AUDIO_FINISHING",
      music_pipeline_status: "MASTERED",
      mastered_at: new Date().toISOString(),
    },
  });

  await CreativeAssetsRuntime.update(sourceAsset.id, {
    metadata: {
      ...(sourceAsset.metadata || {}),
      music_pipeline_status: "MASTERED",
      music_source_task_id: finishTask.metadata?.source_task_id || null,
      music_finish_task_id: finishTask.id,
      master_asset_id: masterAsset.id,
      mastered_at: new Date().toISOString(),
    },
  });

  return masterAsset;
}

export async function ensureMusicMaster({
  organizationId,
  projectId = null,
  missionId = null,
  sourceAsset,
  session = {},
  usage = null,
  result = null,
  retryFailed = false,
}) {
  if (!sourceAsset) return { status: "WAITING_FOR_SOURCE", ready: false, failed: false };
  if (!projectId) {
    return {
      status: "PROJECT_REQUIRED",
      ready: false,
      failed: false,
      source_asset: publicAsset(sourceAsset),
    };
  }

  const sourceTask = await ensureSourceTask({
    organizationId,
    projectId,
    sourceAsset,
    session,
    usage,
    result,
  });
  let finishTask = await ensureFinishTask({
    organizationId,
    projectId,
    sourceTask,
    sourceAsset,
    session,
    usage,
  });

  if (finishTask.status === "FAILED" && retryFailed) {
    finishTask = await ProductionTaskRuntime.update(finishTask.id, {
      status: "WAITING",
      error: null,
      output: {},
      timing: {
        ...(finishTask.timing || {}),
        started_at: null,
        completed_at: null,
      },
      metadata: {
        ...(finishTask.metadata || {}),
        music_finish_retry_at: new Date().toISOString(),
      },
    });
  }

  if (!["COMPLETED", "FAILED"].includes(finishTask.status)) {
    finishTask = await dispatchAudioTask(finishTask);
  }

  if (finishTask.status === "FAILED") {
    return {
      status: "FAILED",
      ready: false,
      failed: true,
      error: finishTask.error || "CREATIVE_MUSIC_MASTERING_FAILED",
      source_task_id: sourceTask.id,
      finish_task_id: finishTask.id,
      source_asset: publicAsset(sourceAsset),
      master_asset: null,
    };
  }

  const masterAsset = await persistMasterAsset({
    organizationId,
    projectId,
    missionId,
    sourceAsset,
    finishTask,
    session,
    usage,
  });

  return {
    status: masterAsset ? "MASTERED" : "MASTER_OUTPUT_PENDING",
    ready: Boolean(masterAsset),
    failed: false,
    source_task_id: sourceTask.id,
    finish_task_id: finishTask.id,
    source_asset: publicAsset(sourceAsset),
    master_asset: publicAsset(masterAsset),
  };
}

export async function musicAssetHistory({ organizationId, projectId = null, missionId = null }) {
  const assets = await projectMusicAssets({ organizationId, projectId, missionId });
  return assets
    .slice()
    .sort((left, right) => {
      const versionDelta = finite(right.metadata?.music_version, 0) - finite(left.metadata?.music_version, 0);
      if (versionDelta) return versionDelta;
      const leftMaster = text(left.metadata?.music_asset_kind).toUpperCase() === MASTER_KIND ? 1 : 0;
      const rightMaster = text(right.metadata?.music_asset_kind).toUpperCase() === MASTER_KIND ? 1 : 0;
      return rightMaster - leftMaster;
    })
    .map(publicAsset);
}

export const CreativeMusicFinishingRuntime = {
  persistGeneration: persistMusicGenerationAsset,
  ensureMaster: ensureMusicMaster,
  history: musicAssetHistory,
};
