import { createHash } from "node:crypto";
import { spawn } from "node:child_process";
import { materializeMedia } from "@/lib/creative/media/runtime/CreativeMediaInspectionRuntime";

export const AUDIO_POST_DIALOGUE_MATCH_RENDER_CONTRACT="AVANTIQO_AUDIO_POST_DIALOGUE_MATCH_RENDER_V1";
const FREQ=Object.freeze({low:120,body:350,presence:2500,air:7000});
function text(v){return String(v??"").trim();}
function run(cmd,args,timeout=240000){return new Promise((resolve,reject)=>{const child=spawn(cmd,args,{shell:false,stdio:["ignore","pipe","pipe"]}),out=[],err=[],timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("AUDIO_POST_DIALOGUE_MATCH_RENDER_TIMEOUT"));},timeout);child.stdout.on("data",c=>out.push(c));child.stderr.on("data",c=>err.push(c));child.on("error",e=>{clearTimeout(timer);reject(e);});child.on("close",code=>{clearTimeout(timer);const stderr=Buffer.concat(err).toString("utf8");code===0?resolve(Buffer.concat(out)):reject(new Error(stderr||`AUDIO_POST_DIALOGUE_MATCH_RENDER_EXIT_${code}`));});});}
export async function renderApprovedAudioPostDialogueMatch({organization_id,source_asset={},plan={},approval={},media_tools={}}={}){if(!organization_id)throw new Error("AUDIO_POST_DIALOGUE_MATCH_RENDER_ORGANIZATION_REQUIRED");if(text(plan.contract)!=="AVANTIQO_AUDIO_POST_DIALOGUE_MATCH_V1"||text(approval.contract)!=="AVANTIQO_AUDIO_POST_DIALOGUE_MATCH_APPROVAL_V1"||approval.status!=="APPROVED")throw new Error("AUDIO_POST_DIALOGUE_MATCH_RENDER_APPROVAL_REQUIRED");if(text(approval.plan_fingerprint)!==text(plan.plan_fingerprint))throw new Error("AUDIO_POST_DIALOGUE_MATCH_RENDER_FINGERPRINT_MISMATCH");if(text(source_asset.id)!==text(plan.adr_asset_id))throw new Error("AUDIO_POST_DIALOGUE_MATCH_RENDER_SOURCE_MISMATCH");const url=text(source_asset.file_url||source_asset.url);if(!url)throw new Error("AUDIO_POST_DIALOGUE_MATCH_RENDER_SOURCE_URL_REQUIRED");const filters=[`volume=${Number(approval.approved_gain_match_db||0)}dB`];for(const move of approval.approved_eq_moves||[]){const hz=FREQ[text(move.band).toLowerCase()];if(!hz)continue;filters.push(`equalizer=f=${hz}:width_type=o:width=1:g=${Number(move.change_db||0)}`);}const ffmpeg=text(media_tools.ffmpeg||process.env.CREATIVE_FFMPEG_PATH)||"ffmpeg",media=await materializeMedia({organization_id,url,file_name:source_asset.file_name||"adr.wav",mime_type:source_asset.metadata?.mime_type||"audio/wav",policy:{max_bytes:1_073_741_824,timeout_ms:300000,max_redirects:0}});try{const bytes=await run(ffmpeg,["-hide_banner","-loglevel","error","-i",media.file_path,"-vn","-af",filters.join(","),"-ar","48000","-c:a","pcm_s24le","-f","wav","-"]),hash=createHash("sha256").update(bytes).digest("hex");return{contract:AUDIO_POST_DIALOGUE_MATCH_RENDER_CONTRACT,output_bytes:bytes,output_file_name:`${text(source_asset.file_name||source_asset.id||"adr").replace(/\.[^.]+$/,'')}-dialogue-match.wav`,checksum_sha256:hash,filter_chain:filters.join(","),source_asset_id:source_asset.id,production_asset_id:plan.production_asset_id,plan_fingerprint:plan.plan_fingerprint,applied_gain_match_db:approval.approved_gain_match_db,applied_eq_moves:approval.approved_eq_moves||[],room_tone_printed:false,perspective_reverb_printed:false,source_audio_preserved:true,render_new_asset_only:true,automatic_processing_authority:false};}finally{await media.cleanup().catch(()=>{});}}
export const CreativeAudioPostDialogueMatchRenderRuntime=Object.freeze({contract:AUDIO_POST_DIALOGUE_MATCH_RENDER_CONTRACT,render:renderApprovedAudioPostDialogueMatch});
