import { createHash } from "node:crypto";
import { spawn } from "node:child_process";
import { materializeMedia } from "@/lib/creative/media/runtime/CreativeMediaInspectionRuntime";

export const AUDIO_POST_DIALOGUE_PROFILE_CONTRACT="AVANTIQO_AUDIO_POST_DIALOGUE_PROFILE_V1";
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function db(v){return 20*Math.log10(Math.max(1e-12,v));}
function run(cmd,args,timeout=180000){return new Promise((resolve,reject)=>{const child=spawn(cmd,args,{shell:false,stdio:["ignore","pipe","pipe"]}),out=[],err=[],timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("AUDIO_POST_DIALOGUE_PROFILE_PROCESS_TIMEOUT"));},timeout);child.stdout.on("data",c=>out.push(c));child.stderr.on("data",c=>err.push(c));child.on("error",e=>{clearTimeout(timer);reject(e);});child.on("close",code=>{clearTimeout(timer);const stderr=Buffer.concat(err).toString("utf8");if(code!==0)reject(new Error(stderr||`AUDIO_POST_DIALOGUE_PROFILE_PROCESS_EXIT_${code}`));else resolve(Buffer.concat(out));});});}
function floats(buf){const n=Math.floor(buf.length/4),a=new Float32Array(n);for(let i=0;i<n;i++)a[i]=buf.readFloatLE(i*4);return a;}
function lowpass(input,rate,cutoff){const out=new Float32Array(input.length),alpha=1-Math.exp((-2*Math.PI*Math.max(20,Math.min(rate*.45,cutoff)))/rate);let y=0;for(let i=0;i<input.length;i++){y+=alpha*(finite(input[i])-y);out[i]=y;}return out;}
function subtract(a,b){const out=new Float32Array(Math.max(a.length,b.length));for(let i=0;i<out.length;i++)out[i]=finite(a[i])-finite(b[i]);return out;}
function rms(a){let s=0;for(const v of a)s+=v*v;return Math.sqrt(s/Math.max(1,a.length));}
function digest(value){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
export async function analyzeAudioPostDialogueProfile({organization_id,asset={},media_tools={}}={}){if(!organization_id)throw new Error("AUDIO_POST_DIALOGUE_PROFILE_ORGANIZATION_REQUIRED");const url=text(asset.file_url||asset.audio_url||asset.url);if(!url)throw new Error("AUDIO_POST_DIALOGUE_PROFILE_SOURCE_REQUIRED");const ffmpeg=text(media_tools.ffmpeg||process.env.CREATIVE_FFMPEG_PATH)||"ffmpeg",media=await materializeMedia({organization_id,url,file_name:asset.file_name||asset.name||"dialogue.wav",mime_type:asset.metadata?.mime_type||"audio/wav",policy:{max_bytes:1_073_741_824,timeout_ms:300000,max_redirects:0}});try{const rate=24000,raw=await run(ffmpeg,["-hide_banner","-loglevel","error","-i",media.file_path,"-vn","-ac","1","-ar",String(rate),"-f","f32le","-acodec","pcm_f32le","-"]),samples=floats(raw);if(samples.length<rate/4)throw new Error("AUDIO_POST_DIALOGUE_PROFILE_AUDIO_TOO_SHORT");const lp180=lowpass(samples,rate,180),lp700=lowpass(samples,rate,700),lp4000=lowpass(samples,rate,4000),bands={low:Number(db(rms(lp180)).toFixed(2)),body:Number(db(rms(subtract(lp700,lp180))).toFixed(2)),presence:Number(db(rms(subtract(lp4000,lp700))).toFixed(2)),air:Number(db(rms(subtract(samples,lp4000))).toFixed(2))};let peak=0;for(const v of samples)peak=Math.max(peak,Math.abs(v));const core={contract:AUDIO_POST_DIALOGUE_PROFILE_CONTRACT,asset_id:asset.id||null,sample_rate:rate,sample_count:samples.length,duration_seconds:Number((samples.length/rate).toFixed(4)),rms_dbfs:Number(db(rms(samples)).toFixed(2)),peak_dbfs:Number(db(peak).toFixed(2)),bands};return Object.freeze({...core,profile_digest:digest(core),actual_audio_measured:true,semantic_quality_inferred:false,source_audio_rewritten:false});}finally{await media.cleanup().catch(()=>{});}}
export const CreativeAudioPostDialogueProfileRuntime=Object.freeze({contract:AUDIO_POST_DIALOGUE_PROFILE_CONTRACT,analyze:analyzeAudioPostDialogueProfile});
