const CONTRACT="AVANTIQO_MUSIC_MIDI_GROOVE_V1";
const PRESETS=Object.freeze({straight:{timing:[],velocity:[]},swing_54:{swing:0.54},swing_58:{swing:0.58},swing_62:{swing:0.62},laid_back:{offset_beats:0.018,velocity_scale:0.96},push:{offset_beats:-0.012,velocity_scale:1.03}});
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,min,max,f=min){return Math.max(min,Math.min(max,finite(v,f)));}
function deterministic(seed){let value=seed>>>0;return()=>{value=(1664525*value+1013904223)>>>0;return value/0xffffffff;};}
function seedFrom(value){const source=text(value)||"avantiqo";let seed=2166136261;for(let i=0;i<source.length;i+=1){seed^=source.charCodeAt(i);seed=Math.imul(seed,16777619);}return seed>>>0;}
export function applyMusicMidiGroove(clip={},input={}){if(!Array.isArray(clip.notes))throw new Error("CREATIVE_MUSIC_MIDI_GROOVE_CLIP_REQUIRED");const presetName=text(input.preset||"straight");const preset=PRESETS[presetName]||PRESETS.straight;const strength=clamp(input.strength,0,1,1),humanizeTimingMs=clamp(input.humanize_timing_ms,0,80,0),humanizeVelocity=clamp(input.humanize_velocity,0,40,0),bpm=clamp(input.bpm,30,300,120),spb=60/bpm;const random=deterministic(seedFrom(`${clip.id}:${input.seed||0}:${presetName}`));const source=structuredClone(clip);if(!source.groove_original){source.groove_original={notes:structuredClone(source.notes),immutable:true,captured_at:new Date().toISOString()};}
source.notes=source.notes.map((note,index)=>{const originalStart=finite(note.start_beat,0),originalVelocity=Math.round(clamp(note.velocity,1,127,100));let target=originalStart+finite(preset.offset_beats,0);if(Number.isFinite(preset.swing)){const eighthIndex=Math.round(originalStart/.5);if(eighthIndex%2===1){const straight=.5*eighthIndex;const pairStart=Math.floor(eighthIndex/2);const swung=pairStart+(preset.swing);target+=swung-straight;}}const jitterBeats=((random()*2-1)*humanizeTimingMs/1000)/spb;const nextStart=Math.max(0,originalStart+(target-originalStart)*strength+jitterBeats);const scaled=originalVelocity*finite(preset.velocity_scale,1);const velocityJitter=(random()*2-1)*humanizeVelocity;return{...note,start_beat:Math.round(nextStart*1e6)/1e6,velocity:Math.round(clamp(originalVelocity+(scaled-originalVelocity)*strength+velocityJitter,1,127,originalVelocity)),groove_source_start_beat:finite(note.groove_source_start_beat,originalStart),groove_source_velocity:finite(note.groove_source_velocity,originalVelocity),groove_note_index:index};}).sort((a,b)=>a.start_beat-b.start_beat||a.pitch-b.pitch);source.groove={contract:CONTRACT,preset:presetName,strength,humanize_timing_ms:humanizeTimingMs,humanize_velocity:humanizeVelocity,seed:text(input.seed||"0"),reversible:true,applied_at:new Date().toISOString()};return source;}
export function restoreMusicMidiGroove(clip={}){if(!clip.groove_original?.immutable||!Array.isArray(clip.groove_original.notes))throw new Error("CREATIVE_MUSIC_MIDI_GROOVE_ORIGINAL_MISSING");const next=structuredClone(clip);next.notes=structuredClone(next.groove_original.notes);delete next.groove;delete next.groove_original;return next;}
export const CreativeMusicMidiGrooveRuntime={contract:CONTRACT,presets:Object.keys(PRESETS),apply:applyMusicMidiGroove,restore:restoreMusicMidiGroove};
