import { createMusicAutomationLane } from "./CreativeMusicAutomationRuntime.js";
import { musicBeatToSeconds } from "./CreativeMusicTempoMapRuntime.js";

const CONTRACT = "AVANTIQO_MUSIC_MIX_AUTOMATION_DECISION_V1";
const OWNED_PREFIX = "mix-engineer-auto-";
function text(v){return String(v??"").trim();}
function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function role(track={}){const h=`${text(track.type)} ${text(track.name)}`.toLowerCase();if(/vocal|lead|vox|singer/.test(h))return "VOCAL";if(/guitar/.test(h))return "GUITAR";if(/keys|piano|synth|pad/.test(h))return "KEYS";if(/backing|stem|music|instrument/.test(h))return "BACKING";return "OTHER";}
function ownedLane(lane={}){return text(lane.id).startsWith(OWNED_PREFIX);}
function deltaFor(roleId, section={}){const intensity=clamp(finite(section.intensity,.5),0,1);const type=text(section.type).toLowerCase();if(roleId==="VOCAL"){let d=(intensity-.55)*1.3;if(type==="chorus")d+=.2;if(type==="intro"||type==="outro")d-=.15;return clamp(d,-.5,.8);}if(["GUITAR","KEYS","BACKING"].includes(roleId)){const vocalFocus=(type==="chorus"||type==="pre_chorus")?1:0;return clamp(-(intensity-.55)*.35-vocalFocus*.12,-.4,.2);}return 0;}
function pointsFor(track, sections, tempoMap, roleId){const base=finite(track.gain_db,0), points=[];for(let i=0;i<sections.length;i+=1){const s=sections[i],start=musicBeatToSeconds(tempoMap,s.start_beat),end=musicBeatToSeconds(tempoMap,s.end_beat),value=clamp(base+deltaFor(roleId,s),-60,12),prev=points.at(-1);if(i===0){points.push({time_seconds:Number(start.toFixed(3)),value:Number(value.toFixed(2))});}else{const ramp=.18,pre=Math.max(0,start-ramp),post=Math.min(end,start+ramp);if(prev&&pre>prev.time_seconds+.01)points.push({time_seconds:Number(pre.toFixed(3)),value:prev.value});points.push({time_seconds:Number(post.toFixed(3)),value:Number(value.toFixed(2))});}if(i===sections.length-1&&end>start)points.push({time_seconds:Number(end.toFixed(3)),value:Number(value.toFixed(2))});}return points.filter((p,i,a)=>!i||p.time_seconds>a[i-1].time_seconds+.001||p.value!==a[i-1].value);}
export function buildMusicMixAutomationPlan(session={}, arrangement={}){const sections=(arrangement.sections||[]).filter(s=>Number.isFinite(Number(s.start_beat))&&Number.isFinite(Number(s.end_beat))).sort((a,b)=>a.start_beat-b.start_beat);if(sections.length<2)return {contract:CONTRACT,status:"ARRANGEMENT_REQUIRED",lanes:[],section_count:sections.length,artistic_intent_inferred:false,mutation_authorized:false};const tempoMap=session.tempo_map||{initial_bpm:session.bpm||120,initial_time_signature:session.time_signature||"4/4"};const lanes=[];for(const track of session.tracks||[]){if(track.mute===true)continue;const r=role(track);if(!["VOCAL","GUITAR","KEYS","BACKING"].includes(r))continue;const existing=(session.automation_lanes||[]).find(l=>l.target_type==="track"&&l.target_id===track.id&&l.parameter==="gain_db");const blocked=Boolean(existing&&!ownedLane(existing));const points=pointsFor(track,sections,tempoMap,r);if(points.length<2)continue;lanes.push({id:existing&&ownedLane(existing)?existing.id:`${OWNED_PREFIX}${track.id}`,target_type:"track",target_id:track.id,track_name:track.name||"Track",role:r,parameter:"gain_db",interpolation:"linear",points,blocked_by_existing_manual_lane:blocked,decision:r==="VOCAL"?"section-aware vocal ride":"section-aware supporting energy ride",max_delta_db:r==="VOCAL"?.8:.4});}return {contract:CONTRACT,status:lanes.some(l=>!l.blocked_by_existing_manual_lane)?"AUTOMATION_PLAN_READY":"NO_SAFE_AUTOMATION_CHANGES",section_count:sections.length,lanes,arrangement_intent_source:"PERSISTED_SECTION_INTENSITY",artistic_intent_inferred:false,manual_automation_preserved:true,mutation_authorized:false};}
export function applyMusicMixAutomationPlan(session={},plan={}){const next=structuredClone(session);next.automation_lanes=Array.isArray(next.automation_lanes)?next.automation_lanes:[];for(const row of plan.lanes||[]){if(row.blocked_by_existing_manual_lane)continue;const lane=createMusicAutomationLane({id:row.id,target_type:row.target_type,target_id:row.target_id,parameter:row.parameter,interpolation:row.interpolation,enabled:true,points:row.points});const i=next.automation_lanes.findIndex(x=>x.id===lane.id);if(i>=0)next.automation_lanes[i]=lane;else next.automation_lanes.push(lane);}return next;}
export const CreativeMusicMixAutomationRuntime=Object.freeze({contract:CONTRACT,build:buildMusicMixAutomationPlan,apply:applyMusicMixAutomationPlan});
