import crypto from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";

import { materializeMedia } from "@/lib/creative/media/runtime/CreativeMediaInspectionRuntime";
import { createMusicSpatialAudioConfig } from "./CreativeMusicSpatialAudioRuntime.js";
import { normalizeMusicSurroundFinishTarget } from "./CreativeMusicSurroundFinishingContractRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_SURROUND_FINISH_V1";
function text(v){return String(v??"").trim();}function finite(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}function checksum(buffer){return crypto.createHash("sha256").update(buffer).digest("hex");}
function run(command,args,timeoutMs=600000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{shell:false,stdio:["ignore","pipe","pipe"]}),stdout=[],stderr=[];const timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("CREATIVE_MUSIC_SURROUND_FINISH_TIMEOUT"));},timeoutMs);child.stdout.on("data",c=>stdout.push(c));child.stderr.on("data",c=>stderr.push(c));child.on("error",e=>{clearTimeout(timer);reject(e);});child.on("close",code=>{clearTimeout(timer);const out={stdout:Buffer.concat(stdout).toString("utf8"),stderr:Buffer.concat(stderr).toString("utf8")};if(code===0)resolve(out);else reject(new Error(out.stderr||`CREATIVE_MUSIC_SURROUND_FINISH_EXIT_${code}`));});});}
function loudnessJson(stderr){const matches=[...String(stderr||"").matchAll(/\{\s*"input_i"[\s\S]*?\}/gm)];if(!matches.length)return null;try{return JSON.parse(matches.at(-1)[0]);}catch{return null;}}
async function measure(ffmpeg,file,target){const args=["-hide_banner","-nostats","-i",file,"-af",`loudnorm=I=${target.target_lufs}:LRA=${target.loudness_range_lu}:TP=${target.true_peak_dbtp}:print_format=json`,"-f","null","-"];const result=await run(ffmpeg,args,240000);const d=loudnessJson(result.stderr);if(!d)throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_MEASUREMENT_REQUIRED");return{integrated_lufs:finite(d.input_i),true_peak_dbtp:finite(d.input_tp),loudness_range_lu:finite(d.input_lra),threshold_lufs:finite(d.input_thresh),target_offset:finite(d.target_offset)};}
function twoPassFilter(target,m){return `loudnorm=I=${target.target_lufs}:LRA=${target.loudness_range_lu}:TP=${target.true_peak_dbtp}:measured_I=${m.integrated_lufs}:measured_LRA=${m.loudness_range_lu}:measured_TP=${m.true_peak_dbtp}:measured_thresh=${m.threshold_lufs}:offset=${m.target_offset}:linear=true:print_format=json`;}
async function probe(ffprobe,file){const out=await run(ffprobe,["-v","error","-show_entries","format=duration:stream=codec_name,codec_type,sample_rate,channels,channel_layout,bits_per_raw_sample","-of","json",file],120000),p=JSON.parse(out.stdout||"{}"),a=(p.streams||[]).find(x=>x.codec_type==="audio");if(!a)throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_AUDIO_REQUIRED");return{duration_seconds:finite(p.format?.duration),codec_name:text(a.codec_name),sample_rate:finite(a.sample_rate),channels:finite(a.channels),channel_layout:text(a.channel_layout),bits_per_raw_sample:finite(a.bits_per_raw_sample)};}

export async function finishMusicSurroundPremaster({organization_id,file_url,file_name=null,mime_type="audio/wav",layout_id,sample_rate=48000,lfe_low_pass_hz=120,target={},bwf=null,media_tools={}}={}){
 if(!organization_id)throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_ORGANIZATION_REQUIRED");if(!file_url)throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_SOURCE_REQUIRED");const spatial=createMusicSpatialAudioConfig({layout_id,lfe:{low_pass_hz:lfe_low_pass_hz}});if(!spatial.surround_enabled)throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_LAYOUT_REQUIRED");const masterTarget=normalizeMusicSurroundFinishTarget(target),ffmpeg=text(media_tools.ffmpeg||process.env.CREATIVE_FFMPEG_PATH)||"ffmpeg",ffprobe=text(media_tools.ffprobe||process.env.CREATIVE_FFPROBE_PATH)||"ffprobe",source=await materializeMedia({url:file_url,file_name:file_name||"surround-premaster.wav",mime_type,organization_id,policy:{max_bytes:2_147_483_648,timeout_ms:300000,max_redirects:0}}),root=await fs.mkdtemp(path.join(os.tmpdir(),"avantiqo-surround-finish-"));
 try{
  const preProbe=await probe(ffprobe,source.file_path);if(preProbe.channels!==spatial.channel_count)throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_SOURCE_CHANNEL_MISMATCH");const expectedLayout=spatial.layout_id==="5.1"?"5.1(side)":"7.1";if(preProbe.channel_layout!==expectedLayout)throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_SOURCE_LAYOUT_MISMATCH");if(preProbe.codec_name!=="pcm_s24le")throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_SOURCE_PCM24_REQUIRED");
  const preMeasurement=await measure(ffmpeg,source.file_path,masterTarget),floatPath=path.join(root,"surround-master-float.wav"),finalPath=path.join(root,"surround-master-24.wav");
  await run(ffmpeg,["-y","-i",source.file_path,"-af",twoPassFilter(masterTarget,preMeasurement),"-ar",String(Math.round(finite(sample_rate,48000))),"-c:a","pcm_f32le",floatPath]);
  const finalArgs=["-y","-i",floatPath,"-af",`aresample=${Math.round(finite(sample_rate,48000))}:osf=s32:output_sample_bits=24:dither_method=triangular`,"-c:a","pcm_s24le"];if(bwf?.enabled===true)finalArgs.push("-write_bext","1","-metadata",`description=${text(bwf.description||"Avantiqo Professional Audio Engine")}`,"-metadata",`originator=${text(bwf.originator||"Avantiqo")}`,"-metadata",`originator_reference=${text(bwf.originator_reference||"")}`,"-metadata",`time_reference=${Math.max(0,Math.round(finite(bwf.time_reference_samples,0)))}`);finalArgs.push(finalPath);
  await run(ffmpeg,finalArgs);
  const finalProbe=await probe(ffprobe,finalPath);if(finalProbe.channels!==spatial.channel_count||finalProbe.channel_layout!==expectedLayout)throw new Error("CREATIVE_MUSIC_SURROUND_FINISH_LAYOUT_NOT_PRESERVED");const postMeasurement=await measure(ffmpeg,finalPath,masterTarget),failures=[];if(!Number.isFinite(postMeasurement.integrated_lufs)||Math.abs(postMeasurement.integrated_lufs-masterTarget.target_lufs)>masterTarget.tolerance_lu)failures.push("SURROUND_FINISH_LOUDNESS_TARGET_MISSED");if(!Number.isFinite(postMeasurement.true_peak_dbtp)||postMeasurement.true_peak_dbtp>masterTarget.true_peak_dbtp+masterTarget.true_peak_tolerance_db)failures.push("SURROUND_FINISH_TRUE_PEAK_EXCEEDED");if(failures.length)throw new Error(`CREATIVE_MUSIC_SURROUND_FINISH_FAILED:${failures.join(",")}`);
  const buffer=await fs.readFile(finalPath);return{success:true,contract:CONTRACT,buffer,checksum:checksum(buffer),file_name:`master-${spatial.layout_id.replace(".","-")}-24bit.wav`,mime_type:"audio/wav",channel_layout:spatial.layout_id,ffmpeg_channel_layout:expectedLayout,channels:spatial.channel_count,speaker_order:[...spatial.speaker_order],sample_rate:finalProbe.sample_rate,bit_depth:24,pre_measurement:preMeasurement,post_measurement:postMeasurement,target:masterTarget,internal_master_format:"float32",final_integer_pcm_conversion_only:true,dither_applied:true,dither_method:"TPDF_TRIANGULAR",layout_preserved:true,bwf_requested:bwf?.enabled===true,time_reference_samples:bwf?.enabled===true?Math.max(0,Math.round(finite(bwf.time_reference_samples,0))):null,dolby_branded:false,dolby_certification_performed:false,provider_job_submitted:false,original_premaster_preserved:true};
 }finally{await source.cleanup().catch(()=>{});await fs.rm(root,{recursive:true,force:true}).catch(()=>{});}
}
export const CreativeMusicSurroundFinishingRuntime=Object.freeze({contract:CONTRACT,normalizeTarget:normalizeMusicSurroundFinishTarget,finish:finishMusicSurroundPremaster});
