import { applyMusicGroupProcessing } from "./CreativeMusicBusProcessingRuntime.js";
import { createMusicAuxBus, createMusicGroupBus, ensureMusicEngineeringBuses, upsertMusicTrackSend } from "./CreativeMusicMixerRoutingRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_VOCAL_PRODUCTION_BUS_V1";
const ROLE_MAP=Object.freeze({lead:"LEAD",lead_vocal:"LEAD",double:"DOUBLE",doubles:"DOUBLE",double_vocal:"DOUBLE",backing:"BACKING",backing_vocal:"BACKING",harmony:"HARMONY",harmony_vocal:"HARMONY",choir:"CHOIR",adlib:"ADLIB",ad_lib:"ADLIB"});
const BUS_BY_ROLE=Object.freeze({LEAD:"bus-vocal-lead",DOUBLE:"bus-vocal-double",BACKING:"bus-vocal-backing",HARMONY:"bus-vocal-harmony",CHOIR:"bus-vocal-choir",ADLIB:"bus-vocal-adlib"});
const ROLE_SETTINGS=Object.freeze({
  LEAD:{parallel_db:-14,eq:{high_pass_hz:75,low_shelf_db:0,low_shelf_hz:140,presence_db:.75,presence_hz:3200,presence_q:.85,high_shelf_db:.5,high_shelf_hz:9500},compressor:{enabled:true,threshold_db:-20,ratio:2.4,attack_ms:24,release_ms:150,knee_db:7,makeup_db:0},reverb_db:-18,delay_db:-23},
  DOUBLE:{parallel_db:-16,eq:{high_pass_hz:95,low_shelf_db:-1,low_shelf_hz:180,presence_db:.25,presence_hz:3500,presence_q:.9,high_shelf_db:0,high_shelf_hz:10000},compressor:{enabled:true,threshold_db:-22,ratio:3.2,attack_ms:15,release_ms:120,knee_db:8,makeup_db:0},reverb_db:-20,delay_db:-26},
  HARMONY:{parallel_db:-19,eq:{high_pass_hz:100,low_shelf_db:-.75,low_shelf_hz:180,presence_db:.2,presence_hz:3000,presence_q:.9,high_shelf_db:.25,high_shelf_hz:9500},compressor:{enabled:true,threshold_db:-22,ratio:3,attack_ms:18,release_ms:150,knee_db:8,makeup_db:0},reverb_db:-17,delay_db:-27},
  BACKING:{parallel_db:-21,eq:{high_pass_hz:110,low_shelf_db:-1,low_shelf_hz:200,presence_db:0,presence_hz:3200,presence_q:1,high_shelf_db:0,high_shelf_hz:9500},compressor:{enabled:true,threshold_db:-23,ratio:3.4,attack_ms:14,release_ms:140,knee_db:8,makeup_db:0},reverb_db:-16,delay_db:-29},
  ADLIB:{parallel_db:-17,eq:{high_pass_hz:90,low_shelf_db:-.5,low_shelf_hz:170,presence_db:.5,presence_hz:3500,presence_q:.85,high_shelf_db:.5,high_shelf_hz:10000},compressor:{enabled:true,threshold_db:-21,ratio:2.8,attack_ms:18,release_ms:130,knee_db:7,makeup_db:0},reverb_db:-18,delay_db:-19},
  CHOIR:{parallel_db:-22,eq:{high_pass_hz:120,low_shelf_db:-1.25,low_shelf_hz:220,presence_db:-.25,presence_hz:3000,presence_q:1,high_shelf_db:.25,high_shelf_hz:10000},compressor:{enabled:true,threshold_db:-24,ratio:3.5,attack_ms:20,release_ms:180,knee_db:9,makeup_db:0},reverb_db:-14,delay_db:-30},
});
function text(v){return String(v??"").trim();}
export function normalizeMusicVocalProductionRole(value){const raw=text(value).toLowerCase().replace(/[\s-]+/g,"_");return ROLE_MAP[raw]||null;}
function managedBus(session,id){return (session.buses||[]).find(bus=>bus.id===id);}
function ensureManagedGroup(session,{id,name,output_bus_id,processing}){const existing=managedBus(session,id);if(existing&&existing.type!=="group")throw new Error(`CREATIVE_MUSIC_VOCAL_BUS_ID_CONFLICT:${id}`);if(existing&&existing.vocal_production_managed!==true)throw new Error(`CREATIVE_MUSIC_VOCAL_BUS_MANUAL_CONFLICT:${id}`);let bus=existing?structuredClone(existing):createMusicGroupBus({id,name,output_bus_id});bus.name=name;bus.output_bus_id=output_bus_id;bus.vocal_production_managed=true;bus.vocal_production_contract=CONTRACT;bus=applyMusicGroupProcessing(bus,processing);const index=(session.buses||[]).findIndex(row=>row.id===id);if(index>=0)session.buses[index]=bus;else session.buses.push(bus);return bus;}
function ensureManagedSend(track,busId,levelDb){const existing=(track.sends||[]).find(send=>send.bus_id===busId);if(existing)return{track,preserved:true};const next=upsertMusicTrackSend(track,{bus_id:busId,level_db:levelDb,enabled:true,pre_fader:false});return{track:next,preserved:false};}
function rolePan(role,index,count){if(role==="LEAD")return 0;const spreads={DOUBLE:.38,HARMONY:.28,BACKING:.52,ADLIB:.18,CHOIR:.68},spread=spreads[role]||0;if(count<=1)return role==="ADLIB"?.12:0;const position=count===2?(index===0?-spread:spread):-spread+(2*spread*index)/Math.max(1,count-1);return Number(Math.max(-.9,Math.min(.9,position)).toFixed(3));}
export function buildMusicVocalProductionBuses(sessionInput={}){
  const session=ensureMusicEngineeringBuses(sessionInput),vocalTracks=(session.tracks||[]).filter(track=>String(track.type).toLowerCase()==="vocal"),failures=[],roles=[];
  for(const track of vocalTracks){const role=normalizeMusicVocalProductionRole(track.vocal_role);if(!role)failures.push(`VOCAL_PRODUCTION_ROLE_REQUIRED:${track.id}`);else roles.push({track_id:track.id,role});}
  if(vocalTracks.length&&!roles.some(row=>row.role==="LEAD"))failures.push("VOCAL_PRODUCTION_LEAD_REQUIRED");
  if(failures.length)return{contract:CONTRACT,success:false,session,failures,role_assignments:roles};
  const parallelExisting=managedBus(session,"bus-vocal-parallel");if(parallelExisting&&parallelExisting.type!=="aux")throw new Error("CREATIVE_MUSIC_VOCAL_PARALLEL_BUS_ID_CONFLICT");if(parallelExisting&&parallelExisting.vocal_production_managed!==true)throw new Error("CREATIVE_MUSIC_VOCAL_PARALLEL_MANUAL_CONFLICT");if(!parallelExisting){const parallel=createMusicAuxBus({id:"bus-vocal-parallel",type:"compressor",name:"VOCAL PARALLEL",gain_db:0,parameters:{threshold_db:-30,ratio:8,attack_ms:3,release_ms:120,knee_db:6,makeup_db:8,high_pass_hz:90,wet_db:-10}});parallel.vocal_production_managed=true;parallel.vocal_production_contract=CONTRACT;session.buses.push(parallel);}
  ensureManagedGroup(session,{id:"bus-vocal-all",name:"VOCAL MASTER",output_bus_id:"bus-master",processing:{eq:{high_pass_hz:55,low_shelf_db:0,low_shelf_hz:140,presence_db:.25,presence_hz:3200,presence_q:.8,high_shelf_db:.25,high_shelf_hz:10000},compressor:{enabled:true,threshold_db:-18,ratio:1.8,attack_ms:30,release_ms:180,knee_db:8,makeup_db:0}}});
  const usedRoles=[...new Set(roles.map(row=>row.role))];for(const role of usedRoles){const settings=ROLE_SETTINGS[role];ensureManagedGroup(session,{id:BUS_BY_ROLE[role],name:`VOCAL ${role}`,output_bus_id:"bus-vocal-all",processing:{eq:settings.eq,compressor:settings.compressor}});}
  const sendPreservation=[],panPreservation=[];const roleMembers=new Map(usedRoles.map(role=>[role,roles.filter(row=>row.role===role)]));session.tracks=(session.tracks||[]).map(track=>{const assignment=roles.find(row=>row.track_id===track.id);if(!assignment)return track;const role=assignment.role,settings=ROLE_SETTINGS[role],members=roleMembers.get(role)||[],memberIndex=members.findIndex(row=>row.track_id===track.id),manualPan=Math.abs(Number(track.pan)||0)>1e-6&&track.vocal_production_managed_pan!==true,targetPan=rolePan(role,memberIndex,members.length);let next={...track,vocal_role:role,output_bus_id:BUS_BY_ROLE[role],pan:manualPan?track.pan:targetPan,vocal_production_managed_pan:manualPan?false:true,vocal_production:{contract:CONTRACT,role,bus_id:BUS_BY_ROLE[role],pan:manualPan?track.pan:targetPan,manual_pan_preserved:manualPan,phase_widening_used:false,haas_delay_used:false,human_listening_review_required:true,automatic_acceptance:false}};panPreservation.push({track_id:track.id,role,pan:next.pan,manual_pan_preserved:manualPan});let send=ensureManagedSend(next,"bus-reverb",settings.reverb_db);next=send.track;sendPreservation.push({track_id:track.id,bus_id:"bus-reverb",manual_send_preserved:send.preserved});send=ensureManagedSend(next,"bus-delay",settings.delay_db);next=send.track;sendPreservation.push({track_id:track.id,bus_id:"bus-delay",manual_send_preserved:send.preserved});send=ensureManagedSend(next,"bus-vocal-parallel",settings.parallel_db);next=send.track;sendPreservation.push({track_id:track.id,bus_id:"bus-vocal-parallel",manual_send_preserved:send.preserved});return next;});
  const priorReference=text(session.vocal_production?.reference_lead_track_id),leadIds=new Set(roles.filter(row=>row.role==="LEAD").map(row=>row.track_id)),referenceLead=priorReference&&leadIds.has(priorReference)?priorReference:(leadIds.size===1?[...leadIds][0]:null);session.vocal_production={contract:CONTRACT,status:"ROUTED_REVIEW_REQUIRED",lead_track_count:roles.filter(row=>row.role==="LEAD").length,vocal_track_count:vocalTracks.length,roles:usedRoles,role_assignments:roles,reference_lead_track_id:referenceLead,bus_ids:["bus-vocal-all","bus-vocal-parallel",...usedRoles.map(role=>BUS_BY_ROLE[role])], parallel_compression:{bus_id:"bus-vocal-parallel",threshold_db:-30,ratio:8,attack_ms:3,release_ms:120,return_wet_db:-10,non_destructive:true},manual_send_preservation:sendPreservation,pan_placement:panPreservation,artificial_phase_widening_forbidden:true,haas_delay_widening_forbidden:true,source_audio_rewritten:false,non_destructive:true,human_listening_review_required:true,pitch_timing_correction_separately_certification_gated:true};
  return{contract:CONTRACT,success:true,session,failures:[],...session.vocal_production};
}
export function inspectMusicVocalProduction(session={}){const vocalTracks=(session.tracks||[]).filter(track=>String(track.type).toLowerCase()==="vocal"),missing=vocalTracks.filter(track=>!normalizeMusicVocalProductionRole(track.vocal_role)).map(track=>track.id),managed=(session.buses||[]).filter(bus=>bus.vocal_production_managed===true);return{contract:"AVANTIQO_MUSIC_VOCAL_PRODUCTION_QC_V1",vocal_track_count:vocalTracks.length,declared_role_count:vocalTracks.length-missing.length,missing_role_track_ids:missing,lead_track_count:vocalTracks.filter(track=>normalizeMusicVocalProductionRole(track.vocal_role)==="LEAD").length,managed_bus_count:managed.length,routed_track_count:vocalTracks.filter(track=>String(track.output_bus_id||"").startsWith("bus-vocal-")).length,professional_vocal_routing_ready:vocalTracks.length>0&&missing.length===0&&vocalTracks.some(track=>normalizeMusicVocalProductionRole(track.vocal_role)==="LEAD")&&managed.some(bus=>bus.id==="bus-vocal-all"),human_listening_review_required:true,pitch_timing_correction_separately_certification_gated:true};}
export const CreativeMusicVocalProductionBusRuntime=Object.freeze({contract:CONTRACT,normalizeRole:normalizeMusicVocalProductionRole,build:buildMusicVocalProductionBuses,inspect:inspectMusicVocalProduction});
