const CONTRACT="AVANTIQO_PICTURE_CONTACT_EVIDENCE_V1";
const ROLES=Object.freeze(["FOOT","HAND","BODY","PROP","DOOR","VEHICLE","MACHINERY","SURFACE"]);
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,a,b,f=0){return Math.max(a,Math.min(b,finite(v,f)));}
function box(v){const a=Array.isArray(v)?v:[0,0,0,0];return{x:finite(a[0]),y:finite(a[1]),w:Math.max(0,finite(a[2])),h:Math.max(0,finite(a[3]))};}
function center(b){return{x:b.x+b.w/2,y:b.y+b.h/2};}
function edgeDistance(a,b){const dx=Math.max(a.x-(b.x+b.w),b.x-(a.x+a.w),0),dy=Math.max(a.y-(b.y+b.h),b.y-(a.y+a.h),0);return Math.hypot(dx,dy);}
function overlap(a,b){const x=Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)),y=Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));return x*y;}
function speed(s){return Math.hypot(finite(s.dx),finite(s.dy));}
function sampleAt(track,t,tol=.08){let best=null,delta=Infinity;for(const s of track.samples||[]){const d=Math.abs(finite(s.time_seconds,-999)-t);if(d<delta){best=s;delta=d;}}return delta<=tol?best:null;}
function pairType(a,b){const roles=new Set([a.role,b.role]);if(roles.has("FOOT")&&roles.has("SURFACE"))return"FOOT_CONTACT";if(roles.has("HAND")&&roles.has("PROP"))return"PROP_CONTACT";if(roles.has("HAND")&&roles.has("DOOR"))return"DOOR_MOVEMENT";if(roles.has("BODY")&&roles.has("SURFACE"))return"BODY_CONTACT";if((roles.has("HAND")||roles.has("BODY"))&&roles.has("VEHICLE"))return"VEHICLE_INTERACTION";if((roles.has("HAND")||roles.has("BODY"))&&roles.has("MACHINERY"))return"MACHINERY_MOVEMENT";return null;}
export function normalizePictureObjectTrack(input={}){const role=text(input.role).toUpperCase();if(!ROLES.includes(role))throw new Error("PICTURE_CONTACT_TRACK_ROLE_INVALID:"+role);return{id:text(input.id)||"track",role,subject_id:text(input.subject_id)||null,object_id:text(input.object_id)||null,surface_material:text(input.surface_material||"UNKNOWN").toUpperCase(),samples:(input.samples||[]).map(s=>({time_seconds:Math.max(0,finite(s.time_seconds)),bbox:Array.isArray(s.bbox)?s.bbox.map(Number):[0,0,0,0],dx:finite(s.dx),dy:finite(s.dy),tracked_points:Math.max(0,finite(s.tracked_points)),mean_lk_error:s.mean_lk_error==null?null:Math.max(0,finite(s.mean_lk_error))})).sort((a,b)=>a.time_seconds-b.time_seconds)};}
export function derivePictureContactEvidence({tracks=[],frame_width=1920,frame_height=1080,max_gap_percent=1.5,min_confidence=.75}={}){const rows=(tracks||[]).map(normalizePictureObjectTrack),events=[];const diag=Math.max(1,Math.hypot(frame_width,frame_height)),gapLimit=diag*clamp(max_gap_percent,.1,10,1.5)/100;for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i],b=rows[j],eventType=pairType(a,b);if(!eventType)continue;const times=[...new Set([...(a.samples||[]).map(s=>s.time_seconds),...(b.samples||[]).map(s=>s.time_seconds)])].sort((x,y)=>x-y);let priorNear=false,priorSpeed=null;for(const t of times){const sa=sampleAt(a,t),sb=sampleAt(b,t);if(!sa||!sb)continue;const ba=box(sa.bbox),bb=box(sb.bbox),gap=edgeDistance(ba,bb),touch=overlap(ba,bb)>0||gap<=gapLimit,relativeSpeed=Math.hypot(finite(sa.dx)-finite(sb.dx),finite(sa.dy)-finite(sb.dy)),qualityA=clamp(sa.tracked_points/40,0,1,0)*(sa.mean_lk_error==null?1:clamp(1-sa.mean_lk_error/25,0,1,0)),qualityB=clamp(sb.tracked_points/40,0,1,0)*(sb.mean_lk_error==null?1:clamp(1-sb.mean_lk_error/25,0,1,0)),quality=Math.sqrt(qualityA*qualityB),motionChange=priorSpeed==null?0:clamp(Math.abs(relativeSpeed-priorSpeed)/12,0,1,0),contactStrength=touch?1:clamp(1-gap/Math.max(1,gapLimit),0,1,0),confidence=clamp(.55*contactStrength+.3*quality+.15*motionChange,0,1,0);if(touch&&!priorNear&&confidence>=min_confidence){const moving=a.role==="SURFACE"?b:a,target=a.role==="SURFACE"?a:b;events.push({id:"contact-"+a.id+"-"+b.id+"-"+Math.round(t*1000),event_type:eventType,time_seconds:t,confidence:Number(confidence.toFixed(4)),subject_id:moving.subject_id||target.subject_id||null,object_id:moving.object_id||target.object_id||null,surface_material:(a.role==="SURFACE"?a.surface_material:b.role==="SURFACE"?b.surface_material:"UNKNOWN"),source_track_ids:[a.id,b.id],evidence:{gap_pixels:Number(gap.toFixed(3)),overlap_pixels:Number(overlap(ba,bb).toFixed(3)),relative_speed_pixels_per_sample:Number(relativeSpeed.toFixed(3)),motion_change_score:Number(motionChange.toFixed(4)),track_quality:Number(quality.toFixed(4)),explicit_roi_roles:true,semantic_model_used:false}});}priorNear=touch;priorSpeed=relativeSpeed;}}return{contract:CONTRACT,events,event_count:events.length,track_count:rows.length,minimum_confidence:min_confidence,explicit_roi_roles_required:true,semantic_model_used:false,automatic_semantic_classification:false,human_review_required:true};}
export const CreativePictureContactEvidenceRuntime=Object.freeze({contract:CONTRACT,roles:ROLES,normalizeTrack:normalizePictureObjectTrack,derive:derivePictureContactEvidence});