import { spawn } from "node:child_process";
import { materializeMedia } from "@/lib/creative/media/runtime/CreativeMediaInspectionRuntime";

const CONTRACT = "AVANTIQO_MUSIC_MIX_EVIDENCE_V13";
const MAX_ANALYSIS_SECONDS = 600;
const ENVELOPE_RATE = 16000;
const ENVELOPE_WINDOW_SECONDS = 1.0;
const ENVELOPE_HOP_SECONDS = 0.5;
function text(v){return String(v??"").trim();}
function finite(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}
function namedStats(stderr,name){const s=String(stderr||"");const escaped=String(name).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const mean=s.match(new RegExp(`\\[volumedetect@${escaped}[^\\]]*\\] mean_volume:\\s*(-?[0-9.]+)\\s*dB`,"i"));const peak=s.match(new RegExp(`\\[volumedetect@${escaped}[^\\]]*\\] max_volume:\\s*(-?[0-9.]+)\\s*dB`,"i"));return {mean_db:finite(mean?.[1]),peak_dbfs:finite(peak?.[1])};}
async function measureTrackSignal(ffmpeg,file,analysisSeconds){
  const bands=[
    ["full",null],["sub","highpass=f=30,lowpass=f=120"],["lowmid","highpass=f=120,lowpass=f=500"],["warmth","highpass=f=140,lowpass=f=280"],
    ["boxiness","highpass=f=280,lowpass=f=550"],["presence","highpass=f=2200,lowpass=f=5200"],["air","highpass=f=7000,lowpass=f=14000"],["sibilance","highpass=f=5600,lowpass=f=9500"],
  ];
  const spectralLabels=bands.map(([name])=>`[${name}]`).join("");
  const graph=[
    `[0:a]asplit=${bands.length+1}${spectralLabels}[env]`,
    ...bands.map(([name,filter])=>`[${name}]${filter?`${filter},`:""}volumedetect@${name},anullsink`),
    '[env]asplit=3[efull][epresence][elow]',
    '[efull]anull[fullout]',
    '[epresence]highpass=f=2200,lowpass=f=5200[presenceout]',
    '[elow]highpass=f=30,lowpass=f=160[lowout]',
    '[fullout][presenceout][lowout]amerge=inputs=3[out]',
  ].join(';');
  const args=["-hide_banner","-nostats","-t",String(Math.max(1,Math.min(MAX_ANALYSIS_SECONDS,finite(analysisSeconds,MAX_ANALYSIS_SECONDS)))),"-i",file,"-vn","-filter_complex",graph,"-map","[out]","-ac","3","-ar",String(ENVELOPE_RATE),"-f","f32le","-acodec","pcm_f32le","-"];
  const {stdout,stderr}=await new Promise((resolve,reject)=>{const child=spawn(ffmpeg,args,{shell:false,stdio:["ignore","pipe","pipe"]});const stdout=[],stderr=[];const timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("CREATIVE_MUSIC_MIX_EVIDENCE_TIMEOUT"));},180000);child.stdout.on("data",c=>stdout.push(c));child.stderr.on("data",c=>stderr.push(c));child.on("error",e=>{clearTimeout(timer);reject(e);});child.on("close",code=>{clearTimeout(timer);const err=Buffer.concat(stderr).toString("utf8");if(code===0)resolve({stdout:Buffer.concat(stdout),stderr:err});else reject(new Error(err||`CREATIVE_MUSIC_MIX_EVIDENCE_EXIT_${code}`));});});
  const frames=Math.floor(stdout.length/(4*3)),channels=[new Float32Array(frames),new Float32Array(frames),new Float32Array(frames)];
  for(let i=0;i<frames;i++){const base=i*12;channels[0][i]=stdout.readFloatLE(base);channels[1][i]=stdout.readFloatLE(base+4);channels[2][i]=stdout.readFloatLE(base+8);}
  return {bands:Object.fromEntries(bands.map(([name])=>[name,namedStats(stderr,name)])),envelopes:{dynamics_envelope:envelopeRows(channels[0]),presence_envelope:envelopeRows(channels[1]),low_envelope:envelopeRows(channels[2])}};
}

function envelopeRows(samples){
  const win=Math.max(1,Math.round(ENVELOPE_RATE*ENVELOPE_WINDOW_SECONDS)),hop=Math.max(1,Math.round(ENVELOPE_RATE*ENVELOPE_HOP_SECONDS)),rows=[];
  for(let start=0;start+Math.round(ENVELOPE_RATE*.25)<=samples.length;start+=hop){const end=Math.min(samples.length,start+win);let sum=0;for(let i=start;i<end;i++)sum+=samples[i]*samples[i];const rms=Math.sqrt(sum/Math.max(1,end-start));const db=rms>1e-9?20*Math.log10(rms):-120;rows.push({time_seconds:Number(((start+(end-start)/2)/ENVELOPE_RATE).toFixed(3)),rms_dbfs:Number(db.toFixed(2))});}
  return rows;
}
function analysisSecondsFor(track={},basis="SOURCE_MEDIA"){const clips=(track.clips||[]).filter(c=>c?.muted!==true);const end=basis==="TRACK_RENDER"?Math.max(0,...clips.map(c=>finite(c.start_seconds,0)+finite(c.duration_seconds,0))):Math.max(0,...clips.map(c=>finite(c.source_offset_seconds,0)+finite(c.duration_seconds,0)));return Math.max(1,Math.min(MAX_ANALYSIS_SECONDS,end||MAX_ANALYSIS_SECONDS));}
function sourceMediaEvidenceExact(track={}){const clips=(track.clips||[]).filter(c=>c?.muted!==true&&c?.source_asset_id);if(clips.length!==1)return false;const clip=clips[0];return finite(clip.source_offset_seconds,0)===0&&finite(clip.gain_db,0)===0&&finite(clip.fade_in_seconds,0)===0&&finite(clip.fade_out_seconds,0)===0&&clip.loop_enabled!==true&&clip.reversed!==true&&text(clip.warp_mode||"off")==="off";}
async function trackEvidence({organization_id,track,source_url,ffmpeg,evidence_timeline_basis="SOURCE_MEDIA"}){const media=await materializeMedia({organization_id,source_url,source_file_name:`${track.id}.wav`,source_mime_type:"audio/wav"});try{const analysis_seconds=analysisSecondsFor(track,evidence_timeline_basis);const {bands,envelopes}=await measureTrackSignal(ffmpeg,media.file_path,analysis_seconds);const {full,sub,lowmid,warmth,boxiness,presence,air,sibilance}=bands;const {dynamics_envelope:envelope,presence_envelope:presenceEnvelope,low_envelope:lowEnvelope}=envelopes;const delta=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)?Number((a-b).toFixed(2)):null;return {track_id:track.id,measured:true,mean_db:full.mean_db,peak_dbfs:full.peak_dbfs,crest_proxy_db:Number.isFinite(full.mean_db)&&Number.isFinite(full.peak_dbfs)?Number((full.peak_dbfs-full.mean_db).toFixed(2)):null,sub_vs_lowmid_db:delta(sub.mean_db,lowmid.mean_db),presence_vs_lowmid_db:delta(presence.mean_db,lowmid.mean_db),warmth_vs_lowmid_db:delta(warmth.mean_db,lowmid.mean_db),boxiness_vs_warmth_db:delta(boxiness.mean_db,warmth.mean_db),boxiness_vs_presence_db:delta(boxiness.mean_db,presence.mean_db),air_vs_presence_db:delta(air.mean_db,presence.mean_db),sibilance_vs_presence_db:delta(sibilance.mean_db,presence.mean_db),dynamics_envelope:envelope,presence_envelope:presenceEnvelope,low_envelope:lowEnvelope,envelope_window_seconds:ENVELOPE_WINDOW_SECONDS,envelope_hop_seconds:ENVELOPE_HOP_SECONDS,analysis_seconds,analysis_capped:analysis_seconds>=MAX_ANALYSIS_SECONDS,analysis_process_count:1,spectral_process_count:1,envelope_process_count:1,shared_decode_process:true};}finally{await media.cleanup().catch(()=>{});}}

function clipAt(track,time){return (track?.clips||[]).find(c=>c?.muted!==true&&time>=finite(c.start_seconds,0)&&time<=finite(c.start_seconds,0)+finite(c.duration_seconds,0));}
function envelopeValueAt(track,row,key,time){const clip=clipAt(track,time),env=row?.[key];if(!clip||!Array.isArray(env)||!env.length)return null;const sourceTime=row?.evidence_timeline_basis==="TRACK_RENDER"?time:finite(clip.source_offset_seconds,0)+(time-finite(clip.start_seconds,0));let best=null,distance=Infinity;for(const point of env){const d=Math.abs(finite(point.time_seconds,-999)-sourceTime);if(d<distance){distance=d;best=point;}}return best&&distance<=.8?finite(best.rms_dbfs,null):null;}
function overlapRange(a,b){let best=null;for(const ca of a?.clips||[]){if(ca?.muted===true)continue;const as=finite(ca.start_seconds,0),ae=as+finite(ca.duration_seconds,0);for(const cb of b?.clips||[]){if(cb?.muted===true)continue;const bs=finite(cb.start_seconds,0),be=bs+finite(cb.duration_seconds,0),start=Math.max(as,bs),end=Math.min(ae,be);if(end-start>=.5&&(!best||end-start>best.end-best.start))best={start,end};}}return best;}
function temporalRelationship(trackA,rowA,trackB,rowB){const overlap=overlapRange(trackA,trackB);if(!overlap)return null;const windows=[];for(let t=overlap.start+.5;t<overlap.end;t+=.5){const ap=envelopeValueAt(trackA,rowA,"presence_envelope",t),bp=envelopeValueAt(trackB,rowB,"presence_envelope",t),al=envelopeValueAt(trackA,rowA,"low_envelope",t),bl=envelopeValueAt(trackB,rowB,"low_envelope",t),af=envelopeValueAt(trackA,rowA,"dynamics_envelope",t),bf=envelopeValueAt(trackB,rowB,"dynamics_envelope",t);if([ap,bp,al,bl,af,bf].every(Number.isFinite))windows.push({time_seconds:Number(t.toFixed(3)),presence_score:Math.max(0,1-Math.abs(ap-bp)/10),low_score:Math.max(0,1-Math.abs(al-bl)/10),level_score:Math.max(0,1-Math.abs(af-bf)/12)});}
  const active=windows.filter(w=>w.level_score>.05);if(active.length<3)return null;const avg=k=>Number((active.reduce((sum,w)=>sum+w[k],0)/active.length).toFixed(3));return {method:"TEMPORAL_SPECTRAL_COMPETITION",overlap_window_count:active.length,overlap_seconds:Number((active.length*.5).toFixed(2)),temporal_presence_competition_score:avg("presence_score"),temporal_low_competition_score:avg("low_score"),temporal_level_proximity_score:avg("level_score"),simultaneous_timeline_windows_measured:true,psychoacoustic_masking_measured:false};}

export async function analyzeMusicMixEvidence({organization_id,session,asset_urls={},track_render_urls={},media_tools={}}={}){if(!organization_id)throw new Error("CREATIVE_MUSIC_MIX_EVIDENCE_ORGANIZATION_REQUIRED");const ffmpeg=text(media_tools.ffmpeg||process.env.CREATIVE_FFMPEG_PATH)||"ffmpeg";const rows=[];for(const track of session?.tracks||[]){if(track.mute===true)continue;const sourceIds=[...new Set((track.clips||[]).filter(c=>c?.muted!==true&&c?.source_asset_id).map(c=>c.source_asset_id))];const trackRenderUrl=track_render_urls?.[track.id]||null;const exactSource=sourceIds.length===1&&sourceMediaEvidenceExact(track);const renderRequired=sourceIds.length>1||!exactSource;if(renderRequired&&!trackRenderUrl){rows.push({track_id:track.id,measured:false,reason:sourceIds.length>1?"MULTIPLE_SOURCE_ASSETS_REQUIRE_TRACK_RENDER":"EDITED_SOURCE_RANGE_REQUIRE_TRACK_RENDER",source_asset_count:sourceIds.length,timeline_evidence_safe:false});continue;}const sourceId=sourceIds[0]||null;const useTrackRender=renderRequired&&Boolean(trackRenderUrl);const sourceUrl=useTrackRender?trackRenderUrl:(sourceId?asset_urls[sourceId]:null);if(!sourceUrl){rows.push({track_id:track.id,measured:false,reason:"SOURCE_URL_UNAVAILABLE",source_asset_count:sourceIds.length,timeline_evidence_safe:false});continue;}try{const basis=useTrackRender?"TRACK_RENDER":"SOURCE_MEDIA";rows.push({...await trackEvidence({organization_id,track,source_url:sourceUrl,ffmpeg,evidence_timeline_basis:basis}),source_asset_count:sourceIds.length,timeline_evidence_safe:true,evidence_source:useTrackRender?"TRACK_STEM_RENDER":"SOURCE_ASSET",evidence_timeline_basis:basis});}catch(error){rows.push({track_id:track.id,measured:false,reason:text(error?.message||"ANALYSIS_FAILED"),source_asset_count:sourceIds.length,timeline_evidence_safe:false});}}
const measured=rows.filter(r=>r.measured);
const relationships=[];
const trackById=new Map((session?.tracks||[]).map(t=>[t.id,t]));
for(let i=0;i<measured.length;i+=1){for(let j=i+1;j<measured.length;j+=1){const a=measured[i],b=measured[j];const presenceOverlap=Math.abs((a.presence_vs_lowmid_db??0)-(b.presence_vs_lowmid_db??0));const lowOverlap=Math.abs((a.sub_vs_lowmid_db??0)-(b.sub_vs_lowmid_db??0));const meanDelta=Math.abs((a.mean_db??-120)-(b.mean_db??-120));const temporal=temporalRelationship(trackById.get(a.track_id),a,trackById.get(b.track_id),b);relationships.push({track_a_id:a.track_id,track_b_id:b.track_id,presence_overlap_score:Number(Math.max(0,1-presenceOverlap/8).toFixed(3)),low_overlap_score:Number(Math.max(0,1-lowOverlap/8).toFixed(3)),level_proximity_score:Number(Math.max(0,1-meanDelta/12).toFixed(3)),measured_from_independent_track_spectra:true,...(temporal||{}),simultaneous_masking_measured:false});}}
const ambiguousTracks=rows.filter(r=>["MULTIPLE_SOURCE_ASSETS_REQUIRE_TRACK_RENDER","EDITED_SOURCE_RANGE_REQUIRE_TRACK_RENDER"].includes(r.reason));
return {contract:CONTRACT,measured_track_count:measured.length,ambiguous_source_track_count:ambiguousTracks.length,all_timeline_evidence_safe:ambiguousTracks.length===0,analysis_processes_per_measured_track:1,spectral_processes_per_measured_track:1,envelope_processes_per_measured_track:1,shared_decode_process:true,tracks:rows,relationships,relationship_method:relationships.some(r=>r.simultaneous_timeline_windows_measured)?"TEMPORAL_SPECTRAL_COMPETITION_WITH_STATIC_FALLBACK":"INDEPENDENT_TRACK_SPECTRAL_OVERLAP_PROXY",simultaneous_timeline_windows_measured:relationships.some(r=>r.simultaneous_timeline_windows_measured),simultaneous_masking_measured:false,artistic_intent_inferred:false,mutation_authorized:false};}
export const CreativeMusicMixEvidenceRuntime=Object.freeze({contract:CONTRACT,analyze:analyzeMusicMixEvidence});
