import crypto from "node:crypto";
const CONTRACT="AVANTIQO_AUDIO_POST_DIALOGUE_LISTENING_REVIEW_V1";
function text(v){return String(v??"").trim();}
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(!value||typeof value!=="object")return value;return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])]));}
function digest(value){return crypto.createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex");}
export function audioPostListeningBinding(packageState={}){return{project_revision:packageState.project_revision,picture_lock_digest:packageState.picture_lock_digest,language:packageState.language,full_mix_asset_id:packageState.full_mix?.asset_id||null,stem_assets:(packageState.stems||[]).map(row=>({delivery_code:row.delivery_code,asset_id:row.asset_id||null})).sort((a,b)=>String(a.delivery_code).localeCompare(String(b.delivery_code))),channel_layout:packageState.channel_layout,channels:packageState.channels};}
export function createAudioPostListeningReview(packageState={},input={}){const status=text(input.status).toUpperCase();if(!["APPROVED","REJECTED"].includes(status))throw new Error("CREATIVE_AUDIO_POST_LISTENING_STATUS_INVALID");const reviewer=text(input.reviewer_user_id);if(!reviewer)throw new Error("CREATIVE_AUDIO_POST_LISTENING_REVIEWER_REQUIRED");const note=text(input.note);if(status==="REJECTED"&&!note)throw new Error("CREATIVE_AUDIO_POST_LISTENING_REJECTION_NOTE_REQUIRED");const binding=audioPostListeningBinding(packageState);if(!binding.full_mix_asset_id)throw new Error("CREATIVE_AUDIO_POST_LISTENING_FULL_MIX_REQUIRED");return{contract:CONTRACT,status,reviewer_user_id:reviewer,note:note||null,reviewed_at:text(input.reviewed_at)||new Date().toISOString(),binding,binding_hash:digest(binding),dialogue_intelligibility_listened:true,semantic_intelligibility_human_judgment:true,automatic_acceptance:false,audio_mutation_performed:false};}
export function evaluateAudioPostListeningReview(packageState={},review=null){const binding=audioPostListeningBinding(packageState),bindingHash=digest(binding);if(!review)return{contract:"AVANTIQO_AUDIO_POST_DIALOGUE_LISTENING_STATUS_V1",required:true,current:false,approved:false,status:"MISSING",binding_hash:bindingHash};const current=review.contract===CONTRACT&&review.binding_hash===bindingHash;return{contract:"AVANTIQO_AUDIO_POST_DIALOGUE_LISTENING_STATUS_V1",required:true,current,approved:current&&review.status==="APPROVED",status:current?review.status:"STALE",binding_hash:bindingHash,reviewed_at:review.reviewed_at||null,reviewer_user_id:review.reviewer_user_id||null,note:review.note||null};}
export const CreativeAudioPostListeningReviewRuntime=Object.freeze({contract:CONTRACT,binding:audioPostListeningBinding,create:createAudioPostListeningReview,evaluate:evaluateAudioPostListeningReview});
