const CONTRACT="AVANTIQO_AUDIO_POST_LANGUAGE_VERSION_V1";
const LANGUAGE_STEMS=new Set(["DIALOGUE","VOICEOVER","ADR"]);
function text(v){return String(v??"").trim();}
export function normalizeAudioPostLanguage(value){const language=text(value).toLowerCase();if(!language||language==="und")throw new Error("CREATIVE_AUDIO_POST_LANGUAGE_REQUIRED");if(!/^[a-z]{2,3}(?:-[a-z0-9]{2,8})*$/.test(language))throw new Error(`CREATIVE_AUDIO_POST_LANGUAGE_INVALID:${language}`);return language;}
export function isLanguageScopedPostStem(stemId){return LANGUAGE_STEMS.has(text(stemId).toUpperCase());}
export function filterTrackForAudioPostLanguage(track={},language){if(!LANGUAGE_STEMS.has(text(track.audio_role).toUpperCase()))return structuredClone(track);const lang=normalizeAudioPostLanguage(language),next=structuredClone(track);next.clips=(next.clips||[]).filter(clip=>text(clip.audio_post?.language).toLowerCase()===lang);next.takes=(next.takes||[]).filter(take=>!take.audio_post?.language||text(take.audio_post.language).toLowerCase()===lang);return next;}

export function audioPostSessionHasLanguageRoles(session={}){return (session.tracks||[]).some(track=>LANGUAGE_STEMS.has(text(track.audio_role).toUpperCase()));}
export function buildAudioPostLanguageSession(sessionInput={},language){if(!audioPostSessionHasLanguageRoles(sessionInput))return structuredClone(sessionInput);const lang=normalizeAudioPostLanguage(language),session=structuredClone(sessionInput);session.tracks=(session.tracks||[]).map(track=>filterTrackForAudioPostLanguage(track,lang)).filter(track=>!LANGUAGE_STEMS.has(text(track.audio_role).toUpperCase())||(track.clips||[]).length>0||(track.takes||[]).length>0);session.delivery_language=lang;session.language_version_contract=CONTRACT;return session;}

export function languageVersionAssetMetadata(stemId,language){const scoped=isLanguageScopedPostStem(stemId);return{contract:CONTRACT,delivery_language:scoped?normalizeAudioPostLanguage(language):null,language_scoped:scoped,shared_across_language_versions:!scoped};}
export function buildAudioPostLanguageVersionManifest({language,picture_lock_digest,project_revision,full_mix_asset_id=null,stems=[]}={}){const lang=normalizeAudioPostLanguage(language),languageStems=(stems||[]).filter(row=>isLanguageScopedPostStem(row.stem_id||row.id)),sharedStems=(stems||[]).filter(row=>!isLanguageScopedPostStem(row.stem_id||row.id));return{contract:"AVANTIQO_AUDIO_POST_LANGUAGE_VERSION_MANIFEST_V1",language:lang,picture_lock_digest:picture_lock_digest||null,project_revision:Number(project_revision)||0,full_mix_asset_id:full_mix_asset_id||null,language_stems:languageStems.map(row=>({delivery_code:row.delivery_code,asset_id:row.asset_id||null})),shared_stems:sharedStems.map(row=>({delivery_code:row.delivery_code,asset_id:row.asset_id||null})),shared_me_asset_id:sharedStems.find(row=>row.delivery_code==="ME")?.asset_id||null,common_assets_reused:true,dialogue_assets_language_scoped:true};}
export const CreativeAudioPostVersionRuntime=Object.freeze({contract:CONTRACT,normalizeLanguage:normalizeAudioPostLanguage,isLanguageScopedStem:isLanguageScopedPostStem,filterTrack:filterTrackForAudioPostLanguage,assetMetadata:languageVersionAssetMetadata,manifest:buildAudioPostLanguageVersionManifest,sessionHasLanguageRoles:audioPostSessionHasLanguageRoles,buildLanguageSession:buildAudioPostLanguageSession});
