import {spawn} from "node:child_process";
import {createHash} from "node:crypto";
import {materializeMedia} from "../../media/runtime/CreativeMediaInspectionRuntime.js";
import {renderCinematicSoundSynthesisPreview} from "../client/MusicCinematicSoundSynthesisRenderRuntime.js";
function text(v){return String(v??"").trim();}
function run(command,args,input=null,timeout=300000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{stdio:["pipe","pipe","pipe"]}),out=[],err=[];const timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("CINEMATIC_SOUND_SYNTH_EXECUTION_TIMEOUT"));},timeout);child.stdout.on("data",c=>out.push(c));child.stderr.on("data",c=>err.push(c));child.on("error",reject);child.on("close",code=>{clearTimeout(timer);code===0?resolve(Buffer.concat(out)):reject(new Error(Buffer.concat(err).toString()||"CINEMATIC_SOUND_SYNTH_EXECUTION_FAILED"));});if(input)child.stdin.end(input);else child.stdin.end();});}
function floats(bytes){return new Float32Array(bytes.buffer,bytes.byteOffset,Math.floor(bytes.byteLength/4));}
async function decode(ffmpeg,media,rate){const bytes=await run(ffmpeg,["-hide_banner","-loglevel","error","-i",media.file_path,"-vn","-ac","1","-ar",String(rate),"-f","f32le","-acodec","pcm_f32le","-"]);return new Float32Array(floats(bytes));}
export async function executeCinematicSoundSynthesis({organization_id,plan,primary_asset,secondary_asset=null,sample_rate=48000,media_tools={}}={}){if(!organization_id)throw new Error("CINEMATIC_SOUND_SYNTH_EXEC_ORGANIZATION_REQUIRED");if(plan?.contract!=="AVANTIQO_CINEMATIC_SOUND_SYNTHESIS_V1"||plan.ready_for_preview!==true)throw new Error("CINEMATIC_SOUND_SYNTH_EXEC_READY_PLAN_REQUIRED");if(!primary_asset?.file_url)throw new Error("CINEMATIC_SOUND_SYNTH_EXEC_PRIMARY_ASSET_REQUIRED");const ffmpeg=text(media_tools.ffmpeg||process.env.CREATIVE_FFMPEG_PATH)||"ffmpeg",primary=await materializeMedia({organization_id,url:primary_asset.file_url,file_name:primary_asset.file_name||"source.wav",mime_type:primary_asset.metadata?.mime_type||"audio/wav",policy:{max_bytes:2_147_483_648,timeout_ms:300000,max_redirects:0}}),secondary=secondary_asset?.file_url?await materializeMedia({organization_id,url:secondary_asset.file_url,file_name:secondary_asset.file_name||"secondary.wav",mime_type:secondary_asset.metadata?.mime_type||"audio/wav",policy:{max_bytes:2_147_483_648,timeout_ms:300000,max_redirects:0}}):null;try{const a=await decode(ffmpeg,primary,sample_rate),b=secondary?await decode(ffmpeg,secondary,sample_rate):null,rendered=renderCinematicSoundSynthesisPreview({plan,primary_source:a,secondary_source:b,sample_rate}),pcm=Buffer.from(rendered.mono.buffer,rendered.mono.byteOffset,rendered.mono.byteLength),wav=await run(ffmpeg,["-hide_banner","-loglevel","error","-f","f32le","-ar",String(sample_rate),"-ac","1","-i","pipe:0","-c:a","pcm_s24le","-ar",String(sample_rate),"-rf64","auto","-f","wav","pipe:1"],pcm);return{contract:"AVANTIQO_CINEMATIC_SOUND_SYNTH_EXECUTION_V1",buffer:wav,checksum_sha256:createHash("sha256").update(wav).digest("hex"),file_name:"cinematic-synthesis-24bit.wav",mime_type:"audio/wav",sample_rate,channels:1,bit_depth:24,frames:rendered.frames,layer_renders:rendered.layer_renders,source_asset_id:primary_asset.id,secondary_asset_id:secondary_asset?.id||null,source_assets_preserved:true,render_to_new_asset_only:true,provider_job_submitted:false,release_master:false};}finally{await primary.cleanup().catch(()=>{});if(secondary)await secondary.cleanup().catch(()=>{});}}
export const CreativeCinematicSoundSynthesisExecutionRuntime=Object.freeze({contract:"AVANTIQO_CINEMATIC_SOUND_SYNTH_EXECUTION_V1",execute:executeCinematicSoundSynthesis});