import { normalizeMusicSpatialTrack } from "./CreativeMusicSpatialAudioRuntime.js";
import { soundObjectSpatialAutomationLanes } from "./CreativeMusicCinematicSoundObjectRuntime.js";
import { deriveMusicAcousticWorldAutomation } from "./CreativeMusicAcousticWorldGeometryRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_SOUND_OBJECT_RENDER_BINDING_V1";
function text(v){return String(v??"").trim();}
const GENERATED_PARAMETERS=new Set(["spatial:azimuth_degrees","spatial:elevation_degrees","spatial:distance_meters","spatial:width_percent","spatial:occlusion_percent","spatial:reflection_amount_percent"]);
function geometryLaneIds(object){return new Set(["azimuth_degrees","elevation_degrees","distance_meters","occlusion_percent","reflection_amount_percent"].map(kind=>`geometry-${object.id}-${kind}`));}
function generatedLaneIds(object){return new Set(["azimuth","elevation","distance","width","occlusion","reflections"].map(kind=>`spatial-${object.id}-${kind}`));}
export function bindMusicSoundObjectsToSession(sessionInput={}){
  const session=structuredClone(sessionInput),tracks=new Map((session.tracks||[]).map(track=>[track.id,track])),bindings=[],failures=[],usedTracks=new Map(),generatedIds=new Set();
  for(const object of session.sound_objects||[]){for(const id of generatedLaneIds(object))generatedIds.add(id);for(const id of geometryLaneIds(object))generatedIds.add(id);}
  session.automation_lanes=(session.automation_lanes||[]).filter(lane=>!generatedIds.has(text(lane.id)));
  for(const object of session.sound_objects||[]){const trackId=text(object.assigned_track_id);if(!trackId)continue;const track=tracks.get(trackId);if(!track){failures.push(`SOUND_OBJECT_ASSIGNED_TRACK_NOT_FOUND:${object.id}:${trackId}`);continue;}if(usedTracks.has(trackId)){failures.push(`SOUND_OBJECT_TRACK_ALREADY_BOUND:${trackId}:${usedTracks.get(trackId)}:${object.id}`);continue;}usedTracks.set(trackId,object.id);const path=object.spatial_path||{},mode=Number(path.width_percent)>0?"WIDE":"POINT",baseline=normalizeMusicSpatialTrack({...track.spatial,mode,azimuth_degrees:path.start_azimuth_degrees,elevation_degrees:path.start_elevation_degrees,distance_meters:path.start_distance_meters,width_percent:path.width_percent,divergence_percent:path.divergence_percent,obstruction_material:path.obstruction_material,follows_picture_object:object.id,immersive:{...(path.immersive||{}),occlusion_percent:path.start_occlusion_percent,obstruction_material:path.obstruction_material,reflection_amount_percent:path.start_reflection_amount_percent}});track.spatial=baseline;let geometry=null;try{if(session.acoustic_world&&object.picture_object_id&&path.mode==="FOLLOW_PICTURE_OBJECT")geometry=deriveMusicAcousticWorldAutomation({world:session.acoustic_world,sound_object:object,track_id:trackId});}catch(error){failures.push(String(error?.message||error));continue;}if(geometry){const first=geometry.rows[0]||{};track.spatial=normalizeMusicSpatialTrack({...track.spatial,azimuth_degrees:first.azimuth_degrees,elevation_degrees:first.elevation_degrees,distance_meters:first.distance_meters,immersive:{...(track.spatial.immersive||{}),occlusion_percent:first.occlusion_percent,obstruction_material:geometry.obstruction_material,reflection_amount_percent:first.reflection_amount_percent}});}track.sound_object_binding={contract:CONTRACT,sound_object_id:object.id,picture_lock_digest:object.picture_lock_digest||null,mode,source_of_truth:geometry?"ACOUSTIC_WORLD_GEOMETRY":"CINEMATIC_SOUND_OBJECT",acoustic_world_id:geometry?.world_id||null,manual_spatial_override_allowed:false};const lanes=geometry?.lanes||soundObjectSpatialAutomationLanes(object,trackId);for(const lane of lanes){const conflict=(session.automation_lanes||[]).find(existing=>existing.enabled!==false&&existing.target_type==="track"&&existing.target_id===trackId&&existing.parameter===lane.parameter&&!generatedIds.has(text(existing.id)));if(conflict){failures.push(`SOUND_OBJECT_AUTOMATION_CONFLICT:${object.id}:${trackId}:${lane.parameter}:${conflict.id||"manual"}`);continue;}session.automation_lanes.push(lane);}bindings.push({sound_object_id:object.id,track_id:trackId,mode,automation_lane_ids:lanes.map(lane=>lane.id),immersive:path.immersive||null});}
  if(failures.length)return{contract:CONTRACT,success:false,session,bindings,failures};
  return{contract:CONTRACT,success:true,session,bindings,failures:[],binding_count:bindings.length,final_render_bound:true,manual_reentry_required:false};
}
export const CreativeMusicSoundObjectRenderBindingRuntime=Object.freeze({contract:CONTRACT,bind:bindMusicSoundObjectsToSession});
