import { buildMusicFoleyPlan } from "./CreativeMusicFoleyPlanRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_PICTURE_FOLEY_CUE_PROPOSAL_V1";
const EVENT_MAP=Object.freeze({
  FOOT_CONTACT:{category:"FOOTSTEP",label:"footstep"},
  CLOTH_MOVEMENT:{category:"CLOTH",label:"cloth movement"},
  PROP_CONTACT:{category:"PROP",label:"prop handling"},
  DOOR_MOVEMENT:{category:"PROP",label:"door movement"},
  BODY_CONTACT:{category:"BODY",label:"body movement/contact"},
  VEHICLE_INTERACTION:{category:"VEHICLE",label:"vehicle interaction"},
  IMPACT:{category:"IMPACT",label:"impact"},
  MACHINERY_MOVEMENT:{category:"MACHINERY",label:"machinery movement"},
});
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,a,b,f=0){return Math.max(a,Math.min(b,finite(v,f)));}
function surface(v){const s=text(v).toUpperCase();return ["WOOD","TILE","CONCRETE","GRAVEL","GRASS","METAL","WATER","CARPET","DIRT","UNKNOWN"].includes(s)?s:"UNKNOWN";}
export function proposeMusicPictureFoleyCues({picture_lock,tracked_events=[]}={}){if(!text(picture_lock?.picture_lock_digest))throw new Error("CREATIVE_MUSIC_PICTURE_FOLEY_PICTURE_LOCK_REQUIRED");const duration=finite(picture_lock?.duration_seconds,null),fps=finite(picture_lock?.frame_rate,null);if(!(duration>0))throw new Error("CREATIVE_MUSIC_PICTURE_FOLEY_DURATION_REQUIRED");const evidence=[],cues=[];for(const row of tracked_events||[]){const type=text(row.event_type).toUpperCase(),mapped=EVENT_MAP[type];if(!mapped)continue;const confidence=clamp(row.confidence,0,1,0);if(confidence<.75)continue;const start=Math.max(0,finite(row.time_seconds,0));if(start>duration)continue;const material=surface(row.surface_material),actor=text(row.subject_id)||null,objectId=text(row.object_id)||null,detail=[mapped.label,material!=="UNKNOWN"?"on "+material.toLowerCase():"",text(row.description)].filter(Boolean).join(" · ");const cue={id:text(row.id)||"picture-foley-"+(cues.length+1),category:mapped.category,start_seconds:start,duration_seconds:Math.max(.01,finite(row.duration_seconds,type==="FOOT_CONTACT"?.12:.25)),description:detail,perspective:text(row.perspective||"ON_SCREEN").toUpperCase(),intensity:clamp(row.intensity,0,1,.5),sync_tolerance_ms:type==="IMPACT"||type==="FOOT_CONTACT"?16:40,picture_event_id:text(row.id)||null,subject_id:actor,object_id:objectId,surface_material:material,evidence_confidence:confidence,proposal_only:true,human_approval_required:true};cues.push(cue);evidence.push({picture_event_id:cue.picture_event_id,event_type:type,confidence,subject_id:actor,object_id:objectId,surface_material:material,time_seconds:start});}const plan=buildMusicFoleyPlan({cues,picture_duration_seconds:duration,frame_rate:fps});plan.events=plan.events.map((event,index)=>({...event,picture_event_id:cues[index]?.picture_event_id||null,subject_id:cues[index]?.subject_id||null,object_id:cues[index]?.object_id||null,surface_material:cues[index]?.surface_material||"UNKNOWN",evidence_confidence:cues[index]?.evidence_confidence||0,proposal_only:true,human_approval_required:true}));return{contract:CONTRACT,picture_lock_digest:text(picture_lock.picture_lock_digest),tracked_event_count:(tracked_events||[]).length,accepted_evidence_count:evidence.length,rejected_low_confidence_count:(tracked_events||[]).filter(x=>EVENT_MAP[text(x.event_type).toUpperCase()]&&clamp(x.confidence,0,1,0)<.75).length,evidence,foley_plan:plan,automatic_picture_inference_performed:false,automatic_sound_selection:false,automatic_generation:false,human_cue_approval_required:true};}
export const CreativeMusicPictureFoleyCueRuntime=Object.freeze({contract:CONTRACT,propose:proposeMusicPictureFoleyCues,eventTypes:Object.keys(EVENT_MAP)});
