import { createMusicAutomationLane } from "./CreativeMusicAutomationRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_ACOUSTIC_WORLD_GEOMETRY_V1";
const MATERIAL_OCCLUSION=Object.freeze({AIR:0,CURTAIN:24,GLASS:36,WOOD:52,VEHICLE_BODY:68,BRICK:82,CONCRETE:92,METAL:96});
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,a,b,f=0){return Math.max(a,Math.min(b,finite(v,f)));}
function vec(v={}){return{x:finite(v.x),y:finite(v.y),z:finite(v.z)};}function lerp(a,b,t){return a+(b-a)*t;}
function sample(keys=[],time,fallback={}){const rows=(keys||[]).map(k=>({time_seconds:Math.max(0,finite(k.time_seconds)),...vec(k)})).sort((a,b)=>a.time_seconds-b.time_seconds);if(!rows.length)return vec(fallback);if(time<=rows[0].time_seconds)return vec(rows[0]);if(time>=rows.at(-1).time_seconds)return vec(rows.at(-1));const hi=rows.findIndex(k=>k.time_seconds>=time),a=rows[hi-1],b=rows[hi],t=(time-a.time_seconds)/Math.max(1e-9,b.time_seconds-a.time_seconds);return{x:lerp(a.x,b.x,t),y:lerp(a.y,b.y,t),z:lerp(a.z,b.z,t)};}
function segmentAabb(a,b,box){const min=vec(box?.min),max=vec(box?.max);let t0=0,t1=1;for(const axis of ["x","y","z"]){const d=b[axis]-a[axis];if(Math.abs(d)<1e-9){if(a[axis]<min[axis]||a[axis]>max[axis])return false;continue;}let u0=(min[axis]-a[axis])/d,u1=(max[axis]-a[axis])/d;if(u0>u1)[u0,u1]=[u1,u0];t0=Math.max(t0,u0);t1=Math.min(t1,u1);if(t0>t1)return false;}return true;}
function angles(source,listener){const x=source.x-listener.x,y=source.y-listener.y,z=source.z-listener.z,d=Math.max(.1,Math.hypot(x,y,z));return{distance_meters:d,azimuth_degrees:Math.atan2(x,-z)*180/Math.PI,elevation_degrees:Math.asin(clamp(y/d,-1,1))*180/Math.PI};}
function portalOpen(world,obstacle,time){const ids=Array.isArray(obstacle.portal_ids)?obstacle.portal_ids:[];if(!ids.length)return 0;return Math.max(...ids.map(id=>{const p=(world.portals||[]).find(row=>text(row.id)===text(id));if(!p)return 0;const keys=p.open_percent_keyframes||[];if(!keys.length)return clamp(p.open_percent,0,100,0);const rows=keys.map(k=>({time_seconds:finite(k.time_seconds),x:finite(k.open_percent)}));return clamp(sample(rows,time,{x:p.open_percent}).x,0,100,0);}),0);}
function obstruction(world,a,b,time){let strongest={percent:0,material:"AIR",obstacle_id:null};for(const obstacle of world.obstacles||[]){if(obstacle.enabled===false||!segmentAabb(a,b,obstacle.bounds))continue;const material=text(obstacle.material||"CONCRETE").toUpperCase(),base=MATERIAL_OCCLUSION[material]??MATERIAL_OCCLUSION.CONCRETE,percent=base*(1-portalOpen(world,obstacle,time)/100);if(percent>strongest.percent)strongest={percent,material:material in MATERIAL_OCCLUSION?material:"CONCRETE",obstacle_id:text(obstacle.id)||null};}return strongest;}
export function normalizeMusicAcousticWorld(input={}){return{contract:CONTRACT,id:text(input.id)||"acoustic-world",coordinate_system:"RIGHT_HANDED_Y_UP_METERS",listener:{picture_object_id:text(input.listener?.picture_object_id)||"camera",keyframes:input.listener?.keyframes||[]},sources:(input.sources||[]).map(s=>({picture_object_id:text(s.picture_object_id),keyframes:s.keyframes||[]})).filter(s=>s.picture_object_id),obstacles:(input.obstacles||[]).map(o=>({...o,id:text(o.id),material:text(o.material||"CONCRETE").toUpperCase(),bounds:{min:vec(o.bounds?.min),max:vec(o.bounds?.max)}})),portals:input.portals||[],reflection_amount_percent:clamp(input.reflection_amount_percent,0,100,25),geometry_authoritative:true,manual_occlusion_override_allowed:false};}
export function deriveMusicAcousticWorldAutomation({world:worldInput,sound_object,track_id}={}){const world=normalizeMusicAcousticWorld(worldInput),pictureId=text(sound_object?.picture_object_id),source=world.sources.find(s=>s.picture_object_id===pictureId);if(!source)throw new Error(`CREATIVE_MUSIC_ACOUSTIC_WORLD_SOURCE_NOT_FOUND:${pictureId||"missing"}`);const start=Math.max(0,finite(sound_object?.start_seconds)),end=Math.max(start+.001,finite(sound_object?.end_seconds,start+.001)),times=[start,end,...source.keyframes.map(k=>finite(k.time_seconds)),...world.listener.keyframes.map(k=>finite(k.time_seconds))].filter(t=>t>=start&&t<=end).sort((a,b)=>a-b).filter((t,i,a)=>i===0||Math.abs(t-a[i-1])>1e-6);const rows=times.map(time=>{const s=sample(source.keyframes,time),l=sample(world.listener.keyframes,time),a=angles(s,l),o=obstruction(world,l,s,time);return{time_seconds:time,...a,occlusion_percent:o.percent,obstruction_material:o.material,obstacle_id:o.obstacle_id,reflection_amount_percent:world.reflection_amount_percent};});const mk=(parameter,key)=>createMusicAutomationLane({id:`geometry-${sound_object.id}-${key}`,target_type:"track",target_id:track_id,parameter,interpolation:"linear",points:rows.map(r=>({time_seconds:r.time_seconds,value:r[key]}))});return{contract:"AVANTIQO_MUSIC_ACOUSTIC_WORLD_AUTOMATION_V1",world_id:world.id,sound_object_id:sound_object.id,track_id,source_picture_object_id:pictureId,geometry_authoritative:true,rows,obstruction_material:rows.reduce((a,r)=>r.occlusion_percent>(a?.occlusion_percent??-1)?r:a,null)?.obstruction_material||"AIR",lanes:[mk("spatial:azimuth_degrees","azimuth_degrees"),mk("spatial:elevation_degrees","elevation_degrees"),mk("spatial:distance_meters","distance_meters"),mk("spatial:occlusion_percent","occlusion_percent"),mk("spatial:reflection_amount_percent","reflection_amount_percent")]};}
export const CreativeMusicAcousticWorldGeometryRuntime=Object.freeze({contract:CONTRACT,normalize:normalizeMusicAcousticWorld,deriveAutomation:deriveMusicAcousticWorldAutomation});
