import { createMusicGroupBus } from "./CreativeMusicMixerRoutingRuntime.js";
import { normalizeMusicGroupProcessing } from "./CreativeMusicBusProcessingRuntime.js";

const CONTRACT="AVANTIQO_AUDIO_POST_RERECORDING_MIX_V1";
const BUS_DEFS=Object.freeze([
 {id:"bus-post-dx",role:"DIALOGUE",label:"DX",priority:100,duck_target:false},
 {id:"bus-post-vo",role:"VOICEOVER",label:"VO",priority:95,duck_target:false},
 {id:"bus-post-adr",role:"ADR",label:"ADR",priority:95,duck_target:false},
 {id:"bus-post-mx",role:"MUSIC",label:"MX",priority:60,duck_target:true},
 {id:"bus-post-fx",role:"EFFECTS",label:"FX",priority:55,duck_target:true},
 {id:"bus-post-fol",role:"FOLEY",label:"Foley",priority:58,duck_target:true},
 {id:"bus-post-amb",role:"AMBIENCE",label:"Ambience",priority:45,duck_target:true},
]);
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,min,max,f=0){return Math.max(min,Math.min(max,finite(v,f)));}
export function normalizeAudioPostMixPolicy(input={}){const duck=input.dialogue_ducking||{};return{contract:CONTRACT,dialogue_priority:input.dialogue_priority!==false,dialogue_key_roles:["DIALOGUE","VOICEOVER","ADR"],duck_target_roles:["MUSIC","EFFECTS","FOLEY","AMBIENCE"],dialogue_ducking:{enabled:duck.enabled!==false,threshold_dbfs:clamp(duck.threshold_dbfs,-60,0,-30),ratio:clamp(duck.ratio,1,20,3),attack_ms:clamp(duck.attack_ms,.5,500,12),release_ms:clamp(duck.release_ms,10,5000,220),knee_db:clamp(duck.knee_db,0,24,6),max_reduction_db:clamp(duck.max_reduction_db,0,18,6)},center_dialogue_preferred:input.center_dialogue_preferred!==false,dialogue_lfe_forbidden:true,automatic_mix_acceptance:false,independent_listening_review_required:true};}
export function ensureAudioPostMixBuses(sessionInput={}){const session=structuredClone(sessionInput);session.buses=Array.isArray(session.buses)?session.buses:[];for(const def of BUS_DEFS){let bus=session.buses.find(item=>item.id===def.id);if(!bus){bus=createMusicGroupBus({id:def.id,name:`Post ${def.label}`,output_bus_id:"bus-master",gain_db:0,pan:0});bus.processing=normalizeMusicGroupProcessing({});session.buses.push(bus);}bus.audio_post={contract:"AVANTIQO_AUDIO_POST_BUS_V1",role:def.role,label:def.label,priority:def.priority,dialogue_duck_target:def.duck_target};bus.destructive_processing_allowed=false;}for(const track of session.tracks||[]){const def=BUS_DEFS.find(item=>item.role===text(track.audio_role).toUpperCase());if(def)track.output_bus_id=def.id;if(["DIALOGUE","VOICEOVER","ADR"].includes(text(track.audio_role).toUpperCase())&&session.spatial_audio?.surround_enabled===true){track.spatial={...(track.spatial||{}),mode:"BED",center_send_db:0,lfe_send_db:-120,surround_send_db:-120};}}session.audio_post_mix=normalizeAudioPostMixPolicy(session.audio_post_mix||{});return session;}
export function validateAudioPostMix(session={}){const failures=[];const policy=normalizeAudioPostMixPolicy(session.audio_post_mix||{}),byId=new Map((session.buses||[]).map(bus=>[bus.id,bus]));let languageTracks=0;for(const def of BUS_DEFS){const relevant=(session.tracks||[]).filter(track=>text(track.audio_role).toUpperCase()===def.role);if(relevant.length&&!byId.has(def.id))failures.push(`AUDIO_POST_BUS_MISSING:${def.label}`);if(["DIALOGUE","VOICEOVER","ADR"].includes(def.role))languageTracks+=relevant.length;for(const track of relevant){if(track.output_bus_id!==def.id)failures.push(`AUDIO_POST_TRACK_ROUTE_INVALID:${track.id}:${def.label}`);if(policy.center_dialogue_preferred&&["DIALOGUE","VOICEOVER","ADR"].includes(def.role)&&session.spatial_audio?.surround_enabled===true){if(String(track.spatial?.mode||"BED").toUpperCase()==="BED"&&finite(track.spatial?.center_send_db,-120)<-12)failures.push(`AUDIO_POST_DIALOGUE_CENTER_SEND_LOW:${track.id}`);if(finite(track.spatial?.lfe_send_db,-120)>-100)failures.push(`AUDIO_POST_DIALOGUE_LFE_FORBIDDEN:${track.id}`);}}}
 if(languageTracks&&policy.dialogue_priority&&policy.dialogue_ducking.enabled!==true)failures.push("AUDIO_POST_DIALOGUE_DUCKING_REQUIRED");return{success:failures.length===0,contract:"AVANTIQO_AUDIO_POST_RERECORDING_MIX_VALIDATION_V1",failures,language_track_count:languageTracks,dialogue_priority:policy.dialogue_priority,dialogue_ducking:policy.dialogue_ducking,surround_layout:session.spatial_audio?.layout_id||"stereo",post_bus_count:BUS_DEFS.filter(def=>(session.tracks||[]).some(track=>text(track.audio_role).toUpperCase()===def.role)).length,re_recording_mix_ready:failures.length===0,independent_listening_review_required:true};}
export function audioPostMixBusDefinitions(){return BUS_DEFS.map(item=>({...item}));}
export const CreativeAudioPostMixRuntime=Object.freeze({contract:CONTRACT,normalize:normalizeAudioPostMixPolicy,ensure:ensureAudioPostMixBuses,validate:validateAudioPostMix,buses:audioPostMixBusDefinitions});
