import { bindMusicSessionToPicture, createMusicPictureLock, musicFramesToSeconds, musicSecondsToFrames } from "./CreativeMusicPictureLockRuntime.js";

const CONTRACT="AVANTIQO_AUDIO_POST_RECONFORM_V1";
function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function text(v){return String(v??"").trim();}
function normalizeMapEntry(input,index){const oldStart=Math.max(0,Math.round(finite(input.old_start_frame,0))),oldEnd=Math.max(oldStart,Math.round(finite(input.old_end_frame,oldStart))),newStart=Math.max(0,Math.round(finite(input.new_start_frame,oldStart)));return{id:text(input.id)||`segment-${index+1}`,old_start_frame:oldStart,old_end_frame:oldEnd,new_start_frame:newStart,frame_delta:newStart-oldStart};}
export function normalizeAudioPostConformMap(entries=[]){const map=(Array.isArray(entries)?entries:[]).map(normalizeMapEntry).sort((a,b)=>a.old_start_frame-b.old_start_frame);for(let i=1;i<map.length;i++){if(map[i].old_start_frame<=map[i-1].old_end_frame)throw new Error("CREATIVE_AUDIO_POST_CONFORM_MAP_OVERLAP");}return map;}
export function mapAudioPostFrame(frame,mapEntries=[]){const f=Math.max(0,Math.round(finite(frame,0))),map=(mapEntries||[]).map((item,index)=>Number.isFinite(Number(item?.frame_delta))?item:normalizeMapEntry(item,index)),entry=map.find(item=>f>=item.old_start_frame&&f<=item.old_end_frame);return entry?f+entry.frame_delta:f;}
function mapSeconds(seconds,oldFps,newFps,map){const oldFrame=musicSecondsToFrames(seconds,oldFps),newFrame=mapAudioPostFrame(oldFrame,map);return musicFramesToSeconds(newFrame,newFps);}
export function reconformAudioPostSession(sessionInput={},nextPictureInput={},conformMapInput=[]){
  const original=structuredClone(sessionInput),oldPicture=original.picture_lock;if(!oldPicture?.picture_lock_digest)throw new Error("CREATIVE_AUDIO_POST_RECONFORM_CURRENT_PICTURE_REQUIRED");const nextPicture=createMusicPictureLock(nextPictureInput),map=normalizeAudioPostConformMap(conformMapInput);if(!map.length)throw new Error("CREATIVE_AUDIO_POST_RECONFORM_MAP_REQUIRED");const oldFps=finite(oldPicture.frame_rate,24),newFps=finite(nextPicture.frame_rate,oldFps);let movedClips=0,movedAutomationPoints=0,editorialApprovalsInvalidated=0;
  const next=structuredClone(original);
  for(const track of next.tracks||[]){for(const clip of track.clips||[]){const before=finite(clip.start_seconds,0),after=mapSeconds(before,oldFps,newFps,map);if(Math.abs(after-before)>.000001){clip.start_seconds=after;clip.preserve_source_asset=true;clip.destructive_edit=false;movedClips++;}if(clip.audio_post){const oldSync=Math.max(0,Math.round(finite(clip.audio_post.sync_frame,musicSecondsToFrames(before,oldFps)))),newSync=mapAudioPostFrame(oldSync,map);if(newSync!==oldSync){clip.audio_post.sync_frame=newSync;clip.audio_post.sync_seconds=musicFramesToSeconds(newSync,newFps);clip.audio_post.sync_timecode=null;if(clip.audio_post.dialogue_edit_approved===true){clip.audio_post.dialogue_edit_approved=false;editorialApprovalsInvalidated++;}clip.audio_post.reconform_required_review=true;clip.audio_post.reconformed_from_sync_frame=oldSync;}}}
  }
  for(const lane of next.automation_lanes||[]){for(const point of lane.points||[]){const before=finite(point.time_seconds,0),after=mapSeconds(before,oldFps,newFps,map);if(Math.abs(after-before)>.000001){point.time_seconds=after;movedAutomationPoints++;}}(lane.points||[]).sort((a,b)=>a.time_seconds-b.time_seconds);}
  next.picture_lock=nextPicture;next.timeline={...(next.timeline||{}),timebase:"PICTURE_FRAMES",frame_rate:newFps,picture_duration_seconds:nextPicture.duration_seconds,picture_lock_digest:nextPicture.picture_lock_digest,start_timecode:nextPicture.start_timecode};
  next.audio_post_reconform={contract:CONTRACT,from_picture_lock_digest:oldPicture.picture_lock_digest,to_picture_lock_digest:nextPicture.picture_lock_digest,conform_map:map,moved_clip_count:movedClips,moved_automation_point_count:movedAutomationPoints,editorial_approvals_invalidated:editorialApprovalsInvalidated,source_audio_rewritten:false,original_sources_preserved:true,completed_at:new Date().toISOString()};
  return{session:next,report:next.audio_post_reconform};
}

export function previewAudioPostReconform(sessionInput={},nextPictureInput={},conformMapInput=[]){
  const oldPicture=sessionInput?.picture_lock;if(!oldPicture?.picture_lock_digest)throw new Error("CREATIVE_AUDIO_POST_RECONFORM_CURRENT_PICTURE_REQUIRED");
  const nextPicture=createMusicPictureLock(nextPictureInput),map=normalizeAudioPostConformMap(conformMapInput);if(!map.length)throw new Error("CREATIVE_AUDIO_POST_RECONFORM_MAP_REQUIRED");
  const oldFps=finite(oldPicture.frame_rate,24),newFps=finite(nextPicture.frame_rate,oldFps),clips=[],automation=[];let approvals=0;
  for(const track of sessionInput.tracks||[]){for(const clip of track.clips||[]){const before=finite(clip.start_seconds,0),after=mapSeconds(before,oldFps,newFps,map),oldSync=clip.audio_post?Math.max(0,Math.round(finite(clip.audio_post.sync_frame,musicSecondsToFrames(before,oldFps)))):null,newSync=oldSync==null?null:mapAudioPostFrame(oldSync,map);if(Math.abs(after-before)>.000001||newSync!==oldSync){const invalidates=clip.audio_post?.dialogue_edit_approved===true&&newSync!==oldSync;if(invalidates)approvals++;clips.push({track_id:track.id,clip_id:clip.id,source_asset_id:clip.source_asset_id||null,from_seconds:before,to_seconds:after,from_sync_frame:oldSync,to_sync_frame:newSync,editorial_approval_will_invalidate:invalidates});}}}
  for(const lane of sessionInput.automation_lanes||[]){for(let index=0;index<(lane.points||[]).length;index++){const point=lane.points[index],before=finite(point.time_seconds,0),after=mapSeconds(before,oldFps,newFps,map);if(Math.abs(after-before)>.000001)automation.push({lane_id:lane.id||null,target_type:lane.target_type||null,target_id:lane.target_id||null,parameter:lane.parameter||null,point_index:index,from_seconds:before,to_seconds:after});}}
  return{contract:"AVANTIQO_AUDIO_POST_RECONFORM_PREVIEW_V1",from_picture_lock_digest:oldPicture.picture_lock_digest,to_picture_lock_digest:nextPicture.picture_lock_digest,from_picture:{asset_id:oldPicture.picture_asset_id,cut_id:oldPicture.cut_id,duration_seconds:oldPicture.duration_seconds,frame_rate:oldPicture.frame_rate},to_picture:{asset_id:nextPicture.picture_asset_id,cut_id:nextPicture.cut_id,duration_seconds:nextPicture.duration_seconds,frame_rate:nextPicture.frame_rate},conform_map:map,affected_clips:clips,affected_automation_points:automation,moved_clip_count:clips.length,moved_automation_point_count:automation.length,editorial_approvals_will_invalidate:approvals,source_audio_will_be_rewritten:false,original_sources_preserved:true,mutation_performed:false,delivery_seal_will_be_invalidated:true};
}

export const CreativeAudioPostReconformRuntime=Object.freeze({contract:CONTRACT,normalizeMap:normalizeAudioPostConformMap,mapFrame:mapAudioPostFrame,preview:previewAudioPostReconform,reconform:reconformAudioPostSession});
