import fs from "node:fs/promises";
import { materializeMedia } from "@/lib/creative/media/runtime/CreativeMediaInspectionRuntime";

const CONTRACT="AVANTIQO_MUSIC_BWF_VERIFICATION_V1";
function text(v){return String(v??"").trim();}function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function expectedTimeReference(startTimecode,frameRate,sampleRate){const [h=0,m=0,s=0,f=0]=text(startTimecode||"00:00:00:00").split(":").map(v=>Math.max(0,Math.floor(finite(v,0))));return Math.round((h*3600+m*60+s+f/Math.max(1,finite(frameRate,24)))*sampleRate);}
function readAscii(buffer,offset,length){return buffer.subarray(offset,offset+length).toString("ascii").replace(/\0+$/g,"").trim();}
function chunks(buffer){const rows=[];let offset=12;while(offset+8<=buffer.length){const id=readAscii(buffer,offset,4),size=buffer.readUInt32LE(offset+4);if(!id||size<0||offset+8+size>buffer.length)break;rows.push({id,size,offset,payload_offset:offset+8});offset+=8+size+(size%2);}return rows;}
function parseBext(buffer,row){if(!row||row.size<348)return null;const p=row.payload_offset,low=buffer.readUInt32LE(p+338),high=buffer.readUInt32LE(p+342);return{description:readAscii(buffer,p,256),originator:readAscii(buffer,p+256,32),originator_reference:readAscii(buffer,p+288,32),origination_date:readAscii(buffer,p+320,10),origination_time:readAscii(buffer,p+330,8),time_reference_samples:high*4294967296+low,version:buffer.readUInt16LE(p+346)};}
function parseFmt(buffer,row){if(!row||row.size<16)return null;const p=row.payload_offset;return{format_tag:buffer.readUInt16LE(p),channels:buffer.readUInt16LE(p+2),sample_rate:buffer.readUInt32LE(p+4),bit_depth:buffer.readUInt16LE(p+14),channel_mask:row.size>=24?buffer.readUInt32LE(p+20):null,wave_format_extensible:buffer.readUInt16LE(p)===0xfffe};}
export async function verifyMusicBwfDelivery({organization_id,file_url,file_name="audio.wav",mime_type="audio/wav",expected={}}={}){if(!organization_id||!file_url)throw new Error("CREATIVE_MUSIC_BWF_SOURCE_REQUIRED");const media=await materializeMedia({organization_id,url:file_url,file_name,mime_type,policy:{max_bytes:2_147_483_648,timeout_ms:300000,max_redirects:0}});try{const buffer=await fs.readFile(media.file_path);if(readAscii(buffer,0,4)!=="RIFF"||readAscii(buffer,8,4)!=="WAVE")throw new Error("CREATIVE_MUSIC_BWF_WAV_REQUIRED");const rows=chunks(buffer),fmt=parseFmt(buffer,rows.find(r=>r.id==="fmt")),bext=parseBext(buffer,rows.find(r=>r.id==="bext")),failures=[];if(!bext)failures.push("BWF_BEXT_CHUNK_REQUIRED");if(!fmt)failures.push("BWF_FMT_CHUNK_REQUIRED");const expectedRate=Math.round(finite(expected.sample_rate,fmt?.sample_rate||48000));if(fmt&&fmt.sample_rate!==expectedRate)failures.push("BWF_SAMPLE_RATE_MISMATCH");if(fmt&&Math.round(finite(expected.bit_depth,24))!==fmt.bit_depth)failures.push("BWF_BIT_DEPTH_MISMATCH");const expectedReference=expectedTimeReference(expected.start_timecode,expected.frame_rate,expectedRate);if(bext&&bext.time_reference_samples!==expectedReference)failures.push("BWF_TIME_REFERENCE_MISMATCH");if(expected.channels&&fmt&&fmt.channels!==Math.round(expected.channels))failures.push("BWF_CHANNEL_COUNT_MISMATCH");if(expected.require_extensible===true&&fmt?.wave_format_extensible!==true)failures.push("BWF_WAVE_FORMAT_EXTENSIBLE_REQUIRED");return{contract:CONTRACT,passed:failures.length===0,failures,bext_present:Boolean(bext),bext,format:fmt,expected:{start_timecode:text(expected.start_timecode||"00:00:00:00"),frame_rate:finite(expected.frame_rate,24),sample_rate:expectedRate,bit_depth:Math.round(finite(expected.bit_depth,24)),channels:expected.channels||null,time_reference_samples:expectedReference,require_extensible:expected.require_extensible===true},file_size_bytes:buffer.length,actual_file_bytes_verified:true};}finally{await media.cleanup().catch(()=>{});}}
export const CreativeMusicBwfVerificationRuntime=Object.freeze({contract:CONTRACT,verify:verifyMusicBwfDelivery});
