const profile = (value) => Object.freeze({
  ...value,
  capabilityIds: Object.freeze([...(value.capabilityIds || [])]),
  primaryActions: Object.freeze([...(value.primaryActions || [])].map(Object.freeze)),
  stages: Object.freeze([...(value.stages || [])].map((stage) => Object.freeze({
    ...stage,
    capabilityIds: Object.freeze([...(stage.capabilityIds || [])]),
  }))),
  tools: Object.freeze([...(value.tools || [])].map(Object.freeze)),
});

export const OPERATIONS_INDUSTRY_PROFILES = Object.freeze({
  retail: profile({
    id: "retail",
    eyebrow: "Retail Operations",
    title: "Retail Control",
    description: "Sell, fulfill and resolve store work from one operating view. Transaction execution stays in POS while inventory, customer, commercial and finance truth remain with their canonical owners.",
    capabilityIds: [
      "order-capture", "checkout", "receipts", "cash-control", "fulfillment-dispatch",
      "queue-entries", "work-items", "assignments", "incidents", "exceptions-holds",
    ],
    primaryActions: [
      { id: "sell", label: "Start selling", route: "/operations/pos" },
      { id: "inventory", label: "Check inventory", route: "/supply-chain/inventory" },
      { id: "customers", label: "Customers", route: "/commercial/customers" },
    ],
    stages: [
      { id: "sale", label: "Sell", description: "Basket and customer sale", capabilityIds: ["order-capture"], route: "/operations/pos" },
      { id: "settle", label: "Settle", description: "Payment and receipt", capabilityIds: ["checkout", "receipts"], route: "/operations/pos" },
      { id: "fulfill", label: "Fulfill", description: "Pickup or delivery handoff", capabilityIds: ["fulfillment-dispatch"], route: "/operations/fulfillment-dispatch" },
      { id: "exceptions", label: "Resolve exceptions", description: "Holds, incidents and waiting work", capabilityIds: ["exceptions-holds", "incidents", "queue-entries"], route: "/operations/queue-entries" },
    ],
    tools: [
      { id: "orders", label: "Orders", description: "Review transaction history and open orders", route: "/operations/pos?view=orders" },
      { id: "receipts", label: "Receipts", description: "Receipt history and reissue", route: "/operations/pos?view=receipts" },
      { id: "cash", label: "Cash control", description: "Drawer and shift reconciliation", route: "/operations/pos?view=cash-control" },
      { id: "inventory", label: "Inventory", description: "Stock, movement and replenishment", route: "/supply-chain/inventory" },
      { id: "commercial", label: "Commercial", description: "Pricing, campaigns and customers", route: "/commercial" },
      { id: "finance", label: "Finance", description: "Accounting and settlement control", route: "/finance" },
    ],
    boundary: "Operations owns transaction execution and fulfillment. Supply Chain owns stock; Commercial owns customer and pricing truth; Finance owns accounting and settlement records.",
  }),

  fieldService: profile({
    id: "field-service",
    eyebrow: "Field Service Operations",
    title: "Service Control",
    description: "Run the technician day as one service lifecycle: committed visit → dispatch → perform work → capture evidence → resolve follow-up. Recurring service definitions remain configurable rather than industry hardcoded.",
    capabilityIds: [
      "work-orders", "appointment-windows", "dispatch", "assignments", "queue-entries",
      "work-items", "completion-evidence", "checklists", "incidents", "exceptions-holds",
      "escalations", "corrective-actions",
    ],
    primaryActions: [
      { id: "dispatch", label: "Open dispatch board", route: "/operations/dispatch" },
      { id: "orders", label: "Service orders", route: "/operations/work-orders" },
      { id: "appointments", label: "Appointments", route: "/operations/appointment-windows" },
    ],
    stages: [
      { id: "committed", label: "Committed", description: "Approved service work and appointment windows", capabilityIds: ["work-orders", "appointment-windows"], route: "/operations/work-orders" },
      { id: "dispatch", label: "Dispatch", description: "Assign and release work", capabilityIds: ["dispatch", "assignments", "queue-entries"], route: "/operations/dispatch" },
      { id: "execute", label: "On site", description: "Active technician execution", capabilityIds: ["work-items", "checklists"], route: "/operations/work-items" },
      { id: "prove", label: "Complete & prove", description: "Evidence and acknowledgement", capabilityIds: ["completion-evidence"], route: "/operations/completion-evidence" },
      { id: "followup", label: "Follow-up", description: "Exceptions, escalation and corrective action", capabilityIds: ["exceptions-holds", "incidents", "escalations", "corrective-actions"], route: "/operations/exceptions-holds" },
    ],
    tools: [
      { id: "plans", label: "Service plans", description: "Recurring customer commitments", route: "/operations/field-service/service-plans" },
      { id: "templates", label: "Execution protocols", description: "Dynamic inspection and evidence templates", route: "/operations/field-service/execution-templates" },
      { id: "reports", label: "Service reports", description: "Completed work and customer-safe evidence", route: "/operations/field-service/service-reports" },
      { id: "queue", label: "Service queue", description: "Waiting and unassigned service work", route: "/operations/queue-entries" },
      { id: "evidence", label: "Completion evidence", description: "Proof of service and sign-off", route: "/operations/completion-evidence" },
      { id: "incidents", label: "Incidents", description: "Field disruption and recovery", route: "/operations/incidents" },
    ],
    boundary: "Operations owns service execution, dispatch, responsibility and evidence. Service/Commercial own customer commitments; People owns workforce authority; Supply Chain owns materials; Finance owns billing and accounting.",
  }),

  construction: profile({
    id: "construction",
    eyebrow: "Project & Field Operations",
    title: "Field Execution Control",
    description: "Move authorized field work from ready-to-start through dispatch, execution, inspection and completion evidence without turning project, procurement or finance data into Operations duplicates.",
    capabilityIds: [
      "work-orders", "queue-entries", "dispatch", "assignments", "work-items", "checklists",
      "completion-evidence", "incidents", "exceptions-holds", "corrective-actions", "quality-checks",
    ],
    primaryActions: [
      { id: "work", label: "Open field work", route: "/operations/work-orders" },
      { id: "dispatch", label: "Dispatch", route: "/operations/dispatch" },
      { id: "incidents", label: "Report incident", route: "/operations/incidents" },
    ],
    stages: [
      { id: "ready", label: "Ready", description: "Authorized work waiting for execution", capabilityIds: ["work-orders", "queue-entries"], route: "/operations/work-orders" },
      { id: "assigned", label: "Assigned", description: "Dispatched field responsibility", capabilityIds: ["dispatch", "assignments"], route: "/operations/dispatch" },
      { id: "execute", label: "Execute", description: "Active field work and procedures", capabilityIds: ["work-items", "checklists"], route: "/operations/work-items" },
      { id: "inspect", label: "Inspect", description: "Quality and exception resolution", capabilityIds: ["quality-checks", "exceptions-holds", "corrective-actions"], route: "/operations/quality-checks" },
      { id: "complete", label: "Complete", description: "Evidence-backed completion", capabilityIds: ["completion-evidence"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "assignments", label: "Assignments", description: "Accountable responsibility", route: "/operations/assignments" },
      { id: "queue", label: "Work queue", description: "Waiting field demand", route: "/operations/queue-entries" },
      { id: "quality", label: "Quality checks", description: "Inspection and release", route: "/operations/quality-checks" },
      { id: "incidents", label: "Incidents", description: "Safety and operating disruption", route: "/operations/incidents" },
      { id: "projects", label: "Projects", description: "Scope, milestones and project governance", route: "/projects" },
      { id: "materials", label: "Supply Chain", description: "Procurement and material availability", route: "/supply-chain" },
    ],
    boundary: "Operations owns accountable field execution. Projects and Commercial own scope and commitments; Supply Chain owns procurement/materials; Finance owns budgets, accounting and settlement.",
  }),

  manufacturing: profile({
    id: "manufacturing",
    eyebrow: "Manufacturing Operations",
    title: "Production Control",
    description: "Run production by exception: release work, execute at work centres, watch quality and downtime, prove completion, then hand material and costing truth to their canonical domains.",
    capabilityIds: [
      "work-orders", "operational-runs", "work-centres", "assignments", "work-items",
      "quality-checks", "quality-inspections", "resource-downtime", "exceptions-holds",
      "corrective-actions", "completion-evidence", "queue-entries",
    ],
    primaryActions: [
      { id: "runs", label: "Production runs", route: "/operations/operational-runs" },
      { id: "work", label: "Work orders", route: "/operations/work-orders" },
      { id: "quality", label: "Quality", route: "/operations/quality-checks" },
    ],
    stages: [
      { id: "release", label: "Release", description: "Authorized production demand", capabilityIds: ["work-orders", "queue-entries"], route: "/operations/work-orders" },
      { id: "run", label: "Run", description: "Active batches and station execution", capabilityIds: ["operational-runs", "work-items", "assignments"], route: "/operations/operational-runs" },
      { id: "quality", label: "Quality", description: "In-process and final checks", capabilityIds: ["quality-checks", "quality-inspections"], route: "/operations/quality-checks" },
      { id: "exceptions", label: "Downtime & holds", description: "Constraints requiring intervention", capabilityIds: ["resource-downtime", "exceptions-holds", "corrective-actions"], route: "/operations/resource-downtime" },
      { id: "complete", label: "Complete", description: "Evidence-backed production completion", capabilityIds: ["completion-evidence"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "centres", label: "Work centres", description: "Stations, lines and equipment capacity", route: "/operations/work-centres" },
      { id: "usage", label: "Material usage", description: "Issue and consume production material", route: "/supply-chain/production/usage" },
      { id: "batches", label: "Output receipt", description: "Receive completed output into stock", route: "/supply-chain/production/batches" },
      { id: "waste", label: "Scrap & waste", description: "Record production losses", route: "/supply-chain/production/waste" },
      { id: "costing", label: "Production costing", description: "Cost and variance accounting", route: "/supply-chain/production/costing" },
      { id: "people", label: "Workforce", description: "Labour coverage and time", route: "/people" },
    ],
    boundary: "Operations owns execution, quality and downtime. Supply Chain owns material/output stock; People owns labour; Finance owns production accounting and variance.",
  }),

  venue: profile({
    id: "venue",
    eyebrow: "Venue Operations",
    title: "Live Venue Control",
    description: "Keep service moving during live trading: sell and settle in POS, route operational work, resolve incidents and preserve accountable handoffs without making event planning part of the execution kernel.",
    capabilityIds: [
      "order-capture", "checkout", "receipts", "cash-control", "queue-entries",
      "work-items", "assignments", "handoffs", "incidents", "escalations", "exceptions-holds",
    ],
    primaryActions: [
      { id: "pos", label: "Open POS", route: "/operations/pos" },
      { id: "queue", label: "Live work queue", route: "/operations/queue-entries" },
      { id: "incident", label: "Report incident", route: "/operations/incidents" },
    ],
    stages: [
      { id: "serve", label: "Serve", description: "Sales, payment and receipts", capabilityIds: ["order-capture", "checkout", "receipts"], route: "/operations/pos" },
      { id: "coordinate", label: "Coordinate", description: "Waiting work and assignments", capabilityIds: ["queue-entries", "assignments", "work-items"], route: "/operations/queue-entries" },
      { id: "handoff", label: "Handoff", description: "Ownership changes during live service", capabilityIds: ["handoffs"], route: "/operations/handoffs" },
      { id: "resolve", label: "Resolve", description: "Incidents, escalation and holds", capabilityIds: ["incidents", "escalations", "exceptions-holds"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "cash", label: "Cash control", description: "Shift and drawer reconciliation", route: "/operations/pos?view=cash-control" },
      { id: "receipts", label: "Receipts", description: "Receipt history and reissue", route: "/operations/pos?view=receipts" },
      { id: "assignments", label: "Assignments", description: "Active responsibility", route: "/operations/assignments" },
      { id: "handoffs", label: "Handoffs", description: "Controlled ownership transfer", route: "/operations/handoffs" },
      { id: "incidents", label: "Incident log", description: "Disruption and recovery", route: "/operations/incidents" },
      { id: "commercial", label: "Commercial events", description: "Campaign and event planning", route: "/commercial" },
    ],
    boundary: "Operations owns live venue execution and incidents. Commercial owns event/campaign planning; Finance owns accounting; People owns workforce authority.",
  }),

  healthcare: profile({
    id: "healthcare",
    eyebrow: "Healthcare Operations",
    title: "Patient Flow Operations",
    description: "Coordinate operational patient flow without turning Operations into the clinical system of record. Clinical workflows remain owned by Healthcare; Operations manages neutral queues, assignments, incidents and service execution visibility.",
    capabilityIds: ["queue-entries", "assignments", "work-items", "handoffs", "incidents", "escalations", "exceptions-holds"],
    primaryActions: [
      { id: "dashboard", label: "Healthcare dashboard", route: "/healthcare/dashboard" },
      { id: "appointments", label: "Appointments", route: "/healthcare/appointments" },
      { id: "queue", label: "Operational queue", route: "/operations/queue-entries" },
    ],
    stages: [
      { id: "arrive", label: "Arrive & queue", description: "Clinical demand enters operational flow", capabilityIds: ["queue-entries"], route: "/operations/queue-entries" },
      { id: "assign", label: "Assign", description: "Accountable service responsibility", capabilityIds: ["assignments"], route: "/operations/assignments" },
      { id: "serve", label: "Coordinate service", description: "Non-clinical execution and handoff", capabilityIds: ["work-items", "handoffs"], route: "/operations/work-items" },
      { id: "resolve", label: "Resolve disruption", description: "Operational incidents and escalations", capabilityIds: ["incidents", "escalations", "exceptions-holds"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "admissions", label: "Admissions", description: "Healthcare-owned admission/discharge", route: "/healthcare/admissions" },
      { id: "beds", label: "Beds & wards", description: "Healthcare-owned capacity state", route: "/healthcare/beds" },
      { id: "pharmacy", label: "Pharmacy", description: "Healthcare-owned medication workflow", route: "/healthcare/pharmacy" },
      { id: "records", label: "Medical records", description: "Controlled clinical records", route: "/healthcare/medical-records" },
      { id: "incidents", label: "Operational incidents", description: "Non-clinical disruption coordination", route: "/operations/incidents" },
      { id: "assignments", label: "Operational assignments", description: "Neutral accountability", route: "/operations/assignments" },
    ],
    boundary: "Healthcare remains authoritative for patients, appointments, admissions, beds, clinical records, pharmacy and clinical decisions. Operations coordinates non-clinical execution only.",
  }),


  education: profile({
    id: "education",
    eyebrow: "Education Operations",
    title: "School Day Control",
    description: "Run the school day around timetable delivery, rooms, staff responsibility, learner-support work, controlled handoffs and safeguarding incidents while academic records remain with the education system of record.",
    capabilityIds: [
      "work-orders", "work-schedules", "resource-schedules", "resource-reservations",
      "assignments", "work-items", "handoffs", "checklists", "incidents",
      "escalations", "completion-evidence", "quality-checks",
    ],
    primaryActions: [
      { id: "day", label: "Today’s school work", route: "/operations/work-items" },
      { id: "schedule", label: "Timetable operations", route: "/operations/work-schedules" },
      { id: "incidents", label: "Safeguarding & incidents", route: "/operations/incidents" },
    ],
    stages: [
      { id: "plan", label: "Timetable", description: "Classes, activities, rooms and operating windows", capabilityIds: ["work-schedules", "resource-schedules", "resource-reservations"], route: "/operations/work-schedules" },
      { id: "prepare", label: "Prepare", description: "Assigned staff and ready learning spaces", capabilityIds: ["assignments", "work-orders"], route: "/operations/assignments" },
      { id: "deliver", label: "Deliver", description: "Teaching, supervision and support work", capabilityIds: ["work-items", "checklists"], route: "/operations/work-items" },
      { id: "handoff", label: "Handoff", description: "Controlled transitions between staff and activities", capabilityIds: ["handoffs"], route: "/operations/handoffs" },
      { id: "protect", label: "Protect", description: "Safeguarding, incidents and escalation", capabilityIds: ["incidents", "escalations", "completion-evidence"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "rooms", label: "Rooms & spaces", description: "Reserve classrooms, labs, sports and shared spaces", route: "/operations/resource-reservations" },
      { id: "checklists", label: "Opening / closing checks", description: "Controlled school-day and facility checks", route: "/operations/checklists" },
      { id: "quality", label: "Operational quality", description: "Verify service and environment readiness", route: "/operations/quality-checks" },
      { id: "people", label: "People", description: "Rosters, attendance and workforce authority", route: "/people" },
      { id: "documents", label: "Documents", description: "Policies, forms and controlled records", route: "/documents" },
      { id: "finance", label: "Finance", description: "Fees, accounting and settlement", route: "/finance" },
    ],
    boundary: "Operations coordinates the school day, spaces, responsibilities and incidents. Student academic records, grades and curriculum truth remain outside Operations; People owns workforce records and Finance owns accounting.",
  }),

  automotive: profile({
    id: "automotive",
    eyebrow: "Automotive Service Operations",
    title: "Workshop Control",
    description: "Run vehicle intake through diagnosis, bay assignment, repair, inspection and customer-ready handoff with traceable parts and completion evidence.",
    capabilityIds: [
      "work-requests", "work-orders", "appointment-windows", "queue-entries", "assignments",
      "work-items", "resource-reservations", "resource-downtime", "checklists",
      "quality-inspections", "quality-checks", "completion-evidence", "exceptions-holds",
    ],
    primaryActions: [
      { id: "intake", label: "Vehicle intake", route: "/operations/work-requests" },
      { id: "work", label: "Workshop jobs", route: "/operations/work-orders" },
      { id: "bays", label: "Bays & equipment", route: "/operations/resource-reservations" },
    ],
    stages: [
      { id: "book", label: "Book & intake", description: "Appointment, vehicle concern and authorization", capabilityIds: ["appointment-windows", "work-requests"], route: "/operations/work-requests" },
      { id: "diagnose", label: "Diagnose", description: "Inspection, estimate evidence and job scope", capabilityIds: ["checklists", "work-orders"], route: "/operations/checklists" },
      { id: "repair", label: "Repair", description: "Bay, technician and active work execution", capabilityIds: ["assignments", "work-items", "resource-reservations"], route: "/operations/work-items" },
      { id: "inspect", label: "Quality check", description: "Final inspection, road-test and release decision", capabilityIds: ["quality-inspections", "quality-checks", "exceptions-holds"], route: "/operations/quality-inspections" },
      { id: "handover", label: "Customer ready", description: "Completion evidence and controlled handover", capabilityIds: ["completion-evidence"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "appointments", label: "Appointments", description: "Booked workshop windows", route: "/operations/appointment-windows" },
      { id: "queue", label: "Workshop queue", description: "Waiting and unassigned vehicles", route: "/operations/queue-entries" },
      { id: "downtime", label: "Equipment downtime", description: "Unavailable lifts, tools and equipment", route: "/operations/resource-downtime" },
      { id: "parts", label: "Parts inventory", description: "Parts stock, issue and replenishment", route: "/supply-chain/inventory" },
      { id: "customers", label: "Customers", description: "Customer and vehicle commercial context", route: "/commercial/customers" },
      { id: "finance", label: "Billing", description: "Invoice and payment accounting", route: "/finance" },
    ],
    boundary: "Operations owns workshop execution, bay control, inspections and handover evidence. Supply Chain owns parts stock; Commercial owns customer commitments; Finance owns invoices, payments and accounting.",
  }),

  logistics: profile({
    id: "logistics",
    eyebrow: "Logistics Operations",
    title: "Transport & Dispatch Control",
    description: "Move committed loads through planning, routing, dispatch, custody handoffs, delivery proof and exception recovery.",
    capabilityIds: [
      "work-orders", "workload-planning", "routing", "dispatch", "assignments", "queue-entries",
      "resource-schedules", "resource-availability", "handoffs", "completion-evidence",
      "incidents", "exceptions-holds", "service-level-breaches",
    ],
    primaryActions: [
      { id: "dispatch", label: "Dispatch board", route: "/operations/dispatch" },
      { id: "loads", label: "Loads & jobs", route: "/operations/work-orders" },
      { id: "routing", label: "Routes", route: "/operations/routing" },
    ],
    stages: [
      { id: "plan", label: "Plan", description: "Loads, routes and capacity", capabilityIds: ["workload-planning", "routing", "resource-schedules"], route: "/operations/workload-planning" },
      { id: "dispatch", label: "Dispatch", description: "Vehicle/resource assignment and release", capabilityIds: ["dispatch", "assignments", "queue-entries"], route: "/operations/dispatch" },
      { id: "move", label: "Move", description: "Active transport execution and custody", capabilityIds: ["work-orders", "handoffs"], route: "/operations/work-orders" },
      { id: "prove", label: "Deliver & prove", description: "Delivery evidence and acknowledgement", capabilityIds: ["completion-evidence"], route: "/operations/completion-evidence" },
      { id: "recover", label: "Recover exceptions", description: "Delay, incident, hold and SLA recovery", capabilityIds: ["incidents", "exceptions-holds", "service-level-breaches"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "availability", label: "Fleet/resource availability", description: "Operational vehicles and resources", route: "/operations/resource-availability" },
      { id: "handoffs", label: "Custody handoffs", description: "Accountable transfer between execution parties", route: "/operations/handoffs" },
      { id: "sla", label: "Service breaches", description: "Late and failed commitments", route: "/operations/service-level-breaches" },
      { id: "inventory", label: "Warehouse inventory", description: "Stock truth and movement", route: "/supply-chain/inventory" },
      { id: "people", label: "Drivers & workforce", description: "People-owned eligibility and rosters", route: "/people" },
      { id: "finance", label: "Finance", description: "Cost, billing and settlement", route: "/finance" },
    ],
    boundary: "Operations owns route execution, dispatch and proof. Supply Chain owns stock; People owns driver employment and qualifications; Finance owns accounting and settlement.",
  }),

  facilities: profile({
    id: "facilities",
    eyebrow: "Facilities Operations",
    title: "Property & Maintenance Control",
    description: "Run requests, planned maintenance, reactive work, contractors, assets, inspections and evidence across properties and facilities.",
    capabilityIds: [
      "work-requests", "work-orders", "recurring-work", "work-schedules", "dispatch", "assignments",
      "equipment", "resource-downtime", "checklists", "quality-inspections",
      "incidents", "completion-evidence", "service-level-breaches",
    ],
    primaryActions: [
      { id: "requests", label: "Service requests", route: "/operations/work-requests" },
      { id: "orders", label: "Maintenance work", route: "/operations/work-orders" },
      { id: "schedule", label: "Planned maintenance", route: "/operations/recurring-work" },
    ],
    stages: [
      { id: "request", label: "Request", description: "Reactive demand and planned maintenance", capabilityIds: ["work-requests", "recurring-work"], route: "/operations/work-requests" },
      { id: "plan", label: "Plan", description: "Priority, timing and resource readiness", capabilityIds: ["work-orders", "work-schedules"], route: "/operations/work-orders" },
      { id: "execute", label: "Execute", description: "Dispatch, assignment and maintenance work", capabilityIds: ["dispatch", "assignments"], route: "/operations/dispatch" },
      { id: "inspect", label: "Inspect", description: "Safety, quality and return-to-service checks", capabilityIds: ["checklists", "quality-inspections"], route: "/operations/quality-inspections" },
      { id: "prove", label: "Close", description: "Evidence, SLA and incident closure", capabilityIds: ["completion-evidence", "service-level-breaches", "incidents"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "equipment", label: "Equipment", description: "Operational asset references and condition", route: "/operations/equipment" },
      { id: "downtime", label: "Downtime", description: "Unavailable plant and facilities", route: "/operations/resource-downtime" },
      { id: "incidents", label: "Incidents", description: "Facility disruption and response", route: "/operations/incidents" },
      { id: "materials", label: "Materials", description: "Maintenance stock and procurement", route: "/supply-chain" },
      { id: "documents", label: "Compliance documents", description: "Permits, records and controlled evidence", route: "/documents" },
      { id: "finance", label: "Cost control", description: "Supplier costs and accounting", route: "/finance" },
    ],
    boundary: "Operations owns maintenance execution and operating evidence. Asset masters, legal property records, procurement and accounting remain in their canonical domains.",
  }),

  professionalServices: profile({
    id: "professional-services",
    eyebrow: "Professional Services Operations",
    title: "Client Delivery Control",
    description: "Run client commitments through scoped work, staffing, delivery, approvals, evidence and SLA control while Projects, Commercial and Finance retain their canonical records.",
    capabilityIds: [
      "work-requests", "work-orders", "work-packages", "work-schedules", "assignments", "work-items",
      "operational-approvals", "handoffs", "completion-evidence", "service-levels",
      "service-level-breaches", "exceptions-holds",
    ],
    primaryActions: [
      { id: "delivery", label: "Active client work", route: "/operations/work-items" },
      { id: "schedule", label: "Delivery schedule", route: "/operations/work-schedules" },
      { id: "approvals", label: "Approvals", route: "/operations/operational-approvals" },
    ],
    stages: [
      { id: "intake", label: "Intake", description: "Qualified client request and authorized scope", capabilityIds: ["work-requests", "work-orders"], route: "/operations/work-requests" },
      { id: "plan", label: "Plan", description: "Work package, schedule and responsibility", capabilityIds: ["work-packages", "work-schedules", "assignments"], route: "/operations/work-packages" },
      { id: "deliver", label: "Deliver", description: "Active accountable client work", capabilityIds: ["work-items"], route: "/operations/work-items" },
      { id: "review", label: "Review & approve", description: "Controlled approval and handoff", capabilityIds: ["operational-approvals", "handoffs"], route: "/operations/operational-approvals" },
      { id: "close", label: "Close", description: "Completion evidence and SLA resolution", capabilityIds: ["completion-evidence", "service-level-breaches", "exceptions-holds"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "projects", label: "Projects", description: "Scope, milestones and project economics", route: "/projects" },
      { id: "clients", label: "Clients", description: "Commercial relationship and commitments", route: "/commercial/customers" },
      { id: "documents", label: "Client documents", description: "Controlled files and deliverables", route: "/documents" },
      { id: "people", label: "People", description: "Skills, availability and workforce truth", route: "/people" },
      { id: "sla", label: "Service levels", description: "Response and completion commitments", route: "/operations/service-levels" },
      { id: "finance", label: "Billing & profitability", description: "Invoices, time value and accounting", route: "/finance" },
    ],
    boundary: "Operations owns execution and delivery control. Projects owns project scope; Commercial owns client truth; Documents owns files; People owns workforce; Finance owns billing and accounting.",
  }),

  rentalFleet: profile({
    id: "rental-fleet",
    eyebrow: "Rental & Fleet Operations",
    title: "Fleet & Handover Control",
    description: "Control vehicle or equipment availability, reservations, inspection, customer handover, returns, damage evidence and maintenance downtime.",
    capabilityIds: [
      "resource-availability", "resource-reservations", "appointment-windows", "work-orders",
      "checklists", "handoffs", "completion-evidence", "incidents", "resource-downtime",
      "quality-inspections", "order-capture", "checkout", "receipts",
    ],
    primaryActions: [
      { id: "availability", label: "Availability", route: "/operations/resource-availability" },
      { id: "reservations", label: "Reservations", route: "/operations/resource-reservations" },
      { id: "handover", label: "Handover / return", route: "/operations/handoffs" },
    ],
    stages: [
      { id: "reserve", label: "Reserve", description: "Availability and committed reservation", capabilityIds: ["resource-availability", "resource-reservations", "appointment-windows"], route: "/operations/resource-reservations" },
      { id: "prepare", label: "Prepare", description: "Pre-handover inspection and readiness", capabilityIds: ["checklists", "quality-inspections"], route: "/operations/checklists" },
      { id: "handover", label: "Handover", description: "Custody, payment and condition evidence", capabilityIds: ["handoffs", "checkout", "receipts"], route: "/operations/handoffs" },
      { id: "return", label: "Return", description: "Return inspection and damage evidence", capabilityIds: ["completion-evidence", "incidents"], route: "/operations/completion-evidence" },
      { id: "recover", label: "Maintain", description: "Repair, downtime and return to availability", capabilityIds: ["work-orders", "resource-downtime"], route: "/operations/work-orders" },
    ],
    tools: [
      { id: "pos", label: "Payment", description: "Deposits, charges and receipts", route: "/operations/pos" },
      { id: "inspections", label: "Inspections", description: "Condition and safety checks", route: "/operations/quality-inspections" },
      { id: "damage", label: "Damage evidence", description: "Photo and completion evidence", route: "/operations/completion-evidence" },
      { id: "maintenance", label: "Maintenance", description: "Fleet service work and downtime", route: "/operations/work-orders" },
      { id: "customers", label: "Customers", description: "Commercial customer records", route: "/commercial/customers" },
      { id: "finance", label: "Finance", description: "Deposits, settlement and accounting", route: "/finance" },
    ],
    boundary: "Operations owns availability, custody handoffs, inspections and maintenance execution. Commercial owns customer/rental commitments; Finance owns deposits and accounting.",
  }),

  salonSpa: profile({
    id: "salon-spa",
    eyebrow: "Salon & Spa Operations",
    title: "Appointment & Service Control",
    description: "Run bookings, therapist or stylist assignment, room/chair capacity, treatment delivery, checkout, rebooking and service recovery.",
    capabilityIds: [
      "appointment-windows", "queue-entries", "assignments", "resource-reservations",
      "work-items", "checklists", "order-capture", "checkout", "receipts",
      "incidents", "completion-evidence",
    ],
    primaryActions: [
      { id: "appointments", label: "Appointments", route: "/operations/appointment-windows" },
      { id: "service", label: "Today’s services", route: "/operations/work-items" },
      { id: "checkout", label: "Checkout", route: "/operations/pos" },
    ],
    stages: [
      { id: "book", label: "Book", description: "Appointment and service commitment", capabilityIds: ["appointment-windows"], route: "/operations/appointment-windows" },
      { id: "prepare", label: "Prepare", description: "Staff and room/chair readiness", capabilityIds: ["assignments", "resource-reservations"], route: "/operations/assignments" },
      { id: "serve", label: "Deliver service", description: "Treatment, consultation and controlled steps", capabilityIds: ["work-items", "checklists"], route: "/operations/work-items" },
      { id: "settle", label: "Settle", description: "Products, payment and receipt", capabilityIds: ["order-capture", "checkout", "receipts"], route: "/operations/pos" },
      { id: "recover", label: "Follow-up", description: "Evidence, incident and service recovery", capabilityIds: ["completion-evidence", "incidents"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "queue", label: "Waiting list", description: "Walk-ins and waiting services", route: "/operations/queue-entries" },
      { id: "resources", label: "Rooms & chairs", description: "Operational service resources", route: "/operations/resource-reservations" },
      { id: "pos", label: "POS", description: "Checkout, retail products and receipts", route: "/operations/pos" },
      { id: "customers", label: "Clients", description: "Customer history and relationship", route: "/commercial/customers" },
      { id: "inventory", label: "Products & consumables", description: "Stock truth and replenishment", route: "/supply-chain/inventory" },
      { id: "people", label: "Team", description: "Rosters, skills and attendance", route: "/people" },
    ],
    boundary: "Operations owns appointment execution and service flow. Commercial owns client truth and offers; Supply Chain owns stock; People owns workforce; Finance owns accounting.",
  }),

  security: profile({
    id: "security",
    eyebrow: "Security Operations",
    title: "Security Control",
    description: "Run posts, patrols, access-related work, incident response, shift handoffs and evidence with accountable escalation.",
    capabilityIds: [
      "operational-runs", "work-schedules", "assignments", "work-items", "checklists",
      "handoffs", "incidents", "incident-triage", "escalations", "completion-evidence",
      "operational-timeline",
    ],
    primaryActions: [
      { id: "patrols", label: "Patrols", route: "/operations/operational-runs" },
      { id: "incidents", label: "Incidents", route: "/operations/incidents" },
      { id: "handoffs", label: "Shift handover", route: "/operations/handoffs" },
    ],
    stages: [
      { id: "post", label: "Post & patrol", description: "Scheduled coverage and patrol runs", capabilityIds: ["work-schedules", "operational-runs", "assignments"], route: "/operations/operational-runs" },
      { id: "observe", label: "Observe", description: "Checks and routine security work", capabilityIds: ["work-items", "checklists"], route: "/operations/checklists" },
      { id: "respond", label: "Respond", description: "Incident triage and accountable action", capabilityIds: ["incidents", "incident-triage"], route: "/operations/incidents" },
      { id: "escalate", label: "Escalate", description: "Escalation and controlled transfer", capabilityIds: ["escalations", "handoffs"], route: "/operations/escalations" },
      { id: "prove", label: "Record", description: "Evidence and immutable timeline", capabilityIds: ["completion-evidence", "operational-timeline"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "schedule", label: "Coverage schedule", description: "Operational post and patrol scheduling", route: "/operations/work-schedules" },
      { id: "checks", label: "Checklists", description: "Opening, patrol and closing controls", route: "/operations/checklists" },
      { id: "timeline", label: "Operational timeline", description: "Chronology of events and response", route: "/operations/operational-timeline" },
      { id: "people", label: "People", description: "Licences, qualifications, rosters and attendance", route: "/people" },
      { id: "documents", label: "Controlled documents", description: "Policies, permits and evidence", route: "/documents" },
      { id: "compliance", label: "Compliance", description: "Risk and compliance authority", route: "/compliance" },
    ],
    boundary: "Operations owns security execution, incidents, escalation and evidence. People owns guard employment/licensing records; Compliance owns enterprise policy and risk authority.",
  }),


  accountingPractice: profile({
    id: "accounting-practice",
    eyebrow: "Accounting Practice Operations",
    title: "Client Work & Close Control",
    description: "Coordinate multi-client accounting work, document requests, review, approvals, deadlines and delivery while each client ledger remains governed inside Finance.",
    capabilityIds: [
      "work-requests", "work-orders", "work-packages", "work-schedules", "assignments",
      "work-items", "checklists", "operational-approvals", "handoffs", "completion-evidence",
      "service-levels", "service-level-breaches", "exceptions-holds",
    ],
    primaryActions: [
      { id: "clients", label: "Client work", route: "/operations/work-items" },
      { id: "schedule", label: "Close & filing calendar", route: "/operations/work-schedules" },
      { id: "approvals", label: "Review & approvals", route: "/operations/operational-approvals" },
    ],
    stages: [
      { id: "intake", label: "Intake", description: "Client request, evidence demand and authorized engagement work", capabilityIds: ["work-requests", "work-orders"], route: "/operations/work-requests" },
      { id: "plan", label: "Plan", description: "Periods, deadlines, work packages and responsibility", capabilityIds: ["work-packages", "work-schedules", "assignments"], route: "/operations/work-packages" },
      { id: "prepare", label: "Prepare", description: "Bookkeeping, reconciliation and statutory tasks", capabilityIds: ["work-items", "checklists"], route: "/operations/work-items" },
      { id: "review", label: "Review", description: "Controlled review, correction and approval", capabilityIds: ["operational-approvals", "exceptions-holds"], route: "/operations/operational-approvals" },
      { id: "deliver", label: "Deliver", description: "Evidence-backed client handoff and deadline closure", capabilityIds: ["handoffs", "completion-evidence", "service-level-breaches"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "finance", label: "Client Finance", description: "Ledgers, reconciliation, VAT, statutory and reporting truth", route: "/finance" },
      { id: "documents", label: "Client Documents", description: "Evidence, source documents and controlled files", route: "/documents" },
      { id: "clients", label: "Client Portfolio", description: "Accounting-firm client relationships and access", route: "/finance/accounting-firm" },
      { id: "requests", label: "Evidence Requests", description: "Outstanding client information and follow-up", route: "/operations/work-requests" },
      { id: "approvals", label: "Review Queue", description: "Controlled review and sign-off", route: "/operations/operational-approvals" },
      { id: "sla", label: "Deadlines", description: "Service commitments and missed deadlines", route: "/operations/service-level-breaches" },
    ],
    boundary: "Operations owns practice workflow, responsibility, review status and delivery evidence. Finance owns each client ledger, tax and statutory accounting; Documents owns source files; Administration owns client access relationships.",
  }),

  agency: profile({
    id: "agency",
    eyebrow: "Agency Operations",
    title: "Client Delivery & Production Control",
    description: "Run briefs, scopes, production, approvals, delivery and client deadlines across creative and marketing work without duplicating project, creative or finance truth.",
    capabilityIds: [
      "work-requests", "work-orders", "work-packages", "work-schedules", "assignments",
      "work-items", "operational-approvals", "handoffs", "completion-evidence",
      "service-levels", "service-level-breaches", "exceptions-holds",
    ],
    primaryActions: [
      { id: "delivery", label: "Active client delivery", route: "/operations/work-items" },
      { id: "production", label: "Creative production", route: "/creative" },
      { id: "approvals", label: "Client approvals", route: "/operations/operational-approvals" },
    ],
    stages: [
      { id: "brief", label: "Brief", description: "Qualified request and authorized client scope", capabilityIds: ["work-requests", "work-orders"], route: "/operations/work-requests" },
      { id: "plan", label: "Plan", description: "Work package, schedule and accountable team", capabilityIds: ["work-packages", "work-schedules", "assignments"], route: "/operations/work-packages" },
      { id: "produce", label: "Produce", description: "Creative, campaign and delivery execution", capabilityIds: ["work-items"], route: "/operations/work-items" },
      { id: "approve", label: "Approve", description: "Internal and client approval gates", capabilityIds: ["operational-approvals", "exceptions-holds"], route: "/operations/operational-approvals" },
      { id: "deliver", label: "Deliver", description: "Final handoff, evidence and SLA closure", capabilityIds: ["handoffs", "completion-evidence", "service-level-breaches"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "creative", label: "Creative Studio", description: "Image, video, music, voice and production tools", route: "/creative" },
      { id: "projects", label: "Projects", description: "Scope, milestones and economics", route: "/projects" },
      { id: "clients", label: "Clients", description: "Commercial relationship and commitments", route: "/commercial/customers" },
      { id: "documents", label: "Documents", description: "Briefs, deliverables and approvals", route: "/documents" },
      { id: "people", label: "Team", description: "Capacity, skills and workforce truth", route: "/people" },
      { id: "finance", label: "Billing & profitability", description: "Invoices, receivables and accounting", route: "/finance" },
    ],
    boundary: "Operations owns accountable delivery flow. Projects owns project structure, Creative owns generated media and production assets, Commercial owns client truth, Documents owns files, People owns workforce and Finance owns accounting.",
  }),

  artistAgency: profile({
    id: "artist-agency",
    eyebrow: "Artist & Entertainment Agency",
    title: "Booking & Show Control",
    description: "Run booking requests, holds, offers, contracts, advancing, travel readiness, show-day execution and settlement handoff around each artist engagement.",
    capabilityIds: [
      "work-requests", "work-orders", "appointment-windows", "work-schedules", "assignments",
      "work-items", "operational-approvals", "handoffs", "checklists", "completion-evidence",
      "incidents", "exceptions-holds",
    ],
    primaryActions: [
      { id: "bookings", label: "Booking pipeline", route: "/operations/work-requests" },
      { id: "schedule", label: "Artist schedule", route: "/operations/work-schedules" },
      { id: "shows", label: "Show execution", route: "/operations/work-items" },
    ],
    stages: [
      { id: "request", label: "Request & hold", description: "Opportunity, date hold and booking request", capabilityIds: ["work-requests", "appointment-windows"], route: "/operations/work-requests" },
      { id: "confirm", label: "Offer & confirm", description: "Approval, contract and confirmed commitment", capabilityIds: ["operational-approvals", "work-orders"], route: "/operations/operational-approvals" },
      { id: "advance", label: "Advance", description: "Travel, venue, production and hospitality readiness", capabilityIds: ["work-schedules", "assignments", "checklists"], route: "/operations/checklists" },
      { id: "show", label: "Show day", description: "Call times, execution and live exceptions", capabilityIds: ["work-items", "incidents"], route: "/operations/work-items" },
      { id: "settle", label: "Settle & close", description: "Completion evidence, handoff and finance settlement input", capabilityIds: ["handoffs", "completion-evidence", "exceptions-holds"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "projects", label: "Bookings & Projects", description: "Engagement scope and project context", route: "/projects" },
      { id: "calendar", label: "Schedule", description: "Artist and team operating schedule", route: "/people/calendar" },
      { id: "documents", label: "Contracts & Riders", description: "Controlled contracts and show documentation", route: "/documents" },
      { id: "clients", label: "Promoters & Clients", description: "Commercial relationship context", route: "/commercial/customers" },
      { id: "travel", label: "Travel readiness", description: "Travel-related operational work and handoffs", route: "/operations/checklists" },
      { id: "finance", label: "Settlement", description: "Invoices, deposits and accounting", route: "/finance" },
    ],
    boundary: "Operations owns booking execution, advancing and show-day accountability. Commercial/Projects own deal and scope truth; Documents owns contracts; People owns workforce/artist identity; Finance owns invoicing, deposits and settlement accounting.",
  }),

  foodProduction: profile({
    id: "food-production",
    eyebrow: "Food Production Operations",
    title: "Production & Quality Control",
    description: "Coordinate production demand, batches, station work, quality, downtime and completion while recipes, ingredients, inventory and costing remain canonical in Supply Chain and Finance.",
    capabilityIds: [
      "work-orders", "operational-runs", "work-centres", "assignments", "work-items",
      "checklists", "quality-checks", "quality-inspections", "resource-downtime",
      "exceptions-holds", "corrective-actions", "completion-evidence",
    ],
    primaryActions: [
      { id: "runs", label: "Production runs", route: "/operations/operational-runs" },
      { id: "quality", label: "Quality control", route: "/operations/quality-checks" },
      { id: "production", label: "Recipes & batches", route: "/supply-chain/production" },
    ],
    stages: [
      { id: "release", label: "Release", description: "Authorized production demand and batch plan", capabilityIds: ["work-orders"], route: "/operations/work-orders" },
      { id: "prepare", label: "Prepare", description: "Station readiness, people and pre-run checks", capabilityIds: ["work-centres", "assignments", "checklists"], route: "/operations/checklists" },
      { id: "run", label: "Produce", description: "Active batches and station execution", capabilityIds: ["operational-runs", "work-items"], route: "/operations/operational-runs" },
      { id: "verify", label: "Verify", description: "Quality, hold, corrective action and downtime", capabilityIds: ["quality-checks", "quality-inspections", "exceptions-holds", "corrective-actions", "resource-downtime"], route: "/operations/quality-checks" },
      { id: "complete", label: "Complete", description: "Evidence-backed production completion", capabilityIds: ["completion-evidence"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "recipes", label: "Recipes", description: "Canonical recipes and ingredient quantities", route: "/supply-chain/production/recipes" },
      { id: "batches", label: "Batches", description: "Production batch records", route: "/supply-chain/production/batches" },
      { id: "prepared", label: "Prepared items", description: "Prepared production outputs", route: "/supply-chain/production/prepared" },
      { id: "usage", label: "Usage & waste", description: "Actual material usage and waste", route: "/supply-chain/production/usage" },
      { id: "inventory", label: "Inventory", description: "Ingredient and finished-stock truth", route: "/supply-chain/inventory" },
      { id: "costing", label: "Costing", description: "Production cost and variance", route: "/supply-chain/production/costing" },
    ],
    boundary: "Operations owns execution, quality and downtime. Supply Chain owns recipes, ingredients, inventory, batch material truth and waste; People owns labour; Finance owns accounting and variance.",
  }),

  carWash: profile({
    id: "car-wash",
    eyebrow: "Car Wash Operations",
    title: "Vehicle Queue & Bay Control",
    description: "Run vehicle intake, service-package selection, queue, bay assignment, wash/detail execution, inspection, checkout and handover from one operating flow.",
    capabilityIds: [
      "work-requests", "queue-entries", "assignments", "resource-reservations", "work-items",
      "checklists", "quality-inspections", "completion-evidence", "order-capture",
      "checkout", "receipts", "incidents",
    ],
    primaryActions: [
      { id: "intake", label: "Vehicle intake", route: "/operations/work-requests" },
      { id: "queue", label: "Live queue", route: "/operations/queue-entries" },
      { id: "checkout", label: "Checkout", route: "/operations/pos" },
    ],
    stages: [
      { id: "intake", label: "Intake", description: "Vehicle, customer and selected service package", capabilityIds: ["work-requests"], route: "/operations/work-requests" },
      { id: "queue", label: "Queue & bay", description: "Waiting sequence, bay and team assignment", capabilityIds: ["queue-entries", "resource-reservations", "assignments"], route: "/operations/queue-entries" },
      { id: "service", label: "Wash / detail", description: "Active service work and required steps", capabilityIds: ["work-items", "checklists"], route: "/operations/work-items" },
      { id: "inspect", label: "Inspect", description: "Final quality and exception resolution", capabilityIds: ["quality-inspections", "incidents"], route: "/operations/quality-inspections" },
      { id: "settle", label: "Checkout & handover", description: "Payment, receipt and completion evidence", capabilityIds: ["order-capture", "checkout", "receipts", "completion-evidence"], route: "/operations/pos" },
    ],
    tools: [
      { id: "bays", label: "Bays", description: "Reserve and control wash/detail capacity", route: "/operations/resource-reservations" },
      { id: "quality", label: "Quality", description: "Final vehicle inspection", route: "/operations/quality-inspections" },
      { id: "pos", label: "POS", description: "Service package checkout and receipts", route: "/operations/pos" },
      { id: "customers", label: "Customers", description: "Customer and loyalty context", route: "/commercial/customers" },
      { id: "inventory", label: "Consumables", description: "Chemicals, towels and consumable stock", route: "/supply-chain/inventory" },
      { id: "people", label: "Team", description: "Rosters and workforce truth", route: "/people" },
    ],
    boundary: "Operations owns vehicle flow, queue, bay assignment, service execution, inspection and handover. Commercial owns customer/loyalty truth; Supply Chain owns consumables; People owns workforce; Finance owns accounting.",
  }),



  veterinary: profile({
    id: "veterinary",
    eyebrow: "Veterinary Operations",
    title: "Veterinary & Animal Care Flow",
    description: "Coordinate appointments, intake, treatment work, rooms, equipment, handoffs, discharge readiness and operational evidence without making Operations the clinical-record authority.",
    capabilityIds: [
      "appointment-windows", "queue-entries", "work-items", "work-schedules", "assignments",
      "resources", "resource-reservations", "equipment", "checklists", "completion-evidence",
      "incidents", "quality-checks", "handoffs",
    ],
    primaryActions: [
      { id: "queue", label: "Patient queue", route: "/operations/queue-entries" },
      { id: "work", label: "Animal-care work", route: "/operations/work-items" },
      { id: "appointments", label: "Appointments", route: "/operations/appointment-windows" },
    ],
    stages: [
      { id: "book", label: "Book", description: "Appointment and service windows", capabilityIds: ["appointment-windows", "work-schedules"], route: "/operations/appointment-windows" },
      { id: "intake", label: "Intake", description: "Arrival, triage queue and room readiness", capabilityIds: ["queue-entries", "resources", "resource-reservations"], route: "/operations/queue-entries" },
      { id: "care", label: "Care", description: "Assigned treatment and animal-care work", capabilityIds: ["work-items", "assignments", "checklists"], route: "/operations/work-items" },
      { id: "handoff", label: "Handoff", description: "Discharge, transfer and completion evidence", capabilityIds: ["handoffs", "completion-evidence", "quality-checks"], route: "/operations/handoffs" },
      { id: "recover", label: "Recover", description: "Incidents and operational exceptions", capabilityIds: ["incidents"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "rooms", label: "Rooms & resources", description: "Consult rooms, kennels and operational spaces", route: "/operations/resources" },
      { id: "equipment", label: "Equipment", description: "Operational equipment availability and readiness", route: "/operations/equipment" },
      { id: "quality", label: "Quality checks", description: "Operational completion and safety checks", route: "/operations/quality-checks" },
      { id: "people", label: "People", description: "Staff identity, rosters and qualifications", route: "/people" },
      { id: "finance", label: "Finance", description: "Billing, accounting and settlement authority", route: "/finance" },
    ],
    boundary: "Operations owns appointment flow, rooms, execution, handoffs and operational evidence. Veterinary clinical records, diagnosis, prescriptions and medical decisions remain with the clinical record authority; People owns workforce eligibility and Finance owns accounting.",
  }),

  fitnessRecreation: profile({
    id: "fitness-recreation",
    eyebrow: "Fitness & Recreation Operations",
    title: "Fitness, Gym & Recreation Control",
    description: "Coordinate classes, appointments, trainer work, spaces, equipment, check-ins and service exceptions while memberships and customer entitlements remain commercially authoritative elsewhere.",
    capabilityIds: [
      "appointment-windows", "queue-entries", "work-items", "work-schedules", "assignments",
      "resources", "resource-reservations", "equipment", "checklists", "incidents",
      "service-levels", "completion-evidence",
    ],
    primaryActions: [
      { id: "schedule", label: "Classes & sessions", route: "/operations/work-schedules" },
      { id: "checkin", label: "Check-in queue", route: "/operations/queue-entries" },
      { id: "work", label: "Trainer work", route: "/operations/work-items" },
    ],
    stages: [
      { id: "book", label: "Book", description: "Classes, sessions and appointment windows", capabilityIds: ["appointment-windows", "work-schedules"], route: "/operations/work-schedules" },
      { id: "checkin", label: "Check in", description: "Arrival and service queue", capabilityIds: ["queue-entries"], route: "/operations/queue-entries" },
      { id: "deliver", label: "Deliver", description: "Trainer, coach and facility work", capabilityIds: ["work-items", "assignments"], route: "/operations/work-items" },
      { id: "resources", label: "Resources", description: "Studios, courts, rooms and equipment", capabilityIds: ["resources", "resource-reservations", "equipment"], route: "/operations/resources" },
      { id: "recover", label: "Recover", description: "Safety incidents and service exceptions", capabilityIds: ["incidents", "service-levels", "completion-evidence"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "spaces", label: "Spaces & courts", description: "Operational resource availability", route: "/operations/resources" },
      { id: "equipment", label: "Equipment", description: "Fitness and recreation equipment readiness", route: "/operations/equipment" },
      { id: "commercial", label: "Memberships & customers", description: "Membership and entitlement truth", route: "/commercial" },
      { id: "people", label: "People", description: "Trainer rosters and qualifications", route: "/people" },
    ],
    boundary: "Operations owns session execution, queues, spaces, equipment and incidents. Commercial owns memberships, subscriptions and customer entitlements; People owns trainers and qualifications; Finance owns billing and accounting.",
  }),

  childcare: profile({
    id: "childcare",
    eyebrow: "Childcare Operations",
    title: "Childcare & Daycare Control",
    description: "Coordinate arrival, room work, supervision, activities, handoffs, safety checks and incidents with strict operational accountability while child records and safeguarding authority remain governed outside the generic Operations layer.",
    capabilityIds: [
      "queue-entries", "work-items", "work-schedules", "assignments", "resources",
      "resource-reservations", "checklists", "quality-inspections", "completion-evidence",
      "handoffs", "incidents", "service-levels",
    ],
    primaryActions: [
      { id: "day", label: "Day flow", route: "/operations/queue-entries" },
      { id: "rooms", label: "Rooms & activities", route: "/operations/work-items" },
      { id: "handoff", label: "Pickup handoff", route: "/operations/handoffs" },
    ],
    stages: [
      { id: "arrival", label: "Arrival", description: "Check-in and room intake", capabilityIds: ["queue-entries", "handoffs"], route: "/operations/queue-entries" },
      { id: "plan", label: "Plan", description: "Room activities and daily work", capabilityIds: ["work-schedules", "assignments", "resource-reservations"], route: "/operations/work-schedules" },
      { id: "supervise", label: "Supervise", description: "Assigned room, activity and care work", capabilityIds: ["work-items", "checklists"], route: "/operations/work-items" },
      { id: "pickup", label: "Pickup", description: "Controlled end-of-day handoff", capabilityIds: ["handoffs", "completion-evidence"], route: "/operations/handoffs" },
      { id: "safety", label: "Safety", description: "Inspection and incident control", capabilityIds: ["quality-inspections", "incidents", "service-levels"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "rooms", label: "Rooms & capacity", description: "Operational rooms and resource capacity", route: "/operations/resources" },
      { id: "checks", label: "Safety checks", description: "Configured operational checks and evidence", route: "/operations/quality-inspections" },
      { id: "people", label: "People", description: "Staff rosters, identity and qualifications", route: "/people" },
      { id: "documents", label: "Documents", description: "Governed records and evidence", route: "/documents" },
    ],
    boundary: "Operations owns daily execution, rooms, activities, handoffs and operational safety evidence. Child master records, safeguarding decisions, consent and regulated education/health records remain in their owning domain; People owns staff authority.",
  }),

  cleaningServices: profile({
    id: "cleaning-services",
    eyebrow: "Cleaning Operations",
    title: "Cleaning & Janitorial Service Control",
    description: "Run recurring and ad-hoc cleaning work, routes, assignments, checklists, supply-aware execution, inspections, proof of completion and SLA recovery across customer or internal sites.",
    capabilityIds: [
      "work-requests", "work-orders", "work-items", "recurring-work", "work-schedules",
      "assignments", "routing", "checklists", "completion-evidence", "quality-inspections",
      "incidents", "service-levels", "service-level-breaches",
    ],
    primaryActions: [
      { id: "work", label: "Cleaning work", route: "/operations/work-items" },
      { id: "schedule", label: "Cleaning schedule", route: "/operations/work-schedules" },
      { id: "quality", label: "Inspection & proof", route: "/operations/quality-inspections" },
    ],
    stages: [
      { id: "intake", label: "Request", description: "Recurring or ad-hoc cleaning demand", capabilityIds: ["work-requests", "recurring-work"], route: "/operations/work-requests" },
      { id: "plan", label: "Plan", description: "Schedule, route and assign cleaners", capabilityIds: ["work-orders", "work-schedules", "assignments", "routing"], route: "/operations/work-schedules" },
      { id: "clean", label: "Clean", description: "Execute task and checklist work", capabilityIds: ["work-items", "checklists"], route: "/operations/work-items" },
      { id: "verify", label: "Verify", description: "Inspection and completion evidence", capabilityIds: ["quality-inspections", "completion-evidence"], route: "/operations/quality-inspections" },
      { id: "recover", label: "Recover", description: "Incidents, complaints and SLA breaches", capabilityIds: ["incidents", "service-levels", "service-level-breaches"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "dispatch", label: "Dispatch", description: "Assigned mobile and site work", route: "/operations/dispatch" },
      { id: "evidence", label: "Completion evidence", description: "Photos, sign-off and proof", route: "/operations/completion-evidence" },
      { id: "inventory", label: "Cleaning supplies", description: "Canonical stock position", route: "/supply-chain/inventory" },
      { id: "people", label: "People", description: "Cleaner rosters and qualifications", route: "/people" },
    ],
    boundary: "Operations owns cleaning execution, routing, checklists, inspection, evidence and SLA recovery. Supply Chain owns stock quantities; Commercial owns customer/contract truth; People owns workforce; Finance owns billing and accounting.",
  }),

  propertyManagement: profile({
    id: "property-management",
    eyebrow: "Property Operations",
    title: "Property & Facility Service Control",
    description: "Run tenant and property requests, preventive work, inspections, contractor handoffs, service levels and evidence without duplicating the property, lease or finance masters.",
    capabilityIds: [
      "work-requests", "work-orders", "work-items", "work-schedules", "assignments",
      "resource-reservations", "quality-inspections", "completion-evidence", "incidents",
      "exceptions-holds", "service-levels", "service-level-breaches", "handoffs",
    ],
    primaryActions: [
      { id: "requests", label: "Property requests", route: "/operations/work-requests" },
      { id: "work", label: "Maintenance work", route: "/operations/work-orders" },
      { id: "inspections", label: "Inspections", route: "/operations/quality-inspections" },
    ],
    stages: [
      { id: "intake", label: "Request", description: "Tenant, owner or property demand", capabilityIds: ["work-requests", "service-levels"], route: "/operations/work-requests" },
      { id: "plan", label: "Plan", description: "Authorize, schedule and assign work", capabilityIds: ["work-orders", "work-schedules", "assignments"], route: "/operations/work-orders" },
      { id: "execute", label: "Execute", description: "Perform maintenance and contractor work", capabilityIds: ["work-items", "resource-reservations"], route: "/operations/work-items" },
      { id: "inspect", label: "Inspect", description: "Inspection, evidence and acceptance", capabilityIds: ["quality-inspections", "completion-evidence"], route: "/operations/quality-inspections" },
      { id: "recover", label: "Recover", description: "Incidents, breaches and handoffs", capabilityIds: ["incidents", "exceptions-holds", "service-level-breaches", "handoffs"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "schedule", label: "Maintenance schedule", description: "Planned and recurring work", route: "/operations/work-schedules" },
      { id: "resources", label: "Property resources", description: "Spaces, equipment and shared capacity", route: "/operations/resources" },
      { id: "evidence", label: "Completion evidence", description: "Photos, sign-off and completion proof", route: "/operations/completion-evidence" },
      { id: "commercial", label: "Customers & contracts", description: "Customer and commercial relationship truth", route: "/commercial" },
      { id: "finance", label: "Finance", description: "Billing, deposits and accounting", route: "/finance" },
      { id: "people", label: "People", description: "Staff and contractor workforce authority", route: "/people" },
    ],
    boundary: "Operations owns request-to-completion execution and evidence. Commercial owns customer/contract truth; Administration or the property master owns locations/assets; People owns workforce authority; Finance owns accounting and billing.",
  }),

  agriculture: profile({
    id: "agriculture",
    eyebrow: "Agriculture Operations",
    title: "Farm & Production Cycle Control",
    description: "Coordinate field, crop, livestock and farm-service work as governed operational cycles: plan work, reserve equipment, execute rounds, inspect quality and retain evidence while inventory and costing remain canonical elsewhere.",
    capabilityIds: [
      "operational-runs", "work-orders", "work-items", "work-schedules", "assignments",
      "resources", "resource-reservations", "equipment", "checklists", "quality-inspections",
      "completion-evidence", "incidents", "exceptions-holds", "corrective-actions",
    ],
    primaryActions: [
      { id: "runs", label: "Farm cycles", route: "/operations/operational-runs" },
      { id: "work", label: "Field work", route: "/operations/work-items" },
      { id: "quality", label: "Quality & inspection", route: "/operations/quality-inspections" },
    ],
    stages: [
      { id: "plan", label: "Plan", description: "Seasonal, daily and recurring work", capabilityIds: ["work-orders", "work-schedules"], route: "/operations/work-schedules" },
      { id: "prepare", label: "Prepare", description: "Assign people, equipment and capacity", capabilityIds: ["assignments", "resources", "resource-reservations", "equipment"], route: "/operations/assignments" },
      { id: "execute", label: "Execute", description: "Field rounds, batches and work items", capabilityIds: ["operational-runs", "work-items", "checklists"], route: "/operations/operational-runs" },
      { id: "inspect", label: "Inspect", description: "Quality, yield and evidence checks", capabilityIds: ["quality-inspections", "completion-evidence"], route: "/operations/quality-inspections" },
      { id: "recover", label: "Recover", description: "Exceptions, incidents and corrective action", capabilityIds: ["incidents", "exceptions-holds", "corrective-actions"], route: "/operations/incidents" },
    ],
    tools: [
      { id: "equipment", label: "Equipment", description: "Operational machinery and availability", route: "/operations/equipment" },
      { id: "inventory", label: "Inventory", description: "Seed, feed, chemicals, packaging and harvested stock", route: "/supply-chain/inventory" },
      { id: "production", label: "Production", description: "Batch and material movement where applicable", route: "/supply-chain/production" },
      { id: "quality", label: "Quality inspections", description: "Configured acceptance checks", route: "/operations/quality-inspections" },
      { id: "evidence", label: "Field evidence", description: "Completion and inspection proof", route: "/operations/completion-evidence" },
      { id: "people", label: "Workforce", description: "Rosters, qualifications and attendance authority", route: "/people" },
    ],
    boundary: "Operations owns farm-work execution, resource coordination, inspection and evidence. Supply Chain owns stock and material truth; People owns workforce authority; Finance owns costing/accounting; specialist agronomy or veterinary records remain with their owning domain.",
  }),

  warehouseDistribution: profile({
    id: "warehouse-distribution",
    eyebrow: "Warehouse & Distribution Operations",
    title: "Warehouse Flow Control",
    description: "Coordinate receiving, putaway, replenishment, picking, packing, staging, dispatch and exception recovery while Supply Chain remains authoritative for inventory quantities and warehouse master data.",
    capabilityIds: [
      "queue-entries", "work-orders", "work-items", "work-schedules", "assignments",
      "handoffs", "resource-reservations", "quality-checks", "completion-evidence",
      "incidents", "exceptions-holds", "throughput", "backlog",
    ],
    primaryActions: [
      { id: "queue", label: "Warehouse queue", route: "/operations/queue-entries" },
      { id: "work", label: "Active warehouse work", route: "/operations/work-items" },
      { id: "inventory", label: "Inventory", route: "/supply-chain/inventory" },
    ],
    stages: [
      { id: "receive", label: "Receive", description: "Inbound work and receiving queue", capabilityIds: ["queue-entries", "work-orders"], route: "/operations/queue-entries" },
      { id: "move", label: "Putaway & replenish", description: "Assigned internal movement work", capabilityIds: ["assignments", "work-items", "resource-reservations"], route: "/operations/work-items" },
      { id: "pick", label: "Pick & pack", description: "Controlled fulfillment execution", capabilityIds: ["work-items", "quality-checks"], route: "/operations/work-items" },
      { id: "handoff", label: "Stage & dispatch", description: "Custody and dispatch handoff", capabilityIds: ["handoffs", "completion-evidence"], route: "/operations/handoffs" },
      { id: "recover", label: "Exceptions", description: "Shortage, damage, delay and operational holds", capabilityIds: ["incidents", "exceptions-holds"], route: "/operations/exceptions-holds" },
    ],
    tools: [
      { id: "warehouses", label: "Warehouses", description: "Canonical warehouse master and zones", route: "/supply-chain/warehouse" },
      { id: "inventory", label: "Stock position", description: "Inventory quantity and valuation truth", route: "/supply-chain/inventory" },
      { id: "receiving", label: "Receiving", description: "Procurement goods receipt", route: "/supply-chain/procurement/receiving" },
      { id: "dispatch", label: "Dispatch", description: "Outbound work coordination", route: "/operations/dispatch" },
      { id: "quality", label: "Quality", description: "Damage and completion checks", route: "/operations/quality-checks" },
      { id: "performance", label: "Performance", description: "Throughput and backlog visibility", route: "/operations/throughput" },
    ],
    boundary: "Operations owns warehouse execution queues, assignments, handoffs and exceptions. Supply Chain owns warehouse masters, stock quantities, procurement and fulfillment documents; People owns workforce; Finance owns inventory accounting.",
  }),

  generalOperations: profile({
    id: "general-operations",
    eyebrow: "Adaptive Operations",
    title: "Business Operations Control",
    description: "A complete industry-neutral operating model for organizations without a dedicated vertical pack yet: intake work, schedule it, assign responsibility, execute, inspect, recover exceptions and retain evidence.",
    capabilityIds: [
      "work-requests", "work-orders", "work-items", "work-schedules", "appointment-windows",
      "queue-entries", "dispatch", "assignments", "handoffs", "resources", "resource-reservations",
      "checklists", "completion-evidence", "incidents", "exceptions-holds", "quality-checks",
      "service-levels", "operational-timeline",
    ],
    primaryActions: [
      { id: "work", label: "Active work", route: "/operations/work-items" },
      { id: "schedule", label: "Schedule", route: "/operations/work-schedules" },
      { id: "exceptions", label: "Exceptions", route: "/operations/exceptions-holds" },
    ],
    stages: [
      { id: "intake", label: "Intake", description: "Requests and authorized work", capabilityIds: ["work-requests", "work-orders"], route: "/operations/work-requests" },
      { id: "plan", label: "Plan", description: "Schedule, queue and reserve capacity", capabilityIds: ["work-schedules", "appointment-windows", "queue-entries", "resource-reservations"], route: "/operations/work-schedules" },
      { id: "execute", label: "Execute", description: "Dispatch, assign and complete work", capabilityIds: ["dispatch", "assignments", "work-items"], route: "/operations/work-items" },
      { id: "control", label: "Control", description: "Checklists, quality and exceptions", capabilityIds: ["checklists", "quality-checks", "exceptions-holds", "incidents"], route: "/operations/checklists" },
      { id: "close", label: "Close", description: "Evidence, handoff and operational history", capabilityIds: ["completion-evidence", "handoffs", "operational-timeline"], route: "/operations/completion-evidence" },
    ],
    tools: [
      { id: "requests", label: "Requests", description: "New operational demand", route: "/operations/work-requests" },
      { id: "orders", label: "Work orders", description: "Authorized accountable work", route: "/operations/work-orders" },
      { id: "resources", label: "Resources", description: "Spaces, devices, equipment and capacity", route: "/operations/resources" },
      { id: "quality", label: "Quality", description: "Checks and inspections", route: "/operations/quality-checks" },
      { id: "incidents", label: "Incidents", description: "Disruption and recovery", route: "/operations/incidents" },
      { id: "timeline", label: "Timeline", description: "Immutable operating chronology", route: "/operations/operational-timeline" },
    ],
    boundary: "This adaptive pack only owns operational execution. Domain-specific master data continues to belong to the canonical Avantiqo domain that owns it.",
  }),

});

const INDUSTRY_PROFILE_ALIASES = Object.freeze({
  "field-service": "fieldService",
  cleaning: "fieldService",
  "commercial-cleaning": "fieldService",
  "residential-cleaning": "fieldService",
  hvac: "fieldService",
  "air-conditioning": "fieldService",
  "aircon-service": "fieldService",
  inspection: "fieldService",
  "inspection-service": "fieldService",
  "equipment-service": "fieldService",
  "appliance-service": "fieldService",
  "repair-service": "fieldService",
  "mobile-service": "fieldService",
  "technician-service": "fieldService",
  "maintenance-service": "fieldService",
  "installation-service": "fieldService",

  education: "education",
  school: "education",
  academy: "education",
  college: "education",
  university: "education",
  kindergarten: "education",
  "nursery-school": "education",
  "training-centre": "education",
  "training-center": "education",
  "learning-centre": "education",
  "learning-center": "education",

  automotive: "automotive",
  mechanic: "automotive",
  garage: "automotive",
  workshop: "automotive",
  "auto-repair": "automotive",
  "car-repair": "automotive",
  "vehicle-service": "automotive",
  "auto-service": "automotive",
  "motorcycle-repair": "automotive",
  "body-shop": "automotive",
  "service-centre": "automotive",
  "service-center": "automotive",

  logistics: "logistics",
  transport: "logistics",
  transportation: "logistics",
  delivery: "logistics",
  courier: "logistics",
  freight: "logistics",
  shipping: "logistics",
  "last-mile": "logistics",
  haulage: "logistics",

  facilities: "facilities",
  "facility-management": "facilities",
  "facility-services": "facilities",
  maintenance: "facilities",
  fm: "facilities",
  "plant-maintenance": "facilities",
  "building-services": "facilities",

  "professional-services": "professionalServices",
  consulting: "professionalServices",
  consultancy: "professionalServices",
  legal: "professionalServices",
  "law-firm": "professionalServices",
  advisory: "professionalServices",
  architecture: "professionalServices",
  "design-firm": "professionalServices",
  "engineering-consultancy": "professionalServices",

  rental: "rentalFleet",
  "car-rental": "rentalFleet",
  "vehicle-rental": "rentalFleet",
  "equipment-rental": "rentalFleet",
  "bike-rental": "rentalFleet",
  "marine-rental": "rentalFleet",
  fleet: "rentalFleet",
  "fleet-management": "rentalFleet",
  "vehicle-fleet": "rentalFleet",
  "equipment-hire": "rentalFleet",

  salon: "salonSpa",
  spa: "salonSpa",
  beauty: "salonSpa",
  wellness: "salonSpa",
  "hair-salon": "salonSpa",
  "nail-salon": "salonSpa",
  massage: "salonSpa",
  barber: "salonSpa",
  barbershop: "salonSpa",
  "aesthetic-clinic": "salonSpa",
  "wellness-centre": "salonSpa",
  "wellness-center": "salonSpa",

  security: "security",
  guarding: "security",
  "security-services": "security",
  "security-company": "security",
  "guard-service": "security",
  patrol: "security",
  "manned-guarding": "security",
  "loss-prevention": "security",

  entertainment: "venue",
  shop: "retail",
  store: "retail",
  boutique: "retail",
  supermarket: "retail",
  hospital: "healthcare",
  clinic: "healthcare",
  medical: "healthcare",
  dental: "healthcare",
  contractor: "construction",
  engineering: "construction",
  building: "construction",
  manufacturer: "manufacturing",
  factory: "manufacturing",
  fabrication: "manufacturing",
  "assembly-line": "manufacturing",
  "discrete-manufacturing": "manufacturing",
  "process-manufacturing": "manufacturing",
  nightclub: "venue",
  "event-venue": "venue",

  "accounting-practice": "accountingPractice",
  "accounting-firm": "accountingPractice",
  "accounting-firms": "accountingPractice",
  bookkeeping: "accountingPractice",
  bookkeeper: "accountingPractice",
  "tax-practice": "accountingPractice",
  "tax-firm": "accountingPractice",
  "audit-firm": "accountingPractice",
  accountancy: "accountingPractice",

  agency: "agency",
  "creative-agency": "agency",
  "marketing-agency": "agency",
  "digital-agency": "agency",
  "production-company": "agency",
  "media-agency": "agency",
  "advertising-agency": "agency",
  "design-agency": "agency",

  "artist-agency": "artistAgency",
  "booking-agency": "artistAgency",
  "talent-agency": "artistAgency",
  "music-agency": "artistAgency",
  "artist-management": "artistAgency",
  "cole-ley": "artistAgency",

  "food-production": "foodProduction",
  "central-kitchen": "foodProduction",
  commissary: "foodProduction",
  bakery: "foodProduction",
  "food-manufacturing": "foodProduction",
  "food-manufacturer": "foodProduction",
  "food-factory": "foodProduction",
  "catering-production": "foodProduction",

  "car-wash": "carWash",
  carwash: "carWash",
  "auto-wash": "carWash",
  "vehicle-wash": "carWash",
  detailing: "carWash",
  "auto-detailing": "carWash",
  "car-detailing": "carWash",
  "vehicle-detailing": "carWash",

  veterinary: "veterinary",
  vet: "veterinary",
  "vet-clinic": "veterinary",
  "veterinary-clinic": "veterinary",
  "pet-clinic": "veterinary",
  "animal-clinic": "veterinary",
  "animal-hospital": "veterinary",
  "animal-care": "veterinary",
  "pet-care": "veterinary",
  gym: "fitnessRecreation",
  fitness: "fitnessRecreation",
  "fitness-center": "fitnessRecreation",
  "fitness-centre": "fitnessRecreation",
  "health-club": "fitnessRecreation",
  "sports-center": "fitnessRecreation",
  "sports-centre": "fitnessRecreation",
  club: "fitnessRecreation",
  "sports-club": "fitnessRecreation",
  recreation: "fitnessRecreation",
  "recreation-center": "fitnessRecreation",
  "recreation-centre": "fitnessRecreation",
  childcare: "childcare",
  daycare: "childcare",
  "day-care": "childcare",
  preschool: "childcare",
  creche: "childcare",
  "child-care": "childcare",
  "early-childhood": "childcare",
  "early-childhood-center": "childcare",
  "early-childhood-centre": "childcare",
  cleaning: "fieldService",
  "residential-cleaning": "fieldService",
  "cleaning-services": "cleaningServices",
  "cleaning-company": "cleaningServices",
  "contract-cleaning": "cleaningServices",
  "housekeeping-services": "cleaningServices",
  janitorial: "cleaningServices",
  "janitorial-services": "cleaningServices",
  housekeeping: "cleaningServices",
  "commercial-cleaning": "fieldService",
  "facility-cleaning": "cleaningServices",
  "property-management": "propertyManagement",
  "property-manager": "propertyManagement",
  "property-services": "propertyManagement",
  property: "propertyManagement",
  "building-management": "propertyManagement",
  condominium: "propertyManagement",
  "condo-management": "propertyManagement",
  "strata-management": "propertyManagement",
  "estate-management": "propertyManagement",
  "commercial-property": "propertyManagement",
  "residential-property": "propertyManagement",

  agriculture: "agriculture",
  farm: "agriculture",
  farming: "agriculture",
  horticulture: "agriculture",
  plantation: "agriculture",
  livestock: "agriculture",
  aquaculture: "agriculture",
  "agri-business": "agriculture",
  agribusiness: "agriculture",

  warehouse: "warehouseDistribution",
  warehousing: "warehouseDistribution",
  "warehouse-distribution": "warehouseDistribution",
  distribution: "warehouseDistribution",
  "distribution-center": "warehouseDistribution",
  "distribution-centre": "warehouseDistribution",
  fulfillment: "warehouseDistribution",
  fulfilment: "warehouseDistribution",
  "fulfillment-center": "warehouseDistribution",
  "fulfilment-centre": "warehouseDistribution",
  "3pl": "warehouseDistribution",
  "third-party-logistics": "warehouseDistribution",
});

export function getOperationsIndustryProfile(id) {
  const target = String(id || "").trim();
  if (!target) return null;
  const aliasKey = target.toLowerCase().replace(/_/g, "-");
  const mappedKey = INDUSTRY_PROFILE_ALIASES[aliasKey];
  return (mappedKey && OPERATIONS_INDUSTRY_PROFILES[mappedKey])
    || OPERATIONS_INDUSTRY_PROFILES[target]
    || Object.values(OPERATIONS_INDUSTRY_PROFILES).find((profileItem) => profileItem.id === target)
    || null;
}

export default OPERATIONS_INDUSTRY_PROFILES;
