const PestControlOperationsProfile = Object.freeze({
  id: "pest-control",
  eyebrow: "Pest Control",
  title: "Pest Control",
  description:
    "Run recurring and on-demand pest service from one operating view: protect today’s commitments, assign the right technician, perform the treatment, govern monitoring points, understand repeat site pressure, capture evidence and resolve follow-up before the customer has to chase.",
  capabilityIds: Object.freeze([
    "work-orders",
    "appointment-windows",
    "dispatch",
    "assignments",
    "queue-entries",
    "work-items",
    "equipment",
    "activities",
    "completion-evidence",
    "checklists",
    "quality-checks",
    "incidents",
    "exceptions-holds",
    "escalations",
    "corrective-actions",
  ]),
  metricCards: Object.freeze([
    Object.freeze({ key: "attention", label: "Attention", detail: "Visits needing a human decision now", attention: true }),
    Object.freeze({ key: "scheduled_today", label: "Scheduled today", detail: "Visits already in today’s service plan" }),
    Object.freeze({ key: "overdue", label: "Overdue", detail: "Past-due customer commitments", attention: true }),
    Object.freeze({ key: "unassigned", label: "Unassigned", detail: "Service without accountable ownership", attention: true }),
    Object.freeze({ key: "high_priority", label: "Priority", detail: "High or critical service work", attention: true }),
    Object.freeze({ key: "completed_today", label: "Completed today", detail: "Evidence-backed service completed today" }),
  ]),
  primaryActions: Object.freeze([
    Object.freeze({ id: "dispatch", label: "Today’s dispatch", route: "/operations/dispatch" }),
    Object.freeze({ id: "technician", label: "Technician execution", route: "/operations/field-service/technician" }),
    Object.freeze({ id: "treatments", label: "Treatment register", route: "/operations/field-service/treatments" }),
    Object.freeze({ id: "monitoring-points", label: "Monitoring points", route: "/operations/field-service/monitoring-points" }),
    Object.freeze({ id: "site-intelligence", label: "Site intelligence", route: "/operations/field-service/site-intelligence" }),
    Object.freeze({ id: "plans", label: "Service plans", route: "/operations/field-service/service-plans" }),
  ]),
  stages: Object.freeze([
    Object.freeze({
      id: "plan",
      label: "Plan visits",
      description: "Committed service and customer time windows",
      capabilityIds: Object.freeze(["work-orders", "appointment-windows"]),
      route: "/operations/work-orders",
    }),
    Object.freeze({
      id: "route",
      label: "Route & assign",
      description: "Put the right technician on the right work",
      capabilityIds: Object.freeze(["dispatch", "assignments", "queue-entries"]),
      route: "/operations/dispatch",
    }),
    Object.freeze({
      id: "service",
      label: "Service on site",
      description: "Protocol-driven inspection, pest findings, treatment and technician execution",
      capabilityIds: Object.freeze(["work-items", "checklists"]),
      route: "/operations/field-service/technician",
    }),
    Object.freeze({
      id: "monitor",
      label: "Control monitoring",
      description: "Govern bait stations, traps, ILTs and termite points, their check cadence and append-only field checks",
      capabilityIds: Object.freeze(["equipment", "activities"]),
      route: "/operations/field-service/monitoring-points",
    }),
    Object.freeze({
      id: "intelligence",
      label: "Understand the site",
      description: "Recurring pest pressure, repeat areas, monitoring history and next-visit context",
      capabilityIds: Object.freeze(["equipment", "activities", "quality-checks"]),
      route: "/operations/field-service/site-intelligence",
    }),
    Object.freeze({
      id: "evidence",
      label: "Prove completion",
      description: "Evidence, quality checks and customer-safe proof",
      capabilityIds: Object.freeze(["completion-evidence", "quality-checks"]),
      route: "/operations/completion-evidence",
    }),
    Object.freeze({
      id: "follow-up",
      label: "Resolve follow-up",
      description: "Callbacks, exceptions and corrective work",
      capabilityIds: Object.freeze(["exceptions-holds", "incidents", "escalations", "corrective-actions"]),
      route: "/operations/exceptions-holds",
    }),
  ]),
  tools: Object.freeze([
    Object.freeze({ id: "technician", label: "Technician workspace", description: "On-site protocol, proof and controlled completion", route: "/operations/field-service/technician" }),
    Object.freeze({ id: "treatments", label: "Treatment register", description: "Pest findings, product applications, method, treatment area and stock preflight", route: "/operations/field-service/treatments" }),
    Object.freeze({ id: "monitoring-points", label: "Monitoring points", description: "Bait stations, traps, ILTs, termite points, check cadence and governed field checks", route: "/operations/field-service/monitoring-points" }),
    Object.freeze({ id: "site-intelligence", label: "Site intelligence", description: "Repeat pest pressure, area patterns, monitoring history and next-visit brief", route: "/operations/field-service/site-intelligence" }),
    Object.freeze({ id: "plans", label: "Service plans", description: "Recurring customer commitments and cadence", route: "/operations/field-service/service-plans" }),
    Object.freeze({ id: "templates", label: "Treatment protocols", description: "Inspection, treatment and evidence protocols", route: "/operations/field-service/execution-templates" }),
    Object.freeze({ id: "reports", label: "Service reports", description: "Completed visits and customer-safe evidence", route: "/operations/field-service/service-reports" }),
    Object.freeze({ id: "evidence", label: "Completion evidence", description: "Photos, proof and sign-off", route: "/operations/completion-evidence" }),
    Object.freeze({ id: "customers", label: "Customers", description: "Customer and site context", route: "/commercial/customers" }),
    Object.freeze({ id: "materials", label: "Materials & stock", description: "Products, materials and availability", route: "/supply-chain/inventory" }),
  ]),
  guidance: Object.freeze([
    "Protect overdue, unassigned and imminent commitments before touching healthy work.",
    "Use routing and matching as decision support; accountable dispatch authority stays visible to the human operator.",
    "Record pest findings and treatment applications against the exact visit; Supply Chain stays authoritative for products and stock.",
    "Identify each installed monitoring point by governed code or barcode and record every field check against that exact point instead of replacing prior history.",
    "Before repeat visits, review monitoring cadence and site intelligence for recurring pest pressure, repeat areas and device history instead of relying on memory.",
    "Treat a visit as operationally complete only when the required protocol, treatment, proof and follow-up state are clear.",
  ]),
  boundary:
    "Operations owns service execution, dispatch, responsibility, operational monitoring equipment, monitoring-check evidence, derived site intelligence and completion evidence. Commercial owns the customer and customer-site master; People owns workforce authority; Supply Chain owns materials and consumable inventory; Finance owns billing and accounting. Monitoring and intelligence reuse governed cross-domain identifiers and never create parallel customer, asset or inventory authority.",
});

export default PestControlOperationsProfile;
