import PublicSiteHeader from "@/components/public/PublicSiteHeader";
import PublicArtStage from "@/components/public/PublicArtStage";

const WORLDS = [
  ["RUN", "Business OS", "/business", "Run finance, operations, people, supply chain and sales from one connected business workspace.", "/bg-hero-control.jpg", null],
  ["THINK", "Intelligence", "/intelligence-platform", "Ask questions, research decisions, use agents and act on approved work.", "/branding/avantiqo-intelligence-core-hero.webp", "intelligence"],
  ["CREATE", "Creative Studios", "/creative-studios", "Image, video and music production from objective to finished work.", "/art/creative-image.jpg", null],
  ["SPEAK", "Voice", "/voice", "Speech recognition, realtime voice, TTS, production and telephony.", "/art/creative-music.jpg", "voice"],
  ["BUILD", "Code", "/code", "Understand, plan, build, test, integrate and verify software work.", "/art/developer-work.jpg", "code"],
  ["PROCESS", "Documents", "/documents", "OCR, extraction, classification, validation and document intelligence.", "/art/commercial-integrations.jpg", "documents"],
  ["CONNECT", "API & Channels", "/api-platform", "Capabilities, jobs, integrations, commerce and customer-facing surfaces.", "/art/commercial-channels.jpg", "api"],
  ["COMPUTE", "Infrastructure", "/compute", "Run inference, rendering and batch workloads with owned capacity first and extra compute when needed.", "/art/commercial-compute.jpg", "compute"],
];

function Arrow(){return <svg aria-hidden="true" viewBox="0 0 20 20" className="h-3.5 w-3.5" fill="none"><path d="M4 10h11M11 6l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>}

export default function AvantiqoUniverseHome(){
  return <main className="min-h-screen bg-[#F7F6F3] text-[#171614]">
    <PublicSiteHeader context="Avantiqo" audience="platform" />
    <section className="relative overflow-hidden border-b border-black/[0.07] bg-[#F4F0E8]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_16%_0%,rgba(214,166,106,.16),transparent_32%)]" />
      <div className="relative mx-auto grid max-w-[1540px] lg:min-h-[760px] lg:grid-cols-[44%_56%]">
        <div className="flex items-center px-5 py-16 sm:px-7 lg:px-10 lg:py-20 xl:px-14">
          <div className="max-w-[680px]">
            <p className="text-[9px] font-semibold uppercase tracking-[0.30em] text-[#9A744B]">AVANTIQO / INTELLIGENT OPERATING PLATFORM</p>
            <h1 className="mt-5 text-[56px] font-medium leading-[.92] tracking-[-0.065em] sm:text-[72px] lg:text-[84px]">Run the business. Create the next thing.</h1>
            <p className="mt-7 max-w-[620px] text-[16px] leading-8 text-[#625F59]">Use one Avantiqo account to run the business, work with intelligence, create content, build software and use compute. Your organization, permissions and work stay connected across the areas you use.</p>
            <div className="mt-9 flex flex-wrap gap-2.5"><a href="/start" className="inline-flex h-11 items-center gap-2 rounded-full bg-[#171614] px-5 text-[10px] font-semibold text-white">Start Now <Arrow/></a><a href="#worlds" className="inline-flex h-11 items-center rounded-full border border-black/[0.10] bg-white/70 px-5 text-[10px] font-semibold text-[#56514A]">Explore Avantiqo</a></div>
          </div>
        </div>
        <div className="relative min-h-[560px] overflow-hidden bg-[#171614] lg:min-h-0 lg:border-l lg:border-black/[0.08]">
          <div className="absolute inset-0 grid grid-cols-[1.28fr_.72fr] gap-px bg-[#D6A66A]/24">
            <div className="relative overflow-hidden"><div className="absolute inset-0 scale-[1.02] bg-cover bg-center" style={{backgroundImage:"url(/bg-hero-control.jpg)"}}/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(17,14,11,.04),rgba(17,14,11,.12)_45%,rgba(17,14,11,.56))]"/><div className="absolute bottom-5 left-5 text-[7px] font-semibold uppercase tracking-[0.20em] text-[#F0C993]">RUN / BUSINESS OS</div></div>
            <div className="grid grid-rows-3 gap-px bg-[#D6A66A]/24">{[["CREATE","/art/creative-video.jpg"],["BUILD","/art/developer-work.jpg"],["SCALE","/art/commercial-compute.jpg"]].map(([label,src])=><div key={label} className="relative overflow-hidden"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`url(${src})`}}/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(17,14,11,.02),rgba(17,14,11,.58))]"/><div className="absolute bottom-4 left-4 text-[7px] font-semibold uppercase tracking-[0.18em] text-[#E9CAA0]">{label}</div></div>)}</div>
          </div>
          <div className="absolute left-7 top-7 rounded-full border border-[#D6A66A]/38 bg-[#F7F1E8]/92 px-3 py-1.5 text-[7px] font-semibold uppercase tracking-[0.18em] text-[#8A633C] shadow-[0_10px_30px_rgba(40,28,18,.10)]">ONE AVANTIQO · DIFFERENT WORLDS</div>
          <div className="absolute inset-x-7 bottom-7 rounded-[22px] border border-[#D6A66A]/35 bg-[#F6F0E7]/94 p-5 text-[#171614] shadow-[0_30px_80px_rgba(35,25,15,.24)] backdrop-blur-xl"><div className="text-[7px] font-semibold uppercase tracking-[0.20em] text-[#A37849]">ONE CONNECTED ACCOUNT</div><div className="mt-3 flex flex-wrap gap-2 text-[8px] text-[#6C6359]">{["Identity","Organization","Context","Capabilities","Intelligence","Wallet","Execution","Evidence","Billing"].map(x=><span key={x} className="rounded-full border border-[#D6A66A]/26 bg-white/60 px-2.5 py-1.5">{x}</span>)}</div></div>
        </div>
      </div>
    </section>
    <section id="worlds" className="bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-16 sm:px-7 lg:px-10 lg:py-24"><div className="mb-10 max-w-3xl"><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">THE AVANTIQO WORLD</p><h2 className="mt-3 text-[38px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[52px]">Enter through the capability you need.</h2></div><div className="grid gap-3 md:grid-cols-2">{WORLDS.map(([verb,name,href,copy,image,artKind])=><a key={name} href={href} className="group grid min-h-[270px] overflow-hidden rounded-[26px] border border-black/[0.075] bg-white shadow-[0_16px_45px_rgba(30,24,18,.035)] sm:grid-cols-[42%_58%]"><div className="relative min-h-[180px] overflow-hidden bg-[#171614]">{artKind ? <PublicArtStage kind={artKind}/> : <div className="absolute inset-0 bg-cover bg-center transition duration-700 group-hover:scale-[1.03]" style={{backgroundImage:`url(${image})`}}/>}<div className="absolute inset-0 bg-black/24"/><div className="absolute left-5 top-5 text-[7px] font-semibold uppercase tracking-[0.18em] text-[#F1C98E]">{verb}</div></div><div className="flex flex-col justify-between p-6 sm:p-7"><div><div className="text-[8px] font-semibold uppercase tracking-[0.16em] text-[#A37849]">AVANTIQO / {name}</div><h3 className="mt-4 text-[28px] font-medium tracking-[-0.045em]">{name}</h3><p className="mt-3 text-[11px] leading-6 text-[#746F68]">{copy}</p></div><div className="mt-6 inline-flex items-center gap-2 text-[10px] font-semibold text-[#8A633C]">Explore <Arrow/></div></div></a>)}</div></div></section>

    <section className="border-y border-black/[0.06] bg-[#F4F0E8]"><div className="mx-auto max-w-[1320px] px-5 py-18 sm:px-7 lg:px-10 lg:py-24"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">CHOOSE HOW YOU WANT TO USE AVANTIQO</p><h2 className="mt-3 text-[38px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[52px]">Different needs. One connected account.</h2></div><p className="max-w-2xl text-[13px] leading-7 text-[#706A62] lg:justify-self-end">Use Avantiqo for everyday business operations, creative production, development, compute or enterprise rollout. Start with the area you need and add more when it helps your team.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["01","Software","Run day-to-day operations","/pricing"],["02","Creative","Create campaigns and production work","/creative-studios"],["03","Platform","Build, integrate and run workloads","/developers"],["04","Enterprise","Roll out across larger organizations","/enterprise"]].map(([no,t,d,h])=><a key={t} href={h} className="group rounded-[24px] border border-black/[0.075] bg-white/72 p-5 shadow-[0_12px_36px_rgba(40,30,20,.035)] transition hover:-translate-y-0.5 hover:border-[#D6A66A]/40"><div className="text-[8px] font-bold text-[#A37849]">{no}</div><div className="mt-8 text-[16px] font-semibold text-[#2E2A25]">{t}</div><p className="mt-2 text-[10px] leading-5 text-[#7A756E]">{d}</p><div className="mt-5 text-[9px] font-semibold text-[#8A633C]">Explore →</div></a>)}</div></div></section>
    <section className="border-b border-black/[0.06] bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-18 sm:px-7 lg:px-10 lg:py-24"><div className="grid gap-3 lg:grid-cols-3"><a href="/solutions" className="rounded-[26px] border border-black/[0.075] bg-white p-6"><div className="text-[8px] font-semibold uppercase tracking-[0.18em] text-[#9A744B]">SOLUTIONS</div><h3 className="mt-4 text-[28px] font-medium tracking-[-0.045em]">Made for the industry being run.</h3><p className="mt-3 text-[11px] leading-6 text-[#746F68]">Restaurant, hotel, retail, construction, agency and accounting packages on one operating core.</p></a><a href="/ecosystem" className="rounded-[26px] border border-[#D6A66A]/25 bg-[#F7F1E8] p-6"><div className="text-[8px] font-semibold uppercase tracking-[0.18em] text-[#9A744B]">MARKETPLACE</div><h3 className="mt-4 text-[28px] font-medium tracking-[-0.045em]">Find specialist capabilities in one place.</h3><p className="mt-3 text-[11px] leading-6 text-[#746F68]">Discover agents, solutions, connectors, services and compute that can work with your Avantiqo organization.</p></a><a href="/resources" className="rounded-[26px] border border-black/[0.075] bg-white p-6"><div className="text-[8px] font-semibold uppercase tracking-[0.18em] text-[#9A744B]">RESOURCES</div><h3 className="mt-4 text-[28px] font-medium tracking-[-0.045em]">Learn what Avantiqo can do for you.</h3><p className="mt-3 text-[11px] leading-6 text-[#746F68]">Guides, industry playbooks, research, templates, benchmarks, case studies and product updates.</p></a></div></div></section>
    <section className="bg-[#F3EFE7]"><div className="mx-auto max-w-[1120px] px-5 py-20 text-center sm:px-7 lg:px-10 lg:py-28"><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">START WITH THE JOB, NOT THE PRODUCT LIST</p><h2 className="mx-auto mt-4 max-w-4xl text-[42px] font-medium leading-[1.00] tracking-[-0.055em] sm:text-[58px]">What do you want Avantiqo to do?</h2><p className="mx-auto mt-5 max-w-2xl text-[13px] leading-7 text-[#706A62]">Run the business. Create something. Build with the platform. Use compute. Or bring Avantiqo into a larger organization.</p><div className="mt-8 flex flex-wrap justify-center gap-2.5"><a href="/start" className="inline-flex h-11 items-center rounded-full bg-[#171614] px-5 text-[10px] font-semibold text-white">Choose your path →</a><a href="/pricing" className="inline-flex h-11 items-center rounded-full border border-[#D6A66A]/40 bg-white/72 px-5 text-[10px] font-semibold text-[#6A5540]">See pricing</a></div></div></section>
  </main>;
}
