import PublicSiteHeader from "@/components/public/PublicSiteHeader";
import Image from "next/image";
import BusinessPartnerShowcase from "@/components/public/BusinessPartnerShowcase";

const WORLDS = [
  ["RUN", "Business Products", "/products", "Run finance, people, customers, operations, stock and documents from one connected business context.", "/art/avantiqo-luxury/hospitality-hero.webp", "commerce"],
  ["INDUSTRY", "Solutions", "/solutions", "Start with a restaurant, hotel, retail or service setup shaped around the work your team already knows.", "/art/commercial-solutions.jpg", "solutions"],
  ["CREATE", "Creative Studios", "/creative-studios", "Create image, music and film from brief to finished master. Video Studio is a full film/VFX production pipeline — not a prompt-to-video generator.", "/art/creative-image.jpg", "creative"],
  ["BUILD", "Developers", "/developers", "Build software, integrations and embedded products with Avantiqo capabilities and APIs.", "/art/developer-work.jpg", "code"],
  ["SCALE", "Compute", "/compute", "Run inference, rendering and batch workloads with owned and elastic capacity.", "/art/commercial-compute.jpg", "compute"],
];

function Arrow(){return <svg aria-hidden="true" viewBox="0 0 20 20" className="h-3.5 w-3.5" fill="none"><path d="M4 10h11M11 6l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>}

export default function AvantiqoUniverseHome(){
  return <main className="min-h-screen bg-[#F7F6F3] text-[#171614]">
    <PublicSiteHeader context="Avantiqo" audience="platform" />
    <section className="relative overflow-hidden border-b border-black/[0.07] bg-[#F4F0E8]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_16%_0%,rgba(214,166,106,.16),transparent_32%)]" />
      <div className="relative mx-auto grid max-w-[1540px] lg:min-h-[760px] lg:grid-cols-[44%_56%]">
        <div className="flex items-center px-5 py-16 sm:px-7 lg:px-10 lg:py-20 xl:px-14">
          <div className="max-w-[680px]">
            <p className="text-[9px] font-semibold uppercase tracking-[0.30em] text-[#9A744B]">AVANTIQO / INTELLIGENT OPERATING PLATFORM</p>
            <h1 className="mt-5 text-[56px] font-medium leading-[.92] tracking-[-0.065em] sm:text-[72px] lg:text-[84px]">Run the business. Create the next thing.</h1>
            <p className="mt-7 max-w-[620px] text-[16px] leading-8 text-[#625F59]">Start with the business problem, creative job or technical workload you have now. Avantiqo keeps the company context connected as you add more products and services later.</p>
            <div className="mt-9 flex flex-wrap gap-2.5"><a href="/start" className="inline-flex h-11 items-center gap-2 rounded-full bg-[#171614] px-5 text-[10px] font-semibold text-white">Start Now <Arrow/></a><a href="#worlds" className="inline-flex h-11 items-center rounded-full border border-black/[0.10] bg-white/70 px-5 text-[10px] font-semibold text-[#56514A]">Explore Avantiqo</a></div>
          </div>
        </div>
        <div className="relative m-5 min-h-[560px] overflow-hidden rounded-[36px] border border-black/[0.08] bg-[#E9DFD1] shadow-[0_34px_100px_rgba(68,47,25,.13)] sm:m-7 lg:ml-0 lg:min-h-0 lg:self-stretch">
          <Image src="/art/commercial-start.jpg" alt="Avantiqo across real business and creative work" fill priority sizes="56vw" className="object-cover" />
          <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(255,255,255,.01),rgba(20,15,10,.02)_52%,rgba(20,15,10,.23))]"/>
          <div className="absolute left-7 top-7 rounded-full border border-white/70 bg-[#F7F0E7]/78 px-3 py-1.5 text-[7px] font-semibold uppercase tracking-[0.18em] text-[#8A633C] shadow-[0_10px_30px_rgba(40,28,18,.10)] backdrop-blur-xl">ONE AVANTIQO · DIFFERENT WORLDS</div>
          <div className="absolute inset-x-7 bottom-7 rounded-[22px] border border-white/72 bg-[#F6F0E7]/90 p-5 text-[#171614] shadow-[0_30px_80px_rgba(35,25,15,.16)] backdrop-blur-xl"><div className="text-[7px] font-semibold uppercase tracking-[0.20em] text-[#A37849]">ONE CONNECTED ACCOUNT</div><div className="mt-3 flex flex-wrap gap-2 text-[8px] text-[#6C6359]">{["Company","People","Customers","Money","Work","Documents","Intelligence","History","Usage"].map(x=><span key={x} className="rounded-full border border-[#D6A66A]/26 bg-white/60 px-2.5 py-1.5">{x}</span>)}</div></div>
        </div>
      </div>
    </section>
    <section id="worlds" className="bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-16 sm:px-7 lg:px-10 lg:py-24"><div className="mb-10 max-w-3xl"><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">THE AVANTIQO WORLD</p><h2 className="mt-3 text-[38px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[52px]">Enter through the work you need to do.</h2></div><div className="grid gap-3 md:grid-cols-2">{WORLDS.map(([verb,name,href,copy,image,artKind])=><a key={name} href={href} className="group grid min-h-[270px] overflow-hidden rounded-[26px] border border-black/[0.075] bg-white shadow-[0_16px_45px_rgba(30,24,18,.035)] sm:grid-cols-[42%_58%]"><div className="relative min-h-[180px] overflow-hidden bg-[#E9DFD1]"><div className="absolute inset-0 bg-cover bg-center transition duration-700 group-hover:scale-[1.03]" style={{backgroundImage:`url(${image})`}}/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(255,255,255,.01),rgba(15,10,6,.30))]"/><div className="absolute left-5 top-5 text-[7px] font-semibold uppercase tracking-[0.18em] text-[#F1C98E]">{verb}</div></div><div className="flex flex-col justify-between p-6 sm:p-7"><div><div className="text-[8px] font-semibold uppercase tracking-[0.16em] text-[#A37849]">AVANTIQO / {name}</div><h3 className="mt-4 text-[28px] font-medium tracking-[-0.045em]">{name}</h3><p className="mt-3 text-[11px] leading-6 text-[#746F68]">{copy}</p></div><div className="mt-6 inline-flex items-center gap-2 text-[10px] font-semibold text-[#8A633C]">Explore <Arrow/></div></div></a>)}</div></div></section>

    <section className="border-y border-black/[0.06] bg-[#EEE6DB] text-[#1D1B18]"><div className="mx-auto max-w-[1320px] px-5 py-16 sm:px-7 lg:px-10 lg:py-20">
      <div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#D6A66A]">ONE BUSINESS · CONNECTED WORK</p><h2 className="mt-3 text-[38px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[52px]">The handoffs are where Avantiqo becomes different.</h2></div><p className="max-w-2xl text-[12px] leading-6 text-[#6E655C] lg:justify-self-end">A sale can change stock, finance and customer history. A clock-in can affect scheduling, payroll and finance. The same business context stays attached instead of being re-entered across separate software.</p></div>
      <div className="mt-10 grid gap-2 md:grid-cols-7">{["Customers","Sales","Operations","People","Stock","Finance","Intelligence"].map((item,index)=><div key={item} className="relative rounded-[16px] border border-black/[0.07] bg-white/52 px-4 py-5"><div className="text-[7px] font-semibold text-[#D6A66A]">0{index+1}</div><div className="mt-3 text-[9px] text-[#5F554B]">{item}</div>{index<6?<span className="absolute -right-2 top-1/2 hidden -translate-y-1/2 text-[#D6A66A]/50 md:block">→</span>:null}</div>)}</div>
      <div className="mt-10 grid gap-8 rounded-[28px] border border-black/[0.07] bg-white/52 p-6 lg:grid-cols-[.8fr_1.2fr] lg:p-8">
        <div><div className="text-[8px] font-semibold uppercase tracking-[.2em] text-[#D6A66A]">BUSINESS PARTNER</div><h3 className="mt-3 text-[30px] font-medium tracking-[-.045em]">Tell Avantiqo what you need done.</h3><p className="mt-4 text-[11px] leading-6 text-[#6E655C]">Business Partner can investigate, reason across the connected company context, prepare work, execute approved capabilities and verify what happened.</p><a href="/intelligence-platform" className="mt-6 inline-flex text-[9px] font-semibold text-[#8A633C]">Explore Business Partner →</a></div>
        <BusinessPartnerShowcase compact />
      </div>
    </div></section>

    <section className="border-y border-black/[0.06] bg-[#F4F0E8]"><div className="mx-auto max-w-[1320px] px-5 py-18 sm:px-7 lg:px-10 lg:py-24"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">CHOOSE HOW YOU WANT TO USE AVANTIQO</p><h2 className="mt-3 text-[38px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[52px]">Different needs. One connected account.</h2></div><p className="max-w-2xl text-[13px] leading-7 text-[#706A62] lg:justify-self-end">Use Avantiqo for everyday business operations, creative production, development, compute or enterprise rollout. Start with the area you need and add more when it helps your team.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["01","Software","Run day-to-day operations","/pricing","/art/avantiqo-luxury/hospitality-hero.webp"],["02","Creative","Create campaigns and production work","/creative-studios","/art/creative-video.jpg"],["03","Platform","Build, integrate and run workloads","/developers","/art/developer-work.jpg"],["04","Enterprise","Roll out across larger organizations","/enterprise","/art/commercial-enterprise.jpg"]].map(([no,t,d,h,image])=><a key={t} href={h} className="group overflow-hidden rounded-[24px] border border-black/[0.075] bg-white/72 shadow-[0_12px_36px_rgba(40,30,20,.035)] transition hover:-translate-y-0.5 hover:border-[#D6A66A]/40 hover:shadow-[0_22px_55px_rgba(40,30,20,.08)]"><div className="relative h-[138px] overflow-hidden bg-[#E9DFD1]"><div className="absolute inset-0 bg-cover bg-center transition duration-700 group-hover:scale-[1.04]" style={{backgroundImage:`url(${image})`}}/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(255,255,255,.01),rgba(12,8,5,.38))]"/><div className="absolute left-4 top-4 text-[8px] font-bold text-[#F1C98E]">{no}</div></div><div className="p-5"><div className="text-[16px] font-semibold text-[#2E2A25]">{t}</div><p className="mt-2 text-[10px] leading-5 text-[#7A756E]">{d}</p><div className="mt-5 text-[9px] font-semibold text-[#8A633C]">Explore →</div></div></a>)}</div></div></section>
    <section className="border-b border-black/[0.06] bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-18 sm:px-7 lg:px-10 lg:py-24"><div className="grid gap-3 lg:grid-cols-3">{[
      ["SOLUTIONS","Made for the industry being run.","Restaurant, hotel, retail, construction, agency and accounting solutions with the workflows those teams actually need.","/solutions","solutions"],
      ["MARKETPLACE","Find specialist capabilities in one place.","Discover agents, solutions, connectors, services and compute that can work with your Avantiqo organization.","/ecosystem","marketplace"],
      ["RESOURCES","Learn how to use Avantiqo for real work.","Guides, industry playbooks, research, templates, benchmarks, case studies and product updates.","/resources","insights"],
    ].map(([label,title,copy,href,kind])=>{const image=kind==="solutions"?"/art/commercial-solutions.jpg":kind==="marketplace"?"/art/commercial-marketplace.jpg":"/art/commercial-insights.jpg";return <a key={label} href={href} className="group overflow-hidden rounded-[26px] border border-black/[0.075] bg-white shadow-[0_14px_40px_rgba(40,30,20,.04)] transition hover:-translate-y-0.5 hover:border-[#D6A66A]/35"><div className="relative h-[190px] overflow-hidden bg-[#E9DFD1]"><div className="absolute inset-0 bg-cover bg-center transition duration-700 group-hover:scale-[1.04]" style={{backgroundImage:`url(${image})`}}/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(255,255,255,.01),rgba(12,8,5,.42))]"/><div className="absolute left-5 top-5 text-[8px] font-semibold uppercase tracking-[0.18em] text-[#F1C98E]">{label}</div></div><div className="p-6"><h3 className="text-[28px] font-medium tracking-[-0.045em]">{title}</h3><p className="mt-3 text-[11px] leading-6 text-[#746F68]">{copy}</p><div className="mt-5 text-[9px] font-semibold text-[#8A633C]">Explore →</div></div></a>})}</div></div></section>
    <section className="bg-[#F3EFE7]"><div className="mx-auto max-w-[1120px] px-5 py-20 text-center sm:px-7 lg:px-10 lg:py-28"><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">START WITH THE JOB, NOT THE PRODUCT LIST</p><h2 className="mx-auto mt-4 max-w-4xl text-[42px] font-medium leading-[1.00] tracking-[-0.055em] sm:text-[58px]">What do you want Avantiqo to do?</h2><p className="mx-auto mt-5 max-w-2xl text-[13px] leading-7 text-[#706A62]">Run the business. Create something. Build with the platform. Use compute. Or bring Avantiqo into a larger organization.</p><div className="mt-8 flex flex-wrap justify-center gap-2.5"><a href="/start" className="inline-flex h-11 items-center rounded-full bg-[#171614] px-5 text-[10px] font-semibold text-white">Choose your path →</a><a href="/pricing" className="inline-flex h-11 items-center rounded-full border border-[#D6A66A]/40 bg-white/72 px-5 text-[10px] font-semibold text-[#6A5540]">See pricing</a></div></div></section>
  </main>;
}
