import PublicSiteHeader from "@/components/public/PublicSiteHeader";

function Arrow({ className = "" }) {
  return <svg aria-hidden="true" viewBox="0 0 20 20" className={className} fill="none"><path d="M4 10h11M11 6l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

const SURFACE_ART = {
  compute:{image:"/art/commercial-compute.jpg",label:"Compute fabric",line:"Own workloads first. Paid demand next. Idle capacity can earn.",chips:["OWNED GPU","PAID JOBS","IDLE RENTAL"],panel:[["AVANTIQO","Priority 01"],["PAID WORK","Priority 02"],["IDLE","Revenue ready"]]},
  marketplace:{image:"/art/commercial-marketplace.jpg",label:"Marketplace economy",line:"People, products and capacity connected through one commercial layer.",chips:["PUBLISH","METER","SETTLE"],panel:[["CAPABILITIES","Supply"],["AGENTS","Specialists"],["SOLUTIONS","Industry packs"]]},
  solutions:{image:"/art/commercial-solutions.jpg",label:"Industry solutions",line:"Real operating environments, shaped around the business being run.",chips:["HOSPITALITY","RETAIL","SERVICES"],panel:[["BUSINESS OS","Core"],["INDUSTRY","Workflow"],["CONTEXT","Shared"]]},
  integrations:{image:"/art/commercial-integrations.jpg",label:"Connected services",line:"Bring communications, payments, documents and specialist providers into governed work.",chips:["CONNECT","AUTHORIZE","EXECUTE"],panel:[["MESSAGING","Connected"],["PAYMENTS","Governed"],["DATA","Scoped"]]},
  partners:{image:"/art/commercial-partners.jpg",label:"Partner network",line:"Trusted operators can bring whole portfolios of businesses onto Avantiqo.",chips:["ADVISE","IMPLEMENT","SCALE"],panel:[["CLIENTS","Portfolio"],["ACCESS","Scoped"],["VALUE","Shared"]]},
  agents:{image:"/art/commercial-agents.jpg",label:"Governed agents",line:"Automation stays attached to people, evidence, permissions and exact business capabilities.",chips:["RESEARCH","PREPARE","EXECUTE"],panel:[["CONTEXT","Business"],["AUTHORITY","Exact"],["PROOF","Durable"]]},
  enterprise:{image:"/art/commercial-enterprise.jpg",label:"Enterprise operating scope",line:"Multi-entity operations with one governance model and portfolio visibility.",chips:["ENTITIES","LOCATIONS","PORTFOLIO"],panel:[["GOVERNANCE","Unified"],["CONTROL","Scoped"],["SCALE","Global"]]},
  services:{image:"/art/commercial-services.jpg",label:"Implementation services",line:"Discovery, migration, configuration and launch grounded in the real operating environment.",chips:["DISCOVER","IMPLEMENT","OPTIMIZE"],panel:[["MIGRATE","Evidence"],["CONFIGURE","Workflow"],["LAUNCH","Ready"]]},
  insights:{image:"/art/commercial-insights.jpg",label:"Decision intelligence",line:"Turn governed evidence into exceptions, forecasts and higher-value decisions.",chips:["EVIDENCE","FORECAST","DECIDE"],panel:[["FINANCE","Signal"],["OPS","Signal"],["COMMERCIAL","Signal"]]},
  pricing:{image:"/art/commercial-pricing.jpg",label:"Commercial model",line:"Simple platform economics around subscription, usage, transactions and supply.",chips:["SUBSCRIBE","CONSUME","EARN"],panel:[["BUSINESS OS","Recurring"],["WALLET","Usage"],["PLATFORM","Economics"]]},
  commerce:{image:"/art/commercial-commerce.jpg",label:"Commerce flow",line:"A real customer interaction can become payment, settlement and finance evidence in one flow.",chips:["SELL","SETTLE","POST"],panel:[["ORDER","Open"],["PAYMENT","Matched"],["FINANCE","Posted"]]},
  channels:{image:"/art/commercial-channels.jpg",label:"Every business surface",line:"Web, mobile, portal, kiosk and POS stay connected to the same business context.",chips:["WEB","MOBILE","POS"],panel:[["CUSTOMER","Surface"],["STAFF","Surface"],["EMBEDDED","Surface"]]},
};

function SurfaceArt({ kind }) {
  const art = SURFACE_ART[kind] || SURFACE_ART.agents;
  return <div className="relative min-h-[520px] overflow-hidden rounded-[32px] border border-black/[0.08] bg-[#E9E2D7] shadow-[0_38px_110px_rgba(68,47,25,.16)]">
    {kind === "solutions" ? <div className="absolute inset-0 grid grid-cols-[1.25fr_.75fr] gap-1 bg-[#E8E0D4] p-1"><div className="bg-cover bg-center" style={{backgroundImage:'url(/art/commercial-solutions.jpg)'}}/><div className="grid grid-rows-2 gap-1"><div className="bg-cover bg-center" style={{backgroundImage:'url(/art/commercial-enterprise.jpg)'}}/><div className="bg-cover bg-center" style={{backgroundImage:'url(/art/commercial-services.jpg)'}}/></div></div> : kind === "channels" ? <><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:'url(/art/commercial-channels.jpg)'}}/><div className="absolute right-[6%] top-[14%] h-[30%] w-[34%] overflow-hidden rounded-[18px] border border-white/45 bg-white shadow-[0_18px_50px_rgba(0,0,0,.16)]"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:'url(/art/commercial-commerce.jpg)'}}/><div className="absolute inset-0 bg-gradient-to-t from-black/45 to-transparent"/><div className="absolute bottom-2 left-3 text-[7px] font-semibold uppercase tracking-[0.16em] text-white">POS / CUSTOMER</div></div><div className="absolute left-[7%] bottom-[28%] h-[24%] w-[31%] overflow-hidden rounded-[18px] border border-white/45 bg-white shadow-[0_18px_50px_rgba(0,0,0,.16)]"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:'url(/art/developer-work.jpg)'}}/><div className="absolute inset-0 bg-gradient-to-t from-black/45 to-transparent"/><div className="absolute bottom-2 left-3 text-[7px] font-semibold uppercase tracking-[0.16em] text-white">WEB / EMBEDDED</div></div></> : <div className="absolute inset-0 bg-cover bg-center transition duration-700" style={{backgroundImage:`url(${art.image})`}}/>}
    <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(255,255,255,.04),transparent_34%,rgba(9,8,7,.7))]"/>
    <div className="absolute left-5 top-5 rounded-full border border-white/38 bg-white/78 px-3 py-1.5 text-[8px] font-semibold uppercase tracking-[0.2em] text-[#6D4B2B] shadow-sm backdrop-blur-xl">AVANTIQO · {art.label}</div>
    <div className="absolute right-5 top-5 hidden rounded-[16px] border border-white/22 bg-black/24 px-3 py-2 text-right text-white backdrop-blur-xl sm:block"><div className="text-[7px] uppercase tracking-[0.18em] text-[#E8C18D]">REAL OPERATING CONTEXT</div><div className="mt-1 text-[8px] text-white/58">One governed system</div></div>
    <div className="absolute inset-x-5 bottom-5 rounded-[22px] border border-white/20 bg-black/34 p-4 text-white shadow-[0_18px_45px_rgba(0,0,0,.14)] backdrop-blur-xl sm:p-5">
      <div className="grid gap-4 sm:grid-cols-[1fr_auto] sm:items-end"><div><div className="text-[8px] font-semibold uppercase tracking-[0.2em] text-[#E8C18D]">{art.label}</div><div className="mt-2 max-w-lg text-[11px] leading-5 text-white/68">{art.line}</div><div className="mt-4 flex flex-wrap gap-1.5">{art.chips.map(x=><span key={x} className="rounded-full border border-white/18 bg-white/[0.04] px-2.5 py-1 text-[7px] font-semibold tracking-[0.13em] text-white/62">{x}</span>)}</div></div>
      <div className="grid min-w-[210px] grid-cols-3 gap-1.5">{art.panel.map(([a,b])=><div key={a} className="rounded-[11px] border border-white/14 bg-black/18 p-2.5"><div className="text-[7px] font-semibold text-white/72">{a}</div><div className="mt-1 text-[6px] uppercase tracking-[0.12em] text-[#E8C18D]/65">{b}</div></div>)}</div></div>
    </div>
  </div>;
}

const RELATED = {
  compute:[["Developers","/developers","Turn capacity into metered workloads."],["Marketplace","/ecosystem","Distribute approved compute supply."],["Pricing","/pricing","Connect usage to the commercial model."]],
  marketplace:[["Developers","/developers","Build capabilities businesses can consume."],["Partners","/partners","Scale distribution through trusted operators."],["Compute","/compute","Add infrastructure supply to the economy."]],
  solutions:[["Services","/services","Implement each industry package well."],["Partners","/partners","Scale vertical delivery through specialists."],["Enterprise","/enterprise","Expand from one site to operating portfolios."]],
  pricing:[["Commerce","/commerce","Create transaction-driven revenue."],["Compute","/compute","Turn infrastructure into usage economics."],["Marketplace","/ecosystem","Add platform commission and settlement."]],
  integrations:[["Channels","/channels","Bring connected services into every surface."],["Commerce","/commerce","Connect providers to revenue flows."],["Developers","/developers","Expose integrations through governed APIs."]],
  partners:[["Services","/services","Package repeatable implementation work."],["Solutions","/solutions","Take vertical products to more businesses."],["Enterprise","/enterprise","Manage larger customer portfolios."]],
  agents:[["Insights","/insights","Turn evidence into higher-value decisions."],["Developers","/developers","Expose governed agent capabilities."],["Marketplace","/ecosystem","Package specialist agents for distribution."]],
  commerce:[["Channels","/channels","Sell through web, portal, mobile and POS."],["Integrations","/integrations","Connect payments and communication rails."],["Pricing","/pricing","Capture subscription, usage and transaction value."]],
  channels:[["Commerce","/commerce","Connect every surface to the revenue flow."],["Creative Studios","/creative-studios","Produce the content those surfaces need."],["Developers","/developers","Embed Avantiqo into external experiences."]],
  enterprise:[["Insights","/insights","Add portfolio intelligence and exceptions."],["Services","/services","Deliver complex rollout and integration programs."],["Partners","/partners","Extend implementation capacity globally."]],
  services:[["Solutions","/solutions","Standardize implementation around industry outcomes."],["Partners","/partners","Scale delivery without custom-work bottlenecks."],["Enterprise","/enterprise","Support higher-complexity operating environments."]],
  insights:[["Agents","/agents","Move from insight to governed action."],["Enterprise","/enterprise","Package portfolio-level decision products."],["Pricing","/pricing","Monetize premium analysis without taxing everyday use."]],
};

export default function CommercialSurfacePage({config}) {
  return <main className="min-h-screen bg-[#F7F6F3] text-[#191919]">
    <PublicSiteHeader context={config.context} links={[{label:"Solutions",href:"/solutions",visibility:"hidden lg:inline-flex"},{label:"Commerce",href:"/commerce",visibility:"hidden lg:inline-flex"},{label:"Channels",href:"/channels",visibility:"hidden xl:inline-flex"},{label:"Developers",href:"/developers",visibility:"hidden xl:inline-flex"}]} />
    <section className="relative overflow-hidden border-b border-black/[0.06]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_78%_8%,rgba(214,166,106,.12),transparent_34%)]"/><div className="relative mx-auto grid max-w-[1460px] gap-12 px-5 py-16 sm:px-7 lg:grid-cols-[.86fr_1.14fr] lg:items-center lg:px-10 lg:py-24"><div className="max-w-[680px]"><div className="inline-flex rounded-full border border-[#D6A66A]/25 bg-[#D6A66A]/[0.07] px-3 py-1.5 text-[8px] font-semibold uppercase tracking-[0.18em] text-[#8A633C]">{config.status}</div><p className="mt-7 text-[10px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">{config.eyebrow}</p><h1 className="mt-4 text-[48px] font-medium leading-[.98] tracking-[-0.06em] sm:text-[62px] lg:text-[72px]">{config.title}</h1><p className="mt-6 max-w-xl text-[16px] leading-8 text-[#625F59]">{config.description}</p><div className="mt-8 flex flex-wrap gap-2.5"><a href={config.primaryHref || "/login"} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#171716] px-5 text-[11px] font-semibold text-white">{config.primary || "Enter Avantiqo"}<Arrow className="h-3.5 w-3.5"/></a><a href="/pricing" className="inline-flex h-11 items-center rounded-xl border border-black/[0.09] bg-white px-5 text-[11px] font-semibold text-[#56514A]">Commercial model</a></div></div><SurfaceArt kind={config.art} /></div></section>
    <section className="border-b border-black/[0.06] bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">{config.valueEyebrow}</p><h2 className="mt-3 max-w-4xl text-[36px] font-medium leading-[1.04] tracking-[-0.045em] sm:text-[48px]">{config.valueTitle}</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{config.value.map(([t,d],i)=><article key={t} className="rounded-[22px] border border-black/[0.075] bg-white p-5 shadow-[0_10px_35px_rgba(40,30,20,.035)]"><div className="text-[8px] font-bold text-[#A37849]">0{i+1}</div><h3 className="mt-7 text-[15px] font-semibold text-[#302D29]">{t}</h3><p className="mt-2 text-[10px] leading-5 text-[#7A756E]">{d}</p></article>)}</div></div></section>
    <section className="border-b border-white/[0.06] bg-[#171716] text-white"><div className="mx-auto grid max-w-[1320px] gap-12 px-5 py-20 sm:px-7 lg:grid-cols-[.72fr_1.28fr] lg:px-10 lg:py-24"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#D6A66A]">Revenue architecture</p><h2 className="mt-3 text-[36px] font-medium leading-[1.04] tracking-[-0.045em] text-[#F7F4EF] sm:text-[48px]">{config.moneyTitle}</h2><p className="mt-5 max-w-lg text-[13px] leading-7 text-white/42">{config.moneyDescription}</p></div><div className="grid gap-3 sm:grid-cols-2">{config.money.map(([t,d],i)=><div key={t} className="rounded-[20px] border border-white/[0.08] bg-white/[0.025] p-5"><div className="text-[8px] font-bold text-[#D6A66A]">0{i+1}</div><div className="mt-6 text-[14px] font-semibold text-white/78">{t}</div><div className="mt-2 text-[9px] leading-5 text-white/34">{d}</div></div>)}</div></div></section>
    <section className="border-b border-black/[0.06] bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-16 sm:px-7 lg:px-10 lg:py-20"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">Continue through Avantiqo</p><h2 className="mt-2 text-[30px] font-medium tracking-[-0.045em] text-[#1D1B18] sm:text-[38px]">One surface creates demand for the next.</h2></div><a href="/pricing" className="text-[10px] font-semibold text-[#8A633C]">See the commercial model →</a></div><div className="mt-8 grid gap-3 md:grid-cols-3">{(RELATED[config.art] || RELATED.pricing).map(([label,href,text],i)=><a key={href} href={href} className="group rounded-[22px] border border-black/[0.075] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#D6A66A]/35"><div className="flex items-center justify-between"><span className="text-[8px] font-bold text-[#A37849]">0{i+1}</span><Arrow className="h-3.5 w-3.5 text-[#B9AA95] transition group-hover:translate-x-0.5 group-hover:text-[#9A744B]"/></div><div className="mt-7 text-[14px] font-semibold text-[#302D29]">{label}</div><p className="mt-2 text-[10px] leading-5 text-[#7A756E]">{text}</p></a>)}</div></div></section>
    <section className="bg-[#F7F6F3]"><div className="mx-auto max-w-[1120px] px-5 py-20 text-center sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">Part of the Avantiqo economy</p><h2 className="mx-auto mt-4 max-w-4xl text-[38px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[52px]">{config.cta}</h2><div className="mt-8 flex flex-wrap justify-center gap-2.5"><a href={config.primaryHref || "/login"} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#171716] px-5 text-[11px] font-semibold text-white">{config.primary || "Enter Avantiqo"}<Arrow className="h-3.5 w-3.5"/></a><a href="/developers" className="inline-flex h-11 items-center rounded-xl border border-black/[0.09] bg-white px-5 text-[11px] font-semibold text-[#56514A]">Developer platform</a></div></div></section>
  </main>;
}
