import Image from "next/image";

const process = [
  ["01", "Brief", "Objective, audience and constraints"],
  ["02", "Research", "Context, references and opportunity"],
  ["03", "Direction", "Creative system and production plan"],
  ["04", "Creation", "Specialist production engines"],
  ["05", "Review", "Critique, quality and continuity"],
  ["06", "Repair", "Targeted correction and refinement"],
  ["07", "Delivery", "Commercial-ready masters and variants"],
];

function Arrow({ className = "" }) {
  return <svg aria-hidden="true" viewBox="0 0 20 20" className={className} fill="none"><path d="M4 10h11M11 6l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

function StudioArtwork({ studio }) {
  const video = studio.startsWith("Video");
  const music = studio.startsWith("Music");
  const mode = video ? "DIRECTOR / FRAME 24" : music ? "MIX ROOM / MASTER 01" : "ART DIRECTION / 01";
  const detail = video ? "STORY · SHOT · CONTINUITY" : music ? "COMPOSE · MIX · MASTER" : "CONCEPT · IMAGE · TYPOGRAPHY";
  const stats = video ? ["24 FPS", "CINEMA", "MASTER"] : music ? ["48 kHz", "STEREO", "MASTER"] : ["4:5", "16:9", "MASTER"];
  return (
    <div className="relative min-h-[590px] overflow-hidden rounded-[32px] border border-white/[0.09] bg-[#070706] shadow-[0_42px_120px_rgba(35,22,10,.3)]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_42%,rgba(214,166,106,.16),transparent_42%),linear-gradient(180deg,rgba(255,255,255,.018),transparent_36%)]" />
      <div className="absolute left-5 top-5 z-20 flex items-center gap-2 rounded-full border border-[#D6A66A]/25 bg-black/55 px-3 py-1.5 backdrop-blur-xl"><span className="h-1.5 w-1.5 rounded-full bg-[#D6A66A] shadow-[0_0_12px_rgba(214,166,106,.95)]"/><span className="text-[8px] font-semibold uppercase tracking-[0.2em] text-[#E5C08A]">{mode}</span></div>
      <div className="absolute right-5 top-5 z-20 text-right"><div className="text-[7px] font-semibold uppercase tracking-[0.24em] text-white/42">AVANTIQO CREATIVE</div><div className="mt-1 text-[7px] uppercase tracking-[0.18em] text-[#D6A66A]/75">{detail}</div></div>

      {!video && !music ? <div className="absolute inset-x-[9%] top-[18%] bottom-[18%] z-10 grid grid-cols-[.7fr_1.3fr_.7fr] gap-3">
        <div className="relative translate-y-10 overflow-hidden rounded-[18px] border border-white/[0.09] bg-[#11100e]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_62%_35%,rgba(214,166,106,.44),transparent_28%),linear-gradient(135deg,#17130f,#080807)]"/><div className="absolute inset-x-4 bottom-4 border-t border-white/[0.08] pt-3 text-[7px] uppercase tracking-[0.18em] text-white/38">Concept study</div></div>
        <div className="relative overflow-hidden rounded-[20px] border border-[#D6A66A]/30 bg-[#0d0c0a] shadow-[0_0_55px_rgba(214,166,106,.08)]"><div className="absolute inset-[10%] border border-white/[0.1]"/><div className="absolute inset-x-[18%] top-[18%] h-[46%] rounded-[16px] border border-white/[0.08] bg-[radial-gradient(circle_at_50%_46%,rgba(236,194,129,.55),rgba(90,54,23,.14)_34%,transparent_67%)]"/><div className="absolute inset-x-[18%] bottom-[17%]"><div className="h-2 w-3/4 bg-white/70"/><div className="mt-2 h-px w-1/2 bg-[#D6A66A]/70"/><div className="mt-3 h-1 w-full bg-white/10"/><div className="mt-1.5 h-1 w-4/5 bg-white/10"/></div></div>
        <div className="relative translate-y-10 overflow-hidden rounded-[18px] border border-white/[0.09] bg-[#11100e]"><div className="absolute inset-0 bg-[linear-gradient(155deg,transparent_22%,rgba(214,166,106,.28)_48%,transparent_75%)]"/><div className="absolute inset-x-4 bottom-4 border-t border-white/[0.08] pt-3 text-[7px] uppercase tracking-[0.18em] text-white/38">Layout system</div></div>
      </div> : null}

      {video ? <div className="absolute inset-x-[8%] top-[18%] bottom-[18%] z-10">
        <div className="relative aspect-video overflow-hidden rounded-[20px] border border-white/[0.12] bg-[#0b0a09] shadow-[0_0_60px_rgba(214,166,106,.1)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_64%_40%,rgba(214,166,106,.42),transparent_22%),linear-gradient(155deg,#15110d,#070706_62%)]"/><div className="absolute left-[12%] top-[20%] h-[58%] w-px bg-[#D6A66A]/45"/><div className="absolute bottom-[20%] left-[12%] right-[10%] h-px bg-white/[0.13]"/><div className="absolute bottom-[24%] left-[16%] text-[8px] uppercase tracking-[0.22em] text-white/44">Shot 024 · master take</div></div>
        <div className="mt-3 grid grid-cols-5 gap-2">{[1,2,3,4,5].map((n)=><div key={n} className={`aspect-video rounded-[8px] border ${n===3?'border-[#D6A66A]/55 bg-[#24180f]':'border-white/[0.08] bg-white/[0.025]'}`}><div className="m-1 h-px bg-white/[0.08]"/></div>)}</div>
      </div> : null}

      {music ? <div className="absolute inset-x-[8%] top-[19%] bottom-[18%] z-10 rounded-[20px] border border-white/[0.09] bg-black/20 p-6 backdrop-blur-[1px]">
        <div className="flex items-center justify-between border-b border-white/[0.08] pb-4"><span className="text-[8px] uppercase tracking-[0.2em] text-white/38">AVQ MASTER SESSION</span><span className="text-[8px] uppercase tracking-[0.16em] text-[#D6A66A]/70">-9.2 LUFS</span></div>
        <div className="mt-8 flex h-36 items-center justify-center gap-[4px]">{[22,38,56,74,44,82,62,34,68,88,52,76,42,61,86,48,70,31,57,79,45,66,37,54,73,41,63,28,51,77,46,32].map((h,i)=><span key={i} className="w-[4px] rounded-full bg-[#D6A66A]/72 shadow-[0_0_9px_rgba(214,166,106,.18)]" style={{height:`${h}%`}} />)}</div>
        <div className="mt-8 grid grid-cols-4 gap-2">{["VOCAL","MUSIC","SFX","MASTER"].map((x,i)=><div key={x} className="rounded-[10px] border border-white/[0.08] bg-white/[0.02] p-3"><div className="text-[7px] tracking-[0.15em] text-white/30">{x}</div><div className="mt-3 h-1 rounded-full bg-white/[0.08]"><div className="h-full rounded-full bg-[#D6A66A]/55" style={{width:`${58+i*9}%`}}/></div></div>)}</div>
      </div> : null}

      <div className="absolute inset-x-5 bottom-5 z-20 grid grid-cols-[1fr_auto] items-end gap-4 border-t border-white/[0.11] pt-4"><div><div className="text-[8px] font-semibold uppercase tracking-[0.22em] text-[#D6A66A]">Production intelligence</div><div className="mt-1 max-w-md text-[10px] leading-5 text-white/48">Designed around the discipline, not wrapped around a generic generator.</div></div><div className="hidden gap-1.5 sm:flex">{stats.map((x)=><span key={x} className="rounded-full border border-white/[0.1] bg-black/25 px-2 py-1 text-[7px] font-semibold tracking-[0.12em] text-white/42 backdrop-blur-sm">{x}</span>)}</div></div>
    </div>
  );
}


function StudioWorkspace({ studio }) {
  const video = studio.startsWith("Video");
  const music = studio.startsWith("Music");
  const labels = video ? ["Story", "Scenes", "Shots", "Dailies", "Edit", "Master"] : music ? ["Compose", "Arrange", "Vocals", "SFX", "Mix", "Master"] : ["Research", "Direction", "Create", "Review", "Repair", "Deliver"];
  const status = video ? "SHOT 024 / REVIEW" : music ? "MASTER BUS / REVIEW" : "CAMPAIGN 01 / REVIEW";
  return <section className="border-b border-white/[0.06] bg-[#0f0f0e] text-white">
    <div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-7 lg:px-10 lg:py-24">
      <div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end">
        <div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#D6A66A]">Inside {studio}</p><h2 className="mt-3 max-w-xl text-[38px] font-medium leading-[1.02] tracking-[-0.05em] text-[#F6F2EC] sm:text-[48px]">A production workspace, not a prompt box.</h2><p className="mt-5 max-w-lg text-[13px] leading-7 text-white/42">Every mission keeps direction, production state, reviews, repairs and approved outputs connected from start to finish.</p></div>
        <div className="flex flex-wrap gap-2 lg:justify-end">{labels.map((x,i)=><span key={x} className={`rounded-full border px-3 py-1.5 text-[8px] font-semibold uppercase tracking-[0.14em] ${i===3?'border-[#D6A66A]/45 bg-[#D6A66A]/10 text-[#E8C18D]':'border-white/[0.09] bg-white/[0.025] text-white/35'}`}>{String(i+1).padStart(2,'0')} {x}</span>)}</div>
      </div>
      <div className="mt-10 overflow-hidden rounded-[28px] border border-white/[0.09] bg-[#080807] shadow-[0_35px_100px_rgba(0,0,0,.32)]">
        <div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#D6A66A] shadow-[0_0_12px_rgba(214,166,106,.8)]"/><span className="text-[8px] font-semibold uppercase tracking-[0.18em] text-[#E4BB84]">{status}</span></div><div className="text-[7px] uppercase tracking-[0.2em] text-white/20">AVANTIQO / CREATIVE RUNTIME</div></div>
        <div className="grid min-h-[430px] lg:grid-cols-[210px_1fr_270px]">
          <div className="border-b border-white/[0.06] p-4 lg:border-b-0 lg:border-r"><div className="text-[7px] uppercase tracking-[0.18em] text-white/22">Mission</div><div className="mt-4 rounded-xl border border-[#D6A66A]/20 bg-[#D6A66A]/[0.06] p-3"><div className="text-[9px] font-semibold text-white/72">Primary production</div><div className="mt-1 text-[8px] leading-4 text-white/28">Objective, references, constraints and approved direction.</div></div><div className="mt-5 space-y-1.5">{labels.map((x,i)=><div key={x} className={`flex items-center justify-between rounded-lg px-2.5 py-2 text-[8px] ${i===3?'bg-white/[0.05] text-white/70':'text-white/28'}`}><span>{x}</span><span>{i<3?'✓':i===3?'LIVE':'·'}</span></div>)}</div></div>
          <div className="relative overflow-hidden border-b border-white/[0.06] p-5 lg:border-b-0 lg:border-r">
            {music ? <><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_42%,rgba(214,166,106,.08),transparent_42%)]"/><div className="relative mt-14 flex h-44 items-center justify-center gap-[5px]">{[28,41,62,78,49,86,57,39,67,91,53,73,45,82,58,35,64,88,51,76,43,69,84,47,61,79,38,55,72,46,66,33].map((h,i)=><span key={i} className="w-[4px] rounded-full bg-[#D6A66A]/62" style={{height:`${h}%`}}/>)}</div><div className="relative mt-10 grid grid-cols-4 gap-2">{["VOCAL","MUSIC","SFX","MASTER"].map((x,i)=><div key={x} className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-3"><div className="text-[7px] text-white/26">{x}</div><div className="mt-3 h-1 rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-[#D6A66A]/50" style={{width:`${52+i*10}%`}}/></div></div>)}</div></> : video ? <><div className="relative mx-auto mt-6 aspect-video max-w-3xl overflow-hidden rounded-[18px] border border-white/[0.08] bg-[#0d0c0a]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_67%_38%,rgba(214,166,106,.34),transparent_25%),linear-gradient(150deg,#16120e,#090908_64%)]"/><div className="absolute inset-[9%] border border-white/[0.07]"/><div className="absolute bottom-[13%] left-[12%] text-[8px] uppercase tracking-[0.18em] text-white/24">MASTER TAKE / CONTINUITY LOCKED</div></div><div className="mt-4 grid grid-cols-6 gap-2">{[1,2,3,4,5,6].map((n)=><div key={n} className={`aspect-video rounded-lg border ${n===4?'border-[#D6A66A]/50 bg-[#25190f]':'border-white/[0.07] bg-white/[0.02]'}`}/>)}</div></> : <><div className="relative mx-auto grid h-full max-w-3xl grid-cols-[.72fr_1.28fr_.72fr] items-center gap-3 py-10"><div className="h-[58%] rounded-[16px] border border-white/[0.07] bg-[radial-gradient(circle_at_60%_40%,rgba(214,166,106,.22),transparent_32%)]"/><div className="relative h-[84%] rounded-[18px] border border-[#D6A66A]/22 bg-[#0e0d0b]"><div className="absolute inset-[10%] border border-white/[0.07]"/><div className="absolute inset-x-[18%] top-[16%] h-[48%] rounded-xl bg-[radial-gradient(circle_at_50%_42%,rgba(214,166,106,.36),transparent_58%)]"/><div className="absolute inset-x-[18%] bottom-[15%] space-y-2"><div className="h-1.5 w-3/4 bg-white/55"/><div className="h-px w-1/2 bg-[#D6A66A]/55"/><div className="h-1 w-full bg-white/[0.07]"/></div></div><div className="h-[58%] rounded-[16px] border border-white/[0.07] bg-[linear-gradient(155deg,transparent_25%,rgba(214,166,106,.16),transparent_74%)]"/></div></>}
          </div>
          <div className="p-4"><div className="flex items-center justify-between"><span className="text-[7px] uppercase tracking-[0.18em] text-white/22">Review</span><span className="rounded-full border border-[#D6A66A]/20 bg-[#D6A66A]/[0.06] px-2 py-1 text-[7px] text-[#D6A66A]">QUALITY GATE</span></div><div className="mt-5 space-y-3">{[["Direction",96],["Continuity",93],["Craft",95],["Delivery",98]].map(([x,v])=><div key={x}><div className="flex justify-between text-[8px]"><span className="text-white/38">{x}</span><span className="text-white/54">{v}</span></div><div className="mt-1.5 h-1 rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-[#D6A66A]/55" style={{width:`${v}%`}}/></div></div>)}</div><div className="mt-6 rounded-xl border border-white/[0.07] bg-white/[0.02] p-3"><div className="text-[8px] font-semibold text-white/60">Targeted repair</div><div className="mt-2 text-[8px] leading-4 text-white/28">Only the failed detail returns to production. Approved work remains locked.</div></div></div>
        </div>
      </div>
    </div>
  </section>;
}

export default function CreativeStudioProductPage({ studio, title, subtitle, description, capabilities, useCases, cta }) {
  return (
    <main className="min-h-screen bg-[#F7F6F3] text-[#191919]">
      <header className="sticky top-0 z-50 border-b border-black/[0.07] bg-[#F7F6F3]/95 backdrop-blur-xl">
        <div className="mx-auto flex h-[64px] max-w-[1460px] items-center justify-between px-5 sm:px-7 lg:px-10">
          <a href="/" className="flex items-center gap-3"><span className="rounded-xl bg-[#171716] px-3 py-2 shadow-[0_4px_16px_rgba(0,0,0,.08)]"><Image src="/branding/avantiqo-wordmark.png" alt="Avantiqo" width={126} height={10} className="h-[10px] w-auto object-contain" priority /></span><div className="hidden text-[7px] font-semibold uppercase tracking-[0.18em] text-[#9A744B] sm:block">{studio}</div></a>
          <nav className="flex items-center gap-1"><a href="/creative-studios" className="hidden rounded-lg px-3 py-2 text-[10px] text-[#6C6963] hover:bg-white md:inline-flex">Creative Studios</a><a href="/developers" className="hidden rounded-lg px-3 py-2 text-[10px] text-[#6C6963] hover:bg-white lg:inline-flex">Developers</a><a href="/" className="hidden rounded-lg px-3 py-2 text-[10px] text-[#6C6963] hover:bg-white xl:inline-flex">Platform</a><a href="/login" className="ml-1 inline-flex h-9 items-center gap-2 rounded-xl bg-[#171716] px-4 text-[10px] font-semibold text-white">Login <Arrow className="h-3 w-3" /></a></nav>
        </div>
      </header>

      <section className="border-b border-black/[0.06] bg-[#F7F6F3]">
        <div className="mx-auto grid max-w-[1460px] gap-12 px-5 py-16 sm:px-7 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-10 lg:py-24">
          <div className="max-w-[690px]"><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">Avantiqo {studio}</p><h1 className="mt-5 text-[48px] font-medium leading-[.98] tracking-[-0.055em] text-[#181817] sm:text-[62px] lg:text-[72px]">{title}</h1><p className="mt-5 text-[12px] font-semibold uppercase tracking-[0.18em] text-[#8D643C]">{subtitle}</p><p className="mt-6 max-w-xl text-[16px] leading-8 text-[#625F59]">{description}</p><div className="mt-8 flex flex-wrap gap-2.5"><a href="#capabilities" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#171716] px-5 text-[11px] font-semibold text-white">Explore {studio} <Arrow className="h-3.5 w-3.5" /></a><a href="#process" className="inline-flex h-11 items-center rounded-xl border border-black/[0.09] bg-white px-5 text-[11px] font-semibold text-[#56514A]">See production flow</a></div></div>
          <StudioArtwork studio={studio} />
        </div>
      </section>

      <section id="capabilities" className="border-b border-black/[0.06] bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">A complete production system</p><h2 className="mt-3 max-w-3xl text-[36px] font-medium leading-[1.04] tracking-[-0.045em] sm:text-[46px]">Not a generator. A professional creative workflow.</h2><div className="mt-10 grid overflow-hidden rounded-[24px] border border-black/[0.075] bg-white sm:grid-cols-2 lg:grid-cols-4">{capabilities.map(([name, text], i)=><article key={name} className={`min-h-[190px] p-5 ${i%4!==3?'lg:border-r lg:border-black/[0.06]':''} ${i<4?'border-b border-black/[0.06]':''}`}><div className="text-[9px] font-bold text-[#A37849]">0{i+1}</div><h3 className="mt-5 text-[15px] font-semibold text-[#302D29]">{name}</h3><p className="mt-2 text-[10px] leading-5 text-[#7A756E]">{text}</p></article>)}</div></div></section>

      <StudioWorkspace studio={studio} />

      <section id="process" className="border-b border-black/[0.06] bg-[#F7F6F3]"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">From idea to impact</p><h2 className="mt-3 text-[36px] font-medium tracking-[-0.045em] sm:text-[46px]">One connected production path.</h2><div className="mt-10 grid gap-3 md:grid-cols-2 xl:grid-cols-7">{process.map(([n,t,d])=><div key={t} className="rounded-[20px] border border-black/[0.075] bg-white p-4"><div className="text-[8px] font-bold text-[#A37849]">{n}</div><h3 className="mt-6 text-[13px] font-semibold">{t}</h3><p className="mt-2 text-[9px] leading-4 text-[#817B73]">{d}</p></div>)}</div></div></section>

      <section className="border-b border-white/[0.06] bg-[#171716] text-white"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#D6A66A]">Real business use</p><h2 className="mt-3 max-w-3xl text-[36px] font-medium leading-[1.04] tracking-[-0.045em] text-[#F7F4EF] sm:text-[46px]">Creative output built to do a job.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{useCases.map(([name,text],index)=><div key={name} className="group rounded-[20px] border border-white/[0.08] bg-white/[0.025] p-5 transition hover:-translate-y-0.5 hover:border-[#D6A66A]/25 hover:bg-white/[0.04]"><div className="relative h-28 overflow-hidden rounded-[16px] border border-white/[0.06] bg-[#0c0b0a]">{studio.startsWith("Music")?<><div className="absolute inset-x-4 top-5 flex h-16 items-center justify-center gap-[3px]">{[31,52,72,44,83,57,35,68,91,47,73,39,62,80,49,66].map((h,i)=><span key={i} className="w-[3px] rounded-full bg-[#D6A66A]/55" style={{height:`${Math.max(18,h-index*2)}%`}}/>)}</div><div className="absolute inset-x-4 bottom-4 flex gap-1">{[0,1,2,3].map(n=><span key={n} className={`h-1 flex-1 rounded-full ${n<=index%4?'bg-[#D6A66A]/55':'bg-white/[0.08]'}`}/>)}</div></>:studio.startsWith("Video")?<><div className="absolute inset-3 rounded-[10px] border border-white/[0.08] bg-[radial-gradient(circle_at_65%_42%,rgba(214,166,106,.3),transparent_28%)]"/><div className="absolute bottom-4 left-4 right-4 flex gap-1">{[0,1,2,3,4].map(n=><span key={n} className={`h-1 flex-1 ${n===index%5?'bg-[#D6A66A]/65':'bg-white/[0.08]'}`}/>)}</div><div className="absolute left-4 top-4 text-[7px] tracking-[0.16em] text-white/28">SHOT {String(index+1).padStart(2,'0')}</div></>:<><div className={`absolute ${index%3===0?'left-[18%] top-[20%] h-[62%] w-[38%] rounded-[14px]':index%3===1?'inset-x-[18%] top-[18%] h-[64%] rounded-full':'right-[16%] top-[18%] h-[64%] w-[44%] rotate-[-8deg] rounded-[12px]'} border border-[#D6A66A]/25 bg-[radial-gradient(circle_at_50%_45%,rgba(214,166,106,.34),transparent_58%)]`}/><div className="absolute left-4 top-4 h-7 w-7 border-l border-t border-[#D6A66A]/28"/><div className="absolute bottom-4 right-4 h-7 w-7 border-b border-r border-[#D6A66A]/28"/></>}<div className="absolute right-3 top-3 text-[7px] font-semibold uppercase tracking-[0.16em] text-[#D6A66A]/75">{studio.startsWith("Video")?"FRAME":studio.startsWith("Music")?"AUDIO":"VISUAL"} · 0{index+1}</div></div><h3 className="mt-5 text-[14px] font-semibold text-white/82">{name}</h3><p className="mt-2 text-[10px] leading-5 text-white/38">{text}</p></div>)}</div></div></section>

      <section className="border-b border-black/[0.06] bg-[#FBFAF8]"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 py-20 sm:px-7 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-10 lg:py-24"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">Creative capability, anywhere</p><h2 className="mt-3 max-w-2xl text-[36px] font-medium leading-[1.04] tracking-[-0.045em] sm:text-[46px]">Use the Studio in Avantiqo or connect it to your own product.</h2><p className="mt-5 max-w-xl text-[14px] leading-7 text-[#6C6963]">The same governed creative capability can power a Studio mission, an API workflow, an agent tool or an embedded customer experience.</p><a href="/developers" className="mt-7 inline-flex h-11 items-center gap-2 rounded-xl bg-[#171716] px-5 text-[11px] font-semibold text-white">Explore developer access <Arrow className="h-3.5 w-3.5" /></a></div><div className="grid gap-3 sm:grid-cols-2">{[["01","Studio mission","Full creative production inside Avantiqo."],["02","API workflow","Call certified creative capabilities from software."],["03","Agent tool","Give an agent governed creative execution."],["04","Embedded experience","Bring selected production flows into another product."]].map(([n,t,d])=><div key={t} className="rounded-[20px] border border-black/[0.075] bg-white p-5"><div className="text-[8px] font-bold text-[#A37849]">{n}</div><h3 className="mt-5 text-[14px] font-semibold text-[#302D29]">{t}</h3><p className="mt-2 text-[10px] leading-5 text-[#7A756E]">{d}</p></div>)}</div></div></section>

      <section className="bg-[#F7F6F3]"><div className="mx-auto max-w-[1120px] px-5 py-20 text-center sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">A more creative tomorrow</p><h2 className="mx-auto mt-4 max-w-4xl text-[38px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[50px]">{cta}</h2><div className="mt-8 flex flex-wrap justify-center gap-2.5"><a href="/login" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#171716] px-5 text-[11px] font-semibold text-white">Enter Avantiqo <Arrow className="h-3.5 w-3.5" /></a><a href="/developers" className="inline-flex h-11 items-center rounded-xl border border-black/[0.09] bg-white px-5 text-[11px] font-semibold text-[#56514A]">Developer access</a></div></div></section>
    </main>
  );
}
