function GridLines() {
  return <div className="absolute inset-0 opacity-[0.11]" style={{backgroundImage:"linear-gradient(rgba(214,166,106,.14) 1px,transparent 1px),linear-gradient(90deg,rgba(214,166,106,.14) 1px,transparent 1px)",backgroundSize:"52px 52px"}} />;
}

function PhotoLayer({ src, position = "center", opacity = 1 }) {
  return <><div className="absolute inset-0 scale-[1.015] bg-cover" style={{backgroundImage:`url(${src})`,backgroundPosition:position,opacity}}/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,7,6,.74),rgba(8,7,6,.18)_48%,rgba(8,7,6,.46)),linear-gradient(180deg,rgba(8,7,6,.12),rgba(8,7,6,.18)_46%,rgba(8,7,6,.78))]"/></>;
}

function Label({children}) { return <div className="text-[7px] font-semibold uppercase tracking-[0.22em] text-[#D6A66A]">{children}</div>; }
function Dot(){return <span className="h-1.5 w-1.5 rounded-full bg-[#D6A66A]"/>}

function IntelligenceArt(){
  return <div className="absolute inset-0 overflow-hidden bg-[#0c0b0a] text-white">
    <GridLines/><div className="absolute -right-20 top-10 h-[440px] w-[440px] rounded-full border border-[#D6A66A]/20 bg-[radial-gradient(circle_at_42%_38%,rgba(214,166,106,.42),rgba(214,166,106,.06)_28%,transparent_62%)] shadow-[0_0_120px_rgba(214,166,106,.08)]"/>
    <div className="absolute left-[7%] top-[12%] w-[42%] rounded-[24px] border border-white/10 bg-black/45 p-5 backdrop-blur-xl"><Label>EVIDENCE ROOM</Label><div className="mt-4 space-y-3">{[["Cash position","THB 2.48m"],["Attendance","6 exceptions"],["Open invoices","37"],["Bookings","18 today"]].map(([a,b])=><div key={a} className="flex items-center justify-between border-b border-white/8 pb-2 text-[10px]"><span className="text-white/48">{a}</span><span className="text-white/88">{b}</span></div>)}</div></div>
    <div className="absolute bottom-[12%] right-[6%] w-[52%] rounded-[28px] border border-[#D6A66A]/25 bg-[#15120e]/90 p-6 shadow-[0_25px_80px_rgba(0,0,0,.45)]"><div className="flex items-center justify-between"><Label>BUSINESS PARTNER</Label><span className="text-[7px] text-white/28">AUTHORIZED BUSINESS DATA</span></div><div className="mt-4 text-[20px] leading-7 text-white/92">Business data → reasoning → approved action.</div><div className="mt-5 grid grid-cols-4 gap-2">{["RESEARCH","PLAN","APPROVE","VERIFY"].map(x=><div key={x} className="rounded-xl border border-white/9 bg-white/[0.035] px-3 py-3 text-[7px] text-white/55">{x}</div>)}</div></div>
  </div>;
}

function VoiceArt(){
  const bars=[28,44,18,66,38,82,55,34,74,46,88,64,32,58,76,40,68,24,52,34];
  return <div className="absolute inset-0 overflow-hidden bg-[#0e0d0c] text-white"><GridLines/>
    <div className="absolute inset-x-[8%] top-[16%] rounded-[30px] border border-white/10 bg-white/[0.035] p-6 backdrop-blur-xl"><div className="flex items-center justify-between"><Label>LIVE VOICE SESSION</Label><div className="flex items-center gap-2 text-[7px] text-white/32"><Dot/> 00:01:42</div></div><div className="mt-8 flex h-28 items-center gap-1.5">{bars.map((h,i)=><div key={i} className="flex-1 rounded-full bg-[linear-gradient(180deg,#D6A66A,rgba(214,166,106,.2))]" style={{height:h}}/>)}</div></div>
    <div className="absolute bottom-[10%] left-[8%] w-[48%] rounded-[24px] border border-white/10 bg-black/55 p-5"><Label>TRANSCRIPT</Label><div className="mt-4 space-y-3 text-[11px] leading-5"><p className="text-white/78">“Move the supplier review to tomorrow and send the updated brief.”</p><p className="text-white/35">Intent resolved · calendar + message capability</p></div></div>
    <div className="absolute bottom-[10%] right-[8%] w-[30%] rounded-[24px] border border-[#D6A66A]/25 bg-[#17130e] p-5"><Label>VOICE → WORK</Label><div className="mt-4 space-y-2 text-[8px] text-white/52">{["LISTEN","UNDERSTAND","ACT","RESULT"].map((x,i)=><div key={x} className="flex items-center gap-2"><span className="text-[#D6A66A]">0{i+1}</span>{x}</div>)}</div></div>
  </div>;
}

function CodeArt({api=false}){
  const code=api?["POST /v1/capabilities/execute","organization_id: org_...","capability: finance.invoice.create","permission: approved","→ 202 accepted · job_8F21"]:["mission: repair invoice workflow","repo: avantiqo/core","01  inspect capability graph","02  patch exact path","03  run focused tests","04  verify production contract","✓  result recorded"];
  return <div className="absolute inset-0 overflow-hidden bg-[#0a0b0b] text-white"><PhotoLayer src={api?"/art/commercial-integrations.jpg":"/art/developer-work.jpg"} position={api?"center":"58% center"}/><GridLines/>
    <div className="absolute left-[6%] top-[10%] bottom-[10%] w-[24%] rounded-[24px] border border-white/9 bg-[#111]/90 p-5"><Label>{api?'CAPABILITY INDEX':'REPOSITORY'}</Label><div className="mt-5 space-y-3 text-[8px] text-white/44">{(api?["finance","documents","intelligence","creative","operations","people"]:["app/","components/","lib/","tests/","supabase/","scripts/"]).map((x,i)=><div key={x} className={i===2?'rounded-lg bg-[#D6A66A]/10 px-3 py-2 text-[#E7C18D]':'px-3 py-1'}>{x}</div>)}</div></div>
    <div className="absolute left-[33%] right-[6%] top-[10%] bottom-[24%] rounded-[26px] border border-white/10 bg-[#111214]/95 p-6 shadow-[0_30px_90px_rgba(0,0,0,.45)]"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-white/15"/><span className="h-2 w-2 rounded-full bg-white/15"/><span className="h-2 w-2 rounded-full bg-[#D6A66A]/60"/><span className="ml-3 text-[7px] text-white/28">{api?'capability.request':'mission.plan'}</span></div><div className="mt-7 font-mono text-[10px] leading-7">{code.map((x,i)=><div key={x} className={i===code.length-1?'text-[#D6A66A]':'text-white/58'}><span className="mr-4 text-white/18">{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div></div>
    <div className="absolute bottom-[8%] left-[38%] right-[9%] grid grid-cols-3 gap-2">{(api?["AUTHENTICATED","METERED","CONTROLLED"]:["TESTS PASS","REVIEWED","VERIFIED"]).map(x=><div key={x} className="rounded-xl border border-white/9 bg-black/65 px-3 py-3 text-center text-[7px] text-white/48">{x}</div>)}</div>
  </div>;
}

function DocumentsArt(){
  return <div className="absolute inset-0 overflow-hidden bg-[#ece7de] text-[#171614]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_18%,rgba(214,166,106,.22),transparent_30%)]"/>
    <div className="absolute left-[8%] top-[8%] bottom-[8%] w-[48%] rotate-[-2deg] rounded-[18px] border border-black/8 bg-white p-8 shadow-[0_30px_70px_rgba(45,35,20,.16)]"><div className="flex items-center justify-between"><Label>SUPPLIER INVOICE</Label><span className="text-[7px] text-black/28">PDF · 2 pages</span></div><div className="mt-8 text-[22px] font-medium">North Coast Supply Co.</div><div className="mt-2 text-[10px] text-black/40">Invoice #NC-10482 · 17 Sep 2026</div><div className="mt-8 space-y-3">{[["Produce","18,400"],["Dry goods","9,250"],["Delivery","850"]].map(([a,b])=><div key={a} className="flex justify-between border-b border-black/8 pb-2 text-[10px]"><span>{a}</span><span>THB {b}</span></div>)}</div><div className="mt-8 flex justify-between border-t border-black/10 pt-4 text-[14px] font-semibold"><span>Total</span><span>THB 28,500</span></div></div>
    <div className="absolute right-[7%] top-[16%] w-[39%] rounded-[24px] border border-black/10 bg-[#171614] p-6 text-white shadow-[0_28px_80px_rgba(0,0,0,.26)]"><Label>DOCUMENT INTELLIGENCE</Label><div className="mt-5 space-y-3">{[["Vendor","North Coast Supply"],["Total","28,500 THB"],["Tax","Validated"],["Route","Accounts payable"]].map(([a,b])=><div key={a} className="flex justify-between rounded-xl border border-white/8 bg-white/[0.035] px-3 py-3 text-[9px]"><span className="text-white/35">{a}</span><span>{b}</span></div>)}</div><div className="mt-5 rounded-xl border border-[#D6A66A]/25 bg-[#D6A66A]/8 px-4 py-3 text-[8px] text-[#E7C18D]">READY → REVIEW & POST</div></div>
  </div>;
}

function ComputeArt(){
  return <div className="absolute inset-0 overflow-hidden bg-[#090b0d] text-white"><PhotoLayer src="/art/commercial-compute.jpg" position="center" opacity={0.86}/><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_22%,rgba(214,166,106,.16),transparent_34%)]"/><GridLines/><div className="absolute inset-x-[8%] top-[10%] rounded-[28px] border border-white/10 bg-[#101215]/95 p-6"><div className="flex items-center justify-between"><Label>AVANTIQO SCHEDULER</Label><span className="text-[7px] text-white/25">LIVE FABRIC</span></div><div className="mt-6 grid grid-cols-4 gap-3">{[["NODE 01","RTX 2060","62%"],["NODE 02","RTX 4090","18%"],["WORK QUEUE","4 jobs","NEXT"],["OVERFLOW","standby","READY"]].map(([a,b,c])=><div key={a} className="rounded-2xl border border-white/9 bg-white/[0.025] p-4"><div className="text-[7px] text-[#D6A66A]">{a}</div><div className="mt-3 text-[12px]">{b}</div><div className="mt-5 h-1 rounded-full bg-white/8"><div className="h-full rounded-full bg-[#D6A66A]" style={{width:c.includes('%')?c:'46%'}}/></div><div className="mt-2 text-[7px] text-white/28">{c}</div></div>)}</div></div><div className="absolute bottom-[10%] left-[8%] right-[8%] flex items-center justify-between gap-3">{["OWN WORKLOADS","WORKLOAD DEMAND","SPARE CAPACITY"].map((x,i)=><div key={x} className="flex-1 rounded-2xl border border-white/9 bg-black/60 p-4"><div className="text-[7px] text-white/30">PRIORITY 0{i+1}</div><div className="mt-2 text-[10px]">{x}</div></div>)}</div></div>;
}


function PricingArt(){
  return <div className="absolute inset-0 overflow-hidden bg-[#EEE7DC] text-[#171614]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_76%_18%,rgba(214,166,106,.28),transparent_32%),linear-gradient(135deg,#F7F2EA,#E9E0D4)]"/><PhotoLayer src="/art/commercial-pricing.jpg" position="center" opacity={0.18}/><div className="absolute inset-x-[8%] top-[11%] grid grid-cols-2 gap-3">{[["BUSINESS OS","Recurring subscription","Predictable"],["CREATIVE","Missions · campaigns","Project"],["PLATFORM","API · compute · usage","Metered"],["ENTERPRISE","Contract · SLA · services","Custom"]].map(([a,b,c],i)=><div key={a} className="rounded-[24px] border border-[#D6A66A]/24 bg-white/72 p-5 shadow-[0_18px_50px_rgba(55,40,25,.08)] backdrop-blur-sm"><div className="flex items-center justify-between"><span className="text-[7px] font-semibold text-[#A37849]">0{i+1}</span><span className="text-[6px] uppercase tracking-[0.14em] text-[#9A8F82]">{c}</span></div><div className="mt-5 text-[18px] text-[#1D1A16]">{a}</div><div className="mt-2 text-[9px] text-[#706A62]">{b}</div><div className="mt-6 h-px bg-black/[0.07]"><div className="h-px bg-[#D6A66A]" style={{width:`${48+i*12}%`}}/></div></div>)}</div><div className="absolute bottom-[9%] left-[8%] right-[8%] flex items-center justify-between rounded-[22px] border border-[#D6A66A]/28 bg-[#F8F3EB]/94 px-5 py-4 shadow-[0_20px_55px_rgba(60,43,25,.10)]"><Label>ONE ACCOUNT</Label><div className="text-[9px] text-[#6F675E]">Software · missions · usage · enterprise</div></div></div>;
}

function MarketplaceArt(){
  const supply=[["CAPABILITY","Exact business function"],["AGENT","Specialist agent"],["SOLUTION","Industry outcome"],["COMPUTE","Metered capacity"]];
  const demand=[["RESTAURANT","Operate & grow"],["HOTEL","Run property"],["AGENCY","Deliver client work"],["DEVELOPER","Build & distribute"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#11100E] text-white"><GridLines/><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_45%,rgba(214,166,106,.15),transparent_32%),radial-gradient(circle_at_85%_12%,rgba(214,166,106,.07),transparent_28%)]"/>
    <div className="absolute left-[6%] top-[10%] bottom-[17%] w-[34%] rounded-[30px] border border-white/10 bg-white/[0.035] p-6 backdrop-blur-xl"><div className="flex items-center justify-between"><Label>SUPPLY</Label><span className="text-[7px] text-white/28">PUBLISH</span></div><div className="mt-6 space-y-2">{supply.map(([a,b],i)=><div key={a} className="rounded-[16px] border border-white/8 bg-black/24 p-4"><div className="flex items-center justify-between"><span className="text-[8px] font-semibold tracking-[.13em] text-white/74">{a}</span><span className="text-[7px] text-[#D6A66A]">0{i+1}</span></div><div className="mt-2 text-[7px] text-white/34">{b}</div></div>)}</div></div>
    <div className="absolute left-1/2 top-[14%] bottom-[22%] w-px -translate-x-1/2 bg-[linear-gradient(180deg,transparent,#D6A66A_18%,#D6A66A_82%,transparent)]"><span className="absolute -left-[5px] top-[12%] h-[11px] w-[11px] rounded-full border border-[#D6A66A] bg-[#17130E]"/><span className="absolute -left-[5px] top-1/2 h-[11px] w-[11px] rounded-full border border-[#D6A66A] bg-[#D6A66A] shadow-[0_0_22px_rgba(214,166,106,.45)]"/><span className="absolute -left-[5px] bottom-[12%] h-[11px] w-[11px] rounded-full border border-[#D6A66A] bg-[#17130E]"/></div>
    <div className="absolute left-[43%] top-[19%] space-y-[98px] text-[6px] font-semibold tracking-[.18em] text-[#E5BD84]"><div>PUBLISH</div><div>METER</div><div>SETTLE</div></div>
    <div className="absolute right-[6%] top-[10%] bottom-[17%] w-[34%] rounded-[30px] border border-[#D6A66A]/20 bg-[#F2EBE0] p-6 text-[#171614] shadow-[0_28px_80px_rgba(0,0,0,.22)]"><div className="flex items-center justify-between"><Label>DEMAND</Label><span className="text-[7px] text-black/28">DISCOVER</span></div><div className="mt-6 space-y-2">{demand.map(([a,b],i)=><div key={a} className="grid grid-cols-[30px_1fr] items-center rounded-[16px] border border-black/[0.07] bg-white/58 p-3"><span className="text-[7px] font-bold text-[#A37849]">0{i+1}</span><div><div className="text-[8px] font-semibold tracking-[.12em]">{a}</div><div className="mt-1 text-[7px] text-black/40">{b}</div></div></div>)}</div></div>
    <div className="absolute bottom-[7%] left-[8%] right-[8%] flex items-center justify-between rounded-[22px] border border-[#D6A66A]/24 bg-[#1A1713]/92 px-5 py-4 shadow-[0_18px_60px_rgba(0,0,0,.24)]"><Label>AVANTIQO ECONOMY</Label><div className="text-[8px] text-white/48">Capability <span className="mx-2 text-[#D6A66A]">→</span> Customer use <span className="mx-2 text-[#D6A66A]">→</span> Usage record <span className="mx-2 text-[#D6A66A]">→</span> Result</div></div>
  </div>;
}

function PartnersArt(){
  const clients=[["01","HOSPITALITY"],["02","RETAIL"],["03","SERVICES"],["04","CONSTRUCTION"],["05","ACCOUNTING"],["06","AGENCY"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#EFE8DD] text-[#171614]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_23%_20%,rgba(214,166,106,.25),transparent_30%),linear-gradient(135deg,#F8F3EB,#E7DDD0)]"/>
    <div className="absolute left-[7%] top-[14%] h-[260px] w-[260px] rounded-full border border-[#D6A66A]/34 bg-[#171614] shadow-[0_30px_90px_rgba(35,25,15,.22)]"><div className="absolute inset-[18px] rounded-full border border-white/9"/><div className="absolute inset-0 flex flex-col items-center justify-center text-center"><Label>PARTNER</Label><div className="mt-3 text-[22px] text-white">One trusted operator</div><div className="mt-2 text-[8px] text-white/40">Advice · implementation · support</div></div></div>
    <svg className="absolute inset-0 h-full w-full" viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><path d="M320 310 C450 310 470 130 590 130 M320 310 C470 310 470 230 590 230 M320 310 C470 310 470 330 590 330 M320 310 C470 310 470 430 590 430 M320 310 C450 310 470 530 590 530" fill="none" stroke="rgba(166,120,73,.32)" strokeWidth="1.2"/></svg>
    <div className="absolute right-[7%] top-[9%] bottom-[16%] w-[39%] rounded-[28px] border border-[#D6A66A]/26 bg-white/66 p-5 shadow-[0_26px_75px_rgba(55,39,23,.10)] backdrop-blur-sm"><div className="flex items-center justify-between"><Label>CLIENT PORTFOLIO</Label><span className="text-[7px] text-black/30">SCOPED ACCESS</span></div><div className="mt-5 grid grid-cols-2 gap-2">{clients.map(([n,a])=><div key={a} className="rounded-[16px] border border-black/[0.07] bg-[#FBF8F3] p-4"><div className="text-[7px] font-bold text-[#A37849]">{n}</div><div className="mt-5 text-[8px] font-semibold tracking-[.12em]">{a}</div><div className="mt-1 text-[7px] text-black/36">Independent organization</div></div>)}</div></div>
    <div className="absolute bottom-[7%] left-[8%] right-[8%] grid grid-cols-4 gap-2">{[["ADVISE","Expertise"],["IMPLEMENT","Delivery"],["OPERATE","Support"],["IMPROVE","Results"]].map(([a,b],i)=><div key={a} className="rounded-[18px] border border-[#D6A66A]/22 bg-[#171614] px-4 py-3 text-white"><div className="text-[7px] text-[#D6A66A]">0{i+1}</div><div className="mt-2 text-[8px] font-semibold">{a}</div><div className="mt-1 text-[7px] text-white/34">{b}</div></div>)}</div>
  </div>;
}

function EnterpriseArt(){
  const entities=[["THAILAND","6 locations","LIVE"],["SINGAPORE","3 locations","LIVE"],["SWEDEN","2 entities","READY"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#11100E] text-white"><GridLines/><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_20%,rgba(214,166,106,.16),transparent_34%)]"/>
    <div className="absolute left-[6%] top-[10%] bottom-[10%] w-[31%] rounded-[30px] border border-white/10 bg-white/[0.035] p-6"><Label>GROUP CONTROL</Label><div className="mt-5 text-[24px] leading-8 text-white/90">One control model across entities, locations and teams.</div><div className="mt-7 space-y-2">{["POLICY","PERMISSIONS","RECORDS","REPORTING"].map((x,i)=><div key={x} className="flex items-center justify-between border-b border-white/8 py-2 text-[8px]"><span className="text-white/42">0{i+1}</span><span className="text-white/68">{x}</span></div>)}</div></div>
    <div className="absolute right-[6%] top-[11%] w-[52%] space-y-3">{entities.map(([a,b,c],i)=><div key={a} className="grid grid-cols-[42px_1fr_90px] items-center rounded-[22px] border border-[#D6A66A]/18 bg-[#F2EBE0] p-4 text-[#171614] shadow-[0_18px_55px_rgba(0,0,0,.18)]"><span className="text-[7px] font-bold text-[#A37849]">0{i+1}</span><div><div className="text-[11px] font-semibold">{a}</div><div className="mt-1 text-[7px] text-black/38">{b}</div></div><div className="rounded-full border border-[#D6A66A]/28 px-3 py-2 text-center text-[6px] font-semibold tracking-[.15em] text-[#8D6841]">{c}</div></div>)}</div>
    <div className="absolute bottom-[10%] right-[6%] w-[52%] rounded-[24px] border border-white/10 bg-black/48 p-5"><div className="grid grid-cols-4 gap-2 text-center">{[["GROUP","1"],["ENTITIES","8"],["LOCATIONS","19"],["TEAMS","42"]].map(([a,b])=><div key={a}><div className="text-[20px] text-[#E4BC83]">{b}</div><div className="mt-1 text-[6px] tracking-[.14em] text-white/35">{a}</div></div>)}</div></div>
  </div>;
}

function ServicesArt(){
  const phases=[["DISCOVER","Reality","Entities · workflows · priorities"],["MIGRATE","Truth","Data · documents · opening state"],["CONFIGURE","Control","Roles · approvals · integrations"],["LAUNCH","Proof","Train · verify · optimize"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#F0E9DE] text-[#171614]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_86%_12%,rgba(214,166,106,.26),transparent_31%)]"/><div className="absolute left-[7%] right-[7%] top-[12%] bottom-[14%] rounded-[30px] border border-[#D6A66A]/26 bg-white/68 p-6 shadow-[0_28px_80px_rgba(52,37,22,.11)]">
    <div className="flex items-center justify-between"><Label>IMPLEMENTATION PATH</Label><span className="text-[7px] tracking-[.15em] text-black/28">OPERATING REALITY → LIVE SYSTEM</span></div><div className="mt-7 grid h-[72%] grid-cols-4 gap-2">{phases.map(([a,b,c],i)=><div key={a} className="relative flex flex-col justify-between rounded-[20px] border border-black/[0.07] bg-[#FBF8F3] p-4"><div><div className="text-[7px] font-bold text-[#A37849]">0{i+1}</div><div className="mt-6 text-[9px] font-semibold tracking-[.12em]">{a}</div><div className="mt-1 text-[16px] text-[#40372F]">{b}</div></div><div className="text-[7px] leading-4 text-black/38">{c}</div>{i<3?<span className="absolute -right-[7px] top-1/2 z-10 h-px w-3 bg-[#D6A66A]"/>:null}</div>)}</div></div>
    <div className="absolute bottom-[7%] left-[10%] right-[10%] flex items-center justify-between rounded-full border border-[#D6A66A]/26 bg-[#171614] px-5 py-3 text-[7px] text-white/48"><span className="text-[#D6A66A]">DISCIPLINED TRANSFORMATION</span><span>Source records · defined scope · verified go-live</span></div>
  </div>;
}

function SolutionsArt(){
  const tiles=[["RESTAURANT","/art/commercial-solutions.jpg"],["HOTEL","/art/commercial-enterprise.jpg"],["RETAIL","/art/commercial-commerce.jpg"],["SERVICES","/art/commercial-services.jpg"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#12100e] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(214,166,106,.10),transparent_48%)]"/><div className="absolute inset-0 grid grid-cols-2 grid-rows-2 gap-px bg-[#D6A66A]/10">{tiles.map(([label,img])=><div key={label} className="relative overflow-hidden"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`url(${img})`}}/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.10),rgba(0,0,0,.58))]"/><div className="absolute bottom-4 left-4 text-[7px] font-semibold tracking-[0.18em] text-[#F1C98E]">{label}</div></div>)}</div><div className="absolute left-1/2 top-1/2 w-[48%] -translate-x-1/2 -translate-y-1/2 rounded-[28px] border border-white/14 bg-[#15120f]/90 p-6 text-center shadow-[0_35px_90px_rgba(0,0,0,.40)] backdrop-blur-xl"><Label>ONE BUSINESS OS</Label><div className="mt-4 text-[22px] leading-7">Different business areas. One connected Avantiqo workspace.</div><div className="mt-5 flex flex-wrap justify-center gap-2 text-[7px] text-white/42">{["FINANCE","PEOPLE","OPERATIONS","DOCUMENTS","INTELLIGENCE"].map(x=><span key={x} className="rounded-full border border-white/10 px-2.5 py-1.5">{x}</span>)}</div></div></div>;
}

function AgentsArt(){
  const steps=[["01","CONTEXT","Organization · entity · role"],["02","INPUT","Records · policy · request"],["03","PERMISSION","Workflow · approval · scope"],["04","VERIFY","Result · history · audit"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#EEE7DC] text-[#171614]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_16%,rgba(214,166,106,.24),transparent_31%),linear-gradient(135deg,#F8F3EB,#E9E0D4)]"/><div className="absolute left-[6%] right-[6%] top-[11%] rounded-[28px] border border-[#D6A66A]/28 bg-white/76 p-6 shadow-[0_28px_80px_rgba(52,37,22,.10)]"><div className="flex items-center justify-between"><Label>CONTROLLED AGENT RUN</Label><span className="text-[7px] uppercase tracking-[0.16em] text-[#8C8174]">Defined permissions · recorded result</span></div><div className="mt-7 grid grid-cols-4 gap-2">{steps.map(([n,a,b],i)=><div key={a} className="relative rounded-[18px] border border-black/[0.07] bg-[#FBF8F3] p-4"><div className="text-[7px] font-bold text-[#A37849]">{n}</div><div className="mt-8 text-[9px] font-semibold tracking-[0.13em] text-[#2F2A25]">{a}</div><div className="mt-2 text-[7px] leading-4 text-[#81766A]">{b}</div>{i<3?<span className="absolute -right-[7px] top-1/2 z-10 h-px w-3 bg-[#D6A66A]"/>:null}</div>)}</div></div><div className="absolute bottom-[10%] left-[9%] right-[9%] grid grid-cols-[1.12fr_.88fr] gap-3"><div className="rounded-[24px] border border-[#D6A66A]/26 bg-[#171614] p-5 text-white shadow-[0_22px_65px_rgba(0,0,0,.18)]"><Label>BUSINESS PARTNER</Label><div className="mt-4 text-[18px] leading-7 text-white/88">Research → prepare → approve → execute → verify.</div></div><div className="rounded-[24px] border border-[#D6A66A]/24 bg-white/74 p-5"><div className="text-[7px] font-semibold uppercase tracking-[0.18em] text-[#9A744B]">RESULT</div><div className="mt-4 grid grid-cols-2 gap-2 text-[7px] text-[#6F665D]">{["Scoped","Approved","Executed","Audited"].map(x=><div key={x} className="rounded-xl border border-black/[0.06] bg-[#F9F5EE] px-3 py-2">{x}</div>)}</div></div></div></div>;
}
function InsightsArt(){
  const rows=[["Cash","+6.4%","Healthy"],["Revenue","-3.1%","Attention"],["Labor","+1.8%","Stable"],["Stock","2 risks","Review"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#EFE8DD] text-[#171614]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_82%_14%,rgba(214,166,106,.24),transparent_30%)]"/><div className="absolute left-[6%] top-[10%] bottom-[10%] w-[56%] rounded-[28px] border border-[#D6A66A]/26 bg-white/78 p-6 shadow-[0_28px_80px_rgba(50,35,20,.10)]"><div className="flex items-center justify-between"><Label>EXECUTIVE BRIEF</Label><span className="text-[7px] text-[#958A7D]">17 SEP · LIVE CONTEXT</span></div><div className="mt-7 text-[24px] leading-8 text-[#231F1B]">What changed. Why it matters. What needs attention next.</div><div className="mt-7 space-y-2">{rows.map(([a,b,c])=><div key={a} className="grid grid-cols-[1fr_.7fr_.8fr] items-center rounded-xl border border-black/[0.06] bg-[#FAF7F1] px-4 py-3 text-[8px]"><span className="font-semibold text-[#3E3832]">{a}</span><span className="text-[#8A633C]">{b}</span><span className="text-right text-[#877D72]">{c}</span></div>)}</div></div><div className="absolute right-[6%] top-[18%] w-[28%] rounded-[24px] border border-[#D6A66A]/28 bg-[#171614] p-5 text-white"><Label>PRIORITY SIGNAL</Label><div className="mt-4 text-[18px] leading-7 text-white/88">Margin pressure is concentrated in one operating unit.</div><div className="mt-5 text-[8px] leading-5 text-white/42">Evidence attached · forecast available · action path ready</div></div><div className="absolute bottom-[10%] right-[6%] w-[28%] grid grid-cols-2 gap-2">{["EXCEPTIONS","FORECAST","BENCHMARKS","PORTFOLIO"].map(x=><div key={x} className="rounded-xl border border-[#D6A66A]/24 bg-white/70 px-3 py-3 text-center text-[7px] font-semibold text-[#6F6254]">{x}</div>)}</div></div>;
}
function IntegrationsArt(){
  const flow=[["TRIGGER","Email · message · file"],["AVANTIQO","Context · permissions"],["PROVIDER","Payment · social · data"],["RESULT","Result returns"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#EEE7DC] text-[#171614]"><div className="absolute inset-0 bg-cover bg-center opacity-[.20]" style={{backgroundImage:"url(/art/commercial-integrations.jpg)"}}/><div className="absolute inset-0 bg-[linear-gradient(90deg,#F5EFE6E8,#EDE3D6D8)]"/><div className="absolute inset-x-[7%] top-[14%] grid grid-cols-4 gap-2">{flow.map(([a,b],i)=><div key={a} className="relative rounded-[22px] border border-[#D6A66A]/25 bg-white/78 p-5 shadow-[0_18px_45px_rgba(50,35,20,.07)]"><div className="text-[7px] font-bold text-[#A37849]">0{i+1}</div><div className="mt-8 text-[10px] font-semibold tracking-[0.13em] text-[#2E2924]">{a}</div><div className="mt-2 text-[8px] leading-5 text-[#7B7064]">{b}</div>{i<3?<span className="absolute -right-[7px] top-1/2 z-10 h-px w-3 bg-[#D6A66A]"/>:null}</div>)}</div><div className="absolute bottom-[11%] left-[7%] right-[7%] rounded-[26px] border border-[#D6A66A]/28 bg-[#171614] p-6 text-white"><div className="flex items-center justify-between"><Label>CONNECTED EXECUTION</Label><span className="text-[7px] text-white/30">Same connected business data</span></div><div className="mt-4 flex flex-wrap gap-2">{["WHATSAPP","EMAIL","PAYMENTS","DOCUMENTS","SOCIAL","DATA"].map(x=><span key={x} className="rounded-full border border-white/10 px-3 py-2 text-[7px] text-white/55">{x}</span>)}</div></div></div>;
}
function ChannelsArt(){
  const tiles=[["PUBLIC","Website · booking"],["CUSTOMER","Portal · payment"],["STAFF","Mobile · kiosk · POS"],["EMBEDDED","Widgets · partner apps"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#F0E9DF] text-[#171614]"><div className="absolute inset-0 grid grid-cols-[1.15fr_.85fr] gap-px bg-[#D6A66A]/22"><div className="relative overflow-hidden"><div className="absolute inset-0 scale-[1.02] bg-cover bg-center" style={{backgroundImage:"url(/art/commercial-channels.jpg)"}}/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(20,16,12,.02),rgba(20,16,12,.08)_50%,rgba(20,16,12,.46))]"/></div><div className="grid grid-cols-2 grid-rows-2 gap-px bg-[#D6A66A]/22">{tiles.map(([a,b],i)=><div key={a} className="flex flex-col justify-between bg-[#F8F3EB] p-4"><span className="text-[7px] font-bold text-[#A37849]">0{i+1}</span><div><div className="text-[8px] font-semibold tracking-[0.14em] text-[#302B26]">{a}</div><div className="mt-2 text-[7px] leading-4 text-[#81766A]">{b}</div></div></div>)}</div></div><div className="absolute bottom-7 left-7 rounded-[22px] border border-[#D6A66A]/30 bg-[#F8F3EB]/92 p-5 shadow-[0_24px_65px_rgba(45,31,18,.15)] backdrop-blur-xl"><Label>ONE CONNECTED BUSINESS</Label><div className="mt-3 text-[16px] text-[#2E2924]">Every surface uses the same permissions and business records.</div></div></div>;
}
function CommerceArt(){
  const steps=[["SELL","Order · booking · invoice"],["PAY","Cash · card · QR · transfer"],["SETTLE","Match provider · transaction"],["POST","Connected finance record"]];
  return <div className="absolute inset-0 overflow-hidden bg-[#EFE7DC] text-[#171614]"><div className="absolute inset-0 bg-cover bg-center opacity-[.34]" style={{backgroundImage:"url(/art/commercial-commerce.jpg)"}}/><div className="absolute inset-0 bg-[linear-gradient(90deg,#F5EFE6F2 0%,#EFE6DBD9 44%,rgba(239,230,219,.34))]"/><div className="absolute left-[7%] top-[12%] bottom-[12%] w-[44%] rounded-[28px] border border-[#D6A66A]/28 bg-white/80 p-6 shadow-[0_28px_80px_rgba(55,39,23,.10)]"><Label>REVENUE FLOW</Label><div className="mt-7 space-y-2">{steps.map(([a,b],i)=><div key={a} className="grid grid-cols-[30px_1fr] gap-3 rounded-[16px] border border-black/[0.06] bg-[#FAF7F1] p-3"><span className="text-[7px] font-bold text-[#A37849]">0{i+1}</span><div><div className="text-[9px] font-semibold text-[#302A25]">{a}</div><div className="mt-1 text-[7px] text-[#82776B]">{b}</div></div></div>)}</div></div><div className="absolute bottom-[12%] right-[7%] w-[37%] rounded-[24px] border border-[#D6A66A]/26 bg-[#171614] p-5 text-white shadow-[0_24px_70px_rgba(0,0,0,.20)]"><Label>CONNECTED MONEY</Label><div className="mt-4 text-[18px] leading-7 text-white/88">Customer activity stays connected all the way to Finance.</div><div className="mt-5 flex gap-2 text-[7px] text-white/38"><span>ORDER</span><span>→</span><span>PAYMENT</span><span>→</span><span>BOOKS</span></div></div></div>;
}

export default function PublicArtStage({kind="intelligence"}){
  if(kind==="voice") return <VoiceArt/>;
  if(kind==="code" || kind==="developer") return <CodeArt/>;
  if(kind==="api") return <CodeArt api/>;
  if(kind==="documents") return <DocumentsArt/>;
  if(kind==="compute") return <ComputeArt/>;
  if(kind==="pricing") return <PricingArt/>;
  if(kind==="marketplace") return <MarketplaceArt/>;
  if(kind==="partners") return <PartnersArt/>;
  if(kind==="enterprise") return <EnterpriseArt/>;
  if(kind==="services") return <ServicesArt/>;
  if(kind==="solutions") return <SolutionsArt/>;
  if(kind==="agents") return <AgentsArt/>;
  if(kind==="insights") return <InsightsArt/>;
  if(kind==="integrations") return <IntegrationsArt/>;
  if(kind==="channels") return <ChannelsArt/>;
  if(kind==="commerce") return <CommerceArt/>;
  return <IntelligenceArt/>;
}
