import { supabaseAdmin } from "../../../../shared/supabase/admin.js";
import { enqueueLocalComputeJob } from "../AvantiqoLocalComputeEnqueueRuntime.js";
export const AVANTIQO_CODE_LOCAL_JOB_PREFIX="local-code:";
const MODEL="qwen3:4b-instruct"; const PRODUCT_MODEL="avantiqo-code-v1"; const INFRASTRUCTURE="AVANTIQO_LOCAL_NODE_V1";
const LOCAL_CAPABILITIES=new Set(["ai.code.generate","ai.code.invent","ai.code.edit","ai.code.refactor","ai.code.review","ai.code.debug","ai.code.test","ai.web.build","ai.web.repair","ai.app.build","ai.integration.build"]);
const INTERACTIVE_CODE_PRIORITY=90;
function text(v){return String(v??"").trim();} function object(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}} function enabled(v){return ["1","true","yes","on"].includes(text(v).toLowerCase());}
function rawJobId(v){const id=text(v);if(!id.startsWith(AVANTIQO_CODE_LOCAL_JOB_PREFIX))throw new Error("AVANTIQO_CODE_LOCAL_JOB_ID_REQUIRED");return id.slice(AVANTIQO_CODE_LOCAL_JOB_PREFIX.length);} export function isCodeLocalJob(v){return text(v).startsWith(AVANTIQO_CODE_LOCAL_JOB_PREFIX);} export function isCodeLocalCapability(v){return LOCAL_CAPABILITIES.has(text(v));}
function instruction(input={}){return text(input.provider_prompt||input.prompt||input.instructions_text||input.instructions||input.input||input.description||input.title||input.generation?.instructions);}
async function available(){ if(!enabled(process.env.AVANTIQO_LOCAL_COMPUTE_QUEUE_ENABLED ?? "true"))return false;if(text(process.env.AVANTIQO_LOCAL_CODE_ENABLED)&&!enabled(process.env.AVANTIQO_LOCAL_CODE_ENABLED))return false;const q=await supabaseAdmin.from("avantiqo_local_compute_nodes").select("id,last_seen_at,enabled,capabilities").eq("enabled",true).contains("capabilities",["ai.code.generate"]).order("last_seen_at",{ascending:false}).limit(4);if(q.error)throw q.error;const now=Date.now();return(q.data||[]).some(n=>{const s=new Date(n.last_seen_at||0).getTime();return Number.isFinite(s)&&now-s<=90000;});}
export const AvantiqoCodeLocalQueueProvider={id:"avantiqo-code",available,
 async execute(input={}){const capability=text(input.capability);if(!LOCAL_CAPABILITIES.has(capability))throw new Error(`AVANTIQO_CODE_LOCAL_CAPABILITY_NOT_SUPPORTED:${capability}`);if(!(await available()))throw new Error("AVANTIQO_CODE_LOCAL_NODE_UNAVAILABLE");const organizationId=text(input.context?.organization_id),usageId=text(input.context?.usage_id);if(!organizationId||!usageId)throw new Error("AVANTIQO_CODE_LOCAL_GOVERNED_CONTEXT_REQUIRED");const prompt=instruction(input);if(!prompt)throw new Error("AVANTIQO_CODE_LOCAL_INSTRUCTION_REQUIRED");const system="You are Avantiqo Code local execution. Produce concise, correct implementation output. Never reveal chain-of-thought. Return only the requested code, patch, review, diagnosis or test guidance. Do not claim a file was changed unless the caller supplied an execution tool that actually changed it.";const payload={messages:[{role:"system",content:system},{role:"user",content:prompt+"\n\nStructured context:\n"+JSON.stringify(object(input.generation||input.requirements||input.metadata||{})).slice(0,12000)}],temperature:Number.isFinite(Number(input.temperature))?Number(input.temperature):0.1,max_output_tokens:Math.min(Number(input.max_output_tokens||4096),4096),think:false,...((input.response_format||input.responseFormat)?.type==="json_object"?{response_format:{type:"json_object"}}:{})};const ins=await enqueueLocalComputeJob({organization_id:organizationId,usage_id:usageId,capability,lane:"gpu",workload:"code_text",model:MODEL,payload,priority:75,max_attempts:2,input});return{success:true,provider:"avantiqo-code",model:PRODUCT_MODEL,output:{provider_job_id:`${AVANTIQO_CODE_LOCAL_JOB_PREFIX}${ins.id}`,status:"queued",engine_contract:"AVANTIQO_CODE_ENGINE_V1",capability,infrastructure_provider:INFRASTRUCTURE,local_node:true,runtime_model:MODEL,raw_reasoning_persisted:false}};},
 async getStatus(input={}){const jobId=text(input.job_id||input.jobId||input.provider_job_id),id=rawJobId(jobId);const q=await supabaseAdmin.from("avantiqo_local_compute_jobs").select("status,result,metrics,error_code,node_id,model").eq("id",id).maybeSingle();if(q.error)throw q.error;const row=q.data;if(!row)return{status:"failed",provider_job_id:jobId,error:"AVANTIQO_CODE_LOCAL_JOB_NOT_FOUND"};const s=text(row.status).toUpperCase();if(s==="COMPLETED"){const r=object(row.result),result=text(r.text||r.result);if(!result)return{status:"failed",provider_job_id:jobId,error:"AVANTIQO_CODE_LOCAL_COMPLETED_RESULT_REQUIRED",customer_charge_eligible:false,infrastructure_provider:INFRASTRUCTURE,local_node:true};return{status:"completed",provider_job_id:jobId,output:{status:"completed",provider:"avantiqo-code",model:PRODUCT_MODEL,engine_contract:"AVANTIQO_CODE_ENGINE_V1",result,infrastructure_provider:INFRASTRUCTURE,runtime_model:text(row.model)||MODEL,node_id:row.node_id,metrics:object(row.metrics),local_node:true,raw_reasoning_persisted:false},infrastructure_provider:INFRASTRUCTURE};}if(["FAILED","CANCELLED"].includes(s))return{status:"failed",provider_job_id:jobId,error:text(row.error_code)||`AVANTIQO_CODE_LOCAL_${s}`};return{status:s==="RUNNING"?"processing":"queued",provider_job_id:jobId,infrastructure_provider:INFRASTRUCTURE,local_node:true};}
};
