export const CreateQuotationEvents = {
  created: "COMMERCIAL_QUOTATION_CREATED",
  sent: "COMMERCIAL_QUOTATION_SENT",
  accepted: "COMMERCIAL_QUOTATION_ACCEPTED",
  rejected: "COMMERCIAL_QUOTATION_REJECTED",
  converted: "COMMERCIAL_QUOTATION_CONVERTED",
  cancelled: "COMMERCIAL_QUOTATION_CANCELLED",
};
