export const SYSTEM_EVENTS = {

  // POS
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_COMPLETED: "ORDER_COMPLETED",

  // PRODUCTION
  PRODUCTION_STARTED: "PRODUCTION_STARTED",
  PRODUCTION_COMPLETED: "PRODUCTION_COMPLETED",

  // INVENTORY
  STOCK_LOW: "STOCK_LOW",
  STOCK_CRITICAL: "STOCK_CRITICAL",

  // FINANCE
  INVOICE_APPROVED: "INVOICE_APPROVED",
  PAYROLL_COMPLETED: "PAYROLL_COMPLETED",

  // MARKETING
  CAMPAIGN_GENERATED: "CAMPAIGN_GENERATED",
  CAMPAIGN_PUBLISHED: "CAMPAIGN_PUBLISHED",

  // EVENTS
  SALES_EVENT_STARTED: "SALES_EVENT_STARTED",
  SALES_EVENT_COMPLETED: "SALES_EVENT_COMPLETED",

  // AI
  AI_RECOMMENDATION_CREATED:
    "AI_RECOMMENDATION_CREATED",

};