import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildBusinessDriverEvidencePlan } from "../lib/intelligence/runtime/AvantiqoBusinessDriverEvidencePlanRuntime.js";

test("evidence plan maps important internal drivers to registered authoritative reads",()=>{const p=buildBusinessDriverEvidencePlan({industry:"restaurant"});const revenue=p.internal_evidence_plan.find(x=>x.driver_id==="revenue");const labor=p.internal_evidence_plan.find(x=>x.driver_id==="labor");assert.equal(revenue.coverage_status,"REGISTERED_READ_AVAILABLE");assert.ok(revenue.registered_read_capability_keys.includes("finance.customer_invoices.read"));assert.ok(labor.registered_read_capability_keys.includes("people.attendance.read"));});
test("missing internal evidence is surfaced as a gap instead of invented",()=>{const p=buildBusinessDriverEvidencePlan({industry:"restaurant",available_reads:[]});assert.equal(p.registered_internal_driver_coverage,0);assert.ok(p.internal_driver_gap_ids.includes("revenue"));assert.equal(p.execution_policy.missing_read_must_be_reported_not_invented,true);});
test("external context requires fresh evidence and cannot define internal truth",()=>{const p=buildBusinessDriverEvidencePlan({industry:"hotel"});const weather=p.external_evidence_plan.find(x=>x.context_id==="weather");assert.equal(weather.evidence_status,"FRESH_EXTERNAL_EVIDENCE_REQUIRED");assert.equal(weather.internal_product_truth_effect,"NONE");assert.equal(p.execution_policy.external_evidence_only_after_internal_variance,true);});
test("industry overlay changes evidence priority while keeping evidence contract",()=>{const r=buildBusinessDriverEvidencePlan({industry:"restaurant"});const h=buildBusinessDriverEvidencePlan({industry:"hotel"});assert.notDeepEqual(r.internal_evidence_plan.slice(0,5).map(x=>x.driver_id),h.internal_evidence_plan.slice(0,5).map(x=>x.driver_id));assert.equal(r.authority_effect,"NONE");});
test("business intelligence agent carries executable diagnosis evidence plan",()=>{const s=fs.readFileSync("lib/intelligence/runtime/BusinessIntelligenceAgentRuntime.js","utf8");assert.match(s,/buildBusinessDriverEvidencePlan/);assert.match(s,/business_driver_evidence_plan/);assert.match(s,/context\?\.industry/);});
