import test from "node:test";
import assert from "node:assert/strict";
import { buildBusinessDiagnosisPipeline, completeBusinessDiagnosisPipeline } from "../lib/intelligence/runtime/AvantiqoBusinessDiagnosisPipelineRuntime.js";

test("pipeline composes diagnosis evidence and read execution",()=>{const p=buildBusinessDiagnosisPipeline({metric:"cash"});assert.equal(p.metric,"cash");assert.ok(p.execution_plan.internal_reads.length>0);assert.equal(p.external_research_allowed,false);assert.equal(p.authority_effect,"NONE");});

test("small residual does not open external research",()=>{const p=buildBusinessDiagnosisPipeline({metric:"profit"});const r=completeBusinessDiagnosisPipeline({plan:p,baseline_value:100,actual_value:90,driver_rows:[{driver_id:"revenue",direct_contribution:-9.7}]});assert.equal(r.residual_material,false);assert.equal(r.external_research_allowed,false);assert.equal(r.final_evidence_state,"INTERNAL_SUFFICIENT");});

test("material residual opens causal stage without inventing support",()=>{const p=buildBusinessDiagnosisPipeline({metric:"profit"});const r=completeBusinessDiagnosisPipeline({plan:p,baseline_value:100,actual_value:80,driver_rows:[{driver_id:"revenue",direct_contribution:-8}],external_evidence:[{context_id:"weather",evidence_strength:.8,timing_consistent:true,direction_consistent:true,magnitude_plausible:true,confounders_checked:false,alternative_explanations_checked:false}]});assert.equal(r.residual_material,true);assert.equal(r.external_research_allowed,true);assert.deepEqual(r.causal.supported_context_ids,[]);assert.equal(r.final_evidence_state,"INTERNAL_WITH_UNRESOLVED_EXTERNAL_RESIDUAL");});

test("fully supported external evidence is clearly separated from internal proof",()=>{const p=buildBusinessDiagnosisPipeline({metric:"demand"});const r=completeBusinessDiagnosisPipeline({plan:p,baseline_value:100,actual_value:70,driver_rows:[{driver_id:"volume",direct_contribution:-10}],external_evidence:[{context_id:"weather",evidence_strength:.9,timing_consistent:true,direction_consistent:true,magnitude_plausible:true,confounders_checked:true,alternative_explanations_checked:true}]});assert.deepEqual(r.causal.supported_context_ids,["weather"]);assert.equal(r.final_evidence_state,"INTERNAL_AND_SUPPORTED_EXTERNAL");assert.equal(r.authority_effect,"NONE");});
