import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { hasPreparedAttachmentReflexCandidate, resolvePreparedAttachmentReflex } from '../lib/operator/runtime/OperatorPreparedAttachmentReflex.js';

const cap={key:'supply-chain.goods_receipts.receive',mode:'write',requires_confirmation:true,auto_execute:false};
function file(status='READY_FOR_REVIEW') { return { prepared_candidate:{ type:'goods_receipt', recognized:true, status, purchase_order:{id:'po-1',po_number:'PO-0001',status:'APPROVED'}, import_payload: status==='READY_FOR_REVIEW'?{purchase_order_id:'po-1'}:null, clarification_question: status==='PARTIAL_OR_UNVERIFIED'?'This delivery does not exactly prove the full approved purchase order quantities. Review it as a partial/exception receipt before stock is moved.':null, authorization_effect:'NONE' } }; }

test('full delivery stages canonical receiving only behind confirmation',()=>{ const a=[file()]; assert.equal(hasPreparedAttachmentReflexCandidate(a,'Receive this delivery'),true); const r=resolvePreparedAttachmentReflex({message:'Receive this delivery',entityId:'e1',attachments:a,capabilities:[cap]}); assert.equal(r.intent,'execute'); assert.equal(r.execution.capability_key,'supply-chain.goods_receipts.receive'); assert.equal(r.execution.payload.purchase_order_id,'po-1'); assert.match(r.response_text,/requires your confirmation/i); });
test('partial or unverified delivery cannot move stock',()=>{ const r=resolvePreparedAttachmentReflex({message:'Receive this',entityId:'e1',attachments:[file('PARTIAL_OR_UNVERIFIED')],capabilities:[cap]}); assert.equal(r.intent,'clarify'); assert.equal(r.execution.capability_key,null); assert.match(r.response_text,/partial\/exception receipt/i); });
test('already received PO does not create duplicate receipt',()=>{ const r=resolvePreparedAttachmentReflex({message:'Receive this',entityId:'e1',attachments:[file('ALREADY_RECEIVED')],capabilities:[cap]}); assert.equal(r.intent,'answer'); assert.equal(r.execution.capability_key,null); assert.match(r.response_text,/already received/i); });
test('receiving capability delegates to canonical runtime and is confirmation gated',()=>{ const src=readFileSync('lib/inventory/procurement/receiving/GoodsReceiptOperatorCapability.js','utf8'); assert.match(src,/receivePurchaseOrder/); assert.match(src,/operatorRequiresConfirmation: true/); assert.doesNotMatch(src,/\.from\("goods_receipts"\).*insert/s); });
test('preparer requires exact full quantity evidence and never assumes partial delivery is full',()=>{ const src=readFileSync('lib/inventory/procurement/receiving/GoodsReceiptAttachmentPreparationRuntime.js','utf8'); assert.match(src,/exactFullMatch/); assert.match(src,/delivery\.length!==poItems\.length/); assert.match(src,/PARTIAL_OR_UNVERIFIED/); });
