import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {applyMusicObjectMotionAcoustics} from "../lib/creative/music/client/MusicObjectMotionAcousticsRuntime.js";
import {createMusicCinematicSoundObject,soundObjectSpatialAutomationLanes} from "../lib/creative/music/runtime/CreativeMusicCinematicSoundObjectRuntime.js";
import {bindMusicSoundObjectsToSession} from "../lib/creative/music/runtime/CreativeMusicSoundObjectRenderBindingRuntime.js";
function rms(a,start=0,end=a.length){let s=0,n=0;for(let i=start;i<end;i++){s+=a[i]*a[i];n++;}return Math.sqrt(s/Math.max(1,n));}
function highFreqSignal(n=48000,rate=48000){const a=new Float32Array(n);for(let i=0;i<n;i++)a[i]=0.6*Math.sin(2*Math.PI*6000*i/rate)+0.25*Math.sin(2*Math.PI*900*i/rate);return a;}
test("material-aware occlusion darkens and attenuates heavy barriers more than light barriers",()=>{const src=highFreqSignal(),glass=applyMusicObjectMotionAcoustics({left:src,sample_rate:48000,spatial:{immersive:{doppler_enabled:false,reflections_enabled:false,occlusion_enabled:true,occlusion_percent:100,obstruction_material:"GLASS"}}}),concrete=applyMusicObjectMotionAcoustics({left:src,sample_rate:48000,spatial:{immersive:{doppler_enabled:false,reflections_enabled:false,occlusion_enabled:true,occlusion_percent:100,obstruction_material:"CONCRETE"}}});assert.equal(glass.metadata.occlusion.obstruction_material,"GLASS");assert.equal(concrete.metadata.occlusion.obstruction_material,"CONCRETE");assert.ok(concrete.metadata.occlusion.min_cutoff_hz<glass.metadata.occlusion.min_cutoff_hz);assert.ok(concrete.metadata.occlusion.max_attenuation_db>glass.metadata.occlusion.max_attenuation_db);assert.ok(rms(concrete.direct.left)<rms(glass.direct.left));});
test("picture-time occlusion automation ramps through the render without rewriting source",()=>{const src=highFreqSignal(24000,24000),lane={enabled:true,parameter:"spatial:occlusion_percent",interpolation:"linear",points:[{time_seconds:0,value:0},{time_seconds:1,value:100}]},r=applyMusicObjectMotionAcoustics({left:src,sample_rate:24000,spatial:{immersive:{doppler_enabled:false,reflections_enabled:false,obstruction_material:"METAL"}},automation_lanes:[lane]});assert.equal(r.metadata.occlusion.automation_applied,true);assert.equal(r.metadata.occlusion.min_occlusion_percent,0);assert.ok(r.metadata.occlusion.max_occlusion_percent>99);assert.ok(rms(r.direct.left,18000,23999)<rms(r.direct.left,0,6000));assert.equal(r.metadata.source_audio_rewritten,false);});
test("reflection wetness can transition over picture time",()=>{const src=new Float32Array(48000);src[0]=1;src[24000]=1;const lane={enabled:true,parameter:"spatial:reflection_amount_percent",interpolation:"linear",points:[{time_seconds:0,value:0},{time_seconds:1,value:80}]},r=applyMusicObjectMotionAcoustics({left:src,sample_rate:48000,spatial:{immersive:{doppler_enabled:false,reflections_enabled:true,reflection_amount_percent:0,room_size:.5}},automation_lanes:[lane]});assert.equal(r.reflections.enabled,true);assert.equal(r.metadata.reflection_automation_applied,true);assert.ok(r.reflections.left.some((v,i)=>i>24000&&Math.abs(v)>0));});
test("cinematic sound object authors occlusion/reflection lanes and binding carries them to final render track",()=>{const o=createMusicCinematicSoundObject({id:"car",assigned_track_id:"fx",category:"VEHICLE",start_seconds:0,duration_seconds:2,spatial_path:{mode:"MOVE",start_azimuth_degrees:-30,end_azimuth_degrees:30,start_occlusion_percent:0,end_occlusion_percent:100,start_reflection_amount_percent:10,end_reflection_amount_percent:60,obstruction_material:"VEHICLE_BODY"}}),lanes=soundObjectSpatialAutomationLanes(o,"fx");assert.ok(lanes.some(l=>l.parameter==="spatial:occlusion_percent"));assert.ok(lanes.some(l=>l.parameter==="spatial:reflection_amount_percent"));const session={tracks:[{id:"fx",spatial:{mode:"BED"},clips:[]}],automation_lanes:[],sound_objects:[o]},bound=bindMusicSoundObjectsToSession(session);assert.equal(bound.success,true);const track=bound.session.tracks[0];assert.equal(track.spatial.immersive.obstruction_material,"VEHICLE_BODY");assert.equal(track.spatial.immersive.occlusion_percent,0);assert.ok(bound.session.automation_lanes.some(l=>l.parameter==="spatial:occlusion_percent"));});
test("Sound Design and final surround renderer expose world-acoustics controls/evidence",()=>{const ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicSoundDesignObjectPanel.jsx","utf8"),surround=fs.readFileSync("lib/creative/music/client/MusicOfflineSurroundRenderRuntime.js","utf8"),preview=fs.readFileSync("lib/creative/music/client/MusicImmersiveBinauralMonitorRuntime.js","utf8");assert.match(ui,/Occlusion start %/);assert.match(ui,/Obstruction/);assert.match(ui,/Reflection end %/);assert.match(ui,/material-aware occlusion/);assert.match(surround,/motion_acoustics: motion\.metadata/);assert.match(preview,/occlusionFilter/);assert.match(preview,/obstruction_material/);});
