import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {createMusicAuxBus,validateMusicMixerRouting} from "../lib/creative/music/runtime/CreativeMusicMixerRoutingRuntime.js";
import {buildMusicVocalProductionBuses} from "../lib/creative/music/runtime/CreativeMusicVocalProductionBusRuntime.js";
function session(){return{tracks:[{id:"lead",type:"vocal",vocal_role:"LEAD",name:"Lead",output_bus_id:"bus-master",sends:[]},{id:"dbl",type:"vocal",vocal_role:"DOUBLE",name:"Double",output_bus_id:"bus-master",sends:[]}],buses:[{id:"bus-master",type:"master",name:"Master",gain_db:0,pan:0,mute:false,solo:false}],automation_lanes:[]};}
test("shared aux contract supports aggressive but bounded parallel compressor",()=>{const bus=createMusicAuxBus({id:"bus-vocal-parallel",type:"compressor",parameters:{threshold_db:-32,ratio:10,attack_ms:2,release_ms:140,makeup_db:9,wet_db:-11}});assert.equal(bus.effect_type,"compressor");assert.equal(bus.parameters.threshold_db,-32);assert.equal(bus.parameters.ratio,10);assert.equal(bus.parameters.release_ms,140);assert.equal(bus.destructive_processing_allowed,false);const s=session();s.buses.push(bus);validateMusicMixerRouting(s);});
test("professional vocal builder creates parallel bus and role-specific sends",()=>{const r=buildMusicVocalProductionBuses(session());assert.equal(r.success,true);const bus=r.session.buses.find(x=>x.id==="bus-vocal-parallel");assert.equal(bus.effect_type,"compressor");assert.equal(bus.vocal_production_managed,true);const lead=r.session.tracks.find(x=>x.id==="lead"),dbl=r.session.tracks.find(x=>x.id==="dbl");assert.equal(lead.sends.find(x=>x.bus_id==="bus-vocal-parallel").level_db,-14);assert.equal(dbl.sends.find(x=>x.bus_id==="bus-vocal-parallel").level_db,-16);assert.equal(r.parallel_compression.non_destructive,true);});
test("manual parallel send is preserved",()=>{const s=session();s.tracks[0].sends=[{id:"human-parallel",bus_id:"bus-vocal-parallel",level_db:-9,enabled:true,pre_fader:false}];s.buses.push({...createMusicAuxBus({id:"bus-vocal-parallel",type:"compressor"}),vocal_production_managed:true});const r=buildMusicVocalProductionBuses(s);assert.equal(r.success,true);assert.equal(r.session.tracks[0].sends.find(x=>x.bus_id==="bus-vocal-parallel").level_db,-9);assert.ok(r.manual_send_preservation.some(x=>x.track_id==="lead"&&x.bus_id==="bus-vocal-parallel"&&x.manual_send_preserved));});
test("parallel compressor runs in browser preview stereo offline and surround paths",()=>{const preview=fs.readFileSync("lib/creative/music/client/MusicMultitrackPreviewEngine.js","utf8"),offline=fs.readFileSync("lib/creative/music/client/MusicOfflineMixRenderRuntime.js","utf8"),surround=fs.readFileSync("lib/creative/music/client/MusicSurroundAuxRuntime.js","utf8");for(const src of [preview,offline,surround]){assert.match(src,/createDynamicsCompressor/);assert.match(src,/threshold_db/);assert.match(src,/release_ms/);}assert.match(preview,/effectType === "compressor"/);assert.match(offline,/type === "compressor"/);assert.match(surround,/type==="compressor"/);});
test("long-form graph context retains compressor release memory",()=>{const src=fs.readFileSync("lib/creative/music/runtime/CreativeProfessionalAudioLongFormRenderPlanRuntime.js","utf8");assert.match(src,/effect_type\)\.toLowerCase\(\)==="compressor"/);assert.match(src,/release_ms,120/);});
test("automation contract can target vocal parallel send",()=>{const src=fs.readFileSync("lib/creative/music/runtime/CreativeMusicAutomationRuntime.js","utf8");assert.match(src,/send_db:bus-vocal-parallel/);});


test("Mixer Sends exposes editable vocal parallel compression without printing the dry source",()=>{const ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicMixerSendsPanel.jsx","utf8");assert.match(ui,/Vocal Parallel Compression/);assert.match(ui,/bus-vocal-parallel/);assert.match(ui,/Threshold dB/);assert.match(ui,/Release ms/);assert.match(ui,/dry vocal remains untouched/);});
