import test from "node:test";import assert from "node:assert/strict";
import {buildProfessionalAudioDeliveryManifest,professionalAudioStemDefinition,tracksForProfessionalAudioStem} from "../lib/creative/music/runtime/CreativeProfessionalAudioEngineRuntime.js";
const tracks=[{id:"dx",audio_role:"DIALOGUE",clips:[{source_asset_id:"a-dx"}]},{id:"vo",audio_role:"VOICEOVER",clips:[{source_asset_id:"a-vo"}]},{id:"mx",audio_role:"MUSIC",clips:[{source_asset_id:"a-mx"}]},{id:"fx",audio_role:"EFFECTS",clips:[{source_asset_id:"a-fx"}]},{id:"fol",audio_role:"FOLEY",clips:[{source_asset_id:"a-fol"}]},{id:"amb",audio_role:"AMBIENCE",clips:[{source_asset_id:"a-amb"}]}];
test("professional audio engine defines explicit DX MX FX Foley Ambience and M&E roles",()=>{assert.deepEqual(professionalAudioStemDefinition("ME").roles.includes("DIALOGUE"),false);for(const id of ["DIALOGUE","MUSIC","EFFECTS","FOLEY","AMBIENCE","ME","FULL_PROGRAM"])assert.equal(professionalAudioStemDefinition(id).id,id);});
test("M&E excludes language while preserving music effects foley and ambience",()=>{const ids=tracksForProfessionalAudioStem(tracks,"ME").map(x=>x.id);assert.deepEqual(ids,["mx","fx","fol","amb"]);});
test("delivery manifest is explicit and forbids track-name role guessing",()=>{const manifest=buildProfessionalAudioDeliveryManifest({tracks});assert.equal(manifest.contract,"AVANTIQO_PROFESSIONAL_AUDIO_DELIVERY_MANIFEST_V1");assert.equal(manifest.role_inference_from_track_name_forbidden,true);const me=manifest.stems.find(x=>x.id==="ME");assert.deepEqual(me.source_asset_ids,["a-amb","a-fol","a-fx","a-mx"]);});


import fs from "node:fs";
test("multitrack sessions persist explicit professional audio roles and Workstation exposes them",()=>{const runtime=fs.readFileSync("lib/creative/music/runtime/CreativeMusicMultitrackRuntime.js","utf8"),ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicMultitrackStudioPanelV2.jsx","utf8");assert.match(runtime,/audio_role: normalizeProfessionalAudioRole/);assert.match(ui,/PROFESSIONAL_AUDIO_ROLES/);assert.match(ui,/Role <select/);});
test("canonical stem route registers governed post stems with exact role and channel lineage",()=>{const route=fs.readFileSync("app/api/creative/music/stem-render/route.js","utf8"),panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicStemExportPanel.jsx","utf8"),renderer=fs.readFileSync("lib/creative/music/client/MusicOfflineStemRenderRuntime.js","utf8");assert.match(route,/POST_STEM/);assert.match(route,/professionalAudioStemDefinition/);assert.match(route,/PROFESSIONAL_AUDIO_STEM/);assert.match(route,/professional_audio_delivery_code/);assert.match(renderer,/buildProfessionalAudioStemSession/);assert.match(panel,/Professional Audio Post stems/);assert.match(panel,/renderMusicSurroundPremasterOffline/);assert.match(panel,/Track names are never guessed/);});


test("world-class planner exposes four rooms over the shared professional audio engine",async()=>{const {buildWorldClassMusicStudioPlan,listWorldClassMusicWorkers,listWorldClassMusicCapabilities}=await import("../lib/creative/music/runtime/CreativeMusicWorldClassStudioRuntime.js");const plan=buildWorldClassMusicStudioPlan({objective:"Do full audio post and 5.1 surround sound for a commercial with dialogue, Foley and M&E delivery"});assert.equal(plan.professional_audio_engine.contract,"AVANTIQO_PROFESSIONAL_AUDIO_ENGINE_V1");assert.equal(plan.professional_audio_engine.shared_engine,true);assert.ok(plan.active_audio_rooms.includes("SOUND_DESIGN"));assert.ok(plan.active_audio_rooms.includes("AUDIO_POST"));assert.ok(plan.active_audio_rooms.includes("MASTERING_DELIVERY"));for(const id of ["supervising_sound_editor","dialogue_editor","foley_supervisor","music_editor","re_recording_mixer","delivery_engineer"])assert.ok(plan.workers.some(worker=>worker.id===id),id);for(const id of ["audio_post","surround_mix","professional_post_stems","cinematic_sound_design"])assert.ok(listWorldClassMusicCapabilities().some(cap=>cap.id===id),id);assert.ok(listWorldClassMusicWorkers().some(worker=>worker.id==="re_recording_mixer"));});


test("Studio exposes four engine-owned rooms over one shared project and workstation",()=>{const engine=fs.readFileSync("lib/creative/music/runtime/CreativeProfessionalAudioEngineRuntime.js","utf8"),workspace=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicStudioWorkspace.jsx","utf8"),shell=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicUnifiedWorkstationShell.jsx","utf8");assert.match(engine,/MUSIC_PRODUCTION/);assert.match(engine,/SOUND_DESIGN/);assert.match(engine,/AUDIO_POST/);assert.match(engine,/MASTERING_DELIVERY/);assert.match(workspace,/Avantiqo Professional Audio Studio/);assert.match(workspace,/Professional audio rooms/);assert.match(workspace,/Switching rooms never creates a second audio project/);assert.match(shell,/One project · one session/);assert.match(shell,/audioRoom/);assert.match(shell,/onRoomChange/);});
