import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {filterTrackForAudioPostLanguage,languageVersionAssetMetadata,buildAudioPostLanguageVersionManifest} from "../lib/creative/music/runtime/CreativeAudioPostVersionRuntime.js";
test("language-scoped DX keeps only clips matching selected language",()=>{const track={id:"dx",audio_role:"DIALOGUE",clips:[{id:"en",source_asset_id:"a",audio_post:{language:"en"}},{id:"th",source_asset_id:"b",audio_post:{language:"th"}}]};const en=filterTrackForAudioPostLanguage(track,"en");assert.deepEqual(en.clips.map(x=>x.id),["en"]);assert.equal(track.clips.length,2);});
test("DX VO ADR are language scoped while M&E and common stems are reusable",()=>{assert.equal(languageVersionAssetMetadata("DIALOGUE","th").delivery_language,"th");assert.equal(languageVersionAssetMetadata("DIALOGUE","th").shared_across_language_versions,false);assert.equal(languageVersionAssetMetadata("ME",null).delivery_language,null);assert.equal(languageVersionAssetMetadata("ME",null).shared_across_language_versions,true);});
test("version manifest reuses common M&E while isolating language stems",()=>{const m=buildAudioPostLanguageVersionManifest({language:"th",picture_lock_digest:"lock",project_revision:7,stems:[{stem_id:"DIALOGUE",delivery_code:"DX",asset_id:"dx-th"},{stem_id:"MUSIC",delivery_code:"MX",asset_id:"mx"},{stem_id:"ME",delivery_code:"ME",asset_id:"me"}]});assert.equal(m.language,"th");assert.equal(m.language_stems[0].asset_id,"dx-th");assert.equal(m.shared_me_asset_id,"me");assert.equal(m.common_assets_reused,true);});
test("stem renderer route UI and delivery gate carry language identity end to end",()=>{const route=fs.readFileSync("app/api/creative/music/stem-render/route.js","utf8"),panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicStemExportPanel.jsx","utf8"),delivery=fs.readFileSync("lib/creative/music/runtime/CreativeAudioPostDeliveryRuntime.js","utf8");assert.match(route,/delivery_language/);assert.match(route,/filterTrackForAudioPostLanguage/);assert.match(panel,/DX \/ VO \/ ADR are rendered from clips matching the selected language/);assert.match(delivery,/delivery_language/);assert.match(delivery,/language_version_manifest/);});


test("release render filters the full mix session and persists language on stereo and surround masters",()=>{const route=fs.readFileSync("app/api/creative/music/release-render/route.js","utf8"),panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicReleaseRenderPanel.jsx","utf8"),surround=fs.readFileSync("app/api/creative/music/surround-finish/route.js","utf8");assert.match(route,/buildAudioPostLanguageSession/);assert.match(route,/versionedSession/);assert.match(route,/delivery_language: version\.delivery_language/);assert.match(route,/CREATIVE_MUSIC_RELEASE_LANGUAGE_MISMATCH/);assert.match(panel,/renderSession/);assert.match(panel,/Only DX \/ VO \/ ADR clips matching this language enter the Full Mix/);assert.match(surround,/buildAudioPostLanguageSession/);assert.match(surround,/delivery_language:premaster\.metadata/);});

test("delivery and final QC reject a full mix from the wrong language",async()=>{const {buildAudioPostDeliveryPackage}=await import("../lib/creative/music/runtime/CreativeAudioPostDeliveryRuntime.js");const {ensureAudioPostMixBuses}=await import("../lib/creative/music/runtime/CreativeAudioPostMixRuntime.js");const session=ensureAudioPostMixBuses({revision:2,picture_lock:{picture_lock_digest:"lock",frame_rate:24,frame_count:240},spatial_audio:{layout_id:"5.1",channel_count:6,surround_enabled:true},tracks:[{id:"dx",audio_role:"DIALOGUE",spatial:{mode:"BED"},clips:[{id:"c",source_asset_id:"d",audio_post:{language:"th",speaker:"A",sync_frame:1,dialogue_edit_approved:true}}]},{id:"mx",audio_role:"MUSIC",clips:[{id:"m",source_asset_id:"m"}]}],buses:[{id:"bus-master",type:"master"}]});const stem=(code,id,sources,language=null)=>({id,metadata:{music_asset_kind:"PROFESSIONAL_AUDIO_STEM",professional_audio_delivery_code:code,delivery_language:language,project_revision:2,channels:6,channel_layout:"5.1",render_duration_seconds:10,peak_dbfs:-3,rms_dbfs:-18,clipping:false,source_assets_preserved:true,source_asset_ids:sources,destructive_edit:false}});const wrongMaster={id:"master-en",metadata:{music_asset_kind:"SURROUND_MASTER",delivery_language:"en",project_revision:2,release_candidate:true,channels:6,channel_layout:"5.1",render_duration_seconds:10,surround_validation_passed:true,surround_technical_validation:{passed:true,observed:{duration_seconds:10,stereo_downmix:{true_peak_dbtp:-1},mono_downmix:{true_peak_dbtp:-2}}}}};const r=buildAudioPostDeliveryPackage({session,assets:[stem("DX","dx-th",["d"],"th"),stem("MX","mx",["m"]),stem("ME","me",["m"]),wrongMaster],language:"th"});assert.equal(r.release_ready,false);assert.ok(r.failures.includes("AUDIO_POST_CURRENT_FULL_MIX_MASTER_REQUIRED"));});
