import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { analyzeMusicMixEngineer } from "../lib/creative/music/runtime/CreativeMusicMixEngineerRuntime.js";

function session(){return {revision:1,tracks:[
  {id:"vox",type:"vocal",name:"Lead Vocal",gain_db:0,pan:0,channel_strip:{high_pass_hz:20,presence_db:0,high_shelf_db:0,compressor:{}},clips:[{id:"cv",source_asset_id:"av",start_seconds:0,duration_seconds:20,source_offset_seconds:0}],sends:[],inserts:[]},
  {id:"gtr",type:"guitar",name:"Guitar",gain_db:0,pan:0,channel_strip:{high_pass_hz:20,presence_db:0,high_shelf_db:0,compressor:{}},clips:[{id:"cg",source_asset_id:"ag",start_seconds:0,duration_seconds:20,source_offset_seconds:0}],sends:[],inserts:[]},
  {id:"bass",type:"bass",name:"Bass",gain_db:0,pan:0,channel_strip:{high_pass_hz:20,low_shelf_db:0,presence_db:0,compressor:{}},clips:[{id:"cb",source_asset_id:"ab",start_seconds:0,duration_seconds:20,source_offset_seconds:0}],sends:[],inserts:[]},
  {id:"drums",type:"drums",name:"Drums",gain_db:0,pan:0,channel_strip:{high_pass_hz:20,low_shelf_db:0,presence_db:0,compressor:{}},clips:[{id:"cd",source_asset_id:"ad",start_seconds:0,duration_seconds:20,source_offset_seconds:0}],sends:[],inserts:[]},
],automation_lanes:[]};}
const rows=["vox","gtr","bass","drums"].map(track_id=>({track_id,measured:true,mean_db:-20,peak_dbfs:-5,crest_proxy_db:15,sub_vs_lowmid_db:0,presence_vs_lowmid_db:0,air_vs_presence_db:-3,sibilance_vs_presence_db:-5,dynamics_envelope:[]}));

test("temporal competition overrides misleading whole-track relationship proxy",()=>{const evidence={contract:"AVANTIQO_MUSIC_MIX_EVIDENCE_V5",tracks:rows,relationships:[{track_a_id:"vox",track_b_id:"gtr",presence_overlap_score:.98,level_proximity_score:.9,temporal_presence_competition_score:.2,temporal_level_proximity_score:.9,overlap_window_count:12,simultaneous_timeline_windows_measured:true,simultaneous_masking_measured:false}],simultaneous_timeline_windows_measured:true,simultaneous_masking_measured:false};const plan=analyzeMusicMixEngineer(session(),evidence);assert.equal(plan.relationship_decisions.some(x=>x.type==="VOCAL_TEMPORAL_COMPETITION"),false);});

test("strong synchronized vocal and low-end competition creates bounded decisions",()=>{const evidence={contract:"AVANTIQO_MUSIC_MIX_EVIDENCE_V5",tracks:rows,relationships:[{track_a_id:"vox",track_b_id:"gtr",presence_overlap_score:.2,level_proximity_score:.2,temporal_presence_competition_score:.85,temporal_level_proximity_score:.8,overlap_window_count:18,simultaneous_timeline_windows_measured:true,simultaneous_masking_measured:false},{track_a_id:"bass",track_b_id:"drums",low_overlap_score:.2,level_proximity_score:.2,temporal_low_competition_score:.82,temporal_level_proximity_score:.75,overlap_window_count:20,simultaneous_timeline_windows_measured:true,simultaneous_masking_measured:false}],simultaneous_timeline_windows_measured:true,simultaneous_masking_measured:false};const plan=analyzeMusicMixEngineer(session(),evidence);assert.ok(plan.relationship_decisions.some(x=>x.type==="VOCAL_TEMPORAL_COMPETITION"));assert.ok(plan.relationship_decisions.some(x=>x.type==="LOW_END_TEMPORAL_COMPETITION"));const gtr=plan.track_decisions.find(x=>x.track_id==="gtr"),bass=plan.track_decisions.find(x=>x.track_id==="bass");assert.equal(gtr.gain_db,-.5);assert.equal(gtr.channel_strip.presence_db,-1);assert.ok(bass.channel_strip.low_shelf_db<=.25);assert.equal(plan.simultaneous_masking_measured,false);});

test("evidence runtime measures band envelopes on real clip timeline without claiming masking",()=>{const source=fs.readFileSync(new URL("../lib/creative/music/runtime/CreativeMusicMixEvidenceRuntime.js",import.meta.url),"utf8");assert.match(source,/presence_envelope/);assert.match(source,/low_envelope/);assert.match(source,/TEMPORAL_SPECTRAL_COMPETITION/);assert.match(source,/source_offset_seconds/);assert.match(source,/psychoacoustic_masking_measured:false/);});

test("Workstation labels temporal spectral competition precisely",()=>{const source=fs.readFileSync(new URL("../components/creative/ProductionStudio/workspaces/MusicMixEngineerPanel.jsx",import.meta.url),"utf8");assert.match(source,/synchronized windows/i);assert.match(source,/temporal spectral competition/i);assert.match(source,/not psychoacoustic masking/i);});
