import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildMusicMixAutomationPlan, applyMusicMixAutomationPlan } from "../lib/creative/music/runtime/CreativeMusicMixAutomationRuntime.js";

const session={bpm:120,time_signature:"4/4",tempo_map:{contract:"AVANTIQO_MUSIC_TEMPO_MAP_V2",tempo_events:[{contract:"AVANTIQO_MUSIC_TEMPO_EVENT_V1",id:"t0",beat:0,bpm:120,curve:"step"}],meter_events:[{contract:"AVANTIQO_MUSIC_METER_EVENT_V1",id:"m0",beat:0,time_signature:"4/4"}],non_destructive:true,exact_linear_ramp_integration:true},tracks:[{id:"vox",type:"vocal",name:"Lead Vocal",gain_db:-3,mute:false},{id:"keys",type:"keys",name:"Keys",gain_db:-5,mute:false}],automation_lanes:[]};
const arrangement={sections:[{id:"v",type:"verse",start_beat:0,end_beat:16,intensity:.5},{id:"c",type:"chorus",start_beat:16,end_beat:32,intensity:.9},{id:"o",type:"outro",start_beat:32,end_beat:40,intensity:.3}]};

test("mix automation creates bounded section-aware vocal and support rides",()=>{const plan=buildMusicMixAutomationPlan(session,arrangement);assert.equal(plan.status,"AUTOMATION_PLAN_READY");assert.equal(plan.section_count,3);const vocal=plan.lanes.find(x=>x.target_id==="vox");const keys=plan.lanes.find(x=>x.target_id==="keys");assert.ok(vocal);assert.ok(keys);assert.ok(vocal.points.every(p=>p.value>=-3.5&&p.value<=-2.2));assert.ok(keys.points.every(p=>p.value>=-5.4&&p.value<=-4.8));const next=applyMusicMixAutomationPlan(session,plan);assert.equal(next.automation_lanes.length,2);assert.equal(next.automation_lanes[0].destructive_processing_allowed,false);});

test("manual gain automation is preserved and blocks automatic replacement",()=>{const withManual=structuredClone(session);withManual.automation_lanes=[{contract:"AVANTIQO_MUSIC_MIXER_AUTOMATION_V1",id:"human-vocal-ride",target_type:"track",target_id:"vox",parameter:"gain_db",interpolation:"linear",enabled:true,points:[{time_seconds:0,value:-3},{time_seconds:10,value:-2.5}],destructive_processing_allowed:false}];const plan=buildMusicMixAutomationPlan(withManual,arrangement);assert.equal(plan.lanes.find(x=>x.target_id==="vox").blocked_by_existing_manual_lane,true);const next=applyMusicMixAutomationPlan(withManual,plan);assert.equal(next.automation_lanes.find(x=>x.target_id==="vox").id,"human-vocal-ride");});

test("Mix Engineer UI exposes section automation truthfully",()=>{const source=fs.readFileSync(new URL("../components/creative/ProductionStudio/workspaces/MusicMixEngineerPanel.jsx",import.meta.url),"utf8");assert.match(source,/Section automation/);assert.match(source,/manual gain automation is never overwritten/i);assert.match(source,/Reverb\/delay movement is not generated/);});
