import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {resolveProfessionalAudioDeliveryProfile,validateProfessionalAudioDeliveryProfile} from "../lib/creative/music/runtime/CreativeProfessionalAudioDeliveryProfileRuntime.js";
test("professional delivery profiles separate music release picture post broadcast and cinema handoffs",()=>{for(const id of ["music_release","picture_post","broadcast_handoff","cinema_handoff"])assert.equal(resolveProfessionalAudioDeliveryProfile(id).id,id);assert.equal(resolveProfessionalAudioDeliveryProfile("picture_post").bwf_required,true);assert.deepEqual(resolveProfessionalAudioDeliveryProfile("cinema_handoff").allowed_layouts,["5.1","7.1"]);assert.equal(resolveProfessionalAudioDeliveryProfile("cinema_handoff").dolby_branding,false);});
test("picture/broadcast/cinema profiles fail closed on missing picture lock or incompatible format",()=>{const r=validateProfessionalAudioDeliveryProfile({session:{sample_rate:44100,spatial_audio:{layout_id:"stereo"}},profile:"cinema_handoff",mastering:{target_lufs:-20,true_peak_dbtp:-2}});assert.equal(r.success,false);assert.ok(r.failures.includes("DELIVERY_PROFILE_PICTURE_LOCK_REQUIRED"));assert.ok(r.failures.includes("DELIVERY_PROFILE_SAMPLE_RATE_REQUIRED:48000"));assert.ok(r.failures.includes("DELIVERY_PROFILE_LAYOUT_NOT_ALLOWED:stereo"));});
test("broadcast/cinema require explicit loudness targets instead of pretending one global target",()=>{const session={sample_rate:48000,picture_lock:{picture_lock_digest:"p"},spatial_audio:{layout_id:"5.1"}};const bad=validateProfessionalAudioDeliveryProfile({session,profile:"broadcast_handoff",mastering:{}});assert.ok(bad.failures.includes("DELIVERY_PROFILE_EXPLICIT_LOUDNESS_TARGET_REQUIRED"));const good=validateProfessionalAudioDeliveryProfile({session,profile:"broadcast_handoff",mastering:{target_lufs:-23,true_peak_dbtp:-1}});assert.equal(good.success,true);});
test("release plan assets and Studio carry delivery-profile identity end to end",()=>{const plan=fs.readFileSync("lib/creative/music/runtime/CreativeMusicReleaseRenderPlanRuntime.js","utf8"),release=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicReleaseRenderPanel.jsx","utf8"),stem=fs.readFileSync("app/api/creative/music/stem-render/route.js","utf8");assert.match(plan,/delivery_profile_validation/);assert.match(release,/Delivery profile/);assert.match(release,/deliveryProfileId/);assert.match(stem,/delivery_profile_id/);});


test("Studio exposes explicit LUFS/true-peak fields for broadcast and cinema profiles",()=>{const ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicReleaseRenderPanel.jsx","utf8");assert.match(ui,/Target LUFS/);assert.match(ui,/True peak dBTP/);assert.match(ui,/does not silently assume one global regional standard/);});
test("final QC seal package and version matrix preserve delivery-profile identity",()=>{for(const file of ["lib/creative/music/runtime/CreativeAudioPostFinalQcRuntime.js","lib/creative/music/runtime/CreativeAudioPostDeliveryRuntime.js","lib/creative/music/runtime/CreativeAudioPostPackageManifestRuntime.js","lib/creative/music/runtime/CreativeAudioPostVersionMatrixRuntime.js"])assert.match(fs.readFileSync(file,"utf8"),/delivery_profile/);});
