import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {buildMusicVocalProductionBuses,inspectMusicVocalProduction} from "../lib/creative/music/runtime/CreativeMusicVocalProductionBusRuntime.js";
function session(){return{tracks:[{id:"lead",type:"vocal",name:"Lead",vocal_role:"LEAD",output_bus_id:"bus-master",sends:[]},{id:"dbl",type:"vocal",name:"Double",vocal_role:"DOUBLE",output_bus_id:"bus-master",sends:[]},{id:"harm",type:"vocal",name:"Harmony",vocal_role:"HARMONY",output_bus_id:"bus-master",sends:[]}],buses:[{id:"bus-master",type:"master",name:"Master",gain_db:0,pan:0,mute:false,solo:false}],automation_lanes:[]};}
test("professional vocal routing builds explicit lead double harmony hierarchy into one vocal master",()=>{const r=buildMusicVocalProductionBuses(session());assert.equal(r.success,true);for(const id of ["bus-vocal-all","bus-vocal-lead","bus-vocal-double","bus-vocal-harmony"])assert.ok(r.session.buses.some(bus=>bus.id===id&&bus.vocal_production_managed===true));assert.equal(r.session.tracks.find(t=>t.id==="lead").output_bus_id,"bus-vocal-lead");assert.equal(r.session.tracks.find(t=>t.id==="dbl").output_bus_id,"bus-vocal-double");assert.equal(r.source_audio_rewritten,false);assert.equal(r.human_listening_review_required,true);});
test("vocal production refuses undeclared roles and requires an explicit lead",()=>{const s=session();s.tracks[0].vocal_role=null;let r=buildMusicVocalProductionBuses(s);assert.equal(r.success,false);assert.ok(r.failures.some(x=>x.startsWith("VOCAL_PRODUCTION_ROLE_REQUIRED")));s.tracks[0].vocal_role="BACKING";r=buildMusicVocalProductionBuses(s);assert.equal(r.success,false);assert.ok(r.failures.includes("VOCAL_PRODUCTION_LEAD_REQUIRED"));});
test("manual reverb or delay sends are preserved rather than overwritten",()=>{const s=session();s.tracks[0].sends=[{id:"human",bus_id:"bus-reverb",level_db:-11,enabled:true,pre_fader:false}];const r=buildMusicVocalProductionBuses(s);assert.equal(r.success,true);assert.equal(r.session.tracks[0].sends.find(x=>x.bus_id==="bus-reverb").level_db,-11);assert.ok(r.manual_send_preservation.some(x=>x.track_id==="lead"&&x.bus_id==="bus-reverb"&&x.manual_send_preserved));});
test("QC reports declared-role and managed-bus readiness",()=>{const built=buildMusicVocalProductionBuses(session()),qc=inspectMusicVocalProduction(built.session);assert.equal(qc.professional_vocal_routing_ready,true);assert.equal(qc.vocal_track_count,3);assert.equal(qc.lead_track_count,1);assert.ok(qc.managed_bus_count>=4);assert.equal(qc.pitch_timing_correction_separately_certification_gated,true);});
test("Studio exposes explicit vocal role assignment and governed build action",()=>{const workstation=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicMultitrackStudioPanelV2.jsx","utf8"),mix=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicMixEngineerPanel.jsx","utf8"),route=fs.readFileSync("app/api/creative/music/multitrack/route.js","utf8");assert.match(workstation,/Assign role/);assert.match(workstation,/DOUBLE/);assert.match(mix,/Build vocal production/);assert.match(route,/apply_vocal_production/);});


test("world-class registry distinguishes implemented vocal production from certification-gated correction",()=>{const registry=fs.readFileSync("lib/creative/music/runtime/CreativeMusicWorldClassStudioRuntime.js","utf8"),auto=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicAutoStudioPanel.jsx","utf8");assert.match(registry,/professional_vocal_production/);assert.match(registry,/creative\.music\.vocal-production/);assert.match(registry,/pitch_tuning[\s\S]*CERTIFICATION_GATED/);assert.match(auto,/Vocal production/);assert.match(auto,/CERTIFICATION GATED/);assert.doesNotMatch(auto,/label: "Vocal engineering"[\s\S]*status: "PARTIAL"/);});


test("role-aware vocal placement anchors lead and spreads real doubles/harmonies without Haas widening",()=>{const s={tracks:[{id:"lead",type:"vocal",vocal_role:"LEAD",pan:0,sends:[]},{id:"d1",type:"vocal",vocal_role:"DOUBLE",pan:0,sends:[]},{id:"d2",type:"vocal",vocal_role:"DOUBLE",pan:0,sends:[]},{id:"h1",type:"vocal",vocal_role:"HARMONY",pan:0,sends:[]},{id:"h2",type:"vocal",vocal_role:"HARMONY",pan:0,sends:[]}],buses:[{id:"bus-master",type:"master",name:"Master",gain_db:0,pan:0,mute:false,solo:false}],automation_lanes:[]},r=buildMusicVocalProductionBuses(s),by=new Map(r.session.tracks.map(t=>[t.id,t]));assert.equal(by.get("lead").pan,0);assert.equal(by.get("d1").pan,-.38);assert.equal(by.get("d2").pan,.38);assert.equal(by.get("h1").pan,-.28);assert.equal(by.get("h2").pan,.28);assert.equal(r.artificial_phase_widening_forbidden,true);assert.equal(r.haas_delay_widening_forbidden,true);});
test("existing engineer pan is preserved and never recentered by vocal production",()=>{const s=session();s.tracks[1].pan=.63;const r=buildMusicVocalProductionBuses(s),track=r.session.tracks.find(t=>t.id==="dbl");assert.equal(track.pan,.63);assert.equal(track.vocal_production.manual_pan_preserved,true);assert.ok(r.pan_placement.some(x=>x.track_id==="dbl"&&x.manual_pan_preserved));});
