import test from 'node:test';
import assert from 'node:assert/strict';
import { buildCanonicalPreproductionEvidence } from '../lib/creative/production-room/runtime/CreativeCanonicalPreproductionEvidenceRuntime.js';

test('canonical preproduction evidence derives workstreams from authored shot truth without provider calls', () => {
  const shot={id:'shot-a',subject:'worker and machine',subject_class:'HUMAN',subject_identity_key:'person-a',action:'Worker completes the authored machine check and records the result.',purpose:'Show a complete real action and consequence.',duration_seconds:4,scene_location:{city:'Test City',context:'Workshop'},camera:{focus_target:'worker hands',focus_transition:'hold on hands',platform:'tripod',stabilization:'tripod',movement_path:'locked',framing:'close detail'},virtual_camera_state:{start:{camera_height_m:1.5},end:{camera_height_m:1.5}},lighting:{source:'window daylight',direction:'camera left',contrast:'medium contrast',colour:'neutral daylight',exposure_intent:'protect hands and machine detail'},production_design:{environment:'working workshop',props:'inspection sheet',wardrobe:'work clothes',materials:'steel and paper',texture_detail:'worn steel surface'},material_behavior:'Steel remains rigid and paper remains stable under contact.',continuity_invariants:['same worker','same machine'],subject_motion_choreography:{path:'hands move from control to inspection sheet',clearance_and_contact_constraints:['no hand-machine interpenetration']},audio:{source_sound:'machine click',sound_effects:['paper movement'],spatial_field:'machine left',mix_intent:'machine click foreground',silence:'brief pause'},vfx:[],transition_out:'cut after inspection mark',known_failure_modes:['wrong worker identity'],repair_instructions:'repair only failed identity or contact detail'};
  const plan={workflow_kind:'TEMPORAL',temporal_contract:{duration_seconds:4},story_lineage:{master_plan_hash:'master-a'},creative_tribunal:{passed:true},validation:{passed:true},concept:{title:'Test'},scenes:[{id:'scene-a',location:shot.scene_location,shots:[shot]}],deliverables:[{format:'VIDEO'}]};
  const research_report={evidence:{source_manifest:[{source_id:'a'},{source_id:'b'}],location_findings:{verified:true},cultural_findings:{verified:true},technical_findings:{verified:true},weather_daylight_findings:{deferred:true},open_questions:['No unresolved research questions remain after source review.']}};
  const department_breakdown={take_strategy:{max_takes_per_shot:2},shot_assignments:[{shot_id:'shot-a',unit_ids:['PRIMARY_UNIT'],coverage_purpose:shot.purpose}],units:[{unit_id:'PRIMARY_UNIT',shot_ids:['shot-a']}]};
  const result=buildCanonicalPreproductionEvidence({plan,research_report,department_breakdown});
  for(const requirement of [1,2,3,4,5,6,7,8,9,10,12,13,14,16,18,19]) assert.equal(result.reports_by_requirement[requirement].passed,true,`requirement ${requirement}: ${result.reports_by_requirement[requirement].failures.join(',')}`);
  assert.equal(result.zero_provider_calls,true);
  assert.equal(result.zero_media_generation,true);
});
