import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildMusicImmersiveScene, validateMusicImmersiveScene } from "../lib/creative/music/runtime/CreativeMusicImmersiveSceneRuntime.js";
import { encodeMusicPointSourceToFoa, sumMusicFoaBeds, decodeMusicFoaToStereo } from "../lib/creative/music/client/MusicFirstOrderAmbisonicRenderRuntime.js";

test("canonical immersive scene separates object tracks from bed tracks without Dolby branding",()=>{const session={id:"s1",revision:3,picture_lock:{picture_lock_digest:"pic"},tracks:[{id:"obj",name:"Car",audio_role:"EFFECTS",spatial:{mode:"POINT",azimuth_degrees:30,elevation_degrees:15,distance_meters:8,immersive:{doppler_enabled:true}}},{id:"bed",name:"Music",audio_role:"MUSIC",spatial:{mode:"BED"}}],sound_objects:[{id:"car-object",assigned_track_id:"obj",picture_object_id:"car-visual",name:"Hero car"}]};const scene=buildMusicImmersiveScene(session);assert.equal(scene.object_count,1);assert.equal(scene.bed_count,1);assert.equal(scene.objects[0].picture_object_id,"car-visual");assert.deepEqual(scene.ambisonic_master.channel_labels,["W","Y","Z","X"]);assert.equal(scene.ambisonic_master.normalization,"SN3D");assert.equal(scene.adm.authoring_enabled,false);assert.equal(validateMusicImmersiveScene(scene).passed,true);});

test("FOA point encoder uses ACN/SN3D B-format and preserves height component",()=>{const mono=new Float32Array([1,0.5,-0.25]),r=encodeMusicPointSourceToFoa({mono,azimuth_degrees:90,elevation_degrees:30});assert.deepEqual(r.channel_order,["W","Y","Z","X"]);assert.deepEqual(r.acn_order,[0,1,2,3]);assert.equal(r.normalization,"SN3D");assert.ok(Math.abs(r.channels[2][0])>0.49);assert.ok(Math.abs(r.channels[1][0])>0.8);assert.ok(Math.abs(r.channels[3][0])<0.001);});

test("FOA scene can sum multiple sound objects and derive stereo without mutating scene master",()=>{const a=encodeMusicPointSourceToFoa({mono:new Float32Array([1,1]),azimuth_degrees:-45}),b=encodeMusicPointSourceToFoa({mono:new Float32Array([0.5,0.5]),azimuth_degrees:45}),sum=sumMusicFoaBeds([a,b]),stereo=decodeMusicFoaToStereo(sum);assert.equal(sum.channels.length,4);assert.equal(stereo.left.length,2);assert.equal(stereo.right.length,2);assert.equal(stereo.height_component_preserved_in_scene,true);assert.equal(stereo.height_collapsed_for_stereo,true);});

test("spatial and final surround renderers expose one canonical ambisonic scene while ADM remains disabled",()=>{const spatial=fs.readFileSync("lib/creative/music/runtime/CreativeMusicSpatialAudioRuntime.js","utf8"),surround=fs.readFileSync("lib/creative/music/client/MusicOfflineSurroundRenderRuntime.js","utf8");assert.match(spatial,/canonical_object_scene_enabled: true/);assert.match(spatial,/ambisonic_master_enabled: true/);assert.match(spatial,/ambisonic_channel_order: "ACN"/);assert.match(spatial,/ambisonic_normalization: "SN3D"/);assert.match(spatial,/atmos_adm_bwf_authoring_enabled: false/);assert.match(surround,/immersive_scene: immersiveScene/);});
