import test from "node:test";import assert from "node:assert/strict";
import {createMusicPictureLock} from "../lib/creative/music/runtime/CreativeMusicPictureLockRuntime.js";
import {buildMusicCinematicSoundObjectPlan,createMusicCinematicSoundObject,soundObjectLayerReadiness,soundObjectSpatialAutomationLanes} from "../lib/creative/music/runtime/CreativeMusicCinematicSoundObjectRuntime.js";

test("vehicle sound object carries Deenen-style layered source architecture without auto-generating layers",()=>{const o=createMusicCinematicSoundObject({id:"car1",category:"VEHICLE",start_seconds:1,duration_seconds:3,frame_rate:24,picture_object_id:"lambo",spatial_path:{mode:"FOLLOW_PICTURE_OBJECT",start_azimuth_degrees:-110,end_azimuth_degrees:110}});assert.equal(o.contract,"AVANTIQO_MUSIC_CINEMATIC_SOUND_OBJECT_V1");for(const type of ["PRODUCTION_SOURCE","MECHANICAL","BODY","TRANSIENT","SUB_LFE","ENVIRONMENT","CHARACTER_SWEETENER"])assert.ok(o.layers.some(x=>x.type===type));assert.equal(o.governance.automatic_layer_generation_authority,false);assert.equal(o.start_timecode,"00:00:01:00");assert.equal(o.end_timecode,"00:00:04:00");});
test("picture-locked sound-object plan preserves cue-sheet lineage",()=>{const lock=createMusicPictureLock({picture_asset_id:"v1",cut_id:"c1",picture_digest:"sha",duration_seconds:10,frame_rate:24});const plan=buildMusicCinematicSoundObjectPlan({picture_lock:lock,cue_sheet_hash:"cuehash",cues:[{id:"hit",category:"IMPACT",start_seconds:2,duration_seconds:.2}]});assert.equal(plan.picture_lock_digest,lock.picture_lock_digest);assert.equal(plan.cue_sheet_hash,"cuehash");assert.equal(plan.automatic_generation_started,false);assert.equal(plan.objects[0].cue_sheet_hash,"cuehash");});
test("moving sound object creates exact spatial automation lanes on assigned track",()=>{const o=createMusicCinematicSoundObject({id:"heli",category:"MACHINERY",start_seconds:2,end_seconds:5,duration_seconds:3,spatial_path:{mode:"MOVE",start_azimuth_degrees:-90,end_azimuth_degrees:140,width_percent:35}});const lanes=soundObjectSpatialAutomationLanes(o,"track-heli");assert.equal(lanes[0].contract,"AVANTIQO_MUSIC_MIXER_AUTOMATION_V2");assert.equal(lanes[0].parameter,"spatial:azimuth_degrees");assert.deepEqual(lanes[0].points.map(x=>x.value),[-90,140]);assert.ok(lanes.some(x=>x.parameter==="spatial:width_percent"));});
test("required source layers fail readiness until real assets are attached",()=>{const o=createMusicCinematicSoundObject({category:"IMPACT"});const before=soundObjectLayerReadiness(o);assert.equal(before.ready,false);o.layers.forEach((layer,i)=>{layer.asset_id=`asset-${i}`;});const after=soundObjectLayerReadiness(o);assert.equal(after.ready,true);assert.equal(after.automatic_waiver_allowed,false);});

import {buildMusicCinematicCuesFromDirector,buildMusicSoundObjectPlanFromDirector} from "../lib/creative/music/runtime/CreativeMusicCinematicCueBridgeRuntime.js";
test("Director shot-relative sync events and absolute Foley bind to one picture clock without semantic guessing",()=>{const lock=createMusicPictureLock({picture_asset_id:"v1",cut_id:"c1",picture_digest:"sha",duration_seconds:10,frame_rate:24});const director={duration_seconds:10,cue_sheet_hash:"hash1",cues:[{cue_id:"s1:q1",shot_id:"q1",timeline_in_seconds:2,timeline_out_seconds:5,duration_seconds:3,sync_events:[{at_seconds:.5,event:"metallic pass"}],ambience:"tunnel air",sound_effects:["complex tonal signature"]}]};const foley={picture_duration_seconds:10,events:[{id:"step1",category:"FOOTSTEP",start_seconds:6,duration_seconds:.1,description:"shoe hit",sync_tolerance_ms:20,perspective:"ON_SCREEN"}]};const bridge=buildMusicCinematicCuesFromDirector({picture_lock:lock,director_cue_sheet:director,foley_plan:foley});assert.equal(bridge.director_sync_event_time_basis,"SHOT_RELATIVE");assert.equal(bridge.foley_time_basis,"PICTURE_ABSOLUTE");assert.equal(bridge.cues.find(x=>x.id.includes(":sync:"))?.start_seconds,2.5);assert.equal(bridge.cues.find(x=>x.name==="complex tonal signature")?.category,"CUSTOM");assert.equal(bridge.cues.find(x=>x.name==="shoe hit")?.category,"FOOTSTEP");const plan=buildMusicSoundObjectPlanFromDirector({picture_lock:lock,director_cue_sheet:director,foley_plan:foley});assert.equal(plan.picture_lock_digest,lock.picture_lock_digest);assert.equal(plan.cue_sheet_hash,"hash1");});
