import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {normalizeMusicImmersiveObject,immersivePositionFromAngles,dopplerPlaybackRate} from "../lib/creative/music/runtime/CreativeMusicImmersiveObjectRuntime.js";
import {mapVehicleRpmToPitch,firingFrequencyFromRpm} from "../lib/creative/music/runtime/CreativeVehicleAcousticMathRuntime.js";
import {evaluateMusicSoundDesignPreparation} from "../lib/creative/music/runtime/CreativeMusicSoundDesignPreparationRuntime.js";
test("immersive objects model position distance elevation Doppler reflections and binaural without Dolby branding",()=>{const o=normalizeMusicImmersiveObject({azimuth_degrees:45,elevation_degrees:20,distance_meters:8,doppler_enabled:true,reflections_enabled:true});assert.equal(o.object_based,true);assert.equal(o.binaural_monitor_enabled,true);assert.equal(o.dolby_branded,false);assert.equal(o.hrtf_mode,"BROWSER_HRTF");const p=immersivePositionFromAngles(o);assert.ok(p.x>0);assert.ok(p.y>0);assert.ok(p.z<0);assert.notEqual(dopplerPlaybackRate({source_velocity_mps:30}),1);});
test("vehicle RPM model maps four-stroke combustion event frequency to musical pitch but does not claim measured identity",()=>{assert.equal(firingFrequencyFromRpm({rpm:4000,cylinders:8,strokes:4}),266.6666666666667);const r=mapVehicleRpmToPitch({rpm:4000,cylinders:8,strokes:4});assert.equal(r.measured_audio_required_for_exact_engine_pitch,true);assert.ok(r.note);});
test("binaural renderer uses WebAudio HRTF and object path remains separate from dry source analysis",()=>{const source=fs.readFileSync("lib/creative/music/client/MusicImmersiveBinauralRenderRuntime.js","utf8"),object=fs.readFileSync("lib/creative/music/runtime/CreativeMusicCinematicSoundObjectRuntime.js","utf8");assert.match(source,/panningModel="HRTF"/);assert.match(source,/dopplerPlaybackRate/);assert.match(source,/reflections_applied/);assert.match(object,/start_distance_meters/);assert.match(object,/spatial:elevation_degrees/);assert.match(object,/spatial:distance_meters/);});
test("Sound Design exposes vehicle source analysis and immersive controls",()=>{const ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicSoundDesignObjectPanel.jsx","utf8"),route=fs.readFileSync("app/api/creative/music/vehicle-acoustics/route.js","utf8");assert.match(ui,/Vehicle acoustic intelligence/);assert.match(ui,/Analyze prepared/);assert.match(ui,/Immersive object audio/);assert.match(ui,/Doppler/);assert.match(ui,/Reflections/);assert.match(route,/analyze_asset/);assert.match(route,/rpm_pitch/);});
test("world-class planner advertises immersive object audio and vehicle acoustic analysis",()=>{const source=fs.readFileSync("lib/creative/music/runtime/CreativeMusicWorldClassStudioRuntime.js","utf8");assert.match(source,/immersive_object_audio/);assert.match(source,/vehicle_acoustic_analysis/);assert.match(source,/8d sound/);});


test("immersive readiness enforces dry-prep then measured vehicle analysis on the exact prepared asset",()=>{const object={id:"car",category:"VEHICLE",layers:[{asset_id:"raw"}],source_preparation:{parent_source_asset_id:"raw",prepared_asset_id:"dry"},vehicle_acoustics:{source_asset_id:"dry",analysis:{measured:true}}};assert.equal(evaluateMusicSoundDesignPreparation(object).immersive_ready,true);object.vehicle_acoustics.source_asset_id="old";const stale=evaluateMusicSoundDesignPreparation(object);assert.equal(stale.immersive_ready,false);assert.ok(stale.failures.includes("SOUND_DESIGN_VEHICLE_ANALYSIS_SOURCE_STALE"));});
test("vehicle route and Sound Design UI expose non-destructive dry preparation before analysis",()=>{const route=fs.readFileSync("app/api/creative/music/vehicle-acoustics/route.js","utf8"),ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicSoundDesignObjectPanel.jsx","utf8");assert.match(route,/action==="prepare_source"/);assert.match(route,/sound_design_parent_asset_id/);assert.match(route,/spatial_processing_applied:false/);assert.match(ui,/Prepare dry source/);assert.match(ui,/Analyze prepared/);assert.match(ui,/Immersive readiness/);});
