import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {ensureAudioPostMixBuses,validateAudioPostMix} from "../lib/creative/music/runtime/CreativeAudioPostMixRuntime.js";
import {applyMusicLinkedMultichannelSidechain} from "../lib/creative/music/client/MusicMultichannelDspRuntime.js";
test("Audio Post mix creates canonical DX VO ADR MX FX Foley and Ambience buses without name guessing",()=>{const session=ensureAudioPostMixBuses({tracks:[{id:"d",audio_role:"DIALOGUE"},{id:"m",audio_role:"MUSIC"},{id:"x",audio_role:"EFFECTS"}],buses:[{id:"bus-master",type:"master"}]});assert.equal(session.tracks.find(x=>x.id==="d").output_bus_id,"bus-post-dx");assert.equal(session.tracks.find(x=>x.id==="m").output_bus_id,"bus-post-mx");assert.ok(session.buses.some(x=>x.id==="bus-post-fx"));assert.equal(session.audio_post_mix.dialogue_priority,true);});
test("surround dialogue tracks fail closed when routed to LFE or not centered enough",()=>{const session=ensureAudioPostMixBuses({spatial_audio:{layout_id:"5.1",surround_enabled:true},tracks:[{id:"d",audio_role:"DIALOGUE",spatial:{mode:"BED"}}],buses:[{id:"bus-master",type:"master"}]});session.tracks[0].spatial.center_send_db=-30;session.tracks[0].spatial.lfe_send_db=-6;const r=validateAudioPostMix(session);assert.equal(r.success,false);assert.ok(r.failures.includes("AUDIO_POST_DIALOGUE_CENTER_SEND_LOW:d"));assert.ok(r.failures.includes("AUDIO_POST_DIALOGUE_LFE_FORBIDDEN:d"));});
test("linked multichannel sidechain ducks all target speakers by identical gain",()=>{const frames=4000,key=[new Float32Array(frames).fill(.8),new Float32Array(frames).fill(.8)],a=Float32Array.from({length:frames},(_,i)=>Math.sin(i*.07)*.4),b=Float32Array.from(a,v=>v*.2);const r=applyMusicLinkedMultichannelSidechain([a,b],key,48000,{threshold_dbfs:-30,ratio:4,attack_ms:1,release_ms:50,max_reduction_db:6});assert.equal(r.sidechain_applied,true);assert.ok(r.gain_reduction_db_min<0);let n=0;for(let i=100;i<frames;i++){if(Math.abs(r.channels[0][i])<1e-6)continue;assert.ok(Math.abs(r.channels[1][i]/r.channels[0][i]-.2)<1e-5);n++;}assert.ok(n>1000);});
test("Audio Post room has dedicated re-recording mix surface contract",()=>{const shell=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicUnifiedWorkstationShell.jsx","utf8"),panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicAudioPostMixPanel.jsx","utf8"),renderer=fs.readFileSync("lib/creative/music/client/MusicOfflineSurroundRenderRuntime.js","utf8");assert.match(shell,/MusicAudioPostMixPanel/);assert.match(panel,/Re-recording Mix/);assert.match(panel,/Dialogue priority/);assert.match(panel,/Save post mix/);assert.match(renderer,/applyMusicLinkedMultichannelSidechain/);assert.match(renderer,/dialogue_ducking_applied/);});


test("stereo offline renderer uses real two-input dialogue sidechain worklet",()=>{const graph=fs.readFileSync("lib/creative/music/client/MusicGroupBusPreviewGraph.js","utf8"),render=fs.readFileSync("lib/creative/music/client/MusicOfflineMixRenderRuntime.js","utf8"),worklet=fs.readFileSync("public/audio/avantiqo-music-dynamics-worklet.js","utf8");assert.match(graph,/numberOfInputs: 2/);assert.match(graph,/avantiqo-dialogue-sidechain/);assert.match(graph,/keyInput\.connect\(sidechain, 0, 1\)/);assert.match(render,/audio_post_dialogue_ducking_applied/);assert.match(worklet,/AvantiqoDialogueSidechainProcessor/);});
test("server validates persisted Audio Post re-recording mix policy",()=>{const route=fs.readFileSync("app/api/creative/music/multitrack/route.js","utf8");assert.match(route,/validateAudioPostMix/);assert.match(route,/CREATIVE_AUDIO_POST_MIX_INVALID/);});
