import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {buildMusicVocalProductionBuses} from "../lib/creative/music/runtime/CreativeMusicVocalProductionBusRuntime.js";
import {evaluateMusicVocalProductionQc} from "../lib/creative/music/runtime/CreativeMusicVocalProductionQcRuntime.js";
function evidence(asset="a"){return{contract:"AVANTIQO_MUSIC_VOCAL_ENGINEERING_EVIDENCE_V1",source_asset_id:asset,source_offset_seconds:0,source_duration_seconds:2,source_audio_measured:true,measured:{source_mean_db:-20,source_peak_dbfs:-3,body_vs_presence_db:1,sibilance_vs_presence_db:8,rumble_vs_body_db:-15,body_dominant:false,presence_deficit:false,sibilance_elevated:true,sub_rumble_elevated:false},performance:{active_dynamic_range_db:8,median_crest_db:5,dynamics_windows:[],sibilant_event_candidates:[],air_noise_event_candidates:[],breath_events_confirmed:false,signal_proxy_only:true}};}
function session(){const base={tracks:[{id:"lead",type:"vocal",vocal_role:"LEAD",name:"Lead",pan:0,sends:[],clips:[{id:"c1",source_asset_id:"a",source_offset_seconds:0,duration_seconds:2,muted:false,vocal_engineering_evidence:evidence("a")}]}],buses:[{id:"bus-master",type:"master",name:"Master",gain_db:0,pan:0,mute:false,solo:false}],automation_lanes:[]};return buildMusicVocalProductionBuses(base).session;}
test("QC passes structural/evidence gate but keeps measured sibilance as listening review flag",()=>{const q=evaluateMusicVocalProductionQc(session());assert.equal(q.technical_ready_for_listening_review,true);assert.equal(q.release_certified,false);assert.equal(q.artistic_quality_inferred,false);assert.ok(q.review_flags.some(x=>x.code==="VOCAL_SIBILANCE_ELEVATED"));});
test("QC fails closed when an audible vocal clip has no current engineering evidence",()=>{const s=session();delete s.tracks[0].clips[0].vocal_engineering_evidence;const q=evaluateMusicVocalProductionQc(s);assert.equal(q.technical_ready_for_listening_review,false);assert.ok(q.blockers.some(x=>x.startsWith("VOCAL_CURRENT_ENGINEERING_EVIDENCE_REQUIRED")));});
test("QC blocks phase-widening claims instead of accepting mono-risk tricks",()=>{const s=session();s.tracks[0].vocal_production.haas_delay_used=true;const q=evaluateMusicVocalProductionQc(s);assert.equal(q.technical_ready_for_listening_review,false);assert.ok(q.blockers.some(x=>x.startsWith("VOCAL_PHASE_WIDENING_FORBIDDEN")));});
test("multitrack API and Mix Engineer surface the vocal QC gate",()=>{const route=fs.readFileSync("app/api/creative/music/multitrack/route.js","utf8"),ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicMixEngineerPanel.jsx","utf8");assert.match(route,/vocal_production_qc/);assert.match(route,/evaluateMusicVocalProductionQc/);assert.match(ui,/Vocal QC/);assert.match(ui,/No artistic quality score/);});
