import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {buildAudioPostDialogueMatchPlan,approveAudioPostDialogueMatch} from "../lib/creative/music/runtime/CreativeAudioPostDialogueMatchRuntime.js";
const profile=(id,rms,bands)=>({asset_id:id,rms_dbfs:rms,bands,profile_digest:`digest-${id}`});
test("dialogue match builds bounded level and tonal continuity plan from measured production/ADR profiles",()=>{const plan=buildAudioPostDialogueMatchPlan({production:profile("prod",-21,{low:-28,body:-24,presence:-26,air:-36}),adr:profile("adr",-15,{low:-33,body:-26,presence:-20,air:-29}),editorial:{production_sound:true,production_perspective:"MEDIUM",adr_perspective:"CLOSE"},room_tone_asset_id:"room"});assert.equal(plan.gain_match_db,-6);assert.equal(plan.band_deltas_db.low,5);assert.ok(plan.eq_moves.some(x=>x.band==="low"&&x.change_db===5));assert.ok(plan.warnings.includes("DIALOGUE_PERSPECTIVE_MISMATCH"));assert.equal(plan.automatic_eq_apply_forbidden,true);assert.equal(plan.source_audio_rewritten,false);});
test("dialogue match approval is fingerprint-bound and requires room/perspective review",()=>{const plan=buildAudioPostDialogueMatchPlan({production:profile("prod",-20,{low:-30,body:-24,presence:-25,air:-35}),adr:profile("adr",-19,{low:-29,body:-24,presence:-24,air:-34}),editorial:{production_sound:true,production_perspective:"FAR",adr_perspective:"CLOSE"},room_tone_asset_id:"room"});assert.throws(()=>approveAudioPostDialogueMatch(plan,{plan_fingerprint:"wrong",level_match_approved:true}),/FINGERPRINT_MISMATCH/);const approval=approveAudioPostDialogueMatch(plan,{plan_fingerprint:plan.plan_fingerprint,level_match_approved:true,tonal_match_approved:true,room_tone_continuity_approved:true,perspective_match_approved:true,override_warnings:true,reviewer_user_id:"u"});assert.equal(approval.status,"APPROVED");assert.equal(approval.automatic_processing_authorized,false);});
test("dialogue profile and API measure real audio and keep project scope",()=>{const profileSource=fs.readFileSync("lib/creative/music/runtime/CreativeAudioPostDialogueProfileRuntime.js","utf8"),route=fs.readFileSync("app/api/creative/music/dialogue-match/route.js","utf8");assert.match(profileSource,/actual_audio_measured:true/);assert.match(profileSource,/bands=\{low:/);assert.match(profileSource,/materializeMedia/);assert.match(route,/requireOrganizationAccess/);assert.match(route,/AUDIO_POST_DIALOGUE_MATCH_ASSET_SCOPE_INVALID/);assert.match(route,/resolveCreativeProviderAssetUrl/);assert.match(route,/audio_post_dialogue_match_approvals/);});
test("ADR Clip Editor exposes production asset perspective measured match and approval",()=>{const ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicClipEditorPanel.jsx","utf8"),editorial=fs.readFileSync("lib/creative/music/runtime/CreativeAudioPostEditorialRuntime.js","utf8"),parent=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicMultitrackStudioPanelV2.jsx","utf8");assert.match(ui,/Dialogue \/ ADR acoustic match/);assert.match(ui,/Production line asset/);assert.match(ui,/Production perspective/);assert.match(ui,/ADR perspective/);assert.match(ui,/Analyze match/);assert.match(ui,/Approve plan/);assert.match(ui,/dialogue_match_plan_fingerprint/);assert.match(editorial,/production_match_asset_id/);assert.match(editorial,/dialogue_match_approved/);assert.match(parent,/organizationId=\{organizationId\}/);assert.match(parent,/projectId=\{projectId\}/);});

test("approved dialogue match renders a new 24-bit derived ADR asset without baking room tone or perspective",()=>{const render=fs.readFileSync("lib/creative/music/runtime/CreativeAudioPostDialogueMatchRenderRuntime.js","utf8"),route=fs.readFileSync("app/api/creative/music/dialogue-match/route.js","utf8");assert.match(render,/pcm_s24le/);assert.match(render,/RENDER_FINGERPRINT_MISMATCH/);assert.match(render,/source_audio_preserved:true/);assert.match(render,/render_new_asset_only:true/);assert.match(render,/room_tone_printed:false/);assert.match(render,/perspective_reverb_printed:false/);assert.match(route,/AUDIO_POST_ADR_MATCHED/);assert.match(route,/CURRENT_APPROVAL_REQUIRED/);assert.match(route,/derived_asset:true/);assert.match(route,/destructive_edit:false/);});
test("Clip Editor requires explicit render and explicit use of matched ADR while preserving original take id",()=>{const ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicClipEditorPanel.jsx","utf8"),editorial=fs.readFileSync("lib/creative/music/runtime/CreativeAudioPostEditorialRuntime.js","utf8");assert.match(ui,/Render matched ADR/);assert.match(ui,/Use matched asset/);assert.match(ui,/dialogue_match_original_adr_asset_id:postEdit\.dialogue_match_original_adr_asset_id\|\|clip\.source_asset_id/);assert.match(ui,/preserve_source_asset:true/);assert.match(ui,/destructive_edit:false/);assert.match(editorial,/dialogue_match_original_adr_asset_id/);assert.match(editorial,/dialogue_match_rendered_asset_id/);});
