import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {normalizeMusicSpatialLayout,createMusicSpatialAudioConfig} from "../lib/creative/music/runtime/CreativeMusicSpatialAudioRuntime.js";
import {deriveMusicPointSpeakerGains,mixMusicTrackIntoSpatialChannels} from "../lib/creative/music/client/MusicSpatialMixMathRuntime.js";
import {encodeMusicChannelsWav24} from "../lib/creative/music/client/MusicWav24Runtime.js";
test("owned 7.1.4 layout exposes twelve discrete speakers without Dolby branding",()=>{const l=normalizeMusicSpatialLayout("7.1.4"),c=createMusicSpatialAudioConfig({layout_id:"7.1.4"});assert.equal(l.channel_count,12);assert.deepEqual(l.speaker_order.slice(-4),["Tfl","Tfr","Tbl","Tbr"]);assert.equal(c.dolby.branded_delivery_enabled,false);assert.equal(c.monitoring.speaker_calibration_required_for_surround,true);});
test("elevated front object routes energy into top-front speakers",()=>{const gains=deriveMusicPointSpeakerGains("7.1.4",0,0,45);assert.ok((gains.Tfl||0)>0||(gains.Tfr||0)>0);const floor=deriveMusicPointSpeakerGains("7.1.4",0,0,0);assert.ok((gains.Tfl||0)+(gains.Tfr||0)>(floor.Tfl||0)+(floor.Tfr||0));});
test("7.1.4 point render writes energy into native height channels",()=>{const left=new Float32Array(128).fill(1),right=new Float32Array(128).fill(1),out=mixMusicTrackIntoSpatialChannels({layout:"7.1.4",left,right,spatial:{mode:"POINT",azimuth_degrees:-30,elevation_degrees:45,distance_meters:1,lfe_send_db:-120}});assert.equal(out.length,12);const heightEnergy=out.slice(8).reduce((sum,ch)=>sum+ch.reduce((a,v)=>a+v*v,0),0);assert.ok(heightEnergy>0);});
test("24-bit WAV_EXTENSIBLE encoder supports 12-channel 7.1.4 mask",()=>{const wav=encodeMusicChannelsWav24(Array.from({length:12},()=>new Float32Array(64)),48000,{channel_layout:"7.1.4"});assert.equal(wav.channels,12);assert.equal(wav.channel_layout,"7.1.4");assert.equal(wav.wave_format_extensible,true);assert.equal(wav.channel_mask,0x2d63f);});
test("surround renderer distinguishes native 7.1.4 height from horizontal bed collapse",()=>{const src=fs.readFileSync("lib/creative/music/client/MusicOfflineSurroundRenderRuntime.js","utf8");assert.match(src,/NATIVE_HEIGHT_CHANNELS/);assert.match(src,/native_height_channels/);assert.match(src,/spatial\.layout_id === "7\.1\.4"/);});


test("Workstation and automation UI expose 7.1.4 elevation and distance authoring",()=>{const workstation=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicMultitrackStudioPanelV2.jsx","utf8"),automation=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicAutomationPanel.jsx","utf8");assert.match(workstation,/7\.1\.4 Height/);assert.match(workstation,/Elevation/);assert.match(workstation,/Distance m/);assert.match(automation,/spatial:elevation_degrees/);assert.match(automation,/spatial:distance_meters/);});
