import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {evaluateAudioPostFinalQc} from "../lib/creative/music/runtime/CreativeAudioPostFinalQcRuntime.js";
function asset(code,id,sources=[]){return{id,metadata:{music_asset_kind:"PROFESSIONAL_AUDIO_STEM",professional_audio_delivery_code:code,delivery_language:["DX","VO","ADR"].includes(code)?"en":null,project_revision:4,channels:6,channel_layout:"5.1",render_duration_seconds:60,peak_dbfs:-3,rms_dbfs:-18,clipping:false,source_assets_preserved:true,bwf_verified:true,bext_present:true,time_reference_samples:0,start_timecode:"00:00:00:00",source_asset_ids:sources}};}
function session(){return{revision:4,spatial_audio:{layout_id:"5.1",channel_count:6},tracks:[{id:"dx",audio_role:"DIALOGUE",clips:[{id:"d1",audio_post:{language:"en",dialogue_edit_approved:true}}]},{id:"mx",audio_role:"MUSIC",clips:[{id:"m1",source_asset_id:"m"}]},{id:"fx",audio_role:"EFFECTS",clips:[{id:"x1",source_asset_id:"x"}]}]};}
function master(){return{id:"master",metadata:{music_asset_kind:"SURROUND_MASTER",delivery_language:"en",project_revision:4,release_candidate:true,channels:6,channel_layout:"5.1",bwf_verified:true,bext_present:true,time_reference_samples:0,start_timecode:"00:00:00:00",render_duration_seconds:60,surround_validation_passed:true,surround_technical_validation:{passed:true,observed:{duration_seconds:60,stereo_downmix:{true_peak_dbtp:-1},mono_downmix:{true_peak_dbtp:-2}}}}};}
test("final post QC passes coherent current 5.1 master stems M&E and language editorial",()=>{const assets=[asset("DX","dx",["d"]),asset("MX","mx",["m"]),asset("FX","fx",["x"]),asset("ME","me",["m","x"]),master()];const r=evaluateAudioPostFinalQc({session:session(),assets,language:"en"});assert.equal(r.passed,true);assert.equal(r.fold_down_qc.passed,true);assert.equal(r.me_coherence.passed,true);assert.equal(r.dialogue_intelligibility.human_listening_review_required,true);assert.equal(r.dialogue_intelligibility.automatic_semantic_claim,false);});
test("final post QC fails duration language M&E coherence and format drift",()=>{const s=session();s.tracks[0].clips[0].audio_post.language="th";const bad=asset("DX","dx",["d"]);bad.metadata.render_duration_seconds=59;bad.metadata.channels=2;bad.metadata.channel_layout="stereo";const r=evaluateAudioPostFinalQc({session:s,assets:[bad,asset("MX","mx",["m"]),asset("FX","fx",["x"]),asset("ME","me",["m"]),master()],language:"en"});assert.equal(r.passed,false);assert.ok(r.failures.includes("AUDIO_POST_LANGUAGE_VERSION_MISMATCH"));assert.ok(r.failures.includes("AUDIO_POST_STEM_DURATION_MISMATCH:DX"));assert.ok(r.failures.includes("AUDIO_POST_STEM_FORMAT_MISMATCH:DX"));assert.ok(r.failures.includes("AUDIO_POST_ME_SOURCE_COHERENCE_FAILED"));});
test("surround package requires measured fold-down evidence",()=>{const m=master();delete m.metadata.surround_technical_validation;const r=evaluateAudioPostFinalQc({session:session(),assets:[asset("DX","dx",["d"]),asset("MX","mx",["m"]),asset("FX","fx",["x"]),asset("ME","me",["m","x"]),m],language:"en"});assert.equal(r.passed,false);assert.ok(r.failures.includes("AUDIO_POST_FOLD_DOWN_QC_REQUIRED"));});
test("delivery runtime and UI are wired to final post QC",()=>{const delivery=fs.readFileSync("lib/creative/music/runtime/CreativeAudioPostDeliveryRuntime.js","utf8"),panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicDeliverablesPanel.jsx","utf8");assert.match(delivery,/evaluateAudioPostFinalQc/);assert.match(delivery,/final_qc/);assert.match(panel,/Final post QC/);});
