import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildAudioPostDialogueRestorationPlan, createAudioPostDialogueRestorationReview } from "../lib/creative/music/runtime/CreativeAudioPostDialogueRestorationRuntime.js";

test("dialogue restoration plans film-specific repairs without auto-applying them",()=>{const plan=buildAudioPostDialogueRestorationPlan({source_asset_id:"asset-dx",room_tone_asset_id:"tone-1",diagnostics:{dc_offset:.02,hum_warning:true,noise_warning:true,floor_history_windows:8,clicks_detected:true,plosive_detected:true,excess_reverb_detected:true,clothing_rustle_detected:true,wind_detected:true,clipping_detected:true,room_tone_gap_detected:true}});const ids=plan.processors.map(x=>x.id);for(const id of ["dc_block","dehum","declick","plosive_repair","broadband_denoise","dereverb","rustle_repair","wind_repair","declip","room_tone_fill"])assert.ok(ids.includes(id),id);assert.equal(plan.automatic_apply_forbidden,true);assert.equal(plan.original_source_preserved,true);assert.equal(plan.render_new_asset_only,true);assert.equal(plan.publication_authorized,false);});
test("noise repair fails closed without enough floor evidence and room-tone fill requires a matched asset",()=>{const plan=buildAudioPostDialogueRestorationPlan({source_asset_id:"asset-dx",diagnostics:{noise_warning:true,floor_history_windows:1,room_tone_gap_detected:true}});assert.ok(plan.blockers.includes("DIALOGUE_NOISE_PROFILE_EVIDENCE_REQUIRED"));assert.ok(plan.blockers.includes("MATCHED_ROOM_TONE_ASSET_REQUIRED"));assert.equal(plan.technical_plan_ready,false);});
test("dialogue restoration listening review requires every criterion at 92 plus level-matched A/B",()=>{const plan=buildAudioPostDialogueRestorationPlan({source_asset_id:"asset-dx"}),scores={noise_transparency:95,speech_naturalness:95,room_continuity:95,plosive_click_integrity:95,spectral_artifact_control:95,sync_perspective_continuity:95};const blocked=createAudioPostDialogueRestorationReview(plan,{status:"APPROVED",reviewer_user_id:"u1",scores,level_matched_ab_confirmed:false});assert.equal(blocked.release_eligible,false);const passed=createAudioPostDialogueRestorationReview(plan,{status:"APPROVED",reviewer_user_id:"u1",scores,level_matched_ab_confirmed:true,material_artifact_detected:false});assert.equal(passed.release_eligible,true);});
test("cleanup route binds dialogue restoration to the existing owned cleanup path",()=>{const route=fs.readFileSync("app/api/creative/music/studio/route.js","utf8");assert.match(route,/buildAudioPostDialogueRestorationPlan/);assert.match(route,/sourceRole === "dialogue"/);assert.match(route,/dialogue_restoration_plan: dialogueRestorationPlan/);});
