import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildAudioPostPrintmasterPlan, evaluateAudioPostPrintmasterVariant, sealAudioPostPrintmasterSet } from "../lib/creative/music/runtime/CreativeAudioPostPrintmasterRuntime.js";

const session={revision:7,picture_lock:{picture_lock_digest:"pic-7"},spatial_audio:{layout_id:"7.1.4"}};

test("printmaster plan creates separate theatrical near-field and streaming variants from one approved master",()=>{const p=buildAudioPostPrintmasterPlan({session,source_master_asset_id:"master-1"});assert.equal(p.variants.length,3);assert.equal(p.separate_printmasters_required,true);assert.equal(p.one_master_fits_all_claimed,false);for(const v of p.variants){assert.equal(v.source_master_asset_id,"master-1");assert.equal(v.source_premixes_reused,true);assert.equal(v.independent_qc_required,true);assert.equal(v.independent_listening_review_required,true);assert.equal(v.automatic_loudness_normalization,false);}});

test("theatrical and near-field printmasters require the correct monitoring review",()=>{const p=buildAudioPostPrintmasterPlan({session,source_master_asset_id:"master-1"}),base={source_master_asset_id:"master-1",picture_lock_digest:"pic-7",project_revision:7,channel_layout:"7.1.4",rendered_asset_id:"render-1",technical_qc_passed:true,listening_review_approved:true};const theatrical=evaluateAudioPostPrintmasterVariant(p,"THEATRICAL",{...base,cinema_monitor_reviewed:true});assert.equal(theatrical.passed,true);const nearBlocked=evaluateAudioPostPrintmasterVariant(p,"NEAR_FIELD",base);assert.ok(nearBlocked.failures.includes("PRINTMASTER_NEAR_FIELD_MONITOR_REVIEW_REQUIRED"));const near=evaluateAudioPostPrintmasterVariant(p,"NEAR_FIELD",{...base,near_field_monitor_reviewed:true});assert.equal(near.passed,true);});

test("stale picture revision or wrong source master fails closed",()=>{const p=buildAudioPostPrintmasterPlan({session,source_master_asset_id:"master-1"}),r=evaluateAudioPostPrintmasterVariant(p,"STREAMING",{source_master_asset_id:"master-old",picture_lock_digest:"pic-old",project_revision:6,channel_layout:"7.1.4",rendered_asset_id:"render-old",technical_qc_passed:true,listening_review_approved:true,near_field_monitor_reviewed:true});assert.ok(r.failures.includes("PRINTMASTER_SOURCE_MASTER_MISMATCH"));assert.ok(r.failures.includes("PRINTMASTER_PICTURE_LOCK_MISMATCH"));assert.ok(r.failures.includes("PRINTMASTER_PROJECT_REVISION_STALE"));});

test("printmaster set only seals when every requested version independently passes",()=>{const p=buildAudioPostPrintmasterPlan({session,source_master_asset_id:"master-1",variants:["THEATRICAL","NEAR_FIELD"]}),base={source_master_asset_id:"master-1",picture_lock_digest:"pic-7",project_revision:7,channel_layout:"7.1.4",rendered_asset_id:"render-1",technical_qc_passed:true,listening_review_approved:true};const a=evaluateAudioPostPrintmasterVariant(p,"THEATRICAL",{...base,cinema_monitor_reviewed:true}),b=evaluateAudioPostPrintmasterVariant(p,"NEAR_FIELD",{...base,near_field_monitor_reviewed:true});const seal=sealAudioPostPrintmasterSet(p,[a,b]);assert.equal(seal.immutable_evidence,true);assert.equal(seal.variants.length,2);assert.ok(seal.seal_hash.length===64);});

test("world-class registry exposes printmaster versioning as implemented shared-engine capability",()=>{const src=fs.readFileSync("lib/creative/music/runtime/CreativeMusicWorldClassStudioRuntime.js","utf8");assert.match(src,/printmaster_versions/);assert.match(src,/creative\.audio\.printmasters/);});
