import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

test("Sound Design room exposes synthesis measured spaces and immersive scene master",()=>{const shell=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicUnifiedWorkstationShell.jsx","utf8"),panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicAdvancedSoundDesignPanel.jsx","utf8");assert.match(shell,/MusicAdvancedSoundDesignPanel/);assert.match(panel,/Synthesis Lab/);assert.match(panel,/Measured Acoustic Spaces/);assert.match(panel,/Immersive Scene Master/);assert.match(panel,/buildCinematicSoundSynthesisPlan/);assert.match(panel,/buildMeasuredAcousticSpaceLibrary/);assert.match(panel,/buildMusicImmersiveScene/);});

test("Deliverables exposes governed film printmaster plan",()=>{const panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicDeliverablesPanel.jsx","utf8"),route=fs.readFileSync("app/api/creative/music/audio-post-delivery/route.js","utf8");assert.match(panel,/Film Printmasters/);assert.match(panel,/THEATRICAL|theatrical/);assert.match(panel,/near-field/);assert.match(panel,/streaming/);assert.match(route,/printmaster_plan/);assert.match(route,/buildAudioPostPrintmasterPlan/);assert.match(route,/THEATRICAL/);assert.match(route,/NEAR_FIELD/);assert.match(route,/STREAMING/);});

test("delivery download and manifest resolve the current language seal before use",()=>{const route=fs.readFileSync("app/api/creative/music/audio-post-delivery/route.js","utf8");assert.match(route,/sealedLanguage=\[\.\.\.seals\]/);assert.match(route,/action==="download_package"\)\{const seal=sealedLanguage/);assert.match(route,/action==="export_manifest"\)\{const seal=sealedLanguage/);});
test("printmaster workflow binds exact rendered assets to independent review and immutable set seal",()=>{const panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicDeliverablesPanel.jsx","utf8"),route=fs.readFileSync("app/api/creative/music/audio-post-delivery/route.js","utf8"),runtime=fs.readFileSync("lib/creative/music/runtime/CreativeAudioPostPrintmasterRuntime.js","utf8");assert.match(panel,/Save independent review/);assert.match(panel,/Seal printmaster set/);assert.match(route,/printmaster_review/);assert.match(route,/printmaster_seal/);assert.match(route,/PRINTMASTER_RENDERED_ASSET_SCOPE_MISMATCH/);assert.match(runtime,/PRINTMASTER_RENDERED_ASSET_REQUIRED/);assert.match(runtime,/rendered_asset_id/);});
test("Advanced Sound Design exposes governed measured-space transition timeline",()=>{const panel=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicAdvancedSoundDesignPanel.jsx","utf8");assert.match(panel,/buildAcousticSpaceTransitionPlan/);assert.match(panel,/Measured-space transition/);assert.match(panel,/Add governed IR transition/);assert.match(panel,/Portal \/ doorway ID/);assert.match(panel,/equal-power measured IR crossfade/);});
