import test from "node:test";
import assert from "node:assert/strict";
import { deriveMusicAcousticWorldAutomation, normalizeMusicAcousticWorld } from "../lib/creative/music/runtime/CreativeMusicAcousticWorldGeometryRuntime.js";
import { createMusicCinematicSoundObject } from "../lib/creative/music/runtime/CreativeMusicCinematicSoundObjectRuntime.js";
import { bindMusicSoundObjectsToSession } from "../lib/creative/music/runtime/CreativeMusicSoundObjectRenderBindingRuntime.js";

function fixture(portalOpen=0){return normalizeMusicAcousticWorld({id:"set-1",listener:{keyframes:[{time_seconds:0,x:0,y:0,z:0},{time_seconds:2,x:0,y:0,z:0}]},sources:[{picture_object_id:"car-visual",keyframes:[{time_seconds:0,x:-4,y:0,z:-10},{time_seconds:1,x:0,y:0,z:-10},{time_seconds:2,x:4,y:0,z:-10}]}],obstacles:[{id:"wall",material:"CONCRETE",bounds:{min:{x:-1,y:-2,z:-6},max:{x:1,y:2,z:-4}},portal_ids:["door"]}],portals:[{id:"door",open_percent:portalOpen}],reflection_amount_percent:42});}
function soundObject(){return createMusicCinematicSoundObject({id:"car-sound",assigned_track_id:"fx-car",category:"VEHICLE",picture_object_id:"car-visual",start_seconds:0,duration_seconds:2,spatial_path:{mode:"FOLLOW_PICTURE_OBJECT"}});}

test("geometry derives moving azimuth distance and material occlusion from tracked picture coordinates",()=>{const result=deriveMusicAcousticWorldAutomation({world:fixture(0),sound_object:soundObject(),track_id:"fx-car"});assert.equal(result.geometry_authoritative,true);assert.equal(result.rows.length,3);assert.ok(result.rows[0].azimuth_degrees<0);assert.equal(result.rows[1].azimuth_degrees,0);assert.ok(result.rows[2].azimuth_degrees>0);assert.equal(result.rows[1].obstruction_material,"CONCRETE");assert.equal(result.rows[1].occlusion_percent,92);assert.ok(result.lanes.some(l=>l.parameter==="spatial:distance_meters"));assert.ok(result.lanes.some(l=>l.parameter==="spatial:occlusion_percent"));});

test("open acoustic portal removes wall occlusion without manual percentage authoring",()=>{const closed=deriveMusicAcousticWorldAutomation({world:fixture(0),sound_object:soundObject(),track_id:"fx-car"}),open=deriveMusicAcousticWorldAutomation({world:fixture(100),sound_object:soundObject(),track_id:"fx-car"});assert.equal(closed.rows[1].occlusion_percent,92);assert.equal(open.rows[1].occlusion_percent,0);});

test("sound-object binding switches FOLLOW_PICTURE_OBJECT to acoustic-world authority",()=>{const session={tracks:[{id:"fx-car",spatial:{mode:"BED"},clips:[]}],automation_lanes:[],sound_objects:[soundObject()],acoustic_world:fixture(0)},bound=bindMusicSoundObjectsToSession(session);assert.equal(bound.success,true);assert.equal(bound.session.tracks[0].sound_object_binding.source_of_truth,"ACOUSTIC_WORLD_GEOMETRY");assert.equal(bound.session.tracks[0].sound_object_binding.acoustic_world_id,"set-1");assert.equal(bound.session.tracks[0].spatial.immersive.obstruction_material,"CONCRETE");assert.ok(bound.session.automation_lanes.some(l=>l.id==="geometry-car-sound-azimuth_degrees"));assert.ok(bound.session.automation_lanes.some(l=>l.id==="geometry-car-sound-occlusion_percent"));});
