import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {buildAudioPostDeliveryPackage,sealAudioPostDeliveryPackage} from "../lib/creative/music/runtime/CreativeAudioPostDeliveryRuntime.js";
import {ensureAudioPostMixBuses} from "../lib/creative/music/runtime/CreativeAudioPostMixRuntime.js";
function session(){return ensureAudioPostMixBuses({revision:3,picture_lock:{picture_lock_digest:"lock",frame_rate:24,frame_count:240},spatial_audio:{layout_id:"5.1",channel_count:6,surround_enabled:true},tracks:[{id:"dx",audio_role:"DIALOGUE",spatial:{mode:"BED"},clips:[{id:"dx1",source_asset_id:"s1",audio_post:{language:"en",speaker:"A",sync_frame:10,dialogue_edit_approved:true}}]},{id:"mx",audio_role:"MUSIC",clips:[{id:"m1",source_asset_id:"s2"}]},{id:"fx",audio_role:"EFFECTS",clips:[{id:"f1",source_asset_id:"s3"}]}],buses:[{id:"bus-master",type:"master"}]});}
function stem(code,id,sources=[]){return{id,created_at:"2026-09-18T00:00:00Z",metadata:{music_asset_kind:"PROFESSIONAL_AUDIO_STEM",professional_audio_delivery_code:code,project_revision:3,channels:6,channel_layout:"5.1",render_duration_seconds:60,peak_dbfs:-3,rms_dbfs:-18,clipping:false,source_assets_preserved:true,source_asset_ids:sources,destructive_edit:false}};}
function master(){return{id:"master",metadata:{music_asset_kind:"SURROUND_MASTER",project_revision:3,release_candidate:true,channels:6,channel_layout:"5.1",render_duration_seconds:60,surround_validation_passed:true,surround_technical_validation:{passed:true,observed:{duration_seconds:60,stereo_downmix:{true_peak_dbtp:-1},mono_downmix:{true_peak_dbtp:-2}}}}};}
test("Audio Post package fails closed until current master and required professional stems exist",()=>{const r=buildAudioPostDeliveryPackage({session:session(),assets:[],language:"en"});assert.equal(r.release_ready,false);assert.ok(r.failures.includes("AUDIO_POST_CURRENT_FULL_MIX_MASTER_REQUIRED"));assert.ok(r.failures.some(x=>x.includes("AUDIO_POST_REQUIRED_STEM_MISSING")));});
test("Audio Post package validates picture lock editorial M&E and current 5.1 assets",()=>{const assets=[stem("DX","dx",["s1"]),stem("MX","mx",["s2"]),stem("FX","fx",["s3"]),stem("ME","me",["s2","s3"]),master()];const r=buildAudioPostDeliveryPackage({session:session(),assets,language:"en"});assert.equal(r.release_ready,true);assert.equal(r.me.asset_id,"me");assert.equal(r.full_mix.asset_id,"master");assert.equal(r.channel_layout,"5.1");});
test("delivery API and UI expose package readiness rather than file-exists semantics",()=>{const route=fs.readFileSync("app/api/creative/music/audio-post-delivery/route.js","utf8"),ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicDeliverablesPanel.jsx","utf8");assert.match(route,/buildAudioPostDeliveryPackage/);assert.match(route,/release_ready/);assert.match(ui,/Audio Post delivery package/);assert.match(ui,/release_ready/);assert.match(ui,/M&E/);});


test("release-ready package can be immutably sealed without changing audio",()=>{const assets=[stem("DX","dx",["s1"]),stem("MX","mx",["s2"]),stem("FX","fx",["s3"]),stem("ME","me",["s2","s3"]),master()],pkg=buildAudioPostDeliveryPackage({session:session(),assets,language:"en"});const a=sealAudioPostDeliveryPackage(pkg,{sealed_at:"2026-09-18T12:00:00Z"}),b=sealAudioPostDeliveryPackage(pkg,{sealed_at:"2026-09-18T13:00:00Z"});assert.equal(a.manifest_hash,b.manifest_hash);assert.equal(a.immutable_evidence,true);assert.equal(a.audio_mutation_performed,false);});
test("delivery route persists explicit seals and UI never auto-seals",()=>{const route=fs.readFileSync("app/api/creative/music/audio-post-delivery/route.js","utf8"),ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicDeliverablesPanel.jsx","utf8");assert.match(route,/action==="seal"/);assert.match(route,/audio_post_delivery_seals/);assert.match(route,/audio_post_current_delivery_seal/);assert.match(ui,/Seal delivery package/);assert.match(ui,/sealDeliveryPackage/);});


test("Audio Post delivery fails closed when re-recording mix policy is absent",()=>{const s=session();delete s.audio_post_mix;const r=buildAudioPostDeliveryPackage({session:s,assets:[],language:"en"});assert.equal(r.release_ready,false);assert.ok(r.failures.includes("AUDIO_POST_RERECORDING_MIX_POLICY_REQUIRED"));});
