import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const provider=fs.readFileSync("lib/platform/service-runtime/providers/avantiqo-audio/AvantiqoMusicLocalNodeProvider.js","utf8");
const worker=fs.readFileSync("services/avantiqo-music-local/node01_worker.ps1","utf8");
const runner=fs.readFileSync("services/avantiqo-music-local/vocal_role_separator_runner.py","utf8");
const registration=fs.readFileSync("lib/platform/service-runtime/providers/avantiqo-audio/AvantiqoAudioProviderRegistration.js","utf8");
const catalog=fs.readFileSync("lib/platform/service-runtime/ai/PlatformAIServiceCatalog.js","utf8");
test("local provider defines a separate research-only vocal-role capability",()=>{assert.match(provider,/"ai\.audio\.vocal-role-separate"/);assert.match(provider,/music_vocal_role_separator/);assert.match(provider,/DEMUCS_HTDEMUCS_FT_PLUS_UVR_KARA2_VOCAL_ROLE_RESEARCH_V1/);assert.match(provider,/model_license_verified: false/);});
test("Node01 advertises vocal-role separation only when runner and Python modules actually exist",()=>{assert.match(worker,/VocalRoleRuntimeReady = \$false/);assert.match(worker,/import demucs, audio_separator/);assert.match(worker,/Test-Path \$VocalRoleRunner/);assert.match(worker,/if \(\$VocalRoleRuntimeReady\).*ai\.audio\.vocal-role-separate/s);assert.match(worker,/RunMusicVocalRoleSeparationJob/);});
test("candidate pipeline is explicit Demucs full-vocal isolation then KARA2 second pass",()=>{assert.match(runner,/STAGE1_MODEL = "htdemucs_ft"/);assert.match(runner,/STAGE2_MODEL = "UVR_MDXNET_KARA_2\.onnx"/);assert.match(runner,/--two-stems", "vocals"/);assert.match(runner,/separator\.separate\(\)/);assert.match(runner,/vocals_output_role.*LEAD/);assert.match(runner,/instrumental_output_role.*SUPPORTING_VOCALS/);});
test("candidate fails closed on ambiguous KARA output and never claims production certification",()=>{assert.match(runner,/KARA_OUTPUT_AMBIGUOUS/);assert.match(runner,/human_listening_review_required.*True/s);assert.match(runner,/model_license_verified.*False/s);assert.match(runner,/production_certified.*False/s);assert.match(runner,/ordinary_four_stem_substitution_forbidden.*True/s);});
test("registry and service catalog expose exact research runtime without enabling production routing",()=>{assert.match(registration,/RESEARCH_RUNTIME_IMPLEMENTED_CERTIFICATION_REQUIRED/);assert.match(registration,/UVR_MDXNET_KARA_2\.onnx/);assert.match(registration,/preserve_backing_vocals_supported: true/);assert.match(registration,/model_license_verified: false/);assert.match(registration,/production_routing_allowed: false/);assert.match(catalog,/id: "ai\.audio\.vocal-role-separate"/);});

test("Studio surfaces candidate-runtime truth without exposing uncertified production execution",()=>{const stems=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicStemsPanel.jsx","utf8"),backing=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicBackingTrackPanel.jsx","utf8");assert.match(stems,/owned research runtime ready · certification \+ license review required/);assert.match(stems,/certification \+ model-license review required/);assert.match(backing,/owned research runtime/);assert.match(backing,/production stays disabled/);assert.match(stems,/executionReady = plan\?\.ready_for_execution === true && separationMode === "STANDARD_STEMS"/);});
