import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {CreativeMusicMasteringListeningReviewRuntime as R} from "../lib/creative/music/runtime/CreativeMusicMasteringListeningReviewRuntime.js";
const analysis={contract:"AVANTIQO_MUSIC_REFERENCE_MASTERING_V1",master_asset_id:"master-1",references:[{reference_asset_id:"ref-1",loudness_match_gain_db:-2,deltas:{crest_delta_db:1,band_deltas_db:{bass:1}},review_flags:[]}]};
function review(score=95){return{contract:R.contract,reference_analysis_fingerprint:R.fingerprint(analysis),level_matched_reference_comparison_confirmed:true,material_artifact_present:false,criteria:R.criteria.map(id=>({id,score_0_to_100:score}))};}
test("mastering review requires all nine human criteria at 92+",()=>{const x=R.validate(review(),analysis);assert.equal(x.status,"APPROVED");assert.equal(x.criteria.length,9);assert.equal(x.minimum_score_0_to_100,95);assert.equal(x.automatic_approval_forbidden,true);});
test("mastering review rejects stale analysis fingerprint and low score",()=>{const a=review();a.reference_analysis_fingerprint="stale";assert.throws(()=>R.validate(a,analysis),/FINGERPRINT_MISMATCH/);const b=review();b.criteria[0].score_0_to_100=91;assert.throws(()=>R.validate(b,analysis),/SCORE_BELOW_POLICY/);});
test("mastering review requires actual level-matched A-B and rejects material artifacts",()=>{const a=review();a.level_matched_reference_comparison_confirmed=false;assert.throws(()=>R.validate(a,analysis),/LEVEL_MATCHED_AB_REQUIRED/);const b=review();b.material_artifact_present=true;assert.throws(()=>R.validate(b,analysis),/MATERIAL_ARTIFACT_REJECTS/);});
test("master-reference API persists review bound to exact current analysis",()=>{const route=fs.readFileSync("app/api/creative/music/master-reference/route.js","utf8");assert.match(route,/action===\"review\"/);assert.match(route,/masteringReferenceAnalysisFingerprint/);assert.match(route,/music_mastering_reference_reviews/);assert.match(route,/music_current_mastering_reference_review/);assert.match(route,/endpoint_mutation_performed:true/);});

test("Master Studio exposes structured scored mastering review bound to analysis fingerprint",()=>{const ui=fs.readFileSync("components/creative/ProductionStudio/workspaces/MusicMasterStudioPanel.jsx","utf8");assert.match(ui,/Human mastering review · every criterion ≥92/);assert.match(ui,/level-matched A\/B against the selected references/);assert.match(ui,/Material artifact detected/);assert.match(ui,/Approve mastering review/);assert.match(ui,/reference_analysis_fingerprint:referenceFingerprint/);assert.match(ui,/Avantiqo never generates these scores/);});
