import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { derivePlanDiscriminatingEvidence } from "../lib/operator/runtime/OperatorPlanDiscriminatingEvidenceRuntime.js";
const candidate=(id,score,reads,write="finance.invoice.create")=>({candidate_id:id,index:id==="a"?0:1,score,governed_plan:{valid:true,steps:[...reads.map((key,i)=>({id:`r${i}`,kind:"read",capability_key:key,mutates:false,risk:"low",expected_output:"current evidence"})),{id:"w",kind:"action_candidate",capability_key:write,mutates:true}]}});
test("close valid plans require discriminating registered read before mutation",()=>{const r=derivePlanDiscriminatingEvidence([candidate("a",1000,["finance.ar.read"]),candidate("b",970,["finance.customer.read"])]);assert.equal(r.required,true);assert.equal(r.mutation_execution_blocked_until_discrimination,true);assert.equal(r.authority_effect,"NONE");assert.ok(["finance.ar.read","finance.customer.read"].includes(r.selected_read_capability_key));});
test("well separated plans do not add unnecessary evidence work",()=>{const r=derivePlanDiscriminatingEvidence([candidate("a",1000,["finance.ar.read"]),candidate("b",800,["finance.customer.read"])]);assert.equal(r.required,false);assert.equal(r.reason,"PLAN_SCORE_SEPARATION_SUFFICIENT");});
test("single valid plan stays compatible",()=>{const r=derivePlanDiscriminatingEvidence([candidate("a",1000,["finance.ar.read"])]);assert.equal(r.required,false);assert.equal(r.reason,"FEWER_THAN_TWO_VALID_PLANS");});
test("owned cognitive planner blocks execution guidance while discrimination is required",()=>{const source=fs.readFileSync("lib/operator/runtime/OperatorOwnedCognitivePlanRuntime.js","utf8");assert.match(source,/derivePlanDiscriminatingEvidence/);assert.match(source,/executionGuidanceAllowed = valid && discriminatingEvidence\.required !== true/);assert.match(source,/ambiguous_plans_require_discriminating_evidence_before_mutation: true/);assert.match(source,/discriminating_evidence: discriminatingEvidence/);});
