import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import PublicSiteHeader from "@/components/public/PublicSiteHeader";
import { industrySolutions } from "@/components/public/industrySolutionConfigs";

export function generateStaticParams() { return Object.keys(industrySolutions).map((slug) => ({ slug })); }
export async function generateMetadata({ params }) { const {slug}=await params; const c=industrySolutions[slug]; return c ? { title: `${c.name} | Avantiqo Solutions`, description: c.intro } : {}; }

export default async function Page({ params }) {
  const { slug } = await params;
  const c = industrySolutions[slug];
  if (!c) notFound();
  return <main className="min-h-screen bg-[#F7F4EE] text-[#181614]">
    <PublicSiteHeader context={c.name} audience="business" tone="light" />
    <section className="border-b border-[#D7CEC2]/55 bg-[#F3EEE5]">
      <div className="mx-auto grid max-w-[1540px] gap-10 px-5 py-14 sm:px-7 lg:min-h-[700px] lg:grid-cols-[.88fr_1.12fr] lg:items-center lg:px-10 lg:py-20">
        <div className="max-w-[650px]"><div className="text-[9px] font-semibold uppercase tracking-[.22em] text-[#A36F39]">{c.eyebrow}</div><h1 className="mt-5 text-[52px] font-medium leading-[.94] tracking-[-.065em] sm:text-[66px] xl:text-[78px]">{c.hero}</h1><p className="mt-7 max-w-[610px] text-[15px] leading-8 text-[#696158]">{c.intro}</p><div className="mt-9 flex flex-wrap gap-2.5"><Link href="/start" className="inline-flex h-11 items-center rounded-full bg-[#181614] px-5 text-[10px] font-semibold text-white">Start with {c.name}</Link><Link href="/solutions" className="inline-flex h-11 items-center rounded-full border border-black/[0.10] bg-white/68 px-5 text-[10px] font-semibold text-[#5F574F]">All solutions</Link></div></div>
        <div className="relative min-h-[530px] overflow-hidden rounded-[34px] border border-black/[0.08] bg-[#E9DFD1] shadow-[0_34px_95px_rgba(68,47,25,.13)]"><Image src={c.image} alt={`${c.name} operating environment`} fill priority sizes="58vw" className="object-cover" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(255,255,255,.01),rgba(20,15,10,.04)_58%,rgba(20,15,10,.38))]" /><div className="absolute left-5 top-5 rounded-full border border-white/55 bg-white/20 px-3.5 py-1.5 text-[7px] font-semibold uppercase tracking-[.20em] text-white backdrop-blur-md">AVANTIQO / {c.name}</div><div className="absolute bottom-5 left-5 right-5 rounded-[22px] border border-white/35 bg-[#F8F1E8]/82 p-5 text-[#2B241E] shadow-[0_18px_45px_rgba(0,0,0,.10)] backdrop-blur-xl"><div className="text-[7px] font-semibold uppercase tracking-[.20em] text-[#A36F39]">ONE OPERATING CONTEXT</div><div className="mt-2 text-[14px] leading-6">Work, people, finance, documents and intelligence remain connected underneath the industry workflow.</div></div></div>
      </div>
    </section>
    <section className="border-b border-[#D7CEC2]/50 bg-[#FBFAF7]"><div className="mx-auto max-w-[1540px] px-5 py-16 sm:px-7 lg:px-10 lg:py-20"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="text-[8px] font-semibold uppercase tracking-[.2em] text-[#9A744B]">WHAT THE TEAM ACTUALLY RUNS</p><h2 className="mt-3 max-w-xl text-[42px] font-medium leading-[.98] tracking-[-.05em] sm:text-[56px]">Built around the operating reality.</h2></div><p className="max-w-2xl text-[12px] leading-6 text-[#6E675F] lg:justify-self-end">Not a generic module bundle. Each surface follows the terminology, handoffs and evidence of the industry while the platform foundation stays consistent.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{c.capabilities.map(([title,copy],i)=><article key={title} className="rounded-[24px] border border-black/[0.07] bg-[#F6F0E7] p-6 shadow-[0_14px_34px_rgba(51,38,24,.04)]"><div className="text-[8px] font-semibold text-[#A36F39]">0{i+1}</div><h3 className="mt-8 text-[21px] font-medium tracking-[-.035em]">{title}</h3><p className="mt-3 text-[10px] leading-5 text-[#756D64]">{copy}</p></article>)}</div></div></section>
    <section className="border-b border-[#D7CEC2]/50 bg-[#EEE7DD]"><div className="mx-auto grid max-w-[1540px] gap-10 px-5 py-16 sm:px-7 lg:grid-cols-[.78fr_1.22fr] lg:items-center lg:px-10 lg:py-20"><div><p className="text-[8px] font-semibold uppercase tracking-[.2em] text-[#9A744B]">OPERATING FLOW</p><h2 className="mt-3 text-[42px] font-medium leading-[1] tracking-[-.05em] sm:text-[56px]">The work keeps moving.</h2><p className="mt-5 max-w-xl text-[12px] leading-6 text-[#6D665E]">Each step is connected to the same organization, permissions and evidence. Approved work moves forward without losing the business context that created it.</p></div><div className="grid gap-3 sm:grid-cols-5">{c.workflow.map((step,i)=><div key={step} className="rounded-[20px] border border-black/[0.07] bg-[#F9F5EF] p-5"><div className="text-[8px] font-semibold text-[#A36F39]">0{i+1}</div><div className="mt-10 text-[12px] font-semibold leading-5">{step}</div></div>)}</div></div></section>
    <section className="border-b border-[#D7CEC2]/50 bg-[#FBFAF7]"><div className="mx-auto grid max-w-[1540px] gap-10 px-5 py-16 sm:px-7 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:py-20"><div className="relative min-h-[420px] overflow-hidden rounded-[32px] border border-black/[0.08] shadow-[0_24px_70px_rgba(56,39,22,.09)]"><Image src={c.image} alt="" fill sizes="52vw" className="object-cover scale-[1.08]"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(10,8,6,.01),rgba(10,8,6,.28))]"/></div><div><p className="text-[8px] font-semibold uppercase tracking-[.2em] text-[#9A744B]">BUSINESS OUTCOME</p><h2 className="mt-3 text-[40px] font-medium leading-[1.02] tracking-[-.05em] sm:text-[54px]">Less translation between the business and the software.</h2><div className="mt-8 space-y-3">{c.outcomes.map((x,i)=><div key={x} className="flex gap-4 border-t border-black/[0.08] pt-4"><span className="text-[8px] font-semibold text-[#A36F39]">0{i+1}</span><span className="text-[12px] leading-6 text-[#5F5850]">{x}</span></div>)}</div></div></div></section>
    <section className="bg-[#F0E7DA]"><div className="mx-auto grid max-w-[1320px] gap-8 px-5 py-20 sm:px-7 lg:grid-cols-[1fr_auto] lg:items-center lg:px-10 lg:py-24"><div><p className="text-[9px] font-semibold uppercase tracking-[.22em] text-[#A36F39]">{c.name.toUpperCase()} + AVANTIQO</p><h2 className="mt-4 max-w-4xl text-[44px] font-medium leading-[.98] tracking-[-.055em] sm:text-[60px]">Start with the operation you already know.</h2><p className="mt-5 max-w-3xl text-[13px] leading-7 text-[#70665B]">Then connect the products, people, finance, documents, channels and intelligence around it.</p></div><Link href="/start" className="inline-flex h-11 items-center rounded-full bg-[#181614] px-5 text-[10px] font-semibold text-white">Plan this solution</Link></div></section>
  </main>;
}
