import PublicSiteHeader from "@/components/public/PublicSiteHeader";

export const metadata = { title: "Resources | Avantiqo", description: "Guides, research, playbooks, templates, benchmarks, case studies and product updates from Avantiqo." };

const GROUPS = [
  ["Guides","Learn how Avantiqo operating, creative, developer and compute layers work.","Start with practical product and implementation guidance."],
  ["Industry playbooks","See how restaurants, hotels, retail, construction, agencies and accounting firms can use the platform.","Turn one platform into industry-specific outcomes."],
  ["Research & benchmarks","Read evidence-led analysis across operations, finance, AI, creative production and infrastructure.","Build authority around the decisions customers actually make."],
  ["Case studies","Show real operating problems, implementation choices and measurable outcomes.","Sell proof instead of only product claims."],
  ["Templates","Reusable operating, campaign, document and workflow patterns for customers and partners.","Give people a faster path from interest to value."],
  ["Product updates","Track meaningful platform improvements, new capabilities and commercial releases.","Keep customers and partners current without mixing this into sales copy."],
];

export default function ResourcesPage(){ return <main className="min-h-screen bg-[#F7F6F3] text-[#171614]"><PublicSiteHeader context="Resources" audience="platform"/><section className="border-b border-black/[0.06] bg-[#F4F0E8]"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-7 lg:px-10 lg:py-28"><p className="text-[9px] font-semibold uppercase tracking-[0.24em] text-[#9A744B]">AVANTIQO / RESOURCES</p><div className="mt-4 grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><h1 className="max-w-3xl text-[52px] font-medium leading-[.96] tracking-[-0.06em] sm:text-[70px]">Learn the system. Understand the opportunity.</h1><p className="max-w-xl text-[15px] leading-8 text-[#6D675F] lg:justify-self-end">A serious knowledge layer for customers, operators, developers, partners and buyers — built around useful guidance, industry understanding, proof and repeatable operating patterns.</p></div></div></section><section className="bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-16 sm:px-7 lg:px-10 lg:py-24"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{GROUPS.map(([t,d,b],i)=><article key={t} className="min-h-[260px] rounded-[26px] border border-black/[0.075] bg-white p-6 shadow-[0_14px_40px_rgba(40,30,20,.03)]"><div className="text-[8px] font-bold text-[#A37849]">0{i+1}</div><h2 className="mt-9 text-[25px] font-medium tracking-[-0.04em]">{t}</h2><p className="mt-3 text-[11px] leading-6 text-[#746F68]">{d}</p><div className="mt-7 border-t border-black/[0.06] pt-4 text-[9px] leading-5 text-[#9A744B]">{b}</div></article>)}</div></div></section><section className="border-t border-black/[0.06] bg-[#F3EFE7]"><div className="mx-auto max-w-[1120px] px-5 py-20 text-center sm:px-7 lg:px-10"><p className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">FROM LEARNING TO ACTION</p><h2 className="mx-auto mt-4 max-w-3xl text-[40px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[54px]">Use the knowledge. Then enter the right Avantiqo world.</h2><div className="mt-8 flex flex-wrap justify-center gap-2.5"><a href="/start" className="inline-flex h-11 items-center rounded-full bg-[#171614] px-5 text-[10px] font-semibold text-white">Start Now →</a><a href="/solutions" className="inline-flex h-11 items-center rounded-full border border-[#D6A66A]/38 bg-white/72 px-5 text-[10px] font-semibold text-[#6A5540]">Explore Solutions</a></div></div></section></main>; }
