"use client";
export const dynamic = "force-dynamic";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, CalendarDays, Check, ChevronRight, Clock3, CreditCard, MapPin, RefreshCw, ShieldCheck, UserRound } from "lucide-react";
import { useOrganizationRuntime } from "@/lib/hooks/useOrganizationRuntime";

const STEPS=[["customer","Customer & site"],["service","Service & protocol"],["schedule","Schedule"],["technician","Technician"],["billing","Billing"],["review","Review"]];
const EMPTY={customer_party_id:"",customer_location_name:"",service_name:"Routine pest control service",service_category:"preventive_pest_control",execution_template_id:"",first_service_at:"",contract_end:"",duration_minutes:"60",recurrence_preset:"monthly",recurrence_interval:"1",recurrence_unit:"month",preferred_staff_id:"",billing_mode:"per_visit",billing_amount:"",billing_currency_code:"THB",billing_due_days:"0",billing_tax_code_id:"",notes:""};
const cls="mt-2 w-full rounded-xl border border-black/[0.09] bg-white px-3.5 py-3 text-[11px] text-[#2B2926] outline-none transition focus:border-[#D6A66A]/60";
function text(v){return String(v??"").trim();}
function iso(v){if(!v)return null;const x=new Date(v);return Number.isNaN(x.getTime())?null:x.toISOString();}
function date(v){if(!v)return "Not set";const x=new Date(v);return Number.isNaN(x.getTime())?"Not set":new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(x);}
function frequency(f){if(f.recurrence_preset==="weekly")return "Every week";if(f.recurrence_preset==="biweekly")return "Every 2 weeks";if(f.recurrence_preset==="monthly")return "Every month";if(f.recurrence_preset==="quarterly")return "Every 3 months";if(f.recurrence_preset==="yearly")return "Every year";return `Every ${f.recurrence_interval||1} ${f.recurrence_unit||"month"}${Number(f.recurrence_interval||1)===1?"":"s"}`;}
function statusTone(s){return s==="active"?"border-[#748267]/20 bg-[#748267]/[0.06] text-[#607057]":s==="paused"?"border-[#C08A4A]/20 bg-[#C08A4A]/[0.06] text-[#76583A]":"border-black/[0.08] bg-black/[0.025] text-[#777169]";}
function Input({label,hint,children}){return <label className="block"><span className="text-[9px] font-medium text-[#4E4943]">{label}</span>{hint?<span className="ml-2 text-[8px] text-[#99928A]">{hint}</span>:null}{children}</label>;}

export default function ServicePlansPage(){
 const params=useParams(),{organization,loading:orgLoading}=useOrganizationRuntime(),organizationId=params?.organizationId||organization?.id||"";
 const [customers,setCustomers]=useState([]),[technicians,setTechnicians]=useState([]),[templates,setTemplates]=useState([]),[taxCodes,setTaxCodes]=useState([]),[plans,setPlans]=useState([]),[form,setForm]=useState({...EMPTY});
 const [step,setStep]=useState(0),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{if(!organizationId)return;setLoading(true);setError("");try{const [cr,pr,er,tr,xr]=await Promise.all([fetch(`/api/commercial/customers?organizationId=${encodeURIComponent(organizationId)}&limit=500`,{cache:"no-store"}),fetch(`/api/service-management/plans?organizationId=${encodeURIComponent(organizationId)}&limit=500`,{cache:"no-store"}),fetch("/api/people/directory",{cache:"no-store"}).catch(()=>null),fetch(`/api/service-management/execution-templates?organizationId=${encodeURIComponent(organizationId)}&industry_key=pest_control&status=active&limit=500`,{cache:"no-store"}),fetch(`/api/finance/tax-codes?organizationId=${encodeURIComponent(organizationId)}`,{cache:"no-store"}).catch(()=>null)]);const [cj,pj,ej,tj,xj]=await Promise.all([cr.json().catch(()=>({})),pr.json().catch(()=>({})),er?.json().catch(()=>({}))||{},tr.json().catch(()=>({})),xr?.json().catch(()=>({}))||{}]);if(!cr.ok||!cj.success)throw new Error(cj.error||"Customers could not be loaded.");if(!pr.ok||!pj.success)throw new Error(pj.error||"Service plans could not be loaded.");if(!tr.ok||!tj.success)throw new Error(tj.error||"Treatment protocols could not be loaded.");setCustomers(cj.rows||[]);setPlans(pj.rows||[]);setTemplates(tj.rows||[]);setTechnicians(er?.ok&&ej?.success&&ej.organizationId===organizationId?(ej.employees||[]).filter((e)=>e.active!==false&&e.employment):[]);setTaxCodes(xr?.ok&&xj?.success?(xj.taxCodes||xj.rows||[]):[]);}catch(e){setError(e.message||"Pest Control service setup could not be loaded.");}finally{setLoading(false);}},[organizationId]);
 useEffect(()=>{load();},[load]);
 const customer=useMemo(()=>customers.find((r)=>(r.party_id||r.id)===form.customer_party_id)||null,[customers,form.customer_party_id]);
 const template=useMemo(()=>templates.find((r)=>r.id===form.execution_template_id)||null,[templates,form.execution_template_id]);
 const technician=useMemo(()=>technicians.find((r)=>r.id===form.preferred_staff_id)||null,[technicians,form.preferred_staff_id]);
 const required=Array.isArray(template?.required_qualification_codes)?template.required_qualification_codes:[];
 const active=plans.filter((p)=>p.status==="active"), overdue=active.filter((p)=>p.next_service_at&&new Date(p.next_service_at).getTime()<Date.now());
 function update(name,value){setForm((c)=>({...c,[name]:value}));setError("");}
 function chooseCustomer(value){const row=customers.find((r)=>(r.party_id||r.id)===value)||null,site=row?.shipping_address||row?.address||row?.billing_address||"";setForm((c)=>({...c,customer_party_id:value,customer_location_name:c.customer_party_id===value?c.customer_location_name:site}));setError("");}
 function validate(i){if(i===0&&(!form.customer_party_id||!text(form.customer_location_name)))return "Choose the customer and confirm the service site.";if(i===1&&(!text(form.service_name)||!form.execution_template_id))return "Name the service and choose its treatment protocol.";if(i===2&&!iso(form.first_service_at))return "Choose when the first service should happen.";if(i===4&&["per_visit","recurring"].includes(form.billing_mode)&&(form.billing_amount===""||!text(form.billing_currency_code)))return "Enter price and currency.";return "";}
 function next(){const problem=validate(step);if(problem){setError(problem);return;}setStep((s)=>Math.min(5,s+1));}
 async function createPlan(){for(let i=0;i<5;i+=1){const problem=validate(i);if(problem){setStep(i);setError(problem);return;}}setSaving(true);setError("");setNotice("");try{const first=iso(form.first_service_at);const r=await fetch("/api/service-management/plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId,customer_party_id:form.customer_party_id,customer_location_name:text(form.customer_location_name),service_name:text(form.service_name),service_category:form.service_category||"preventive_pest_control",industry_key:"pest_control",execution_template_id:form.execution_template_id,preferred_staff_id:technician?.id||null,preferred_staff_name:technician?.name||null,first_service_at:first,contract_start:first,contract_end:iso(form.contract_end),duration_minutes:Number(form.duration_minutes)||60,recurrence:{preset:form.recurrence_preset,interval:Number(form.recurrence_interval)||1,unit:form.recurrence_unit},billing:{mode:form.billing_mode,amount:form.billing_amount===""?null:Number(form.billing_amount),currency_code:text(form.billing_currency_code).toUpperCase()||null,due_days:Number(form.billing_due_days)||0,tax_code_id:form.billing_tax_code_id||null},notes:text(form.notes)||null})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||"Service plan could not be created.");setForm({...EMPTY});setStep(0);setNotice("Service plan created. Generate the first governed visit when it should enter Dispatch.");await load();}catch(e){setError(e.message||"Service plan could not be created.");}finally{setSaving(false);}}
 async function generateVisit(plan){setSaving(true);setError("");setNotice("");try{const r=await fetch(`/api/service-management/plans/${plan.id}/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||"Next visit could not be generated.");setNotice(j.generated?"Next governed visit created in Operations and ready for Dispatch.":"No duplicate visit was created; the occurrence already exists or the contract is complete.");await load();}catch(e){setError(e.message||"Next visit could not be generated.");}finally{setSaving(false);}}
 async function setStatus(plan,status){setSaving(true);setError("");try{const r=await fetch(`/api/service-management/plans/${plan.id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId,status})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||"Plan status could not be changed.");setNotice(status==="paused"?"Future recurring generation paused. Existing work is unchanged.":"Recurring plan reactivated.");await load();}catch(e){setError(e.message||"Plan status could not be changed.");}finally{setSaving(false);}}
 if(orgLoading)return <div className="min-h-[420px] bg-[#F7F6F3] p-8 text-sm text-[#77736C]">Preparing Pest Control service plans…</div>;
 return <main className="min-h-[calc(100vh-61px)] bg-[#F7F6F3] px-4 py-5 text-[#201E1B] md:px-7 lg:px-9 lg:py-7"><div className="mx-auto max-w-[1580px]">
  <header className="flex flex-wrap items-end justify-between gap-4 border-b border-black/[0.07] pb-5"><div><Link href={`/workspace/${encodeURIComponent(organizationId)}/operations/field-service`} className="inline-flex items-center gap-1.5 text-[9px] text-[#8D867E]"><ArrowLeft size={10}/> Pest Control</Link><div className="mt-3 text-[9px] font-medium uppercase tracking-[0.16em] text-[#9A744B]">Recurring service</div><h1 className="mt-1 text-[28px] font-medium tracking-[-0.04em]">Service plans</h1><p className="mt-1 max-w-3xl text-[11px] leading-5 text-[#777169]">Define the customer commitment once. Each generated visit snapshots the protocol and goes through governed Dispatch eligibility.</p></div><div className="flex gap-2"><Link href={`/workspace/${encodeURIComponent(organizationId)}/operations/dispatch`} className="rounded-xl border border-black/[0.08] bg-white px-3.5 py-2.5 text-[9px]">Dispatch</Link><Link href={`/workspace/${encodeURIComponent(organizationId)}/operations/field-service/execution-templates`} className="rounded-xl border border-[#D6A66A]/30 bg-[#D6A66A]/[0.07] px-3.5 py-2.5 text-[9px] text-[#725434]">Treatment protocols</Link><button onClick={load} className="inline-flex items-center gap-1 rounded-xl border border-black/[0.08] bg-white px-3.5 py-2.5 text-[9px]"><RefreshCw size={10} className={loading?"animate-spin":""}/>Refresh</button></div></header>
  {error?<div className="mt-4 rounded-xl border border-[#B36B52]/20 bg-[#B36B52]/[0.05] px-4 py-3 text-[10px] text-[#8B4937]">{error}</div>:null}{notice?<div className="mt-4 rounded-xl border border-[#748267]/18 bg-[#748267]/[0.05] px-4 py-3 text-[10px] text-[#607057]">{notice}</div>:null}
  <section className="mt-5 grid gap-3 sm:grid-cols-3">{[["Active plans",active.length],["Scheduling attention",overdue.length],["Active protocols",templates.length]].map(([l,v])=><div key={l} className="rounded-2xl border border-black/[0.07] bg-white p-4"><div className="text-[8px] uppercase tracking-[0.1em] text-[#948D84]">{l}</div><div className="mt-2 text-[24px] font-medium">{v}</div></div>)}</section>
  <div className="mt-5 grid gap-5 xl:grid-cols-[650px_minmax(0,1fr)]"><section className="overflow-hidden rounded-2xl border border-black/[0.075] bg-white"><div className="border-b border-black/[0.06] px-5 py-4"><div className="text-[9px] uppercase tracking-[0.13em] text-[#9A744B]">Create service plan</div><h2 className="mt-1 text-[18px] font-medium">Set up recurring work</h2></div><div className="grid grid-cols-6 border-b border-black/[0.06] bg-[#FBFAF8]">{STEPS.map(([id,label],i)=><button key={id} onClick={()=>i<=step&&setStep(i)} className={`px-2 py-3 ${i===step?"bg-white":""}`}><span className={`mx-auto flex h-5 w-5 items-center justify-center rounded-full text-[8px] ${i<step?"bg-[#748267] text-white":i===step?"bg-[#D6A66A]":"bg-[#ECE9E4] text-[#958F87]"}`}>{i<step?<Check size={9}/>:i+1}</span><span className="mt-1 block truncate text-[7px] text-[#817A72]">{label}</span></button>)}</div><div className="min-h-[410px] p-5">
   {step===0?<div className="space-y-4"><div className="flex items-center gap-2 text-[12px] font-medium"><MapPin size={13}/>Where are we servicing?</div><Input label="Customer"><select value={form.customer_party_id} onChange={(e)=>chooseCustomer(e.target.value)} className={cls}><option value="">Choose customer…</option>{customers.map((r)=><option key={r.party_id||r.id} value={r.party_id||r.id}>{r.customer_name||r.display_name||r.name}</option>)}</select></Input><Input label="Service site"><textarea value={form.customer_location_name} onChange={(e)=>update("customer_location_name",e.target.value)} className={`${cls} min-h-24`} placeholder="Hotel, villa, branch, building or full address"/></Input>{customer?<div className="rounded-xl bg-[#FBFAF8] p-3 text-[9px]">{customer.customer_name||customer.name}{customer.phone?` · ${customer.phone}`:""}</div>:null}</div>:null}
   {step===1?<div className="space-y-4"><div className="flex items-center gap-2 text-[12px] font-medium"><ShieldCheck size={13}/>What service should be performed?</div><Input label="Service name"><input value={form.service_name} onChange={(e)=>update("service_name",e.target.value)} className={cls}/></Input><Input label="Treatment protocol" hint="Snapshots into each generated visit"><select value={form.execution_template_id} onChange={(e)=>update("execution_template_id",e.target.value)} className={cls}><option value="">Choose protocol…</option>{templates.map((r)=><option key={r.id} value={r.id}>{r.name} · v{r.version||1}</option>)}</select></Input>{template?<div className="rounded-xl border border-[#D6A66A]/20 bg-[#D6A66A]/[0.04] p-3"><div className="text-[9px] font-medium text-[#725434]">{template.name}</div><div className="mt-1 text-[8px] leading-4 text-[#817A72]">{template.description||template.instructions||"Governed field protocol"}</div>{required.length?<div className="mt-2 flex flex-wrap gap-1.5">{required.map((code)=><span key={code} className="rounded-full border border-[#D6A66A]/25 bg-white px-2 py-1 text-[7px] text-[#725434]">Requires {code}</span>)}</div>:<div className="mt-2 text-[8px] text-[#8A837A]">No special People qualification required.</div>}</div>:templates.length===0?<div className="rounded-xl border border-[#B36B52]/20 bg-[#B36B52]/[0.05] p-3 text-[9px] text-[#8B4937]">Create an active treatment protocol before a customer service plan.</div>:null}</div>:null}
   {step===2?<div className="space-y-4"><div className="flex items-center gap-2 text-[12px] font-medium"><CalendarDays size={13}/>When should we service them?</div><div className="grid gap-3 sm:grid-cols-2"><Input label="First visit"><input type="datetime-local" value={form.first_service_at} onChange={(e)=>update("first_service_at",e.target.value)} className={cls}/></Input><Input label="Typical duration"><select value={form.duration_minutes} onChange={(e)=>update("duration_minutes",e.target.value)} className={cls}><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">1 hour</option><option value="90">1.5 hours</option><option value="120">2 hours</option></select></Input></div><Input label="Repeat"><select value={form.recurrence_preset} onChange={(e)=>update("recurrence_preset",e.target.value)} className={cls}><option value="weekly">Every week</option><option value="biweekly">Every 2 weeks</option><option value="monthly">Every month</option><option value="quarterly">Every 3 months</option><option value="yearly">Every year</option><option value="custom">Custom</option></select></Input>{form.recurrence_preset==="custom"?<div className="grid gap-3 sm:grid-cols-2"><Input label="Every"><input type="number" min="1" value={form.recurrence_interval} onChange={(e)=>update("recurrence_interval",e.target.value)} className={cls}/></Input><Input label="Unit"><select value={form.recurrence_unit} onChange={(e)=>update("recurrence_unit",e.target.value)} className={cls}><option value="day">Days</option><option value="week">Weeks</option><option value="month">Months</option><option value="year">Years</option></select></Input></div>:null}<Input label="Contract end" hint="Optional"><input type="datetime-local" value={form.contract_end} onChange={(e)=>update("contract_end",e.target.value)} className={cls}/></Input></div>:null}
   {step===3?<div className="space-y-4"><div className="flex items-center gap-2 text-[12px] font-medium"><UserRound size={13}/>Who normally handles this customer?</div><Input label="Preferred technician" hint="Optional — never authority"><select value={form.preferred_staff_id} onChange={(e)=>update("preferred_staff_id",e.target.value)} className={cls}><option value="">Let Dispatch decide each visit</option>{technicians.map((r)=><option key={r.id} value={r.id}>{r.name}{r.position?` · ${r.position}`:""}</option>)}</select></Input><div className="rounded-xl border border-[#D6A66A]/20 bg-[#D6A66A]/[0.04] p-4 text-[9px] leading-4 text-[#725434]">Preference never bypasses eligibility. For every generated appointment, Dispatch re-checks current People qualification evidence, availability and published shift coverage before assignment. If the preferred person is not eligible, they are shown as blocked rather than silently assigned.</div><Input label="Standing customer / site instructions" hint="Optional"><textarea value={form.notes} onChange={(e)=>update("notes",e.target.value)} className={`${cls} min-h-28`} placeholder="Gate code, contact person, sensitive areas, pets, access hours…"/></Input></div>:null}
   {step===4?<div className="space-y-4"><div className="flex items-center gap-2 text-[12px] font-medium"><CreditCard size={13}/>How is this customer billed?</div><Input label="Billing arrangement"><select value={form.billing_mode} onChange={(e)=>update("billing_mode",e.target.value)} className={cls}><option value="per_visit">Invoice each completed visit</option><option value="recurring">Recurring billing arrangement</option><option value="prepaid">Prepaid / already paid</option><option value="none">Do not bill from this plan</option></select></Input>{["per_visit","recurring"].includes(form.billing_mode)?<><div className="grid gap-3 sm:grid-cols-2"><Input label="Price"><input type="number" min="0" step="0.01" value={form.billing_amount} onChange={(e)=>update("billing_amount",e.target.value)} className={cls}/></Input><Input label="Currency"><input maxLength={3} value={form.billing_currency_code} onChange={(e)=>update("billing_currency_code",e.target.value.toUpperCase())} className={cls}/></Input></div><div className="grid gap-3 sm:grid-cols-2"><Input label="Payment due"><select value={form.billing_due_days} onChange={(e)=>update("billing_due_days",e.target.value)} className={cls}><option value="0">Due immediately</option><option value="7">7 days</option><option value="15">15 days</option><option value="30">30 days</option></select></Input><Input label="Tax rule"><select value={form.billing_tax_code_id} onChange={(e)=>update("billing_tax_code_id",e.target.value)} className={cls}><option value="">No tax rule</option>{taxCodes.map((r)=><option key={r.id} value={r.id}>{r.name||r.code||"Tax rule"}{Number.isFinite(Number(r.rate))?` · ${r.rate}%`:""}</option>)}</select></Input></div></>:<div className="rounded-xl bg-[#FBFAF8] p-4 text-[9px]">No invoice will be created from completed visits under this plan.</div>}</div>:null}
   {step===5?<div className="space-y-3"><div className="text-[12px] font-medium">Check before creating</div>{[["Customer",customer?.customer_name||customer?.name||"—"],["Site",form.customer_location_name||"—"],["Service",form.service_name],["Protocol",template?.name||"—"],["Required qualifications",required.length?required.join(", "):"None"],["First visit",date(iso(form.first_service_at))],["Frequency",frequency(form)],["Preferred technician",technician?.name||"Dispatch decides"],["Billing",form.billing_mode==="per_visit"?`${form.billing_amount||"—"} ${form.billing_currency_code} per completed visit`:form.billing_mode.replaceAll("_"," ")]].map(([l,v])=><div key={l} className="flex justify-between gap-4 rounded-xl bg-[#FBFAF8] px-3.5 py-3"><span className="text-[8px] uppercase text-[#99928A]">{l}</span><span className="max-w-[65%] text-right text-[10px] font-medium">{v}</span></div>)}<div className="rounded-xl border border-[#D6A66A]/20 bg-[#D6A66A]/[0.04] p-3 text-[9px] leading-4 text-[#725434]">Creating a plan does not start work. “Generate next visit” creates the governed occurrence that then enters Dispatch eligibility.</div></div>:null}
  </div><div className="flex justify-between border-t border-black/[0.06] bg-[#FBFAF8] p-4"><button disabled={step===0||saving} onClick={()=>setStep((s)=>Math.max(0,s-1))} className="rounded-xl border border-black/[0.08] bg-white px-4 py-2.5 text-[9px] disabled:opacity-30">Back</button>{step<5?<button onClick={next} className="inline-flex items-center gap-1 rounded-xl bg-[#2C2925] px-4 py-2.5 text-[9px] text-white">Continue <ChevronRight size={10}/></button>:<button disabled={saving} onClick={createPlan} className="rounded-xl bg-[#2C2925] px-4 py-2.5 text-[9px] text-white disabled:opacity-40">{saving?"Creating…":"Create service plan"}</button>}</div></section>
  <section className="overflow-hidden rounded-2xl border border-black/[0.075] bg-white"><div className="flex justify-between border-b border-black/[0.06] px-5 py-4"><div><div className="text-[9px] uppercase tracking-[0.13em] text-[#9A744B]">Current commitments</div><h2 className="mt-1 text-[16px] font-medium">Customer service plans</h2></div><span className="text-[10px] text-[#817A72]">{plans.length} plans</span></div><div className="divide-y divide-black/[0.05]">{plans.map((plan)=>{const delivery=plan.attributes?.service_delivery||{},rq=delivery.execution_protocol?.required_qualification_codes||delivery.required_qualification_codes||[];return <div key={plan.id} className="p-5"><div className="flex flex-wrap justify-between gap-4"><div><div className="flex gap-2"><span className={`rounded-full border px-2 py-1 text-[7px] uppercase ${statusTone(plan.status)}`}>{plan.status}</span><span className="text-[8px] text-[#99928A]">{frequency({recurrence_preset:plan.recurrence?.preset,recurrence_interval:plan.recurrence?.interval,recurrence_unit:plan.recurrence?.unit})}</span></div><div className="mt-2 text-[13px] font-medium">{plan.service_name}</div><div className="mt-1 text-[9px] text-[#756F68]">{delivery.customer_name||"Customer"} · {plan.customer_location_name||"Site not named"}</div>{Array.isArray(rq)&&rq.length?<div className="mt-2 flex flex-wrap gap-1">{rq.map((code)=><span key={code} className="rounded-full border border-[#D6A66A]/20 px-2 py-1 text-[7px] text-[#76583A]">{code}</span>)}</div>:null}</div><div className="text-right"><div className="flex justify-end gap-1 text-[8px] text-[#99928A]"><Clock3 size={9}/>Next visit</div><div className="mt-1 text-[10px] font-medium">{date(plan.next_service_at)}</div></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-black/[0.05] pt-3"><div className="text-[8px] text-[#8F877F]">Protocol · {delivery.execution_template_id?"governed":"missing"}{delivery.preferred_staff_name?` · Preferred: ${delivery.preferred_staff_name}`:""}</div><div className="flex gap-2">{plan.status==="active"?<><button disabled={saving} onClick={()=>generateVisit(plan)} className="rounded-lg border border-[#D6A66A]/30 bg-[#D6A66A]/[0.07] px-3 py-2 text-[8px] text-[#725434]">Generate next visit</button><button disabled={saving} onClick={()=>setStatus(plan,"paused")} className="rounded-lg border border-black/[0.08] px-3 py-2 text-[8px]">Pause recurring</button></>:plan.status==="paused"?<button disabled={saving} onClick={()=>setStatus(plan,"active")} className="rounded-lg border border-[#D6A66A]/30 bg-[#D6A66A]/[0.07] px-3 py-2 text-[8px] text-[#725434]">Resume recurring</button>:null}</div></div></div>;})}{!loading&&!plans.length?<div className="p-10 text-center text-[10px] text-[#8C857D]">No service plans yet. Create the first customer commitment on the left.</div>:null}</div></section></div>
 </div></main>;
}
