"use client";
import { useEffect, useState } from "react";
import { Film, Plus, RefreshCw, ShieldAlert, Trash2 } from "lucide-react";
function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function blankSegment(){return{old_start_frame:0,old_end_frame:0,new_start_frame:0};}
export default function MusicAudioPostReconformPanel({organizationId,projectId,onApplied}){
 const [session,setSession]=useState(null),[picture,setPicture]=useState({picture_asset_id:"",cut_id:"",picture_digest:"",duration_seconds:0,frame_rate:24,start_timecode:"00:00:00:00"}),[segments,setSegments]=useState([blankSegment()]),[preview,setPreview]=useState(null),[busy,setBusy]=useState(""),[error,setError]=useState("");
 useEffect(()=>{if(!organizationId||!projectId)return;let cancelled=false;(async()=>{try{const res=await fetch("/api/creative/music/multitrack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"load",organization_id:organizationId,creative_project_id:projectId})}),body=await res.json();if(!res.ok||body.success===false)throw new Error(body.error||"Audio session could not load");if(cancelled)return;setSession(body.session);const current=body.session?.picture_lock||{};setPicture({picture_asset_id:current.picture_asset_id||"",cut_id:current.cut_id||"",picture_digest:current.picture_digest||"",duration_seconds:finite(current.duration_seconds,0),frame_rate:finite(current.frame_rate,24),start_timecode:current.start_timecode||"00:00:00:00"});}catch(e){if(!cancelled)setError(e.message||"Audio session could not load");}})();return()=>{cancelled=true;};},[organizationId,projectId]);
 function updateSegment(index,key,value){setSegments(rows=>rows.map((row,i)=>i===index?{...row,[key]:Math.max(0,Math.round(finite(value,0)))}:row));setPreview(null);}
 async function request(action){if(!session)return;setBusy(action);setError("");try{const res=await fetch("/api/creative/music/multitrack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,organization_id:organizationId,creative_project_id:projectId,expected_revision:session.revision,picture,conform_map:segments})}),body=await res.json();if(!res.ok||body.success===false)throw new Error(body.error||"Picture reconform failed");if(action==="preview_reconform")setPreview(body.preview);else{setSession(body.session);setPreview(null);onApplied?.(body);}}catch(e){setError(e.message||"Picture reconform failed");}finally{setBusy("");}}
 if(!projectId)return null;
 return <section className="border-b border-white/7 bg-[#090909] px-4 py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[8px] font-semibold uppercase tracking-[0.18em] text-[#d6a66a]/65"><Film className="h-3.5 w-3.5"/>Picture Reconform</div><div className="mt-1 text-[10px] text-white/34">Review picture changes before moving any audio. Source WAVs are never rewritten.</div></div>{session?.picture_lock ? <div className="text-right text-[7px] text-white/20"><div>CURRENT · {session.picture_lock.cut_id}</div><div>{session.picture_lock.frame_rate} fps · {session.picture_lock.duration_seconds}s</div></div>:null}</div>
 <div className="mt-4 grid gap-2 md:grid-cols-3 xl:grid-cols-6">{[["Picture asset","picture_asset_id"],["Cut ID","cut_id"],["Picture digest","picture_digest"]].map(([label,key])=><label key={key} className="block"><div className="mb-1 text-[7px] uppercase tracking-[0.13em] text-white/18">{label}</div><input value={picture[key]} onChange={e=>{setPicture(v=>({...v,[key]:e.target.value}));setPreview(null);}} className="w-full rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[9px] text-white/55"/></label>)}<label className="block"><div className="mb-1 text-[7px] uppercase tracking-[0.13em] text-white/18">Duration s</div><input type="number" min="0.001" step="0.001" value={picture.duration_seconds} onChange={e=>{setPicture(v=>({...v,duration_seconds:Number(e.target.value)}));setPreview(null);}} className="w-full rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[9px] text-white/55"/></label><label className="block"><div className="mb-1 text-[7px] uppercase tracking-[0.13em] text-white/18">Frame rate</div><select value={picture.frame_rate} onChange={e=>{setPicture(v=>({...v,frame_rate:Number(e.target.value)}));setPreview(null);}} className="w-full rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[9px] text-white/55">{[23.976,24,25,29.97,30,48,50,59.94,60].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label className="block"><div className="mb-1 text-[7px] uppercase tracking-[0.13em] text-white/18">Start TC</div><input value={picture.start_timecode} onChange={e=>{setPicture(v=>({...v,start_timecode:e.target.value}));setPreview(null);}} className="w-full rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[9px] text-white/55"/></label></div>
 <div className="mt-4"><div className="mb-2 flex items-center justify-between"><div className="text-[7px] uppercase tracking-[0.14em] text-white/20">Conform map · old frame range → new start</div><button type="button" onClick={()=>{setSegments(r=>[...r,blankSegment()]);setPreview(null);}} className="inline-flex items-center gap-1 rounded-lg border border-white/7 px-2 py-1 text-[7px] text-white/30"><Plus className="h-3 w-3"/>Segment</button></div><div className="space-y-1.5">{segments.map((row,index)=><div key={index} className="grid grid-cols-[1fr_1fr_1fr_auto] gap-1.5"><input type="number" min="0" value={row.old_start_frame} onChange={e=>updateSegment(index,"old_start_frame",e.target.value)} className="rounded-lg border border-white/7 bg-black/25 px-2 py-1.5 text-[8px] text-white/45" placeholder="old start"/><input type="number" min="0" value={row.old_end_frame} onChange={e=>updateSegment(index,"old_end_frame",e.target.value)} className="rounded-lg border border-white/7 bg-black/25 px-2 py-1.5 text-[8px] text-white/45" placeholder="old end"/><input type="number" min="0" value={row.new_start_frame} onChange={e=>updateSegment(index,"new_start_frame",e.target.value)} className="rounded-lg border border-white/7 bg-black/25 px-2 py-1.5 text-[8px] text-white/45" placeholder="new start"/><button type="button" disabled={segments.length===1} onClick={()=>{setSegments(r=>r.filter((_,i)=>i!==index));setPreview(null);}} className="rounded-lg border border-white/7 px-2 text-white/20 disabled:opacity-20"><Trash2 className="h-3 w-3"/></button></div>)}</div></div>
 {error?<div className="mt-3 rounded-lg border border-red-300/10 bg-red-400/[0.02] px-3 py-2 text-[8px] text-red-100/55">{error}</div>:null}
 {preview?<div className="mt-3 rounded-xl border border-[#d6a66a]/12 bg-[#d6a66a]/[0.025] p-3"><div className="flex items-center gap-2 text-[8px] text-[#efd29f]/65"><ShieldAlert className="h-3.5 w-3.5"/>Reconform impact review</div><div className="mt-2 grid grid-cols-2 gap-2 text-[8px] text-white/35 md:grid-cols-5"><span>{preview.moved_clip_count} clips move</span><span>{preview.moved_automation_point_count} automation points move</span><span>{preview.moved_sound_object_count || 0} sound objects move</span><span>{preview.editorial_approvals_will_invalidate} editorial approvals reset</span><span>Delivery seal invalidated</span></div><div className="mt-2 text-[7px] text-white/20">No source audio rewrite · current revision remains untouched until Apply.</div></div>:null}
 <div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={Boolean(busy)} onClick={()=>request("preview_reconform")} className="inline-flex items-center gap-1.5 rounded-lg border border-white/8 px-3 py-2 text-[8px] text-white/42 disabled:opacity-25"><RefreshCw className={`h-3 w-3 ${busy==="preview_reconform"?"animate-spin":""}`}/>Review impact</button><button type="button" disabled={!preview||Boolean(busy)} onClick={()=>request("reconform_picture")} className="rounded-lg border border-[#d6a66a]/25 bg-[#d6a66a]/10 px-3 py-2 text-[8px] font-semibold text-[#efd29f]/70 disabled:opacity-25">Apply reconform</button></div></section>;
}
