"use client";
import { useEffect, useState } from "react";
import { AudioLines, Save, ShieldCheck } from "lucide-react";
import { ensureAudioPostMixBuses, validateAudioPostMix } from "@/lib/creative/music/runtime/CreativeAudioPostMixRuntime";
function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
export default function MusicAudioPostMixPanel({organizationId,projectId,onApplied}){
 const [session,setSession]=useState(null),[validation,setValidation]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!organizationId||!projectId)return;let cancelled=false;(async()=>{try{const r=await fetch("/api/creative/music/multitrack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"load",organization_id:organizationId,creative_project_id:projectId})}),b=await r.json();if(!r.ok||b.success===false)throw new Error(b.error||"Audio Post mix could not load");if(!cancelled){const next=ensureAudioPostMixBuses(b.session);setSession(next);setValidation(validateAudioPostMix(next));}}catch(e){if(!cancelled)setError(e.message||"Audio Post mix could not load");}})();return()=>{cancelled=true;};},[organizationId,projectId]);
 function updatePolicy(values){setSession(current=>{const next=structuredClone(current);next.audio_post_mix={...(next.audio_post_mix||{}),...values,dialogue_ducking:{...(next.audio_post_mix?.dialogue_ducking||{}),...(values.dialogue_ducking||{})}};setValidation(validateAudioPostMix(next));return next;});}
 async function save(){if(!session||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/creative/music/multitrack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",organization_id:organizationId,creative_project_id:projectId,session})}),b=await r.json();if(!r.ok||b.success===false)throw new Error(b.error||"Audio Post mix could not save");setSession(b.session);setValidation(validateAudioPostMix(b.session));onApplied?.(b);}catch(e){setError(e.message||"Audio Post mix could not save");}finally{setBusy(false);}}
 if(!projectId)return null;const policy=session?.audio_post_mix||{},duck=policy.dialogue_ducking||{};
 return <section className="border-b border-white/7 bg-[#090807] px-4 py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[8px] font-semibold uppercase tracking-[.18em] text-[#d6a66a]/65"><AudioLines className="h-3.5 w-3.5"/>Re-recording Mix</div><div className="mt-1 text-[10px] text-white/34">DX / VO / ADR priority over MX / FX / Foley / Ambience with linked surround-safe ducking.</div></div><button type="button" disabled={!session||busy||validation?.success===false} onClick={save} className="inline-flex items-center gap-1.5 rounded-lg border border-[#d6a66a]/25 bg-[#d6a66a]/10 px-3 py-2 text-[8px] text-[#efd29f]/70 disabled:opacity-25"><Save className="h-3 w-3"/>{busy?"Saving…":"Save post mix"}</button></div>
 {error?<div className="mt-3 text-[8px] text-red-100/55">{error}</div>:null}
 {session?<><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-6"><label className="rounded-lg border border-white/7 bg-black/20 p-2"><div className="text-[7px] uppercase text-white/18">Dialogue priority</div><input type="checkbox" checked={policy.dialogue_priority!==false} onChange={e=>updatePolicy({dialogue_priority:e.target.checked})} className="mt-2 accent-[#d6a66a]"/></label><label className="rounded-lg border border-white/7 bg-black/20 p-2"><div className="text-[7px] uppercase text-white/18">Ducking</div><input type="checkbox" checked={duck.enabled!==false} onChange={e=>updatePolicy({dialogue_ducking:{enabled:e.target.checked}})} className="mt-2 accent-[#d6a66a]"/></label>{[["Threshold dBFS","threshold_dbfs",-60,0,1],["Ratio","ratio",1,20,.1],["Attack ms","attack_ms",.5,500,.5],["Release ms","release_ms",10,5000,10]].map(([label,key,min,max,step])=><label key={key} className="rounded-lg border border-white/7 bg-black/20 p-2"><div className="text-[7px] uppercase text-white/18">{label}</div><input type="number" min={min} max={max} step={step} value={finite(duck[key],key==="threshold_dbfs"?-30:key==="ratio"?3:key==="attack_ms"?12:220)} onChange={e=>updatePolicy({dialogue_ducking:{[key]:Number(e.target.value)}})} className="mt-1 w-full bg-transparent text-[9px] text-white/52 outline-none"/></label>)}</div><div className="mt-3 flex flex-wrap gap-1.5">{(session.buses||[]).filter(bus=>bus.audio_post).map(bus=><span key={bus.id} className="rounded-lg border border-white/7 bg-black/20 px-2 py-1 text-[7px] text-white/30">{bus.audio_post.label} · {bus.audio_post.role}</span>)}</div><div className={`mt-3 rounded-lg border px-3 py-2 text-[8px] ${validation?.success?"border-emerald-300/10 bg-emerald-300/[.02] text-emerald-100/55":"border-amber-300/10 bg-amber-300/[.02] text-amber-100/55"}`}><div className="flex items-center gap-1.5"><ShieldCheck className="h-3 w-3"/>{validation?.success?"Re-recording mix routing ready":"Re-recording mix needs correction"}</div>{validation?.failures?.length?<div className="mt-1 text-[7px]">{validation.failures.join(" · ")}</div>:null}<div className="mt-1 text-[7px] text-white/18">Surround ducking is linked across speakers. Dialogue LFE is forbidden. Independent listening review remains required.</div></div></>:null}</section>;
}
