"use client";
import {useEffect,useMemo,useState} from "react";
import {Footprints,ScanLine,ShieldCheck} from "lucide-react";
export default function MusicFoleyContactPanel({organizationId,projectId,onApplied}){
 const [session,setSession]=useState(null),[tracks,setTracks]=useState([]),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [role,setRole]=useState("FOOT"),[surface,setSurface]=useState("GRAVEL"),[bbox,setBbox]=useState({x:0,y:0,w:100,h:100}),[sourceAsset,setSourceAsset]=useState(""),[targetTrack,setTargetTrack]=useState(""),[selectedCue,setSelectedCue]=useState("");
 useEffect(()=>{if(!organizationId||!projectId)return;(async()=>{try{const r=await fetch("/api/creative/music/multitrack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"load",organization_id:organizationId,creative_project_id:projectId})}),b=await r.json();if(!r.ok||b.success===false)throw new Error(b.error||"Foley session could not load");setSession(b.session);}catch(e){setError(e.message||"Foley session could not load");}})();},[organizationId,projectId]);
 const cues=preview?.foley_proposal?.foley_plan?.events||[],selected=cues.find(x=>x.id===selectedCue)||null,foleyTracks=useMemo(()=>(session?.tracks||[]).filter(t=>["FOLEY","EFFECTS","AMBIENCE"].includes(String(t.audio_role||"").toUpperCase())),[session]);
 async function track(){if(!session||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/creative/music/foley-tracking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organization_id:organizationId,creative_project_id:projectId,role,surface_material:role==="SURFACE"?surface:"UNKNOWN",bbox:[bbox.x,bbox.y,bbox.w,bbox.h],sample_fps:12,max_frames:1200})}),b=await r.json();if(!r.ok||b.success===false)throw new Error(b.error||"ROI tracking failed");setTracks(v=>[...v,b.track]);}catch(e){setError(e.message||"ROI tracking failed");}finally{setBusy(false);}}
 async function detect(){if(!session||tracks.length<2||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/creative/music/multitrack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"preview_foley_contacts",organization_id:organizationId,creative_project_id:projectId,expected_revision:session.revision,tracks,frame_width:1920,frame_height:1080,min_confidence:.75})}),b=await r.json();if(!r.ok||b.success===false)throw new Error(b.error||"Contact preview failed");setPreview(b);setSelectedCue(b.foley_proposal?.foley_plan?.events?.[0]?.id||"");}catch(e){setError(e.message||"Contact preview failed");}finally{setBusy(false);}}
 async function bind(){if(!selected||!sourceAsset||!targetTrack||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/creative/music/multitrack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"bind_foley_asset",organization_id:organizationId,creative_project_id:projectId,expected_revision:session.revision,cue:selected,source_asset_id:sourceAsset,target_track_id:targetTrack})}),b=await r.json();if(!r.ok||b.success===false)throw new Error(b.error||"Foley asset could not bind");setSession(b.session);onApplied?.(b);}catch(e){setError(e.message||"Foley asset could not bind");}finally{setBusy(false);}}
 return <section className="border-b border-white/7 bg-[#080808] px-4 py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[8px] font-semibold uppercase tracking-[.18em] text-[#d6a66a]/65"><Footprints className="h-3.5 w-3.5"/>Picture-aware Foley</div><div className="mt-1 text-[10px] text-white/32">Track explicit ROIs locally, derive evidence-backed contact candidates, review them, then bind real Foley to exact picture time.</div></div><div className="text-[7px] text-white/18">No semantic guessing · no provider inference</div></div>
 {error?<div className="mt-3 rounded-lg border border-red-300/10 bg-red-400/[.02] px-3 py-2 text-[8px] text-red-100/55">{error}</div>:null}
 <div className="mt-4 grid gap-3 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-xl border border-white/7 bg-black/20 p-3"><div className="flex items-center gap-2 text-[8px] uppercase tracking-[.14em] text-white/35"><ScanLine className="h-3.5 w-3.5"/>ROI tracker</div><div className="mt-3 grid grid-cols-3 gap-2"><select value={role} onChange={e=>setRole(e.target.value)} className="rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[8px] text-white/50">{["FOOT","HAND","BODY","PROP","DOOR","VEHICLE","MACHINERY","SURFACE"].map(v=><option key={v}>{v}</option>)}</select>{role==="SURFACE"?<select value={surface} onChange={e=>setSurface(e.target.value)} className="rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[8px] text-white/50">{["WOOD","TILE","CONCRETE","GRAVEL","GRASS","METAL","WATER","CARPET","DIRT","UNKNOWN"].map(v=><option key={v}>{v}</option>)}</select>:<div/>}<button type="button" disabled={busy} onClick={track} className="rounded-lg border border-[#d6a66a]/18 bg-[#d6a66a]/[.05] px-2 py-1.5 text-[8px] text-[#efd29f]/60 disabled:opacity-30">{busy?"Working…":"Track ROI"}</button>{["x","y","w","h"].map(k=><label key={k}><div className="mb-1 text-[7px] uppercase text-white/18">{k}</div><input type="number" value={bbox[k]} onChange={e=>setBbox(v=>({...v,[k]:Number(e.target.value)}))} className="w-full rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[8px] text-white/50"/></label>)}</div><div className="mt-3 flex flex-wrap gap-1.5">{tracks.map(t=><span key={t.id} className="rounded-lg border border-white/7 px-2 py-1 text-[7px] text-white/28">{t.role} · {t.samples?.length||0} samples</span>)}</div><button type="button" disabled={tracks.length<2||busy} onClick={detect} className="mt-3 rounded-lg border border-white/8 px-2.5 py-1.5 text-[8px] text-white/40 disabled:opacity-25">Derive contact candidates</button></div>
 <div className="rounded-xl border border-white/7 bg-black/20 p-3"><div className="flex items-center gap-2 text-[8px] uppercase tracking-[.14em] text-white/35"><ShieldCheck className="h-3.5 w-3.5"/>Human review & bind</div><div className="mt-2 text-[8px] text-white/24">{preview?(preview.contact_evidence?.event_count||0)+" evidence-backed contact events":"Run contact detection first."}</div>{cues.length?<><select value={selectedCue} onChange={e=>setSelectedCue(e.target.value)} className="mt-3 w-full rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[8px] text-white/50">{cues.map(c=><option key={c.id} value={c.id}>{c.category+" · "+Number(c.start_seconds).toFixed(3)+"s · "+(c.surface_material||"UNKNOWN")+" · "+Math.round((c.evidence_confidence||0)*100)+"%"}</option>)}</select><input value={sourceAsset} onChange={e=>setSourceAsset(e.target.value)} placeholder="Real Foley source asset ID" className="mt-2 w-full rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[8px] text-white/50"/><select value={targetTrack} onChange={e=>setTargetTrack(e.target.value)} className="mt-2 w-full rounded-lg border border-white/8 bg-black/30 px-2 py-2 text-[8px] text-white/50"><option value="">Target Foley / FX track</option>{foleyTracks.map(t=><option key={t.id} value={t.id}>{(t.name||t.id)+" · "+t.audio_role}</option>)}</select><button type="button" disabled={!selected||!sourceAsset||!targetTrack||busy} onClick={bind} className="mt-3 rounded-lg border border-emerald-300/14 px-2.5 py-1.5 text-[8px] text-emerald-100/55 disabled:opacity-25">Approve cue & bind real Foley asset</button></>:null}</div></div></section>;
}