"use client";
import { useEffect, useState } from "react";
import { RotateCcw, Sparkles } from "lucide-react";

export default function MusicMixEngineerPanel({ organizationId, projectId, onApplied }) {
  const [plan,setPlan]=useState(null),[revision,setRevision]=useState(0),[undoAvailable,setUndoAvailable]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[vocalProduction,setVocalProduction]=useState(null),[vocalQc,setVocalQc]=useState(null);
  async function request(action,extra={}){if(!organizationId||!projectId||busy)return null;setBusy(true);setError("");try{const response=await fetch("/api/creative/music/mix-engineer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,organization_id:organizationId,creative_project_id:projectId,...extra})});const body=await response.json();if(!response.ok||body.success===false)throw new Error(body.error||"Mix Engineer failed");if(body.plan)setPlan(body.plan);if(Number.isFinite(Number(body.revision)))setRevision(Number(body.revision));if(typeof body.undo_available==="boolean")setUndoAvailable(body.undo_available);return body;}catch(cause){setError(cause?.message||"Mix Engineer failed");return null;}finally{setBusy(false);}}
  useEffect(()=>{void request("analyze");},[organizationId,projectId]);
  async function apply(){const result=await request("apply",{expected_revision:revision});if(result){const refreshed=await request("analyze");onApplied?.(refreshed||result);}}
  async function undo(){const result=await request("undo");if(result){const refreshed=await request("analyze");onApplied?.(refreshed||result);}}
  async function rebase(){const result=await request("rebase",{expected_revision:revision});if(result){const refreshed=await request("analyze");onApplied?.(refreshed||result);}}
  async function buildVocalProduction(){if(!organizationId||!projectId||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/creative/music/multitrack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"apply_vocal_production",organization_id:organizationId,creative_project_id:projectId,expected_revision:revision})}),body=await response.json();if(!response.ok||body.success===false)throw new Error(body.error||"Vocal production routing failed");setVocalProduction(body.vocal_production||null);setVocalQc(body.vocal_production_qc||null);setRevision(Number(body.revision||revision));const refreshed=await request("analyze");onApplied?.(refreshed||body);}catch(cause){setError(cause?.message||"Vocal production routing failed");}finally{setBusy(false);}}
  if(!projectId)return null;
  return <section className="border-b border-white/8 bg-[#0a0908] px-5 py-4 text-white">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.2em] text-[#d6a66a]/70"><Sparkles className="h-3.5 w-3.5"/>Mix Engineer</div><div className="mt-1 text-sm font-medium text-white/75">Evidence-driven professional mix decisions</div><div className="mt-1 max-w-3xl text-[9px] leading-4 text-white/28">Builds hierarchy, vocal focus, low-end control, dynamics, saturation and shared depth from the real session. Changes are non-destructive, revision-bound and require listening review.</div></div><div className="flex gap-2"><button disabled={busy} onClick={buildVocalProduction} className="rounded-lg border border-white/8 px-3 py-2 text-[9px] text-white/38 disabled:opacity-25">Build vocal production</button>{plan?.status==="REBASE_REQUIRED"?<button disabled={busy} onClick={rebase} className="rounded-lg border border-amber-200/20 bg-amber-100/[.05] px-3 py-2 text-[9px] text-amber-100/65 disabled:opacity-25">Use current mix as new baseline</button>:<button disabled={busy||plan?.status==="NO_NEW_MIX_CHANGES"||!plan?.track_decisions?.some(row=>row.changed)} onClick={apply} className="rounded-lg border border-[#d6a66a]/30 bg-[#d6a66a]/10 px-3 py-2 text-[9px] text-[#efd29f] disabled:opacity-25">{busy?"Working…":plan?.status==="NO_NEW_MIX_CHANGES"?"Mix plan already applied":"Apply mix plan"}</button>}<button disabled={busy||!undoAvailable} onClick={undo} className="inline-flex items-center gap-1.5 rounded-lg border border-white/8 px-3 py-2 text-[9px] text-white/35 disabled:opacity-25"><RotateCcw className="h-3 w-3"/>Undo</button></div></div>
    {error?<div className="mt-3 text-[9px] text-red-100/60">{error}</div>:null}{vocalProduction?<div className="mt-3 rounded-lg border border-[#d6a66a]/12 bg-[#d6a66a]/[.025] px-3 py-2 text-[8px] text-[#efd29f]/55">Vocal production · {vocalProduction.vocal_track_count} tracks · {vocalProduction.managed_bus_count} managed buses · explicit roles · manual sends preserved · listening review required</div>:null}{vocalQc?<div className={`mt-2 rounded-lg border px-3 py-2 text-[8px] ${vocalQc.technical_ready_for_listening_review?"border-emerald-300/10 bg-emerald-300/[.02] text-emerald-100/55":"border-amber-300/10 bg-amber-300/[.02] text-amber-100/55"}`}>Vocal QC · {vocalQc.technical_ready_for_listening_review?"TECHNICALLY READY FOR LISTENING REVIEW":`${vocalQc.blockers.length} blocker(s)`} · {vocalQc.review_flags.length} measured review flag(s){vocalQc.blockers.length?<div className="mt-1 text-[7px] opacity-70">{vocalQc.blockers.join(" · ")}</div>:null}{vocalQc.vocal_stack_alignment?.stack_track_count?<div className="mt-1 text-[7px] opacity-70">Stack timing · {vocalQc.vocal_stack_alignment.tracks.map(row=>`${row.role} ${row.phrase_pair_count} pairs${row.median_absolute_start_offset_ms!=null?` · median ${row.median_absolute_start_offset_ms}ms`:""}`).join(" · ")}</div>:null}<div className="mt-1 text-[7px] opacity-60">No artistic quality score, automatic timing correction or automatic release approval is inferred.</div></div>:null}{plan?.status==="REBASE_REQUIRED"?<div className="mt-3 rounded-lg border border-amber-100/10 bg-amber-100/[.025] px-3 py-2 text-[8px] leading-4 text-amber-100/50">The session changed after the last Mix Engineer apply. Avantiqo will not overwrite those edits. Confirm the current mix as the new baseline before generating another plan.</div>:null}
    {plan?<><div className="mt-3 text-[8px] text-white/22">Measured audio evidence: {plan.measured_track_count||0}/{(plan.track_decisions||[]).length} active tracks</div><div className="mt-3 grid gap-2 lg:grid-cols-4">{(plan.track_decisions||[]).filter(row=>row.changed).slice(0,8).map(row=><div key={row.track_id} className="rounded-xl border border-white/7 bg-white/[.018] p-3"><div className="text-[8px] uppercase tracking-[.12em] text-[#d6a66a]/55">{row.role}</div><div className="mt-1 truncate text-[10px] font-medium text-white/60">{row.track_name}</div><div className="mt-2 text-[8px] leading-4 text-white/24">{row.decisions.join(" · ")}</div>{row.evidence?<div className="mt-2 border-t border-white/6 pt-2 text-[7px] leading-3 text-white/18">Mean {row.evidence.mean_db??"—"} dBFS · peak {row.evidence.peak_dbfs??"—"} dBFS · crest {row.evidence.crest_proxy_db??"—"} dB · sub/low-mid {row.evidence.sub_vs_lowmid_db??"—"} dB · box/warmth {row.evidence.boxiness_vs_warmth_db??"—"} dB · box/presence {row.evidence.boxiness_vs_presence_db??"—"} dB · presence/low-mid {row.evidence.presence_vs_lowmid_db??"—"} dB · corr {row.evidence.stereo_correlation??"—"} · mono Δ {row.evidence.mono_fold_down_loss_db??"—"} dB · LUFS {row.evidence.integrated_lufs??"—"} · TP {row.evidence.true_peak_dbtp??"—"} dBTP · LRA {row.evidence.loudness_range_lu??"—"} LU · harsh P90 {row.evidence.dynamic_harshness?.p90_harshness_vs_body_db??"—"} dB · low corr {row.evidence.low_stereo_correlation??"—"} · low mono Δ {row.evidence.low_mono_fold_down_loss_db??"—"} dB</div>:<div className="mt-2 text-[7px] text-white/14">Role-only fallback; source evidence unavailable.</div>}</div>)}</div></>:null}
    {plan?.relationship_decisions?.length?<div className="mt-3 rounded-xl border border-white/7 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.14em] text-[#d6a66a]/50">Inter-track relationships</div><div className="mt-2 space-y-1 text-[8px] leading-4 text-white/28">{plan.relationship_decisions.map((item,index)=><div key={`${item.type}-${index}`}>{item.type==="VOCAL_TEMPORAL_COMPETITION"?`Vocal pocket · ${item.overlap_window_count} synchronized windows · competition ${item.presence_score}`:item.type==="LOW_END_TEMPORAL_COMPETITION"?`Low-end separation · ${item.overlap_window_count} synchronized windows · competition ${item.low_score}`:item.type==="VOCAL_MASKING_PROXY"?`Vocal pocket · static presence proxy ${item.presence_score}`:`Low-end separation · static overlap proxy ${item.low_score}`}</div>)}</div><div className="mt-2 text-[7px] text-white/16">Synchronized clip windows are preferred when available; otherwise Avantiqo falls back to independent-track spectral evidence. This measures temporal spectral competition, not psychoacoustic masking. Audition remains required.</div></div>:null}
    {plan?.automation_plan?.lanes?.length?<div className="mt-3 rounded-xl border border-white/7 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.14em] text-[#d6a66a]/50">Section automation</div><div className="mt-1 text-[7px] text-white/17">{plan.automation_plan.section_count} arrangement sections · persisted section intensity · short transition ramps</div><div className="mt-2 grid gap-1.5 sm:grid-cols-2">{plan.automation_plan.lanes.map((lane)=><div key={lane.id} className="rounded-lg border border-white/6 px-2.5 py-2"><div className="text-[8px] text-white/42">{lane.track_name} · {lane.decision}</div><div className="mt-1 text-[7px] text-white/18">{lane.points.length} points · max ±{lane.max_delta_db} dB{lane.micro_dynamics?.measured?` · ${lane.micro_dynamics.observation_count} measured vocal/accompaniment windows`:""}{lane.blocked_by_existing_manual_lane?" · manual lane preserved":""}</div></div>)}</div><div className="mt-2 text-[7px] leading-3 text-white/16">Existing manual gain automation is never overwritten. Vocal micro-rides use measured source envelopes mapped through the clip timeline and remain bounded; artistic listening still decides whether the movement feels right. Reverb depth now follows approved section intensity, and delay throws are only created at measured active vocal transitions. Existing manual send automation is preserved.</div></div>:null}
    {plan?.issues?.length?<div className="mt-3 text-[8px] leading-4 text-amber-100/45">{plan.issues.map(issue=>issue.message).join(" · ")}</div>:null}
  </section>;
}
