import Image from "next/image";

export const metadata={title:"Creative Studios | Avantiqo",description:"Avantiqo Creative Studios: complete production systems for image, video and music."};
const studios=[
  ["Image Studio","From concept to campaign.","Research, art direction, image production, critique, repair, typography and final delivery.","/creative-studios/image"],
  ["Video Studio","From story to screen.","Story development, shot design, production, dailies, repair, edit, post-production and mastering.","/creative-studios/video"],
  ["Music Studio","From idea to full production.","Composition, arrangement, edit, remix, stems, vocal work, SFX, mix and master.","/creative-studios/music"],
];
const process=[["01","Brief"],["02","Research"],["03","Direction"],["04","Creation"],["05","Review"],["06","Repair"],["07","Delivery"]];
function Arrow({className=""}){return <svg viewBox="0 0 20 20" className={className} fill="none"><path d="M4 10h11M11 6l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function Core(){return <div className="relative mx-auto min-h-[580px] w-full overflow-hidden rounded-[30px] border border-white/[0.08] bg-[#090908] shadow-[0_42px_120px_rgba(35,22,10,.28)]"><Image src="/branding/avantiqo-intelligence-core-hero.webp" alt="Avantiqo Intelligence Core" fill sizes="(max-width: 1024px) 100vw, 54vw" className="object-cover object-center" priority/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.08),transparent_55%,rgba(0,0,0,.78))]"/><div className="absolute left-5 top-5 rounded-full border border-[#D6A66A]/25 bg-black/45 px-3 py-1.5 text-[8px] font-semibold uppercase tracking-[0.2em] text-[#E5C08A] backdrop-blur-xl">AVANTIQO INTELLIGENCE CORE</div><div className="absolute inset-x-5 bottom-5 border-t border-white/[0.1] pt-4"><div className="text-[8px] font-semibold uppercase tracking-[0.22em] text-[#D6A66A]">People / ideas / possibilities</div><div className="mt-1 text-[10px] text-white/45">One intelligence layer. Three world-class production disciplines.</div></div></div>}

export default function Page(){return <main className="min-h-screen bg-[#F7F6F3] text-[#191919]">
<header className="sticky top-0 z-50 border-b border-black/[0.07] bg-[#F7F6F3]/95 backdrop-blur-xl"><div className="mx-auto flex h-[64px] max-w-[1460px] items-center justify-between px-5 sm:px-7 lg:px-10"><a href="/" className="flex items-center gap-3"><span className="rounded-xl bg-[#171716] px-3 py-2 shadow-[0_4px_16px_rgba(0,0,0,.08)]"><Image src="/branding/avantiqo-wordmark.png" alt="Avantiqo" width={126} height={10} className="h-[10px] w-auto object-contain" priority/></span><div className="hidden text-[7px] font-semibold uppercase tracking-[0.18em] text-[#9A744B] sm:block">Creative Studios</div></a><nav className="flex items-center gap-1"><a href="#studios" className="hidden rounded-lg px-3 py-2 text-[10px] text-[#6C6963] hover:bg-white md:inline-flex">Studios</a><a href="/developers" className="hidden rounded-lg px-3 py-2 text-[10px] text-[#6C6963] hover:bg-white lg:inline-flex">Developers</a><a href="/login" className="ml-1 inline-flex h-9 items-center gap-2 rounded-xl bg-[#171716] px-4 text-[10px] font-semibold text-white">Login <Arrow className="h-3 w-3"/></a></nav></div></header>
<section className="border-b border-black/[0.06]"><div className="mx-auto grid max-w-[1460px] gap-12 px-5 py-16 sm:px-7 lg:grid-cols-[.88fr_1.12fr] lg:items-center lg:px-10 lg:py-24"><div className="max-w-[690px]"><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#9A744B]">Avantiqo Creative Studios</p><h1 className="mt-5 text-[50px] font-medium leading-[.97] tracking-[-0.06em] text-[#181817] sm:text-[64px] lg:text-[76px]">From imagination to real-world impact.</h1><p className="mt-7 max-w-xl text-[17px] leading-8 text-[#625F59]">Three professional creative production systems for image, video and music. Avantiqo carries the work from brief and research through direction, production, review, repair and final delivery.</p><div className="mt-8 flex flex-wrap gap-2.5"><a href="#studios" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#171716] px-5 text-[11px] font-semibold text-white">Explore the studios <Arrow className="h-3.5 w-3.5"/></a><a href="#process" className="inline-flex h-11 items-center rounded-xl border border-black/[0.09] bg-white px-5 text-[11px] font-semibold text-[#56514A]">See production flow</a></div></div><div className="relative overflow-hidden rounded-[34px] border border-black/[0.08] bg-[#171716] p-7 shadow-[0_34px_95px_rgba(37,31,24,.16)] sm:p-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_18%,rgba(214,166,106,.18),transparent_30%)]"/><Core/></div></div></section>
<section id="studios" className="border-b border-black/[0.06] bg-[#FBFAF8]"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">Three studios. One creative system.</p><h2 className="mt-3 max-w-3xl text-[38px] font-medium leading-[1.04] tracking-[-0.045em] sm:text-[48px]">Choose the medium. Keep the intelligence.</h2><div className="mt-12 grid gap-4 lg:grid-cols-3">{studios.map(([name,title,text,href],i)=><a key={name} href={href} className="group overflow-hidden rounded-[26px] border border-black/[0.075] bg-white transition hover:-translate-y-1 hover:shadow-[0_18px_50px_rgba(60,45,30,.09)]"><div className="relative h-56 overflow-hidden bg-[#11100e]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_56%_44%,rgba(214,166,106,.34),transparent_25%),linear-gradient(135deg,#17130f,#080807_72%)]"/><div className="absolute inset-[12%] rounded-[18px] border border-white/[0.08] bg-black/15"><div className={`absolute ${i===1?'inset-x-[12%] top-[28%] h-[44%]':i===2?'inset-x-[10%] top-[30%] h-[38%]':'inset-[14%]'} border border-[#D6A66A]/20`}>{i===2?<div className="flex h-full items-center justify-center gap-[3px]">{[25,52,78,41,66,88,44,71,36,62,81,47,69,31].map((h,j)=><span key={j} className="w-[3px] rounded-full bg-[#D6A66A]/65" style={{height:`${h}%`}}/>)}</div>:null}</div></div><div className="absolute left-5 top-5 text-[8px] font-bold uppercase tracking-[0.18em] text-[#D6A66A]">0{i+1}</div><div className="absolute bottom-5 right-5 flex h-9 w-9 items-center justify-center rounded-full border border-[#D6A66A]/35 bg-black/20 text-[#D6A66A] backdrop-blur-sm"><Arrow className="h-4 w-4"/></div></div><div className="p-6"><p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#9A744B]">{name}</p><h3 className="mt-2 text-[25px] font-medium tracking-[-0.035em]">{title}</h3><p className="mt-4 text-[11px] leading-6 text-[#77716A]">{text}</p></div></a>)}</div></div></section>
<section id="process" className="border-b border-black/[0.06] bg-[#F7F6F3]"><div className="mx-auto max-w-[1320px] px-5 py-20 sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">More than generation</p><h2 className="mt-3 text-[38px] font-medium tracking-[-0.045em] sm:text-[48px]">A complete creative production path.</h2><div className="mt-10 grid gap-3 md:grid-cols-2 xl:grid-cols-7">{process.map(([n,t])=><div key={t} className="rounded-[20px] border border-black/[0.075] bg-white p-4"><div className="text-[8px] font-bold text-[#A37849]">{n}</div><div className="mt-8 text-[13px] font-semibold">{t}</div></div>)}</div></div></section>
<section className="border-b border-white/[0.06] bg-[#171716] text-white"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 py-20 sm:px-7 lg:grid-cols-[.8fr_1.2fr] lg:px-10 lg:py-24"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#D6A66A]">The Intelligence Core</p><h2 className="mt-3 text-[38px] font-medium leading-[1.04] tracking-[-0.045em] text-[#F7F4EF] sm:text-[48px]">One objective across every medium.</h2><p className="mt-5 text-[14px] leading-7 text-white/48">Image, video and music can operate separately or share the same brief, research, direction, governance and quality logic in one connected mission.</p></div><div className="grid gap-3 sm:grid-cols-3">{["Image Studio","Video Studio","Music Studio"].map((x,i)=><div key={x} className="rounded-[20px] border border-white/[0.08] bg-white/[0.025] p-5"><div className="text-[8px] font-bold text-[#D6A66A]">0{i+1}</div><div className="mt-10 text-[14px] font-semibold text-white/78">{x}</div><div className="mt-2 text-[9px] text-white/34">Connected to the same creative intelligence.</div></div>)}</div></div></section>
<section className="bg-[#F7F6F3]"><div className="mx-auto max-w-[1120px] px-5 py-20 text-center sm:px-7 lg:px-10 lg:py-24"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#9A744B]">Creative production for real business</p><h2 className="mx-auto mt-4 max-w-4xl text-[40px] font-medium leading-[1.02] tracking-[-0.05em] sm:text-[52px]">Give the Studio the objective. Let the production system do the work.</h2><div className="mt-8 flex flex-wrap justify-center gap-2.5"><a href="/login" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#171716] px-5 text-[11px] font-semibold text-white">Enter Avantiqo <Arrow className="h-3.5 w-3.5"/></a><a href="/developers" className="inline-flex h-11 items-center rounded-xl border border-black/[0.09] bg-white px-5 text-[11px] font-semibold text-[#56514A]">Developer access</a></div></div></section>
</main>}
