export const AVANTIQO_INTELLIGENCE_CREDENTIAL_PROVISIONING_CONTRACT = "AVANTIQO_INTELLIGENCE_LOCAL_ONLY_V1";
export async function provisionAvantiqoIntelligenceCredential(){ const error=new Error("AVANTIQO_CLOUD_INTELLIGENCE_CREDENTIALS_RETIRED_LOCAL_ONLY"); error.code="AVANTIQO_CLOUD_INTELLIGENCE_CREDENTIALS_RETIRED_LOCAL_ONLY"; error.status=410; throw error; }
export const AvantiqoIntelligenceCredentialProvisioningRuntime=Object.freeze({contract:AVANTIQO_INTELLIGENCE_CREDENTIAL_PROVISIONING_CONTRACT,retired:true,local_only:true,provision:provisionAvantiqoIntelligenceCredential});
export default AvantiqoIntelligenceCredentialProvisioningRuntime;
