const LOCAL_MODEL = "Qwen/Qwen3-4B-GGUF:Q4_K_M";

export const AVANTIQO_INTELLIGENCE_LOCAL_MODEL = LOCAL_MODEL;
export const AVANTIQO_INTELLIGENCE_LOCAL_CONTEXT_TOKENS = 6144;
export const AVANTIQO_INTELLIGENCE_LOCAL_CONTEXT_SAFETY_TOKENS = 384;
export const AVANTIQO_INTELLIGENCE_LOCAL_FAST_OUTPUT_CAP = 4096;
export const AVANTIQO_INTELLIGENCE_LOCAL_FRONT_OUTPUT_CAP = 640;
