export const dynamic="force-dynamic";
export const runtime="nodejs";
import {NextResponse} from "next/server";
import {requireOrganizationAccess} from "@/lib/platform/security/requireOrganizationAccess";
import {supabaseAdmin} from "@/lib/shared/supabase/admin";
import {listImageStudioFontCatalog,materializeImageStudioFont} from "@/lib/creative/stills/runtime/CreativeImageStudioFontRuntime.js";
const clean=(value)=>String(value??"").trim();
async function authorize(request){const url=new URL(request.url);const organizationId=clean(url.searchParams.get("organization_id"));const projectId=clean(url.searchParams.get("project_id"));if(!organizationId||!projectId)return{error:NextResponse.json({success:false,error:"organization_id and project_id required"},{status:400})};const access=await requireOrganizationAccess({organizationId,request});if(!access.success)return{error:NextResponse.json({success:false,error:access.error},{status:access.status||403})};const {data,error}=await supabaseAdmin.from("creative_projects").select("id,organization_id,archived").eq("id",projectId).eq("organization_id",access.organizationId).maybeSingle();if(error)throw error;if(!data||data.archived)return{error:NextResponse.json({success:false,error:"Creative project not found in organization"},{status:404})};return{organizationId:access.organizationId,projectId,url};}
export async function GET(request){try{const scope=await authorize(request);if(scope.error)return scope.error;const fontAssetId=clean(scope.url.searchParams.get("font_asset_id"));if(!fontAssetId){const catalog=await listImageStudioFontCatalog({organization_id:scope.organizationId,creative_project_id:scope.projectId});return NextResponse.json({success:true,catalog});}const font=await materializeImageStudioFont({organization_id:scope.organizationId,creative_project_id:scope.projectId,font_asset_id:fontAssetId});return new NextResponse(font.bytes,{status:200,headers:{"content-type":font.mime_type||"font/ttf","cache-control":"private, max-age=3600","x-avantiqo-font-asset-id":font.font_asset_id,"x-avantiqo-font-family":font.family,"x-avantiqo-font-contract":font.contract}});}catch(error){console.error("CREATIVE_IMAGE_STUDIO_FONT_FAILED",error);return NextResponse.json({success:false,error:error?.message||"Unable to resolve Image Studio font"},{status:/REQUIRED|NOT_RENDERABLE|NOT_FOUND/.test(error?.message||"")?400:500});}}
