export const dynamic="force-dynamic";export const runtime="nodejs";
import {NextResponse} from "next/server";
import {CreativeAssetsRuntime} from "@/lib/creative/assets/runtime/CreativeAssetsRuntime";
import * as CreativeProjectRepository from "@/lib/creative/projects/repositories/CreativeProjectRepository";
import {validateMusicSurroundPremaster} from "@/lib/creative/music/runtime/CreativeMusicSurroundValidationRuntime";
import {requireOrganizationAccess} from "@/lib/platform/security/requireOrganizationAccess";
const PERMISSIONS=Object.freeze(["creative.execute","creative.production.run","creative.*"]),KEY="music_multitrack_project";
const text=v=>String(v??"").trim();const finite=(v,f=null)=>Number.isFinite(Number(v))?Number(v):f;
export async function POST(request){try{const body=await request.json(),organizationId=text(body.organization_id),projectId=text(body.creative_project_id),assetId=text(body.asset_id);if(!organizationId)return NextResponse.json({success:false,error:"organization_id required"},{status:400});if(!assetId)return NextResponse.json({success:false,error:"asset_id required"},{status:400});const access=await requireOrganizationAccess({organizationId,request,requiredAnyPermission:PERMISSIONS});if(!access.success)return NextResponse.json({success:false,error:access.error||"forbidden"},{status:access.status||403});const project=await CreativeProjectRepository.getById(projectId);if(!project||String(project.organization_id)!==String(organizationId))throw new Error("CREATIVE_MUSIC_SURROUND_VALIDATION_PROJECT_NOT_FOUND");const asset=await CreativeAssetsRuntime.get(assetId);if(!asset||String(asset.organization_id)!==String(organizationId)||String(asset.creative_project_id)!==String(projectId))throw new Error("CREATIVE_MUSIC_SURROUND_VALIDATION_ASSET_NOT_FOUND");if(text(asset.metadata?.music_asset_kind)!=="SURROUND_PREMASTER")throw new Error("CREATIVE_MUSIC_SURROUND_PREMASTER_REQUIRED");const session=project.metadata?.[KEY]||{},spatial=session.spatial_audio||{};const assetRevision=Math.max(0,Math.round(finite(asset.metadata?.project_revision,0))),currentRevision=Math.max(0,Math.round(finite(session.revision,0)));if(assetRevision!==currentRevision)throw new Error("CREATIVE_MUSIC_SURROUND_PREMASTER_STALE");const validation=await validateMusicSurroundPremaster({organization_id:organizationId,file_url:asset.file_url,file_name:asset.file_name||`${asset.id}.wav`,mime_type:asset.metadata?.mime_type||"audio/wav",expected:{layout_id:spatial.layout_id,sample_rate:session.sample_rate,lfe_low_pass_hz:spatial.lfe?.low_pass_hz}});await CreativeAssetsRuntime.update(asset.id,{metadata:{...(asset.metadata||{}),surround_technical_validation:validation,surround_validation_contract:validation.contract,surround_validation_passed:validation.passed===true,surround_validated_at:validation.validated_at}});return NextResponse.json({success:validation.passed===true,contract:"AVANTIQO_MUSIC_SURROUND_VALIDATION_RESPONSE_V1",asset_id:asset.id,project_revision:assetRevision,validation,provider_job_submitted:false,remastering_performed:false},{status:200,headers:{"Cache-Control":"no-store"}});}catch(error){return NextResponse.json({success:false,error:error?.message||"Music surround validation failed",provider_job_submitted:false,remastering_performed:false},{status:error?.status||400});}}
