import crypto from "node:crypto";
import { CreativeBlenderRuntime } from "@/lib/creative/tools/runtime/CreativeBlenderRuntime";
import { CreativeCinemaEngineCertificationLedgerRuntime } from "@/lib/creative/certification/runtime/CreativeCinemaEngineCertificationLedgerRuntime";
import { CreativeCinematicMotionDesignRuntime } from "./CreativeCinematicMotionDesignRuntime";

export const AVANTIQO_CINEMATIC_MOTION_DESIGN_RENDER_CONTRACT="AVANTIQO_CINEMATIC_MOTION_DESIGN_RENDER_V1";
function text(v){return String(v??"").trim();}
function list(v){return Array.isArray(v)?v.filter(Boolean):[];}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");}
function seeded(seed){let x=(Number(seed)||1)>>>0;return()=>{x=(1664525*x+1013904223)>>>0;return x/4294967296;};}
function materialPreset(name){
  const n=text(name).toUpperCase();
  if(n.includes("GLASS"))return{color:[.78,.9,1,1],metallic:0,roughness:.06,emission:0};
  if(n.includes("GOLD"))return{color:[.71,.49,.22,1],metallic:.88,roughness:.16,emission:0};
  if(n.includes("METAL")||n.includes("CARBON"))return{color:[.1,.115,.14,1],metallic:.92,roughness:.2,emission:0};
  if(n.includes("EMISSIVE")||n.includes("ENERGY"))return{color:[.9,.72,.38,1],metallic:.15,roughness:.12,emission:5};
  return{color:[.12,.13,.15,1],metallic:.05,roughness:.55,emission:0};
}
function materialFrames(event){const a=materialPreset(event.material.start),b=materialPreset(event.material.end);return[{frame:event.start_frame,...a,metallic:event.material.metallic_start,roughness:event.material.roughness_start,emission:event.material.emission_start},{frame:event.end_frame,...b,metallic:event.material.metallic_end,roughness:event.material.roughness_end,emission:event.material.emission_end}];}
function worldText(event){return[{type:"TEXT",name:event.event_id,text:event.exact_text,location:event.position,rotation:event.rotation,scale:[.01,.01,.01],color:[.78,.65,.38,1],metallic:.8,roughness:.18,extrude:.08,bevel:.025,keyframes:[{frame:event.start_frame,scale:[.01,.01,.01],location:[event.position[0],event.position[1],event.position[2]-.25]},{frame:Math.round((event.start_frame+event.end_frame)/2),scale:event.scale,location:event.position},{frame:event.end_frame,scale:event.scale,location:event.position}],material_keyframes:materialFrames(event)}];}
function assembly(event,{particle=false}={}){const r=seeded(event.procedural.seed);const out=[];const count=Math.min(event.procedural.count,particle?220:90);for(let i=0;i<count;i+=1){const a=r()*Math.PI*2;const rr=event.procedural.radius*(.65+r()*1.35);const z=(r()-.5)*event.procedural.radius*1.4;const target=[event.position[0]+Math.cos(a)*event.procedural.radius*.22,event.position[1]+Math.sin(a)*event.procedural.radius*.22,event.position[2]+z*.15];const start=[event.position[0]+Math.cos(a)*rr,event.position[1]+Math.sin(a)*rr,event.position[2]+z];const size=particle?.025+r()*.045:.045+r()*.09;out.push({type:particle?"SPHERE":"CUBE",name:`${event.event_id}-${i}`,location:start,rotation:[r()*180,r()*180,r()*180],scale:[size,size,size],color:[.16,.17,.19,1],metallic:.75,roughness:.24,bevel:.03,keyframes:[{frame:event.start_frame,location:start,scale:[size*.35,size*.35,size*.35]},{frame:event.end_frame,location:target,scale:[size,size,size]}],material_keyframes:materialFrames(event)});}return out;}
function materialTransform(event){return[{type:"SPHERE",name:event.event_id,location:event.position,rotation:event.rotation,scale:event.scale,color:[.11,.12,.14,1],metallic:event.material.metallic_start,roughness:event.material.roughness_start,emission:event.material.emission_start,keyframes:[{frame:event.start_frame,scale:event.scale,rotation:event.rotation},{frame:event.end_frame,scale:event.scale,rotation:[event.rotation[0],event.rotation[1]+150,event.rotation[2]+35]}],material_keyframes:materialFrames(event)}];}
function technicalReveal(event){const out=[];for(let i=0;i<6;i+=1)out.push({type:"RING",name:`${event.event_id}-ring-${i}`,location:[event.position[0],event.position[1],event.position[2]+i*.04],rotation:[90,0,i*18],scale:[.05,.05,.05],color:[.72,.58,.31,1],metallic:.7,roughness:.15,emission:.8,keyframes:[{frame:event.start_frame+i*2,scale:[.05,.05,.05]},{frame:event.end_frame-i,scale:[event.scale[0]*(1+i*.13),event.scale[1]*(1+i*.13),event.scale[2]*(1+i*.13)]}],material_keyframes:materialFrames(event)});return out;}
function transitionPhysics(event){return[{type:"RING",name:`${event.event_id}-portal`,location:event.position,rotation:event.rotation,scale:[.01,.01,.01],color:[.83,.67,.34,1],metallic:.9,roughness:.12,emission:2,keyframes:[{frame:event.start_frame,scale:[.01,.01,.01],rotation:event.rotation},{frame:event.end_frame,scale:[event.scale[0]*2.3,event.scale[1]*2.3,event.scale[2]*2.3],rotation:[event.rotation[0],event.rotation[1]+90,event.rotation[2]+180]}],material_keyframes:materialFrames(event)},...assembly(event,{particle:true})];}
function objectsFor(event){switch(event.type){case"WORLD_SPACE_TYPOGRAPHY":return worldText(event);case"PROCEDURAL_ASSEMBLY":return assembly(event);case"PARTICLE_MORPH":return assembly(event,{particle:true});case"MATERIAL_TRANSFORMATION":return materialTransform(event);case"TECHNICAL_REVEAL":return technicalReveal(event);case"TRANSITION_PHYSICS":return transitionPhysics(event);case"WORLD_SPACE_GRAPHIC":return technicalReveal(event);case"LOGO_TRANSFORMATION":return assembly(event,{particle:true});default:return[];}}
function compileScene(plan){const objects=plan.events.flatMap(objectsFor);return{width:plan.width,height:plan.height,fps:plan.fps,frames:plan.frames,transparent:true,world_color:[.003,.004,.006,1],camera:{location:[0,-7,2.2],look_at:[0,0,.5],lens:62},lights:[{name:"Key",type:"AREA",location:[-3,-3,5],energy:1250,size:3.2,color:[1,.88,.7,1]},{name:"Edge",type:"AREA",location:[3,0,3],energy:850,size:2,color:[.58,.68,1,1]},{name:"Top",type:"AREA",location:[0,1,5],energy:480,size:2.5,color:[1,1,1,1]}],objects};}
export async function renderCinematicMotionDesign({project,plan}={}){
  if(!plan||plan.contract!==CreativeCinematicMotionDesignRuntime.contract)throw new Error("CINEMATIC_MOTION_PLAN_REQUIRED");
  if(plan.status!=="READY")throw new Error(`CINEMATIC_MOTION_PLAN_BLOCKED:${list(plan.blockers).join(",")}`);
  const scene=compileScene(plan);const rendered=await CreativeBlenderRuntime.render({project,scene});const logoEvents=plan.events.filter(e=>e.type==="LOGO_TRANSFORMATION");
  const renderIdentity=hash({plan_hash:plan.contract_hash,scene});const proofChecksum=crypto.createHash("sha256").update(rendered.buffer).digest("hex");
  await CreativeCinemaEngineCertificationLedgerRuntime.record({organization_id:project?.organization_id,creative_project_id:project?.id,evidence:{engine_id:"CINEMATIC_MOTION",implementation_contracts:[CreativeCinematicMotionDesignRuntime.contract,AVANTIQO_CINEMATIC_MOTION_DESIGN_RENDER_CONTRACT],technical_proof_passed:true,technical_proof_id:`blender-motion:${renderIdentity}`,visual_proof_passed:false,proof_checksum:proofChecksum,provider_calls_performed:false,notes:"Real Blender motion render completed. Visual certification remains pending durable reviewed asset evidence."}});
  return{contract:AVANTIQO_CINEMATIC_MOTION_DESIGN_RENDER_CONTRACT,plan_contract_hash:plan.contract_hash,render_identity:renderIdentity,mime_type:rendered.mime_type,buffer:rendered.buffer,bytes:rendered.bytes,scene,blender:rendered.metadata,sound_events:plan.events.flatMap(e=>e.sound_events.map(s=>({...s,motion_event_id:e.event_id}))),exact_brand_lock_required:logoEvents.length>0,exact_brand_logo_asset_node_ids:[...new Set(logoEvents.map(e=>e.logo_asset_node_id).filter(Boolean))],generated_logo_pixels_used:false,brand_lock_applied:logoEvents.length===0,world_space_rendered:true,provider_calls_performed:false};
}
export const CreativeCinematicMotionDesignRenderRuntime=Object.freeze({contract:AVANTIQO_CINEMATIC_MOTION_DESIGN_RENDER_CONTRACT,render:renderCinematicMotionDesign,compileScene});
