"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Cpu, Database, Gauge, RefreshCw, Server, Zap } from "lucide-react";
import { useBusinessContext } from "@/app/providers/BusinessContextProvider";

function number(value, digits = 0) {
  const n = Number(value);
  return Number.isFinite(n) ? n.toLocaleString(undefined, { maximumFractionDigits: digits }) : "—";
}

function Metric({ label, value, detail, icon: Icon }) {
  return <div className="rounded-2xl border border-black/[0.07] bg-white p-4 shadow-[0_1px_2px_rgba(0,0,0,0.025)]"><div className="flex items-center justify-between text-[10px] font-medium uppercase tracking-[0.14em] text-[#817D76]"><span>{label}</span><Icon size={14} className="text-[#A37849]" /></div><div className="mt-3 text-2xl font-semibold tracking-[-0.035em] text-[#1B1A18]">{value}</div><div className="mt-1 text-[10px] text-[#8A867F]">{detail}</div></div>;
}

function StatePill({ online, children }) {
  return <span className={`rounded-full border px-2.5 py-1 text-[9px] font-medium uppercase tracking-[0.08em] ${online ? "border-emerald-700/15 bg-emerald-50 text-emerald-800" : "border-red-700/15 bg-red-50 text-red-800"}`}>{children}</span>;
}

function Detail({ label, value, detail }) {
  return <div className="rounded-xl border border-black/[0.065] bg-[#FCFBF9] p-3"><div className="text-[9px] font-medium uppercase tracking-[0.13em] text-[#918B83]">{label}</div><div className="mt-1 text-[12px] font-medium text-[#37342F]">{value || "—"}</div>{detail ? <div className="mt-1 text-[10px] text-[#918B83]">{detail}</div> : null}</div>;
}

export default function ComputeAdministrationPage() {
  const business = useBusinessContext() || {};
  const organizationId = business.organization_id || business.organization?.id || null;
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!organizationId) return; setLoading(true); setError(""); try { const response = await fetch(`/api/workspace/administration/compute?organizationId=${encodeURIComponent(organizationId)}`, { cache: "no-store", credentials: "include" }); const json = await response.json(); if (!response.ok || json?.success === false) throw new Error(json?.error || "Compute status unavailable"); setData(json); } catch (e) { setError(e?.message || "Compute status unavailable"); } finally { setLoading(false); } }, [organizationId]);
  useEffect(() => { load(); const id = setInterval(load, 15000); return () => clearInterval(id); }, [load]);
  const nodes = Array.isArray(data?.nodes) ? data.nodes : []; const jobs = Array.isArray(data?.jobs) ? data.jobs : [];
  const active = useMemo(() => jobs.filter((job) => ["QUEUED", "RUNNING"].includes(job.status)), [jobs]);
  return <div className="mx-auto max-w-[1750px] space-y-5 pb-10 text-[#1B1A18]">
    <section className="rounded-[26px] border border-black/[0.075] bg-white p-6 shadow-[0_12px_38px_rgba(31,27,20,0.055)] md:p-7"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="text-[11px] font-medium uppercase tracking-[0.24em] text-[#A37849]">Administration · Compute</div><h1 className="mt-2 text-[31px] font-semibold tracking-[-0.04em]">Avantiqo Compute Control</h1><p className="mt-2 max-w-3xl text-[12px] leading-6 text-[#6F6B64]">Owned compute, model routing, live capacity, queue state and overflow control.</p></div><button onClick={load} disabled={loading} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#1F1E1B] px-3.5 text-[11px] font-medium text-white hover:bg-black disabled:opacity-50"><RefreshCw size={14} className={loading ? "animate-spin" : ""} /> Refresh</button></div></section>
    {error ? <div className="rounded-2xl border border-red-700/15 bg-red-50 p-4 text-[11px] text-red-900">{error}</div> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Nodes online" value={`${data?.metrics?.nodes_online || 0}/${data?.metrics?.nodes_total || 0}`} detail="Owned Avantiqo workers" icon={Server} /><Metric label="Queue" value={data?.metrics?.queue_depth || 0} detail={`${active.filter((job) => job.status === "RUNNING").length} running`} icon={Activity} /><Metric label="Avg latency" value={data?.metrics?.average_latency_ms ? `${number(data.metrics.average_latency_ms)} ms` : "—"} detail="Recent completed local jobs" icon={Gauge} /><Metric label="Completed" value={data?.metrics?.completed_jobs || 0} detail="Recent organization jobs" icon={Database} /><Metric label="Failed" value={data?.metrics?.failed_jobs || 0} detail="Recent local failures" icon={Zap} /></section>
    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.25fr)_minmax(360px,0.75fr)]"><div className="space-y-3">{nodes.map((node) => { const meta=node.metadata||{}, gpu=meta.gpu||{}, memory=meta.memory||{}, disk=meta.disk||{}, models=Array.isArray(meta.models)?meta.models:[]; return <div key={node.id} className="rounded-[24px] border border-black/[0.075] bg-white p-5 shadow-[0_1px_2px_rgba(0,0,0,0.025)]"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[0.16em] text-[#918B83]">{node.id}</div><div className="mt-1 text-lg font-semibold">{node.display_name}</div></div><StatePill online={node.online}>{node.online ? "Online" : "Offline"}</StatePill></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Detail label="GPU" value={gpu.name} detail={`Driver ${gpu.driver || "—"}`} /><Detail label="VRAM" value={`${number(gpu.vram_used_mb)} / ${number(gpu.vram_total_mb)} MB`} detail={`GPU ${number(gpu.utilization_pct)}% · ${number(gpu.temperature_c)}°C`} /><Detail label="System" value={meta.cpu?.name} detail={`RAM ${number(memory.free_mb)} MB free · Disk ${number(disk.c_free_gb,1)} GB free`} /><Detail label="Power" value={gpu.power_w != null ? `${number(gpu.power_w,1)} W` : "—"} detail={`Heartbeat ${node.heartbeat_age_seconds != null ? `${node.heartbeat_age_seconds}s ago` : "—"}`} /></div><div className="mt-4 rounded-xl border border-black/[0.065] bg-[#FCFBF9] p-3"><div className="flex items-center justify-between"><div className="text-[9px] font-medium uppercase tracking-[0.13em] text-[#918B83]">Local models</div><div className="text-[9px] text-[#A37849]">Ollama {meta.ollama_version || "—"}</div></div><div className="mt-2 flex flex-wrap gap-2">{models.length ? models.map((model) => <span key={model} className="rounded-full border border-[#A37849]/20 bg-[#F7F0E8] px-2.5 py-1 text-[9px] text-[#76532D]">{model}</span>) : <span className="text-[10px] text-[#918B83]">No model telemetry</span>}</div></div></div>; })}</div>
      <div className="rounded-[24px] border border-black/[0.075] bg-white p-5"><div className="text-[10px] font-medium uppercase tracking-[0.16em] text-[#918B83]">Routing policy</div><div className="mt-4 space-y-3 text-[11px]"><div className="flex items-center justify-between border-b border-black/[0.06] pb-3"><span className="text-[#6F6B64]">Normal intelligence</span><span className="font-medium text-emerald-700">Local first</span></div><div className="flex items-center justify-between border-b border-black/[0.06] pb-3"><span className="text-[#6F6B64]">Deep intelligence</span><span className="font-medium text-[#A37849]">Modal fallback/heavy</span></div><div className="flex items-center justify-between border-b border-black/[0.06] pb-3"><span className="text-[#6F6B64]">Image / video / music</span><span className="font-medium text-[#A37849]">Modal specialist</span></div><div className="flex items-center justify-between"><span className="text-[#6F6B64]">Local transport</span><span className="text-[#4A4640]">Supabase pull queue</span></div></div></div></section>
    <section className="rounded-[24px] border border-black/[0.075] bg-white p-5"><div className="flex items-center justify-between"><div><div className="text-[10px] font-medium uppercase tracking-[0.16em] text-[#918B83]">Recent local work</div><h2 className="mt-1 text-lg font-semibold">Compute jobs</h2><p className="mt-1 text-[10px] text-[#918B83]">Exact model and execution path for every local job.</p></div><Cpu size={17} className="text-[#A37849]" /></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-[10px]"><thead className="text-[#918B83]"><tr><th className="pb-2 pr-4 font-medium">Status</th><th className="pb-2 pr-4 font-medium">Lane</th><th className="pb-2 pr-4 font-medium">Model</th><th className="pb-2 pr-4 font-medium">Runtime path</th><th className="pb-2 pr-4 font-medium">Provider</th><th className="pb-2 font-medium">Latency</th></tr></thead><tbody className="divide-y divide-black/[0.055]">{jobs.slice(0,30).map((job)=><tr key={job.id} className="text-[#5F5A53]"><td className="py-2.5 pr-4 font-medium">{job.status}</td><td className="py-2.5 pr-4">{job.lane}</td><td className="py-2.5 pr-4"><div className="font-medium text-[#37342F]">{job.runtime_model || job.model || "—"}</div><div className="mt-0.5 text-[9px] text-[#9A948C]">{job.model && job.runtime_model !== job.model ? `requested ${job.model}` : "runtime model"}</div></td><td className="py-2.5 pr-4 font-mono text-[9px]">{job.execution_path || "—"}</td><td className="py-2.5 pr-4">{job.infrastructure_provider || "—"}</td><td className="py-2.5">{job.metrics?.elapsed_ms ? `${number(job.metrics.elapsed_ms)} ms` : "—"}</td></tr>)}</tbody></table>{!jobs.length ? <div className="py-8 text-center text-[10px] text-[#918B83]">No local compute jobs for this organization yet.</div> : null}</div></section>
  </div>;
}
