export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export const maxDuration = 300;

import { NextResponse } from "next/server";

import { CreativeAssetsRuntime } from "@/lib/creative/assets/runtime/CreativeAssetsRuntime";
import {
  resolveCreativeProviderAssetUrl,
} from "@/lib/creative/assets/storage/resolveCreativeProviderAssetUrl";
import {
  buildMusicGenerationPlan,
  normalizeMusicBrief,
} from "@/lib/creative/runtime/engines/MusicEngine";
import {
  executeService,
  settlePendingService,
} from "@/lib/platform/service-runtime/execution/ServiceExecutionRuntime";
import {
  requireOrganizationAccess,
} from "@/lib/platform/security/requireOrganizationAccess";

const EXECUTION_PERMISSIONS = Object.freeze([
  "creative.execute",
  "creative.production.run",
  "creative.*",
]);

function text(value) {
  return String(value ?? "").trim();
}

function finite(value, fallback = null) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function clamp(value, min, max, fallback) {
  const number = finite(value, fallback);
  return Math.max(min, Math.min(max, number));
}

function errorStatus(error) {
  const value = `${text(error?.code)}:${text(error?.message)}`.toUpperCase();
  if (value.includes("REQUIRED") || value.includes("INVALID")) return 400;
  if (value.includes("PERMISSION") || value.includes("FORBIDDEN") || value.includes("UNAUTHORIZED")) return 403;
  if (value.includes("NOT FOUND") || value.includes("NOT_FOUND")) return 404;
  if (value.includes("WALLET") || value.includes("BALANCE")) return 402;
  return 500;
}

async function requireAccess(request, organizationId) {
  const access = await requireOrganizationAccess({
    organizationId,
    request,
    requiredAnyPermission: EXECUTION_PERMISSIONS,
  });
  if (!access.success) {
    const error = new Error(access.error || "CREATIVE_MUSIC_ACCESS_FORBIDDEN");
    error.code = access.code || "CREATIVE_MUSIC_ACCESS_FORBIDDEN";
    error.status = access.status || 403;
    throw error;
  }
  return access;
}

function storageReference(output = {}) {
  return text(output?.storage_reference || output?.storageReference);
}

function safeFileName(title, usageId) {
  const stem = text(title || "avantiqo-music")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "avantiqo-music";
  const suffix = text(usageId).slice(0, 8);
  return `${stem}${suffix ? `-${suffix}` : ""}.wav`;
}

async function persistCompletedMusicAsset({
  organizationId,
  body,
  result,
  session = null,
  usageId = null,
}) {
  if (!result || result.pending === true || result.failed === true) return null;
  const output = result.output || {};
  const reference = storageReference(output);
  if (!reference) return null;

  const projectId = text(body.creative_project_id) || null;
  const missionId = text(body.creative_mission_id) || null;
  const normalizedUsageId = text(usageId || result?.usage?.id) || null;
  const assets = await CreativeAssetsRuntime.list({
    organization_id: organizationId,
    creative_project_id: projectId,
    creative_mission_id: missionId,
    limit: 300,
  });
  const existing = assets.find((asset) => (
    text(asset.file_url) === reference ||
    (normalizedUsageId && text(asset.metadata?.music_usage_id) === normalizedUsageId)
  ));
  if (existing) return existing;

  const title = text(session?.title || body.title || "Avantiqo composition").slice(0, 160);
  const masteringProfile = text(
    session?.mastering_profile ||
    body.mastering_profile ||
    result?.usage?.metadata?.mastering_profile ||
    "streaming",
  );

  return CreativeAssetsRuntime.create({
    organization_id: organizationId,
    creative_project_id: projectId,
    creative_mission_id: missionId,
    asset_type: "AUDIO",
    file_url: reference,
    file_name: safeFileName(title, normalizedUsageId),
    name: title,
    title,
    description: "Original music generated by Avantiqo Music Studio.",
    ai_generated: true,
    provider: result.provider || "avantiqo-audio",
    engine: "AVANTIQO_MUSIC",
    prompt: null,
    metadata: {
      media_kind: "MUSIC",
      mime_type: "audio/wav",
      storage_reference: reference,
      music_usage_id: normalizedUsageId,
      music_provider_job_id: text(result.provider_job_id) || null,
      mastering_profile: masteringProfile,
      owned_engine: true,
      engine_family: "ACE_STEP_1_5",
      certified_capability: "ai.music.generate",
      provider_selection_exposed: false,
      user_prompt_surface: false,
      generated_at: new Date().toISOString(),
    },
  });
}

function publicExecution(result, session = null, execution = {}, asset = null) {
  const output = result?.output || null;
  return {
    success: result?.success !== false,
    pending: result?.pending === true,
    failed: result?.failed === true,
    provider: result?.provider || execution.provider || null,
    model: result?.model || execution.model || null,
    provider_job_id: result?.provider_job_id || execution.provider_job_id || null,
    provider_status: result?.provider_status || null,
    usage_id: result?.usage?.id || execution.usage_id || null,
    pricing: result?.pricing || result?.reservation_pricing || execution.pricing || null,
    credential_id: result?.credential_id || execution.credential_id || null,
    started_at: result?.started_at || execution.started_at || null,
    settlement: result?.settlement || null,
    output,
    asset: asset ? {
      id: asset.id,
      title: asset.title || asset.name || null,
      file_url: asset.file_url || null,
      asset_type: asset.asset_type || null,
      metadata: asset.metadata || {},
    } : null,
    ...(session ? {
      session: {
        title: session.title,
        style: session.style,
        mood: session.mood,
        duration_seconds: session.duration_seconds,
        bpm: session.bpm,
        keyscale: session.keyscale || null,
        timesignature: session.timesignature,
        instrumental: session.instrumental,
        vocal_language: session.vocal_language,
        structure: session.structure,
        mastering_profile: session.mastering_profile,
        mastering: session.mastering,
      },
    } : {}),
    engine: {
      owner: "AVANTIQO",
      family: "ACE_STEP_1_5",
      certified_capability: "ai.music.generate",
      provider_selection_exposed: false,
      execution_transport_only_direction: true,
      downstream_mastering_runtime: "AVANTIQO_AUDIO_FINISHING",
    },
  };
}

async function compose(body) {
  const organizationId = text(body.organization_id);
  if (!organizationId) throw new Error("organization_id required");
  const plan = buildMusicGenerationPlan(body);
  const session = plan.session;

  const result = await executeService({
    organization_id: organizationId,
    bill_to_organization_id: organizationId,
    entity_id: text(body.entity_id) || null,
    service_id: plan.service_id,
    capability: plan.capability,
    input: {
      title: session.title,
      description: session.direction,
      quantity: session.duration_seconds,
      currency: text(body.currency || "THB"),
      generation: plan.generation,
      requirements: {
        output_spec: plan.output_spec,
      },
      output_spec: {
        duration_seconds: plan.output_spec.duration_seconds,
        format: plan.output_spec.format,
        mastering_profile: plan.output_spec.mastering_profile,
      },
      provider_parameters: {
        ...(body.seed !== undefined && body.seed !== null && body.seed !== ""
          ? { seed: Math.round(clamp(body.seed, 0, 4294967295, 0)) }
          : {}),
        inference_steps: Math.round(clamp(body.inference_steps, 1, 20, 8)),
        shift: clamp(body.shift, 1, 5, 3),
      },
    },
    metadata: {
      module: "CREATIVE",
      operation: "AVANTIQO_MUSIC_STUDIO_COMPOSE",
      creative_project_id: text(body.creative_project_id) || null,
      creative_mission_id: text(body.creative_mission_id) || null,
      mastering_profile: session.mastering_profile,
      audio_finishing_target: session.mastering,
      music_session: {
        title: session.title,
        style: session.style,
        mood: session.mood,
        energy: session.energy,
        duration_seconds: session.duration_seconds,
        bpm: session.bpm,
        keyscale: session.keyscale || null,
        timesignature: session.timesignature,
        instrumental: session.instrumental,
        vocal_language: session.vocal_language,
        structure: session.structure,
        mastering_profile: session.mastering_profile,
      },
      owned_engine_preferred: true,
      provider_selection_exposed: false,
      user_prompt_surface: false,
    },
    provider_policy: {
      preferred_providers: ["avantiqo-audio"],
    },
    category: plan.category,
  });

  const asset = await persistCompletedMusicAsset({
    organizationId,
    body,
    result,
    session,
    usageId: result?.usage?.id,
  });
  return publicExecution(result, session, {}, asset);
}

async function status(body) {
  const organizationId = text(body.organization_id);
  if (!organizationId) throw new Error("organization_id required");
  const provider = text(body.provider);
  const providerJobId = text(body.provider_job_id);
  const usageId = text(body.usage_id);
  if (!provider) throw new Error("provider required");
  if (!providerJobId) throw new Error("provider_job_id required");
  if (!usageId) throw new Error("usage_id required");

  const result = await settlePendingService({
    organization_id: organizationId,
    provider,
    provider_job_id: providerJobId,
    usage_id: usageId,
    pricing: body.pricing || {},
    quantity: finite(body.quantity, null),
    unit: text(body.unit) || null,
    credential_id: text(body.credential_id) || null,
    started_at: text(body.started_at) || null,
    metadata: {
      module: "CREATIVE",
      operation: "AVANTIQO_MUSIC_STUDIO_SETTLE",
      creative_project_id: text(body.creative_project_id) || null,
      creative_mission_id: text(body.creative_mission_id) || null,
    },
  });

  const session = body.session ? normalizeMusicBrief(body.session) : null;
  const asset = await persistCompletedMusicAsset({
    organizationId,
    body,
    result,
    session,
    usageId,
  });

  return publicExecution(result, session, {
    provider,
    provider_job_id: providerJobId,
    usage_id: usageId,
    pricing: body.pricing || null,
    credential_id: text(body.credential_id) || null,
    started_at: text(body.started_at) || null,
  }, asset);
}

async function resolveAsset(body) {
  const organizationId = text(body.organization_id);
  if (!organizationId) throw new Error("organization_id required");
  const assetId = text(body.asset_id);
  if (!assetId) throw new Error("asset_id required");

  const asset = await CreativeAssetsRuntime.get(assetId);
  if (!asset || text(asset.organization_id) !== organizationId) {
    const error = new Error("CREATIVE_MUSIC_ASSET_NOT_FOUND");
    error.code = "CREATIVE_MUSIC_ASSET_NOT_FOUND";
    error.status = 404;
    throw error;
  }
  const reference = text(asset.file_url || asset.metadata?.storage_reference);
  if (!reference) throw new Error("CREATIVE_MUSIC_ASSET_URL_REQUIRED");
  const url = await resolveCreativeProviderAssetUrl({
    organization_id: organizationId,
    value: reference,
  });
  return {
    success: true,
    pending: false,
    failed: false,
    asset: {
      id: asset.id,
      title: asset.title || asset.name || asset.file_name || "Audio asset",
      file_url: reference,
      playback_url: url,
      asset_type: asset.asset_type || null,
      metadata: asset.metadata || {},
    },
  };
}

export async function POST(request) {
  try {
    const body = await request.json();
    const organizationId = text(body.organization_id);
    if (!organizationId) {
      return NextResponse.json({ success: false, error: "organization_id required" }, { status: 400 });
    }
    await requireAccess(request, organizationId);

    const action = text(body.action || "compose").toLowerCase();
    const result = action === "compose"
      ? await compose(body)
      : action === "status"
        ? await status(body)
        : action === "resolve_asset"
          ? await resolveAsset(body)
          : null;

    if (!result) {
      return NextResponse.json(
        { success: false, error: "CREATIVE_MUSIC_ACTION_INVALID" },
        { status: 400 },
      );
    }

    return NextResponse.json(result, {
      status: result.failed ? 502 : 200,
      headers: { "Cache-Control": "no-store" },
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: error?.message || "Creative Music Studio execution failed",
        code: error?.code || null,
      },
      { status: error?.status || errorStatus(error) },
    );
  }
}
