import { createHash } from "node:crypto";
import { supabaseAdmin } from "@/lib/shared/supabase/admin";
import { resolveAvantiqoLearningOrganization } from "@/lib/intelligence/runtime/AvantiqoLearningOrganizationRuntime";
import { evaluateAvantiqoExperiencePracticeEffectiveness } from "@/lib/intelligence/runtime/AvantiqoBusinessPartnerExperiencePracticeEffectivenessPolicyRuntime";
export const AVANTIQO_BUSINESS_PARTNER_EXPERIENCE_PRACTICE_EFFECTIVENESS_CONTRACT="AVANTIQO_BUSINESS_PARTNER_EXPERIENCE_PRACTICE_EFFECTIVENESS_V1";
const MEMORY_TABLE="intelligence_memories",EXPERIENCE_SCOPE="platform_business_partner_experience",PRACTICE_SCOPE="platform_business_partner_experience_practice",EFFECT_SCOPE="platform_business_partner_experience_practice_effectiveness";
function text(v,l=12000){return String(v??"").trim().slice(0,l)}function list(v){return Array.isArray(v)?v:[]}function object(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}}function hash(v){return createHash("sha256").update(text(v,50000)).digest("hex")}
async function resolveOrg(){const configured=text(process.env.AVANTIQO_INTELLIGENCE_LEARNING_ORGANIZATION_ID,160);if(configured)return configured;const resolved=await resolveAvantiqoLearningOrganization({allowDatabaseFallback:true});return text(resolved?.organization_id,160)}
export async function reconcileAvantiqoBusinessPartnerExperiencePracticeEffectiveness({organizationId=null}={}){
 const org=text(organizationId,160)||await resolveOrg();if(!org)return{success:true,status:"DISABLED",reason:"LEARNING_ORGANIZATION_NOT_CONFIGURED",contract:AVANTIQO_BUSINESS_PARTNER_EXPERIENCE_PRACTICE_EFFECTIVENESS_CONTRACT};
 const [practices,experience]=await Promise.all([supabaseAdmin.from(MEMORY_TABLE).select("id,metadata,created_at,updated_at").eq("organization_id",org).eq("memory_scope",PRACTICE_SCOPE).eq("active",true).order("created_at",{ascending:false}).limit(40),supabaseAdmin.from(MEMORY_TABLE).select("subject,metadata,created_at,updated_at").eq("organization_id",org).eq("memory_scope",EXPERIENCE_SCOPE).eq("active",true).order("created_at",{ascending:false}).limit(10000)]);if(practices.error)throw practices.error;if(experience.error)throw experience.error;
 const all=[];for(const practice of list(practices.data)){const items=evaluateAvantiqoExperiencePracticeEffectiveness({practice,experienceRows:list(experience.data)});for(const item of items)all.push({...item,practice_id:practice.id,practice_created_at:practice.created_at||practice.updated_at||object(practice.metadata).created_at||null})}
 if(!all.length)return{success:true,status:"IDLE",reason:"NO_PRACTICE_EFFECTIVENESS_SIGNAL",contract:AVANTIQO_BUSINESS_PARTNER_EXPERIENCE_PRACTICE_EFFECTIVENESS_CONTRACT,evaluated_count:0};
 const now=new Date().toISOString();const rows=all.map(item=>({organization_id:org,party_id:null,entity_id:null,conversation_id:null,source_turn_id:null,memory_scope:EFFECT_SCOPE,memory_key:`experience-practice-effect:${hash(`${item.practice_id}|${item.capability_key}|${item.failure_class}`).slice(0,40)}`,memory_type:"fact",subject:item.capability_key,content:`Observed post-practice structural failure trend for ${item.capability_key} / ${item.failure_class}: ${item.status}.`,importance:item.status==="OBSERVED_FAILURE_RATE_WORSENED"||item.status==="PRACTICE_NOT_MASTERED"?0.96:0.76,confidence:Math.max(0.5,Number(item.evidence_strength||0)),source:"business_partner_experience_practice_effectiveness",active:true,valid_until:null,superseded_by:null,superseded_at:null,forgotten_at:null,metadata:{contract:AVANTIQO_BUSINESS_PARTNER_EXPERIENCE_PRACTICE_EFFECTIVENESS_CONTRACT,...item,customer_private_content_included:false,customer_identifiers_included:false,raw_reasoning_persisted:false,automatic_training_started:false,automatic_model_promotion:false,authority_effect:"NONE",evaluated_at:now},updated_at:now}));const written=await supabaseAdmin.from(MEMORY_TABLE).upsert(rows,{onConflict:"organization_id,memory_scope,memory_key"}).select("id");if(written.error)throw written.error;
 return{success:true,status:"EFFECTIVENESS_RECONCILED",contract:AVANTIQO_BUSINESS_PARTNER_EXPERIENCE_PRACTICE_EFFECTIVENESS_CONTRACT,evaluated_count:all.length,written_count:list(written.data).length,improved_count:all.filter(x=>x.status==="OBSERVED_FAILURE_RATE_IMPROVED").length,worsened_count:all.filter(x=>x.status==="OBSERVED_FAILURE_RATE_WORSENED").length,not_mastered_count:all.filter(x=>x.status==="PRACTICE_NOT_MASTERED").length,observational_only:true,causal_attribution:false,authority_effect:"NONE"};
}
export async function summarizeAvantiqoBusinessPartnerExperiencePracticeEffectiveness({organizationId=null,limit=5000}={}){const org=text(organizationId,160)||await resolveOrg();if(!org)return{available:false,summaries:[]};const result=await supabaseAdmin.from(MEMORY_TABLE).select("subject,metadata,updated_at").eq("organization_id",org).eq("memory_scope",EFFECT_SCOPE).eq("active",true).order("updated_at",{ascending:false}).limit(Math.max(1,Math.min(10000,Number(limit)||5000)));if(result.error)throw result.error;const seen=new Set(),summaries=[];for(const row of list(result.data)){const m=object(row.metadata),key=`${text(m.capability_key||row.subject,300)}|${text(m.failure_class,80)}`;if(seen.has(key))continue;seen.add(key);summaries.push({capability_key:text(m.capability_key||row.subject,300),failure_class:text(m.failure_class,80),status:text(m.status,120),evidence_strength:Number(m.evidence_strength||0),practice_priority_multiplier:Number(m.practice_priority_multiplier||1),observational_only:true,causal_attribution:false,authority_effect:"NONE"})}return{available:true,summaries,authority_effect:"NONE"}}
export const AvantiqoBusinessPartnerExperiencePracticeEffectivenessRuntime=Object.freeze({contract:AVANTIQO_BUSINESS_PARTNER_EXPERIENCE_PRACTICE_EFFECTIVENESS_CONTRACT,reconcile:reconcileAvantiqoBusinessPartnerExperiencePracticeEffectiveness,summarize:summarizeAvantiqoBusinessPartnerExperiencePracticeEffectiveness});
