const PRODUCT_ROUTES = {
  pos: "/operations/pos",
  "front-desk": "/operations/front-desk",
  bookings: "/operations/reservations",
  reservations: "/operations/reservations",
  payments: "/operations/pos/payments",
  "cash-control": "/finance",
  "customer-receipts": "/operations/pos/receipts",
  orders: "/operations/pos/orders",
  housekeeping: "/operations/housekeeping",
  concierge: "/operations/concierge",
  "hotel-channel-manager": "/operations/channel-manager",
  "revenue-management": "/operations/hotel-revenue",
  "night-audit": "/operations/night-audit",
  workforce: "/people",
  payroll: "/people/payroll",
  attendance: "/people/attendance",
  scheduling: "/people/scheduling",
  "employee-requests": "/people/requests",
  "field-service": "/operations/field-service",
  maintenance: "/operations/maintenance",
  projects: "/projects",
  "staff-portal": "/people",
  performance: "/people",
  "employee-onboarding": "/people",
};
Object.assign(PRODUCT_ROUTES, {
  finance: "/finance",
  invoicing: "/finance",
  payables: "/finance",
  "bank-reconciliation": "/finance",
  collections: "/finance",
  "tax-vat": "/finance",
  "fixed-assets": "/finance",
  close: "/finance/close",
  forecasting: "/finance",
  consolidation: "/finance",
  "e-invoicing": "/finance",
  "reporting-bi": "/finance/reporting",
  inventory: "/supply-chain",
  procurement: "/supply-chain",
  receiving: "/supply-chain/receiving",
  warehouse: "/supply-chain",
  "food-cost": "/supply-chain/production/costing",
  "production-costing": "/supply-chain/production/costing",
  replenishment: "/supply-chain/replenishment",
  "kitchen-display": "/operations/kitchen",
  "menu-management": "/operations/restaurant",
  "prep-production-control": "/supply-chain/production",
  "invoice-intelligence": "/documents",
  "expense-capture": "/documents",
  "bank-statement-intelligence": "/documents",
});
Object.assign(PRODUCT_ROUTES, {
  "three-way-match": "/supply-chain",
  "recipe-import": "/supply-chain/production/recipes",
  "supplier-price-capture": "/supply-chain",
  automations: "/operations",
  crm: "/commercial/customers",
  inbox: "/commercial/customers/communications",
  loyalty: "/commercial/customers/loyalty",
  reviews: "/commercial/reviews",
  marketing: "/commercial/marketing",
  sales: "/commercial/sales/quotes",
  "customer-portal": "/commercial/customers",
  "social-publishing": "/commercial/marketing/social",
  "campaign-attribution": "/commercial/marketing",
  "business-partner": "/ai",
  agents: "/ai",
  insights: "/analytics",
  secretary: "/ai",
  knowledge: "/ai",
  "creative-studio": "/creative",
  "image-studio": "/creative/image",
  "video-studio": "/creative/video",
  "music-studio": "/creative/music",
  "voice-studio": "/creative/voice",
  "campaign-production": "/creative/marketing",
});
Object.assign(PRODUCT_ROUTES, {
  "restaurant-system": "/restaurant",
  "hotel-system": "/hotel",
  "retail-system": "/retail",
  "field-service-system": "/operations/field-service",
  "pest-control-system": "/pest_control",
  "agency-system": "/creative",
  "accounting-firm": "/finance/accounting-firm",
});

const FAMILY_FALLBACKS = Object.freeze({
  "sell-serve": "/operations",
  "people-work": "/people",
  "money-control": "/finance",
  "stock-supply": "/supply-chain",
  "documents-automation": "/documents",
  "customer-growth": "/commercial",
  intelligence: "/ai",
  creative: "/creative",
  industry: "/operations",
});

export function resolveProductWorkspaceRoute({ organizationId, product }) {
  if (!organizationId || !product) return "#";
  const suffix = PRODUCT_ROUTES[product.id] || FAMILY_FALLBACKS[product.family] || "";
  return `/workspace/${organizationId}${suffix}`;
}

export const PRODUCT_WORKSPACE_ROUTES = Object.freeze({ ...PRODUCT_ROUTES });