"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { RefreshCw } from "lucide-react";
import { HotelEmptyState, HotelError, HotelField, HotelMetric, HotelPrimaryAction, HotelSecondaryAction, HotelSection, HotelStatusPill, HotelWorkspaceShell, hotelInputClass, hotelTextareaClass } from "@/components/workspace/hotel/HotelWorkspaceUI";

const TASK_TYPES = ["REPAIR", "INSPECTION", "PREVENTIVE", "SAFETY"];
const statusOf = (task) => String(task?.status || "PENDING").toUpperCase();
const propertyName = (task) => task?.hotel_properties?.name || task?.property_id || "Property";

export default function OperationsMaintenancePage() {
  const params = useParams();
  const organizationId = params?.organizationId || "";
  const [properties, setProperties] = useState([]); const [tasks, setTasks] = useState([]); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState(null); const [error, setError] = useState(null);
  const [form, setForm] = useState({ propertyId: "", taskType: "REPAIR", scheduledAt: "", notes: "" });
  const load = useCallback(async () => { if (!organizationId) return; setLoading(true); setError(null); try { const q = `?organizationId=${encodeURIComponent(organizationId)}`; const [tr, pr] = await Promise.all([fetch(`/api/hotel/maintenance/list${q}`, { cache: "no-store", credentials: "include" }), fetch(`/api/hotel/properties/list${q}`, { cache: "no-store", credentials: "include" })]); const [td, pd] = await Promise.all([tr.json(), pr.json()]); if (!tr.ok) throw new Error(td.error || "Unable to load maintenance tasks"); if (!pr.ok) throw new Error(pd.error || "Unable to load properties"); setTasks(td.tasks || []); setProperties(pd.properties || []); setForm((c) => ({ ...c, propertyId: c.propertyId || pd.properties?.[0]?.id || "" })); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [organizationId]);
  useEffect(() => { load(); }, [load]);
  const groups = useMemo(() => ({ PENDING: tasks.filter((t) => statusOf(t) === "PENDING"), IN_PROGRESS: tasks.filter((t) => statusOf(t) === "IN_PROGRESS"), COMPLETED: tasks.filter((t) => statusOf(t) === "COMPLETED") }), [tasks]);
  async function createTask() { setBusyId("create"); setError(null); try { const r = await fetch("/api/hotel/maintenance/create", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, propertyId: form.propertyId, taskType: form.taskType, scheduledAt: form.scheduledAt || null, notes: form.notes }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to create maintenance task"); setForm((c) => ({ ...c, notes: "" })); await load(); } catch (e) { setError(e.message); } finally { setBusyId(null); } }
  async function transition(taskId, action) { setBusyId(taskId); setError(null); try { const r = await fetch("/api/hotel/maintenance/update", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, taskId, action }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to update maintenance task"); await load(); } catch (e) { setError(e.message); } finally { setBusyId(null); } }
  const active = [...groups.PENDING, ...groups.IN_PROGRESS];
  return <HotelWorkspaceShell organizationId={organizationId} active="maintenance" title="Maintenance" subtitle="Protect room availability and guest experience by turning property defects into accountable work." actions={<HotelSecondaryAction onClick={load} disabled={loading}><RefreshCw size={9} className={loading ? "animate-spin" : ""}/>Refresh</HotelSecondaryAction>}>
    <HotelError>{error}</HotelError>
    <section className="grid grid-cols-3 gap-3"><HotelMetric label="Pending" value={groups.PENDING.length} detail="Waiting for ownership" attention={groups.PENDING.length > 0}/><HotelMetric label="In progress" value={groups.IN_PROGRESS.length} detail="Work underway" attention={groups.IN_PROGRESS.length > 0}/><HotelMetric label="Completed" value={groups.COMPLETED.length} detail="Closed property work"/></section>
    <HotelSection eyebrow="Raise work" title="New maintenance task" detail="Capture the issue against the correct property before it becomes lost operational knowledge."><div className="grid gap-3 p-4 md:grid-cols-4"><HotelField label="Property"><select className={hotelInputClass} value={form.propertyId} onChange={(e) => setForm((c) => ({ ...c, propertyId: e.target.value }))}><option value="">Select property</option>{properties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></HotelField><HotelField label="Task type"><select className={hotelInputClass} value={form.taskType} onChange={(e) => setForm((c) => ({ ...c, taskType: e.target.value }))}>{TASK_TYPES.map((t) => <option key={t}>{t}</option>)}</select></HotelField><HotelField label="Scheduled"><input type="datetime-local" className={hotelInputClass} value={form.scheduledAt} onChange={(e) => setForm((c) => ({ ...c, scheduledAt: e.target.value }))}/></HotelField><div className="flex items-end"><HotelPrimaryAction onClick={createTask} disabled={busyId === "create" || !form.propertyId}>Create task</HotelPrimaryAction></div><div className="md:col-span-4"><HotelField label="Notes"><textarea className={hotelTextareaClass} value={form.notes} onChange={(e) => setForm((c) => ({ ...c, notes: e.target.value }))}/></HotelField></div></div></HotelSection>
    <HotelSection eyebrow="Active defects" title="Maintenance work queue" detail="Pending work first, then work already underway.">{loading ? <HotelEmptyState>Loading maintenance…</HotelEmptyState> : active.length ? <div className="divide-y divide-black/[0.055]">{active.map((task) => <div key={task.id} className="grid gap-2 px-4 py-3 md:grid-cols-[minmax(160px,1fr)_130px_130px_minmax(180px,1.2fr)_120px] md:items-center md:px-5"><div className="text-[9px] font-semibold text-[#403C37]">{propertyName(task)}</div><div className="text-[8px] text-[#716B63]">{task.task_type || "REPAIR"}</div><HotelStatusPill value={statusOf(task)}/><div className="truncate text-[8px] text-[#807A72]">{task.notes || "No notes"}</div><div>{statusOf(task) === "PENDING" ? <HotelSecondaryAction onClick={() => transition(task.id, "START")} disabled={busyId === task.id}>Start work</HotelSecondaryAction> : <HotelPrimaryAction onClick={() => transition(task.id, "COMPLETE")} disabled={busyId === task.id}>Complete</HotelPrimaryAction>}</div></div>)}</div> : <HotelEmptyState>No active maintenance work.</HotelEmptyState>}</HotelSection>
  </HotelWorkspaceShell>;
}
