import { insertVoiceAsyncJob, loadVoiceAsyncJob, submitVoiceService, settleVoiceJob, cancelVoiceJob, voiceText } from "./OperatorVoiceAsyncJobRuntime.js";
const CONTRACT = "AVANTIQO_OPERATOR_ASYNC_TRANSCRIPTION_V2";
const CAPABILITY = "ai.speech.to.text";
const LANE = "voice-stt";
function find(value, key, depth=0) { if (depth>10 || value==null) return null; if (Array.isArray(value)) { for (const v of value) { const f=find(v,key,depth+1); if (f) return f; } return null; } if (typeof value!=="object") return null; if (voiceText(value[key])) return voiceText(value[key]); for (const k of ["output","result","data","response","raw"]) { const f=find(value[k],key,depth+1); if (f) return f; } return null; }
function resultShape(result) { const transcript=find(result,"transcript")||find(result,"text")||find(result,"output_text")||""; const detected_language=find(result,"detected_language"); const language=find(result,"language")||detected_language; return { transcript, language: language||null, detected_language: detected_language||null, language_source: detected_language?"detected":null }; }
export async function startOperatorAsyncTranscription({ organizationId, entityId=null, partyId, audio, fileName=null, mimeType=null, language=null, prompt=null, locale=null, metadata={} }) { const organization=voiceText(organizationId); const party=voiceText(partyId); if(!organization||!party||!audio||typeof audio.arrayBuffer!=="function") throw new Error("AVANTIQO_OPERATOR_ASYNC_TRANSCRIPTION_INPUT_REQUIRED"); const job=await insertVoiceAsyncJob({organizationId:organization,entityId,partyId:party,capability:CAPABILITY,lane:LANE,metadata:{contract:CONTRACT,module:"OPERATOR",operation:"VOICE_TRANSCRIPTION",...metadata}}); const execution=await submitVoiceService({job,organizationId:organization,entityId,partyId:party,capability:CAPABILITY,input:{upload_file:audio,file_name:voiceText(fileName)||audio.name||"avantiqo-voice.wav",mime_type:voiceText(mimeType)||audio.type||"audio/wav",language:voiceText(language)||undefined,prompt:voiceText(prompt)||undefined},metadata:{module:"OPERATOR",operation:"VOICE_TRANSCRIPTION_ASYNC",async_voice_contract:CONTRACT,...metadata}}); if(!execution?.pending) return {success:true,pending:false,contract:CONTRACT,job_id:job.id,provider:"avantiqo-voice",...resultShape(execution)}; return {success:true,pending:true,contract:CONTRACT,job_id:job.id,provider:"avantiqo-voice",provider_status:execution.provider_status||"PENDING",expires_at:job.expires_at}; }
export async function pollOperatorAsyncTranscription({jobId,organizationId}) { const job=await loadVoiceAsyncJob({jobId,organizationId,capability:CAPABILITY,lane:LANE,notFoundCode:"AVANTIQO_OPERATOR_ASYNC_TRANSCRIPTION_JOB"}); if(["FAILED","EXPIRED","CANCELLED"].includes(job.status)) return {success:false,pending:false,contract:CONTRACT,job_id:job.id,status:job.status,error:job.error_code||"AVANTIQO_OPERATOR_ASYNC_TRANSCRIPTION_FAILED"}; const settled=await settleVoiceJob(job,CAPABILITY,CONTRACT); if(settled?.pending) return {success:true,pending:true,contract:CONTRACT,job_id:job.id,status:"PENDING",provider_status:settled.provider_status||job.provider_status}; if(settled?.failed||settled?.success===false) return {success:false,pending:false,contract:CONTRACT,job_id:job.id,status:"FAILED",error:"Voice transcription failed"}; return {success:true,pending:false,contract:CONTRACT,job_id:job.id,provider:"avantiqo-voice",status:"COMPLETED",...resultShape(settled)}; }
export async function cancelOperatorAsyncTranscription({jobId,organizationId}) { const job=await loadVoiceAsyncJob({jobId,organizationId,capability:CAPABILITY,lane:LANE,notFoundCode:"AVANTIQO_OPERATOR_ASYNC_TRANSCRIPTION_JOB"}); return cancelVoiceJob(job,CONTRACT); }
export const OperatorVoiceAsyncTranscriptionRuntime={start:startOperatorAsyncTranscription,poll:pollOperatorAsyncTranscription,cancel:cancelOperatorAsyncTranscription};
