import { ServiceExecutionRuntime } from "@/lib/platform/service-runtime/execution/ServiceExecutionRuntime";
import { ownedOperatorIntelligenceSelectionPolicy, settleOperatorIntelligenceExecution } from "./OperatorOwnedIntelligenceServiceRuntime";

const CONTRACT = "AVANTIQO_PREPARED_ATTACHMENT_CLARIFICATION_INTELLIGENCE_V1";
const text=(v,l=8000)=>String(v??"").trim().slice(0,l);
const object=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
const list=v=>Array.isArray(v)?v:[];
const ALWAYS_REVIEW_READY=new Set(["recipe"]);
const BLOCKING_STATUSES=new Set(["CLARIFICATION_REQUIRED","PARTIAL_OR_UNVERIFIED"]);

function findText(value,depth=0){if(depth>5||value==null)return"";if(typeof value==="string")return value;if(Array.isArray(value)){for(const entry of value){const found=findText(entry,depth+1);if(found)return found;}return"";}if(typeof value!=="object")return"";for(const key of ["text","output_text","content","message"]){if(typeof value[key]==="string"&&value[key].trim())return value[key];}for(const key of ["output","result","data","response","raw"]){const found=findText(value[key],depth+1);if(found)return found;}return"";}
function parseJson(value){const source=text(value,30000);if(!source)return null;const first=source.indexOf("{"),last=source.lastIndexOf("}");for(const candidate of [source,first>=0&&last>first?source.slice(first,last+1):""]){if(!candidate)continue;try{const parsed=JSON.parse(candidate);if(parsed&&typeof parsed==="object"&&!Array.isArray(parsed))return parsed;}catch{}}return null;}

export function preparedCandidateNeedsIntelligence(candidate={}){const type=text(candidate.type,100).toLowerCase();const status=text(candidate.status,100).toUpperCase();if(!type)return false;if(BLOCKING_STATUSES.has(status))return true;if(ALWAYS_REVIEW_READY.has(type)&&status==="READY_FOR_REVIEW")return true;if(type==="inventory_import"&&Number(candidate.ambiguous_count)>0)return true;return false;}
export function preparedAttachmentNeedsIntelligence(attachment={}){const candidate=object(attachment.prepared_candidate);const businessMatch=object(attachment.business_match);return preparedCandidateNeedsIntelligence(candidate)||text(businessMatch.status,100).toUpperCase()==="AMBIGUOUS_MATCH"||businessMatch.clarification_required===true;}

export async function reasonPreparedAttachmentClarification({organizationId,partyId,entityId=null,locale=null,message="",candidate={},attachment={}}={}){
  if(!organizationId||!partyId)throw new Error("PREPARED_ATTACHMENT_CLARIFICATION_CONTEXT_REQUIRED");
  const request={contract:CONTRACT,user_message:text(message,4000),locale:text(locale,80)||null,verified_attachment_state:{type:text(candidate.type,100),status:text(candidate.status,100),deterministic_clarification:text(candidate.clarification_question,1200)||null,candidate,source_evidence:object(object(attachment.analysis).evidence),business_match:object(attachment.business_match)}};
  const instructions=`You are Avantiqo Intelligence acting as a senior business operator. A deterministic attachment processor has already extracted facts, matched records where possible, and enforced hard validation. Your job is only to decide the best human-facing clarification when a material fact is unresolved. Do not weaken, override, bypass, reinterpret away, or satisfy a deterministic blocker. Do not authorize or execute any write. Reason from the actual verified attachment state and source evidence, not a fixed questionnaire. Ask exactly one concise practical question that resolves the highest-value missing or ambiguous fact. Do not ask for facts already evidenced. Never invent entity, supplier, customer, account, tax treatment, SKU, UOM, quantity, price, payment state, PO match, recipe yield, batch output, or any other business fact. For recipe READY_FOR_REVIEW, you may still ask when a material costing uncertainty remains, including unevidenced yield or preparation output; otherwise say no clarification is required. For all deterministic blocking statuses, clarification_required must be true. Return strict JSON only: {"clarification_required":true,"question":"...","reason":"...","missing_fact":"..."}.`;
  let execution=await ServiceExecutionRuntime.execute({organization_id:organizationId,party_id:partyId,entity_id:entityId,service_id:"ai.text.generate",...ownedOperatorIntelligenceSelectionPolicy(),input:{input:JSON.stringify(request),instructions_text:instructions,max_output_tokens:180,text:{verbosity:"low"},response_format:{type:"json_object"}},metadata:{module:"OPERATOR",operation:"PREPARED_ATTACHMENT_CLARIFICATION_REASONING",attachment_type:text(candidate.type,100),authorization_effect:"NONE",deterministic_validation_preserved:true},category:"AI"});
  execution=await settleOperatorIntelligenceExecution({organization_id:organizationId,execution,service_id:"ai.text.generate",execution_lane:"fast",metadata:{module:"OPERATOR",operation:"PREPARED_ATTACHMENT_CLARIFICATION_REASONING_SETTLEMENT",raw_reasoning_persisted:false}});
  const parsed=parseJson(findText(execution));const status=text(candidate.status,100).toUpperCase();const hardBlocked=BLOCKING_STATUSES.has(status)||(text(candidate.type,100).toLowerCase()==="inventory_import"&&Number(candidate.ambiguous_count)>0);const required=hardBlocked||parsed?.clarification_required===true;const question=text(parsed?.question,1200);if(required&&!question)throw new Error("PREPARED_ATTACHMENT_CLARIFICATION_QUESTION_REQUIRED");
  return{contract:CONTRACT,clarification_required:required,question:question||null,reason:text(parsed?.reason,1200)||null,missing_fact:text(parsed?.missing_fact,300)||null,provider_evidence:{provider:text(execution?.provider,120)||"avantiqo-intelligence",model:text(execution?.model,240)||null,usage_id:execution?.usage?.id||execution?.usage_id||null}};
}

export default reasonPreparedAttachmentClarification;
