export const SIGNAL_TYPES = {

  ORDER_CREATED:
    "ORDER_CREATED",

  ORDER_COMPLETED:
    "ORDER_COMPLETED",

  ORDER_CANCELLED:
    "ORDER_CANCELLED",

  PAYMENT_RECEIVED:
    "PAYMENT_RECEIVED",

  PAYMENT_FAILED:
    "PAYMENT_FAILED",

  LOW_INVENTORY:
    "LOW_INVENTORY",

  INVENTORY_UPDATED:
    "INVENTORY_UPDATED",

  PROCUREMENT_REQUIRED:
    "PROCUREMENT_REQUIRED",

  WORKFLOW_STARTED:
    "WORKFLOW_STARTED",

  WORKFLOW_COMPLETED:
    "WORKFLOW_COMPLETED",

  WORKFLOW_FAILED:
    "WORKFLOW_FAILED",

  APPROVAL_REQUIRED:
    "APPROVAL_REQUIRED",

  APPROVAL_COMPLETED:
    "APPROVAL_COMPLETED",

  AI_ALERT:
    "AI_ALERT",

  AI_DECISION:
    "AI_DECISION",

  STAFF_CLOCKED_IN:
    "STAFF_CLOCKED_IN",

  STAFF_CLOCKED_OUT:
    "STAFF_CLOCKED_OUT",

  ALERT_TRIGGERED:
    "ALERT_TRIGGERED",

};
