"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Archive, Download, LoaderCircle, ShieldCheck } from "lucide-react";

const text = (value) => String(value ?? "").trim();
const shortDate = (value) => value ? String(value).replace("T", " ").slice(0, 16) : "—";

export default function PublicAuditorPackagePage() {
  const params = useParams(); const token = text(params?.token);
  const [state, setState] = useState({ loading: true, error: "", data: null });
  useEffect(() => { if (!token) return; fetch(`/api/public/finance/auditor-package/${encodeURIComponent(token)}`, { cache: "no-store" }).then(async (r) => { const body = await r.json().catch(() => ({})); if (!r.ok || body?.success === false) throw new Error(body?.error || "Auditor package unavailable"); return body; }).then((data) => setState({ loading: false, error: "", data })).catch((error) => setState({ loading: false, error: error?.message || "Auditor package unavailable", data: null })); }, [token]);
  if (state.loading) return <main className="min-h-screen bg-[#F3F0EA] p-6"><div className="mx-auto flex max-w-2xl items-center justify-center rounded-3xl bg-white p-12 text-sm text-[#817A72]"><LoaderCircle size={16} className="mr-2 animate-spin"/>Loading frozen auditor package…</div></main>;
  if (state.error) return <main className="min-h-screen bg-[#F3F0EA] p-6"><div className="mx-auto max-w-2xl rounded-3xl border border-red-700/15 bg-white p-10 text-center"><ShieldCheck size={24} className="mx-auto text-[#A37849]"/><h1 className="mt-3 text-lg font-semibold">Auditor package unavailable</h1><p className="mt-2 text-sm text-[#817A72]">{state.error}</p></div></main>;
  const data = state.data || {}; const manifest = data.package?.manifest || {};
  return <main className="min-h-screen bg-[#F3F0EA] px-4 py-8 text-[#2A2723]"><div className="mx-auto max-w-3xl"><section className="overflow-hidden rounded-3xl border border-black/[0.07] bg-white"><div className="bg-[#171512] p-6 text-white"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#D6A66A]"><Archive size={14}/>Auditor evidence room</div><h1 className="mt-2 text-2xl font-semibold">Frozen Finance package v{data.package?.version}</h1><div className="mt-1 text-xs text-white/55">Read-only · exact package only · no ERP access</div></div><div className="p-5 md:p-6"><div className="grid gap-2 sm:grid-cols-2"><Info label="Auditor" value={data.auditor?.name || data.auditor?.email}/><Info label="Access expires" value={shortDate(data.auditor?.expires_at)}/><Info label="Period" value={`${manifest.period?.start_date || "—"} → ${manifest.period?.end_date || "—"}`}/><Info label="Generated" value={shortDate(data.package?.generated_at)}/><Info label="Package digest" value={`${text(data.package?.package_digest).slice(0, 20)}…`}/><Info label="Close fingerprint" value={`${text(data.package?.close_fingerprint_digest).slice(0, 20)}…`}/></div><div className="mt-4 rounded-xl border border-emerald-700/15 bg-emerald-50 p-3 text-xs leading-5 text-emerald-900"><b>Immutable snapshot.</b> This package was frozen from one governed Finance close. Downloading it does not grant access to journals, ERP data or mutation APIs.</div><div className="mt-4 rounded-xl bg-[#F8F6F2] p-4"><div className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#8A633C]">Package population</div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.entries(manifest.population || {}).map(([key, value]) => <div key={key} className="rounded-lg bg-white p-2"><div className="text-[9px] text-[#918B83]">{key.replace(/_/g, " ")}</div><div className="mt-1 text-sm font-semibold">{value}</div></div>)}</div></div><a href={`/api/public/finance/auditor-package/${encodeURIComponent(token)}/download`} className="mt-5 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#76583A] text-sm font-semibold text-white"><Download size={15}/>Download frozen auditor ZIP</a></div></section></div></main>;
}
function Info({ label, value }) { return <div className="rounded-xl bg-[#F8F6F2] p-3"><div className="text-[9px] uppercase tracking-[0.1em] text-[#918B83]">{label}</div><div className="mt-1 break-all text-xs font-semibold">{value || "—"}</div></div>; }
