export const PAYROLL_STATUS = {
  GENERATED: "GENERATED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  RECALCULATED: "RECALCULATED",
  LOCKED: "LOCKED",
  PAID: "PAID",
  DISPUTED: "DISPUTED",
  RESOLVED: "RESOLVED",
  FINALIZED: "FINALIZED",
  ACCOUNTING_CLOSED: "ACCOUNTING_CLOSED",
  CERTIFIED: "CERTIFIED",
  ARCHIVED: "ARCHIVED",
};

export const PAYROLL_TRANSITIONS = {
  GENERATED: [
    PAYROLL_STATUS.APPROVED,
    PAYROLL_STATUS.REJECTED,
  ],
  REJECTED: [PAYROLL_STATUS.RECALCULATED],
  RECALCULATED: [
    PAYROLL_STATUS.APPROVED,
    PAYROLL_STATUS.REJECTED,
  ],
  APPROVED: [PAYROLL_STATUS.LOCKED],
  LOCKED: [PAYROLL_STATUS.PAID],
  PAID: [
    PAYROLL_STATUS.DISPUTED,
    PAYROLL_STATUS.FINALIZED,
  ],
  DISPUTED: [PAYROLL_STATUS.RESOLVED],
  RESOLVED: [PAYROLL_STATUS.FINALIZED],
  FINALIZED: [PAYROLL_STATUS.ACCOUNTING_CLOSED],
  ACCOUNTING_CLOSED: [PAYROLL_STATUS.CERTIFIED],
  CERTIFIED: [PAYROLL_STATUS.ARCHIVED],
  ARCHIVED: [],
};

export function canTransition(currentStatus, nextStatus) {
  return (PAYROLL_TRANSITIONS[currentStatus] || []).includes(nextStatus);
}
