export const dynamic = "force-dynamic";
export const runtime = "nodejs";
import { NextResponse } from "next/server";
import * as CreativeProjectRepository from "@/lib/creative/projects/repositories/CreativeProjectRepository";
import { CreativeAssetsRuntime } from "@/lib/creative/assets/runtime/CreativeAssetsRuntime";
import { resolveCreativeProviderAssetUrl } from "@/lib/creative/assets/storage/resolveCreativeProviderAssetUrl";
import { ensureMusicEngineeringBuses, validateMusicMixerRouting } from "@/lib/creative/music/runtime/CreativeMusicMixerRoutingRuntime";
import { createMusicMultitrackProject, validateMusicMultitrackProject } from "@/lib/creative/music/runtime/CreativeMusicMultitrackRuntime";
import { validateMusicGroupProcessing } from "@/lib/creative/music/runtime/CreativeMusicBusProcessingRuntime";
import { validateMusicAutomation } from "@/lib/creative/music/runtime/CreativeMusicAutomationRuntime";
import { analyzeMusicMixEngineer, applyMusicMixEngineerPlan, createMusicMixEngineerSnapshot, validateMusicMixEngineerSnapshot, createMusicMixEngineerBaseline, sessionMusicMixFingerprint } from "@/lib/creative/music/runtime/CreativeMusicMixEngineerRuntime";
import { analyzeMusicMixEvidence } from "@/lib/creative/music/runtime/CreativeMusicMixEvidenceRuntime";
import { ensureMusicArrangement } from "@/lib/creative/music/runtime/CreativeMusicArrangementRuntime";
import { requireOrganizationAccess } from "@/lib/platform/security/requireOrganizationAccess";
const KEY="music_multitrack_project",ARRANGEMENT_KEY="music_arrangement",HISTORY="music_mix_engineer_history",BASELINE="music_mix_engineer_baseline",LAST="music_mix_engineer_last_applied",MAX_HISTORY=12,PERMISSIONS=["creative.execute","creative.production.run","creative.*"];
const text=v=>String(v??"").trim(); const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
async function access(request,organizationId){const a=await requireOrganizationAccess({organizationId,request,requiredAnyPermission:PERMISSIONS});if(!a.success){const e=new Error(a.error||"CREATIVE_MUSIC_MIX_ACCESS_FORBIDDEN");e.status=a.status||403;throw e;}}
async function projectInScope(org,id){const p=await CreativeProjectRepository.getById(id);if(!p||String(p.organization_id)!==String(org)){const e=new Error("CREATIVE_MUSIC_MIX_PROJECT_NOT_FOUND");e.status=404;throw e;}return p;}
function defaultSession(p){return createMusicMultitrackProject({id:`music-multitrack-${p.id}`,title:p.name||p.title||"Music Project",bpm:p.metadata?.music_bpm||96,time_signature:p.metadata?.music_time_signature||"4/4",sample_rate:48000});}
function normalize(s){const n=ensureMusicEngineeringBuses(s);validateMusicMultitrackProject(n);validateMusicMixerRouting(n);validateMusicGroupProcessing(n);validateMusicAutomation(n);return n;}
function history(p){return Array.isArray(p.metadata?.[HISTORY])?p.metadata[HISTORY].slice(-MAX_HISTORY):[];}

function baseline(p,session){const saved=p.metadata?.[BASELINE];return saved?.contract?structuredClone(saved):createMusicMixEngineerBaseline(session);}
function lastApplied(p){return p.metadata?.[LAST]&&typeof p.metadata[LAST]==="object"?p.metadata[LAST]:null;}
function rebaseRequired(p,session){const last=lastApplied(p);if(!last?.session_fingerprint)return false;return sessionMusicMixFingerprint(session)!==last.session_fingerprint;}
function sessionAssetIds(session={}){return new Set((session.tracks||[]).flatMap(track=>(track.clips||[]).filter(clip=>clip?.muted!==true).map(clip=>text(clip.source_asset_id))).filter(Boolean));}
function sortedUnique(values=[]){return [...new Set(values.map(text).filter(Boolean))].sort();}
async function evidenceInputs(org,projectId,session){const ids=sessionAssetIds(session);const assets=await CreativeAssetsRuntime.list({organization_id:org,creative_project_id:projectId,limit:Math.max(300,ids.size*3)});const asset_urls={},track_render_urls={};const revision=Math.max(0,Math.round(finite(session.revision,0)));const trackSources=new Map((session.tracks||[]).map(track=>[track.id,sortedUnique((track.clips||[]).filter(clip=>clip?.muted!==true).map(clip=>clip.source_asset_id))]));for(const asset of assets){const id=text(asset?.id||asset?.asset_id),source=text(asset?.file_url||asset?.url),meta=asset?.metadata||{};if(id&&ids.has(id)&&source)asset_urls[id]=await resolveCreativeProviderAssetUrl({organization_id:org,value:source});if(text(meta.music_asset_kind)!=="TRACK_EVIDENCE_RENDER"||text(meta.render_kind)!=="TRACK_EVIDENCE"||text(meta.stem_stage)!=="post-source-cleanup-pre-track-processing"||meta.track_processing_applied===true||Math.round(finite(meta.project_revision,-1))!==revision)continue;const trackId=text(meta.target_id),expected=trackSources.get(trackId);if(!trackId||!expected||!expected.length)continue;const lineage=sortedUnique(meta.source_asset_ids||[]);if(JSON.stringify(lineage)!==JSON.stringify(expected)||!source)continue;track_render_urls[trackId]=await resolveCreativeProviderAssetUrl({organization_id:org,value:source});}return{asset_urls,track_render_urls};}
async function evidence(org,projectId,session){const inputs=await evidenceInputs(org,projectId,session);return analyzeMusicMixEvidence({organization_id:org,session,...inputs});}
export async function POST(request){try{const body=await request.json(),org=text(body.organization_id),id=text(body.creative_project_id);if(!org)return NextResponse.json({success:false,error:"organization_id required"},{status:400});await access(request,org);const p=await projectInScope(org,id),session=normalize(p.metadata?.[KEY]||defaultSession(p)),action=text(body.action||"analyze").toLowerCase();
 const arrangement=ensureMusicArrangement(p.metadata?.[ARRANGEMENT_KEY]||{});
 if(action==="analyze"){const mixEvidence=await evidence(org,id,session),base=baseline(p,session),diverged=rebaseRequired(p,session),plan=analyzeMusicMixEngineer(session,mixEvidence,arrangement,base),last=lastApplied(p);if(diverged)plan.status="REBASE_REQUIRED";else if(last?.plan_fingerprint===plan.plan_fingerprint&&last?.baseline_fingerprint===plan.baseline_fingerprint)plan.status="NO_NEW_MIX_CHANGES";return NextResponse.json({success:true,plan,evidence:mixEvidence,revision:session.revision||0,undo_available:history(p).length>0,rebase_required:diverged,mutation_performed:false},{headers:{"Cache-Control":"no-store"}});}
 if(action==="undo"){const h=history(p),snap=h.at(-1);if(!snap)throw new Error("CREATIVE_MUSIC_MIX_UNDO_NOT_AVAILABLE");validateMusicMixEngineerSnapshot(snap);const restored=normalize(structuredClone(snap.session));restored.revision=Math.max(0,Math.round(finite(session.revision,0)))+1;await CreativeProjectRepository.update(p.id,{metadata:{...(p.metadata||{}),[KEY]:restored,[LAST]:null,[HISTORY]:h.slice(0,-1),music_mix_engineer_last_action:"UNDO",music_multitrack_updated_at:new Date().toISOString()}});return NextResponse.json({success:true,action:"undo",revision:restored.revision,undo_available:h.length>1,source_assets_preserved:true,mutation_performed:true});}
 if(action==="rebase"){const expected=Math.max(0,Math.round(finite(body.expected_revision,-1))),current=Math.max(0,Math.round(finite(session.revision,0)));if(expected!==current){const e=new Error(`CREATIVE_MUSIC_MIX_REVISION_CONFLICT:expected=${expected}:current=${current}`);e.status=409;throw e;}const nextBaseline=createMusicMixEngineerBaseline(session);await CreativeProjectRepository.update(p.id,{metadata:{...(p.metadata||{}),[BASELINE]:nextBaseline,[LAST]:null,music_mix_engineer_last_action:"REBASE",music_mix_engineer_updated_at:new Date().toISOString()}});return NextResponse.json({success:true,action:"rebase",status:"REBASED",revision:current,baseline_fingerprint:nextBaseline.fingerprint,undo_available:history(p).length>0,source_assets_preserved:true,audio_render_performed:false,mutation_performed:true},{headers:{"Cache-Control":"no-store"}});}
 const expected=Math.max(0,Math.round(finite(body.expected_revision,-1))),current=Math.max(0,Math.round(finite(session.revision,0)));if(expected!==current){const e=new Error(`CREATIVE_MUSIC_MIX_REVISION_CONFLICT:expected=${expected}:current=${current}`);e.status=409;throw e;}if(action!=="apply")throw new Error("CREATIVE_MUSIC_MIX_ACTION_INVALID");const base=baseline(p,session);if(rebaseRequired(p,session)){return NextResponse.json({success:true,action:"apply",status:"REBASE_REQUIRED",revision:current,undo_available:history(p).length>0,rebase_required:true,mutation_performed:false},{headers:{"Cache-Control":"no-store"}});}const mixEvidence=await evidence(org,id,session),plan=analyzeMusicMixEngineer(session,mixEvidence,arrangement,base),last=lastApplied(p);if(last?.plan_fingerprint===plan.plan_fingerprint&&last?.baseline_fingerprint===plan.baseline_fingerprint){return NextResponse.json({success:true,action:"apply",status:"NO_NEW_MIX_CHANGES",revision:current,plan,evidence:mixEvidence,undo_available:history(p).length>0,reversible:true,source_assets_preserved:true,audio_render_performed:false,mutation_performed:false},{headers:{"Cache-Control":"no-store"}});}const snap=createMusicMixEngineerSnapshot(session,plan),next=normalize(applyMusicMixEngineerPlan(session,plan)),appliedFingerprint=sessionMusicMixFingerprint(next);await CreativeProjectRepository.update(p.id,{metadata:{...(p.metadata||{}),[KEY]:next,[BASELINE]:base,[LAST]:{contract:"AVANTIQO_MUSIC_MIX_ENGINEER_LAST_APPLIED_V1",plan_fingerprint:plan.plan_fingerprint,baseline_fingerprint:plan.baseline_fingerprint,session_fingerprint:appliedFingerprint,applied_revision:next.revision,applied_at:new Date().toISOString()},[HISTORY]:[...history(p),snap].slice(-MAX_HISTORY),music_mix_engineer_last_action:"APPLY",music_mix_engineer_updated_at:new Date().toISOString(),music_multitrack_updated_at:new Date().toISOString()}});return NextResponse.json({success:true,action:"apply",status:"APPLIED",revision:next.revision,plan,evidence:mixEvidence,snapshot_id:snap.id,undo_available:true,reversible:true,source_assets_preserved:true,audio_render_performed:false,artistic_listening_review_required:true,mutation_performed:true},{headers:{"Cache-Control":"no-store"}});
}catch(error){return NextResponse.json({success:false,error:error?.message||"Music Mix Engineer failed"},{status:error?.status||400});}}
