export const dynamic = "force-dynamic";
export const runtime = "nodejs";
import { NextResponse } from "next/server";
import * as CreativeProjectRepository from "@/lib/creative/projects/repositories/CreativeProjectRepository";
import { ensureMusicEngineeringBuses, validateMusicMixerRouting } from "@/lib/creative/music/runtime/CreativeMusicMixerRoutingRuntime";
import { createMusicMultitrackProject, validateMusicMultitrackProject } from "@/lib/creative/music/runtime/CreativeMusicMultitrackRuntime";
import { validateMusicGroupProcessing } from "@/lib/creative/music/runtime/CreativeMusicBusProcessingRuntime";
import { validateMusicAutomation } from "@/lib/creative/music/runtime/CreativeMusicAutomationRuntime";
import { analyzeMusicMixEngineer, applyMusicMixEngineerPlan, createMusicMixEngineerSnapshot, validateMusicMixEngineerSnapshot } from "@/lib/creative/music/runtime/CreativeMusicMixEngineerRuntime";
import { requireOrganizationAccess } from "@/lib/platform/security/requireOrganizationAccess";
const KEY="music_multitrack_project",HISTORY="music_mix_engineer_history",MAX_HISTORY=12,PERMISSIONS=["creative.execute","creative.production.run","creative.*"];
const text=v=>String(v??"").trim(); const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
async function access(request,organizationId){const a=await requireOrganizationAccess({organizationId,request,requiredAnyPermission:PERMISSIONS});if(!a.success){const e=new Error(a.error||"CREATIVE_MUSIC_MIX_ACCESS_FORBIDDEN");e.status=a.status||403;throw e;}}
async function projectInScope(org,id){const p=await CreativeProjectRepository.getById(id);if(!p||String(p.organization_id)!==String(org)){const e=new Error("CREATIVE_MUSIC_MIX_PROJECT_NOT_FOUND");e.status=404;throw e;}return p;}
function defaultSession(p){return createMusicMultitrackProject({id:`music-multitrack-${p.id}`,title:p.name||p.title||"Music Project",bpm:p.metadata?.music_bpm||96,time_signature:p.metadata?.music_time_signature||"4/4",sample_rate:48000});}
function normalize(s){const n=ensureMusicEngineeringBuses(s);validateMusicMultitrackProject(n);validateMusicMixerRouting(n);validateMusicGroupProcessing(n);validateMusicAutomation(n);return n;}
function history(p){return Array.isArray(p.metadata?.[HISTORY])?p.metadata[HISTORY].slice(-MAX_HISTORY):[];}
export async function POST(request){try{const body=await request.json(),org=text(body.organization_id),id=text(body.creative_project_id);if(!org)return NextResponse.json({success:false,error:"organization_id required"},{status:400});await access(request,org);const p=await projectInScope(org,id),session=normalize(p.metadata?.[KEY]||defaultSession(p)),action=text(body.action||"analyze").toLowerCase();
 if(action==="analyze"){return NextResponse.json({success:true,plan:analyzeMusicMixEngineer(session),revision:session.revision||0,undo_available:history(p).length>0,mutation_performed:false},{headers:{"Cache-Control":"no-store"}});}
 if(action==="undo"){const h=history(p),snap=h.at(-1);if(!snap)throw new Error("CREATIVE_MUSIC_MIX_UNDO_NOT_AVAILABLE");validateMusicMixEngineerSnapshot(snap);const restored=normalize(structuredClone(snap.session));restored.revision=Math.max(0,Math.round(finite(session.revision,0)))+1;await CreativeProjectRepository.update(p.id,{metadata:{...(p.metadata||{}),[KEY]:restored,[HISTORY]:h.slice(0,-1),music_mix_engineer_last_action:"UNDO",music_multitrack_updated_at:new Date().toISOString()}});return NextResponse.json({success:true,action:"undo",revision:restored.revision,undo_available:h.length>1,source_assets_preserved:true,mutation_performed:true});}
 const expected=Math.max(0,Math.round(finite(body.expected_revision,-1))),current=Math.max(0,Math.round(finite(session.revision,0)));if(expected!==current){const e=new Error(`CREATIVE_MUSIC_MIX_REVISION_CONFLICT:expected=${expected}:current=${current}`);e.status=409;throw e;}if(action!=="apply")throw new Error("CREATIVE_MUSIC_MIX_ACTION_INVALID");const plan=analyzeMusicMixEngineer(session),snap=createMusicMixEngineerSnapshot(session,plan),next=normalize(applyMusicMixEngineerPlan(session,plan));await CreativeProjectRepository.update(p.id,{metadata:{...(p.metadata||{}),[KEY]:next,[HISTORY]:[...history(p),snap].slice(-MAX_HISTORY),music_mix_engineer_last_action:"APPLY",music_mix_engineer_updated_at:new Date().toISOString(),music_multitrack_updated_at:new Date().toISOString()}});return NextResponse.json({success:true,action:"apply",revision:next.revision,plan,snapshot_id:snap.id,reversible:true,source_assets_preserved:true,audio_render_performed:false,artistic_listening_review_required:true,mutation_performed:true},{headers:{"Cache-Control":"no-store"}});
}catch(error){return NextResponse.json({success:false,error:error?.message||"Music Mix Engineer failed"},{status:error?.status||400});}}
