export const WORLD_CLASS_CONCEPT_POLICY = Object.freeze({
  contract: "AVANTIQO_WORLD_CLASS_CONCEPT_INTELLIGENCE_V1",
  minimum_weighted_score: 92,
  minimum_selector_confidence: 90,
  maximum_pairwise_similarity: 0.55,
  critic_minimums: Object.freeze({
    originality: 94,
    music_energy: 92,
    brand_commercial: 92,
    production: 88,
  }),
  minimum_signature_images: 5,
  minimum_campaign_extensions: 3,
  minimum_anti_cliche_rules: 3,
  generic_swap_test_required: true,
  evidence_specificity_required: true,
  ownable_mechanism_required: true,
  earned_surprise_required: true,
  medium_native_idea_required: true,
  b_grade_concept_forbidden: true,
});
