import { APPROVAL_STATUS }
from "@/lib/shared/constants/statuses";

export const APPROVAL_FLOWS = {

  invoice: [

    APPROVAL_STATUS.SUBMITTED,

    APPROVAL_STATUS.PENDING_MANAGER,

    APPROVAL_STATUS.PENDING_ACCOUNTING,

    APPROVAL_STATUS.PENDING_OWNER,

    APPROVAL_STATUS.APPROVED,

    APPROVAL_STATUS.PAID,

    APPROVAL_STATUS.LOCKED,

  ],

  payroll: [

    APPROVAL_STATUS.SUBMITTED,

    APPROVAL_STATUS.PENDING_MANAGER,

    APPROVAL_STATUS.PENDING_ACCOUNTING,

    APPROVAL_STATUS.PENDING_OWNER,

    APPROVAL_STATUS.APPROVED,

    APPROVAL_STATUS.LOCKED,

  ],

};