const CHANNELS = Object.freeze([
  Object.freeze({
    id: "meta",
    name: "Meta Ads",
    kind: "paid_media",
    provider: "meta",
    capability: "marketing.ads.manage",
    service_id: "meta-ads",
    runtime_status: "ACTIVE",
    networks: Object.freeze(["facebook", "instagram", "messenger", "audience_network"]),
    destinations: Object.freeze(["ENGAGEMENT", "WEBSITE", "LEADS", "WHATSAPP", "MESSENGER", "INSTAGRAM_DIRECT"]),
    formats: Object.freeze(["IMAGE", "VIDEO", "CAROUSEL", "STORY", "REEL"]),
  }),
  Object.freeze({
    id: "google_ads",
    name: "Google Ads",
    kind: "paid_media",
    provider: "google",
    capability: "marketing.google.ads.manage",
    service_id: "google-ads",
    runtime_status: "IMPLEMENTATION_REQUIRED",
    networks: Object.freeze(["search", "display", "youtube", "performance_max", "demand_gen", "shopping", "apps"]),
    destinations: Object.freeze(["WEBSITE", "LEADS", "CALLS", "STORE_VISITS", "APP"]),
    formats: Object.freeze(["SEARCH", "IMAGE", "VIDEO", "PRODUCT", "RESPONSIVE"]),
  }),
  Object.freeze({
    id: "tiktok_ads",
    name: "TikTok Ads",
    kind: "paid_media",
    provider: "tiktok",
    capability: "marketing.tiktok.ads.manage",
    service_id: "tiktok-ads",
    runtime_status: "IMPLEMENTATION_REQUIRED",
    networks: Object.freeze(["tiktok", "pangle"]),
    destinations: Object.freeze(["WEBSITE", "LEADS", "APP", "VIDEO_VIEWS", "SALES"]),
    formats: Object.freeze(["VIDEO", "SPARK_AD", "CAROUSEL"]),
  }),
  Object.freeze({
    id: "line_ads",
    name: "LINE Ads",
    kind: "paid_media",
    provider: "line",
    capability: "marketing.line.ads.manage",
    service_id: "line-ads",
    runtime_status: "IMPLEMENTATION_REQUIRED",
    markets_from_configuration: true,
    networks: Object.freeze(["line"]),
    destinations: Object.freeze(["WEBSITE", "APP", "LINE_OFFICIAL_ACCOUNT"]),
    formats: Object.freeze(["IMAGE", "VIDEO", "CAROUSEL"]),
  }),
  Object.freeze({
    id: "microsoft_ads",
    name: "Microsoft Advertising",
    kind: "paid_media",
    provider: "microsoft",
    capability: "marketing.microsoft.ads.manage",
    service_id: "microsoft-ads",
    runtime_status: "NOT_REGISTERED",
    networks: Object.freeze(["bing", "microsoft_audience", "copilot"]),
    destinations: Object.freeze(["WEBSITE", "LEADS", "CALLS", "SHOPPING"]),
    formats: Object.freeze(["SEARCH", "IMAGE", "VIDEO", "PRODUCT"]),
  }),
  Object.freeze({
    id: "linkedin_ads",
    name: "LinkedIn Ads",
    kind: "paid_media",
    provider: "linkedin",
    capability: "marketing.linkedin.ads.manage",
    service_id: "linkedin-ads",
    runtime_status: "IMPLEMENTATION_REQUIRED",
    networks: Object.freeze(["linkedin"]),
    destinations: Object.freeze(["WEBSITE", "LEADS", "ENGAGEMENT", "VIDEO_VIEWS"]),
    formats: Object.freeze(["IMAGE", "VIDEO", "CAROUSEL", "DOCUMENT", "MESSAGE"]),
  }),
  Object.freeze({
    id: "pinterest_ads",
    name: "Pinterest Ads",
    kind: "paid_media",
    provider: "pinterest",
    capability: "marketing.pinterest.ads.manage",
    service_id: "pinterest-ads",
    runtime_status: "NOT_REGISTERED",
    networks: Object.freeze(["pinterest"]),
    destinations: Object.freeze(["WEBSITE", "SALES", "AWARENESS"]),
    formats: Object.freeze(["IMAGE", "VIDEO", "CAROUSEL", "SHOPPING"]),
  }),
  Object.freeze({
    id: "snapchat_ads",
    name: "Snapchat Ads",
    kind: "paid_media",
    provider: "snapchat",
    capability: "marketing.snapchat.ads.manage",
    service_id: "snapchat-ads",
    runtime_status: "NOT_REGISTERED",
    networks: Object.freeze(["snapchat"]),
    destinations: Object.freeze(["WEBSITE", "APP", "LEADS", "SALES"]),
    formats: Object.freeze(["VIDEO", "IMAGE", "AR"]),
  }),
  Object.freeze({
    id: "x_ads",
    name: "X Ads",
    kind: "paid_media",
    provider: "x",
    capability: "marketing.x.ads.manage",
    service_id: "x-ads",
    runtime_status: "IMPLEMENTATION_REQUIRED",
    networks: Object.freeze(["x"]),
    destinations: Object.freeze(["WEBSITE", "ENGAGEMENT", "VIDEO_VIEWS", "APP"]),
    formats: Object.freeze(["TEXT", "IMAGE", "VIDEO", "CAROUSEL"]),
  }),
  Object.freeze({
    id: "reddit_ads",
    name: "Reddit Ads",
    kind: "paid_media",
    provider: "reddit",
    capability: "marketing.reddit.ads.manage",
    service_id: "reddit-ads",
    runtime_status: "NOT_REGISTERED",
    networks: Object.freeze(["reddit"]),
    destinations: Object.freeze(["WEBSITE", "ENGAGEMENT", "APP"]),
    formats: Object.freeze(["TEXT", "IMAGE", "VIDEO", "CAROUSEL"]),
  }),
  Object.freeze({
    id: "amazon_ads",
    name: "Amazon Ads",
    kind: "paid_media",
    provider: "amazon",
    capability: "marketing.amazon.ads.manage",
    service_id: "amazon-ads",
    runtime_status: "NOT_REGISTERED",
    networks: Object.freeze(["sponsored_products", "sponsored_brands", "display", "streaming_tv"]),
    destinations: Object.freeze(["PRODUCT", "STORE", "WEBSITE"]),
    formats: Object.freeze(["PRODUCT", "IMAGE", "VIDEO"]),
  }),
  Object.freeze({
    id: "email",
    name: "Email",
    kind: "owned_channel",
    provider: "email",
    capability: "communication.email.send",
    service_id: "email-campaigns",
    runtime_status: "IMPLEMENTATION_REQUIRED",
    networks: Object.freeze(["email"]),
    destinations: Object.freeze(["WEBSITE", "REPLY", "BOOKING", "PURCHASE"]),
    formats: Object.freeze(["HTML", "TEXT", "NEWSLETTER", "AUTOMATION"]),
  }),
  Object.freeze({
    id: "whatsapp",
    name: "WhatsApp Business",
    kind: "owned_channel",
    provider: "whatsapp",
    capability: "communication.whatsapp.send",
    service_id: "whatsapp-messaging",
    runtime_status: "ACTIVE_IF_CONFIGURED",
    networks: Object.freeze(["whatsapp"]),
    destinations: Object.freeze(["CONVERSATION", "BOOKING", "PURCHASE", "SUPPORT"]),
    formats: Object.freeze(["TEMPLATE", "TEXT", "IMAGE", "VIDEO", "DOCUMENT"]),
  }),
  Object.freeze({
    id: "line",
    name: "LINE Official Account",
    kind: "owned_channel",
    provider: "line",
    capability: "communication.line.send",
    service_id: "line-messaging",
    runtime_status: "ACTIVE_IF_CONFIGURED",
    networks: Object.freeze(["line"]),
    destinations: Object.freeze(["CONVERSATION", "FOLLOW", "WEBSITE", "PURCHASE"]),
    formats: Object.freeze(["TEXT", "IMAGE", "VIDEO", "FLEX", "RICH_MESSAGE"]),
  }),
  Object.freeze({
    id: "sms",
    name: "SMS",
    kind: "owned_channel",
    provider: "sms",
    capability: "communication.sms.send",
    service_id: "sms-campaigns",
    runtime_status: "IMPLEMENTATION_REQUIRED",
    networks: Object.freeze(["sms"]),
    destinations: Object.freeze(["WEBSITE", "CALL", "REPLY"]),
    formats: Object.freeze(["TEXT"]),
  }),
  Object.freeze({
    id: "push",
    name: "Mobile Push",
    kind: "owned_channel",
    provider: "push",
    capability: "communication.push.send",
    service_id: "push-campaigns",
    runtime_status: "NOT_REGISTERED",
    networks: Object.freeze(["ios", "android", "web_push"]),
    destinations: Object.freeze(["APP", "WEBSITE"]),
    formats: Object.freeze(["TEXT", "IMAGE", "DEEP_LINK"]),
  }),
  Object.freeze({
    id: "organic_social",
    name: "Organic Social",
    kind: "owned_channel",
    provider: "multi",
    capability: "marketing.social.publish",
    service_id: "social-publishing",
    runtime_status: "ACTIVE_IF_CONFIGURED",
    networks: Object.freeze(["facebook", "instagram", "tiktok", "youtube", "linkedin", "x", "pinterest", "google_business"]),
    destinations: Object.freeze(["ENGAGEMENT", "WEBSITE", "CONVERSATION"]),
    formats: Object.freeze(["TEXT", "IMAGE", "VIDEO", "STORY", "REEL", "SHORT"]),
  }),
]);

const BY_ID = Object.freeze(
  Object.fromEntries(CHANNELS.map((channel) => [channel.id, channel]))
);

export function getMarketingChannel(channelId) {
  return BY_ID[String(channelId || "").trim().toLowerCase()] || null;
}

export function listMarketingChannels({ kind = null } = {}) {
  return CHANNELS
    .filter((channel) => !kind || channel.kind === kind)
    .map((channel) => ({ ...channel }));
}

export function listExecutableMarketingChannels() {
  return CHANNELS
    .filter((channel) => ["ACTIVE", "ACTIVE_IF_CONFIGURED"].includes(channel.runtime_status))
    .map((channel) => ({ ...channel }));
}

export { CHANNELS as MARKETING_CHANNEL_CATALOG };

export default MARKETING_CHANNEL_CATALOG;
