export const WarehouseEvents = {

  TASK_CREATED:
    "WAREHOUSE_TASK_CREATED",

  TASK_ASSIGNED:
    "WAREHOUSE_TASK_ASSIGNED",

  TASK_COMPLETED:
    "WAREHOUSE_TASK_COMPLETED",

  PUTAWAY_COMPLETED:
    "WAREHOUSE_PUTAWAY_COMPLETED",

  TRANSFER_COMPLETED:
    "WAREHOUSE_TRANSFER_COMPLETED",

  PICK_COMPLETED:
    "WAREHOUSE_PICK_COMPLETED",

  COUNT_COMPLETED:
    "WAREHOUSE_COUNT_COMPLETED",

};
