import crypto from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import sharp from "sharp";

import { supabaseAdmin } from "@/lib/shared/supabase/admin";
import { resolveCreativeFfmpegPath, resolveCreativeFfprobePath } from "@/lib/creative/media/runtime/CreativeMediaBinaryRuntime";
import { investorBrandBadge, investorBrandDefs } from "@/lib/investor-film/InvestorBrandMarkRuntime";

const CONTRACT = "AVANTIQO_INVESTOR_V9_AUTHENTIC_BRAND_CORRECTION_V2";
const ORG = "33336a72-acb5-474e-856b-8be0269360e2";
const BUCKET = "creative-assets";
const FPS = 24;
const COMMUNICATION_PATH = `${ORG}/avantiqo-investor-film-20260821/communication-intelligence-v3-911f.mp4`;
const STUDIO_PATH = `${ORG}/avantiqo-investor-film-20260821/studio-marketing-cinema-v1-881f.mp4`;

function run(command,args,timeoutMs=420000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{shell:false,stdio:["ignore","pipe","pipe"],env:{...process.env,OMP_NUM_THREADS:"1"}});const out=[],err=[];let settled=false;const timer=setTimeout(()=>{child.kill("SIGKILL");if(!settled){settled=true;reject(new Error("V9_BRAND_CORRECTION_MEDIA_TIMEOUT"));}},timeoutMs);child.stdout.on("data",c=>out.push(c));child.stderr.on("data",c=>err.push(c));child.on("error",e=>{clearTimeout(timer);if(!settled){settled=true;reject(e);}});child.on("close",code=>{clearTimeout(timer);if(settled)return;settled=true;const stdout=Buffer.concat(out).toString("utf8");const stderr=Buffer.concat(err).toString("utf8");if(code!==0)reject(new Error(stderr.slice(-16000)||`MEDIA_EXIT_${code}`));else resolve(stdout);});});}
async function signed(storagePath,expires=7200){const{data,error}=await supabaseAdmin.storage.from(BUCKET).createSignedUrl(storagePath,expires);if(error)throw error;if(!data?.signedUrl)throw new Error(`V9_BRAND_SIGNED_URL_MISSING:${storagePath}`);return data.signedUrl;}
async function upload(storagePath,localPath,metadata){const bytes=await fs.readFile(localPath);const checksum=crypto.createHash("sha256").update(bytes).digest("hex");const{error}=await supabaseAdmin.storage.from(BUCKET).upload(storagePath,bytes,{contentType:"video/mp4",upsert:true,cacheControl:"3600",metadata:{...metadata,contract:CONTRACT,checksum,authentic_brand_marks:true}});if(error)throw error;return{bytes:bytes.length,checksum};}
function svgBase(body){return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540" viewBox="0 0 960 540"><defs>${investorBrandDefs()}</defs>${body}</svg>`);}
function channelOverlaySvg(){const keys=["googleReviews","whatsapp","line","email","facebook","instagram","messenger","website"];return svgBase(keys.map((key,index)=>{const row=Math.floor(index/4),col=index%4,x=78+col*205,y=215+row*58;return `<rect x="${x-3}" y="${y-3}" width="196" height="48" rx="14" fill="#08090b" fill-opacity=".98"/>${investorBrandBadge(key,{x,y,width:190,height:42})}`;}).join(""));}
function aiOverlaySvg(){const services=[["OpenAI","Reasoning",true],["Flux","Image",true],["Runway","Video",true],["Google AI","Model routing",true],["Meta","Social execution",true],["Veo","Video ecosystem",false],["Seedance","Video ecosystem",false],["ElevenLabs","Voice ecosystem",false]];return svgBase(`<rect x="48" y="207" width="864" height="132" rx="18" fill="#08090b" fill-opacity=".985"/>${services.map((item,index)=>{const col=index%4,row=Math.floor(index/4),x=62+col*218,y=220+row*58,status=item[2]?"LIVE":"ECOSYSTEM",color=item[2]?"#D6A66A":"#77736B";return `<g transform="translate(${x} ${y})"><rect width="202" height="44" rx="12" fill="#0b0c0e" stroke="#fff" stroke-opacity=".09"/><circle cx="17" cy="22" r="5.5" fill="${color}"/><text x="32" y="19" fill="#EEEDE8" font-family="Arial" font-size="11" font-weight="700">${item[0]}</text><text x="32" y="33" fill="#85827B" font-family="Arial" font-size="8.5">${item[1]}</text><text x="188" y="26" text-anchor="end" fill="${color}" font-family="Arial" font-size="7.5" font-weight="700" letter-spacing=".7">${status}</text></g>`;}).join("")}`);}
function studioOverlaySvg(){const keys=["facebook","instagram","googleAds","tiktok","youtube","linkedin"];const labels=["Facebook","Instagram","Google Ads","TikTok","YouTube","LinkedIn"];return svgBase(keys.map((key,index)=>{const x=78+index*136,y=236;return `<rect x="${x-3}" y="${y-3}" width="126" height="54" rx="16" fill="#08090b" fill-opacity=".98"/>${investorBrandBadge(key,{x,y,width:120,height:48,label:labels[index],showStatus:true})}`;}).join(""));}
async function rgbaPanel(directory,name,svg){const target=path.join(directory,`${name}.rgba`);await fs.writeFile(target,await sharp(svg).ensureAlpha().raw().toBuffer());return target;}
async function correctCommunication(ffmpeg,directory){const sourceUrl=await signed(COMMUNICATION_PATH);const channels=await rgbaPanel(directory,"channels",channelOverlaySvg());const ai=await rgbaPanel(directory,"ai",aiOverlaySvg());const output=path.join(directory,"communication-corrected-v2.mp4");const cStart=120/FPS,cEnd=(120+168)/FPS,aStart=(120+168+156)/FPS,aEnd=(120+168+156+144)/FPS;await run(ffmpeg,["-y","-i",sourceUrl,"-stream_loop","-1","-f","rawvideo","-pixel_format","rgba","-video_size","960x540","-framerate",String(FPS),"-i",channels,"-stream_loop","-1","-f","rawvideo","-pixel_format","rgba","-video_size","960x540","-framerate",String(FPS),"-i",ai,"-filter_complex",`[1:v]format=rgba,scale=1560:878[ch];[2:v]format=rgba,scale=1560:878[ai];[0:v][ch]overlay=x=180:y=101:enable='between(t,${cStart},${cEnd})':shortest=0[v1];[v1][ai]overlay=x=180:y=101:enable='between(t,${aStart},${aEnd})':shortest=0,format=yuv420p[v]`,`-map`,`[v]`,`-map`,`0:a?`,`-c:v`,`libx264`,`-preset`,`veryfast`,`-crf`,`17`,`-r`,String(FPS),`-c:a`,`copy`,`-frames:v`,`911`,output],420000);const stored=await upload(COMMUNICATION_PATH,output,{organization_id:ORG,exact_frames:911,fps:FPS,corrected_chapter:"COMMUNICATION_INTELLIGENCE"});return{path:COMMUNICATION_PATH,...stored};}
async function correctStudio(ffmpeg,directory){const sourceUrl=await signed(STUDIO_PATH);const overlay=await rgbaPanel(directory,"studio",studioOverlaySvg());const output=path.join(directory,"studio-corrected-v2.mp4");const start=(118+174+156+176)/FPS,end=(118+174+156+176+132)/FPS;await run(ffmpeg,["-y","-i",sourceUrl,"-stream_loop","-1","-f","rawvideo","-pixel_format","rgba","-video_size","960x540","-framerate",String(FPS),"-i",overlay,"-filter_complex",`[1:v]format=rgba,scale=1560:878[ov];[0:v][ov]overlay=x=180:y=101:enable='between(t,${start},${end})':shortest=0,format=yuv420p[v]`,`-map`,`[v]`,`-map`,`0:a?`,`-c:v`,`libx264`,`-preset`,`veryfast`,`-crf`,`17`,`-r`,String(FPS),`-c:a`,`copy`,`-frames:v`,`881`,output],420000);const stored=await upload(STUDIO_PATH,output,{organization_id:ORG,exact_frames:881,fps:FPS,corrected_chapter:"STUDIO_MARKETING"});return{path:STUDIO_PATH,...stored};}
async function probe(ffprobe,url){const raw=await run(ffprobe,["-v","error","-count_frames","-show_entries","stream=codec_type,width,height,r_frame_rate,nb_read_frames","-of","json",url],120000);return JSON.parse(raw||"{}");}
export const AvantiqoInvestorFilmBrandCorrectionRuntimeV2=Object.freeze({CONTRACT,async render(){const ffmpeg=resolveCreativeFfmpegPath(),ffprobe=resolveCreativeFfprobePath();if(!ffmpeg||!ffprobe)throw new Error("V9_BRAND_CORRECTION_MEDIA_BINARY_NOT_READY");const directory=await fs.mkdtemp(path.join(os.tmpdir(),"avantiqo-v9-brand-v2-"));try{const communication=await correctCommunication(ffmpeg,directory);const studio=await correctStudio(ffmpeg,directory);const[cp,sp]=await Promise.all([probe(ffprobe,await signed(COMMUNICATION_PATH)),probe(ffprobe,await signed(STUDIO_PATH))]);const cv=(cp.streams||[]).find(s=>s.codec_type==="video"),sv=(sp.streams||[]).find(s=>s.codec_type==="video");if(Number(cv?.nb_read_frames||0)!==911)throw new Error(`V9_BRAND_COMM_FRAMES_INVALID:${cv?.nb_read_frames}`);if(Number(sv?.nb_read_frames||0)!==881)throw new Error(`V9_BRAND_STUDIO_FRAMES_INVALID:${sv?.nb_read_frames}`);return{success:true,contract:CONTRACT,communication:{...communication,frames:Number(cv.nb_read_frames),dimensions:`${cv.width}x${cv.height}`,fps:cv.r_frame_rate},studio:{...studio,frames:Number(sv.nb_read_frames),dimensions:`${sv.width}x${sv.height}`,fps:sv.r_frame_rate},corrections:{authentic_channel_marks:["Facebook","Instagram","Messenger","WhatsApp","LINE","Google Reviews","Google Ads","TikTok","YouTube","LinkedIn"],neutral_owned_channel_marks:["Email","Website"],ai_service_status_truthful:true,placeholder_social_symbols_removed:true,separate_scene_overlays:true}};}finally{await fs.rm(directory,{recursive:true,force:true}).catch(()=>{});}}});
