export const AVANTIQO_INVESTOR_SCENE_5_PLUS_AUDIT_V1 = Object.freeze({
  contract: "AVANTIQO_INVESTOR_SCENE_5_PLUS_AUDIT_V1",
  audited_from_scene: 5,
  policy: Object.freeze({
    narration_visual_match_required: true,
    every_spoken_domain_or_channel_requires_visual_evidence: true,
    source_quality_required: "APPROVED_VERIFIED_OR_EXPLICITLY_USER_VISUALLY_LOCKED",
    completion_order: Object.freeze([
      "IMPLEMENT",
      "RENDER_LOCAL",
      "VISUAL_QC",
      "REPAIR_IF_NEEDED",
      "USER_APPROVAL",
      "LOCK",
      "NEXT_SCENE",
    ]),
    route_exists_does_not_mean_finished: true,
    image_generation_allowed: false,
    production_deploy_required_for_review: false,
  }),
  scenes: Object.freeze([
    Object.freeze({ scene: 5, status: "LOCKED_WITH_QUALITY_NOTE", narration_role: "OPERATIONS_KNEW_ANOTHER", semantic_visual: "REAL_OPERATIONS_EXECUTION", issue: "The locked opening uses recovered kitchen footage whose asset metadata says visual_quality_verified=false. Do not change it without explicit user unlock; audit note only.", locked: true, change_without_explicit_unlock: false }),
    Object.freeze({ scene: 6, status: "LOCKED_APPROVED", narration_role: "FRAGMENTED_SYSTEMS", semantic_visual: "CUSTOMERS_STAFF_SUPPLIERS_CONVERSATIONS_CAMPAIGNS_ADVERTISING", locked: true, change_without_explicit_unlock: false }),
    Object.freeze({ scene: 7, status: "REPAIR_SOURCE_THEN_RERENDER", narration_role: "OPERATOR_IS_INTEGRATION_LAYER", semantic_visual: "MANAGER_RECONSTRUCTING_COMPANY_CONTEXT", issue: "Current rendered source is recovered candidate footage with visual_quality_verified=false; replace with approved verified manager cinematic footage.", locked: false }),
    Object.freeze({ scene: 8, status: "LOCKED_APPROVED", narration_role: "FOUNDER_OBVIOUS", semantic_visual: "FOUNDER_ONLY", locked: true, change_without_explicit_unlock: false }),
    Object.freeze({ scene: 9, status: "REDESIGN_AND_RENDER", narration_role: "SOFTWARE_UNDERSTANDS_BUSINESS", semantic_visual: "CUSTOMER_COMMUNICATION_OPERATIONS_SUPPLY_FINANCE_CONVERGE_INTO_ONE_CONTEXT", issue: "Concept is directionally correct but current route depends on multiple recovered sources whose visual quality is unverified.", locked: false }),
    Object.freeze({ scene: 10, status: "LOCKED_APPROVED", narration_role: "FOUNDER_BUILT_AVANTIQO", semantic_visual: "FOUNDER_ONLY", locked: true, change_without_explicit_unlock: false }),
    Object.freeze({ scene: 11, status: "REPAIR_SOURCE_THEN_RENDER", narration_role: "AI_NATIVE_BUSINESS_OPERATING_SYSTEM", semantic_visual: "AUTHENTIC_ORGANIZATION_INTELLIGENCE_IN_SHARED_REAL_WORLD_CONTEXT", issue: "Authentic UI is correct; current background is an unverified recovered manager source.", locked: false }),
    Object.freeze({ scene: 12, status: "SEMANTIC_REDRAFT_REQUIRED", narration_role: "SEPARATE_FINANCE_OPERATIONS_CUSTOMERS_AI", semantic_visual: "CLEAR_FINANCE_PLUS_OPERATIONS_PLUS_CUSTOMERS_PLUS_AI_FRAGMENTATION", issue: "Operations-only visual does not communicate all domains named in narration.", locked: false }),
    Object.freeze({ scene: 13, status: "SEMANTIC_REDRAFT_REQUIRED", narration_role: "INFORMATION_DECISIONS_EXECUTION_CONNECTED", semantic_visual: "DOMAINS_CONVERGE_AND_HAND_OFF_INTO_ONE_OPERATING_CONTEXT", issue: "Supply-chain-only visual is too narrow for the spoken meaning.", locked: false }),
    Object.freeze({ scene: 14, status: "SEMANTIC_REDRAFT_REQUIRED", narration_role: "ORGANIZATION_CONTEXT", semantic_visual: "PEOPLE_ENTITIES_PERMISSIONS_CUSTOMERS_SUPPLIERS_HISTORY_CONTEXT", issue: "Finance-only visual does not match organization-context narration.", locked: false }),
    Object.freeze({ scene: 15, status: "SEMANTIC_REDRAFT_REQUIRED", narration_role: "SHARED_CONTEXT_UNIFIES_WORKSPACES", semantic_visual: "MULTIPLE_AUTHENTIC_WORKSPACES_RESOLVE_TO_ONE_ORGANIZATION_CONTEXT", issue: "General Ledger and Accounting Settings are too finance-specific for this narration.", locked: false }),
    Object.freeze({ scene: 16, status: "READY_TO_RENDER_AND_REVIEW", narration_role: "SOFTWARE_CAPABILITY_CHANGE", semantic_visual: "ORGANIZATION_INTELLIGENCE_WITH_APPROVED_MANAGER_CINEMATIC", locked: false }),
    Object.freeze({ scene: 17, status: "SEMANTIC_REDRAFT_REQUIRED", narration_role: "CUSTOMER_INTERACTION_DOES_NOT_END_IN_MESSAGING_TOOL", semantic_visual: "ALL_COMMUNICATION_CHANNELS_FEED_AUTHENTIC_CUSTOMER_COMMUNICATIONS_AND_BUSINESS_CONTEXT", issue: "Autonomous Marketing alone does not match the first communication sentence.", locked: false }),
    Object.freeze({ scene: 18, status: "SEMANTIC_REDRAFT_REQUIRED", narration_role: "CAMPAIGN_CONNECTED_TO_CUSTOMER_AND_RESULT", semantic_visual: "CAMPAIGN_CHANNELS_TO_AUTONOMOUS_MARKETING_TO_CUSTOMER_TO_RESULT", issue: "Kitchen execution is unrelated and must not be used as the explanatory visual.", locked: false }),
    Object.freeze({ scene: 19, status: "SEMANTIC_REDRAFT_REQUIRED", narration_role: "QUOTATION_BOOKING_TASK_SERVICE_FOLLOW_UP_CONNECTED", semantic_visual: "CUSTOMER_COMMUNICATIONS_CONTINUES_TO_REAL_BUSINESS_OBJECTS", issue: "Current route shows communication UI but does not visibly prove quotation, booking, task, service and follow-up continuity.", locked: false }),
  ]),
  communication_visual_contract: Object.freeze({
    inbound_channel_marks: Object.freeze(["WHATSAPP", "LINE", "MESSENGER", "FACEBOOK", "INSTAGRAM", "GOOGLE_REVIEWS", "EMAIL", "WEBSITE"]),
    campaign_channel_marks: Object.freeze(["FACEBOOK", "INSTAGRAM", "GOOGLE_ADS", "TIKTOK", "YOUTUBE", "LINKEDIN"]),
    authentic_ui_required: true,
    broken_or_generated_text_forbidden: true,
    restaurant_or_kitchen_as_generic_communication_background_forbidden: true,
  }),
});

export default AVANTIQO_INVESTOR_SCENE_5_PLUS_AUDIT_V1;
