import crypto from "node:crypto";
import { createReadStream } from "node:fs";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import sharp from "sharp";

import { supabaseAdmin } from "@/lib/shared/supabase/admin";
import { resolveCreativeFfmpegPath, resolveCreativeFfprobePath } from "@/lib/creative/media/runtime/CreativeMediaBinaryRuntime";

const CONTRACT = "AVANTIQO_INVESTOR_FILM_V10_SYNTHETIC_INTELLIGENCE_FINAL_V3";
const ORG = "33336a72-acb5-474e-856b-8be0269360e2";
const PROJECT = "37ca49f2-210d-4665-af6b-6b5fa834f750";
const BUCKET = "creative-assets";
const FPS = 24;
const PROLOGUE_FRAMES = 192;
const V9_FRAMES = 5700;
const TARGET_FRAMES = 5892;
const TARGET_DURATION = 245.5;
const V9_MASTER_PATH = `${ORG}/${PROJECT}/spatial-master-v9/avantiqo-investor-film-v9-intelligence-237.5s.mp4`;
const CANONICAL_LOGO_PATH = `${ORG}/unassigned/5a068b01-d435-412d-b288-d138c33a7f98-avantiqo-logo.png`;
const OUTPUT_PATH = `${ORG}/${PROJECT}/spatial-master-v10/avantiqo-investor-film-v10-synthetic-intelligence-245.5s.mp4`;
const X264_PARAMS = "threads=1:lookahead_threads=0:sync-lookahead=0:rc-lookahead=0:bframes=0";

function run(command,args,timeoutMs=760000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{shell:false,stdio:["ignore","pipe","pipe"],env:{...process.env,OMP_NUM_THREADS:"1",OPENBLAS_NUM_THREADS:"1",MKL_NUM_THREADS:"1"}});const out=[],err=[];let settled=false;const timer=setTimeout(()=>{child.kill("SIGKILL");if(!settled){settled=true;reject(new Error("INVESTOR_V10_MEDIA_TIMEOUT"));}},timeoutMs);child.stdout.on("data",c=>out.push(c));child.stderr.on("data",c=>err.push(c));child.on("error",e=>{clearTimeout(timer);if(!settled){settled=true;reject(e);}});child.on("close",code=>{clearTimeout(timer);if(settled)return;settled=true;const stdout=Buffer.concat(out).toString("utf8"),stderr=Buffer.concat(err).toString("utf8");if(code!==0)reject(new Error(stderr.slice(-18000)||`MEDIA_EXIT_${code}`));else resolve(stdout);});});}
async function exists(storagePath){const d=storagePath.slice(0,storagePath.lastIndexOf("/")),n=storagePath.slice(storagePath.lastIndexOf("/")+1);const{data,error}=await supabaseAdmin.storage.from(BUCKET).list(d,{search:n,limit:10});if(error)throw error;return(data||[]).some(x=>x.name===n);}
async function signed(storagePath,expires=21600){const{data,error}=await supabaseAdmin.storage.from(BUCKET).createSignedUrl(storagePath,expires);if(error)throw error;if(!data?.signedUrl)throw new Error(`INVESTOR_V10_SIGNED_URL_MISSING:${storagePath}`);return data.signedUrl;}
async function probe(ffprobe,input,timeout=180000){const raw=await run(ffprobe,["-v","error","-count_frames","-show_entries","format=duration:stream=codec_type,codec_name,width,height,r_frame_rate,avg_frame_rate,nb_read_frames,sample_rate,channels","-of","json",input],timeout);return JSON.parse(raw||"{}");}
async function sha256File(localPath){const h=crypto.createHash("sha256");for await(const chunk of createReadStream(localPath,{highWaterMark:1024*1024}))h.update(chunk);return h.digest("hex");}
function env(name){const v=process.env[name];if(!v)throw new Error(`INVESTOR_V10_ENV_MISSING:${name}`);return v;}
async function upload(localPath){const stat=await fs.stat(localPath),checksum=await sha256File(localPath),base=env("NEXT_PUBLIC_SUPABASE_URL").replace(/\/$/,""),key=env("SUPABASE_SERVICE_ROLE_KEY"),encoded=OUTPUT_PATH.split("/").map(encodeURIComponent).join("/");const response=await fetch(`${base}/storage/v1/object/${encodeURIComponent(BUCKET)}/${encoded}`,{method:"POST",headers:{Authorization:`Bearer ${key}`,apikey:key,"Content-Type":"video/mp4","Content-Length":String(stat.size),"Cache-Control":"max-age=3600","x-upsert":"true"},body:createReadStream(localPath,{highWaterMark:1024*1024}),duplex:"half",cache:"no-store"});if(!response.ok)throw new Error(`INVESTOR_V10_UPLOAD_FAILED:${response.status}:${(await response.text().catch(()=>"")).slice(0,1000)}`);return{bytes:stat.size,checksum};}

function fieldSvg(){const nodes=[[220,210],[520,150],[805,250],[1120,160],[1410,250],[1660,190],[355,730],[725,805],[1170,735],[1530,795]];const lines=nodes.map(([x,y],i)=>{const nx=960+Math.cos(i*0.83)*(170+(i%3)*60),ny=540+Math.sin(i*0.71)*(105+(i%2)*85);return`<path d="M${x} ${y} C${(x+nx)/2} ${y},${(x+nx)/2} ${ny},${nx} ${ny}" fill="none" stroke="#dfe4e9" stroke-opacity="0.12" stroke-width="1.2"/>`;}).join("");const dots=nodes.map(([x,y],i)=>`<g transform="translate(${x} ${y})"><circle r="${i%3===0?5:3.5}" fill="#eef2f5" fill-opacity="0.68"/><circle r="19" fill="none" stroke="#eef2f5" stroke-opacity="0.07"/></g>`).join("");return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><defs><radialGradient id="g"><stop offset="0" stop-color="#eef2f6" stop-opacity="0.11"/><stop offset="1" stop-color="#000" stop-opacity="0"/></radialGradient></defs>${lines}${dots}<ellipse cx="960" cy="540" rx="500" ry="295" fill="url(#g)"/></svg>`);}
function coreSvg(){const rings=[90,150,225,315].map((r,i)=>`<ellipse cx="960" cy="540" rx="${r*1.62}" ry="${r}" fill="none" stroke="${i===0?'#ffffff':'#cbd1d7'}" stroke-opacity="${0.30-i*0.05}" stroke-width="${i===0?1.8:1}"/>`).join("");const rays=Array.from({length:24},(_,i)=>{const a=Math.PI*2*i/24,x=960+Math.cos(a)*560,y=540+Math.sin(a)*320;return`<path d="M960 540 C${960+Math.cos(a)*185} ${540+Math.sin(a)*105},${960+Math.cos(a)*355} ${540+Math.sin(a)*205},${x} ${y}" fill="none" stroke="#edf0f3" stroke-opacity="0.10"/>`;}).join("");return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><defs><radialGradient id="c"><stop offset="0" stop-color="#fff" stop-opacity="0.22"/><stop offset="0.35" stop-color="#c8ced4" stop-opacity="0.07"/><stop offset="1" stop-color="#000" stop-opacity="0"/></radialGradient></defs><ellipse cx="960" cy="540" rx="575" ry="340" fill="url(#c)"/>${rays}${rings}<circle cx="960" cy="540" r="8" fill="#eef1f4"/><circle cx="960" cy="540" r="38" fill="none" stroke="#d6a66a" stroke-opacity="0.20"/></svg>`);}
function titleSvg(){const text="SYNTHETIC INTELLIGENCE";const depth=Array.from({length:14},(_,i)=>`<text x="960" y="535" text-anchor="middle" font-family="Helvetica Neue,Arial,sans-serif" font-size="86" font-weight="600" letter-spacing="7" fill="#20252b" fill-opacity="${0.30-i*0.012}" transform="translate(${i*1.35} ${i*1.0})">${text}</text>`).join("");return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><defs><linearGradient id="p" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#ffffff"/><stop offset="0.22" stop-color="#aeb6bf"/><stop offset="0.48" stop-color="#f8f9fa"/><stop offset="0.70" stop-color="#6f7780"/><stop offset="0.90" stop-color="#e8ecef"/><stop offset="1" stop-color="#8a929b"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="7" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect x="535" y="375" width="850" height="325" rx="72" fill="#ffffff" fill-opacity="0.012" stroke="#eef2f5" stroke-opacity="0.045"/>${depth}<text x="960" y="535" text-anchor="middle" font-family="Helvetica Neue,Arial,sans-serif" font-size="86" font-weight="600" letter-spacing="7" fill="url(#p)" filter="url(#glow)">${text}</text><text x="960" y="614" text-anchor="middle" font-family="Helvetica Neue,Arial,sans-serif" font-size="20" font-weight="500" letter-spacing="11" fill="#d9dde1" fill-opacity="0.82">FOR BUSINESS</text><rect x="805" y="657" width="310" height="1" fill="#d6a66a" fill-opacity="0.34"/></svg>`);}
async function png(dir,name,svg){const out=path.join(dir,`${name}.png`);await sharp(svg).png().toFile(out);return out;}

async function renderPrologue(ffmpeg,ffprobe,dir){const[field,core,title,logoUrl]=await Promise.all([png(dir,"field",fieldSvg()),png(dir,"core",coreSvg()),png(dir,"title",titleSvg()),signed(CANONICAL_LOGO_PATH)]);const out=path.join(dir,"prologue.mp4");const filter=`[1:v]format=rgba,fade=t=in:st=0.30:d=1.00:alpha=1,fade=t=out:st=4.60:d=0.80:alpha=1[f];[2:v]format=rgba,fade=t=in:st=1.45:d=0.90:alpha=1,fade=t=out:st=6.35:d=0.70:alpha=1[c];[3:v]format=rgba,fade=t=in:st=4.35:d=0.72:alpha=1,fade=t=out:st=7.05:d=0.42:alpha=1[t];[4:v]format=rgba,scale=340:-1,fade=t=in:st=7.02:d=0.26:alpha=1,fade=t=out:st=7.72:d=0.20:alpha=1[l];[0:v][f]overlay=x='5*sin(t*0.30)':y='3*sin(t*0.21)':enable='between(t,0.25,5.40)'[a];[a][c]overlay=x='2*sin(t*0.20)':y='2*sin(t*0.17)':enable='between(t,1.35,7.00)'[b];[b][t]overlay=x='3*sin(t*0.17)':y='2*sin(t*0.13)':enable='between(t,4.25,7.35)'[d];[d][l]overlay=x='(W-w)/2':y='(H-h)/2':enable='between(t,7.00,7.92)',fade=t=out:st=7.75:d=0.25,format=yuv420p[v];[5:a]volume=0.13,afade=t=in:st=0:d=1.40,afade=t=out:st=7.10:d=0.65[lo];[6:a]volume=0.03,afade=t=in:st=2.00:d=1.20,afade=t=out:st=6.90:d=0.80[hi];[lo][hi]amix=inputs=2:duration=longest,alimiter=limit=0.8[a]`;await run(ffmpeg,["-y","-threads","1","-filter_threads","1","-filter_complex_threads","1","-f","lavfi","-i",`color=c=#020304:s=1920x1080:r=${FPS}:d=8`,"-loop","1","-framerate",String(FPS),"-i",field,"-loop","1","-framerate",String(FPS),"-i",core,"-loop","1","-framerate",String(FPS),"-i",title,"-loop","1","-framerate",String(FPS),"-i",logoUrl,"-f","lavfi","-i","sine=frequency=42:sample_rate=48000:duration=8","-f","lavfi","-i","sine=frequency=96:sample_rate=48000:duration=8","-filter_complex",filter,"-map","[v]","-map","[a]","-c:v","libx264","-threads","1","-x264-params",X264_PARAMS,"-preset","ultrafast","-crf","15","-pix_fmt","yuv420p","-r",String(FPS),"-frames:v",String(PROLOGUE_FRAMES),"-c:a","aac","-b:a","256k","-ar","48000","-ac","2","-t","8","-movflags","+faststart",out],260000);const p=await probe(ffprobe,out,90000),v=(p.streams||[]).find(s=>s.codec_type==="video"),a=(p.streams||[]).find(s=>s.codec_type==="audio");if(!v||!a)throw new Error("INVESTOR_V10_PROLOGUE_AV_REQUIRED");if(Number(v.nb_read_frames||0)!==PROLOGUE_FRAMES)throw new Error(`INVESTOR_V10_PROLOGUE_FRAMES_INVALID:${v.nb_read_frames}`);return out;}
async function validate(ffprobe,file){const m=await probe(ffprobe,file),v=(m.streams||[]).find(s=>s.codec_type==="video"),a=(m.streams||[]).find(s=>s.codec_type==="audio"),frames=Number(v?.nb_read_frames||0),duration=Number(m.format?.duration||0),rate=v?.r_frame_rate||v?.avg_frame_rate;if(!v||!a)throw new Error("INVESTOR_V10_AV_REQUIRED");if(Number(v.width)!==1920||Number(v.height)!==1080)throw new Error(`INVESTOR_V10_DIMENSIONS_INVALID:${v.width}x${v.height}`);if(rate!=="24/1")throw new Error(`INVESTOR_V10_FPS_INVALID:${rate}`);if(frames!==TARGET_FRAMES)throw new Error(`INVESTOR_V10_FRAMES_INVALID:${frames}/${TARGET_FRAMES}`);if(Math.abs(duration-TARGET_DURATION)>0.12)throw new Error(`INVESTOR_V10_DURATION_INVALID:${duration}`);return{width:1920,height:1080,frame_rate:rate,exact_frames:frames,duration_seconds:duration,video_codec:v.codec_name,audio_codec:a.codec_name,sample_rate:Number(a.sample_rate||0),channels:Number(a.channels||0)};}
async function updateProject(state){const{data,error}=await supabaseAdmin.from("creative_projects").select("metadata").eq("id",PROJECT).eq("organization_id",ORG).maybeSingle();if(error)throw error;const{error:u}=await supabaseAdmin.from("creative_projects").update({metadata:{...(data?.metadata||{}),synthetic_intelligence_master_v10:state},updated_at:new Date().toISOString()}).eq("id",PROJECT).eq("organization_id",ORG);if(u)throw u;}

export const AvantiqoInvestorFilmSyntheticIntelligenceV10RuntimeV3=Object.freeze({CONTRACT,OUTPUT_PATH,TARGET_FRAMES,TARGET_DURATION,async status(){return{contract:CONTRACT,output_path:OUTPUT_PATH,final_ready:await exists(OUTPUT_PATH),v9_ready:await exists(V9_MASTER_PATH),canonical_logo_ready:await exists(CANONICAL_LOGO_PATH),exact_frames:TARGET_FRAMES,duration_seconds:TARGET_DURATION,prologue_seconds:8,image_generation_used:false,synthetic_product_ui_used:false,canonical_logo_reinterpreted:false};},async render(){const ffmpeg=resolveCreativeFfmpegPath(),ffprobe=resolveCreativeFfprobePath();if(!ffmpeg||!ffprobe)throw new Error("INVESTOR_V10_MEDIA_BINARY_NOT_READY");if(!(await exists(V9_MASTER_PATH)))throw new Error("INVESTOR_V10_V9_MASTER_NOT_READY");if(!(await exists(CANONICAL_LOGO_PATH)))throw new Error("INVESTOR_V10_CANONICAL_LOGO_NOT_READY");const dir=await fs.mkdtemp(path.join(os.tmpdir(),"avantiqo-v10-final-v3-"));try{const intro=await renderPrologue(ffmpeg,ffprobe,dir),v9=await signed(V9_MASTER_PATH,21600),out=path.join(dir,"v10-final.mp4");const filter=`[0:v]fps=${FPS},trim=end_frame=${PROLOGUE_FRAMES},setpts=PTS-STARTPTS[v0];[0:a]atrim=0:8,asetpts=PTS-STARTPTS,aresample=48000[a0];[1:v]fps=${FPS},trim=end_frame=${V9_FRAMES},setpts=PTS-STARTPTS[v1];[1:a]atrim=0:237.5,asetpts=PTS-STARTPTS,aresample=48000[a1];[v0][a0][v1][a1]concat=n=2:v=1:a=1[v][a]`;await run(ffmpeg,["-y","-threads","1","-filter_threads","1","-filter_complex_threads","1","-i",intro,"-i",v9,"-filter_complex",filter,"-map","[v]","-map","[a]","-c:v","libx264","-threads","1","-x264-params",X264_PARAMS,"-preset","ultrafast","-crf","15","-pix_fmt","yuv420p","-r",String(FPS),"-frames:v",String(TARGET_FRAMES),"-c:a","aac","-b:a","256k","-ar","48000","-ac","2","-t",String(TARGET_DURATION),"-movflags","+faststart",out],760000);const technical_qc=await validate(ffprobe,out),stored=await upload(out),state={contract:CONTRACT,status:"RENDERED_REVIEW_REQUIRED",storage_path:OUTPUT_PATH,checksum:stored.checksum,bytes:stored.bytes,exact_frames:technical_qc.exact_frames,duration_seconds:technical_qc.duration_seconds,frame_rate:technical_qc.frame_rate,prologue_seconds:8,v9_body_seconds:237.5,synthetic_intelligence_title:true,synthetic_intelligence_for_business:true,deterministic_typography:true,platinum_depth_treatment:true,image_generation_used:false,synthetic_product_ui_used:false,canonical_logo_reinterpreted:false,technical_qc,updated_at:new Date().toISOString()};await updateProject(state);return{success:true,...state,signed_url:await signed(OUTPUT_PATH,86400)};}finally{await fs.rm(dir,{recursive:true,force:true}).catch(()=>{});}}});
