import crypto from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import sharp from "sharp";

import { getServiceSupabase } from "@/lib/shared/supabase/service";
import { resolveCreativeFfmpegPath, resolveCreativeFfprobePath } from "@/lib/creative/media/runtime/CreativeMediaBinaryRuntime";

const supabase = getServiceSupabase();
const CONTRACT = "AVANTIQO_INVESTOR_BUSINESS_PARTNER_DIGITAL_TWIN_V1";
const BUCKET = "creative-assets";
const ORG = "33336a72-acb5-474e-856b-8be0269360e2";
const FPS = 24;
const TARGET_FRAMES = 922;
const TARGET_DURATION = TARGET_FRAMES / FPS;
const OUTPUT_PATH = `${ORG}/avantiqo-investor-film-20260821/business-partner-digital-twin-v1-922f.mp4`;
const THREAD_ARGS = ["-threads","1","-filter_threads","1","-filter_complex_threads","1"];

const FOUNDER = `${ORG}/avantiqo-investor-film-20260820/founder-v7`;
const SOURCES = Object.freeze({
  founder: `${FOUNDER}/founder-opening-built-synced-approved-v7.mp4`,
  manager: `${ORG}/unassigned/b1f518b9-e1da-4153-a665-93d1768b42f3-gemini-5sts8qv981mh.mp4`,
  reveal: `${ORG}/unassigned/5a56a041-3f60-47ff-a67b-bb011db8874c-gemini-qwgea6koo5yg.mp4`,
  finance: `${ORG}/unassigned/701a4abb-3ed8-4460-99ef-d388d1ce1ffa-gemini-8yvpgxklek51.mp4`,
  procurement: `${ORG}/unassigned/eef84bd3-c208-4ed8-bba0-6088a9b67ef9-gemini-thgn4qnk6hof.mp4`,
  people: `${ORG}/unassigned/97c0dbc3-5cd0-49f8-8121-1f85831ed2ab-gemini-fpkwe0jb7rex.mp4`,
  restaurant: `${ORG}/unassigned/e1b2c387-2dda-4192-bb7a-3cea339e2293-gemini-32vbfjlubvh7.mp4`,
});

const SCENES = Object.freeze([
  { id:"founder", source:"founder", frames:61, mode:"none" },
  { id:"conversation", source:"manager", frames:130, mode:"conversation", eyebrow:"BUSINESS PARTNER", title:"Talk to the company like you would talk to a person.", subtitle:"One objective becomes a live executive conversation across the business." },
  { id:"context", source:"reveal", frames:160, mode:"context", eyebrow:"LIVE BUSINESS CONTEXT", title:"Avantiqo assembles the operating truth before it answers.", subtitle:"Finance, Operations, Supply Chain, People, Customers and current constraints converge into one reasoning surface." },
  { id:"scenario-growth", source:"restaurant", frames:145, mode:"growth", eyebrow:"DIGITAL TWIN · PATH A", title:"Push demand harder.", subtitle:"More reach and volume — but operational pressure becomes the constraint." },
  { id:"scenario-control", source:"finance", frames:145, mode:"control", eyebrow:"DIGITAL TWIN · PATH B", title:"Grow selectively and protect margin.", subtitle:"Shift timing, audience and product mix so growth fits the company’s real capacity." },
  { id:"recommend", source:"manager", frames:121, mode:"recommend", eyebrow:"RECOMMENDATION", title:"Avantiqo explains the trade-off before asking for authority.", subtitle:"The recommendation is grounded in the business, not isolated model output." },
  { id:"execute", source:"procurement", frames:160, mode:"execute", eyebrow:"GOVERNED EXECUTION", title:"“Do it.” becomes coordinated work across the company.", subtitle:"Marketing, operations, supply, people and finance move together — with evidence and authority attached." },
]);
if (SCENES.reduce((n,s)=>n+s.frames,0)!==TARGET_FRAMES) throw new Error("BUSINESS_PARTNER_TIMELINE_INVALID");

const DOMAINS = ["FINANCE","OPERATIONS","SUPPLY CHAIN","PEOPLE","CUSTOMERS","COMMERCIAL"];
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function run(cmd,args,timeout=330000){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:["ignore","pipe","pipe"],env:{...process.env,OMP_NUM_THREADS:"1"}});const out=[],err=[];const timer=setTimeout(()=>{p.kill("SIGKILL");reject(new Error("BUSINESS_PARTNER_MEDIA_TIMEOUT"));},timeout);p.stdout.on("data",c=>out.push(c));p.stderr.on("data",c=>err.push(c));p.on("error",e=>{clearTimeout(timer);reject(e)});p.on("close",code=>{clearTimeout(timer);if(code)reject(new Error(Buffer.concat(err).toString("utf8").slice(-12000)));else resolve(Buffer.concat(out).toString("utf8"));});});}
async function exists(storagePath){const d=storagePath.split("/").slice(0,-1).join("/");const f=storagePath.split("/").at(-1);const {data,error}=await supabase.storage.from(BUCKET).list(d,{search:f,limit:10});return !error&&(data||[]).some(x=>x.name===f);}
async function signed(storagePath,seconds=7200){const {data,error}=await supabase.storage.from(BUCKET).createSignedUrl(storagePath,seconds);if(error)throw error;if(!data?.signedUrl)throw new Error(`BUSINESS_PARTNER_SIGNED_URL_MISSING:${storagePath}`);return data.signedUrl;}
function defs(){return `<defs><linearGradient id="glass" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#07090c" stop-opacity=".93"/><stop offset="1" stop-color="#17120b" stop-opacity=".78"/></linearGradient><radialGradient id="halo"><stop offset="0" stop-color="#D6A66A" stop-opacity=".22"/><stop offset="1" stop-color="#D6A66A" stop-opacity="0"/></radialGradient></defs>`;}
function header(s){return `<text x="70" y="70" fill="#D6A66A" font-family="Arial" font-size="13" font-weight="700" letter-spacing="2.2">AVANTIQO · ${esc(s.eyebrow)}</text><text x="70" y="120" fill="#F7F4ED" font-family="Arial" font-size="34" font-weight="700">${esc(s.title)}</text><text x="70" y="153" fill="#A5A29B" font-family="Arial" font-size="14">${esc(s.subtitle)}</text><rect x="70" y="177" width="820" height="1" fill="#D6A66A" fill-opacity=".35"/>`;}
function card(x,y,w,h,title,sub,accent="#D6A66A"){return `<g transform="translate(${x} ${y})"><rect width="${w}" height="${h}" rx="16" fill="#fff" fill-opacity=".028" stroke="#fff" stroke-opacity=".08"/><rect width="3" height="${h}" rx="2" fill="${accent}"/><text x="20" y="28" fill="#EEECE6" font-family="Arial" font-size="13" font-weight="700">${esc(title)}</text><text x="20" y="50" fill="#85827B" font-family="Arial" font-size="10">${esc(sub)}</text></g>`;}
function conversation(){return `<g transform="translate(75 218)"><rect width="810" height="106" rx="22" fill="#fff" fill-opacity=".03" stroke="#fff" stroke-opacity=".09"/><text x="28" y="34" fill="#85827B" font-family="Arial" font-size="10" font-weight="700">OWNER · VOICE</text><text x="28" y="70" fill="#FAF7F0" font-family="Arial" font-size="23" font-weight="700">Grow revenue tonight — but don’t reduce margin.</text></g><g transform="translate(175 346)"><rect width="710" height="116" rx="22" fill="#D6A66A" fill-opacity=".07" stroke="#D6A66A" stroke-opacity=".26"/><text x="28" y="34" fill="#D6A66A" font-family="Arial" font-size="10" font-weight="700">AVANTIQO</text><text x="28" y="65" fill="#F2EFE8" font-family="Arial" font-size="17" font-weight="700">I’ll compare growth against capacity, margin and supply.</text><text x="28" y="91" fill="#96938C" font-family="Arial" font-size="12">I can show the aggressive path and the safer path before anything changes.</text></g>`;}
function context(){const cx=480,cy=356;return DOMAINS.map((d,i)=>{const a=Math.PI*2*i/DOMAINS.length-Math.PI/2;const x=cx+Math.cos(a)*310,y=cy+Math.sin(a)*112;return `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#D6A66A" stroke-opacity=".16"/><g transform="translate(${x-72} ${y-18})"><rect width="144" height="36" rx="11" fill="#fff" fill-opacity=".035" stroke="#fff" stroke-opacity=".09"/><text x="72" y="23" text-anchor="middle" fill="#C9C6BE" font-family="Arial" font-size="9.5" font-weight="700">${d}</text></g>`;}).join("")+`<circle cx="480" cy="356" r="76" fill="url(#halo)"/><circle cx="480" cy="356" r="54" fill="#090806" stroke="#D6A66A" stroke-opacity=".55"/><text x="480" y="350" text-anchor="middle" fill="#F7F4ED" font-family="Arial" font-size="17" font-weight="700">AVANTIQO</text><text x="480" y="373" text-anchor="middle" fill="#D6A66A" font-family="Arial" font-size="9" font-weight="700">LIVE OPERATING CONTEXT</text>`;}
function scenario(kind){const growth=kind==="growth";return `<g transform="translate(78 218)"><rect width="804" height="245" rx="24" fill="#fff" fill-opacity=".025" stroke="${growth?'#fff':'#D6A66A'}" stroke-opacity="${growth?'.09':'.28'}"/><text x="34" y="43" fill="${growth?'#A7A49C':'#D6A66A'}" font-family="Arial" font-size="11" font-weight="700">${growth?'PATH A · MAXIMIZE DEMAND':'PATH B · CONTROLLED GROWTH'}</text>${card(34,70,222,66,"DEMAND",growth?"push wider and faster":"target highest-value demand",growth?'#BDB9AF':'#D6A66A')}${card(291,70,222,66,"CAPACITY",growth?"pressure rises at peak":"peak load stays protected",growth?'#BDB9AF':'#D6A66A')}${card(548,70,222,66,"MARGIN",growth?"mix can dilute return":"high-margin mix protected",growth?'#BDB9AF':'#D6A66A')}${card(163,154,222,66,"SUPPLY",growth?"replenishment risk rises":"supply stays inside plan",growth?'#BDB9AF':'#D6A66A')}${card(420,154,222,66,"TEAM",growth?"operational pressure rises":"workload stays balanced",growth?'#BDB9AF':'#D6A66A')}</g>`;}
function recommend(){return `<g transform="translate(74 216)"><rect width="812" height="250" rx="25" fill="#D6A66A" fill-opacity=".055" stroke="#D6A66A" stroke-opacity=".28"/><text x="34" y="42" fill="#D6A66A" font-family="Arial" font-size="10" font-weight="700" letter-spacing="1.7">RECOMMENDED · CONTROLLED GROWTH</text><text x="34" y="82" fill="#F8F4EC" font-family="Arial" font-size="25" font-weight="700">Protect the constraint. Push where the business can absorb it.</text><text x="34" y="116" fill="#9A978F" font-family="Arial" font-size="12">Prioritize high-margin demand before peak capacity, then shift promotion after the operating constraint clears.</text>${card(34,150,220,62,"WHY","margin protected")}${card(286,150,220,62,"WHY NOW","capacity is the constraint")}${card(538,150,220,62,"AUTHORITY","approval required")}</g>`;}
function execute(){const steps=[["COMMERCIAL","campaign adjusted"],["OPERATIONS","capacity plan updated"],["SUPPLY","availability checked"],["PEOPLE","responsibility aligned"],["FINANCE","margin + spend monitored"]];return steps.map((s,i)=>`<g transform="translate(${90+i*158} 238)"><circle cx="58" cy="58" r="54" fill="url(#halo)"/><circle cx="58" cy="58" r="37" fill="#090806" stroke="#D6A66A" stroke-opacity=".48"/><text x="58" y="54" text-anchor="middle" fill="#F4F0E8" font-family="Arial" font-size="9" font-weight="700">${s[0]}</text><text x="58" y="69" text-anchor="middle" fill="#8F8B83" font-family="Arial" font-size="7.5">${s[1]}</text>${i<steps.length-1?`<line x1="112" y1="58" x2="154" y2="58" stroke="#D6A66A" stroke-opacity=".35"/>`:''}</g>`).join("")+`<rect x="168" y="382" width="624" height="72" rx="20" fill="#D6A66A" fill-opacity=".07" stroke="#D6A66A" stroke-opacity=".25"/><text x="480" y="412" text-anchor="middle" fill="#F5F1E9" font-family="Arial" font-size="17" font-weight="700">UNDERSTAND → RECOMMEND → APPROVE → EXECUTE</text><text x="480" y="436" text-anchor="middle" fill="#8F8B83" font-family="Arial" font-size="10">One decision. Coordinated business consequences.</text>`;}
function body(s){if(s.mode==="conversation")return conversation();if(s.mode==="context")return context();if(s.mode==="growth")return scenario("growth");if(s.mode==="control")return scenario("control");if(s.mode==="recommend")return recommend();if(s.mode==="execute")return execute();return "";}
function svg(s){return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540">${defs()}<rect x="18" y="18" width="924" height="504" rx="31" fill="#000" fill-opacity=".42"/><rect x="20" y="20" width="920" height="500" rx="30" fill="url(#glass)" stroke="#D6A66A" stroke-opacity=".38"/>${header(s)}${body(s)}</svg>`);}
async function panel(dir,s){const target=path.join(dir,`panel-${s.id}.rgba`);await fs.writeFile(target,await sharp(svg(s)).ensureAlpha().raw().toBuffer());return target;}
function ease(a,b,x,y){const p=`(t-${a})/(${b}-${a})`,e=`(${p}*${p}*(3-2*${p}))`;return `if(lt(t,${a}),${x},if(lt(t,${b}),${x}+(${y}-${x})*${e},${y}))`;}
async function renderScene(ffmpeg,url,panelRaw,s,out){if(s.mode==="none"){await run(ffmpeg,["-y",...THREAD_ARGS,"-i",url,"-vf",`scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,fps=${FPS},setsar=1`,"-an","-c:v","libx264","-preset","veryfast","-crf","17","-r",String(FPS),"-frames:v",String(s.frames),out]);return;}const duration=s.frames/FPS,rs=.25,re=Math.min(1.2,duration*.28),fo=Math.max(re+.3,duration-.35),w=ease(rs,re,520,1540),h=ease(rs,re,292,866),x=ease(rs,re,1000,190),y=ease(rs,re,640,108);const filter=`[0:v]scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,fps=${FPS},setsar=1,setpts=PTS-STARTPTS,eq=contrast=1.055:saturation=.78:brightness=-.028[base];[base]drawbox=x=0:y=0:w=1920:h=1080:color=black@.16:t=fill[graded];[1:v]setpts=PTS-STARTPTS,format=rgba,fade=t=in:st=${rs}:d=.22:alpha=1,fade=t=out:st=${fo}:d=.28:alpha=1,scale=w='${w}':h='${h}':eval=frame[glass];[graded][glass]overlay=x='${x}':y='${y}':eval=frame:repeatlast=1:shortest=0,format=yuv420p[v]`;await run(ffmpeg,["-y",...THREAD_ARGS,"-stream_loop","-1","-i",url,"-stream_loop","-1","-f","rawvideo","-pixel_format","rgba","-video_size","960x540","-framerate",String(FPS),"-i",panelRaw,"-filter_complex",filter,"-map","[v]","-an","-c:v","libx264","-preset","veryfast","-crf","17","-r",String(FPS),"-frames:v",String(s.frames),out]);}
async function concat(ffmpeg,files,out){const args=["-y",...THREAD_ARGS];files.forEach(f=>args.push("-i",f));const reset=files.map((_,i)=>`[${i}:v]fps=${FPS},setpts=PTS-STARTPTS[v${i}]`).join(";");const ins=files.map((_,i)=>`[v${i}]`).join("");args.push("-filter_complex",`${reset};${ins}concat=n=${files.length}:v=1:a=0,format=yuv420p[v]`,"-map","[v]","-an","-c:v","libx264","-preset","veryfast","-crf","17","-r",String(FPS),"-frames:v",String(TARGET_FRAMES),"-movflags","+faststart",out);await run(ffmpeg,args);}
async function probe(file){const ffprobe=resolveCreativeFfprobePath();if(!ffprobe)throw new Error("BUSINESS_PARTNER_FFPROBE_NOT_READY");const out=await run(ffprobe,["-v","error","-count_frames","-select_streams","v:0","-show_entries","stream=width,height,r_frame_rate,nb_read_frames:format=duration","-of","json",file],90000);return JSON.parse(out||"{}");}
async function upload(storagePath,file){const bytes=await fs.readFile(file);const checksum=crypto.createHash("sha256").update(bytes).digest("hex");const {error}=await supabase.storage.from(BUCKET).upload(storagePath,bytes,{contentType:"video/mp4",upsert:true,cacheControl:"3600",metadata:{contract:CONTRACT,exact_frames:TARGET_FRAMES,fps:FPS,digital_twin:true,business_partner:true}});if(error)throw error;return {path:storagePath,bytes:bytes.length,checksum};}

export const AvantiqoInvestorFilmBusinessPartnerRuntimeV1={
  CONTRACT,BUCKET,ORG,OUTPUT_PATH,FPS,TARGET_FRAMES,TARGET_DURATION,SCENES,
  async status(){const readiness={};for(const [k,v] of Object.entries(SOURCES))readiness[k]=await exists(v);return {contract:CONTRACT,ready:await exists(OUTPUT_PATH),output_path:OUTPUT_PATH,source_readiness:readiness,exact_frames:TARGET_FRAMES,duration_seconds:TARGET_DURATION,policies:{illustrative_scenarios_without_fabricated_metrics:true,preserves_founder_lipsync:true,natural_language_business_partner:true,cross_domain_reasoning:true,governed_execution:true}};},
  async downloadUrl(seconds=86400){return await exists(OUTPUT_PATH)?signed(OUTPUT_PATH,seconds):null;},
  async render(){const ffmpeg=resolveCreativeFfmpegPath();if(!ffmpeg)throw new Error("BUSINESS_PARTNER_FFMPEG_NOT_READY");const dir=await fs.mkdtemp(path.join(os.tmpdir(),"avantiqo-business-partner-v1-"));try{const urls={};for(const [k,v] of Object.entries(SOURCES)){if(!(await exists(v)))throw new Error(`BUSINESS_PARTNER_SOURCE_MISSING:${k}`);urls[k]=await signed(v);}const segments=[];for(let i=0;i<SCENES.length;i++){const s=SCENES[i],out=path.join(dir,`scene-${String(i+1).padStart(2,"0")}-${s.id}.mp4`),p=s.mode==="none"?null:await panel(dir,s);await renderScene(ffmpeg,urls[s.source],p,s,out);segments.push(out);}const final=path.join(dir,"business-partner-v1.mp4");await concat(ffmpeg,segments,final);const media=await probe(final),stream=media?.streams?.[0]||{},frames=Number(stream.nb_read_frames||0),duration=Number(media?.format?.duration||0);if(frames!==TARGET_FRAMES)throw new Error(`BUSINESS_PARTNER_FRAME_COUNT_INVALID:${frames}`);if(Number(stream.width)!==1920||Number(stream.height)!==1080)throw new Error("BUSINESS_PARTNER_DIMENSIONS_INVALID");if(stream.r_frame_rate!=="24/1")throw new Error(`BUSINESS_PARTNER_FPS_INVALID:${stream.r_frame_rate}`);if(Math.abs(duration-TARGET_DURATION)>.08)throw new Error(`BUSINESS_PARTNER_DURATION_INVALID:${duration}`);const stored=await upload(OUTPUT_PATH,final);return {success:true,contract:CONTRACT,output:stored,signed_url:await signed(OUTPUT_PATH,86400),exact_frames:frames,duration_seconds:duration,frame_rate:stream.r_frame_rate,width:Number(stream.width),height:Number(stream.height),digital_twin:true,business_partner:true};}finally{await fs.rm(dir,{recursive:true,force:true}).catch(()=>{});}}
};
