import crypto from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";

import { supabaseAdmin } from "@/lib/shared/supabase/admin";
import { resolveCreativeFfmpegPath, resolveCreativeFfprobePath } from "@/lib/creative/media/runtime/CreativeMediaBinaryRuntime";
import { normalizeCreativeStillImage, creativeRawStillInputArgs } from "@/lib/creative/media/runtime/CreativeStillImageInputRuntime";
import { investorBrandBadge, investorBrandDefs } from "@/lib/investor-film/InvestorBrandMarkRuntime";

const CONTRACT = "AVANTIQO_INVESTOR_V9_SPATIAL_INTELLIGENCE_V4_RAW_RGBA";
const ORG = "33336a72-acb5-474e-856b-8be0269360e2";
const BUCKET = "creative-assets";
const FPS = 24;
const COMMUNICATION_PATH = `${ORG}/avantiqo-investor-film-20260821/communication-intelligence-v3-911f.mp4`;
const STUDIO_PATH = `${ORG}/avantiqo-investor-film-20260821/studio-marketing-cinema-v1-881f.mp4`;
const STUDIO_POSTER_PATH = `${ORG}/campaigns/9f9cdf6f-5a6d-4d3a-8df0-b091ea266ecc/f9a260d4-b83b-4022-8844-9a1aace6c06c-03-churchill.png`;
const STUDIO_VIDEO_PATH = `${ORG}/1460b8b2-ef56-4548-8c58-ded3c0d1bed7/e5e0935c-10b7-4206-9141-dd96c4e742d0/e5e0935c-10b7-4206-9141-dd96c4e742d0.mp4`;

function run(command,args,timeoutMs=650000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{shell:false,stdio:["ignore","pipe","pipe"],env:{...process.env,OMP_NUM_THREADS:"1"}});const out=[],err=[];let settled=false;const timer=setTimeout(()=>{child.kill("SIGKILL");if(!settled){settled=true;reject(new Error("V9_SPATIAL_V4_MEDIA_TIMEOUT"));}},timeoutMs);child.stdout.on("data",c=>out.push(c));child.stderr.on("data",c=>err.push(c));child.on("error",e=>{clearTimeout(timer);if(!settled){settled=true;reject(e);}});child.on("close",code=>{clearTimeout(timer);if(settled)return;settled=true;const stdout=Buffer.concat(out).toString("utf8"),stderr=Buffer.concat(err).toString("utf8");if(code!==0)reject(new Error(stderr.slice(-18000)||`MEDIA_EXIT_${code}`));else resolve(stdout);});});}
async function signed(storagePath,expires=7200){const{data,error}=await supabaseAdmin.storage.from(BUCKET).createSignedUrl(storagePath,expires);if(error)throw error;if(!data?.signedUrl)throw new Error(`V9_SPATIAL_SIGNED_URL_MISSING:${storagePath}`);return data.signedUrl;}
async function download(storagePath){const url=await signed(storagePath);const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error(`V9_SPATIAL_ASSET_DOWNLOAD_FAILED:${storagePath}:${response.status}`);return Buffer.from(await response.arrayBuffer());}
async function upload(storagePath,localPath,metadata){const bytes=await fs.readFile(localPath),checksum=crypto.createHash("sha256").update(bytes).digest("hex");const{error}=await supabaseAdmin.storage.from(BUCKET).upload(storagePath,bytes,{contentType:"video/mp4",upsert:true,cacheControl:"3600",metadata:{...metadata,contract:CONTRACT,checksum,spatial_intelligence:true,generated_ui_used:false,real_creative_assets_used:true,still_image_bridge:"SHARP_RAW_RGBA"}});if(error)throw error;return{bytes:bytes.length,checksum};}
async function rawSvg(dir,name,svg,width,height){return normalizeCreativeStillImage({svg_buffer:svg,output_directory:dir,name,width,height,fit:"fill"});}
async function rawBuffer(dir,name,buffer,width,height,fit="contain"){return normalizeCreativeStillImage({input_buffer:buffer,output_directory:dir,name,width,height,fit,background:{r:0,g:0,b:0,alpha:0}});}
function glassSvg({width,height,label,sublabel}){return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#fff" stop-opacity="0.16"/><stop offset="0.45" stop-color="#adb5bf" stop-opacity="0.05"/><stop offset="1" stop-color="#05070a" stop-opacity="0.30"/></linearGradient><linearGradient id="e"><stop offset="0" stop-color="#fff" stop-opacity="0.55"/><stop offset="0.7" stop-color="#aab2bc" stop-opacity="0.12"/><stop offset="1" stop-color="#d6a66a" stop-opacity="0.34"/></linearGradient></defs><rect x="18" y="18" width="${width-36}" height="${height-36}" rx="28" fill="url(#g)" stroke="url(#e)" stroke-width="1.4"/><path d="M44 31 H${width-130}" stroke="#fff" stroke-opacity="0.22"/><circle cx="${width-55}" cy="48" r="4" fill="#d6a66a"/><text x="48" y="62" fill="#f3f4f5" font-family="Arial" font-size="13" font-weight="700" letter-spacing="1.8">${label}</text><text x="48" y="84" fill="#aab0b7" font-family="Arial" font-size="10.5" letter-spacing="0.8">${sublabel}</text></svg>`);}
function communicationSvg(){const nodes=[["googleReviews",90,118,"CUSTOMER SIGNAL"],["whatsapp",90,228,"CONVERSATION"],["line",90,338,"CONVERSATION"],["messenger",678,118,"CONVERSATION"],["instagram",678,228,"SOCIAL INTENT"],["facebook",678,338,"SOCIAL INTENT"]];const connections=nodes.map(([,x,y])=>{const sx=x<480?x+164:x,sy=y+30;return`<path d="M${sx} ${sy} C${x<480?330:630} ${sy},${x<480?390:570} 270,480 270" fill="none" stroke="#dfe4ea" stroke-opacity="0.22" stroke-width="1.2"/>`;}).join("");const badges=nodes.map(([key,x,y,signal])=>`<g transform="translate(${x} ${y})"><rect width="164" height="60" rx="18" fill="#07090c" fill-opacity="0.58" stroke="#eef2f6" stroke-opacity="0.18"/>${investorBrandBadge(key,{x:12,y:9,width:140,height:42})}<text x="82" y="56" text-anchor="middle" fill="#9fa6ae" font-family="Arial" font-size="7.5" letter-spacing="1">${signal}</text></g>`).join("");return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540"><defs>${investorBrandDefs()}</defs>${connections}${badges}<g transform="translate(370 205)"><rect width="220" height="130" rx="30" fill="#080a0e" fill-opacity="0.50" stroke="#eef3f7" stroke-opacity="0.24"/><rect x="12" y="12" width="196" height="106" rx="22" fill="#fff" fill-opacity="0.025"/><text x="110" y="57" text-anchor="middle" fill="#f3f4f5" font-family="Arial" font-size="13" font-weight="700" letter-spacing="2">AVANTIQO</text><text x="110" y="80" text-anchor="middle" fill="#b7bdc5" font-family="Arial" font-size="9" letter-spacing="1.5">COMMUNICATION INTELLIGENCE</text><circle cx="110" cy="101" r="3.5" fill="#d6a66a"/></g></svg>`);}
function marketingSvg(){const keys=["facebook","instagram","googleAds","tiktok","youtube","linkedin"];return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="960" height="170"><defs>${investorBrandDefs()}</defs>${keys.map((key,i)=>`<g transform="translate(${42+i*150} 52)"><rect width="126" height="58" rx="18" fill="#07090c" fill-opacity="0.58" stroke="#eef2f6" stroke-opacity="0.16"/>${investorBrandBadge(key,{x:6,y:8,width:114,height:42,showStatus:true})}</g>`).join("")}<path d="M86 132 H874" stroke="#dfe4ea" stroke-opacity="0.18"/><circle cx="480" cy="132" r="4" fill="#d6a66a"/><text x="480" y="157" text-anchor="middle" fill="#aeb4bc" font-family="Arial" font-size="9" letter-spacing="1.4">CREATE  ·  PUBLISH  ·  LEARN  ·  ACT</text></svg>`);}
async function probe(ffprobe,url){const raw=await run(ffprobe,["-v","error","-count_frames","-show_entries","stream=codec_type,width,height,r_frame_rate,nb_read_frames","-of","json",url],120000);return JSON.parse(raw||"{}");}
function assertVideo(media,frames,label){const v=(media.streams||[]).find(s=>s.codec_type==="video");if(!v)throw new Error(`${label}_VIDEO_MISSING`);if(Number(v.width)!==1920||Number(v.height)!==1080)throw new Error(`${label}_DIMENSIONS_INVALID:${v.width}x${v.height}`);if((v.r_frame_rate||"")!=="24/1")throw new Error(`${label}_FPS_INVALID:${v.r_frame_rate}`);if(Number(v.nb_read_frames||0)!==frames)throw new Error(`${label}_FRAMES_INVALID:${v.nb_read_frames}/${frames}`);}
async function communication(ffmpeg,ffprobe,dir){const sourceUrl=await signed(COMMUNICATION_PATH),nodes=await rawSvg(dir,"communication-nodes",communicationSvg(),960,540),out=path.join(dir,"communication-v4.mp4");await run(ffmpeg,["-y","-threads","1","-i",sourceUrl,...creativeRawStillInputArgs(nodes,{fps:FPS,loop:true}),"-filter_complex",`[1:v]scale=1500:-1,fade=t=in:st=4.80:d=0.70:alpha=1,fade=t=out:st=29.70:d=0.80:alpha=1[n];[0:v][n]overlay=x='210+8*sin(t*0.45)':y='118+4*sin(t*0.31)':enable='between(t,4.60,30.50)':shortest=0,format=yuv420p[v]`,"-map","[v]","-an","-c:v","libx264","-preset","veryfast","-crf","17","-r",String(FPS),"-frames:v","911","-movflags","+faststart",out]);assertVideo(await probe(ffprobe,out),911,"COMMUNICATION");return{path:COMMUNICATION_PATH,...await upload(COMMUNICATION_PATH,out,{organization_id:ORG,exact_frames:911,fps:FPS,corrected_chapter:"COMMUNICATION_INTELLIGENCE",treatment:"SPATIAL_AUTHENTIC_CHANNEL_NODES"})};}
async function studio(ffmpeg,ffprobe,dir){const[sourceUrl,videoUrl,posterBytes]=await Promise.all([signed(STUDIO_PATH),signed(STUDIO_VIDEO_PATH),download(STUDIO_POSTER_PATH)]);const poster=await rawBuffer(dir,"campaign-poster",posterBytes,382,510,"contain"),posterGlass=await rawSvg(dir,"poster-glass",glassSvg({width:430,height:578,label:"CAMPAIGN DESIGN",sublabel:"REAL CREATIVE STUDIO OUTPUT"}),430,578),videoGlass=await rawSvg(dir,"video-glass",glassSvg({width:720,height:457,label:"CINEMATIC VIDEO",sublabel:"REAL CREATIVE STUDIO OUTPUT"}),720,457),channels=await rawSvg(dir,"marketing-nodes",marketingSvg(),960,170),out=path.join(dir,"studio-v4.mp4");await run(ffmpeg,["-y","-threads","1","-i",sourceUrl,...creativeRawStillInputArgs(poster,{fps:FPS,loop:true}),"-stream_loop","-1","-i",videoUrl,...creativeRawStillInputArgs(posterGlass,{fps:FPS,loop:true}),...creativeRawStillInputArgs(videoGlass,{fps:FPS,loop:true}),...creativeRawStillInputArgs(channels,{fps:FPS,loop:true}),"-filter_complex",`[1:v]format=rgba,fade=t=in:st=7.50:d=0.70:alpha=1,fade=t=out:st=20.80:d=0.70:alpha=1[p];[2:v]scale=650:366:force_original_aspect_ratio=increase,crop=650:366,format=rgba,fade=t=in:st=10.20:d=0.80:alpha=1,fade=t=out:st=27.20:d=0.80:alpha=1[m];[3:v]format=rgba,fade=t=in:st=7.20:d=0.60:alpha=1,fade=t=out:st=21.00:d=0.70:alpha=1[pg];[4:v]format=rgba,fade=t=in:st=9.90:d=0.70:alpha=1,fade=t=out:st=27.50:d=0.80:alpha=1[vg];[5:v]scale=1500:266,format=rgba,fade=t=in:st=21.20:d=0.80:alpha=1,fade=t=out:st=34.50:d=0.80:alpha=1[ch];[0:v][pg]overlay=x='120-14*sin(t*0.34)':y='80+6*sin(t*0.28)':enable='between(t,7.00,21.80)'[a];[a][p]overlay=x='144-14*sin(t*0.34)':y='138+6*sin(t*0.28)':enable='between(t,7.30,21.50)'[b];[b][vg]overlay=x='1030+18*sin(t*0.29)':y='145+7*sin(t*0.23)':enable='between(t,9.70,28.30)'[c];[c][m]overlay=x='1065+18*sin(t*0.29)':y='220+7*sin(t*0.23)':enable='between(t,10.00,28.00)'[d];[d][ch]overlay=x=210:y='780+4*sin(t*0.30)':enable='between(t,21.00,35.30)':shortest=0,format=yuv420p[v]`,"-map","[v]","-an","-c:v","libx264","-preset","veryfast","-crf","17","-r",String(FPS),"-frames:v","881","-movflags","+faststart",out],650000);assertVideo(await probe(ffprobe,out),881,"STUDIO");return{path:STUDIO_PATH,...await upload(STUDIO_PATH,out,{organization_id:ORG,exact_frames:881,fps:FPS,corrected_chapter:"STUDIO_MARKETING",treatment:"REAL_OUTPUT_SPATIAL_GLASS",creative_assets:[STUDIO_POSTER_PATH,STUDIO_VIDEO_PATH]})};}

export const AvantiqoInvestorFilmSpatialIntelligenceRuntimeV4=Object.freeze({CONTRACT,async render(){const ffmpeg=resolveCreativeFfmpegPath(),ffprobe=resolveCreativeFfprobePath();if(!ffmpeg||!ffprobe)throw new Error("V9_SPATIAL_V4_MEDIA_BINARY_NOT_READY");const dir=await fs.mkdtemp(path.join(os.tmpdir(),"avantiqo-v9-spatial-v4-"));try{const communication_result=await communication(ffmpeg,ffprobe,dir),studio_result=await studio(ffmpeg,ffprobe,dir);return{success:true,contract:CONTRACT,communication:communication_result,studio:studio_result,image_generation_used:false,synthetic_product_ui_used:false,still_image_bridge:"SHARP_RAW_RGBA",qc:{communication_frames:911,studio_frames:881,width:1920,height:1080,fps:24}};}finally{await fs.rm(dir,{recursive:true,force:true}).catch(()=>{});}}});
