import crypto from "node:crypto";
import { createReadStream } from "node:fs";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import sharp from "sharp";

import { supabaseAdmin } from "@/lib/shared/supabase/admin";
import { resolveCreativeFfmpegPath, resolveCreativeFfprobePath } from "@/lib/creative/media/runtime/CreativeMediaBinaryRuntime";

const CONTRACT = "AVANTIQO_INVESTOR_FILM_V10_SYNTHETIC_INTELLIGENCE_FINAL_V3";
const ORG = "33336a72-acb5-474e-856b-8be0269360e2";
const PROJECT = "37ca49f2-210d-4665-af6b-6b5fa834f750";
const BUCKET = "creative-assets";
const FPS = 24;
const PROLOGUE_FRAMES = 192;
const V9_FRAMES = 5700;
const TARGET_FRAMES = 5892;
const TARGET_DURATION = 245.5;
const V9_MASTER_PATH = `${ORG}/${PROJECT}/spatial-master-v9/avantiqo-investor-film-v9-intelligence-237.5s.mp4`;
const OUTPUT_PATH = `${ORG}/${PROJECT}/spatial-master-v10/avantiqo-investor-film-v10-synthetic-intelligence-245.5s.mp4`;
const X264_PARAMS = "threads=1:lookahead_threads=0:sync-lookahead=0:rc-lookahead=0:bframes=0";

function run(command,args,timeoutMs=760000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{shell:false,stdio:["ignore","pipe","pipe"],env:{...process.env,OMP_NUM_THREADS:"1",OPENBLAS_NUM_THREADS:"1",MKL_NUM_THREADS:"1"}});const out=[],err=[];let settled=false;const timer=setTimeout(()=>{child.kill("SIGKILL");if(!settled){settled=true;reject(new Error("INVESTOR_V10_MEDIA_TIMEOUT"));}},timeoutMs);child.stdout.on("data",c=>out.push(c));child.stderr.on("data",c=>err.push(c));child.on("error",e=>{clearTimeout(timer);if(!settled){settled=true;reject(e);}});child.on("close",code=>{clearTimeout(timer);if(settled)return;settled=true;const stdout=Buffer.concat(out).toString("utf8");const stderr=Buffer.concat(err).toString("utf8");if(code!==0)reject(new Error(stderr.slice(-18000)||`MEDIA_EXIT_${code}`));else resolve(stdout);});});}
async function exists(storagePath){const d=storagePath.slice(0,storagePath.lastIndexOf("/")),n=storagePath.slice(storagePath.lastIndexOf("/")+1);const{data,error}=await supabaseAdmin.storage.from(BUCKET).list(d,{search:n,limit:10});if(error)throw error;return(data||[]).some(x=>x.name===n);}
async function signed(storagePath,expires=21600){const{data,error}=await supabaseAdmin.storage.from(BUCKET).createSignedUrl(storagePath,expires);if(error)throw error;if(!data?.signedUrl)throw new Error(`INVESTOR_V10_SIGNED_URL_MISSING:${storagePath}`);return data.signedUrl;}
async function probe(ffprobe,input,timeout=180000){const raw=await run(ffprobe,["-v","error","-count_frames","-show_entries","format=duration:stream=codec_type,codec_name,width,height,r_frame_rate,avg_frame_rate,nb_read_frames,sample_rate,channels","-of","json",input],timeout);return JSON.parse(raw||"{}");}
async function sha256File(localPath){const h=crypto.createHash("sha256");for await(const chunk of createReadStream(localPath,{highWaterMark:1024*1024}))h.update(chunk);return h.digest("hex");}
function env(name){const v=process.env[name];if(!v)throw new Error(`INVESTOR_V10_ENV_MISSING:${name}`);return v;}
async function upload(localPath){const stat=await fs.stat(localPath),checksum=await sha256File(localPath),base=env("NEXT_PUBLIC_SUPABASE_URL").replace(/\/$/,""),key=env("SUPABASE_SERVICE_ROLE_KEY"),encoded=OUTPUT_PATH.split("/").map(encodeURIComponent).join("/");const response=await fetch(`${base}/storage/v1/object/${encodeURIComponent(BUCKET)}/${encoded}`,{method:"POST",headers:{Authorization:`Bearer ${key}`,apikey:key,"Content-Type":"video/mp4","Content-Length":String(stat.size),"Cache-Control":"max-age=3600","x-upsert":"true"},body:createReadStream(localPath,{highWaterMark:1024*1024}),duplex:"half",cache:"no-store"});if(!response.ok)throw new Error(`INVESTOR_V10_UPLOAD_FAILED:${response.status}:${(await response.text().catch(()=>"" )).slice(0,1000)}`);return{bytes:stat.size,checksum};}

function signals(){const nodes=[[210,215,"TRANSACTION"],[480,145,"CUSTOMER"],[770,235,"INVENTORY"],[1080,145,"PEOPLE"],[1375,245,"OPERATIONS"],[1660,175,"MARKETING"],[340,710,"SUPPLY"],[720,790,"CASH"],[1165,720,"SERVICE"],[1540,780,"DECISION"]];const lines=nodes.map(([x,y],i)=>{const nx=960+Math.cos(i*.83)*(170+(i%3)*62),ny=540+Math.sin(i*.71)*(105+(i%2)*85);return`<path d="M${x} ${y} C${(x+nx)/2} ${y}, ${(x+nx)/2} ${ny}, ${nx} ${ny}" fill="none" stroke="#dce2e7" stroke-opacity="0.105" stroke-width="1.2"/>`;}).join("");const dots=nodes.map(([x,y,l],i)=>`<g transform="translate(${x} ${y})"><circle r="${i%3===0?5:3.5}" fill="#eef2f6" fill-opacity="0.66"/><circle r="20" fill="none" stroke="#eef2f6" stroke-opacity="0.065"/><text x="15" y="4" fill="#bdc4cb" fill-opacity="0.42" font-family="Arial,sans-serif" font-size="10" letter-spacing="2">${l}</text></g>`).join("");return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><defs><radialGradient id="g"><stop offset="0" stop-color="#eef2f6" stop-opacity="0.10"/><stop offset="1" stop-color="#000" stop-opacity="0"/></radialGradient></defs>${lines}${dots}<ellipse cx="960" cy="540" rx="430" ry="265" fill="url(#g)"/></svg>`);}
function network(){const rings=[80,138,208,302].map((r,i)=>`<ellipse cx="960" cy="540" rx="${r*1.58}" ry="${r}" fill="none" stroke="${i===0?'#ffffff':'#cbd1d7'}" stroke-opacity="${0.28-i*0.045}" stroke-width="${i===0?1.7:1}"/>`).join("");const spokes=Array.from({length:20},(_,i)=>{const a=Math.PI*2*i/20,x=960+Math.cos(a)*535,y=540+Math.sin(a)*305;return`<path d="M960 540 C${960+Math.cos(a)*170} ${540+Math.sin(a)*95},${960+Math.cos(a)*340} ${540+Math.sin(a)*190},${x} ${y}" fill="none" stroke="#e8ecef" stroke-opacity="0.095"/>`;}).join("");return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><defs><radialGradient id="c"><stop offset="0" stop-color="#fff" stop-opacity="0.18"/><stop offset="0.35" stop-color="#bac1c8" stop-opacity="0.055"/><stop offset="1" stop-color="#000" stop-opacity="0"/></radialGradient></defs><ellipse cx="960" cy="540" rx="550" ry="325" fill="url(#c)"/>${spokes}${rings}<circle cx="960" cy="540" r="7" fill="#e8ecef"/><circle cx="960" cy="540" r="35" fill="none" stroke="#d6a66a" stroke-opacity="0.16"/></svg>`);}
function title(){const text="SYNTHETIC INTELLIGENCE";const cuts=Array.from({length:15},(_,i)=>`<rect x="${520+i*64}" y="432" width="14" height="160" transform="skewX(-18)" fill="black" fill-opacity="${i%2===0?0.15:0.08}"/>`).join("");const depth=Array.from({length:6},(_,i)=>`<text x="960" y="545" text-anchor="middle" font-family="Arial,sans-serif" font-size="82" font-weight="700" letter-spacing="8.5" transform="translate(${i*1.5} ${i*1.1}) scale(1.04 1) skewX(-4)" fill="#252a30" fill-opacity="0.22">${text}</text>`).join("");return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><defs><linearGradient id="p" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffffff"/><stop offset="0.24" stop-color="#cfd4da"/><stop offset="0.52" stop-color="#7d858e"/><stop offset="0.77" stop-color="#f3f5f6"/><stop offset="1" stop-color="#777f88"/></linearGradient><mask id="engineered"><rect width="1920" height="1080" fill="white"/>${cuts}</mask></defs><path d="M660 446 L708 446 L690 466 L672 466 Z M1250 446 L1298 446 L1280 466 L1262 466 Z" fill="#d6a66a" fill-opacity="0.34"/>${depth}<g mask="url(#engineered)" transform="translate(-38 0)"><text x="960" y="545" text-anchor="middle" font-family="Arial,sans-serif" font-size="82" font-weight="700" letter-spacing="8.5" transform="scale(1.04 1) skewX(-4)" fill="url(#p)">${text}</text></g><text x="960" y="613" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" font-weight="600" letter-spacing="11" fill="#d9dde1" fill-opacity="0.72">FOR BUSINESS</text><rect x="824" y="655" width="272" height="1" fill="#d6a66a" fill-opacity="0.25"/></svg>`);}
async function png(dir,name,svg){const out=path.join(dir,`${name}.png`);await sharp(svg).png().toFile(out);return out;}

async function prologue(ffmpeg,ffprobe,dir){const[signalPath,networkPath,titlePath]=await Promise.all([png(dir,"signals",signals()),png(dir,"network",network()),png(dir,"title",title())]),out=path.join(dir,"prologue.mp4");const filter=`[1:v]format=rgba,fade=t=in:st=0.30:d=0.95:alpha=1,fade=t=out:st=4.70:d=0.80:alpha=1[s];[2:v]format=rgba,fade=t=in:st=1.60:d=0.85:alpha=1,fade=t=out:st=6.55:d=0.65:alpha=1[n];[3:v]format=rgba,fade=t=in:st=4.25:d=0.70:alpha=1,fade=t=out:st=7.35:d=0.45:alpha=1[t];[0:v][s]overlay=x='4*sin(t*.30)':y='3*sin(t*.21)':enable='between(t,0.20,5.55)'[a];[a][n]overlay=x='2*sin(t*.20)':y='2*sin(t*.17)':enable='between(t,1.50,7.30)'[b];[b][t]overlay=0:0:enable='between(t,4.15,7.78)',fade=t=out:st=7.72:d=0.28,format=yuv420p[v];[4:a]volume=0.12,afade=t=in:st=0:d=1.35,afade=t=out:st=7.00:d=0.70[lo];[5:a]volume=0.028,afade=t=in:st=2.00:d=1.15,afade=t=out:st=6.85:d=0.75[hi];[lo][hi]amix=inputs=2:duration=longest,alimiter=limit=0.8[a]`;await run(ffmpeg,["-y","-threads","1","-filter_threads","1","-filter_complex_threads","1","-f","lavfi","-i",`color=c=#020304:s=1920x1080:r=${FPS}:d=8`,"-loop","1","-framerate",String(FPS),"-i",signalPath,"-loop","1","-framerate",String(FPS),"-i",networkPath,"-loop","1","-framerate",String(FPS),"-i",titlePath,"-f","lavfi","-i","sine=frequency=42:sample_rate=48000:duration=8","-f","lavfi","-i","sine=frequency=96:sample_rate=48000:duration=8","-filter_complex",filter,"-map","[v]","-map","[a]","-c:v","libx264","-threads","1","-x264-params",X264_PARAMS,"-preset","ultrafast","-crf","16","-pix_fmt","yuv420p","-r",String(FPS),"-frames:v",String(PROLOGUE_FRAMES),"-c:a","aac","-b:a","256k","-ar","48000","-ac","2","-t","8","-movflags","+faststart",out],260000);const media=await probe(ffprobe,out,90000),video=(media.streams||[]).find(s=>s.codec_type==="video");if(Number(video?.nb_read_frames||0)!==PROLOGUE_FRAMES)throw new Error(`INVESTOR_V10_PROLOGUE_FRAMES_INVALID:${video?.nb_read_frames}`);return out;}
async function validate(ffprobe,file){const m=await probe(ffprobe,file),v=(m.streams||[]).find(s=>s.codec_type==="video"),a=(m.streams||[]).find(s=>s.codec_type==="audio"),frames=Number(v?.nb_read_frames||0),duration=Number(m.format?.duration||0),rate=v?.r_frame_rate||v?.avg_frame_rate;if(!v||!a)throw new Error("INVESTOR_V10_AV_REQUIRED");if(Number(v.width)!==1920||Number(v.height)!==1080)throw new Error(`INVESTOR_V10_DIMENSIONS_INVALID:${v.width}x${v.height}`);if(rate!=="24/1")throw new Error(`INVESTOR_V10_FPS_INVALID:${rate}`);if(frames!==TARGET_FRAMES)throw new Error(`INVESTOR_V10_FRAMES_INVALID:${frames}/${TARGET_FRAMES}`);if(Math.abs(duration-TARGET_DURATION)>0.12)throw new Error(`INVESTOR_V10_DURATION_INVALID:${duration}`);return{width:1920,height:1080,frame_rate:rate,exact_frames:frames,duration_seconds:duration,video_codec:v.codec_name,audio_codec:a.codec_name,sample_rate:Number(a.sample_rate||0),channels:Number(a.channels||0)};}
async function updateProject(state){const{data,error}=await supabaseAdmin.from("creative_projects").select("metadata").eq("id",PROJECT).eq("organization_id",ORG).maybeSingle();if(error)throw error;const{error:u}=await supabaseAdmin.from("creative_projects").update({metadata:{...(data?.metadata||{}),synthetic_intelligence_master_v10:state},updated_at:new Date().toISOString()}).eq("id",PROJECT).eq("organization_id",ORG);if(u)throw u;}

export const AvantiqoInvestorFilmSyntheticIntelligenceV10RuntimeV2=Object.freeze({CONTRACT,OUTPUT_PATH,TARGET_FRAMES,TARGET_DURATION,async status(){return{contract:CONTRACT,output_path:OUTPUT_PATH,final_ready:await exists(OUTPUT_PATH),v9_ready:await exists(V9_MASTER_PATH),exact_frames:TARGET_FRAMES,duration_seconds:TARGET_DURATION,prologue_seconds:8,approved_logo_film_seconds:8,sequence:["SYNTHETIC_INTELLIGENCE_8S","APPROVED_AVANTIQO_LOGO_FILM_8S","INVESTOR_FILM_BODY"],prologue_logo_visible:false,image_generation_used:false,synthetic_product_ui_used:false};},async render(){const ffmpeg=resolveCreativeFfmpegPath(),ffprobe=resolveCreativeFfprobePath();if(!ffmpeg||!ffprobe)throw new Error("INVESTOR_V10_MEDIA_BINARY_NOT_READY");if(!(await exists(V9_MASTER_PATH)))throw new Error("INVESTOR_V10_V9_MASTER_NOT_READY");const dir=await fs.mkdtemp(path.join(os.tmpdir(),"avantiqo-v10-final-v3-"));try{const intro=await prologue(ffmpeg,ffprobe,dir),v9=await signed(V9_MASTER_PATH,21600),out=path.join(dir,"v10-final.mp4");await run(ffmpeg,["-y","-threads","1","-filter_threads","1","-filter_complex_threads","1","-i",intro,"-i",v9,"-filter_complex",`[0:v]fps=${FPS},trim=end_frame=${PROLOGUE_FRAMES},setpts=PTS-STARTPTS[v0];[0:a]atrim=0:8,asetpts=PTS-STARTPTS,aresample=48000[a0];[1:v]fps=${FPS},trim=end_frame=${V9_FRAMES},setpts=PTS-STARTPTS[v1];[1:a]atrim=0:237.5,asetpts=PTS-STARTPTS,aresample=48000[a1];[v0][a0][v1][a1]concat=n=2:v=1:a=1[v][a]`,"-map","[v]","-map","[a]","-c:v","libx264","-threads","1","-x264-params",X264_PARAMS,"-preset","ultrafast","-crf","15","-pix_fmt","yuv420p","-r",String(FPS),"-frames:v",String(TARGET_FRAMES),"-c:a","aac","-b:a","256k","-ar","48000","-ac","2","-t",String(TARGET_DURATION),"-movflags","+faststart",out],760000);const technical_qc=await validate(ffprobe,out),stored=await upload(out),state={contract:CONTRACT,status:"RENDERED_REVIEW_REQUIRED",storage_path:OUTPUT_PATH,checksum:stored.checksum,bytes:stored.bytes,exact_frames:technical_qc.exact_frames,duration_seconds:technical_qc.duration_seconds,frame_rate:technical_qc.frame_rate,sequence:["SYNTHETIC_INTELLIGENCE_8S","APPROVED_AVANTIQO_LOGO_FILM_8S","INVESTOR_FILM_BODY"],prologue_seconds:8,approved_logo_film_seconds:8,v9_body_seconds:237.5,synthetic_intelligence_title:true,synthetic_intelligence_for_business:true,brand_geometric_typography:true,deterministic_typography:true,prologue_logo_visible:false,image_generation_used:false,synthetic_product_ui_used:false,technical_qc,updated_at:new Date().toISOString()};await updateProject(state);return{success:true,...state,signed_url:await signed(OUTPUT_PATH,86400)};}finally{await fs.rm(dir,{recursive:true,force:true}).catch(()=>{});}}});
