import crypto from "node:crypto";

export const AVANTIQO_ROTO_MATTE_AUTHORITY_CONTRACT="AVANTIQO_ROTO_MATTE_AUTHORITY_V1";
function text(v){return String(v??"").trim();}
function list(v){return Array.isArray(v)?v.filter(Boolean):[];}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");}
export function authorRotoMatte({subject_id,seed_matte_asset_node_id,tracking_asset_node_id,temporal_propagation=true,edge_refinement=true,motion_blur_matte=true,hair_fine_detail=false,transparency_mode="OPAQUE_SUBJECT",garbage_mattes=[],holdout_mattes=[]}={}){
  const blockers=[];if(!text(subject_id))blockers.push("ROTO_SUBJECT_REQUIRED");if(!text(seed_matte_asset_node_id))blockers.push("ROTO_SEED_MATTE_REQUIRED");if(!text(tracking_asset_node_id))blockers.push("ROTO_TRACKING_AUTHORITY_REQUIRED");if(temporal_propagation!==true)blockers.push("ROTO_TEMPORAL_PROPAGATION_REQUIRED");if(edge_refinement!==true)blockers.push("ROTO_EDGE_REFINEMENT_REQUIRED");if(motion_blur_matte!==true)blockers.push("ROTO_MOTION_BLUR_MATTE_REQUIRED");const body={contract:AVANTIQO_ROTO_MATTE_AUTHORITY_CONTRACT,subject_id:text(subject_id),seed_matte_asset_node_id:text(seed_matte_asset_node_id)||null,tracking_asset_node_id:text(tracking_asset_node_id)||null,temporal_propagation:temporal_propagation===true,edge_refinement:edge_refinement===true,motion_blur_matte:motion_blur_matte===true,hair_fine_detail:hair_fine_detail===true,transparency_mode:text(transparency_mode).toUpperCase(),garbage_mattes:list(garbage_mattes),holdout_mattes:list(holdout_mattes),qc:{temporal_chatter_forbidden:true,alpha_halo_forbidden:true,edge_boiling_forbidden:true,foreground_spill_forbidden:true,motion_blur_edge_required:true,transparent_glass_requires_specialized_matte:true,hair_detail_requires_fine_detail_mode:true}};return{...body,status:blockers.length?"BLOCKED":"READY",blockers,contract_hash:hash(body)};
}
export const CreativeRotoMatteAuthorityRuntime=Object.freeze({contract:AVANTIQO_ROTO_MATTE_AUTHORITY_CONTRACT,author:authorRotoMatte});
