import crypto from "node:crypto";

export const AVANTIQO_MECHANICAL_RIG_CONTRACT="AVANTIQO_MECHANICAL_RIG_V1";
const KINDS=new Set(["GENERIC_TRANSFORM","WHEEL_ROTATION","SUSPENSION","HINGE","CAMERA_PATH"]);
function text(v){return String(v??"").trim();}
function list(v){return Array.isArray(v)?v.filter(Boolean):[];}
function finite(v,f=0,min=-Infinity,max=Infinity){const n=Number(v);return Math.max(min,Math.min(max,Number.isFinite(n)?n:f));}
function vec(v,f=[0,0,0]){return Array.isArray(v)&&v.length>=3?v.slice(0,3).map((x,i)=>finite(x,f[i])):f;}
function stable(v){if(Array.isArray(v))return v.map(stable);if(!v||typeof v!=="object")return v;return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");}
function axisVector(axis="X"){const a=text(axis).toUpperCase();return a==="Y"?[0,1,0]:a==="Z"?[0,0,1]:[1,0,0];}
function addVec(a,b){return a.map((x,i)=>x+b[i]);}
function mulVec(a,s){return a.map(x=>x*s);}
function compileRig(rig,objectById){const kind=text(rig.kind).toUpperCase();if(!KINDS.has(kind))throw new Error(`MECHANICAL_RIG_KIND_UNSUPPORTED:${kind}`);const frameStart=Math.max(1,Math.round(finite(rig.frame_start,1)));const frameEnd=Math.max(frameStart+1,Math.round(finite(rig.frame_end,frameStart+24)));if(kind==="CAMERA_PATH"){const points=list(rig.points).map((p,i)=>({frame:Math.max(1,Math.round(finite(p.frame,frameStart+i))),location:vec(p.location),rotation:p.rotation?vec(p.rotation):null,lens:p.lens==null?null:finite(p.lens,50,8,300)}));if(points.length<2)throw new Error("CAMERA_PATH_POINTS_REQUIRED");return{kind,target_object_id:null,camera_keyframes:points};}
  const target=text(rig.target_object_id);const object=objectById.get(target);if(!object)throw new Error(`MECHANICAL_RIG_TARGET_REQUIRED:${target}`);const baseLocation=vec(object.location);const baseRotation=vec(object.rotation);const baseScale=vec(object.scale,[1,1,1]);
  if(kind==="GENERIC_TRANSFORM"){const keyframes=list(rig.keyframes).map(k=>({frame:Math.max(1,Math.round(finite(k.frame,1))),location:k.location?vec(k.location):null,rotation:k.rotation?vec(k.rotation):null,scale:k.scale?vec(k.scale,[1,1,1]):null}));if(!keyframes.length)throw new Error(`MECHANICAL_GENERIC_KEYFRAMES_REQUIRED:${target}`);return{kind,target_object_id:target,keyframes};}
  if(kind==="WHEEL_ROTATION"){const radius=finite(rig.radius_m,.35,.001,10);const travel=finite(rig.travel_meters,0,-10000,10000);const degrees=travel/radius*180/Math.PI;const axis=axisVector(rig.axis||"X");return{kind,target_object_id:target,keyframes:[{frame:frameStart,location:baseLocation,rotation:baseRotation,scale:baseScale},{frame:frameEnd,location:baseLocation,rotation:addVec(baseRotation,mulVec(axis,degrees)),scale:baseScale}],derived:{radius_m:radius,travel_meters:travel,rotation_degrees:degrees}};}
  if(kind==="SUSPENSION"){const axis=axisVector(rig.axis||"Z");const compression=finite(rig.compression_m,0,-2,2);return{kind,target_object_id:target,keyframes:[{frame:frameStart,location:baseLocation,rotation:baseRotation,scale:baseScale},{frame:frameEnd,location:addVec(baseLocation,mulVec(axis,-compression)),rotation:baseRotation,scale:baseScale}],derived:{compression_m:compression}};}
  if(kind==="HINGE"){const axis=axisVector(rig.axis||"Z");const angle=finite(rig.angle_degrees,0,-360,360);return{kind,target_object_id:target,keyframes:[{frame:frameStart,location:baseLocation,rotation:baseRotation,scale:baseScale},{frame:frameEnd,location:baseLocation,rotation:addVec(baseRotation,mulVec(axis,angle)),scale:baseScale}],derived:{angle_degrees:angle}};}
}
export function compileMechanicalRigs({objects=[],rigs=[]}={}){const normalizedObjects=list(objects).map(o=>({...o,animation_keyframes:list(o.animation_keyframes)}));const byId=new Map(normalizedObjects.map(o=>[text(o.object_id),o]));const compiled=list(rigs).map(r=>compileRig(r,byId));let camera_keyframes=[];for(const rig of compiled){if(rig.kind==="CAMERA_PATH"){camera_keyframes=rig.camera_keyframes;continue;}const target=byId.get(rig.target_object_id);target.animation_keyframes=[...list(target.animation_keyframes),...list(rig.keyframes)].sort((a,b)=>a.frame-b.frame);}const body={contract:AVANTIQO_MECHANICAL_RIG_CONTRACT,objects:normalizedObjects,camera_keyframes,compiled_rigs:compiled,policy:{physical_units_meters:true,frame_deterministic:true,wheel_rotation_derived_from_travel:true,rig_target_required:true}};return{...body,rig_hash:hash(body)};}
export const CreativeMechanicalRigRuntime=Object.freeze({contract:AVANTIQO_MECHANICAL_RIG_CONTRACT,kinds:Object.freeze([...KINDS]),compile:compileMechanicalRigs});
