"use client";
import { Eye,EyeOff,Lock,LockOpen,Type,Image as ImageIcon,ChevronUp,ChevronDown,FolderTree,SlidersHorizontal,Scan } from "lucide-react";

export default function ImageStudioLayerPanel({workspace}){
 const board=workspace.selection.artboard_id;
 const layers=workspace.layers.filter(x=>x.artboard_id===board).sort((a,b)=>b.sort_order-a.sort_order);
 const childCount=new Map();
 for(const layer of layers){if(layer.parent_layer_id)childCount.set(layer.parent_layer_id,(childCount.get(layer.parent_layer_id)||0)+1);}
 const select=(event,layer)=>{const additive=event.shiftKey||event.metaKey||event.ctrlKey;workspace.selectLayerOrGroup(layer.id,additive);};
 return <div className="mt-5"><div className="mb-2 flex items-center justify-between"><div className="text-[9px] font-semibold uppercase tracking-[0.22em] text-[#948D84]">Layers</div>{workspace.selection.layer_ids.length>1?<div className="rounded-full border border-[#DDD8D0] bg-[#FBFAF8] px-2 py-0.5 text-[8px] text-[#817A72]">{workspace.selection.layer_ids.length} selected</div>:null}</div><div className="space-y-1">{layers.map(layer=>{const active=workspace.selection.layer_ids.includes(layer.id);const nested=Boolean(layer.parent_layer_id);const children=childCount.get(layer.id)||0;return <div key={layer.id} className={`flex items-center gap-2 rounded-lg border px-2 py-2 ${active?"border-[#D6A66A]/30 bg-[#D6A66A]/[0.05]":"border-[#E7E3DD]"}`} style={{marginLeft:nested?12:0}}><button className="flex min-w-0 flex-1 items-center gap-2 text-left" onClick={event=>select(event,layer)} title="Click to select. Shift/Cmd/Ctrl-click to add or remove from selection.">{nested||children?<FolderTree className="h-3 w-3 text-[#D6A66A]/70"/>:layer.layer_type==="TEXT"?<Type className="h-3 w-3"/>:layer.layer_type==="ADJUSTMENT"?<SlidersHorizontal className="h-3 w-3 text-[#D6A66A]/80"/>:layer.layer_type==="MASK"?<Scan className="h-3 w-3 text-[#D6A66A]/80"/>:<ImageIcon className="h-3 w-3"/>}<span className="truncate text-[9px] text-[#665F57]">{layer.name}</span>{children?<span className="ml-auto text-[7px] text-[#A09A92]">{children}</span>:null}</button><button title="Visibility" onClick={()=>workspace.updateLayerLocal(layer.id,{visible:!layer.visible})}>{layer.visible?<Eye className="h-3 w-3 text-[#8A837A]"/>:<EyeOff className="h-3 w-3 text-[#AAA49C]"/>}</button><button title="Lock" onClick={()=>workspace.updateLayerLocal(layer.id,{locked:!layer.locked})}>{layer.locked?<Lock className="h-3 w-3 text-[#D6A66A]/70"/>:<LockOpen className="h-3 w-3 text-[#99928A]"/>}</button><button title="Forward" onClick={()=>workspace.reorderLayer(layer.id,1)}><ChevronUp className="h-3 w-3 text-[#99928A]"/></button><button title="Back" onClick={()=>workspace.reorderLayer(layer.id,-1)}><ChevronDown className="h-3 w-3 text-[#99928A]"/></button></div>})}{!layers.length?<div className="rounded-lg border border-dashed border-[#DDD8D0] p-3 text-[9px] text-[#99928A]">No editable layers yet.</div>:null}</div></div>;
}
