"use client";

function Field({label,value,onChange,onFocus,onBlur,type="number",step="1"}) {
  return <label className="block"><span className="text-[8px] uppercase tracking-[.14em] text-[#99928A]">{label}</span><input type={type} step={step} value={value??""} onFocus={onFocus} onBlur={onBlur} onChange={e=>onChange(type==="number"?Number(e.target.value):e.target.value)} className="mt-1 w-full rounded-md border border-[#DDD8D0] bg-[#FBFAF8] px-2 py-1.5 text-[10px] text-[#5E5952] outline-none focus:border-[#D6A66A]/40"/></label>;
}
function SelectField({label,value,onChange,options}) {
  return <label className="block"><span className="text-[8px] uppercase tracking-[.14em] text-[#99928A]">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-md border border-[#DDD8D0] bg-[#FBFAF8] px-2 py-1.5 text-[10px] text-[#5E5952] outline-none focus:border-[#D6A66A]/40">{options.map(item=><option key={item} value={item}>{item}</option>)}</select></label>;
}

export default function ImageStudioLayerInspector({workspace}) {
  const selectedIds=workspace.selection.layer_ids||[];
  const id=selectedIds[0]; const layer=workspace.layers.find(x=>x.id===id); if(!layer)return null;
  const multi=selectedIds.length>1;
  const b=layer.bounds||{},t=layer.transform||{},s=layer.style||{},c=layer.content||{},m=layer.metadata||{},crop=m.crop||{};
  const patchBounds=(key,v)=>workspace.updateLayerLocal(id,{bounds:{...b,[key]:v}});
  const patchStyle=(key,v)=>workspace.updateLayerLocal(id,{style:{...s,[key]:v}});
  const patchCrop=(key,v)=>workspace.updateLayerLocal(id,{metadata:{...m,crop:{...crop,[key]:v}}});
  const align=(mode)=>workspace.alignSelected(mode);
  const transactionProps={onFocus:workspace.beginHistoryTransaction,onBlur:workspace.endHistoryTransaction};
  return <section className="mt-5"><div className="flex items-center justify-between"><div className="text-[9px] font-semibold uppercase tracking-[.22em] text-[#D6A66A]/62">Inspector</div>{multi?<span className="rounded-full border border-[#DDD8D0] bg-[#FBFAF8] px-2 py-0.5 text-[8px] text-[#817A72]">{selectedIds.length} selected</span>:null}</div>
    {!multi?<div className="mt-3 grid grid-cols-2 gap-2"><Field {...transactionProps} label="X" value={b.x??0} onChange={v=>patchBounds("x",v)}/><Field {...transactionProps} label="Y" value={b.y??0} onChange={v=>patchBounds("y",v)}/><Field {...transactionProps} label="Width" value={b.width??240} onChange={v=>patchBounds("width",Math.max(24,v))}/><Field {...transactionProps} label="Height" value={b.height??180} onChange={v=>patchBounds("height",Math.max(24,v))}/><Field {...transactionProps} label="Rotate" value={t.rotation??0} onChange={v=>workspace.updateLayerLocal(id,{transform:{...t,rotation:v}})}/></div>:<div className="mt-3 rounded-lg border border-[#E5E1DA] bg-[#FBFAF8] px-3 py-2 text-[9px] leading-4 text-[#817A72]">Group transform is active on-canvas. Resize from any edge or corner, rotate from the top handle, or align and distribute the selection below.</div>}
    <div className="mt-2 grid grid-cols-3 gap-1"><button onClick={()=>align("left")} className="rounded border border-[#E2DED7] py-1 text-[8px] text-[#8A837A]">Left</button><button onClick={()=>align("center_x")} className="rounded border border-[#E2DED7] py-1 text-[8px] text-[#8A837A]">Center X</button><button onClick={()=>align("right")} className="rounded border border-[#E2DED7] py-1 text-[8px] text-[#8A837A]">Right</button><button onClick={()=>align("top")} className="rounded border border-[#E2DED7] py-1 text-[8px] text-[#8A837A]">Top</button><button onClick={()=>align("center_y")} className="rounded border border-[#E2DED7] py-1 text-[8px] text-[#8A837A]">Center Y</button><button onClick={()=>align("bottom")} className="rounded border border-[#E2DED7] py-1 text-[8px] text-[#8A837A]">Bottom</button></div>
    {multi?<div className="mt-1 grid grid-cols-2 gap-1"><button disabled={selectedIds.length<3} onClick={()=>workspace.distributeSelected("x")} className="rounded border border-[#E2DED7] py-1 text-[8px] text-[#8A837A] disabled:opacity-30">Distribute H</button><button disabled={selectedIds.length<3} onClick={()=>workspace.distributeSelected("y")} className="rounded border border-[#E2DED7] py-1 text-[8px] text-[#8A837A] disabled:opacity-30">Distribute V</button></div>:null}
    {!multi&&layer.layer_type==="IMAGE"?<div className="mt-3 space-y-2"><div className="text-[8px] uppercase tracking-[.14em] text-[#99928A]">Non-destructive crop</div><div className="grid grid-cols-2 gap-2"><Field {...transactionProps} label="Focal X %" value={Math.round((crop.x??.5)*100)} onChange={v=>patchCrop("x",Math.max(0,Math.min(1,v/100)))}/><Field {...transactionProps} label="Focal Y %" value={Math.round((crop.y??.5)*100)} onChange={v=>patchCrop("y",Math.max(0,Math.min(1,v/100)))}/><Field {...transactionProps} label="Zoom %" value={Math.round((crop.zoom??1)*100)} onChange={v=>patchCrop("zoom",Math.max(1,v/100))}/><Field {...transactionProps} label="Radius" value={m.mask_radius??0} onChange={v=>workspace.updateLayerLocal(id,{metadata:{...m,mask_radius:Math.max(0,v)}})}/></div></div>:null}
    {!multi&&layer.layer_type==="TEXT"?<div className="mt-3 space-y-2"><Field {...transactionProps} label="Text" type="text" value={c.text||""} onChange={v=>workspace.updateLayerLocal(id,{content:{...c,text:v}})}/><Field {...transactionProps} label="Font family" type="text" value={s.font_family||"Arial, Helvetica, sans-serif"} onChange={v=>patchStyle("font_family",v)}/><div className="grid grid-cols-2 gap-2"><Field {...transactionProps} label="Font size" value={s.font_size??52} onChange={v=>patchStyle("font_size",Math.max(6,v))}/><Field {...transactionProps} label="Weight" value={s.font_weight??600} onChange={v=>patchStyle("font_weight",v)}/><Field {...transactionProps} label="Line height" step="0.05" value={s.line_height??1.05} onChange={v=>patchStyle("line_height",v)}/><Field {...transactionProps} label="Letter spacing" step="0.1" value={s.letter_spacing??0} onChange={v=>patchStyle("letter_spacing",v)}/><SelectField label="Align" value={s.text_align||"left"} onChange={v=>patchStyle("text_align",v)} options={["left","center","right"]}/><SelectField label="Vertical" value={s.vertical_align||"top"} onChange={v=>patchStyle("vertical_align",v)} options={["top","middle","bottom"]}/></div><label className="block"><span className="text-[8px] uppercase tracking-[.14em] text-[#99928A]">Color</span><input type="color" value={s.color||"#111111"} onFocus={workspace.beginHistoryTransaction} onBlur={workspace.endHistoryTransaction} onChange={e=>patchStyle("color",e.target.value)} className="mt-1 h-8 w-full rounded-md border border-[#DDD8D0] bg-[#FBFAF8]"/></label></div>:null}
  </section>;
}
