"use client";
import Image from "next/image";
import { useMemo, useRef, useState } from "react";
import { buildSafeZone, snapLayerBounds } from "@/lib/creative/stills/runtime/CreativeImageStudioDesignRuntime.js";

const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function rect(layer){const b=layer.bounds||{};return{x:n(b.x),y:n(b.y),width:Math.max(24,n(b.width,240)),height:Math.max(24,n(b.height,180))};}
function urlFor(layer,assets){const a=assets.find(x=>x.id===layer.source_asset_id);return a?.image_url||a?.thumbnail_url||a?.file_url||a?.url||"";}

export default function ImageStudioCanvasSurface({workspace,assets=[]}){
 const board=workspace.artboards.find(x=>x.id===workspace.selection.artboard_id)||workspace.artboards[0];
 const layers=useMemo(()=>workspace.layers.filter(x=>x.artboard_id===board?.id).sort((a,b)=>a.sort_order-b.sort_order),[workspace.layers,board?.id]);
 const shell=useRef(null); const drag=useRef(null); const [guide,setGuide]=useState(null); const [regionDraft,setRegionDraft]=useState(null);
 if(!board)return <div className="flex min-h-[420px] items-center justify-center text-xs text-white/30">Create or save an artboard to start composing.</div>;
 const scale=Math.min(1,workspace.viewport.zoom); const w=board.width*scale,h=board.height*scale; const safe=buildSafeZone(board);
 const begin=(e,layer,mode="move")=>{if(layer.locked)return;e.stopPropagation();const additive=e.shiftKey||e.metaKey||e.ctrlKey;const already=workspace.selection.layer_ids.includes(layer.id);if(additive)workspace.toggleLayerSelection(layer.id);else if(!already)workspace.selectLayers([layer.id]);const selectedIds=already&&!additive?workspace.selection.layer_ids:[layer.id];const origins=new Map(layers.filter(item=>selectedIds.includes(item.id)&&!item.locked).map(item=>[item.id,rect(item)]));drag.current={id:layer.id,mode,startX:e.clientX,startY:e.clientY,r:rect(layer),origins};e.currentTarget.setPointerCapture?.(e.pointerId);};
 const move=(e)=>{const d=drag.current;if(!d)return;const dx=(e.clientX-d.startX)/scale,dy=(e.clientY-d.startY)/scale;let next={...d.r};if(d.mode==="resize"){next.width=Math.max(24,d.r.width+dx);next.height=Math.max(24,d.r.height+dy);workspace.updateLayerLocal(d.id,{bounds:next});return;}next.x=clamp(d.r.x+dx,0,board.width-d.r.width);next.y=clamp(d.r.y+dy,0,board.height-d.r.height);const siblings=layers.filter((layer)=>layer.id!==d.id&&!d.origins?.has(layer.id)&&layer.visible!==false);const snapped=snapLayerBounds(next,board,siblings,{threshold:8/Math.max(scale,.25)});next.x=clamp(snapped.bounds.x,0,board.width-d.r.width);next.y=clamp(snapped.bounds.y,0,board.height-d.r.height);setGuide(snapped.guides);const appliedDx=next.x-d.r.x,appliedDy=next.y-d.r.y;for(const [id,origin] of d.origins||[]){workspace.updateLayerLocal(id,{bounds:{...origin,x:clamp(origin.x+appliedDx,0,board.width-origin.width),y:clamp(origin.y+appliedDy,0,board.height-origin.height)}});}};
 const end=()=>{if(regionDraft){workspace.setRegion(regionDraft);setRegionDraft(null);}drag.current=null;setGuide(null);};
 const regionStart=(e)=>{const box=e.currentTarget.getBoundingClientRect();const x=(e.clientX-box.left)/scale,y=(e.clientY-box.top)/scale;if(workspace.ui.tool==="comment"){workspace.setCommentPoint({x,y});e.stopPropagation();return;}if(workspace.ui.tool!=="region")return;setRegionDraft({x,y,width:1,height:1,startX:x,startY:y});e.stopPropagation();};
 const regionMove=(e)=>{if(!regionDraft)return;const box=e.currentTarget.getBoundingClientRect();const x=(e.clientX-box.left)/scale,y=(e.clientY-box.top)/scale;setRegionDraft({...regionDraft,x:Math.min(regionDraft.startX,x),y:Math.min(regionDraft.startY,y),width:Math.abs(x-regionDraft.startX),height:Math.abs(y-regionDraft.startY)});};
 return <div ref={shell} className="relative flex min-h-full items-center justify-center overflow-auto rounded-2xl border border-white/[0.07] bg-black/60 p-12" onPointerMove={move} onPointerUp={end} onPointerCancel={end}>
  <div className="relative shrink-0 overflow-hidden bg-white shadow-[0_30px_100px_rgba(0,0,0,.55)]" style={{width:w,height:h}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const assetId=e.dataTransfer.getData("application/x-avantiqo-asset");if(!assetId)return;workspace.addLayerLocal({id:crypto.randomUUID(),artboard_id:board.id,parent_layer_id:null,source_asset_id:assetId,layer_type:"IMAGE",name:"Placed asset",bounds:{x:board.width*.15,y:board.height*.15,width:board.width*.7,height:board.height*.7},transform:{rotation:0},style:{},content:{},sort_order:layers.length+1,visible:true,locked:false,metadata:{focal_point:{x:.5,y:.5}}});}} onPointerDown={(e)=>{workspace.selectLayers([]);regionStart(e);}} onPointerMove={regionMove} onPointerUp={end}>
   {workspace.ui.grid?<><div className="pointer-events-none absolute inset-0 z-[2] opacity-10" style={{backgroundImage:"linear-gradient(to right,#000 1px,transparent 1px),linear-gradient(to bottom,#000 1px,transparent 1px)",backgroundSize:`${Math.max(8,board.width/12)*scale}px ${Math.max(8,board.height/12)*scale}px`}}/><div className="pointer-events-none absolute z-[3] border border-dashed border-[#D6A66A]/45" style={{left:safe.x*scale,top:safe.y*scale,width:safe.width*scale,height:safe.height*scale}}/></>:null}
   {workspace.comments.filter((comment)=>comment.artboard_id===board.id&&comment.status!=="RESOLVED").map((comment,index)=><div key={comment.id||index} title={comment.body||"Comment"} className="pointer-events-none absolute z-[70] flex h-5 w-5 items-center justify-center rounded-full bg-[#D6A66A] text-[8px] font-bold text-black" style={{left:n(comment.position?.x)*scale-10,top:n(comment.position?.y)*scale-10}}>{index+1}</div>)}
   {workspace.ui.comment_point?<div className="pointer-events-none absolute z-[75] h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border border-black/50 bg-[#D6A66A]" style={{left:workspace.ui.comment_point.x*scale,top:workspace.ui.comment_point.y*scale}}/>:null}
   {(regionDraft||workspace.ui.region)?<div className="pointer-events-none absolute z-[60] border border-[#D6A66A] bg-[#D6A66A]/10" style={{left:(regionDraft||workspace.ui.region).x*scale,top:(regionDraft||workspace.ui.region).y*scale,width:(regionDraft||workspace.ui.region).width*scale,height:(regionDraft||workspace.ui.region).height*scale}}/>:null}{guide?.x!==null&&guide?.x!==undefined?<div className="pointer-events-none absolute bottom-0 top-0 z-50 w-px bg-[#D6A66A]/80" style={{left:guide.x*scale}}/>:null}{guide?.y!==null&&guide?.y!==undefined?<div className="pointer-events-none absolute left-0 right-0 z-50 h-px bg-[#D6A66A]/80" style={{top:guide.y*scale}}/>:null}
   {layers.map(layer=>{if(!layer.visible)return null;const r=rect(layer),selected=workspace.selection.layer_ids.includes(layer.id),u=urlFor(layer,assets),rot=n(layer.transform?.rotation);const style={left:r.x*scale,top:r.y*scale,width:r.width*scale,height:r.height*scale,transform:`rotate(${rot}deg)`,zIndex:10+layer.sort_order};return <div key={layer.id} className={`absolute overflow-visible ${selected?"ring-1 ring-[#D6A66A]":""}`} style={style} onPointerDown={e=>begin(e,layer)}>
    {layer.layer_type==="TEXT"?<div className="h-full w-full whitespace-pre-wrap" style={{fontSize:n(layer.style?.font_size,36)*scale,fontWeight:layer.style?.font_weight||500,color:layer.style?.color||"#111",lineHeight:layer.style?.line_height||1.05,textAlign:layer.style?.text_align||"left"}}>{layer.content?.text||"Text"}</div>:u?<div className="relative h-full w-full overflow-hidden" style={{borderRadius:n(layer.metadata?.mask_radius)*scale}}><Image src={u} alt={layer.name||"Layer"} fill sizes={`${Math.ceil(r.width)}px`} className="object-cover" style={{objectPosition:`${n(layer.metadata?.crop?.x,.5)*100}% ${n(layer.metadata?.crop?.y,.5)*100}%`,transform:`scale(${Math.max(1,n(layer.metadata?.crop?.zoom,1))})`}} draggable={false}/></div>:<div className="h-full w-full border border-dashed border-black/20 bg-black/5"/>}
    {selected&&!layer.locked?<button aria-label="Resize layer" className="absolute -bottom-1.5 -right-1.5 z-50 h-3 w-3 rounded-full border border-black/60 bg-[#D6A66A]" onPointerDown={e=>begin(e,layer,"resize")}/>:null}
   </div>;})}
  </div>
 </div>;
}
