"use client";

import { useState } from "react";

const PRESETS=["NEUTRAL","CINEMATIC_WARM","COOL_STEEL","TEAL_ORANGE","FADED_FILM","MONOCHROME"];
const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
const defaults=()=>({gradient_map:{enabled:false,strength:0,stops:[{position:0,color:"#000000"},{position:1,color:"#ffffff"}]},split_toning:{enabled:false,shadow_color:"#24405c",highlight_color:"#f4c38a",balance:0,strength:0},creative_look:{preset:"NEUTRAL",strength:0}});

function NumberField({label,value,onChange,min=0,max=100,step=1}){
 return <label className="block"><span className="text-[7px] uppercase tracking-[.1em] text-[#A09A92]">{label}</span><input type="number" min={min} max={max} step={step} value={value??0} onChange={e=>onChange(clamp(e.target.value,min,max))} className="mt-1 w-full rounded border border-[#DDD8D0] bg-white px-2 py-1 text-[9px] text-[#625D56] outline-none focus:border-[#D6A66A]/40"/></label>;
}
function Toggle({active,onClick,children}){return <button type="button" onClick={onClick} className={`rounded border px-2 py-1 text-[8px] ${active?"border-[#D6A66A]/40 bg-[#D6A66A]/10 text-[#8A6A42]":"border-[#E2DED7] text-[#8A837A]"}`}>{children}</button>;}

export default function ImageStudioLookEditor({value={},onChange}){
 const [section,setSection]=useState("GRADIENT");
 const base=defaults();
 const look={gradient_map:{...base.gradient_map,...(value.gradient_map||{}),stops:Array.isArray(value.gradient_map?.stops)&&value.gradient_map.stops.length?value.gradient_map.stops:base.gradient_map.stops},split_toning:{...base.split_toning,...(value.split_toning||{})},creative_look:{...base.creative_look,...(value.creative_look||{})}};
 const patch=(key,next)=>onChange?.({...look,[key]:next});
 const stops=[...look.gradient_map.stops].sort((a,b)=>Number(a.position)-Number(b.position));
 const patchStop=(index,next)=>patch("gradient_map",{...look.gradient_map,stops:stops.map((stop,i)=>i===index?{...stop,...next}:stop)});
 const addStop=()=>{if(stops.length>=8)return;const longest=stops.slice(0,-1).map((stop,i)=>({i,gap:stops[i+1].position-stop.position})).sort((a,b)=>b.gap-a.gap)[0];const i=longest?.i??0,a=stops[i],b=stops[i+1]||a;patch("gradient_map",{...look.gradient_map,stops:[...stops,{position:(a.position+b.position)/2,color:"#808080"}].sort((x,y)=>x.position-y.position)});};
 const removeStop=(index)=>{if(stops.length<=2||index===0||index===stops.length-1)return;patch("gradient_map",{...look.gradient_map,stops:stops.filter((_,i)=>i!==index)});};
 const gradientCss=`linear-gradient(90deg,${stops.map(stop=>`${stop.color} ${Math.round(stop.position*100)}%`).join(",")})`;
 return <div className="rounded-lg border border-[#DDD8D0] bg-white p-2">
  <div className="flex items-center justify-between"><div className="text-[8px] font-semibold uppercase tracking-[.14em] text-[#99928A]">Finishing look</div><button type="button" onClick={()=>onChange?.(defaults())} className="text-[8px] text-[#8A837A]">Reset</button></div>
  <div className="mt-2 grid grid-cols-3 gap-1">{[["GRADIENT","Gradient"],["SPLIT","Split tone"],["LOOK","Creative look"]].map(([id,label])=><button type="button" key={id} onClick={()=>setSection(id)} className={`rounded border py-1 text-[7px] font-semibold uppercase tracking-[.06em] ${section===id?"border-[#D6A66A]/40 bg-[#D6A66A]/10 text-[#8A6A42]":"border-[#E5E1DA] text-[#9A938B]"}`}>{label}</button>)}</div>
  {section==="GRADIENT"?<div className="mt-2 space-y-2"><div className="h-6 rounded border border-[#E5E1DA]" style={{background:gradientCss}}/><div className="flex items-center justify-between"><Toggle active={look.gradient_map.enabled} onClick={()=>patch("gradient_map",{...look.gradient_map,enabled:!look.gradient_map.enabled})}>{look.gradient_map.enabled?"Enabled":"Disabled"}</Toggle><button type="button" disabled={stops.length>=8} onClick={addStop} className="text-[8px] text-[#8A837A] disabled:opacity-30">+ Add stop</button></div><NumberField label="Strength %" value={Math.round(look.gradient_map.strength*100)} onChange={v=>patch("gradient_map",{...look.gradient_map,strength:v/100})}/><div className="space-y-1.5">{stops.map((stop,index)=><div key={index} className="grid grid-cols-[1fr_1fr_auto] items-end gap-2"><label><span className="text-[7px] uppercase tracking-[.1em] text-[#A09A92]">Color</span><input type="color" value={stop.color} onChange={e=>patchStop(index,{color:e.target.value})} className="mt-1 h-7 w-full rounded border border-[#DDD8D0]"/></label><NumberField label="Position %" value={Math.round(stop.position*100)} min={0} max={100} onChange={v=>patchStop(index,{position:v/100})}/><button type="button" disabled={index===0||index===stops.length-1||stops.length<=2} onClick={()=>removeStop(index)} className="mb-1 text-[10px] text-[#B36B52] disabled:opacity-20">×</button></div>)}</div><div className="text-[7px] leading-3 text-[#AAA49C]">Maps source luminance through an editable color ramp; up to 8 stops.</div></div>:null}
  {section==="SPLIT"?<div className="mt-2 space-y-2"><Toggle active={look.split_toning.enabled} onClick={()=>patch("split_toning",{...look.split_toning,enabled:!look.split_toning.enabled})}>{look.split_toning.enabled?"Enabled":"Disabled"}</Toggle><div className="grid grid-cols-2 gap-2"><label><span className="text-[7px] uppercase tracking-[.1em] text-[#A09A92]">Shadow color</span><input type="color" value={look.split_toning.shadow_color} onChange={e=>patch("split_toning",{...look.split_toning,shadow_color:e.target.value})} className="mt-1 h-7 w-full rounded border border-[#DDD8D0]"/></label><label><span className="text-[7px] uppercase tracking-[.1em] text-[#A09A92]">Highlight color</span><input type="color" value={look.split_toning.highlight_color} onChange={e=>patch("split_toning",{...look.split_toning,highlight_color:e.target.value})} className="mt-1 h-7 w-full rounded border border-[#DDD8D0]"/></label><NumberField label="Balance" value={Math.round(look.split_toning.balance*100)} min={-100} max={100} onChange={v=>patch("split_toning",{...look.split_toning,balance:v/100})}/><NumberField label="Strength %" value={Math.round(look.split_toning.strength*100)} onChange={v=>patch("split_toning",{...look.split_toning,strength:v/100})}/></div></div>:null}
  {section==="LOOK"?<div className="mt-2 space-y-2"><label className="block"><span className="text-[7px] uppercase tracking-[.1em] text-[#A09A92]">Governed look preset</span><select value={look.creative_look.preset} onChange={e=>patch("creative_look",{...look.creative_look,preset:e.target.value})} className="mt-1 w-full rounded border border-[#DDD8D0] bg-white px-2 py-1 text-[9px] text-[#625D56]">{PRESETS.map(name=><option key={name} value={name}>{name.replaceAll("_"," ")}</option>)}</select></label><NumberField label="Strength %" value={Math.round(look.creative_look.strength*100)} onChange={v=>patch("creative_look",{...look.creative_look,strength:v/100})}/><div className="text-[7px] leading-3 text-[#AAA49C]">These are deterministic Avantiqo looks. Imported 3D LUTs are governed separately.</div></div>:null}
 </div>;
}
