#!/usr/bin/env bash

set -euo pipefail

ROOT="${AVANTIQO_PROJECT_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)}"
RUN_ID="${AVANTIQO_VOICE_TTS_REFRESH_RUN_ID:-}"
EXPECTED_SOURCE_SHA="${AVANTIQO_VOICE_TTS_EXPECTED_CERTIFIED_SOURCE_SHA:-}"
ENDPOINT_ID="${RUNPOD_AVANTIQO_VOICE_TTS_ENDPOINT_ID:-}"
REPOSITORY="churchillkaron/churchill-control-new"
WORKFLOW_NAME="Avantiqo Voice TTS Worker Image Refresh"

fail() {
  echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH=FAIL"
  echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_REASON=$1"
  echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_GENERATION_SUBMITTED=false"
  echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_PRODUCTION_DEPLOY_PERFORMED=false"
  echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_PRICING_ACTIVATION_PERFORMED=false"
  exit 1
}

[ -n "$RUN_ID" ] || fail "AVANTIQO_VOICE_TTS_REFRESH_RUN_ID_REQUIRED"
[ -n "$EXPECTED_SOURCE_SHA" ] || fail "AVANTIQO_VOICE_TTS_EXPECTED_CERTIFIED_SOURCE_SHA_REQUIRED"
[ -n "$ENDPOINT_ID" ] || fail "RUNPOD_AVANTIQO_VOICE_TTS_ENDPOINT_ID_REQUIRED"
printf '%s' "$EXPECTED_SOURCE_SHA" | grep -Eq '^[a-f0-9]{40}$' || fail "EXPECTED_SOURCE_SHA_INVALID"
printf '%s' "$RUN_ID" | grep -Eq '^[0-9]+$' || fail "WORKFLOW_RUN_ID_INVALID"
command -v gh >/dev/null 2>&1 || fail "GH_REQUIRED"
command -v git >/dev/null 2>&1 || fail "GIT_REQUIRED"
command -v node >/dev/null 2>&1 || fail "NODE_REQUIRED"

cd "$ROOT"

META="$(gh run view "$RUN_ID" --repo "$REPOSITORY" --json workflowName,headSha,event --jq '[.workflowName,.headSha,.event] | @tsv')" \
  || fail "WORKFLOW_RUN_READ_FAILED"
IFS=$'\t' read -r ACTUAL_WORKFLOW ACTUAL_HEAD_SHA ACTUAL_EVENT <<< "$META"
[ "$ACTUAL_WORKFLOW" = "$WORKFLOW_NAME" ] || fail "WORKFLOW_NAME_MISMATCH"
[ "$ACTUAL_HEAD_SHA" = "$EXPECTED_SOURCE_SHA" ] || fail "WORKFLOW_SOURCE_SHA_MISMATCH"
[ "$ACTUAL_EVENT" = "workflow_dispatch" ] || fail "WORKFLOW_EVENT_MISMATCH"

echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_RUN_ID=$RUN_ID"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_SOURCE_SHA=$EXPECTED_SOURCE_SHA"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_WORKFLOW_VERIFIED=true"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_GENERATION_SUBMITTED=false"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_PRODUCTION_DEPLOY_PERFORMED=false"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_PRICING_ACTIVATION_PERFORMED=false"

gh run watch "$RUN_ID" --repo "$REPOSITORY" --exit-status \
  || fail "VOICE_TTS_IMAGE_REFRESH_WORKFLOW_FAILED"

CONCLUSION="$(gh run view "$RUN_ID" --repo "$REPOSITORY" --json conclusion --jq '.conclusion')" \
  || fail "WORKFLOW_CONCLUSION_READ_FAILED"
[ "$CONCLUSION" = "success" ] || fail "WORKFLOW_CONCLUSION_NOT_SUCCESS:$CONCLUSION"

git fetch origin main
git merge --ff-only origin/main

SOURCE_DOCKERFILE="$(git show "$EXPECTED_SOURCE_SHA:services/avantiqo-voice-tts/Dockerfile")" \
  || fail "EXPECTED_SOURCE_DOCKERFILE_UNAVAILABLE"
printf '%s\n' "$SOURCE_DOCKERFILE" | grep -F 'ref_path.write_text(revision, encoding="utf-8")' >/dev/null \
  || fail "VOICE_TTS_OFFLINE_MAIN_REF_NO_NEWLINE_FIX_REQUIRED"
printf '%s\n' "$SOURCE_DOCKERFILE" | grep -F 'local_files_only=True' >/dev/null \
  || fail "VOICE_TTS_OFFLINE_LOCAL_FILES_ONLY_BUILD_GATE_REQUIRED"
printf '%s\n' "$SOURCE_DOCKERFILE" | grep -F 'AVANTIQO_VOICE_TTS_BAKED_OFFLINE_MAIN=PASS' >/dev/null \
  || fail "VOICE_TTS_OFFLINE_MAIN_BUILD_ASSERTION_REQUIRED"

echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_SOURCE_GATE=PASS"

bash scripts/repair-avantiqo-runpod-env-local.sh \
  || fail "RUNPOD_LOCAL_ENV_REPAIR_FAILED"

AVANTIQO_VOICE_TTS_EXPECTED_CERTIFIED_SOURCE_SHA="$EXPECTED_SOURCE_SHA" \
AVANTIQO_VOICE_TTS_V3_BIND_STARTUP_PROBE_APPROVED=YES \
RUNPOD_AVANTIQO_VOICE_TTS_ENDPOINT_ID="$ENDPOINT_ID" \
node --env-file=.env.local scripts/bind-avantiqo-voice-tts-v3-certified-image-local.mjs --apply \
  || fail "VOICE_TTS_CERTIFIED_IMAGE_BIND_FAILED"

RUNPOD_AVANTIQO_VOICE_TTS_ENDPOINT_ID="$ENDPOINT_ID" \
node --env-file=.env.local scripts/check-avantiqo-voice-tts-v3-readiness-local.mjs \
  || fail "VOICE_TTS_POST_BIND_READINESS_FAILED"

echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH=PASS"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_GENERATION_SUBMITTED=false"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_STT_SUBMITTED=false"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_PRODUCTION_DEPLOY_PERFORMED=false"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_PRICING_ACTIVATION_PERFORMED=false"
echo "AVANTIQO_VOICE_TTS_V3_OFFLINE_CACHE_FINISH_SECRETS_PRINTED=false"
