#!/bin/sh
set -eu
ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT_DIR"
: "${AVANTIQO_MUSIC_VOCAL_CORRECTION_CERTIFICATION_RIGHTS_APPROVED:?AVANTIQO_MUSIC_VOCAL_CORRECTION_CERTIFICATION_RIGHTS_APPROVED=YES_REQUIRED}"
[ "$AVANTIQO_MUSIC_VOCAL_CORRECTION_CERTIFICATION_RIGHTS_APPROVED" = "YES" ] || { echo RIGHTS_APPROVAL_REQUIRED >&2; exit 1; }
if [ "${AVANTIQO_MUSIC_VOCAL_CORRECTION_CERTIFICATION_SPEND_APPROVED:-}" = "YES" ]; then echo NODE01_LANE_MUST_NOT_REQUIRE_EXTERNAL_SPEND_APPROVAL >&2; exit 1; fi
node scripts/run-avantiqo-music-vocal-correction-node01-certification.mjs
node scripts/prepare-avantiqo-music-vocal-correction-human-review.mjs
printf '%s\n' 'AVANTIQO_MUSIC_VOCAL_CORRECTION_CERTIFICATION=NODE01_TECHNICAL_PASS_HUMAN_REVIEW_REQUIRED'
printf '%s\n' 'AVANTIQO_MUSIC_VOCAL_CORRECTION_EXTERNAL_PROVIDER_SPEND=0'
printf '%s\n' 'AVANTIQO_MUSIC_VOCAL_CORRECTION_PRODUCTION_ACTIVATION=false'
