import PublicSiteHeader from "@/components/public/PublicSiteHeader";
import { productCatalog, PRODUCT_FAMILIES } from "@/components/public/productCatalog";

export const metadata = {
  title: "Developer Capabilities | Avantiqo",
  description: "The Avantiqo capability catalog for developers — business, finance, workforce, document, operations, intelligence and creative engines exposed as exact reusable capabilities.",
};

function Arrow(){return <svg aria-hidden="true" viewBox="0 0 20 20" className="h-3.5 w-3.5" fill="none"><path d="M4 10h11M11 6l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>}

const apiProducts = productCatalog.filter((product) => product.api);
const groups = PRODUCT_FAMILIES.map((family) => ({
  ...family,
  products: apiProducts.filter((product) => product.family === family.id),
})).filter((family) => family.products.length);

export default function DeveloperCapabilitiesPage(){
  return <main className="min-h-screen bg-[#F7F6F3] text-[#171614]">
    <PublicSiteHeader context="Developer Capabilities" audience="developers" />
    <section className="border-b border-[#BDAF9E]/30 bg-[#F3EEE5] text-[#171614]"><div className="mx-auto max-w-[1540px] px-5 py-16 sm:px-7 lg:px-10 lg:py-24 xl:px-14"><p className="text-[9px] font-semibold uppercase tracking-[.24em] text-[#9A744B]">AVANTIQO CAPABILITY CATALOG</p><div className="mt-4 grid gap-10 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><h1 className="max-w-[980px] text-[54px] font-medium leading-[.93] tracking-[-.065em] sm:text-[72px] lg:text-[86px]">Use the business engine without rebuilding the business engine.</h1><p className="mt-7 max-w-[850px] text-[15px] leading-8 text-[#655D54]">Use Avantiqo capabilities from your own software with organization scope, permissions, usage tracking and clear execution results already built into the platform.</p></div><div className="rounded-[28px] border border-[#BDAF9E]/35 bg-white/64 p-6 shadow-[0_18px_50px_rgba(55,39,22,.06)]"><div className="text-[42px] font-medium tracking-[-.06em]">{apiProducts.length}</div><div className="mt-1 text-[8px] font-semibold uppercase tracking-[.15em] text-[#9A744B]">business capabilities</div><p className="mt-5 text-[10px] leading-5 text-[#7A756E]">Use Avantiqo capabilities to add business actions to your own software without rebuilding finance, workforce, operations, document or creative workflows from scratch.</p></div></div></div></section>
    <section className="border-b border-[#BDAF9E]/30 bg-[#F3EEE5]"><div className="mx-auto max-w-[1540px] px-5 py-10 sm:px-7 lg:px-10 xl:px-14"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-[22px] border border-[#BDAF9E]/35 bg-white p-5"><div className="text-[8px] font-bold text-[#A37849]">01</div><h2 className="mt-5 text-[16px] font-semibold">Send data or a request</h2><p className="mt-2 text-[9px] leading-5 text-[#746E66]">Image, PDF, transaction, customer, order, attendance event or structured payload.</p></div><div className="rounded-[22px] border border-[#BDAF9E]/35 bg-white p-5"><div className="text-[8px] font-bold text-[#A37849]">02</div><h2 className="mt-5 text-[16px] font-semibold">Resolve organization context</h2><p className="mt-2 text-[9px] leading-5 text-[#746E66]">Organization, entity, permissions, policy and the capability being called.</p></div><div className="rounded-[22px] border border-[#BDAF9E]/35 bg-white p-5"><div className="text-[8px] font-bold text-[#A37849]">03</div><h2 className="mt-5 text-[16px] font-semibold">Execute the capability</h2><p className="mt-2 text-[9px] leading-5 text-[#746E66]">Read, calculate, classify, create, update, settle, publish or generate.</p></div><div className="rounded-[22px] border border-[#BDAF9E]/35 bg-white p-5"><div className="text-[8px] font-bold text-[#A37849]">04</div><h2 className="mt-5 text-[16px] font-semibold">Return the result</h2><p className="mt-2 text-[9px] leading-5 text-[#746E66]">Result, usage, audit history and references to any created or updated business records.</p></div></div></div></section>
    {groups.map((group,index)=><section key={group.id} className={`border-b border-[#BDAF9E]/30 ${index%2===0?'bg-[#FBFAF8]':'bg-[#F3EFE7]'}`}><div className="mx-auto max-w-[1540px] px-5 py-14 sm:px-7 lg:px-10 lg:py-18 xl:px-14"><div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><div className="text-[8px] font-bold text-[#A37849]">{String(index+1).padStart(2,'0')}</div><h2 className="mt-2 text-[34px] font-medium tracking-[-.045em]">{group.label}</h2></div><p className="max-w-2xl text-[11px] leading-6 text-[#716A62] lg:justify-self-end">{group.description}</p></div><div className="mt-7 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{group.products.map((product)=><article key={product.id} className="rounded-[22px] border border-[#BDAF9E]/35 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><div className="text-[7px] font-semibold uppercase tracking-[.14em] text-[#9A744B]">{product.engine}</div><h3 className="mt-2 text-[17px] font-semibold tracking-[-.025em]">{product.name}</h3></div><span className="rounded-full border border-[#D6A66A]/24 bg-[#FAF6EF] px-2.5 py-1 text-[7px] font-bold uppercase tracking-[.1em] text-[#9A744B]">API</span></div><p className="mt-3 text-[9px] leading-5 text-[#746E66]">{product.summary}</p><div className="mt-5 flex items-center justify-between border-t border-[#BDAF9E]/30 pt-4"><span className="text-[7px] font-semibold uppercase tracking-[.12em] text-[#8A8177]">For developers</span><a href={product.href || `/products/${product.id}`} className="inline-flex items-center gap-1.5 text-[8px] font-semibold text-[#8E653D]">Product context <Arrow/></a></div></article>)}</div></div></section>)}
    <section className="bg-[#EEE6DB] text-[#1D1B18]"><div className="mx-auto max-w-[1200px] px-5 py-20 text-center sm:px-7 lg:px-10"><p className="text-[9px] font-semibold uppercase tracking-[.22em] text-[#9A744B]">BUILD ON THE SAME BUSINESS CAPABILITIES</p><h2 className="mx-auto mt-4 max-w-4xl text-[42px] font-medium leading-[.98] tracking-[-.055em] sm:text-[58px]">Business capabilities you can use inside your own product.</h2><p className="mx-auto mt-6 max-w-3xl text-[12px] leading-7 text-[#6D645B]">Use the same business capability through an Avantiqo workspace, your integration, an API or an embedded experience without rebuilding the business rules yourself.</p><div className="mt-8 flex flex-wrap justify-center gap-2.5"><a href="/products" className="inline-flex h-11 items-center gap-2 rounded-full bg-[#171614] px-5 text-[10px] font-semibold text-white">Product catalog <Arrow/></a><a href="/api-platform" className="inline-flex h-11 items-center rounded-full border border-black/[0.10] bg-white/62 px-5 text-[10px] font-semibold text-[#5A5148]">API Platform</a></div></div></section>
  </main>;
}
