export const CAPABILITY_REGISTRY = {
  TEXT_AI: "TEXT_AI",
  IMAGE_AI: "IMAGE_AI",
  VIDEO_AI: "VIDEO_AI",
  VOICE_AI: "VOICE_AI",
  OCR: "OCR",
  TRANSLATION: "TRANSLATION",
  EMBEDDINGS: "EMBEDDINGS",

  FACEBOOK: "FACEBOOK",
  INSTAGRAM: "INSTAGRAM",
  META_ADS: "META_ADS",
  GOOGLE_BUSINESS: "GOOGLE_BUSINESS",
  TRIPADVISOR: "TRIPADVISOR",

  WHATSAPP: "WHATSAPP",
  LINE: "LINE",
  TELEGRAM: "TELEGRAM",
  EMAIL: "EMAIL",
  SMS: "SMS",

  CARD_PAYMENTS: "CARD_PAYMENTS",
  PAYMENT_LINKS: "PAYMENT_LINKS",

  BOOKING: "BOOKING",
  CHANNEL_MANAGER: "CHANNEL_MANAGER",
  GOOGLE_HOTELS: "GOOGLE_HOTELS",

  STORAGE: "STORAGE",
  SSO: "SSO",
  COMMERCE: "COMMERCE",
  ACCOUNTING_SYNC: "ACCOUNTING_SYNC",
  CRM_SYNC: "CRM_SYNC",
  WEBHOOKS: "WEBHOOKS",
  PRODUCTIVITY: "PRODUCTIVITY",
};

export function getCapability(id) {
  return CAPABILITY_REGISTRY[id] || null;
}

export function listCapabilities() {
  return Object.values(
    CAPABILITY_REGISTRY
  );
}
