import { AVANTIQO_INVESTOR_STUDIO_GENERATION_PLAN } from "./AvantiqoInvestorStudioGenerationPlan";

export const AVANTIQO_INVESTOR_PRODUCT_PROOF_PLAN = Object.freeze({
  contract: "AVANTIQO_INVESTOR_PRODUCT_PROOF_V2_STUDIO_GENERATED",
  audio_source: "LOCKED_CEDAR_V5_229_5_SECONDS",
  audio_start_seconds: 40.078,
  audio_end_seconds: 136.266,
  target_duration_seconds: 96.188,
  studio_generation_plan: AVANTIQO_INVESTOR_STUDIO_GENERATION_PLAN,
  source_policy: "FRESH_AVANTIQO_STUDIO_GENERATED_FILM_ASSETS_GROUNDED_IN_REAL_CAPABILITIES",
  source_quality_policy: "USER_APPROVED_LOCKED_SCENES_OR_FRESH_STUDIO_GENERATION_ONLY",
  existing_asset_policy: "GROUNDING_REFERENCE_ONLY_NOT_FINAL_INSERT",
  capability_resolution_policy: "RESOLVE_REAL_CAPABILITIES_THROUGH_SERVICE_RUNTIME_BEFORE_VISUAL_PLANNING",
  scene_completion_policy: "GENERATE_IN_STUDIO_THEN_RENDER_WITH_LOCKED_NARRATION_THEN_VISUAL_REVIEW_THEN_REPAIR_THEN_USER_APPROVAL_THEN_LOCK",
  synthetic_product_ui_allowed: false,
  product_screenshot_allowed: false,
  extracted_screenshot_fragment_allowed: false,
  browser_window_allowed: false,
  final_asset_reuse_allowed: false,
  official_identity_marks_allowed: true,
  semantic_visual_policy: Object.freeze([
    "SHOW_WHAT_THE_NARRATION_IS_TALKING_ABOUT",
    "EVERY_SPOKEN_DOMAIN_OR_CHANNEL_MUST_HAVE_CLEAR_VISUAL_EVIDENCE",
    "USE_REAL_AVANTIQO_CAPABILITIES_AND_RELATIONSHIPS_AS_GROUNDING",
    "CREATE_THE_FILM_VISUALS_FRESH_INSIDE_AVANTIQO_STUDIO",
    "REFERENCE_ASSETS_INFORM_GENERATION_BUT_ARE_NOT_INSERTED_AS_FINAL_MEDIA",
    "COMMUNICATION_SCENES_SHOW_MESSAGE_TO_CONTEXT_TO_BUSINESS_ACTION",
    "CREATIVE_SCENES_SHOW_STUDIO_CREATING_FRESH_WORK_NOW",
    "WORKFLOW_SCENES_SHOW_CAUSE_TO_BUSINESS_OBJECT_TO_RESULT",
    "REAL_WORLD_CINEMATIC_ACTION_REMAINS_THE_HERO",
    "NO_PRODUCT_SCREENSHOTS",
    "NO_EXTRACTED_SCREENSHOT_GHOSTS",
    "NO_CARD_WALLS",
    "NO_FAKE_UI",
    "NO_GENERIC_AI_ORB",
    "NO_REPEATED_OPERATOR_AT_LAPTOP_AS_DEFAULT_VISUAL",
    "NO_GIANT_EXPLANATORY_CAPTIONS",
  ]),
  capability_visual_roles: [
    "organization_intelligence",
    "operations",
    "supply_chain",
    "finance",
    "customer_communications",
    "people",
    "creative_studio",
    "code_intelligence",
    "operator_runtime",
    "music",
    "speech",
    "integrations",
  ],
  beats: [
    {
      id: "system-01",
      start: 40.078,
      end: 47.672,
      duration: 7.594,
      visual: "organization_intelligence_shared_operating_context",
      required_capabilities: ["organization_intelligence"],
    },
    {
      id: "system-02a",
      start: 47.672,
      end: 54.844,
      duration: 7.172,
      visual: "separate_finance_operations_customers_and_ai",
      required_capabilities: ["finance", "operations", "customer_communications", "organization_intelligence"],
    },
    {
      id: "system-02b",
      start: 54.844,
      end: 62.016,
      duration: 7.172,
      visual: "connected_information_decisions_and_execution",
      required_capabilities: ["organization_intelligence", "operations", "finance", "customer_communications"],
    },
    {
      id: "system-03a",
      start: 62.016,
      end: 67.500,
      duration: 5.484,
      visual: "organization_context_people_entities_permissions_customers_suppliers_history",
      required_capabilities: ["organization_intelligence", "people", "customer_communications", "supply_chain"],
    },
    {
      id: "system-03b",
      start: 67.500,
      end: 72.984,
      duration: 5.484,
      visual: "shared_context_unifies_workspaces",
      required_capabilities: ["organization_intelligence", "operations", "finance", "supply_chain", "customer_communications"],
    },
    {
      id: "system-04",
      start: 72.984,
      end: 75.938,
      duration: 2.954,
      visual: "organization_intelligence_changes_software_capability",
      required_capabilities: ["organization_intelligence", "operator_runtime"],
    },
    {
      id: "workflow-01a",
      start: 75.938,
      end: 81.563,
      duration: 5.625,
      visual: "customer_interaction_channels_to_avantiqo_context_to_action",
      required_capabilities: ["customer_communications", "operator_runtime"],
      editorial_identity_marks: ["WhatsApp", "LINE", "Messenger", "Facebook", "Instagram", "Google Reviews", "Email", "Website"],
    },
    {
      id: "workflow-01b",
      start: 81.563,
      end: 87.188,
      duration: 5.625,
      visual: "creative_studio_creates_campaign_to_customer_and_result",
      required_capabilities: ["creative_studio", "customer_communications", "finance"],
      generation_requirement: "ALL_CAMPAIGN_MEDIA_CREATED_FRESH_FOR_INVESTOR_FILM",
    },
    {
      id: "workflow-01c",
      start: 87.188,
      end: 92.813,
      duration: 5.625,
      visual: "quotation_booking_task_service_followup_connected",
      required_capabilities: ["customer_communications", "commercial", "operations"],
    },
    { id: "workflow-02", start: 92.813, end: 102.094, duration: 9.281, visual: "operations_attention_to_action", required_capabilities: ["operations", "operator_runtime"] },
    { id: "workflow-03", start: 102.094, end: 103.782, duration: 1.688, visual: "UNDERSTAND_RECOMMEND_APPROVE_EXECUTE", required_capabilities: ["organization_intelligence", "operator_runtime"] },
    { id: "vertical-01", start: 103.782, end: 106.313, duration: 2.531, visual: "NOT_ONE_VERTICAL" },
    { id: "vertical-02", start: 106.313, end: 113.907, duration: 7.594, visual: "pest_control_operations", required_capabilities: ["operations"] },
    { id: "vertical-03a", start: 113.907, end: 118.759, duration: 4.852, visual: "restaurant_operations", required_capabilities: ["operations"] },
    { id: "vertical-03b", start: 118.759, end: 123.611, duration: 4.852, visual: "hotel_operations", required_capabilities: ["operations"] },
    { id: "vertical-03c", start: 123.611, end: 128.462, duration: 4.851, visual: "healthcare_operations", required_capabilities: ["operations"] },
    { id: "vertical-03d", start: 128.462, end: 133.313, duration: 4.851, visual: "connected_services_and_field_service", required_capabilities: ["integrations", "operations"] },
    { id: "vertical-04", start: 133.313, end: 136.266, duration: 2.953, visual: "ONE_OPERATING_ARCHITECTURE" },
  ],
  final_montage_order: [
    "organization_intelligence",
    "operations",
    "supply_chain",
    "finance",
    "creative_studio",
    "customer_communications",
    "operator_runtime",
    "pest_control_operations",
    "restaurant_operations",
    "healthcare_operations",
    "integrations",
  ],
});

export default AVANTIQO_INVESTOR_PRODUCT_PROOF_PLAN;
