export const AVANTIQO_INVESTOR_PRODUCT_PROOF_PLAN = Object.freeze({
  contract: "AVANTIQO_INVESTOR_PRODUCT_PROOF_V1",
  audio_source: "LOCKED_CEDAR_V5_229_5_SECONDS",
  audio_start_seconds: 40.078,
  audio_end_seconds: 136.266,
  target_duration_seconds: 96.188,
  source_policy: "AUTHENTIC_AVANTIQO_UI_ONLY",
  source_quality_policy: "APPROVED_VERIFIED_OR_EXPLICITLY_USER_VISUALLY_LOCKED_ONLY",
  scene_completion_policy: "RENDER_THEN_VISUAL_REVIEW_THEN_REPAIR_THEN_USER_APPROVAL_THEN_LOCK_BEFORE_NEXT_SCENE",
  synthetic_product_ui_allowed: false,
  browser_chrome_policy: "CROP_ONLY_DO_NOT_RECREATE_UI",
  error_state_policy: "EXCLUDE_ERROR_FAILED_EMPTY_OR_TEST_STATES_WHEN_CLEAN_ALTERNATIVE_EXISTS",
  semantic_visual_policy: Object.freeze([
    "SHOW_WHAT_THE_NARRATION_IS_TALKING_ABOUT",
    "EVERY_SPOKEN_DOMAIN_OR_CHANNEL_MUST_HAVE_CLEAR_VISUAL_EVIDENCE",
    "DO_NOT_SUBSTITUTE_AN_UNRELATED_INDUSTRY_SHOT_FOR_AN_ABSTRACT_BUSINESS_CONCEPT",
    "COMMUNICATION_SCENES_SHOW_THE_REAL_CHANNEL_ECOSYSTEM",
    "WORKFLOW_SCENES_SHOW_CAUSE_TO_BUSINESS_OBJECT_TO_RESULT",
    "REAL_WORLD_FOOTAGE_REMAINS_THE_HERO",
    "NO_CARD_WALLS",
    "NO_FAKE_UI",
    "NO_GENERIC_AI_ORB",
    "NO_IMAGE_GENERATION",
  ]),
  preferred_real_ui_roles: [
    "organization_intelligence",
    "operations_command_center",
    "supply_chain",
    "finance",
    "general_ledger",
    "finance_governance_accounting_settings",
    "autonomous_marketing",
    "customer_communications",
    "payroll",
    "employee_directory",
    "integrations",
    "pest_control_operations",
    "healthcare_operations",
  ],
  beats: [
    {
      id: "system-01",
      start: 40.078,
      end: 47.672,
      duration: 7.594,
      visual: "organization_intelligence_shared_operating_context",
      required_visuals: ["organization_intelligence"],
    },
    {
      id: "system-02a",
      start: 47.672,
      end: 54.844,
      duration: 7.172,
      visual: "separate_finance_operations_customers_and_ai",
      required_visuals: ["finance", "operations_command_center", "customer_communications", "organization_intelligence"],
    },
    {
      id: "system-02b",
      start: 54.844,
      end: 62.016,
      duration: 7.172,
      visual: "connected_information_decisions_and_execution",
      required_visuals: ["organization_intelligence", "operations_command_center", "finance", "customer_communications"],
    },
    {
      id: "system-03a",
      start: 62.016,
      end: 67.500,
      duration: 5.484,
      visual: "organization_context_people_entities_permissions_customers_suppliers_history",
      required_visuals: ["organization_intelligence", "employee_directory", "customer_communications", "supply_chain"],
    },
    {
      id: "system-03b",
      start: 67.500,
      end: 72.984,
      duration: 5.484,
      visual: "shared_context_unifies_workspaces",
      required_visuals: ["organization_intelligence", "operations_command_center", "finance", "supply_chain", "customer_communications"],
    },
    {
      id: "system-04",
      start: 72.984,
      end: 75.938,
      duration: 2.954,
      visual: "organization_intelligence_changes_software_capability",
      required_visuals: ["organization_intelligence"],
    },
    {
      id: "workflow-01a",
      start: 75.938,
      end: 81.563,
      duration: 5.625,
      visual: "customer_interaction_channels_to_avantiqo",
      required_visuals: ["customer_communications", "communication_channel_marks"],
    },
    {
      id: "workflow-01b",
      start: 81.563,
      end: 87.188,
      duration: 5.625,
      visual: "campaign_to_customer_and_result",
      required_visuals: ["autonomous_marketing", "campaign_channel_marks", "customer_context", "result_context"],
    },
    {
      id: "workflow-01c",
      start: 87.188,
      end: 92.813,
      duration: 5.625,
      visual: "quotation_booking_task_service_followup_connected",
      required_visuals: ["customer_communications", "quotation", "booking", "task", "service", "follow_up"],
    },
    { id: "workflow-02", start: 92.813, end: 102.094, duration: 9.281, visual: "operations_attention_to_action" },
    { id: "workflow-03", start: 102.094, end: 103.782, duration: 1.688, visual: "UNDERSTAND_RECOMMEND_APPROVE_EXECUTE" },
    { id: "vertical-01", start: 103.782, end: 106.313, duration: 2.531, visual: "NOT_ONE_VERTICAL" },
    { id: "vertical-02", start: 106.313, end: 113.907, duration: 7.594, visual: "pest_control_operations" },
    { id: "vertical-03a", start: 113.907, end: 118.759, duration: 4.852, visual: "restaurant_operations" },
    { id: "vertical-03b", start: 118.759, end: 123.611, duration: 4.852, visual: "hotel_or_generic_operations_shell" },
    { id: "vertical-03c", start: 123.611, end: 128.462, duration: 4.851, visual: "healthcare_operations" },
    { id: "vertical-03d", start: 128.462, end: 133.313, duration: 4.851, visual: "connected_services_or_field_service" },
    { id: "vertical-04", start: 133.313, end: 136.266, duration: 2.953, visual: "ONE_OPERATING_ARCHITECTURE" },
  ],
  finance_governance_insert: {
    role: "finance_governance_accounting_settings",
    status: "DEFER_TO_FINANCE_OR_INTEGRATION_NARRATION",
    purpose: "prove real accounting configuration and controlled finance governance where the narration is actually about finance",
  },
  final_montage_order: [
    "organization_intelligence",
    "operations_command_center",
    "supply_chain",
    "finance",
    "general_ledger_or_accounting_settings",
    "autonomous_marketing",
    "customer_communications",
    "operations_attention_to_action",
    "pest_control_operations",
    "restaurant_operations",
    "healthcare_operations",
    "connected_services_or_field_service",
  ],
});

export default AVANTIQO_INVESTOR_PRODUCT_PROOF_PLAN;
