import { AVANTIQO_INVESTOR_INTELLIGENCE_OWNERSHIP_PATCH } from "./AvantiqoInvestorIntelligenceOwnershipPatch";
import { AVANTIQO_INVESTOR_STUDIO_GENERATION_PLAN } from "./AvantiqoInvestorStudioGenerationPlan";

export const AVANTIQO_INVESTOR_FINAL_ACT_PLAN = Object.freeze({
  contract: "AVANTIQO_INVESTOR_FINAL_ACT_V3_STUDIO_GENERATED",
  audio_source: "LOCKED_CEDAR_V5_WITH_AVANTIQO_INTELLIGENCE_OWNERSHIP_PATCH",
  audio_start_seconds: 136.266,
  audio_end_seconds: 229.5,
  target_duration_seconds: 93.234,
  source_policy: "FRESH_AVANTIQO_STUDIO_GENERATED_FILM_ASSETS_PLUS_LOCKED_FOUNDER_AND_LOGO_WINDOWS",
  existing_asset_policy: "GROUNDING_REFERENCE_ONLY_NOT_FINAL_INSERT",
  founder_identity_policy: "APPROVED_GEMINI_FOUNDER_MOTION_ONLY",
  synthetic_product_ui_allowed: false,
  product_screenshot_allowed: false,
  extracted_screenshot_fragment_allowed: false,
  browser_window_allowed: false,
  semantic_sync_required: true,
  studio_generation_plan: AVANTIQO_INVESTOR_STUDIO_GENERATION_PLAN,
  intelligence_ownership_patch: AVANTIQO_INVESTOR_INTELLIGENCE_OWNERSHIP_PATCH,
  capability_resolution_policy: "SERVICE_RUNTIME_REAL_CAPABILITIES_DRIVE_VISUAL_GENERATION",
  release_requirements: Object.freeze({
    avantiqo_owned_intelligence_explicit: true,
    openai_or_claude_must_not_be_presented_as_brain: true,
    external_models_are_optional_providers_only: true,
    fresh_studio_generation_required: true,
    screenshots_forbidden: true,
    intelligence_surfaces_must_be_visible: Object.freeze([
      "CHAT",
      "CODE",
      "OPERATE",
      "CREATIVE STUDIO",
      "MUSIC",
      "SPEECH",
    ]),
  }),
  beats: [
    {
      id: "integration-01",
      start: 136.266,
      end: 140.062,
      duration: 3.797,
      visual: "FOUNDER",
      spoken_meaning: "And the important part is what happens between them.",
    },
    {
      id: "integration-02",
      start: 140.062,
      end: 157.359,
      duration: 17.297,
      visual: "STUDIO_GENERATED_SALE_TO_FINANCE_TO_SUPPLY_TO_PEOPLE_FLOW",
      required_capabilities: ["commercial", "finance", "supply_chain", "people", "compliance"],
      generation_direction: "Create fresh cinematic business moments for each function and connect them with one continuous governed event. No application screens.",
      spoken_meaning: "Show the exact operating chain as each business function is named.",
    },
    {
      id: "channels-01",
      start: 157.359,
      end: 168.328,
      duration: 10.969,
      visual: "STUDIO_GENERATED_MULTI_INTERFACE_ONE_TRUTH",
      required_capabilities: ["customer_communications", "people", "supply_chain", "operations"],
      generation_direction: "Create fresh real-world interactions for customer, employee, supplier and operations participants. Use one visual context thread to prove the same underlying truth without showing interfaces.",
      spoken_meaning: "Different interfaces, same operating system and underlying truth.",
    },
    {
      id: "channels-02",
      start: 168.328,
      end: 177.188,
      duration: 8.859,
      visual: "STUDIO_GENERATED_INTEGRATIONS_OUTWARD_CONNECTIONS",
      required_capabilities: ["integrations"],
      editorial_identity_marks_allowed: true,
      generation_direction: "Create a premium outward connection choreography from Avantiqo context to websites, communication, commerce and external services. Official service marks may appear as identity marks, never a static logo wall.",
      spoken_meaning: "Websites, communications, commerce and external services extend outward while organization context remains central.",
    },
    {
      id: "ai-01",
      start: 177.188,
      end: 183.516,
      duration: 6.328,
      visual: "FOUNDER_TO_AVANTIQO_INTELLIGENCE",
      spoken_meaning: "State explicitly that Avantiqo Intelligence is not OpenAI or Claude; it is Avantiqo's own intelligence built into the operating system.",
    },
    {
      id: "ai-02",
      start: 183.516,
      end: 196.172,
      duration: 12.656,
      visual: "STUDIO_GENERATED_AVANTIQO_INTELLIGENCE_CAPABILITY_FILM",
      required_capabilities: ["chat", "code_intelligence", "operator_runtime", "creative_studio", "music", "speech"],
      capability_signals: ["CHAT", "CODE", "OPERATE", "CREATIVE STUDIO", "MUSIC", "SPEECH"],
      generation_direction: "Generate fresh film material for every intelligence capability. Creative Studio must visibly create new campaign media; Code must use real repository facts translated into cinematic code motion; Operate must show decision becoming action; Music and Speech must use actual generated audio evidence represented cinematically. No product screenshots.",
      spoken_meaning: "One Avantiqo-owned intelligence spans conversation, coding, system management and execution, Creative Studio, music and speech.",
    },
    {
      id: "ai-03",
      start: 196.172,
      end: 199.547,
      duration: 3.375,
      visual: "AVANTIQO_OWNS_THE_BRAIN",
      generation_direction: "Resolve context, memory, orchestration and execution into one restrained Avantiqo intelligence motif. External model providers remain peripheral and never become the hero.",
      spoken_meaning: "External models may assist as providers, but Avantiqo owns the context, memory, orchestration and execution.",
    },
    {
      id: "proof-01",
      start: 199.547,
      end: 210.094,
      duration: 10.547,
      visual: "STUDIO_GENERATED_WORKING_PRODUCT_PROOF",
      required_capabilities: ["marketing", "operations", "finance", "pest_control_operations", "healthcare_operations"],
      generation_direction: "Create fresh industry-specific cinematic business proof grounded in real Avantiqo capability contracts. No dashboards or reused product screenshots.",
      spoken_meaning: "The platform is already working, multi-company and cross-industry by design.",
    },
    {
      id: "strategy-01",
      start: 210.094,
      end: 219.375,
      duration: 9.281,
      visual: "STUDIO_GENERATED_VERTICAL_ENTRY_HORIZONTAL_EXPANSION",
      required_capabilities: ["operations", "finance", "people", "supply_chain", "integrations"],
      generation_direction: "Start inside one painful real workflow, then expand through fresh cinematic business moments across the same organization without reverting to UI montage.",
      spoken_meaning: "Enter through one painful workflow, prove value, then expand across the same platform.",
    },
    {
      id: "close-01",
      start: 219.375,
      end: 222.328,
      duration: 2.953,
      visual: "FOUNDER",
      spoken_meaning: "We are not building another business application.",
    },
    {
      id: "close-02",
      start: 222.328,
      end: 226.125,
      duration: 3.797,
      visual: "FOUNDER",
      spoken_meaning: "We are building the system businesses will operate through.",
    },
    {
      id: "close-03",
      start: 226.125,
      end: 226.547,
      duration: 0.422,
      visual: "APPROVED_3D_AVANTIQO_LOGO",
      spoken_meaning: "Avantiqo.",
    },
    {
      id: "close-04",
      start: 226.547,
      end: 229.5,
      duration: 2.953,
      visual: "APPROVED_3D_AVANTIQO_LOGO_FINAL_HOLD",
      spoken_meaning: "One operating system for the intelligent enterprise.",
    },
  ],
  founder_visible_windows: [
    { key: "founder-mid-integration", start: 136.266, end: 140.062, duration: 3.797 },
    { key: "founder-mid-ai", start: 177.188, end: 183.516, duration: 6.328 },
    { key: "founder-close", start: 219.375, end: 226.125, duration: 6.75 },
  ],
  end_card: {
    logo_source: "APPROVED_3D_LOGO_REVEAL_OUTPUT",
    start: 226.125,
    end: 229.5,
    duration: 3.375,
    text_policy: "NO_EXTRA_COPY_BEYOND_LOCKED_BRAND_CLOSE",
  },
});

export default AVANTIQO_INVESTOR_FINAL_ACT_PLAN;
