export const AVANTIQO_INVESTOR_FINAL_ACT_PLAN = Object.freeze({
  contract: "AVANTIQO_INVESTOR_FINAL_ACT_V1",
  audio_source: "LOCKED_CEDAR_V5_229_5_SECONDS",
  audio_start_seconds: 136.266,
  audio_end_seconds: 229.5,
  target_duration_seconds: 93.234,
  source_policy: "AUTHENTIC_AVANTIQO_UI_PLUS_APPROVED_FOUNDER_ONLY",
  founder_identity_policy: "APPROVED_GEMINI_FOUNDER_MOTION_ONLY",
  synthetic_product_ui_allowed: false,
  semantic_sync_required: true,
  beats: [
    {
      id: "integration-01",
      start: 136.266,
      end: 140.062,
      duration: 3.797,
      visual: "FOUNDER",
      spoken_meaning: "And the important part is what happens between them.",
    },
    {
      id: "integration-02",
      start: 140.062,
      end: 157.359,
      duration: 17.297,
      visual: "SALE_TO_FINANCE_TO_SUPPLY_TO_PEOPLE_FLOW",
      authentic_ui: [
        "general_ledger",
        "supply_chain",
        "payroll_control_center",
        "employee_directory",
        "compliance_or_control_surface",
      ],
      spoken_meaning: "Show the exact operating chain as each business function is named.",
    },
    {
      id: "channels-01",
      start: 157.359,
      end: 168.328,
      duration: 10.969,
      visual: "MULTI_INTERFACE_ONE_TRUTH",
      authentic_ui: [
        "customer_communications",
        "employee_directory",
        "supplier_or_supply_chain",
        "operations_management",
      ],
      spoken_meaning: "Different interfaces, same operating system and underlying truth.",
    },
    {
      id: "channels-02",
      start: 168.328,
      end: 177.188,
      duration: 8.859,
      visual: "INTEGRATIONS",
      authentic_ui: ["integrations_connected_services"],
      spoken_meaning: "Websites, communications, commerce and external services extend outward while organization context remains central.",
    },
    {
      id: "ai-01",
      start: 177.188,
      end: 183.516,
      duration: 6.328,
      visual: "FOUNDER",
      spoken_meaning: "AI moves from answering questions to coordinating real work.",
    },
    {
      id: "ai-02",
      start: 183.516,
      end: 196.172,
      duration: 12.656,
      visual: "GOVERNED_AI_CONTEXT",
      authentic_ui: [
        "organization_intelligence",
        "finance_governance_accounting_settings",
        "operations_access_control",
        "approval_or_evidence_backed_attention",
      ],
      spoken_meaning: "Context, permissions, workflows and accountability are shown as the governance layer around AI.",
    },
    {
      id: "ai-03",
      start: 196.172,
      end: 199.547,
      duration: 3.375,
      visual: "AVANTIQO_INTELLIGENCE",
      spoken_meaning: "It can begin to understand the business itself.",
    },
    {
      id: "proof-01",
      start: 199.547,
      end: 210.094,
      duration: 10.547,
      visual: "AUTHENTIC_WORKING_PRODUCT_PROOF",
      authentic_ui: [
        "marketing",
        "operations_command_center",
        "general_ledger",
        "pest_control_operations",
        "healthcare_operations",
      ],
      spoken_meaning: "The platform is already working, multi-company and cross-industry by design.",
    },
    {
      id: "strategy-01",
      start: 210.094,
      end: 219.375,
      duration: 9.281,
      visual: "VERTICAL_ENTRY_HORIZONTAL_EXPANSION",
      authentic_ui: [
        "pest_control_operations",
        "restaurant_operations",
        "finance",
        "people",
        "supply_chain",
        "integrations_connected_services",
      ],
      spoken_meaning: "Enter through one painful workflow, prove value, then expand across the same platform.",
    },
    {
      id: "close-01",
      start: 219.375,
      end: 222.328,
      duration: 2.953,
      visual: "FOUNDER",
      spoken_meaning: "We are not building another business application.",
    },
    {
      id: "close-02",
      start: 222.328,
      end: 226.125,
      duration: 3.797,
      visual: "FOUNDER",
      spoken_meaning: "We are building the system businesses will operate through.",
    },
    {
      id: "close-03",
      start: 226.125,
      end: 226.547,
      duration: 0.422,
      visual: "APPROVED_3D_AVANTIQO_LOGO",
      spoken_meaning: "Avantiqo.",
    },
    {
      id: "close-04",
      start: 226.547,
      end: 229.5,
      duration: 2.953,
      visual: "APPROVED_3D_AVANTIQO_LOGO_FINAL_HOLD",
      spoken_meaning: "One operating system for the intelligent enterprise.",
    },
  ],
  founder_visible_windows: [
    { key: "founder-mid-integration", start: 136.266, end: 140.062, duration: 3.797 },
    { key: "founder-mid-ai", start: 177.188, end: 183.516, duration: 6.328 },
    { key: "founder-close", start: 219.375, end: 226.125, duration: 6.75 },
  ],
  end_card: {
    logo_source: "APPROVED_3D_LOGO_REVEAL_OUTPUT",
    start: 226.125,
    end: 229.5,
    duration: 3.375,
    text_policy: "NO_EXTRA_COPY_BEYOND_LOCKED_BRAND_CLOSE",
  },
});

export default AVANTIQO_INVESTOR_FINAL_ACT_PLAN;
