import crypto from "node:crypto";

export const AVANTIQO_LENS_SENSOR_PROFILE_CONTRACT="AVANTIQO_LENS_SENSOR_PROFILE_V1";
function text(v){return String(v??"").trim();}
function finite(v,f=0,min=-Infinity,max=Infinity){const n=Number(v);return Math.max(min,Math.min(max,Number.isFinite(n)?n:f));}
function stable(v){if(Array.isArray(v))return v.map(stable);if(!v||typeof v!=="object")return v;return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");}
export function resolveLensSensorProfile({profile={},render_evidence={}}={}){const lens=profile.lens||profile;const sensor=profile.sensor||{};const shutter=profile.shutter||{};const blockers=[];const renderTime={focus_breathing:finite(lens.focus_breathing_percent,0,0,20),bokeh_blades:Math.round(finite(lens.bokeh_blades,0,0,24)),anamorphic_squeeze:finite(lens.anamorphic_squeeze,1,.5,2.5),shutter_angle:finite(shutter.angle_degrees,180,1,360)};if(renderTime.focus_breathing>0&&render_evidence.focus_breathing_authored!==true)blockers.push("OPTICAL_FOCUS_BREATHING_RENDER_STAGE_REQUIRED");if(renderTime.bokeh_blades>0&&render_evidence.bokeh_authored!==true)blockers.push("OPTICAL_BOKEH_RENDER_STAGE_REQUIRED");if(Math.abs(renderTime.anamorphic_squeeze-1)>.01&&render_evidence.anamorphic_projection_authored!==true)blockers.push("OPTICAL_ANAMORPHIC_RENDER_STAGE_REQUIRED");if(Math.abs(renderTime.shutter_angle-180)>.01&&render_evidence.shutter_motion_blur_authored!==true)blockers.push("OPTICAL_SHUTTER_RENDER_STAGE_REQUIRED");const body={contract:AVANTIQO_LENS_SENSOR_PROFILE_CONTRACT,lens:{profile_id:text(lens.profile_id)||"CUSTOM_LENS",focal_length_mm:finite(lens.focal_length_mm,50,8,300),sensor_width_mm:finite(lens.sensor_width_mm,36,1,100),k1:finite(lens.k1??lens.lens_k1,-.018,-.3,.3),k2:finite(lens.k2??lens.lens_k2,.006,-.2,.2),k3:finite(lens.k3,0,-.1,.1),chromatic_shift_pixels:finite(lens.chromatic_shift_pixels,.55,0,8),vignette_angle:finite(lens.vignette_angle,.52,.1,1.5),bloom_sigma:finite(lens.bloom_sigma,2.2,0,16),bloom_strength:finite(lens.bloom_strength,.065,0,.4),halation_sigma:finite(lens.halation_sigma,3.2,0,20),halation_strength:finite(lens.halation_strength,.035,0,.25),veiling_glare:finite(lens.veiling_glare,0,0,.2)},sensor:{profile_id:text(sensor.profile_id)||"CUSTOM_SENSOR",grain_strength:finite(sensor.grain_strength??profile.grain_strength,3.2,0,24),noise_floor:finite(sensor.noise_floor,0,0,12),dynamic_range_stops:finite(sensor.dynamic_range_stops,14,6,20),highlight_rolloff:finite(sensor.highlight_rolloff,.65,0,1)},render_time:renderTime,render_evidence,policy:{post_distortion_allowed:true,post_chromatic_aberration_allowed:true,post_halation_allowed:true,post_bloom_allowed:true,post_grain_allowed:true,focus_breathing_must_be_render_authored:true,bokeh_must_be_render_authored:true,shutter_motion_blur_must_be_render_authored:true,anamorphic_projection_must_be_render_authored:true,color_grade_forbidden:true}};return{...body,status:blockers.length?"BLOCKED":"READY",blockers,profile_hash:hash(body)};}
export const CreativeLensSensorProfileRuntime=Object.freeze({contract:AVANTIQO_LENS_SENSOR_PROFILE_CONTRACT,resolve:resolveLensSensorProfile});
