import { defineCapability } from "@/lib/ubte/runtime/contracts/CapabilityManifest";
import {
  loadOperatorOrganizationalContext,
} from "@/lib/operator/runtime/OperatorOrganizationalContextRuntime";

function text(value) {
  return String(value ?? "").trim();
}

export function createOperatorOrganizationalContextCapability() {
  const manifest = defineCapability({
    domain: "platform",
    capability: "organizational_context",
    action: "read",
    name: "Organizational Context",
    document: "organizational_context",
    description:
      "Read compact organization memory from registered organization data, existing organization profile data, relevant same-user goals, and prior verified Operator execution history. Historical context informs reasoning but does not replace fresh business reads.",
    permissions: [],
    events: [],
    tags: [
      "organization",
      "context",
      "memory",
      "goals",
      "decisions",
      "history",
      "read",
    ],
    operatorAliases: [
      "organization context",
      "business context",
      "company context",
      "prior goals",
      "previous decisions",
      "what do we know about this organization",
    ],
    operatorExamples: [
      "Use what we already know about this organization",
      "What were we working toward before?",
      "What relevant decisions have we already made?",
    ],
    transactional: false,
    aiEnabled: true,
    operatorEnabled: true,
    operatorMode: "read",
    operatorAutoExecute: true,
    operatorRequiresConfirmation: false,
    contextScope: "organization",
    risk: "low",
    reversible: true,
    inputSchema: {
      type: "object",
      properties: {
        focus: {
          type: "string",
          description:
            "Optional current subject or objective used only to rank relevant prior organization memory.",
        },
      },
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        organization: {
          type: "object",
          description: "Stored organization identity and operating context.",
        },
        registered_industries: {
          type: "array",
          description: "Industries registered to the organization at runtime.",
          items: { type: "string" },
        },
        profile: {
          type: ["object", "null"],
          description:
            "Existing organization business profile data when one is already stored. No fallback profile is generated by this capability.",
        },
        relevant_prior_goals: {
          type: "array",
          description:
            "Relevant prior goals and decisions from the same Operator party only.",
          items: { type: "object" },
        },
        relevant_verified_history: {
          type: "array",
          description:
            "Relevant historical Operator execution evidence for the same party.",
          items: { type: "object" },
        },
        generated_at: {
          type: "string",
          description: "Timestamp when this context snapshot was assembled.",
        },
      },
      additionalProperties: false,
    },
  });

  function authorize({ context }) {
    return Boolean(
      text(context?.organizationId) &&
      text(context?.metadata?.partyId),
    );
  }

  async function execute({ context, payload = {} }) {
    const partyId = text(context?.metadata?.partyId);
    if (!partyId) throw new Error("OPERATOR_ORGANIZATIONAL_CONTEXT_PARTY_REQUIRED");

    const contextSnapshot = await loadOperatorOrganizationalContext({
      organizationId: context.organizationId,
      partyId,
      message: text(payload.focus),
      projectState: {},
    });

    return contextSnapshot || {
      version: 1,
      organization: null,
      registered_industries: [],
      profile: null,
      profile_updated_at: null,
      relevant_prior_goals: [],
      relevant_verified_history: [],
      generated_at: new Date().toISOString(),
    };
  }

  return { manifest, authorize, execute };
}

export default createOperatorOrganizationalContextCapability;
