export const AVANTIQO_ATTACHMENT_ANALYSIS_VERSION =
  "AVANTIQO_BUSINESS_PARTNER_ATTACHMENT_ANALYSIS_V4";

export const AVANTIQO_ATTACHMENT_ANALYSIS_AUTHORIZATION_EFFECT = "NONE";

export default AVANTIQO_ATTACHMENT_ANALYSIS_VERSION;
