import { ProductionTaskRuntime } from "@/lib/operations/tasks/runtime/ProductionTaskRuntime";

export const CREATIVE_TEMPORAL_4K_REVIEW_TASK_CONTRACT="CREATIVE_TEMPORAL_4K_REVIEW_TASK_V1";
function text(v){return String(v??"").trim();}
function eligible(task={}){return text(task.capability||task.service_code)==="ai.video.upscale"&&text(task.status).toUpperCase()==="COMPLETED"&&text(task.metadata?.contract)==="CREATIVE_TEMPORAL_4K_DELIVERY_TASK_V1";}
export async function ensureTemporal4KReviewTasks({organization_id,creative_project_id}={}){
  if(!organization_id||!creative_project_id)throw new Error("TEMPORAL_4K_REVIEW_SCOPE_REQUIRED");
  const tasks=await ProductionTaskRuntime.list({organization_id,creative_project_id});const created=[];const existing=[];
  for(const source of tasks.filter(eligible)){
    if(source.metadata?.automated_perceptual_validation_passed===true)continue;
    const prior=tasks.find(t=>text(t.metadata?.contract)==="GENERATED_MEDIA_PERCEPTUAL_REVIEW_V1"&&text(t.metadata?.source_generation_task_id)===text(source.id));if(prior){existing.push(prior);continue;}
    const review=await ProductionTaskRuntime.create({organization_id,creative_project_id,production_graph_id:null,scene_id:null,shot_id:null,type:"EXECUTE_CAPABILITY",status:"WAITING",title:"Review Temporal 4K Master",description:"Review the actual temporal 4K master for temporal stability, detail crawl, identity drift, ringing, over-sharpening, duration/frame preservation and delivery quality.",service_id:"ai.image.analyze",service_code:"ai.image.analyze",capability:"ai.image.analyze",provider_id:null,priority:91,depends_on:[source.id],input:{media_kind:"VIDEO",requirements:{source_generation_task_id:source.id,generated_output_required:true,deterministic_media_inspection_required:true,expected_contract:{media_kind:"VIDEO",thresholds:{minimum_overall_score:92,minimum_continuity_score:94,minimum_artifact_score:94}},thresholds:{minimum_overall_score:92,minimum_continuity_score:94,minimum_artifact_score:94},temporal_4k_review:true,temporal_flicker_absent_required:true,detail_crawl_absent_required:true,identity_drift_absent_required:true,edge_ringing_absent_required:true,over_sharpening_absent_required:true,frame_count_preserved_required:true,duration_preserved_required:true},provider_parameters:{response_format:{type:"json_object"},source_generation_task_id:source.id,media_kind:"VIDEO"}},cost:{estimated:0,actual:0,currency:source.cost?.currency||null,approved:false},timing:{estimated_seconds:0},review:{required:false,approved:false},metadata:{contract:"GENERATED_MEDIA_PERCEPTUAL_REVIEW_V1",source_generation_task_id:source.id,source_node_type:"TEMPORAL_4K_MASTER",media_kind:"VIDEO",automated_validation_required:true,quality_gate:true,release_candidate:true,production_step_id:"temporal-4k-quality",production_step_index:91,temporal_4k_review_task_contract:CREATIVE_TEMPORAL_4K_REVIEW_TASK_CONTRACT}});created.push(review);
  }
  return{contract:CREATIVE_TEMPORAL_4K_REVIEW_TASK_CONTRACT,created,existing,total:created.length+existing.length};
}
export const CreativeTemporal4KReviewTaskRuntime=Object.freeze({contract:CREATIVE_TEMPORAL_4K_REVIEW_TASK_CONTRACT,ensure:ensureTemporal4KReviewTasks});
