"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { RefreshCw } from "lucide-react";
import { HotelEmptyState, HotelError, HotelField, HotelMetric, HotelPrimaryAction, HotelSecondaryAction, HotelSection, HotelStatusPill, HotelWorkspaceShell, hotelInputClass, hotelTextareaClass } from "@/components/workspace/hotel/HotelWorkspaceUI";

const REQUEST_TYPES = ["TRANSPORT", "DINING", "TOUR", "LUGGAGE", "AMENITY", "OTHER"];
const guestName = (request) => request?.hotel_guests?.full_name || [request?.hotel_guests?.first_name, request?.hotel_guests?.last_name].filter(Boolean).join(" ") || "Guest";

export default function ConciergeOperationsPage() {
  const params = useParams(); const organizationId = params?.organizationId || "";
  const [requests, setRequests] = useState([]); const [properties, setProperties] = useState([]); const [guests, setGuests] = useState([]); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState(null); const [creating, setCreating] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ propertyId: "", guestId: "", requestType: "TRANSPORT", details: "" });
  const load = useCallback(async () => { if (!organizationId) return; setLoading(true); setError(""); try { const q = `?organizationId=${encodeURIComponent(organizationId)}`; const [rr, pr, gr] = await Promise.all([fetch(`/api/hotel/concierge/list${q}`, { cache: "no-store", credentials: "include" }), fetch(`/api/hotel/properties/list${q}`, { cache: "no-store", credentials: "include" }), fetch(`/api/hotel/guests/list${q}`, { cache: "no-store", credentials: "include" })]); const [rd, pd, gd] = await Promise.all([rr.json(), pr.json(), gr.json()]); if (!rr.ok) throw new Error(rd.error || "Unable to load guest requests"); if (!pr.ok) throw new Error(pd.error || "Unable to load properties"); if (!gr.ok) throw new Error(gd.error || "Unable to load guests"); setRequests(rd.requests || []); setProperties(pd.properties || []); setGuests(gd.guests || []); setForm((c) => ({ ...c, propertyId: c.propertyId || pd.properties?.[0]?.id || "" })); } catch (e) { setError(e.message || "Unable to load guest requests"); } finally { setLoading(false); } }, [organizationId]);
  useEffect(() => { load(); }, [load]);
  const grouped = useMemo(() => ({ pending: requests.filter((r) => r.status === "PENDING"), inProgress: requests.filter((r) => r.status === "IN_PROGRESS"), completed: requests.filter((r) => ["COMPLETED", "CANCELLED"].includes(r.status)) }), [requests]);
  async function createRequest() { if (!form.propertyId || !form.guestId || !form.requestType) { setError("Property, guest and request type are required"); return; } setCreating(true); setError(""); try { const r = await fetch("/api/hotel/concierge/create", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, ...form }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to create guest request"); setForm((c) => ({ ...c, guestId: "", details: "" })); await load(); } catch (e) { setError(e.message); } finally { setCreating(false); } }
  async function transition(requestId, action) { setBusyId(requestId); setError(""); try { const r = await fetch("/api/hotel/concierge/update", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, requestId, action }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to update guest request"); await load(); } catch (e) { setError(e.message); } finally { setBusyId(null); } }
  const active = [...grouped.pending, ...grouped.inProgress];
  return <HotelWorkspaceShell organizationId={organizationId} active="concierge" title="Guest Requests" subtitle="Turn every guest promise into visible, accountable service work with a clear start and completion handoff." actions={<HotelSecondaryAction onClick={load} disabled={loading}><RefreshCw size={9} className={loading ? "animate-spin" : ""}/>Refresh</HotelSecondaryAction>}>
    <HotelError>{error}</HotelError>
    <section className="grid grid-cols-3 gap-3"><HotelMetric label="Pending" value={grouped.pending.length} detail="Waiting for service" attention={grouped.pending.length > 0}/><HotelMetric label="In progress" value={grouped.inProgress.length} detail="Promises being delivered" attention={grouped.inProgress.length > 0}/><HotelMetric label="Closed" value={grouped.completed.length} detail="Completed or cancelled"/></section>
    <HotelSection eyebrow="New promise" title="Capture guest request" detail="Record the guest, property and request before service begins."><div className="grid gap-3 p-4 md:grid-cols-4"><HotelField label="Property"><select className={hotelInputClass} value={form.propertyId} onChange={(e) => setForm((c) => ({ ...c, propertyId: e.target.value }))}><option value="">Select property</option>{properties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></HotelField><HotelField label="Guest"><select className={hotelInputClass} value={form.guestId} onChange={(e) => setForm((c) => ({ ...c, guestId: e.target.value }))}><option value="">Select guest</option>{guests.map((g) => <option key={g.id} value={g.id}>{g.full_name || [g.first_name, g.last_name].filter(Boolean).join(" ") || "Guest"}</option>)}</select></HotelField><HotelField label="Request type"><select className={hotelInputClass} value={form.requestType} onChange={(e) => setForm((c) => ({ ...c, requestType: e.target.value }))}>{REQUEST_TYPES.map((t) => <option key={t} value={t}>{t.replaceAll("_", " ")}</option>)}</select></HotelField><div className="flex items-end"><HotelPrimaryAction onClick={createRequest} disabled={creating}>{creating ? "Creating…" : "Create request"}</HotelPrimaryAction></div><div className="md:col-span-4"><HotelField label="Details"><textarea className={hotelTextareaClass} value={form.details} onChange={(e) => setForm((c) => ({ ...c, details: e.target.value }))} placeholder="What did we promise the guest?"/></HotelField></div></div></HotelSection>
    <HotelSection eyebrow="Open promises" title="Guest-service work queue" detail="Pending requests first, followed by work already underway.">{loading ? <HotelEmptyState>Loading guest requests…</HotelEmptyState> : active.length ? <div className="divide-y divide-black/[0.055]">{active.map((request) => <div key={request.id} className="grid gap-2 px-4 py-3 md:grid-cols-[140px_minmax(150px,1fr)_150px_minmax(180px,1.2fr)_150px] md:items-center md:px-5"><div className="text-[8px] font-semibold text-[#5F5952]">{String(request.request_type || "REQUEST").replaceAll("_", " ")}</div><div className="text-[9px] font-semibold text-[#403C37]">{guestName(request)}</div><HotelStatusPill value={request.status}/><div className="truncate text-[8px] text-[#807A72]">{request.details || request.hotel_properties?.name || "Guest request"}</div><div className="flex gap-1">{request.status === "PENDING" ? <><HotelPrimaryAction onClick={() => transition(request.id, "START")} disabled={busyId === request.id}>Start</HotelPrimaryAction><HotelSecondaryAction onClick={() => transition(request.id, "CANCEL")} disabled={busyId === request.id}>Cancel</HotelSecondaryAction></> : <HotelPrimaryAction onClick={() => transition(request.id, "COMPLETE")} disabled={busyId === request.id}>Complete</HotelPrimaryAction>}</div></div>)}</div> : <HotelEmptyState>No active guest promises.</HotelEmptyState>}</HotelSection>
  </HotelWorkspaceShell>;
}
