import crypto from "node:crypto";
import { getServiceSupabase } from "@/lib/shared/supabase/service";
import { creativeStorageUri } from "@/lib/creative/assets/storage/CreativePrivateStorageRuntime";

export const AVANTIQO_PRODUCTION_STAGING_CONTRACT="AVANTIQO_PRODUCTION_STAGING_V1";
function text(v){return String(v??"").trim();}
function list(v){return Array.isArray(v)?v.filter(Boolean):[];}
function safe(v){return text(v).replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"asset";}
function checksum(buffer){return crypto.createHash("sha256").update(buffer).digest("hex");}
export function buildStagingManifest({organization_id,creative_project_id,job_id,items=[]}={}){if(!organization_id||!creative_project_id||!text(job_id))throw new Error("PRODUCTION_STAGING_SCOPE_REQUIRED");const normalized=list(items).map((item,index)=>({item_id:text(item.item_id||item.id||`item-${index+1}`),role:text(item.role||"FRAME").toUpperCase(),frame:item.frame==null?null:Number(item.frame),file_name:safe(item.file_name||item.name||`item-${index+1}`),mime_type:text(item.mime_type||"application/octet-stream"),checksum:text(item.checksum)||null,bytes:Number(item.bytes||0),storage_reference:text(item.storage_reference)||null}));return{contract:AVANTIQO_PRODUCTION_STAGING_CONTRACT,organization_id,creative_project_id,job_id:text(job_id),base_path:`${organization_id}/${creative_project_id}/production-cache/${safe(job_id)}`,items:normalized,policy:{checksum_required:true,immutable_frame_cache:true,proxy_and_source_separated:true,staging_before_worker_dispatch:true,content_addressable_reuse:true}};}
export async function uploadStagingBuffer({manifest,item_id,buffer,bucket="creative-private"}={}){if(manifest?.contract!==AVANTIQO_PRODUCTION_STAGING_CONTRACT||!Buffer.isBuffer(buffer))throw new Error("PRODUCTION_STAGING_UPLOAD_SCOPE_REQUIRED");const item=manifest.items.find(x=>x.item_id===item_id);if(!item)throw new Error("PRODUCTION_STAGING_ITEM_NOT_FOUND");const sha=checksum(buffer);if(item.checksum&&item.checksum!==sha)throw new Error("PRODUCTION_STAGING_CHECKSUM_MISMATCH");const storagePath=`${manifest.base_path}/${sha.slice(0,2)}/${sha}-${safe(item.file_name)}`;const supabase=getServiceSupabase();const {error}=await supabase.storage.from(bucket).upload(storagePath,buffer,{contentType:item.mime_type,upsert:false});if(error&& !String(error.message||"").toLowerCase().includes("already exists"))throw error;return{...item,checksum:sha,bytes:buffer.length,storage_reference:creativeStorageUri(bucket,storagePath),storage_path:storagePath,reused:Boolean(error)};}
export function verifyStagingManifest({manifest,items=[]}={}){if(manifest?.contract!==AVANTIQO_PRODUCTION_STAGING_CONTRACT)throw new Error("PRODUCTION_STAGING_MANIFEST_REQUIRED");const map=new Map(list(items).map(i=>[text(i.item_id),i]));const failures=[];for(const expected of manifest.items){const actual=map.get(expected.item_id);if(!actual?.storage_reference)failures.push({item_id:expected.item_id,reason:"STAGED_REFERENCE_REQUIRED"});else if(!text(actual.checksum))failures.push({item_id:expected.item_id,reason:"STAGED_CHECKSUM_REQUIRED"});else if(expected.checksum&&expected.checksum!==actual.checksum)failures.push({item_id:expected.item_id,reason:"STAGED_CHECKSUM_MISMATCH"});}return{contract:"AVANTIQO_PRODUCTION_STAGING_VERIFICATION_V1",passed:failures.length===0,failures,item_count:manifest.items.length};}
export const CreativeProductionStagingRuntime=Object.freeze({contract:AVANTIQO_PRODUCTION_STAGING_CONTRACT,manifest:buildStagingManifest,upload:uploadStagingBuffer,verify:verifyStagingManifest});
