-- Historical production migration parity marker.
-- This version was applied directly to production before its SQL was committed to Git.
-- Superseded by 20260905040500_hotel_atomic_gateway_refund_finance.sql.
-- Intentionally no-op: retained only so local migration history matches the applied remote version.
