-- AVANTIQO PRODUCTION MIGRATION HISTORY MARKER
--
-- Migration version: 20260718200000
--
-- This version is recorded as applied in the production Supabase
-- migration history. Its original source migration was later retired
-- after the schema was superseded by canonical migrations.
--
-- This file intentionally executes no SQL. It preserves the production
-- migration timestamp locally so Supabase can compare local and remote
-- migration history without deleting a valid production history record.
