-- Historical production migration parity marker.
-- This version was applied directly to production before its SQL was committed to Git.
-- Superseded by the canonical Hotel payment, Finance deposit posting, and refund convergence migrations.
-- Intentionally no-op: retained only so local migration history matches the applied remote version.
