-- Historical migration marker.
-- Already applied to the linked production database as 20260809065251.
-- Intentionally a no-op in source control so migration history remains aligned without replaying live DDL.
