alter table public.orders
add column if not exists updated_at timestamptz,
add column if not exists void_reason text,
add column if not exists voided_by text,
add column if not exists voided_at timestamptz,
add column if not exists discount_amount numeric default 0,
add column if not exists discount_type text,
add column if not exists discount_reason text,
add column if not exists discount_approved_by text,
add column if not exists reopened_by text,
add column if not exists reopen_reason text,
add column if not exists reopened_at timestamptz;

alter table public.table_sessions
add column if not exists updated_at timestamptz,
add column if not exists opened_by text,
add column if not exists paid_at timestamptz,
add column if not exists closed_at timestamptz,
add column if not exists payment_method text,
add column if not exists paid_amount numeric default 0,
add column if not exists final_total numeric default 0,
add column if not exists service_charge_amount numeric default 0,
add column if not exists vat_amount numeric default 0,
add column if not exists discount_amount numeric default 0,
add column if not exists merged_into_session_id uuid;

alter table public.restaurant_tables
add column if not exists active_session_id uuid,
add column if not exists updated_at timestamptz;

alter table public.payment_transactions
add column if not exists updated_at timestamptz,
add column if not exists refund_reason text,
add column if not exists refunded_by text,
add column if not exists refunded_at timestamptz;

create table if not exists public.order_item_modifiers (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  order_item_id uuid not null,
  modifier_name text not null,
  modifier_price numeric default 0,
  quantity numeric default 1,
  total numeric default 0,
  added_by text,
  created_at timestamptz default now(),
  updated_at timestamptz
);

alter table public.order_items
add column if not exists updated_at timestamptz;

alter table public.kitchen_tickets
add column if not exists updated_at timestamptz,
add column if not exists sent_at timestamptz,
add column if not exists served_at timestamptz,
add column if not exists voided_by text,
add column if not exists void_reason text,
add column if not exists voided_at timestamptz,
add column if not exists reopened_by text,
add column if not exists reopen_reason text,
add column if not exists reopened_at timestamptz,
add column if not exists archived boolean default false,
add column if not exists archived_by text,
add column if not exists archive_reason text,
add column if not exists archived_at timestamptz,
add column if not exists restored_by text,
add column if not exists restore_reason text,
add column if not exists restored_at timestamptz,
add column if not exists duplicated_from_ticket_id uuid,
add column if not exists duplicated_by text,
add column if not exists duplicate_reason text,
add column if not exists merged_into_ticket_id uuid,
add column if not exists merged_by text,
add column if not exists merge_reason text,
add column if not exists merged_at timestamptz,
add column if not exists split_from_ticket_id uuid,
add column if not exists split_by text,
add column if not exists split_reason text;

create table if not exists public.kitchen_queue (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  kitchen_ticket_id uuid,
  order_id uuid,
  order_item_id uuid,
  table_number text,
  dish_name text,
  quantity numeric default 1,
  status text default 'WAITING',
  priority text default 'NORMAL',
  course text default 'MAIN',
  station text,
  chef_id uuid,
  chef_name text,
  created_at timestamptz default now(),
  updated_at timestamptz,
  started_at timestamptz,
  started_by text,
  completed_at timestamptz,
  completed_by text,
  ready_at timestamptz,
  ready_by text,
  served_at timestamptz,
  served_by text,
  bumped_at timestamptz,
  bumped_by text,
  recalled_at timestamptz,
  recalled_by text,
  rejected_at timestamptz,
  rejected_by text,
  reject_reason text,
  requeued_at timestamptz,
  requeued_by text,
  requeue_reason text,
  held_at timestamptz,
  held_by text,
  hold_reason text,
  delayed_at timestamptz,
  delayed_by text,
  delay_reason text,
  delay_minutes numeric,
  delayed_until timestamptz,
  resumed_at timestamptz,
  resumed_by text,
  cancelled_at timestamptz,
  cancelled_by text,
  cancel_reason text,
  returned_at timestamptz,
  returned_by text,
  return_reason text,
  refired_at timestamptz,
  refired_by text,
  refire_reason text,
  expedited boolean default false,
  expedited_at timestamptz,
  expedited_by text,
  expedite_reason text,
  prioritized_at timestamptz,
  prioritized_by text,
  priority_reason text,
  reassigned_at timestamptz,
  reassigned_by text,
  reassign_reason text,
  assigned_at timestamptz,
  assigned_by text,
  claimed_at timestamptz,
  claimed_by text,
  released_at timestamptz,
  released_by text,
  release_reason text,
  unassigned_at timestamptz,
  unassigned_by text,
  unassign_reason text,
  transferred_at timestamptz,
  transferred_by text,
  transfer_reason text,
  previous_chef_id uuid,
  previous_chef_name text,
  auto_assigned boolean default false,
  auto_assigned_at timestamptz,
  auto_assigned_by text,
  archived boolean default false,
  archived_at timestamptz,
  archived_by text,
  archive_reason text,
  restored_at timestamptz,
  restored_by text,
  restore_reason text,
  duplicated_from_queue_id uuid
);

create index if not exists idx_kitchen_queue_tenant_status
on public.kitchen_queue (tenant_id, status);

create index if not exists idx_kitchen_queue_ticket
on public.kitchen_queue (tenant_id, kitchen_ticket_id);

create index if not exists idx_kitchen_queue_order
on public.kitchen_queue (tenant_id, order_id);
