-- Historical production migration parity marker.
-- This version was applied directly to production before its SQL was committed to Git.
-- Superseded by 20260905034000_hotel_guest_party_atomic_linkage.sql and 20260923052734_hotel_integrity_scope_guards.sql.
-- Intentionally no-op: retained only so local migration history matches the applied remote version.
