-- Historical production migration parity marker.
-- This version was applied directly to production before its SQL was committed to Git.
-- Superseded by 20260905154500_hotel_group_offer_hot_path_indexes.sql.
-- Intentionally no-op: retained only so local migration history matches the applied remote version.
