import { musicSpatialAutomationValueAt } from "./MusicSpatialMixMathRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_OBJECT_MOTION_ACOUSTICS_V2";
const OCCLUSION_MATERIALS=Object.freeze({AIR:{min_cutoff_hz:18000,max_attenuation_db:0},CURTAIN:{min_cutoff_hz:6500,max_attenuation_db:5},GLASS:{min_cutoff_hz:5200,max_attenuation_db:7},WOOD:{min_cutoff_hz:3200,max_attenuation_db:10},VEHICLE_BODY:{min_cutoff_hz:2200,max_attenuation_db:14},BRICK:{min_cutoff_hz:1500,max_attenuation_db:18},CONCRETE:{min_cutoff_hz:1100,max_attenuation_db:22},METAL:{min_cutoff_hz:900,max_attenuation_db:24}});
function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,min,max,f=0){return Math.max(min,Math.min(max,finite(v,f)));}
function sampleLinear(data,index){if(index<0||index>=data.length-1)return index>=0&&index<data.length?finite(data[Math.floor(index)],0):0;const i=Math.floor(index),f=index-i;return finite(data[i],0)*(1-f)+finite(data[i+1],0)*f;}
function laneByParameter(lanes=[],parameter){return (lanes||[]).find(lane=>lane.enabled!==false&&lane.parameter===parameter)||null;}
function distanceLane(lanes=[]){return laneByParameter(lanes,"spatial:distance_meters");}
function distanceAt(lane,time,fallback){return Math.max(.1,musicSpatialAutomationValueAt(lane,time,fallback));}

function materialProfile(value){const id=String(value||"AIR").trim().toUpperCase();return{material:OCCLUSION_MATERIALS[id]?id:"AIR",...(OCCLUSION_MATERIALS[id]||OCCLUSION_MATERIALS.AIR)};}
function applyWorldOcclusion(left,right,sampleRate,spatial,lanes,timelineOffset){const frames=Math.max(left.length,right.length),l=new Float32Array(frames),r=new Float32Array(frames),immersive=spatial.immersive||{},lane=laneByParameter(lanes,"spatial:occlusion_percent"),base=clamp(immersive.occlusion_percent,0,100,0),profile=materialProfile(immersive.obstruction_material||spatial.obstruction_material),enabled=immersive.occlusion_enabled===true||base>0||Boolean(lane);let stateL=0,stateR=0,minOcclusion=100,maxOcclusion=0,minCutoff=Infinity,maxAttenuation=0;if(!enabled){l.set(left);r.set(right);return{left:l,right:r,metadata:{occlusion_applied:false,obstruction_material:profile.material,min_occlusion_percent:0,max_occlusion_percent:0,min_cutoff_hz:null,max_attenuation_db:0}};}for(let i=0;i<frames;i++){const time=Math.max(0,finite(timelineOffset,0)+i/sampleRate),occ=clamp(musicSpatialAutomationValueAt(lane,time,base),0,100,base),t=occ/100,cutoff=18000+(profile.min_cutoff_hz-18000)*(t*t),attenDb=-profile.max_attenuation_db*t,gain=10**(attenDb/20),alpha=1-Math.exp((-2*Math.PI*Math.max(80,Math.min(sampleRate*.45,cutoff)))/sampleRate);stateL+=alpha*(finite(left[i],0)-stateL);stateR+=alpha*(finite(right[i],0)-stateR);l[i]=stateL*gain;r[i]=stateR*gain;minOcclusion=Math.min(minOcclusion,occ);maxOcclusion=Math.max(maxOcclusion,occ);minCutoff=Math.min(minCutoff,cutoff);maxAttenuation=Math.max(maxAttenuation,Math.abs(attenDb));}return{left:l,right:r,metadata:{occlusion_applied:true,obstruction_material:profile.material,min_occlusion_percent:Number(minOcclusion.toFixed(3)),max_occlusion_percent:Number(maxOcclusion.toFixed(3)),min_cutoff_hz:Number(minCutoff.toFixed(2)),max_attenuation_db:Number(maxAttenuation.toFixed(3)),automation_applied:Boolean(lane)}};}
function reflectionAmountAt(lanes,time,fallback){return clamp(musicSpatialAutomationValueAt(laneByParameter(lanes,"spatial:reflection_amount_percent"),time,fallback),0,100,fallback);}

function earlyReflections(left,right,sampleRate,immersive,automationLanes=[],timelineOffset=0){const base=clamp(immersive?.reflection_amount_percent,0,100,25),room=clamp(immersive?.room_size,0,1,.35),frames=Math.max(left.length,right.length),l=new Float32Array(frames),r=new Float32Array(frames),lane=laneByParameter(automationLanes,"spatial:reflection_amount_percent");if(immersive?.reflections_enabled===false||(base<=0&&!lane))return{left:l,right:r,enabled:false,taps:[],automation_applied:false};const taps=[{delay:.009+.021*room,gain:.5},{delay:.021+.047*room,gain:.3},{delay:.037+.083*room,gain:.2}].map((tap,index)=>({...tap,frames:Math.max(1,Math.round(tap.delay*sampleRate)),crossfeed:index===1}));for(const tap of taps){for(let i=tap.frames;i<frames;i++){const source=i-tap.frames,time=Math.max(0,finite(timelineOffset,0)+i/sampleRate),amount=reflectionAmountAt(automationLanes,time,base)/100,gain=amount*tap.gain;if(tap.crossfeed){l[i]+=finite(right[source],0)*gain;r[i]+=finite(left[source],0)*gain;}else{l[i]+=finite(left[source],0)*gain;r[i]+=finite(right[source],0)*gain;}}}return{left:l,right:r,enabled:true,taps:taps.map(t=>({delay_seconds:Number(t.delay.toFixed(6)),gain_at_base:Number((base/100*t.gain).toFixed(6)),crossfeed:t.crossfeed})),automation_applied:Boolean(lane)};}
export function applyMusicObjectMotionAcoustics({left,right=null,sample_rate=48000,spatial={},automation_lanes=[],timeline_offset_seconds=0}={}){const l=left||new Float32Array(0),r=right||l,frames=Math.max(l.length,r.length),rate=Math.max(1000,Math.round(finite(sample_rate,48000))),immersive=spatial.immersive||{},lane=distanceLane(automation_lanes),doppler=immersive.doppler_enabled===true,speed=Math.max(250,finite(immersive.speed_of_sound_mps,343)),propL=new Float32Array(frames),propR=new Float32Array(frames),baseDistance=Math.max(.1,finite(spatial.distance_meters,1));let maxDelay=0,minDistance=Infinity,maxDistance=0;for(let i=0;i<frames;i++){const absoluteTime=Math.max(0,finite(timeline_offset_seconds,0)+i/rate),distance=distanceAt(lane,absoluteTime,baseDistance);minDistance=Math.min(minDistance,distance);maxDistance=Math.max(maxDistance,distance);const delaySeconds=doppler?distance/speed:0;maxDelay=Math.max(maxDelay,delaySeconds);const sourceIndex=i-delaySeconds*rate;propL[i]=sampleLinear(l,sourceIndex);propR[i]=sampleLinear(r,sourceIndex);}const occluded=applyWorldOcclusion(propL,propR,rate,spatial,automation_lanes,timeline_offset_seconds),reflections=earlyReflections(occluded.left,occluded.right,rate,immersive,automation_lanes,timeline_offset_seconds);return{contract:CONTRACT,direct:{left:occluded.left,right:occluded.right},reflections,metadata:{doppler_applied:doppler,propagation_delay_mode:doppler?"DISTANCE_OVER_SPEED_OF_SOUND":"BYPASSED",speed_of_sound_mps:speed,min_distance_meters:Number((Number.isFinite(minDistance)?minDistance:baseDistance).toFixed(4)),max_distance_meters:Number(maxDistance.toFixed(4)),max_propagation_delay_seconds:Number(maxDelay.toFixed(6)),distance_automation_applied:Boolean(lane),occlusion:occluded.metadata,reflections_applied:reflections.enabled,reflection_automation_applied:reflections.automation_applied===true,reflection_taps:reflections.taps,world_acoustics_applied:occluded.metadata.occlusion_applied===true||reflections.enabled,source_audio_rewritten:false,output_length_preserved:true}};}
export const MusicObjectMotionAcousticsRuntime=Object.freeze({contract:CONTRACT,apply:applyMusicObjectMotionAcoustics});
