import { renderMusicTrackPreFaderSendOffline } from "./MusicOfflineStemRenderRuntime";
import { applyMusicSpatialSendGainAutomation, sumMusicStereoSendPair } from "./MusicSpatialMixMathRuntime.js";

function finite(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function dbToGain(db){return 10**(finite(db,0)/20);}
function deterministicNoise(seed){let value=seed>>>0;return()=>{value=(1664525*value+1013904223)>>>0;return(value/0xffffffff)*2-1;};}
function createReverbImpulse(context,decaySeconds){const duration=Math.max(.1,Math.min(12,finite(decaySeconds,2.2))),frames=Math.max(1,Math.round(context.sampleRate*duration)),buffer=context.createBuffer(2,frames,context.sampleRate),noiseL=deterministicNoise(0x41564e54),noiseR=deterministicNoise(0x49514f52);for(let c=0;c<2;c++){const data=buffer.getChannelData(c),noise=c===0?noiseL:noiseR;for(let i=0;i<frames;i++)data[i]=noise()*((1-i/frames)**2.4);}return buffer;}

export async function renderMusicSurroundAuxEffect({bus,input,sampleRate=48000}={}){const Offline=globalThis.OfflineAudioContext||globalThis.webkitOfflineAudioContext;if(!Offline)throw new Error("CREATIVE_MUSIC_SURROUND_AUX_OFFLINE_CONTEXT_UNAVAILABLE");const frames=Math.max(input?.left?.length||0,input?.right?.length||0);if(!frames)return{left:new Float32Array(0),right:new Float32Array(0),tail_seconds:0};const type=String(bus?.effect_type||"").toLowerCase(),p=bus?.parameters||{};let tail=0;if(type==="reverb")tail=Math.max(.1,Math.min(12,finite(p.decay_seconds,2.2)+finite(p.pre_delay_ms,18)/1000));else if(type==="delay"){const time=Math.max(.01,Math.min(2,finite(p.time_seconds,.375))),feedback=Math.max(0,Math.min(.92,finite(p.feedback,.28)));tail=feedback>0?Math.min(12,time*Math.max(1,Math.ceil(Math.log(.001)/Math.log(feedback)))):time;}else if(type==="compressor")tail=0;else throw new Error(`CREATIVE_MUSIC_SURROUND_AUX_TYPE_UNSUPPORTED:${type}`);const context=new Offline(2,Math.ceil((frames/sampleRate+tail)*sampleRate),sampleRate),buffer=context.createBuffer(2,frames,sampleRate);buffer.copyToChannel(input.left,0);buffer.copyToChannel(input.right,1);const source=context.createBufferSource();source.buffer=buffer;let chain=source;
  if(type==="reverb"){const pre=context.createDelay(.3);pre.delayTime.value=Math.max(0,Math.min(.25,finite(p.pre_delay_ms,18)/1000));const damping=context.createBiquadFilter();damping.type="lowpass";damping.frequency.value=Math.max(1000,Math.min(20000,finite(p.damping_hz,8500)));const conv=context.createConvolver();conv.buffer=createReverbImpulse(context,p.decay_seconds);chain.connect(pre);pre.connect(damping);damping.connect(conv);chain=conv;}
  else if(type==="delay"){const low=context.createBiquadFilter();low.type="highpass";low.frequency.value=Math.max(20,Math.min(1000,finite(p.low_cut_hz,180)));const delay=context.createDelay(2.1);delay.delayTime.value=Math.max(.01,Math.min(2,finite(p.time_seconds,.375)));const high=context.createBiquadFilter();high.type="lowpass";high.frequency.value=Math.max(1000,Math.min(20000,finite(p.high_cut_hz,7000)));const feedback=context.createGain();feedback.gain.value=Math.max(0,Math.min(.92,finite(p.feedback,.28)));chain.connect(low);low.connect(delay);delay.connect(high);high.connect(feedback);feedback.connect(delay);chain=high;}
  else{const high=context.createBiquadFilter();high.type="highpass";high.frequency.value=Math.max(20,Math.min(400,finite(p.high_pass_hz,90)));const compressor=context.createDynamicsCompressor();compressor.threshold.value=Math.max(-60,Math.min(0,finite(p.threshold_db,-30)));compressor.ratio.value=Math.max(1,Math.min(20,finite(p.ratio,8)));compressor.attack.value=Math.max(.0001,Math.min(.2,finite(p.attack_ms,3)/1000));compressor.release.value=Math.max(.01,Math.min(2,finite(p.release_ms,120)/1000));compressor.knee.value=Math.max(0,Math.min(40,finite(p.knee_db,6)));const makeup=context.createGain();makeup.gain.value=dbToGain(finite(p.makeup_db,8));chain.connect(high);high.connect(compressor);compressor.connect(makeup);chain=makeup;}
  const wet=context.createGain();wet.gain.value=bus?.mute===true?0:dbToGain(finite(p.wet_db,type==="reverb"?-3:type==="delay"?-6:-10)+finite(bus?.gain_db,0));chain.connect(wet);wet.connect(context.destination);source.start(0);const rendered=await context.startRendering();return{left:new Float32Array(rendered.getChannelData(0)),right:new Float32Array(rendered.getChannelData(1)),tail_seconds:tail,contract:"AVANTIQO_MUSIC_SURROUND_AUX_EFFECT_V1",effect_type:type};}

export async function renderMusicPreFaderSendSource({session,assetUrls,trackId,expectedDurationSeconds=null,renderWindow=null}={}){return renderMusicTrackPreFaderSendOffline({session,assetUrls,trackId,expectedDurationSeconds,renderWindow});}
