import { encodeMusicAudioBufferWav24, analyseMusicAudioBuffer } from "./MusicWav24Runtime";
import { fingerprintMusicMidiBounce } from "../runtime/CreativeMusicMidiBounceFingerprintRuntime";
import { ensureMusicTempoMap, musicBeatToSeconds } from "../runtime/CreativeMusicTempoMapRuntime";

const CONTRACT = "AVANTIQO_MUSIC_MIDI_OFFLINE_BOUNCE_V3";
function finite(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function clamp(value,min,max,fallback=min){return Math.max(min,Math.min(max,finite(value,fallback)));}
function midiFrequency(pitch){return 440*(2**((clamp(pitch,0,127,69)-69)/12));}
function presetDefinition(preset="studio_keys"){
  const presets={studio_keys:{oscillators:[["triangle",0,.7],["sine",12,.18]],attack:.008,decay:.18,sustain:.58,release:.45,filter:5200},warm_pad:{oscillators:[["sawtooth",0,.35],["triangle",-12,.28],["sine",12,.12]],attack:.35,decay:.7,sustain:.7,release:1.4,filter:2400},mono_bass:{oscillators:[["square",-12,.38],["sine",-12,.55]],attack:.005,decay:.12,sustain:.72,release:.18,filter:1200},bright_lead:{oscillators:[["sawtooth",0,.45],["square",0,.2],["sine",12,.08]],attack:.004,decay:.1,sustain:.68,release:.2,filter:4600}};
  return presets[preset]||presets.studio_keys;
}
function presetForTrack(track={}){const requested=String(track.instrument?.preset_id||track.instrument?.instrument_id||"").toLowerCase();if(["studio_keys","warm_pad","mono_bass","bright_lead"].includes(requested))return requested;const kind=String(track.instrument?.kind||"").toLowerCase();if(kind.includes("bass"))return"mono_bass";if(kind.includes("pad"))return"warm_pad";if(kind.includes("lead"))return"bright_lead";return"studio_keys";}
function gainFromDb(db){return 10**(clamp(db,-60,18,0)/20);}
function eventValueAt(clip,type,beat,fallback){let value=fallback;for(const event of clip.control_events||[]){if(event.type!==type)continue;if(finite(event.beat,0)>beat)break;value=finite(event.value,fallback);}return value;}
function sustainEndBeat(clip,note){let end=finite(note.start_beat,0)+Math.max(.001,finite(note.duration_beats,.25));if(eventValueAt(clip,"sustain",end,0)<64)return end;for(const event of clip.control_events||[]){if(event.type==="sustain"&&finite(event.beat,0)>=end&&finite(event.value,0)<64)return Math.max(end,finite(event.beat,end));}return Math.min(finite(clip.duration_beats,end),end+8);}
function selectedLayer(pad,velocity,counter){const layers=(pad.layers||[]).filter((layer)=>layer.enabled!==false&&velocity>=finite(layer.velocity_min,1)&&velocity<=finite(layer.velocity_max,127));if(!layers.length&&pad.sample_asset_id)return{sample_asset_id:pad.sample_asset_id,gain_db:0,tune_semitones:0};if(!layers.length)return null;const ordered=[...layers].sort((a,b)=>finite(a.round_robin_index,0)-finite(b.round_robin_index,0));return ordered[(pad.round_robin_enabled===false?0:counter%ordered.length)];}
async function decodeSamples(urls={}){const AudioContextClass=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioContextClass)return new Map();const context=new AudioContextClass({latencyHint:"playback"});const result=new Map();try{await Promise.all(Object.entries(urls).map(async([id,url])=>{if(!url)return;const response=await fetch(url,{cache:"no-store"});if(!response.ok)return;const bytes=await response.arrayBuffer();result.set(id,await context.decodeAudioData(bytes.slice(0)));}));}finally{await context.close().catch(()=>{});}return result;}
function reverseBuffer(context,source){const target=context.createBuffer(source.numberOfChannels,source.length,source.sampleRate);for(let c=0;c<source.numberOfChannels;c+=1){const input=source.getChannelData(c),out=target.getChannelData(c);for(let i=0;i<input.length;i+=1)out[i]=input[input.length-1-i];}return target;}

export async function renderMusicMidiTrackToWav24({track,bpm=120,tempoMap=null,timeSignature="4/4",sampler=null,sampleUrls={},sampleRate=48000}={}){
  if(!track?.clips?.length)throw new Error("MUSIC_MIDI_BOUNCE_TRACK_REQUIRED");
  const map=ensureMusicTempoMap(tempoMap||{},{bpm,time_signature:timeSignature});let endBeat=0;for(const clip of track.clips||[])endBeat=Math.max(endBeat,finite(clip.start_beat,0)+finite(clip.duration_beats,0));
  const tail=2;const duration=musicBeatToSeconds(map,endBeat)+tail;const frames=Math.max(1,Math.ceil(duration*sampleRate));
  const Offline=globalThis.OfflineAudioContext||globalThis.webkitOfflineAudioContext;if(!Offline)throw new Error("MUSIC_MIDI_BOUNCE_OFFLINE_AUDIO_UNAVAILABLE");
  const context=new Offline(2,frames,sampleRate);const master=context.createGain();master.gain.value=.7*gainFromDb(track.gain_db||0);const pan=context.createStereoPanner();pan.pan.value=clamp(track.pan,-1,1,0);master.connect(pan).connect(context.destination);
  const samplerKind=["drum_machine","sampler","drum_rack"].includes(String(track.instrument?.kind||"").toLowerCase());
  const fingerprintSession={bpm,tempo_map:map,time_signature:timeSignature,sample_rate:sampleRate};
  const sourceMidiCoreFingerprint=fingerprintMusicMidiBounce({session:fingerprintSession,track,sampler:null});
  const sourceMidiFingerprint=fingerprintMusicMidiBounce({session:fingerprintSession,track,sampler:samplerKind?sampler:null});
  const kit=sampler?.kits?.find((entry)=>entry.id===sampler?.selected_kit_id)||sampler?.kits?.[0]||null;const buffers=samplerKind?await decodeSamples(sampleUrls):new Map();const rr=new Map();let renderedNotes=0,renderedHits=0;
  for(const clip of track.clips||[]){const clipStart=Math.max(0,finite(clip.start_beat,0));for(const note of clip.notes||[]){if(note.muted===true)continue;const beat=clipStart+Math.max(0,finite(note.start_beat,0));const endNoteBeat=clipStart+Math.max(finite(note.start_beat,0)+.001,sustainEndBeat(clip,note));const when=musicBeatToSeconds(map,beat);const noteDuration=Math.max(.001,musicBeatToSeconds(map,endNoteBeat)-when);
      if(samplerKind&&kit){const pad=(kit.pads||[]).find((p)=>Math.round(finite(p.midi_pitch,-1))===Math.round(finite(note.pitch,-2)));if(!pad)continue;const key=pad.id||String(note.pitch);const counter=rr.get(key)||0;const layer=selectedLayer(pad,clamp(note.velocity,1,127,100),counter);rr.set(key,counter+1);if(!layer)continue;let buffer=buffers.get(layer.sample_asset_id);if(!buffer)continue;if(pad.reverse===true)buffer=reverseBuffer(context,buffer);const source=context.createBufferSource();source.buffer=buffer;source.playbackRate.value=2**((clamp(pad.tune_semitones,-24,24,0)+clamp(layer.tune_semitones,-24,24,0))/12);const gain=context.createGain();const velocity=clamp(note.velocity,1,127,100)/127;const depth=clamp(pad.velocity_to_gain,0,1,1);gain.gain.value=Math.max(.0001,gainFromDb(finite(pad.gain_db,0)+finite(layer.gain_db,0))*(1-depth+velocity*depth));const panner=context.createStereoPanner();panner.pan.value=clamp(pad.pan,-1,1,0);source.connect(gain).connect(panner).connect(master);const offset=clamp(pad.start_offset_seconds,0,Math.max(0,buffer.duration-.001),0);const end=pad.end_offset_seconds==null?buffer.duration:clamp(pad.end_offset_seconds,offset+.001,buffer.duration,buffer.duration);const sourceDuration=Math.max(.001,end-offset);source.start(when,offset,sourceDuration);renderedHits+=1;continue;}
      const def=presetDefinition(presetForTrack(track));const gain=context.createGain();const velocity=clamp(note.velocity,1,127,100)/127;const relative=Math.max(0,finite(note.start_beat,0));const expression=clamp(eventValueAt(clip,"expression",relative,127),0,127,127)/127;const modulation=clamp(eventValueAt(clip,"modulation",relative,0),0,127,0)/127;const peak=Math.max(.0002,velocity*expression);const attackEnd=when+def.attack,decayEnd=attackEnd+def.decay,releaseStart=Math.max(decayEnd,when+noteDuration),releaseEnd=releaseStart+def.release;gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(peak,attackEnd);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,peak*def.sustain),decayEnd);gain.gain.setValueAtTime(Math.max(.0002,peak*def.sustain),releaseStart);gain.gain.exponentialRampToValueAtTime(.0001,releaseEnd);const filter=context.createBiquadFilter();filter.type="lowpass";filter.frequency.value=def.filter;filter.connect(gain).connect(master);const bend=clamp(eventValueAt(clip,"pitch_bend",relative,0),-8192,8191,0)/8192*200;for(const [wave,octave,level] of def.oscillators){const osc=context.createOscillator(),og=context.createGain();osc.type=wave;osc.frequency.value=midiFrequency(finite(note.pitch,60)+octave);osc.detune.value=bend;og.gain.value=level;if(modulation>.001){const lfo=context.createOscillator(),depth=context.createGain();lfo.frequency.value=5.2;depth.gain.value=modulation*32;lfo.connect(depth).connect(osc.detune);lfo.start(when);lfo.stop(releaseEnd+.02);}osc.connect(og).connect(filter);osc.start(when);osc.stop(releaseEnd+.02);}renderedNotes+=1;}}
  const audio=await context.startRendering();const levels=analyseMusicAudioBuffer(audio);const wav=encodeMusicAudioBufferWav24(audio);return{contract:CONTRACT,wav,levels,duration_seconds:wav.duration_seconds,sample_rate:wav.sample_rate,channels:wav.channels,bit_depth:24,rendered_note_count:renderedNotes,rendered_sampler_hit_count:renderedHits,tempo_map_contract:map.contract,tempo_map_aware:true,source_midi_core_fingerprint:sourceMidiCoreFingerprint,source_midi_fingerprint:sourceMidiFingerprint,source_midi_preserved:true,provider_job_submitted:false,release_master:false};
}

export const MusicMidiBounceEngine={contract:CONTRACT,renderTrack:renderMusicMidiTrackToWav24};
