import { musicSpatialAutomationValueAt } from "./MusicSpatialMixMathRuntime.js";

const CONTRACT="AVANTIQO_MUSIC_OBJECT_MOTION_ACOUSTICS_V1";
function finite(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function clamp(v,min,max,f=0){return Math.max(min,Math.min(max,finite(v,f)));}
function sampleLinear(data,index){if(index<0||index>=data.length-1)return index>=0&&index<data.length?finite(data[Math.floor(index)],0):0;const i=Math.floor(index),f=index-i;return finite(data[i],0)*(1-f)+finite(data[i+1],0)*f;}
function distanceLane(lanes=[]){return (lanes||[]).find(lane=>lane.enabled!==false&&lane.parameter==="spatial:distance_meters")||null;}
function distanceAt(lane,time,fallback){return Math.max(.1,musicSpatialAutomationValueAt(lane,time,fallback));}
function earlyReflections(left,right,sampleRate,immersive){const amount=clamp(immersive?.reflection_amount_percent,0,100,25)/100,room=clamp(immersive?.room_size,0,1,.35),frames=Math.max(left.length,right.length),l=new Float32Array(frames),r=new Float32Array(frames);if(immersive?.reflections_enabled===false||amount<=0)return{left:l,right:r,enabled:false,taps:[]};const taps=[{delay:.009+.021*room,gain:.5},{delay:.021+.047*room,gain:.3},{delay:.037+.083*room,gain:.2}].map((tap,index)=>({...tap,frames:Math.max(1,Math.round(tap.delay*sampleRate)),crossfeed:index===1}));for(const tap of taps){const gain=amount*tap.gain;for(let i=tap.frames;i<frames;i++){const source=i-tap.frames;if(tap.crossfeed){l[i]+=finite(right[source],0)*gain;r[i]+=finite(left[source],0)*gain;}else{l[i]+=finite(left[source],0)*gain;r[i]+=finite(right[source],0)*gain;}}}return{left:l,right:r,enabled:true,taps:taps.map(t=>({delay_seconds:Number(t.delay.toFixed(6)),gain:Number((amount*t.gain).toFixed(6)),crossfeed:t.crossfeed}))};}
export function applyMusicObjectMotionAcoustics({left,right=null,sample_rate=48000,spatial={},automation_lanes=[],timeline_offset_seconds=0}={}){const l=left||new Float32Array(0),r=right||l,frames=Math.max(l.length,r.length),rate=Math.max(1000,Math.round(finite(sample_rate,48000))),immersive=spatial.immersive||{},lane=distanceLane(automation_lanes),doppler=immersive.doppler_enabled===true,speed=Math.max(250,finite(immersive.speed_of_sound_mps,343)),directL=new Float32Array(frames),directR=new Float32Array(frames),baseDistance=Math.max(.1,finite(spatial.distance_meters,1));let maxDelay=0,minDistance=Infinity,maxDistance=0;for(let i=0;i<frames;i++){const absoluteTime=Math.max(0,finite(timeline_offset_seconds,0)+i/rate),distance=distanceAt(lane,absoluteTime,baseDistance);minDistance=Math.min(minDistance,distance);maxDistance=Math.max(maxDistance,distance);const delaySeconds=doppler?distance/speed:0;maxDelay=Math.max(maxDelay,delaySeconds);const sourceIndex=i-delaySeconds*rate;directL[i]=sampleLinear(l,sourceIndex);directR[i]=sampleLinear(r,sourceIndex);}const reflections=earlyReflections(directL,directR,rate,immersive);return{contract:CONTRACT,direct:{left:directL,right:directR},reflections,metadata:{doppler_applied:doppler,propagation_delay_mode:doppler?"DISTANCE_OVER_SPEED_OF_SOUND":"BYPASSED",speed_of_sound_mps:speed,min_distance_meters:Number((Number.isFinite(minDistance)?minDistance:baseDistance).toFixed(4)),max_distance_meters:Number(maxDistance.toFixed(4)),max_propagation_delay_seconds:Number(maxDelay.toFixed(6)),distance_automation_applied:Boolean(lane),reflections_applied:reflections.enabled,reflection_taps:reflections.taps,source_audio_rewritten:false,output_length_preserved:true}};}
export const MusicObjectMotionAcousticsRuntime=Object.freeze({contract:CONTRACT,apply:applyMusicObjectMotionAcoustics});
