import { imageStudioAdjustmentPreviewStyle } from "./CreativeImageStudioAdjustmentRuntime.js";

const num=(value,fallback)=>Number.isFinite(Number(value))?Number(value):fallback;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const BLENDS=Object.freeze({normal:{css:"normal",sharp:"over"},multiply:{css:"multiply",sharp:"multiply"},screen:{css:"screen",sharp:"screen"},overlay:{css:"overlay",sharp:"overlay"},darken:{css:"darken",sharp:"darken"},lighten:{css:"lighten",sharp:"lighten"},difference:{css:"difference",sharp:"difference"},exclusion:{css:"exclusion",sharp:"exclusion"}});
export const IMAGE_STUDIO_BLEND_MODES=Object.freeze(Object.keys(BLENDS));
export function normalizeImageStudioEffects(style={}){const effects=style.effects&&typeof style.effects==="object"?style.effects:{};const blend=BLENDS[String(style.blend_mode||"normal").toLowerCase()]||BLENDS.normal;return{brightness:clamp(num(effects.brightness,1),0,2),contrast:clamp(num(effects.contrast,1),0.25,2),saturation:clamp(num(effects.saturation,1),0,2),hue:clamp(num(effects.hue,0),-180,180),grayscale:clamp(num(effects.grayscale,0),0,1),blur:clamp(num(effects.blur,0),0,40),opacity:clamp(num(style.opacity,1),0,1),blend_mode:String(style.blend_mode||"normal").toLowerCase(),css_blend_mode:blend.css,sharp_blend_mode:blend.sharp};}
export function imageStudioPreviewEffectStyle(style={}){const e=normalizeImageStudioEffects(style);const adjustments=imageStudioAdjustmentPreviewStyle(style);const filters=[adjustments.filter,`brightness(${e.brightness})`,`contrast(${e.contrast})`,`saturate(${e.saturation})`,`hue-rotate(${e.hue}deg)`,`grayscale(${e.grayscale})`].filter(Boolean);if(e.blur>0)filters.push(`blur(${e.blur}px)`);return{opacity:e.opacity,mixBlendMode:e.css_blend_mode,filter:filters.join(" ")};}
export const CreativeImageStudioEffectsRuntime=Object.freeze({contract:"CREATIVE_IMAGE_STUDIO_EFFECTS_V2",blend_modes:IMAGE_STUDIO_BLEND_MODES,normalize:normalizeImageStudioEffects,previewStyle:imageStudioPreviewEffectStyle});
export default CreativeImageStudioEffectsRuntime;
