import crypto from "node:crypto";

export const AVANTIQO_RENDER_FARM_CONTRACT="AVANTIQO_RENDER_FARM_V1";
function text(v){return String(v??"").trim();}
function list(v){return Array.isArray(v)?v.filter(Boolean):[];}
function finite(v,f=0,min=-Infinity,max=Infinity){const n=Number(v);return Math.max(min,Math.min(max,Number.isFinite(n)?n:f));}
function integer(v,f,min=1,max=1e9){return Math.max(min,Math.min(max,Math.round(finite(v,f))));}
function stable(v){if(Array.isArray(v))return v.map(stable);if(!v||typeof v!=="object")return v;return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");}
function chunks(start,end,size){const out=[];let i=start;while(i<=end){const last=Math.min(end,i+size-1);out.push({frame_start:i,frame_end:last,frame_count:last-i+1});i=last+1;}return out;}
function workerScore(worker,job){let score=0;if(worker.enabled===false)return-Infinity;if(job.engine&&list(worker.engines).includes(job.engine))score+=100;if(job.gpu_required&&worker.gpu===true)score+=60;if(job.preferred_gpu&&text(worker.gpu_model).toUpperCase().includes(text(job.preferred_gpu).toUpperCase()))score+=40;if(worker.warm===true)score+=35;if(worker.cache_keys?.includes(job.cache_key))score+=25;score+=Math.max(0,20-finite(worker.cost_weight,10,0,100));score+=Math.min(20,finite(worker.performance_weight,0,0,100));return score;}
export function planRenderFarm({job={},workers=[],completed_chunks=[]}={}){const j={job_id:text(job.job_id||job.id||`render-${Date.now()}`),engine:text(job.engine||"CYCLES").toUpperCase(),frame_start:integer(job.frame_start,1),frame_end:integer(job.frame_end,1),chunk_size:integer(job.chunk_size,8,1,1000),scene_hash:text(job.scene_hash),material_library_hash:text(job.material_library_hash),cache_namespace:text(job.cache_namespace||"render"),gpu_required:job.gpu_required!==false,preferred_gpu:text(job.preferred_gpu),max_retries:integer(job.max_retries,2,0,10)};if(j.frame_end<j.frame_start)throw new Error("RENDER_FARM_FRAME_RANGE_INVALID");j.cache_key=hash({engine:j.engine,scene_hash:j.scene_hash,material_library_hash:j.material_library_hash,cache_namespace:j.cache_namespace});const done=new Set(list(completed_chunks).map(c=>`${c.frame_start}:${c.frame_end}:${text(c.checksum)}`));const assignments=[];const blocked=[];for(const chunk of chunks(j.frame_start,j.frame_end,j.chunk_size)){const identity=hash({job:j.job_id,cache_key:j.cache_key,...chunk});const already=list(completed_chunks).find(c=>c.frame_start===chunk.frame_start&&c.frame_end===chunk.frame_end&&text(c.checksum));if(already){assignments.push({...chunk,chunk_id:identity,status:"REUSED",worker_id:null,checksum:text(already.checksum),retry_count:integer(already.retry_count,0,0,j.max_retries)});continue;}const ranked=list(workers).map(w=>({...w,score:workerScore(w,{...j,...chunk})})).filter(w=>Number.isFinite(w.score)).sort((a,b)=>b.score-a.score);if(!ranked.length){blocked.push({...chunk,chunk_id:identity,reason:"NO_RENDER_WORKER_AVAILABLE"});continue;}assignments.push({...chunk,chunk_id:identity,status:"READY",worker_id:text(ranked[0].worker_id||ranked[0].id),worker_score:ranked[0].score,retry_count:0});}const body={contract:AVANTIQO_RENDER_FARM_CONTRACT,job:j,assignments,blocked,policy:{retry_failed_chunks_only:true,reuse_verified_chunks:true,warm_worker_affinity:true,cache_affinity:true,frame_checksums_required:true,corrupt_or_missing_frame_fails_chunk:true,whole_job_retry_forbidden:true,cost_aware_worker_selection:true}};return{...body,status:blocked.length?"BLOCKED":"READY",plan_hash:hash(body)};}
export function verifyChunkSet({plan,results=[]}={}){if(plan?.contract!==AVANTIQO_RENDER_FARM_CONTRACT)throw new Error("RENDER_FARM_PLAN_REQUIRED");const map=new Map(list(results).map(r=>[text(r.chunk_id),r]));const failures=[];const verified=[];for(const a of plan.assignments){if(a.status==="REUSED"){verified.push(a);continue;}const r=map.get(a.chunk_id);if(!r)failures.push({chunk_id:a.chunk_id,reason:"CHUNK_RESULT_MISSING"});else if(!text(r.checksum))failures.push({chunk_id:a.chunk_id,reason:"CHUNK_CHECKSUM_REQUIRED"});else if(integer(r.frame_count,0,0)!==a.frame_count)failures.push({chunk_id:a.chunk_id,reason:"CHUNK_FRAME_COUNT_MISMATCH"});else verified.push({...a,status:"VERIFIED",checksum:text(r.checksum),bytes:finite(r.bytes,0,0)});}return{contract:"AVANTIQO_RENDER_FARM_VERIFICATION_V1",passed:failures.length===0,failures,verified,total_frames:verified.reduce((s,x)=>s+x.frame_count,0),verification_hash:failures.length?null:hash(verified.map(v=>({chunk_id:v.chunk_id,checksum:v.checksum,frame_count:v.frame_count})))};}
export const CreativeRenderFarmRuntime=Object.freeze({contract:AVANTIQO_RENDER_FARM_CONTRACT,plan:planRenderFarm,verify:verifyChunkSet});
