export const CREATIVE_VIDEO_PRODUCTION_CERTIFICATION_CONTRACT="CREATIVE_VIDEO_PRODUCTION_CERTIFICATION_V1";
const IMPLEMENTED=Object.freeze(new Set(["ai.video.generate"]));
const DEFAULT_CERTIFIED=Object.freeze(new Set(["ai.video.generate"]));
const LOCAL_GENERATION_RESOLUTION="608x352";
function text(v){return String(v??"").trim();}
function configured(){const raw=text(process.env.AVANTIQO_VIDEO_CERTIFIED_CAPABILITIES);if(!raw)return new Set(DEFAULT_CERTIFIED);return new Set(raw.split(',').map(x=>x.trim()).filter(x=>IMPLEMENTED.has(x)));}
function profile(capability){if(capability!=="ai.video.generate")return null;return{generation_resolution:LOCAL_GENERATION_RESOLUTION,delivery_resolution:LOCAL_GENERATION_RESOLUTION,engine:"LTX-2.5 local Node01",temporal_delivery:false,hero_native_4k_default:false};}
export function videoCapabilityCertification(capability){const c=text(capability).toLowerCase();const implemented=IMPLEMENTED.has(c);const certified=implemented&&configured().has(c);return{contract:CREATIVE_VIDEO_PRODUCTION_CERTIFICATION_CONTRACT,capability:c,implemented,certified,status:!implemented?"UNSUPPORTED":certified?"PRODUCTION_CERTIFIED":"CERTIFICATION_REQUIRED",execution_scope:certified?"PRODUCTION_LOCAL":"BENCHMARK_REVIEW_PREVIEW",benchmark_only:!certified,production_certified:certified,profile:implemented?profile(c):null,policy:{capability_level_certification:true,blanket_engine_certification_forbidden:true,unsupported_capability_must_block:true,paid_execution_requires_separate_authority:true,local_only_execution:true,unimplemented_delivery_upscale_must_block:true}};}
export const CreativeVideoProductionCertificationRuntime=Object.freeze({contract:CREATIVE_VIDEO_PRODUCTION_CERTIFICATION_CONTRACT,implemented_capabilities:Object.freeze([...IMPLEMENTED]),status:videoCapabilityCertification});
